### ISSUE TITLE
Tribler goes to foreground when Magnet:: is clicked and download is started.

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1002]
Now it looks like nothing is happening, other clients also pop to the foreground.

**Comment by LipuFei** [comment]
I have just tried the functionality a few times with several different magnet links, turns out that some of them may not be parsed correctly and they don't have infohash, so it raises an exception as follows:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Main/tribler_main.py", line 1079, in start_asked_download
    self.frame.startDownloadFromMagnet(torrentfilename)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Main/vwxGUI/MainFrame.py", line 424, in startDownloadFromMagnet
    tdef = TorrentDefNoMetainfo(infohash, name, url=url)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/TorrentDef.py", line 1110, in __init__
    assert isinstance(infohash, str), "INFOHASH has invalid type: %s" % type(infohash)
AssertionError: INFOHASH has invalid type: <type 'NoneType'>
```

@whirm I will add a `try`-`except` there and show an error dialog if something goes wrong so that users can know what is happening.

**Comment by whirm** [comment]
@LipuFei great
