### ISSUE TITLE
M2Crypto.EVP.EVPError: bad decrypt

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1005]
While running Next for a while, a few of these came up.
commit db988cddf3b0eed2f5e2690352eaa68a496089c9
Author: Lipu Fei <lipu.fei815@gmail.com>
Date:   Tue Dec 16 18:50:35 2014 +0100
```
ERROR   1418874500.11       community:617   Could not remove relay 3670090604 too old
ERROR   1418874620.11       community:617   Could not remove relay 1898028518 no activity
ERROR   1418874698.25       community:1046  Got destroy from {192.168.1.3:7759 98.243.147.25:7759} for circuit 818596000
ERROR   1418874751.43       community:853   Don't know how to decrypt incoming message for circuit_id 3227387793
ERROR   1418874785.13       community:617   Could not remove relay 3615426253 too old
ERROR   1418874800.13       community:617   Could not remove relay 72218982 too old
ERROR   1418874815.11       community:617   Could not remove relay 1469895911 no activity
ERROR   1418874916.56       community:617   Could not remove relay 364903034 too old
ERROR   1418874942.36             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 990, in on_data
    if not self.relay_packet(circuit_id, message_type, packet):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 728, in relay_packet
    encrypted = self.crypto_relay(circuit_id, encrypted)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 1148, in crypto_relay
    return self.crypto.decrypt_str(self.relay_session_keys[circuit_id][direction], content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto.py", line 46, in decrypt_str
    return aes_decrypt_str(key, content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/privatesemantic/crypto/optional_crypto.py", line 70, in aes_decrypt_str
    return ret + cipher.final()
  File "/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py", line 128, in final
    return m2.cipher_final(self.ctx)
M2Crypto.EVP.EVPError: bad decrypt

Unhandled Error
```

**Comment by synctext** [comment]
Not seen it for a while. Good

**Comment by synctext** [comment]
Shoot, still in next branch.
commit a717dc8ce2a3c36c2a9b6f0cd28478976fc9d14d
```
ERROR   1420615743.19       community:618   Could not remove relay 1205035884 no activity
ERROR   1420615743.19       community:618   Could not remove relay 2973658054 no activity
ERROR   1420615758.01        dispersy:1725  exception during handle_callback for cell
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 852, in on_cell
    encrypted = self.crypto_in(circuit_id, encrypted)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 1141, in crypto_in
    return self.crypto.decrypt_str(self.relay_session_keys[circuit_id][EXIT_NODE], content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto/tunnelcrypto.py", line 91, in decrypt_str
    return aes_decrypt_str(key, content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto/cryptowrapper.py", line 40, in aes_decrypt_str
    return ret + cipher.final()
  File "/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py", line 128, in final
    return m2.cipher_final(self.ctx)
EVPError: bad decrypt
ERROR   1420615758.02        dispersy:1725  exception during handle_callback for cell
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 852, in on_cell
    encrypted = self.crypto_in(circuit_id, encrypted)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 1141, in crypto_in
    return self.crypto.decrypt_str(self.relay_session_keys[circuit_id][EXIT_NODE], content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto/tunnelcrypto.py", line 91, in decrypt_str
    return aes_decrypt_str(key, content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto/cryptowrapper.py", line 40, in aes_decrypt_str
    return ret + cipher.final()
  File "/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py", line 128, in final
    return m2.cipher_final(self.ctx)
EVPError: bad decrypt
ERROR   1420615758.02        dispersy:1725  exception during handle_callback for cell
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 852, in on_cell
    encrypted = self.crypto_in(circuit_id, encrypted)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 1141, in crypto_in
    return self.crypto.decrypt_str(self.relay_session_keys[circuit_id][EXIT_NODE], content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto/tunnelcrypto.py", line 91, in decrypt_str
    return aes_decrypt_str(key, content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto/cryptowrapper.py", line 40, in aes_decrypt_str
    return ret + cipher.final()
  File "/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py", line 128, in final
    return m2.cipher_final(self.ctx)
EVPError: bad decrypt
ERROR   1420615758.02        dispersy:1725  exception during handle_callback for cell
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 852, in on_cell
    encrypted = self.crypto_in(circuit_id, encrypted)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 1141, in crypto_in
    return self.crypto.decrypt_str(self.relay_session_keys[circuit_id][EXIT_NODE], content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto/tunnelcrypto.py", line 91, in decrypt_str
    return aes_decrypt_str(key, content)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/crypto/cryptowrapper.py", line 40, in aes_decrypt_str
    return ret + cipher.final()
  File "/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py", line 128, in final
    return m2.cipher_final(self.ctx)
EVPError: bad decrypt
ERROR   1420615785.66       community:1047  Got destroy from {192.168.1.40:7759 81.38.210.244:7759} for circuit 1857042457
ERROR   1420615785.78       community:1047  Got destroy from {192.168.1.40:7759 81.38.210.244:7759} for circuit 114803607
ERROR   1420615811.38       community:854   Don't know how to decrypt incoming message for circuit_id 3390137565
ERRO
```

**Comment by whirm** [comment]
Let's wait for the whole crypto overhaul to be finished before dealing with these bugs as they will probably not be there anymore. 
Depends on https://github.com/Tribler/tribler/issues/1066

**Comment by rjruigrok** [comment]
This bug can be closed.

**Comment by whirm** [comment]
@rjruigrok don't you have permissions to close them yourself?

**Comment by rjruigrok** [comment]
Nope.
3 months ago I had those permissions, but now they magically disappeared. :)

**Comment by whirm** [comment]
Oh well...
