### ISSUE TITLE
Tribler 6.4.0 dont start using libtorrent-rasterbar-0.16.19

### ISSUE THREAD

**Issue by deibiz** [Tribler/tribler#1082]
Using GNU/Linux 32bit
Python 2.7.5
libtorrent-rasterbar 0.16.19
tribler 6.4.0

```
Tribler version: 6.4.0-GIT
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 208, in __init__
    s.start()
  File "/usr/share/tribler/Tribler/Core/Session.py", line 465, in start
    self.lm.register(self, self.sesslock)
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 178, in register
    self.init()
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 222, in init
    self.ltmgr = LibtorrentMgr(self.session, ignore_singleton=self.session.ignore_singleton)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 41, in __init__
    main_ltsession = self.get_session()
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 147, in get_session
    self.ltsessions[hops] = self.create_session(hops)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 124, in create_session
    ltsession.listen_on(listen_port, listen_port + 10)
RuntimeError: Address family not supported by protocol
```

Regards.

**Comment by lfdversluis** [comment]
@whirm Is this still relevant since we use arvid's libtorrent 1.0.8 ?

**Comment by whirm** [comment]
We should see what Debian/Ubuntu is shipping in current LTS and latest non-LTS release.

**Comment by devos50** [comment]
It seems that Ubuntu has libtorrent-rasterbar 0.16.11 in their repo (https://apps.ubuntu.com/cat/applications/python-libtorrent/) which is a several years old version.

Debian seems to ship version 1.0.7 (https://packages.debian.org/sid/python-libtorrent).

**Comment by whirm** [comment]
@devos50 you need to check all versions :

http://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=python-libtorrent

https://packages.debian.org/search?keywords=python-libtorrent&searchon=names&suite=all&section=all

**Comment by devos50** [comment]
We support libtorrent 0.16.18 and upwards. Also, I haven't seen this issue recently so I will close it.
