### ISSUE TITLE
pymdht MINITWISTED crash

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1102]
@whirm Let's temporarily put this here.

Got this with the `next` f0b494a:
```
CRITICAL 1419946607.11     minitwisted:105   MINITWISTED CRASHED
ERROR   1419946607.12     minitwisted:106   MINITWISTED CRASHED
Traceback (most recent call last):
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 103, in run2
    self.run_one_step()
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 179, in run_one_step
    datagram_received)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/controller.py", line 291, in on_datagram_received
    ) = related_query.lookup_obj.on_error_received(msg, addr)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/DecentralizedTracking/pymdht/plugins/lookup_a4.py", line 255, in on_error_received
    logger.debug('Got error from node addr: %r' % node_addr)
TypeError: not all arguments converted during string formatting
MINITWISTED CRASHED (see logs)
```

The pymdht log file contains the following information:
```
2014-12-30 14:36:21,532 CRITICAL minitwisted.py:100 - run2()
run

2014-12-30 14:36:47,113 CRITICAL minitwisted.py:105 - run2()
MINITWISTED CRASHED

2014-12-30 14:36:47,122 ERROR minitwisted.py:106 - run2()
MINITWISTED CRASHED
Traceback (most recent call last):
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 103, in run2
    self.run_one_step()
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 179, in run_one_step
    datagram_received)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/controller.py", line 291, in on_datagram_received
    ) = related_query.lookup_obj.on_error_received(msg, addr)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/DecentralizedTracking/pymdht/plugins/lookup_a4.py", line 255, in on_error_received
    logger.debug('Got error from node addr: %r' % node_addr)
TypeError: not all arguments converted during string formatting
```

**Comment by whirm** [comment]
@LipuFei I see many of the tunnel test failures say that pymdht crashed. I guess switching to your branch will help. Let's do it. :)

**Comment by rauljim** [comment]
Hi guys!
I've been away. I'll take a look asap.
