### ISSUE TITLE
Twisted UDP: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1119]
Error after running V6.3.0 for almost 3 weeks on Ubuntu.

```
ERROR   1418994912.63       community:617   Could not remove relay 2492896422 no activity
ERROR   1418994919.26       community:1046  Got destroy from {192.168.0.199:7759 77.250.134.32:7759} for circuit 3731157480
ERROR   1418994952.49       community:617   Could not remove relay 1119133122 no activity
ERROR   1418994975.17       community:1046  Got destroy from {67.48.121.52:7759} for circuit 1143361267
ERROR   1418994977.33       community:1112  Dropping data packets while EXITing
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 1110, in exit_data
    self.exit_sockets[circuit_id].sendto(data, destination)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 198, in sendto
    self.transport.write(data, destination)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 271, in write
    return self.socket.sendto(datagram, addr)
error: [Errno 11] Resource temporarily unavailable
ERROR   1418994977.34       community:1112  Dropping data packets while EXITing
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 1110, in exit_data
    self.exit_sockets[circuit_id].sendto(data, destination)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 198, in sendto
    self.transport.write(data, destination)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 271, in write
    return self.socket.sendto(datagram, addr)
error: [Errno 11] Resource temporarily unavailable
ERROR   1418994977.35       community:1112  Dropping data packets while EXITing
```

**Comment by whirm** [comment]
This will be fixed when we get to refactor the Session object. See: https://github.com/Tribler/tribler/issues/1070

**Comment by qstokkink** [comment]
This code no longer exists, closing.
