### ISSUE TITLE
M2Crypto.EVP.EVPError: wrong final block length

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1120]
Got this after running V6.4.0 for almost 3 weeks on Ubuntu.
```
ERROR   1419015047.58       community:617   Could not remove relay 1359238870 no activity
ERROR   1419015047.58       community:617   Could not remove relay 1023486889 no activity
ERROR   1419015057.59       community:617   Could not remove relay 2339736708 no activity
ERROR   1419015068.58       community:1046  Got destroy from {192.168.1.40:7759 62.163.91.225:7759} for circuit 2409111674
ERROR   1419015068.58       community:1052  Got an exit socket 2409111674 ('62.163.91.225', 7759)
ERROR   1419015091.53             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 994, in on_data
    encrypted = self.crypto_in(circuit_id, encrypted, is_data=True)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 1134, in crypto_in
    content = self.crypto.decrypt_str(hop.session_keys[ORIGINATOR], content)
  File "/usr/share/tribler/Tribler/community/tunnel/crypto.py", line 46, in decrypt_str
    return aes_decrypt_str(key, content)
  File "/usr/share/tribler/Tribler/community/privatesemantic/crypto/optional_crypto.py", line 70, in aes_decrypt_str
    return ret + cipher.final()
  File "/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py", line 128, in final
    return m2.cipher_final(self.ctx)
M2Crypto.EVP.EVPError: wrong final block length

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 994, in on_data
    encrypted = self.crypto_in(circuit_id, encrypted, is_data=True)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 1134, in crypto_in
    content = self.crypto.decrypt_str(hop.session_keys[ORIGINATOR], content)
  File "/usr/share/tribler/Tribler/community/tunnel/crypto.py", line 46, in decrypt_str
    return aes_decrypt_str(key, content)
  File "/usr/share/tribler/Tribler/community/privatesemantic/crypto/optional_crypto.py", line 70, in aes_decrypt_str
    return ret + cipher.final()
  File "/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py", line 128, in final
    return m2.cipher_final(self.ctx)
M2Crypto.EVP.EVPError: wrong final block length
ERROR   1419015096.74       community:1046  Got destroy from {10.0.1.115:7759 209.134.44.60:39158} for circuit 1300111165
ERROR   1419015096.74       community:1052  Got an exit socket 1300111165 ('209.134.44.60', 39158)
ERROR   1419015097.58       community:617   Could not remove relay 1537398209 no activity
ERROR   1419015097.58       community:617   Could not remove relay 3927068394 no activity
ERROR   1419015107.59       community:617   Could not remove relay 2460521578 no activity
```

**Comment by whirm** [comment]
Let's wait for the whole crypto overhaul to be finished before dealing with these bugs as they will probably not be there anymore. 
Depends on https://github.com/Tribler/tribler/issues/1066

**Comment by rjruigrok** [comment]
This one too, can be closed.
