### ISSUE TITLE
twisted UDP: Temporary failure in name resolution

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1121]
Got this after running V6.4.0 for almost 3 weeks on Ubuntu.

```
ERROR   1419017052.59       community:617   Could not remove relay 508677101 no activity
ERROR   1419017077.58       community:617   Could not remove relay 190483686 too old
ERROR   1419017097.58       community:617   Could not remove relay 4115884542 no activity
ERROR   1419017156.54       community:1112  Dropping data packets while EXITing
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 1110, in exit_data
    self.exit_sockets[circuit_id].sendto(data, destination)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 198, in sendto
    self.transport.write(data, destination)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 271, in write
    return self.socket.sendto(datagram, addr)
gaierror: [Errno -3] Temporary failure in name resolution
ERROR   1419017156.74       community:617   Could not remove relay 68156073 no activity
ERROR   1419017156.74       community:617   Could not remove relay 2499218606 no activity
ERROR   1419017156.74       community:617   Could not remove relay 3033804107 no activity
ERROR   1419017156.74       community:617   Could not remove relay 2934873040 no activity
```

**Comment by whirm** [comment]
This will be fixed when we get to refactor the Session class. See: https://github.com/Tribler/tribler/issues/1070

**Comment by qstokkink** [comment]
This code no longer exists, closing.
