### ISSUE TITLE
Twisted UDP: Name or service not known

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1122]
Got this after running V6.4.0 for almost 3 weeks on Ubuntu.

```
ERROR   1419024427.60       community:617   Could not remove relay 3874014936 no activity
ERROR   1419024442.59       community:617   Could not remove relay 899502459 no activity
ERROR   1419024449.28       community:1112  Dropping data packets while EXITing
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 1110, in exit_data
    self.exit_sockets[circuit_id].sendto(data, destination)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 198, in sendto
    self.transport.write(data, destination)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 271, in write
    return self.socket.sendto(datagram, addr)
gaierror: [Errno -2] Name or service not known
ERROR   1419024451.11       community:1046  Got destroy from {72.208.217.58:42365} for circuit 55503196
ERROR   1419024482.59       community:617   Could not remove relay 581451426 no activity
ERROR   1419024502.59       community:617   Could not remove relay 3085621069 no activity
ERROR   1419024507.59       community:617   Could not remove relay 1627471323 no activity
ERROR   1419024542.49       community:617   Could not remove relay 32394802 no activity
```

**Comment by whirm** [comment]
This will be fixed when we get to refactor the Session class. See: https://github.com/Tribler/tribler/issues/1070

**Comment by qstokkink** [comment]
This code no longer exists, closing.

**Comment by qstokkink** [comment]
This code no longer exists, closing.
