### ISSUE TITLE
Dispersy: assert self.is_valid_address(sock_addr), sock_addr

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1130]
Appears on my NATted Ubuntu box, next branch.
commit a717dc8ce2a3c36c2a9b6f0cd28478976fc9d14d
```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/endpoint.py", line 184, in dispersythread_data_came_in
    timestamp)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1457, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 2036, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 2107, in _on_batch_cache
    self.on_messages(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 2219, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1695, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 183, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/discovery/community.py", line 478, in on_similarity_request
    message.payload.connection_type, message.candidate)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 1509, in create_or_update_walkcandidate
    lan_address, wan_address = self._dispersy.estimate_lan_and_wan_addresses(sock_addr, lan_address, wan_address)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1617, in estimate_lan_and_wan_addresses
    assert self.is_valid_address(sock_addr), sock_addr
exceptions.AssertionError: ('50.136.176.107', 0)
ERROR   1420623764.57             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/endpoint.py", line 184, in dispersythread_data_came_in
    timestamp)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1457, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 2036, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 2107, in _on_batch_cache
    self.on_messages(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 2219, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1695, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 183, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/discovery/community.py", line 607, in on_intro_request
    self._disp_intro_handler(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 2472, in on_introduction_request
    candidate = self.create_or_update_walkcandidate(message.candidate.sock_addr, message.payload.source_lan_address, message.payload.source_wan_address, message.candidate.tunnel, message.payload.connection_type, message.candidate)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 1509, in create_or_update_walkcandidate
    lan_address, wan_address = self._dispersy.estimate_lan_and_wan_addresses(sock_addr, lan_address, wan_address)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1617, in estimate_lan_and_wan_addresses
    assert self.is_valid_address(sock_addr), sock_addr
exceptions.AssertionError: ('50.136.176.107', 0)
```

**Comment by NielsZeilemaker** [comment]
It's an invalid sock_addr which is set when the candidate was created. I would remove the is_address method in candidate.py file, and replace call to it by this is_valid_address.

However, this will cause the LoopbackCandidate to fail. I would simply modify the LoopbackCandidate to not call the super constructor, but setting the attributes manually.

**Comment by whirm** [comment]
Sent a PR to dispersy to address this: https://github.com/Tribler/dispersy/pull/392
