### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'on_introduction_response'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1131]
Apprears in latest next branch, from 6jan
commit a717dc8ce2a3c36c2a9b6f0cd28478976fc9d14d
```
RROR   1420619868.19       community:618   Could not remove relay 53464471 too old
ERROR   1420619888.19       community:618   Could not remove relay 2894346308 too old
ERROR   1420619892.74        dispersy:1725  exception during handle_callback for dispersy-introduction-response
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/community.py", line 2613, in on_introduction_response
    cache.on_introduction_response()
AttributeError: 'NoneType' object has no attribute 'on_introduction_response'
ERROR   1420619898.19       community:618   Could not remove relay 833233907 no activity
ERROR   1420619953.19       community:618   Could not remove relay 2558044117 no activity
```

**Comment by NielsZeilemaker** [comment]
This is a duplicate of this one: https://github.com/Tribler/dispersy/issues/383
