### ISSUE TITLE
Debian sid does not build with currently documented package dependencies to install

### ISSUE THREAD

**Issue by omac777** [Tribler/tribler#1176]
Problem:

tribler$ ./Tribler/Main/Build/update_version_from_git.py
Traceback (most recent call last):
  File "./Tribler/Main/Build/update_version_from_git.py", line 41, in <module>
    runCommand('dch -v {} New upstream release.'.format(version_id).split())
  File "./Tribler/Main/Build/update_version_from_git.py", line 14, in runCommand
    p = Popen(cmd, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Solution:
devscripts package was not documented as package dependency.  Install devscripts:
apt-get install devscripts
./Tribler/Main/Build/update_version_from_git.py
debuild -i -us -uc -b

The end result .deb file will be in `../tribler_6.4.2-124-gabfcf63_all.deb'.

**Comment by whirm** [comment]
Good catch, thanks!
