### ISSUE TITLE
RequestCache KeyError in SearchCommunity

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1204]
The problem is in current `devel`:
```
ERROR   1423136054.27        dispersy:1724  exception during handle_callback for torrent-collect-response
Traceback (most recent call last):
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/community/search/community.py", line 489, in on_torrent_collect_response
    self.request_cache.pop(u"ping", message.payload.identifier)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/dispersy/requestcache.py", line 196, in pop
    cache = self._identifiers.pop(identifier)
KeyError: u'ping:25657'
ERROR   1423136054.29        dispersy:1724  exception during handle_callback for torrent-collect-response
Traceback (most recent call last):
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/community/search/community.py", line 489, in on_torrent_collect_response
    self.request_cache.pop(u"ping", message.payload.identifier)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/dispersy/requestcache.py", line 196, in pop
    cache = self._identifiers.pop(identifier)
KeyError: u'ping:41426'
```

**Comment by rjruigrok** [comment]
Probably related to this error:

<pre>
 CRITICAL 1423226122.23     minitwisted:105   MINITWISTED CRASHED
 ERROR   1423226122.23     minitwisted:106   MINITWISTED CRASHED 
 Traceback (most recent call last):
   File "/home/rob/git/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 103, in run2
    self.run_one_step()
  File "/home/rob/git/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 179, in run_one_step
    datagram_received)
  File "/home/rob/git/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/controller.py", line 262, in on_datagram_received
    callback_f(lookup_id, peers, msg.src_node)
  File "/home/rob/git/tribler/Tribler/community/tunnel/hidden_community.py", line 227, in dht_callback
    self.create_key_request(info_hash, peer)
  File "/home/rob/git/tribler/Tribler/community/tunnel/hidden_community.py", line 240, in create_key_request
    cache = self.request_cache.add(KeyRequestCache(self, circuit, sock_addr, info_hash))
  File "/home/rob/git/tribler/Tribler/community/tunnel/hidden_community.py", line 60, in __init__
    super(KeyRequestCache, self).__init__(community.request_cache, u"key-request")
  File "/home/rob/git/tribler/Tribler/dispersy/requestcache.py", line 50, in __init__
    number = RandomNumberCache.find_unclaimed_identifier(request_cache, prefix)
  File "/home/rob/git/tribler/Tribler/dispersy/requestcache.py", line 57, in find_unclaimed_identifier
    if not request_cache.has(prefix, number):
  File "/home/rob/git/tribler/Tribler/dispersy/requestcache.py", line 172, in has
    assert isInIOThread(), "RequestCache must be used on the reactor's thread"
AssertionError: RequestCache must be used on the reactor's thread
MINITWISTED CRASHED (see logs)</pre>

**Comment by LipuFei** [comment]
Add a `@call_on_reactor_thread` to `dht_callback` should solve the problem.

**Comment by LipuFei** [comment]
@rjruigrok I don't think they are related. The `dht_callback` error is in hidden_community, but the RequestCache KeyError problem is in SearchCommunity.
