### ISSUE TITLE
KeyError: u'ping:31091' pop from requestcache

### ISSUE THREAD

**Issue by rjruigrok** [Tribler/tribler#1205]
ERROR   1423144015.25        dispersy:1724  exception during handle_callback for torrent-collect-response
Traceback (most recent call last):
  File "/home/rob/git/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/rob/git/tribler/Tribler/community/search/community.py", line 489, in on_torrent_collect_response
    self.request_cache.pop(u"ping", message.payload.identifier)
  File "/home/rob/git/tribler/Tribler/dispersy/requestcache.py", line 196, in pop
    cache = self._identifiers.pop(identifier)
KeyError: u'ping:31091'

**Comment by synctext** [comment]
dupe of #1204 ..

**Comment by rjruigrok** [comment]
Never mind :) closed
