### ISSUE TITLE
Each TraceBack will fails the unit test on Jenkins

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1209]
Unit tests and pull request testing should detect all TraceBacks and halt on them. 
Sometimes Dispersy or other components give critical TraceBack, but everything still passes.

TraceBack that got undetected: http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester-isolated_devel/22/

```
18:35:52 [-] [graph_process_guard_...] OUT: Project root is: /home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel
18:35:52 [-] [graph_process_guard_...] OUT: NOT activating virtualenv.
18:35:52 [-] [graph_process_guard_...] OUT: Running graph_process_guard_data.sh
18:35:52 [-] [graph_process_guard_...] ERR: Parsing resource_usage file ./resource_usage.log
18:35:52 [-] [graph_process_guard_...] ERR: Traceback (most recent call last):
18:35:52 [-] [graph_process_guard_...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/gumby/scripts/extract_process_guard_stats.py", line 211, in <module>
18:35:52 [-] [graph_process_guard_...] ERR:     main(argv[1], argv[2])
18:35:52 [-] [graph_process_guard_...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/gumby/scripts/extract_process_guard_stats.py", line 199, in main
18:35:52 [-] [graph_process_guard_...] ERR:     parse_resource_files(input_directory, output_directory, start_time)
18:35:52 [-] [graph_process_guard_...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/gumby/scripts/extract_process_guard_stats.py", line 108, in parse_resource_files
18:35:52 [-] [graph_process_guard_...] ERR:     utime = long(parts[14])
18:35:52 [-] [graph_process_guard_...] ERR: IndexError: list index out of range
18:35:52 [-] [graph_process_guard_...] ERR: ['/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/gumby/scripts/modify_annotations.py', '.']
18:35:52 [-] [graph_process_guard_...] OUT: Usage: /home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/gumby/scripts/modify_annotations.py <peers-directory> <experiment start timestamp>
```

Almost all of the PyDeadObject stuff have been nicely removed. There is some left, see below.
http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/3373/

```
11:47:50 [-] [wrap_in_vnc.sh run_n...] ERR: test_add_metadata (Tribler.Test.test_metadata_community.TestMetadataCommunity) ... SKIP: Automatic thumbnail generation has been disabled and this test will never pass
11:48:28 [-] [wrap_in_vnc.sh run_n...] ERR: test_add_torrents_playlists (Tribler.Test.test_my_channel.TestMyChannel) ... ok
11:49:06 [-] [wrap_in_vnc.sh run_n...] ERR: test_rss_import (Tribler.Test.test_my_channel.TestMyChannel) ... ok
11:49:06 [-] [wrap_in_vnc.sh run_n...] ERR: test_fix_filebasename (Tribler.Test.test_osutils.Test_OsUtils) ... ok
11:50:10 [-] [wrap_in_vnc.sh run_n...] ERR: test_channelsearch (Tribler.Test.test_remote_search.TestRemoteQuery) ... Traceback (most recent call last):
11:50:10 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
11:50:10 [-] [wrap_in_vnc.sh run_n...] ERR:     lambda event: event.callable(*event.args, **event.kw) )
11:50:10 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Main/vwxGUI/list_item.py", line 321, in ShowSelected
11:50:10 [-] [wrap_in_vnc.sh run_n...] ERR:     DoubleLineListItem.ShowSelected(self)
11:50:10 [-] [wrap_in_vnc.sh run_n...] ERR: TypeError: unbound method ShowSelected() must be called with DoubleLineListItem instance as first argument (got _wxPyDeadObject instance instead)
11:50:43 [-] [wrap_in_vnc.sh run_n...] ERR: ok
11:51:15 [-] [wrap_in_vnc.sh run_n...] ERR: test_ffsearch (Tribler.Test.test_remote_search.TestRemoteQuery) ... ok
```

**Comment by LipuFei** [comment]
@synctext The first backtrace is a problem in gumby. The second one is one of those errors we usually get in the GUI.

**Comment by synctext** [comment]
@LipuFei  Yes, so if you and @whirm get rid of all of these, we can "break" the pull-request-tester on all of them.
