### ISSUE TITLE
Unable to install dependencies on clean Ubuntu 14.10

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1269]
```
>uname -a
Linux johan-XPS13 3.16.0-30-generic #40-Ubuntu SMP Mon Jan 12 22:06:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
>sudo dpkg -i python-cryptography_0.5.2-1_amd64.deb libsodium13_1.0.1-1_amd64.deb 
[sudo] password for pouwelse: 
(Reading database ... 256745 files and directories currently installed.)
Preparing to unpack python-cryptography_0.5.2-1_amd64.deb ...
Unpacking python-cryptography (0.5.2-1) over (0.5.2-1) ...
Selecting previously unselected package libsodium13:amd64.
Preparing to unpack libsodium13_1.0.1-1_amd64.deb ...
Unpacking libsodium13:amd64 (1.0.1-1) ...
Setting up python-cryptography (0.5.2-1) ...
Setting up libsodium13:amd64 (1.0.1-1) ...
Processing triggers for libc-bin (2.19-10ubuntu2.2) ...
>run-no-O 
Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 34, in <module>
    run()
  File "Tribler/Main/tribler.py", line 25, in run
    from Tribler.Main.tribler_main import run as run_main
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/tribler_main.py", line 62, in <module>
    from Tribler.Main.vwxGUI.MainFrame import FileDropTarget
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/vwxGUI/MainFrame.py", line 54, in <module>
    from Tribler.Main.vwxGUI.home import Home, Stats, NetworkGraphPanel
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/vwxGUI/home.py", line 7, in <module>
    from Tribler.community.tunnel.hidden_community import HiddenTunnelCommunity
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/tunnel/hidden_community.py", line 19, in <module>
    from Tribler.community.tunnel.routing import RelayRoute, RendezvousPoint, Hop
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/tunnel/routing.py", line 5, in <module>
    from Tribler.dispersy.crypto import LibNaCLPK
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/crypto.py", line 13, in <module>
    import libnacl.dual
ImportError: No module named libnacl.dual
XPS13:~/GITHUB/tribler>
```

**Comment by LipuFei** [comment]
@synctext run the following command and try again
```
cd Tribler/dispersy
git submodule init
git submodule sync
git submodule update
```
