### ISSUE TITLE
Database recovery failed, Tribler tried to recover, but failed. 

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1307]
An incorrect megacache (partial upgrade, running bleeding edge devel)
can bring down Tribler upgrade script.

It gave a nice pop-up, that it failed to covert and was starting a fresh megacache.
Then it halted on the error below.

```~/GITHUB/tribler>run-no-O 
ERROR   1425647124.08         upgrade:72    failed to upgrade: (u"The torrent collecting directory doesn't exist: %s", u'/home/pouwelse/Downloads/TriblerDownloads/collected_torrent_files')
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Upgrade/upgrade.py", line 55, in check_and_upgrade
    yield torrent_migrator.start_migrate()
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Upgrade/torrent_upgrade64.py", line 64, in start_migrate
    self._migrate_torrent_collecting_dir()
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Upgrade/torrent_upgrade65.py", line 57, in _migrate_torrent_collecting_dir
    raise RuntimeError(u"The torrent collecting directory doesn't exist: %s", self.torrent_collecting_dir)
RuntimeError: (u"The torrent collecting directory doesn't exist: %s", u'/home/pouwelse/Downloads/TriblerDownloads/collected_torrent_files')
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/tribler_main.py", line 207, in __init__
    s.start()
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Session.py", line 448, in start
    self.lm.register(self, self.sesslock, autoload_discovery=self.autoload_discovery)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 115, in register
    self.torrent_store = TorrentStore(self.session.get_torrent_store_dir())
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/torrentstore.py", line 63, in __init__
    self._db = LevelDB(store_dir)
LevelDBError: IO error: lock /home/pouwelse/.Tribler/collected_torrents/LOCK: already held by process
```

**Comment by LipuFei** [comment]
@synctext Could you check the version number of your database?
```
SELECT * FROM MyInfo;
```
