### ISSUE TITLE
Traceback error messages from the latest devel

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1312]
Quick writeup of 1 frequent warning and 3 Tracebacks:
```
WARNING 1425814349.56       community:1567  removing ('180.191.217.158', 1108) {192.168.254.104:7759 180.191.217.158:1108} in favor of ('180.191.217.158', 1071) {192.168.254.104:7759 180.191.217.158:1071}
WARNING 1425814354.57       community:1567  removing ('180.191.217.158', 1071) {192.168.254.104:7759 180.191.217.158:1071} in favor of ('180.191.217.158', 1108) {192.168.254.104:7759 180.191.217.158:1108}
WARNING 1425814379.56       community:1567  removing ('180.191.217.158', 1108) {192.168.254.104:7759 180.191.217.158:1108} in favor of ('180.191.217.158', 1071) {192.168.254.104:7759 180.191.217.158:1071}
WARNING 1425814384.57       community:1567  removing ('180.191.217.158', 1071) {192.168.254.104:7759 180.191.217.158:1071} in favor of ('180.191.217.158', 1108) {192.168.254.104:7759 180.191.217.158:1108}
ERROR   1425814429.23             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2059, in _process_message_batch
    return self._on_batch_cache(meta, batch)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2101, in _on_batch_cache
    self.on_messages(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2215, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1694, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 151, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/channel/community.py", line 387, in _disp_on_torrent
    self._channelcast_db.on_torrents_from_dispersy(torrentlist)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 1660, in on_torrents_from_dispersy
    torrent_ids, inserted = self.torrent_db.addOrGetTorrentIDSReturn(infohashes)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 579, in addOrGetTorrentIDSReturn
    assert all(torrent_id for torrent_id in torrent_ids), torrent_ids
exceptions.AssertionError: [17835, None, 17843, 17830, 17839, 17845, 17842, 17838, 17837, 17846, 17834, 17831, 17840, 17832, 17833, 17847, 17844, 17841, 17836]

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2059, in _process_message_batch
    return self._on_batch_cache(meta, batch)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2101, in _on_batch_cache
    self.on_messages(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2215, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1694, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 151, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/channel/community.py", line 387, in _disp_on_torrent
    self._channelcast_db.on_torrents_from_dispersy(torrentlist)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 1660, in on_torrents_from_dispersy
    torrent_ids, inserted = self.torrent_db.addOrGetTorrentIDSReturn(infohashes)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 579, in addOrGetTorrentIDSReturn
    assert all(torrent_id for torrent_id in torrent_ids), torrent_ids
exceptions.AssertionError: [17835, None, 17843, 17830, 17839, 17845, 17842, 17838, 17837, 17846, 17834, 17831, 17840, 17832, 17833, 17847, 17844, 17841, 17836]
WARNING 1425814574.57       community:1567  removing ('180.191.217.158', 1108) {192.168.254.104:7759 180.191.217.158:1108} in favor of ('180.191.217.158', 1043) {192.168.254.104:7759 180.191.217.158:1043}
WARNING 1425814594.68       community:1567  removing ('180.191.217.158', 1043) {192.168.254.104:7759 180.191.217.158:1043} in favor of ('180.191.217.158', 1108) {192.168.254.104:7759 180.191.217.158:1108}



WARNING 1425891670.41       community:1567  removing ('180.191.222.225', 1026) {192.168.254.104:7759 180.191.222.225:1026} in favor of ('180.191.222.225', 1082) {192.168.254.104:7759 180.191.222.225:1082}
WARNING 1425891675.03       community:1567  removing ('180.191.222.225', 1082) {192.168.254.104:7759 180.191.222.225:1082} in favor of ('180.191.222.225', 1085) {192.168.254.104:7759 180.191.222.225:1085}
WARNING 1425891689.98       community:1567  removing ('180.191.222.225', 1085) {192.168.254.104:7759 180.191.222.225:1085} in favor of ('180.191.222.225', 1026) {192.168.254.104:7759 180.191.222.225:1026}
WARNING 1425891700.02       community:1567  removing ('180.191.222.225', 1026) {192.168.254.104:7759 180.191.222.225:1026} in favor of ('180.191.222.225', 1082) {192.168.254.104:7759 180.191.222.225:1082}
ERROR   1425891907.47 TorrentChecking:559   TorrentChecking: Unexpected exception: string indices must be integers, not str
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TorrentChecking.py", line 507, in run
    session.handleRequest()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 114, in handleRequest
    return self.handleResponse()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 302, in handleResponse
    self._processHeader()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 387, in _processHeader
    success = self._processScrapeResponse()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 406, in _processScrapeResponse
    for infohash in response_dict['files'].keys():
TypeError: string indices must be integers, not str
WARNING 1425891920.23       community:1567  removing ('180.191.222.225', 1082) {192.168.254.104:7759 180.191.222.225:1082} in favor of ('180.191.222.225', 1085) {192.168.254.104:7759 180.191.222.225:1085}
WARNING 1425891925.78       community:1567  removing ('180.191.222.225', 1085) {192.168.254.104:7759 180.191.222.225:1085} in favor of ('180.191.222.225', 1051) {192.168.254.104:7759 180.191.222.225:1051}



ERROR   1425826567.26 TorrentChecking:559   TorrentChecking: Unexpected exception: Python argument types in
    libtorrent.bdecode(NoneType)
did not match C++ signature:
    bdecode(std::string)
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TorrentChecking.py", line 507, in run
    session.handleRequest()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 114, in handleRequest
    return self.handleResponse()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 312, in handleResponse
    success = self._processScrapeResponse()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 400, in _processScrapeResponse
    response_dict = bdecode(self._message_buffer)
ArgumentError: Python argument types in
    libtorrent.bdecode(NoneType)
did not match C++ signature:
    bdecode(std::string)
ERROR   1425834012.93   sqlitecachedb:296   ===Twisted===
SQL Type: <type 'str'>
-----
INSERT INTO Torrent (infohash, status_id) VALUES (?, ?)
-----
[('Ctc+eufDQjn+oEZbdr8raAdKfrI=', 0), ('TOYs67ZaZ/S606VCyDXWNMpXalo=', 0), ('xGBHzrtxq3d1DAPsauyC1/+g7rw=', 0)]
======
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 289, in executemany
    result = cur.executemany(sql, args)
  File "src/cursor.c", line 231, in resetcursor
ConstraintError: ConstraintError: UNIQUE constraint failed: Torrent.infohash
ERROR   1425834012.94        dispersy:1724  exception during handle_callback for dispersy-dynamic-settings
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/channel/community.py", line 1097, in on_dynamic_settings
    Community.on_dynamic_settings(self, *args, **kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 3594, in on_dynamic_settings
    self._update_timerange(meta, globaltime_range[0], globaltime_range[1])
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 3633, in _update_timerange
    meta.handle_callback(redo)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/channel/community.py", line 387, in _disp_on_torrent
    self._channelcast_db.on_torrents_from_dispersy(torrentlist)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 1660, in on_torrents_from_dispersy
    torrent_ids, inserted = self.torrent_db.addOrGetTorrentIDSReturn(infohashes)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 576, in addOrGetTorrentIDSReturn
    self._db.executemany(sql, [(bin2str(infohash), status_id) for infohash in to_be_inserted])
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 45, in helper
    return func(*args, **kargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 297, in executemany
    raise msg
ConstraintError: ConstraintError: UNIQUE constraint failed: Torrent.infohash
ERROR   1425851276.05 TorrentChecking:559   TorrentChecking: Unexpected exception: Python argument types in
    libtorrent.bdecode(NoneType)
did not match C++ signature:
    bdecode(std::string)
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TorrentChecking.py", line 507, in run
    session.handleRequest()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 114, in handleRequest
    return self.handleResponse()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 312, in handleResponse
    success = self._processScrapeResponse()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 400, in _processScrapeResponse
    response_dict = bdecode(self._message_buffer)
ArgumentError: Python argument types in
    libtorrent.bdecode(NoneType)
did not match C++ signature:
    bdecode(std::string)
ERROR   1425860382.84 TorrentChecking:559   TorrentChecking: Unexpected exception: Python argument types in
    libtorrent.bdecode(NoneType)
did not match C++ signature:
    bdecode(std::string)
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TorrentChecking.py", line 507, in run
    session.handleRequest()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 114, in handleRequest
    return self.handleResponse()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 312, in handleResponse
    success = self._processScrapeResponse()
  File "/home/pouwelse/GITHUB/tribler/Tribler/TrackerChecking/TrackerSession.py", line 400, in _processScrapeResponse
    response_dict = bdecode(self._message_buffer)
ArgumentError: Python argument types in
    libtorrent.bdecode(NoneType)
did not match C++ signature:
    bdecode(std::string)
WARNING 1425882934.68       community:1567  removing ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064} in favor of ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759}
WARNING 1425882954.68       community:1567  removing ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759} in favor of ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064}
WARNING 1425882964.68       community:1567  removing ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064} in favor of ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759}
WARNING 1425882969.68       community:1567  removing ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759} in favor of ('180.191.222.225', 1041) {192.168.254.104:7759 180.191.222.225:1041}
WARNING 1425882984.57       community:1567  removing ('180.191.222.225', 1041) {192.168.254.104:7759 180.191.222.225:1041} in favor of ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064}
WARNING 1425882994.68       community:1567  removing ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064} in favor of ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759}
WARNING 1425882999.68       community:1567  removing ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759} in favor of ('180.191.222.225', 1041) {192.168.254.104:7759 180.191.222.225:1041}
WARNING 1425883014.56       community:1567  removing ('180.191.222.225', 1041) {192.168.254.104:7759 180.191.222.225:1041} in favor of ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064}
WARNING 1425883024.67       community:1567  removing ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064} in favor of ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759}
WARNING 1425883029.57       community:1567  removing ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759} in favor of ('180.191.222.225', 1041) {192.168.254.104:7759 180.191.222.225:1041}
WARNING 1425883044.56       community:1567  removing ('180.191.222.225', 1041) {192.168.254.104:7759 180.191.222.225:1041} in favor of ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064}
WARNING 1425883054.56       community:1567  removing ('180.191.222.225', 1064) {192.168.254.104:7759 180.191.222.225:1064} in favor of ('180.191.222.225', 7759) {192.168.254.104:7759 180.191.222.225:7759}
W
```

**Comment by whirm** [comment]
We already have issues oppened for the stacktraces not yet fixed on this list, closing.
