### ISSUE TITLE
Searchmanager nullpointer

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/tribler#1354]
```
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR: test_ffsearch (Tribler.Test.test_remote_search.TestRemoteQuery) ... Unhandled Error
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR: Traceback (most recent call last):
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/threading.py", line 763, in run
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:     self.__target(*self.__args, **self.__kwargs)
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:     reactor.run(installSignalHandlers=False)
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:     self.mainLoop()
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:     self.runUntilCurrent()
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR: --- <exception caught here> ---
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:     f(*a, **kw)
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/managers.py", line 85, in _on_search_results
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR:     channel_cache_list = self.channelcast_db.getChannelsByCID(channel_cid_list)
10:23:58 [-] [wrap_in_vnc.sh run_n...] ERR: exceptions.AttributeError: 'NoneType' object has no attribute 'getChannelsByCID'

**Comment by LipuFei** [comment]
@NielsZeilemaker should be fixed by a02d875
