### ISSUE TITLE
Stacktrace when trying to download with [tunnel_community] enabled = False

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1385]
```python
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/Main/vwxGUI/MainFrame.py", line 514, in startDownload
    if dlg.UseHiddenservices():
  File "/var/data/projects/delft/tribler/Tribler/Main/Dialogs/SaveAs.py", line 237, in UseHiddenservices
    return self.anonimity_dialog.GetEndToEndValue()
AttributeError: 'NoneType' object has no attribute 'GetEndToEndValue'
```

This is with current ```devel```

**Comment by NielsZeilemaker** [comment]
Already fixed in https://github.com/Tribler/tribler/pull/1399/files#diff-48db89215e497c2743cd3c070ff79ac1R237
