### ISSUE TITLE
Stacktrace when searching for "tv" on current devel

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1408]
```python
ERROR   1431015039.27   LibtorrentMgr:113   could not restore dht state, starting from scratch
INFO    1431015039.27       community:307   initializing:  BarterCommunity
ERROR   1431015049.69             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/data/projects/delft/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/var/data/projects/delft/tribler/Tribler/dispersy/community.py", line 2050, in _process_message_batch
    return self._on_batch_cache(meta, batch)
  File "/var/data/projects/delft/tribler/Tribler/dispersy/community.py", line 2092, in _on_batch_cache
    self.on_messages(messages)
  File "/var/data/projects/delft/tribler/Tribler/dispersy/community.py", line 2179, in on_messages
    assert all(message.delayed not in possibly_messages for message in possibly_messages if isinstance(message, DelayMessage)), possibly_messages  # delayed messages cannot be accepted
exceptions.AssertionError: [<Tribler.dispersy.message.Implementation object at 0x7fe610bd4b90>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd4910>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd4690>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd4410>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd4190>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd7ed0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd7c50>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd79d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd7750>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd74d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bd7250>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf5f90>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf5d10>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf5a90>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf5810>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf5590>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf5310>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf5090>, <Tribler.dispersy.message.Implementation object at 0x7fe610bbadd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bbab50>, <Tribler.dispersy.message.Implementation object at 0x7fe610bba8d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bba650>, <Tribler.dispersy.message.Implementation object at 0x7fe610bba3d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bba150>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf3e90>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf3c10>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf3990>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf3710>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf3490>, <Tribler.dispersy.message.Implementation object at 0x7fe610bf3210>, <Tribler.dispersy.message.Implementation object at 0x7fe610bebf50>, <Tribler.dispersy.message.Implementation object at 0x7fe610bebcd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610beba50>, <Tribler.dispersy.message.Implementation object at 0x7fe610beb7d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610beb550>, <Tribler.dispersy.message.Implementation object at 0x7fe610beb2d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610beb050>, <Tribler.dispersy.message.Implementation object at 0x7fe610befd90>, <Tribler.dispersy.message.Implementation object at 0x7fe610befb10>, <Tribler.dispersy.message.Implementation object at 0x7fe610bef890>, <Tribler.dispersy.message.Implementation object at 0x7fe610bef610>, <Tribler.dispersy.message.Implementation object at 0x7fe610bef390>, <Tribler.dispersy.message.Implementation object at 0x7fe610bef110>, <Tribler.dispersy.message.Implementation object at 0x7fe610bcde50>, <Tribler.dispersy.message.Implementation object at 0x7fe610bcdbd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bcd950>, <Tribler.dispersy.message.Implementation object at 0x7fe610bcd6d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bcd450>, <Tribler.dispersy.message.Implementation object at 0x7fe610bcd1d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bc7f10>, <Tribler.dispersy.message.Implementation object at 0x7fe610bc7c90>, <Tribler.dispersy.message.Implementation object at 0x7fe610bc7a10>, <Tribler.dispersy.message.Implementation object at 0x7fe610bc7790>, <Tribler.dispersy.message.Implementation object at 0x7fe610bc7510>, <Tribler.dispersy.message.Implementation object at 0x7fe610bc7290>, <Tribler.dispersy.message.Implementation object at 0x7fe610bdcfd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bdcd50>, <Tribler.dispersy.message.Implementation object at 0x7fe610bdcad0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bdc850>, <Tribler.dispersy.message.Implementation object at 0x7fe610bdc5d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610bdc350>, <Tribler.dispersy.message.Implementation object at 0x7fe610bdc0d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c38e10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c38b90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c38910>, <Tribler.dispersy.message.Implementation object at 0x7fe610c38690>, <Tribler.dispersy.message.Implementation object at 0x7fe610c38410>, <Tribler.dispersy.message.Implementation object at 0x7fe610c38190>, <Tribler.dispersy.message.Implementation object at 0x7fe610c17ed0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c17c50>, <Tribler.dispersy.message.Implementation object at 0x7fe610c179d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c17750>, <Tribler.dispersy.message.Implementation object at 0x7fe610c174d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c17250>, <Tribler.dispersy.message.Implementation object at 0x7fe610c13f90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c13d10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c13a90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c13810>, <Tribler.dispersy.message.Implementation object at 0x7fe610c13590>, <Tribler.dispersy.message.Implementation object at 0x7fe610c13310>, <Tribler.dispersy.message.Implementation object at 0x7fe610c13090>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0add0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0ab50>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0a8d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0a650>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0a3d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0a150>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1ae90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1ac10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1a990>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1a710>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1a490>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1a210>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0bf50>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0bcd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c521d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0ba50>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0b7d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0b550>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0b2d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c0b050>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2bd90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2bb10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2b890>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2b610>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2b390>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2b110>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1de50>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1dbd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1d950>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1d6d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1d450>, <Tribler.dispersy.message.Implementation object at 0x7fe610c1d1d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c24f10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c24c90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c24a10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c24790>, <Tribler.dispersy.message.Implementation object at 0x7fe610c24510>, <Tribler.dispersy.message.Implementation object at 0x7fe610c24290>, <Tribler.dispersy.message.Implementation object at 0x7fe610c01fd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c01d50>, <Tribler.dispersy.message.Implementation object at 0x7fe610c01ad0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c01850>, <Tribler.dispersy.message.Implementation object at 0x7fe610c015d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c01350>, <Tribler.dispersy.message.Implementation object at 0x7fe610c010d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2ce10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2cb90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2c910>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2c690>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2c410>, <Tribler.dispersy.message.Implementation object at 0x7fe610c2c190>, <Tribler.dispersy.message.Implementation object at 0x7fe610c76ed0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c76c50>, <Tribler.dispersy.message.Implementation object at 0x7fe610c52090>, <Tribler.dispersy.message.Implementation object at 0x7fe610c52cd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c769d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c76750>, <Tribler.dispersy.message.Implementation object at 0x7fe610c764d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c76250>, <Tribler.dispersy.message.Implementation object at 0x7fe610c3ff90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c3fd10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c3fa90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c3f810>, <Tribler.dispersy.message.Implementation object at 0x7fe610c3f590>, <Tribler.dispersy.message.Implementation object at 0x7fe610c3f310>, <Tribler.dispersy.message.Implementation object at 0x7fe610c3f090>, <Tribler.dispersy.message.Implementation object at 0x7fe610c61dd0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c61b50>, <Tribler.dispersy.message.Implementation object at 0x7fe610c618d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c61650>, <Tribler.dispersy.message.Implementation object at 0x7fe610c613d0>, <Tribler.dispersy.message.Implementation object at 0x7fe610c61150>, <Tribler.dispersy.message.Implementation object at 0x7fe610c57e90>, <Tribler.dispersy.message.Implementation object at 0x7fe610c57c10>, <Tribler.dispersy.message.Implementation object at 0x7fe610c57990>, <Tribler.dispersy.message.Implementation object at 0x7fe610c57710>, <Tribler.dispersy.message.Implementation object at 0x7fe610c57490>, <Tribler.dispersy.message.Implementation object at 0x7fe610c57190>, <Tribler.dispersy.message.Implementation object at 0x7fe610c8b150>, DelayMessageByProof('DelayMessageByProof',), <Tribler.dispersy.message.Implementation object at 0x7fe610c52ed0>]
```

**Comment by whirm** [comment]
If I reset the megagache this goes away. I've stashed the problematic one away so we can reproduce it at will.

**Comment by lfdversluis** [comment]
@whirm Still there?

**Comment by whirm** [comment]
I don't remember seeing this in the last months.
