### ISSUE TITLE
error upon close: The reactor was not clean after stopping

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1448]
```
ERROR   1433339453.40    GuiDBHandler:268   'Traceback (most recent call last):\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/Utility/GuiDBHandler.py", line 133, in wrapper\n    result = workerFn(*args, **kwargs)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/tribler_main.py", line 465, in db_thread\n    return channelcast.getMyChannelId()\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 2475, in getMyChannelId\n    return self._db.fetchone(\'SELECT id FROM Channels WHERE peer_id ISNULL LIMIT 1\')\n  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 45, in helper\n    return func(*args, **kargs)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 372, in fetchone\n    find = self.execute_read(sql, args)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 300, in execute_read\n    return self.execute(sql, args)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 45, in helper\n    return func(*args, **kargs)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 253, in execute\n    cur = self.get_cursor()\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 186, in get_cursor\n    self._cursor_table[thread_name] = self._connection.cursor()\nAttributeError: \'NoneType\' object has no attribute \'cursor\'\n'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/tribler_main.py", line 468, in wx_thread
    my_channel = delayedResult.get()
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/Utility/GuiDBHandler.py", line 269, in get
    raise self.__exception
AttributeError: 'NoneType' object has no attribute 'cursor'
The reactor was not clean after stopping:
>     <DelayedCall 0x7f80802841b8 [294.996900082s] called=0 cancelled=0 LoopingCall<300>(DiscoveryCommunity.periodically_insert_trackers, *(), **{})()>
```

**Comment by whirm** [comment]
Did you close Tribler shortly after starting it?

**Comment by synctext** [comment]
@whirm  That is not something I do for testing. 
This is an entry I found on my STDOUT a long time ago.

**Comment by whirm** [comment]
I'm almost 100% sure this happened because you started and closed Tribler quickly, we are aware of that bug and it'l get fixed by the LibTribler splitting work. So I'm moving this to 6.6.

**Comment by devos50** [comment]
The issue above should cannot happen on the `devel` branch currently. With the code in `next`, we are creating a task regarding `torrentfeed` (https://github.com/Tribler/tribler/blob/next/Tribler/Main/tribler_main.py#L448) but this code has been removed. So I would suggest to close this issue and open another issue with another stack trace if this happen again.

**Comment by whirm** [comment]
@devos50 can you start/stop Tribler quickly (as in less than a minute after starting) and see if you still get errors? If you do, post the new stacktrace here, otherwise we can close this issue.

**Comment by devos50** [comment]
@whirm I opened and closed tribler many times quickly. I haven't seen a single dirty reactor error yet. I will try again tomorrow.

**Comment by lfdversluis** [comment]
On my ubuntu I can open it an close it within a few seconds without any crash happening.

**Comment by whirm** [comment]
Great to read that!
