### ISSUE TITLE
SqliteCacheDBHandler.py, line 409, in getTorrentIDS assert len(to_return) == len(infohashes)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1449]
http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/4273/console
```
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: Traceback (most recent call last):
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/threading.py", line 763, in run
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     self.__target(*self.__args, **self.__kwargs)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     reactor.run(installSignalHandlers=False)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     self.mainLoop()
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     self.runUntilCurrent()
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: --- <exception caught here> ---
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     call.func(*call.args, **call.kw)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/community.py", line 2050, in _process_message_batch
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     return self._on_batch_cache(meta, batch)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/community.py", line 2092, in _on_batch_cache
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     self.on_messages(messages)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/community.py", line 2206, in on_messages
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     if self._dispersy.store_update_forward(possibly_messages, True, True, False):
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/dispersy.py", line 1694, in store_update_forward
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     if self._update(possibly_messages) == False:
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/util.py", line 151, in wrapper
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     return_value = func(*args, **kargs)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     messages[0].handle_callback(messages)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/community/channel/community.py", line 412, in _disp_on_torrent
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     self._channelcast_db.on_torrents_from_dispersy(torrentlist)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 1556, in on_torrents_from_dispersy
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     torrent_ids, inserted = self.torrent_db.addOrGetTorrentIDSReturn(infohashes)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 495, in addOrGetTorrentIDSReturn
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     torrent_id_results = self.getTorrentIDS(infohashes)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 409, in getTorrentIDS
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR:     assert len(to_return) == len(infohashes)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: exceptions.AssertionError:
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: ok
```

**Comment by NielsZeilemaker** [comment]
I'm closing this one, as I think @LipuFei fixed it.
