### ISSUE TITLE
'Session' object has no attribute 'uch'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1482]
When starting Tribler with 1 hidden seeding (1-hop) torrent in the library.
```
ERROR   1434551531.37             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 441, in <lambda>
    notify_reachability = lambda: self.trsession.uch.notify(NTFY_REACHABLE, NTFY_INSERT, None, '')
exceptions.AttributeError: 'Session' object has no attribute 'uch'
```

**Comment by LipuFei** [comment]
This is fixed in #1480. We haven't merge it because we want to test if the catch unexpected exception thing works during the shutdown.
