### ISSUE TITLE
just download again: Tribler.Core.exceptions.DuplicateDownloadException

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1489]
Download something, remove data+torrent, then download it again.
Fails with error below.

Please make a unit test out of this, seen this error popup numerous times in past years. Thnx!
Tested with: http://releases.ubuntu.com/15.04/ubuntu-15.04-desktop-amd64.iso.torrent
```
ERROR   1434722493.79      statistics:51    len d: 79, fixed_n: 3
ERROR   1434722493.80      statistics:51    len d: 0, fixed_n: 3
ERROR   1434722493.80      statistics:51    len d: 213, fixed_n: 3
ERROR   1434722493.80      statistics:51    len d: 75, fixed_n: 3
ERROR   1434722493.80      statistics:51    len d: 0, fixed_n: 3
WARNING 1434722524.80       community:1552  removing ('63.142.161.4', 7759) {192.168.0.19:7759 63.142.161.4:7759} in favor of ('63.142.161.4', 15499) {192.168.0.19:7759 63.142.161.4:15499}
ERROR   1434722535.96             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 201, in <lambda>
    lm_network_engine_wrapper_created_callback, pstate, initialdlstatus)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 248, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 242, in add_torrent
    raise DuplicateDownloadException()
Tribler.Core.exceptions.DuplicateDownloadException: <class 'Tribler.Core.exceptions.DuplicateDownloadException'>: None
```

**Comment by whirm** [comment]
@synctext can't reproduce: @LipuFei tried to reproduce this manually for half an hour and we created a unit test for that and we ran it a bunch of times and we couldn't either so reopen it if you can figure out a way to reproduce it consistently.
