### ISSUE TITLE
exceptions.AssertionError: on_similarity_response

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1504]
Could be that this happened when my IPv4 was changing or wifi-Internet was down for a bit.

```
ERROR   1435195259.96 tunnel_community:911   TunnelCommunity: ignoring create for circuit 1204450159 from ('95.211.198.140', 7112) (too many relays 100)
ERROR   1435195268.02 tunnel_community:911   TunnelCommunity: ignoring create for circuit 2046138985 from ('95.211.198.140', 7112) (too many relays 100)
ERROR   1435195271.94 tunnel_community:911   TunnelCommunity: ignoring create for circuit 3939631638 from ('217.27.182.31', 7759) (too many relays 100)
ERROR   1435195278.78             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/endpoint.py", line 247, in dispersythread_data_came_in
    u"standalone_ep")
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1458, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp, source)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2023, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2093, in _on_batch_cache
    self.on_messages(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2207, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1694, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 151, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/discovery/community.py", line 608, in on_similarity_response
    w_candidate)])
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/discovery/community.py", line 87, in __init__
    assert candidate.get_member()
exceptions.AssertionError: 

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/endpoint.py", line 247, in dispersythread_data_came_in
    u"standalone_ep")
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1458, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp, source)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2023, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2093, in _on_batch_cache
    self.on_messages(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2207, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1694, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 151, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/discovery/community.py", line 608, in on_similarity_response
    w_candidate)])
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/discovery/community.py", line 87, in __init__
    assert candidate.get_member()

```

**Comment by NielsZeilemaker** [comment]
Its a bug in the discovery community, it's probably using the wrong candidate object

**Comment by whirm** [comment]
Ok, I'm able to reproduce it by doing this: 
```
 sudo ifdown lan ; sleep 60 ; sudo ifup lan
```
And then waiting for a bit.

**Comment by NielsZeilemaker** [comment]
@whirm could you add an assert here:
https://github.com/Tribler/dispersy/blob/devel/discovery/community.py#L465
assert candidate.get_member()

and check if that fires

**Comment by whirm** [comment]
Yes it does, for the trackers just after starting Tribler even: 
```
Unhandled Error
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/dispersy/community.py", line 1207, in start_walking
    switch_to_normal_walking()
  File "/var/data/projects/delft/tribler/Tribler/dispersy/community.py", line 1170, in switch_to_normal_walking
    self.register_task("take step", LoopingCall(self.take_step)).start(TAKE_STEP_INTERVAL, now=True)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 173, in start
    self()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/var/data/projects/delft/tribler/Tribler/dispersy/community.py", line 1218, in take_step
    self.create_introduction_request(candidate, self.dispersy_enable_bloom_filter_sync)
  File "/var/data/projects/delft/tribler/Tribler/dispersy/discovery/community.py", line 493, in create_introduction_request
    send = self.create_similarity_request(destination, allow_sync=allow_sync)
  File "/var/data/projects/delft/tribler/Tribler/dispersy/discovery/community.py", line 501, in create_similarity_request
    cache = self._request_cache.add(DiscoveryCommunity.SimilarityAttempt(self, destination, payload, allow_sync))
  File "/var/data/projects/delft/tribler/Tribler/dispersy/discovery/community.py", line 474, in __init__
    assert requested_candidate.get_member(), requested_candidate 
exceptions.AssertionError: {130.161.211.245:6422}
```

**Comment by NielsZeilemaker** [comment]
That makes sense, remove that assert, and add
```
wcandidate.associate(message.authentication.member)
```
to line https://github.com/Tribler/dispersy/blob/devel/discovery/community.py#L597
that should fix it.

**Comment by LipuFei** [comment]
I'll update the dispersy pointer after we merge https://github.com/Tribler/dispersy/pull/436.
