### ISSUE TITLE
Can't import Core.Utilities.twisted_thread when running Tribler from a FUSE filesystem

### ISSUE THREAD

**Issue by snifong** [Tribler/tribler#1511]
**OS:** Sabayon Linux 15.X (Gentoo)
**Version:** Latest (as of 06/28/2015) version pulled from git.
**Command:**  `./tribler.sh` from tribler git root.

Error msg:

```
Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 14, in <module>
    from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
  File "/media/truecrypt1/tribler/Tribler/Main/Tribler.py", line 14, in <module>
    from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
ImportError: No module named Core.Utilities.twisted_thread
```

**Comment by whirm** [comment]
Just did

**Comment by whirm** [comment]
Just did a quick test:

```
 git clone --recursive --depth=1 git@github.com:Tribler/tribler.git
cd tribler
./tribler.sh
```
And it's working fine.

Could you do a ```git fetch --all ; git status  ``` and paste the output here?

Thanks!

**Comment by snifong** [comment]
```
$ git fetch --all; git status
Fetching origin
On branch devel
Your branch is up-to-date with 'origin/devel'.
nothing to commit, working directory clean

$ ./tribler.sh 
Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 14, in <module>
    from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
  File "/media/truecrypt1/tribler/Tribler/Main/Tribler.py", line 14, in <module>
    from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
ImportError: No module named Core.Utilities.twisted_thread

**Comment by whirm** [comment]
That's weird... 
Is ```Tribler/Core/Utilities/twisted_thread.py``` there?

**Comment by snifong** [comment]
Yes.
```
$ ls -h Tribler/Core/Utilities/twisted_thread.py
Tribler/Core/Utilities/twisted_thread.py

**Comment by whirm** [comment]
@snifong: Could you run ```bash -x tribler.sh``` and paste the output?

**Comment by snifong** [comment]
```
$ bash -x tribler.sh 
++ uname -s
+ UNAME=Linux
+ '[' -z '' ']'
+ TRIBLER_SCRIPT=Tribler/Main/tribler.py
+ '[' Linux = Linux ']'
+++ readlink -f tribler.sh
++ dirname /media/truecrypt1/tribler/tribler.sh
+ TRIBLER_DIR=/media/truecrypt1/tribler
+ '[' '!' -d /media/truecrypt1/tribler ']'
+ cd /media/truecrypt1/tribler
+ PYTHONPATH=.:/usr/lib/entropy/lib
+ export PYTHONPATH
+ python2.7 Tribler/Main/tribler.py
Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 14, in <module>
    from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
  File "/media/truecrypt1/tribler/Tribler/Main/Tribler.py", line 14, in <module>
    from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
ImportError: No module named Core.Utilities.twisted_thread
```

**Comment by whirm** [comment]
That looks fine.

Could you try doing the checkout in /tmp instead of the truecrypt volume? I guess truecrypt uses FUSE and maybe that is giving trouble?

**Comment by snifong** [comment]
I checkout to home dir deleted ~/.Tribler dir and tried running it.
```
$ bash -x ./tribler.sh 
++ uname -s
+ UNAME=Linux
+ '[' -z '' ']'
+ TRIBLER_SCRIPT=Tribler/Main/tribler.py
+ '[' Linux = Linux ']'
+++ readlink -f ./tribler.sh
++ dirname /home/shane/tribler/tribler.sh
+ TRIBLER_DIR=/home/shane/tribler
+ '[' '!' -d /home/shane/tribler ']'
+ cd /home/shane/tribler
+ PYTHONPATH=.:/usr/lib/entropy/lib
+ export PYTHONPATH
+ python2.7 Tribler/Main/tribler.py
Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 34, in <module>
    run()
  File "Tribler/Main/tribler.py", line 25, in run
    from Tribler.Main.tribler_main import run as run_main
  File "/home/shane/tribler/Tribler/Main/tribler_main.py", line 76, in <module>
    from Tribler.Main.vwxGUI.MainFrame import FileDropTarget, MainFrame
  File "/home/shane/tribler/Tribler/Main/vwxGUI/MainFrame.py", line 52, in <module>
    from Tribler.Main.vwxGUI.home import Home, Stats, NetworkGraphPanel
  File "/home/shane/tribler/Tribler/Main/vwxGUI/home.py", line 7, in <module>
    from Tribler.community.tunnel.hidden_community import HiddenTunnelCommunity
  File "/home/shane/tribler/Tribler/community/tunnel/hidden_community.py", line 26, in <module>
    from Tribler.community.tunnel.routing import RelayRoute, RendezvousPoint, Hop
  File "/home/shane/tribler/Tribler/community/tunnel/routing.py", line 5, in <module>
    from Tribler.dispersy.crypto import LibNaCLPK
  File "/home/shane/tribler/Tribler/dispersy/crypto.py", line 13, in <module>
    import libnacl.dual
  File "/home/shane/tribler/Tribler/dispersy/libnacl/libnacl/__init__.py", line 75, in <module>
    nacl = _get_nacl()
  File "/home/shane/tribler/Tribler/dispersy/libnacl/libnacl/__init__.py", line 73, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,  and tweetnacl.so
```
After installing libsodium, I ran it again.  GUI started to load then displayed and error dialog with the following error:
```
Tribler version: 6.4.0-GIT
Traceback (most recent call last):
  File "/home/shane/tribler/Tribler/Main/tribler_main.py", line 174, in __init__
    s.start()
  File "/home/shane/tribler/Tribler/Core/Session.py", line 422, in start
    self.lm.register(self, self.sesslock, autoload_discovery=self.autoload_discovery)
  File "/home/shane/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 100, in register
    from Tribler.Core.leveldbstore import LevelDbStore
  File "/home/shane/tribler/Tribler/Core/leveldbstore.py", line 46, in <module>
    from plyveladapter import LevelDB, WriteBatch
  File "/home/shane/tribler/Tribler/Core/plyveladapter.py", line 1, in <module>
    import plyvel
type: No module named plyvel
```
I don't see any available packages for plyvel.

**Comment by whirm** [comment]
@snifong That's the fallback leveldb import, just install ```python-leveldb``` (have a look at ```debian/control``` to see Tribler's current deps.)

**Comment by snifong** [comment]
Installed all the dependencies and was able to run it from my home dir.  I had to install plyvel seperately from LeveDB using pip.

`$ pip install plyvel`

That's the only dep I had to install that way.  Thanks for the help.

Back to your FUSE comment.  I run lots of apps from that truecrypt volume and have never run into trouble.  What gives?

**Comment by whirm** [comment]
@snifong the "supported" leveldb bindings are py-leveldb (http://code.google.com/p/py-leveldb/) as those are available on Debian based distros. Plyvel was added as a backup but either should work fine.

re FUSE: I've seen a handful of weird behaviours when running stuff on a FUSE filesystem in the past. You could ```strace``` the python binary when trying to run Tribler and see if you notice anything weird there and report back.
If you can find a workaround that makes python behave as it should and it's reasonably sane, we will gladly accept a PR.

I'll edit the comment to reflect the actual issue.

Thanks for the report and enjoy Tribler!

**Comment by vandenheuvel** [comment]
This code is removed. @devos50 this can be closed.
