### ISSUE TITLE
Traceback Tribler.Test.test_gui_general.TestGuiGeneral

### ISSUE THREAD

**Issue by rjruigrok** [Tribler/tribler#1517]
Test passes, discovered this traceback while looking for results of other tests. 

```
test_debugpanel (Tribler.Test.test_gui_general.TestGuiGeneral) ... Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/TorrentChecker/torrent_checker.py", line 194, in _task_select_torrents
    self._checker_thread.interrupt()
exceptions.AttributeError: 'NoneType' object has no attribute 'interrupt'
ok```

**Comment by whirm** [comment]
Should be fixed on devel.
