### ISSUE TITLE
Segmentation fault - UnicodeDecodeError - SystemError: ../Objects/tupleobject.c:142: bad argument to internal function - 

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1553]
While running this just-before-RC1 version for memory leaks with Dowser for roughly 48hours.
commit b166ceb25bf9e378c1ceb9cfb0c5af016dc409cb
Merge: e6ce427 8686f54
Author: Elric Milon whirm@users.noreply.github.com
Date:   Tue Jul 7 15:55:43 2015 +0200

Below is the TraceBack output with a `not_filter     for pos in fmt_unpack(hash_.digest()):` error, then a SegFault. However, the stacktrace pictures show for "#16" an UnicodeDecodeError.

```
127.0.0.1 - - [08/Jul/2015:18:12:57] "GET /chart/__builtin__.weakref HTTP/1.1" 200 145 "http://localhost:8080/?floor=1000" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.81 Chrome/43.0.2357.81 Safari/537.36"
INFO    1436371977.34      _cplogging:296   127.0.0.1 - - [08/Jul/2015:18:12:57] "GET /chart/__builtin__.weakref HTTP/1.1" 200 145 "http://localhost:8080/?floor=1000" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.81 Chrome/43.0.2357.81 Safari/537.36"
127.0.0.1 - - [08/Jul/2015:18:12:57] "GET /favicon.ico HTTP/1.1" 200 1406 "http://localhost:8080/?floor=1000" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.81 Chrome/43.0.2357.81 Safari/537.36"
INFO    1436371977.35      _cplogging:296   127.0.0.1 - - [08/Jul/2015:18:12:57] "GET /favicon.ico HTTP/1.1" 200 1406 "http://localhost:8080/?floor=1000" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.81 Chrome/43.0.2357.81 Safari/537.36"
ERROR   1436382307.97       community:2577  already seen this indentifier in this batch, previous candidate {192.168.11.32:7759 125.14.246.199:7759} this one {192.168.11.32:7759 125.14.246.199:7759}
ERROR   1436391639.87        dispersy:1724  exception during handle_callback for dispersy-introduction-request
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2556, in on_introduction_request
    for packet, in payload.bloom_filter.not_filter(generator):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/bloomfilter.py", line 234, in not_filter
    for pos in fmt_unpack(hash_.digest()):
SystemError: ../Objects/tupleobject.c:142: bad argument to internal function
ERROR   1436392105.78       community:2577  already seen this indentifier in this batch, previous candidate {184.64.229.137:7759} this one {184.64.229.137:7759}
ERROR   1436392105.86       community:2577  already seen this indentifier in this batch, previous candidate {184.64.229.137:7759} this one {184.64.229.137:7759}
ERROR   1436392105.86       community:2577  already seen this indentifier in this batch, previous candidate {184.64.229.137:7759} this one {184.64.229.137:7759}
ERROR   1436392105.86       community:2577  already seen this indentifier in this batch, previous candidate {184.64.229.137:7759} this one {184.64.229.137:7759}
ERROR   1436393467.75       community:2577  already seen this indentifier in this batch, previous candidate {192.168.1.107:7759 174.44.80.235:7759} this one {192.168.1.107:7759 174.44.80.235:7759}
ERROR   1436397363.22        dispersy:1724  exception during handle_callback for dispersy-introduction-request
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/community.py", line 2556, in on_introduction_request
    for packet, in payload.bloom_filter.not_filter(generator):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/bloomfilter.py", line 234, in not_filter
    for pos in fmt_unpack(hash_.digest()):
SystemError: ../Objects/tupleobject.c:142: bad argument to internal function
ERROR   1436417122.95       community:2866  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417214.81       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417214.81       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417214.81       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417214.81       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417363.77       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417363.77       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417554.17       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417554.17       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417554.17       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436417554.17       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
Segmentation fault (core dumped)
```

![stacktrace1](https://cloud.githubusercontent.com/assets/325224/8590791/fdbdb784-2623-11e5-80b6-9b6298660714.png)
![stacktrace2](https://cloud.githubusercontent.com/assets/325224/8590795/030fe504-2624-11e5-91f8-9dcefaabb892.png)

![stacktrace3](https://cloud.githubusercontent.com/assets/325224/8590799/09fc6ed2-2624-11e5-9f03-02f2621c0fee.png)

![stacktrace4](https://cloud.githubusercontent.com/assets/325224/8590802/0e1af5b0-2624-11e5-826a-a2f6e8aad269.png)

**Comment by whirm** [comment]
Hm, can you tell me how to reproduce that?

I see that it was on m2crypto land when it segfaulted. I've managed to make m2crypto segfault when feeding it wrong sized keys, so it could also be related to passing bad data to m2crypto.

**Comment by synctext** [comment]
no idea, sadly..

Wrong keylength is a promising lead...!

**Comment by whirm** [comment]
I don't think wrong key lengh is the issue, I'm saying I used to be able to make m2crypto segfault by feeding it bad data (Just checked and the segfault.py script I made to reproduce that doesn't crash anymore, so it seems at least that got fixed in the last months)

**Comment by brandc** [comment]
By chance, could this be related could issue #1541 be related?

**Comment by whirm** [comment]
@brandc nope, that one is already fixed and the unicode error is happening somewhere else. Also, that shouldn't lead to a segfault anyway.

**Comment by whirm** [comment]
@synctext I'm pushing this to the backlog, If anyone is able to reproduce this without enabling dowser I'll have a look at it.

**Comment by qstokkink** [comment]
As M2Crypto has been phased out in IPv8 _and_ this issue has not been reproduced in years, I will close this.
