### ISSUE TITLE
Mac is out of file handlers: Too many open files

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1557]
6.5.0 RC1-xx failed after a minute, when having 38 files in Library.
```
12/07/15 13:55:24,665 QuickLookSatellite[6056]: In -[NSApplication(NSQuietSafeQuit) _updateCanQuitQuietlyAndSafely], _LSSetApplicationInformationItem(NSCanQuitQuietlyAndSafely) returned error -50
12/07/15 13:55:26,120 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:55:26,121 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:55:26,121 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:55:26,121 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:55:26,122 Tribler[6043]: ERROR   1436702126.12 torrent_checker:403   Failed to create session for tracker http://tracker.t411.me:56969/9b5143ba883dc517f3d2856f23da40d5/announce: Cannot resolve tracker URL.
12/07/15 13:55:36,145 Tribler[6043]: ERROR   1436702136.15 torrent_checker:403   Failed to create session for tracker http://www.smartorrent.com:2710/ma7697h0anvl19yzswrrdadj57iyt35w/announce: Could not establish connection
12/07/15 13:55:38,168 Console[6061]: Failed to connect (_consoleX) outlet from (NSApplication) to (ConsoleX): missing setter or instance variable
12/07/15 13:55:46,138 Tribler[6043]: ERROR   1436702146.14 torrent_checker:403   Failed to create session for tracker http://bt2.rutracker.org:80/ann?uk=01quWTyKBR: Could not establish connection
12/07/15 13:55:56,151 Tribler[6043]: ERROR   1436702156.15 torrent_checker:403   Failed to create session for tracker http://heavens-above.biz:80/announce.php?passkey=3c39f0aed862ca9929cce490e640237d: Cannot resolve tracker URL.
12/07/15 13:56:06,209 Tribler[6043]: ERROR   1436702166.21 torrent_checker:403   Failed to create session for tracker http://c.ncore.cc:2710/bc8207cf8aa89db53b33e9d406e83162/announce: Cannot resolve tracker URL.
12/07/15 13:56:16,242 Tribler[6043]: ERROR   1436702176.24 torrent_checker:403   Failed to create session for tracker http://bt3.rutracker.org:80/ann?uk=jt7SW1GTkI: Could not establish connection
12/07/15 13:56:25,059 Tribler[6043]: ERROR   1436702185.06   sqlitecachedb:272   cachedb: ===Twisted===
12/07/15 13:56:25,059 Tribler[6043]: SQL Type: <type 'unicode'>
12/07/15 13:56:25,059 Tribler[6043]: -----
12/07/15 13:56:25,059 Tribler[6043]: UPDATE Torrent SET status=?,comment=?,name=?,secret=?,creation_date=?,num_files=?,length=?,is_collected=?,insert_time=?,relevance=?,category=? WHERE torrent_id = 827589
12/07/15 13:56:25,060 Tribler[6043]: -----
12/07/15 13:56:25,060 Tribler[6043]: ['unknown', u'None', u'Gogo no Kouchou', 0, 1436665048, 7, 230212085, 0, 1436702185L, 0.0, 'Video']
12/07/15 13:56:25,060 Tribler[6043]: ======
12/07/15 13:56:25,060 Tribler[6043]: Traceback (most recent call last):
12/07/15 13:56:25,060 Tribler[6043]:   File "Tribler/Core/CacheDB/sqlitecachedb.pyo", line 263, in execute
12/07/15 13:56:25,061 Tribler[6043]:   File "src/cursor.c", line 236, in resetcursor
12/07/15 13:56:25,061 Tribler[6043]: CantOpenError: CantOpenError: unable to open database file
12/07/15 13:56:25,061 Tribler[6043]: ERROR   1436702185.06 SqliteCacheDBHandler:362   Could not create a TorrentDef instance '\xf2&\xd1\xb8\x8a\\\xd2\xe7\x14\x14\xe3y\xba\xd5\xdd]\xb6R\xdc3' 1436665048 u'Gogo no Kouchou' ((u'[SubDESU-H] Gogo no Kouchou - 01 (704x400 x264 AAC) [3EE5A4A2].mkv', 228331169), (u'ssc\\Gogo_no_Kouchou.jpg', 42026), (u'ssc\\Gogo_no_Kouchou_-_01.jpg', 167516), (u'ssc\\Gogo_no_Kouchou_-_c1.jpg', 1586069), (u'ssc\\Gogo_no_Kouchou_-_ss1.jpg', 26921), (u'ssc\\Gogo_no_Kouchou_-_ss2.jpg', 36826), (u'ssc\\Gogo_no_Kouchou_-_s
12/07/15 13:56:25,061 Tribler[6043]: ERROR   1436702185.06 SqliteCacheDBHandler:362   Could not create a TorrentDef instance '\xf2&\xd1\xb8\x8a\\\xd2\xe7\x14\x14\xe3y\xba\xd5\xdd]\xb6R\xdc3' 1436665048 u'Gogo no Kouchou' ((u'[SubDESU-H] Gogo no Kouchou - 01 (704x400 x264 AAC) [3EE5A4A2].mkv', 228331169), (u'ssc\\Gogo_no_Kouchou.jpg', 42026), (u'ssc\\Gogo_no_Kouchou_-_01.jpg', 167516), (u'ssc\\Gogo_no_Kouchou_-_c1.jpg', 1586069), (u'ssc\\Gogo_no_Kouchou_-_ss1.jpg', 26921), (u'ssc\\Gogo_no_Kouchou_-_ss2.jpg', 36826), (u'ssc\\Gogo_no_Kouchou_-_s
12/07/15 13:56:25,062 Tribler[6043]: ERROR   1436702185.06 SqliteCacheDBHandler:362   Could not create a TorrentDef instance '\xf2&\xd1\xb8\x8a\\\xd2\xe7\x14\x14\xe3y\xba\xd5\xdd]\xb6R\xdc3' 1436665048 u'Gogo no Kouchou' ((u'[SubDESU-H] Gogo no Kouchou - 01 (704x400 x264 AAC) [3EE5A4A2].mkv', 228331169), (u'ssc\\Gogo_no_Kouchou.jpg', 42026), (u'ssc\\Gogo_no_Kouchou_-_01.jpg', 167516), (u'ssc\\Gogo_no_Kouchou_-_c1.jpg', 1586069), (u'ssc\\Gogo_no_Kouchou_-_ss1.jpg', 26921), (u'ssc\\Gogo_no_Kouchou_-_ss2.jpg', 36826), (u'ssc\\Gogo_no_Kouchou_-_s
12/07/15 13:56:40,822 UserNotificationCenter[6065]: *** WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
12/07/15 13:56:51,423 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:56:51,423 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:56:51,424 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:56:51,425 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:57:05,303 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:57:05,304 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:57:05,304 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:57:05,305 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
12/07/15 13:57:25,291 Tribler[6043]: dnssd_clientstub deliver_request: socketpair failed 24 (Resource temporarily unavailable)
```

**Comment by whirm** [comment]
@synctext could you trigger this error again and get the list of open file descriptors by doing this:
http://stackoverflow.com/a/26862998

This way we can get a hint about where we are leaking them.

**Comment by synctext** [comment]
OK, it happened a week or 3 ago again. Let me see if we can reproduce this. It's not easy..

**Comment by synctext** [comment]
Tribler is running smoothly, latest *next* branch of Mac. But, we (still?) have this nice error.

![image](https://cloud.githubusercontent.com/assets/325224/11073731/5721315a-87ec-11e5-8402-51cb2caca760.png)

**Comment by whirm** [comment]
@synctext then you'll need to buy a developer cert from Apple I guess.

**Comment by whirm** [comment]
I'm closing this, feeel free to reopen if you manage to reproduce it.
