### ISSUE TITLE
Upgrade install fails on start, "Unable to obtain adapter information."

### ISSUE THREAD

**Issue by colin1497** [Tribler/tribler#1575]
Tribler version: 6.5.0-rc2
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 174, in __init__
  File "Tribler\Core\Session.pyo", line 422, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 155, in register
  File "Tribler\dispersy\dispersy.pyo", line 136, in __init__
  File "Tribler\dispersy\dispersy.pyo", line 194, in _get_interface_addresses
type: Unable to obtain adapter information.

**Comment by LipuFei** [comment]
We have made a fix for this in dispersy #449. This issue will be closed after we update dispersy in Tribler.

**Comment by LipuFei** [comment]
Fixed by #1581
