### ISSUE TITLE
"Default Anonymous Level:"-Option becomes visible but is not interactable

### ISSUE THREAD

**Issue by EnolRekcah** [Tribler/tribler#1582]
If you deselect "Let me choose a location for every download" in the general settings menu in Windows an option "Default Anonymous Level:" becomes visible where the title "General" is placed. Underneath it seems to be a checkbox but it's kind of buggy.

**Comment by whirm** [comment]
Are you running 6.4.*? This part of the gui has changed since then. Maybe you could try the latest RC?

Thanks!

**Comment by EnolRekcah** [comment]
Yes I'm running v6.4.*. I am having problems with the latest RC. I think this Error is also mentioned in a previous issue:

Tribler version: 6.5.0-rc2
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 174, in __init__
  File "Tribler\Core\Session.pyo", line 422, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 155, in register
  File "Tribler\dispersy\dispersy.pyo", line 136, in __init__
  File "Tribler\dispersy\dispersy.pyo", line 194, in _get_interface_addresses
type: Unable to obtain adapter information.

I can't get it to run.

**Comment by whirm** [comment]
I've just uploaded RC3, which contains fixes for that issue: https://github.com/Tribler/tribler/releases/tag/v6.5.0-rc3

Give it a go and see if it solves your issue.

Thanks!

**Comment by EnolRekcah** [comment]
Thanks ;)

**Comment by EnolRekcah** [comment]
I just downloaded the new release but unfortunately I run into the following Error on Windows 8.1:

Tribler version: 6.5.0-rc3
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 174, in __init__
  File "Tribler\Core\Session.pyo", line 422, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 155, in register
  File "Tribler\dispersy\dispersy.pyo", line 136, in __init__
  File "Tribler\dispersy\dispersy.pyo", line 213, in _get_interface_addresses
type: global name 'self' is not defined

**Comment by whirm** [comment]
Just merged a fix for that, I'll do a quick rebuild shortly. Thanks.

**Comment by EnolRekcah** [comment]
Okay, thanks a lot.
