### ISSUE TITLE
KeyError: '\xe6}\xdf\xfbw\xc4\x94\xaa\xc1\xaf\t\xc1\x84\xa1\xa1\x15\xed\xbb\xb4\x90'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1622]
```
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/tribler_main.py", line 629, in sesscb_states_callback
    self.tunnel_community.monitor_downloads(dslist)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 35, in helper
    return func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/hidden_community.py", line 250, in monitor_downloads
    self.create_introduction_point(info_hash)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/hidden_community.py", line 636, in create_introduction_point
    circuit_id = self.create_circuit(self.hops[info_hash] + 1,
KeyError: '\xe6}\xdf\xfbw\xc4\x94\xaa\xc1\xaf\t\xc1\x84\xa1\xa1\x15\xed\xbb\xb4\x90'
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/tribler_main.py", line 629, in sesscb_states_callback
    self.tunnel_community.monitor_downloads(dslist)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 35, in helper
    return func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/hidden_community.py", line 250, in monitor_downloads
    self.create_introduction_point(info_hash)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/hidden_community.py", line 636, in create_introduction_point
    circuit_id = self.create_circuit(self.hops[info_hash] + 1,
KeyError: '\xe6}\xdf\xfbw\xc4\x94\xaa\xc1\xaf\t\xc1\x84\xa1\xa1\x15\xed\xbb\xb4\x90'
```

**Comment by rjruigrok** [comment]
@synctext Do you remember what the amount of hops was for this download? Was it actually downloading anonymously or using set to 0 hops? Only in the latter case it would be plausible that this error would occur. 

I suspect that https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/hidden_community.py#L237 would need an extra if constriant, checking whether the number of hops is > 0.

**Comment by synctext** [comment]
@rjruigrok Hey Rob, are you still able to take a look at the code for us?
That would really help us out a lot, we're starting to get ready to ship V6.5 after like 3 months of  debugging...

No downloads with any anonimity hops.
Not doing any downloading at the moment of this error, just background circuits I guess.
Just seeing this in latest code: 
```
ERROR   1441901382.17        dispersy:1728  exception during handle_callback for create
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1723, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/tunnel_community.py", line 937, in on_create
    vc = self.exit_candidates[pubkey]
KeyError: 'LibNaCLPK:\xb6TX\xd7\x82\xba2\x1e\xaayj\x88\x88\xef\xae\xf9m\x1f\t\xeee.\xc7\x1b1\x91\x92\xb7F\xb8\xdat\xb6\x9bPy\x05\xbf\x8a\x16/\xb0a\xc5k,3&\xd1\xf1\xf1\x95\xb8\x05\xd0\xf0\x9b\xffV\xd2mi\xa5\x81'
ERROR   1441939229.30 tunnel_community:1144  Circuit is already removed? 3344110819 ('2.146.72.196', 7759)
ERROR   1441963043.78        dispersy:1728  exception during handle_callback for stats-request
```

**Comment by rjruigrok** [comment]
Strange, as the dispersy introduction request / response is overridden to add the pubkey to the `self.exit_candidates` dict [here](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L870) and [here](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L882). 

It iterates over all verified candidates [here](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L935). I assumed that a yield_dispersy_verified_candide would yield candidates that also passed the on_introduction_request/response method, but that's probably not the case here. Not a big deal, just check with an extra if whether the key is included in the `self.exit_candidates` dict would suffice. (btw this could also happen on lines [476](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L476) and line [502](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L502).

**Comment by synctext** [comment]
Still in latest devel of 4Dec.
```
Unhandled error in Deferred:
CRITICAL 1449301277.82         _legacy:154   Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 213, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 35, in helper
    return func(*args, **kargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/tunnel/tunnel_community.py", line 422, in do_circuits
    if not self.create_circuit(circuit_length):
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/tunnel/tunnel_community.py", line 485, in create_circuit
    exit_candidate = self.exit_candidates[pubkey]
exceptions.KeyError: 'LibNaCLPK:\xf7|\xee\x14\xfc\xa4\xc0\xf1B\xcc\xe2q\xad\xac\x94\xa5\xf0\xf3\xdb*\xb9c\x96\x10\x02rGL8Y\xb3\x14\x14\x91\xd2\xa7\xf6\x93\xc0\xae<HvZ\x13,\xa6\xff\xaeD\xcf\xbcj \xa7\xe3\x12\x1d\xb7\x1ff\xcb\xe7\x15'
CRITICAL 1449301277.82         _legacy:154   
```

**Comment by devos50** [comment]
@whirm I think this is a more involving issue. There are more with the hidden community right? Maybe someone working on related stuff should dedicate some time to investigate the hidden community code and see how it works and where it can be improved.

**Comment by whirm** [comment]
@devos50 definitely

@synctext This should go to the tunnel community package too. I'm thinking we should have a milestone just for that suff and we can have a special release just for that even. What do you say?

**Comment by synctext** [comment]
have not seen this in a while, closing.
