### ISSUE TITLE
exception during handle_callback for stats-request

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1657]
On Ubuntu Linux.
commit 0656bab21129317fad5f9c3df74cb1e4759a85d0
Date:   Fri Aug 28 10:36:49 2015 +0200

```
error: 'i' format requires -2147483648 <= number <= 2147483647
ERROR   1441970406.84        dispersy:1728  exception during handle_callback for stats-request
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1723, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/bartercast4/community.py", line 100, in on_stats_request
    self.create_stats_response(message.payload.stats_type, message.candidate)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/bartercast4/community.py", line 111, in create_stats_response
    payload=(stats_type, records))
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/message.py", line 525, in impl
    return self.Implementation(self, authentication_impl, resolution_impl, distribution_impl, destination_impl, payload_impl, *args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/message.py", line 362, in __init__
    self._packet = self._conversion.encode_message(self, sign=sign)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 151, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/conversion.py", line 1024, in encode_message
    payload = encode_functions.payload(message)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/bartercast4/conversion.py", line 33, in _encode_statistics_response
    packed = packed + pack("!H%dsi" % len(peer_id), len(peer_id), peer_id, value)
error: 'i' format requires -2147483648 <= number <= 2147483647
ERROR   1441972624.84        dispersy:1728  exception during handle_callback for stats-request
```

**Comment by whirm** [comment]
I guess we should disable the bartercast community until it's more tested, it doesn't make much sense to have an unused, buggy community enabled in release code.

**Comment by qstokkink** [comment]
Bartercast is no longer supported.
