### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 24: ordinal not in range(128)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1658]
```
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 604, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/list_details.py", line 937, in OnRefresh
    self._Refresh()
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/__init__.py", line 118, in invoke_func
    return func(*args, **kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/list_details.py", line 1429, in _Refresh
    for url, info in sorted(ds.get_tracker_status().items()):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 24: ordinal not in range(128)
```

**Comment by LipuFei** [comment]
@whirm I think every time we receive a torrent file, we should sanitize its tracker list first so that there will be no trackers with strange characters.

**Comment by whirm** [comment]
I guess we should make them unicode
