### ISSUE TITLE
exceptions.ValueError: metainfo not dict

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1672]
This happend I guess during normal background torrentcollecting, when my Tribler was on for a week.

commit 76ae512f675aef847ade6e78051a688e90a9dd10
Date:   Mon Sep 14 15:37:16 2015 +0200
Merge pull request #1661 from LipuFei/win_installer  
Remove "Make default for ppsp urls"

```
ERROR   1443494603.58             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 151, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/TFTP/handler.py", line 191, in _process_callbacks
    callback()
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/TFTP/handler.py", line 260, in <lambda>
    fd = session.file_data, ei = session.extra_info: cb(a, fn, fd, ei)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 35, in helper
    return func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/RemoteTorrentHandler.py", line 601, in _on_download_successful
    tdef = TorrentDef.load_from_memory(file_data)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/TorrentDef.py", line 92, in load_from_memory
    return TorrentDef._create(data)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/TorrentDef.py", line 106, in _create
    validTorrentFile(metainfo)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/utilities.py", line 20, in validTorrentFile
    raise ValueError('metainfo not dict')
exceptions.ValueError: metainfo not dict
```

**Comment by devos50** [comment]
Haven't seen this issue for a long time. Closing.
