### ISSUE TITLE
__init__() takes at least 3 arguments (2 given) on v6.5.0-rc5

### ISSUE THREAD

**Issue by noiseless** [Tribler/tribler#1692]
Hello!
I tried to run tribler (v6.5.0-rc5) on my archlinux and suffered a failure. After the start, I've seen an error message:

```python
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 174, in __init__
    s.start()
  File "/usr/share/tribler/Tribler/Core/Session.py", line 422, in start
    self.lm.register(self, self.sesslock, autoload_discovery=self.autoload_discovery)
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 102, in register
    self.session.get_torrent_store_dir())
  File "/usr/share/tribler/Tribler/Core/leveldbstore.py", line 80, in __init__
    self._db = self._leveldb(store_dir)
type: __init__() takes at least 3 arguments (2 given)
```

How to reproduce:

```bash
$ git clone --recursive https://github.com/Tribler/tribler.git
$ cd tribler
$ git checkout v6.5.0-rc5
$ ./tribler.sh
```

As I can see, LevelDB instance is created in Tribler/Core/leveldbstore.py by following code:

self._db = self._leveldb(store_dir)

But, in Tribler/Core/plyveladapter.py there are this code:

```python
    def __init__(self, state_dir, store_dir, create_if_missing=True):
        self._db = plyvel.DB(store_dir, create_if_missing=create_if_missing)
```

Also, variable "state_dir" doesn't used in this class anymore.
Changing \_\_init\_\_ to:

```python
    def __init__(self, store_dir, create_if_missing=True):
        self._db = plyvel.DB(store_dir, create_if_missing=create_if_missing)
```

fix my problem.

This is a bug or I'm doing something wrong?

**Comment by whirm** [comment]
It's a refactor bug, I've just merged a fix for this on `next` :)

**Comment by secretmylo** [comment]
I'm also getting this. As of the latest version.

    [user@localhost tribler]$ ./tribler.sh 
    Traceback (most recent call last):
      File "/home/user/Development/tribler/Tribler/Main/tribler_main.py", line 165, in __init__
        s.start()
      File "/home/user/Development/tribler/Tribler/Core/Session.py", line 422, in start
        self.lm.register(self, self.sesslock, autoload_discovery=self.autoload_discovery)
      File "/home/user/Development/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line     103, in register
        self.session.get_torrent_store_dir())
      File "/home/user/Development/tribler/Tribler/Core/leveldbstore.py", line 80, in __init__
        self._db = self._leveldb(store_dir)
    TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by whirm** [comment]
This is looks like an old version. Check out the head of  `upstream/next`
