### ISSUE TITLE
OS X Exception

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#1694]
On first run the app tried to use ~/.Tribler/ without making it first... maybe I have had it installed before and there is some partial config leftover, but it should just work not crash.

```
2015-10-28 12:08:26.000 AM kernel[0]: hfs: mounted Tribler on device disk2s2
2015-10-28 12:08:26.285 AM mds[63]: (Volume.Normal:2464) volume:0x7fcc6a11d800 ********** Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/Tribler
2015-10-28 12:09:02.000 AM kernel[0]: hfs: unmount initiated on Tribler on device disk2s2
2015-10-28 12:09:30.553 AM SIMBL Agent[36725]: warning: failed to get scripting definition from /Applications/Tribler.app; it may not be scriptable.
2015-10-28 12:09:30.578 AM Tribler[48823]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
2015-10-28 12:09:36.411 AM Tribler[48823]: Traceback (most recent call last):
2015-10-28 12:09:36.411 AM Tribler[48823]:   File "<string>", line 5, in <module>
2015-10-28 12:09:36.412 AM Tribler[48823]: ImportError: No module named csv
2015-10-28 12:09:37.397 AM Tribler[48823]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.5 instead of 10.10.5. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
2015-10-28 12:09:37.435 AM Tribler[48823]: 0   CarbonCore                          0x90295291 ___Gestalt_SystemVersion_block_invoke + 135
2015-10-28 12:09:37.435 AM Tribler[48823]: 1   libdispatch.dylib                   0x98878430 _dispatch_client_callout + 50
2015-10-28 12:09:37.436 AM Tribler[48823]: 2   libdispatch.dylib                   0x988783b7 dispatch_once_f + 251
2015-10-28 12:09:37.436 AM Tribler[48823]: 3   libdispatch.dylib                   0x98878477 dispatch_once + 31
2015-10-28 12:09:37.436 AM Tribler[48823]: 4   CarbonCore                          0x9020e69d _Gestalt_SystemVersion + 1050
2015-10-28 12:09:37.436 AM Tribler[48823]: 5   CarbonCore                          0x9020d7c0 Gestalt + 150
2015-10-28 12:09:37.436 AM Tribler[48823]: 6   libwx_macud-2.8.0.8.0.dylib         0x063f714b _Z14UMAInitToolboxtb + 43
2015-10-28 12:09:39.719 AM Tribler[48823]: GetDYLDEntryPointWithImage(/System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete,CacheDeleteCopyPurgeableSpaceWithInfo) failed.
2015-10-28 12:09:41.540 AM WindowServer[261]: disable_update_timeout: UI updates were forcibly disabled by application "Tribler" for over 1.00 seconds. Server has re-enabled them.
2015-10-28 12:09:42.561 AM WindowServer[261]: common_reenable_update: UI updates were finally reenabled by application "Tribler" after 2.02 seconds (server forcibly re-enabled them after 1.00 seconds)
2015-10-28 12:11:16.333 AM Tribler[48823]: Traceback (most recent call last):
2015-10-28 12:11:16.333 AM Tribler[48823]:   File "Tribler/Main/tribler_main.pyo", line 1112, in run
2015-10-28 12:11:16.333 AM Tribler[48823]:   File "Tribler/Main/tribler_main.pyo", line 175, in __init__
2015-10-28 12:11:16.333 AM Tribler[48823]:   File "Tribler/Main/tribler_main.pyo", line 393, in InitStage1
2015-10-28 12:11:16.333 AM Tribler[48823]:   File "Tribler/Core/DownloadConfig.pyo", line 200, in save
2015-10-28 12:11:16.333 AM Tribler[48823]:   File "Tribler/Core/Utilities/configparser.pyo", line 56, in write_file
2015-10-28 12:11:16.333 AM Tribler[48823]:   File "codecs.pyo", line 878, in open
2015-10-28 12:11:16.333 AM Tribler[48823]: IOError: [Errno 2] No such file or directory: u'/Users/Dmole/.Tribler/tribler.conf'
2015-10-28 12:16:26.792 AM SIMBL Agent[36725]: warning: failed to get scripting definition from /Applications/Tribler.app; it may not be scriptable.
2015-10-28 12:16:26.803 AM Tribler[48863]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
2015-10-28 12:16:29.133 AM Tribler[48863]: Traceback (most recent call last):
2015-10-28 12:16:29.133 AM Tribler[48863]:   File "<string>", line 5, in <module>
2015-10-28 12:16:29.133 AM Tribler[48863]: ImportError: No module named csv
2015-10-28 12:16:29.279 AM Tribler[48863]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.5 instead of 10.10.5. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
2015-10-28 12:16:29.280 AM Tribler[48863]: 0   CarbonCore                          0x90295291 ___Gestalt_SystemVersion_block_invoke + 135
2015-10-28 12:16:29.280 AM Tribler[48863]: 1   libdispatch.dylib                   0x98878430 _dispatch_client_callout + 50
2015-10-28 12:16:29.280 AM Tribler[48863]: 2   libdispatch.dylib                   0x988783b7 dispatch_once_f + 251
2015-10-28 12:16:29.280 AM Tribler[48863]: 3   libdispatch.dylib                   0x98878477 dispatch_once + 31
2015-10-28 12:16:29.280 AM Tribler[48863]: 4   CarbonCore                          0x9020e69d _Gestalt_SystemVersion + 1050
2015-10-28 12:16:29.280 AM Tribler[48863]: 5   CarbonCore                          0x9020d7c0 Gestalt + 150
2015-10-28 12:16:29.280 AM Tribler[48863]: 6   libwx_macud-2.8.0.8.0.dylib         0x063f714b _Z14UMAInitToolboxtb + 43
2015-10-28 12:16:29.368 AM Tribler[48863]: GetDYLDEntryPointWithImage(/System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete,CacheDeleteCopyPurgeableSpaceWithInfo) failed.
2015-10-28 12:16:45.280 AM Tribler[48863]: Traceback (most recent call last):
2015-10-28 12:16:45.280 AM Tribler[48863]:   File "Tribler/Main/tribler_main.pyo", line 1112, in run
2015-10-28 12:16:45.280 AM Tribler[48863]:   File "Tribler/Main/tribler_main.pyo", line 175, in __init__
2015-10-28 12:16:45.280 AM Tribler[48863]:   File "Tribler/Main/tribler_main.pyo", line 393, in InitStage1
2015-10-28 12:16:45.280 AM Tribler[48863]:   File "Tribler/Core/DownloadConfig.pyo", line 200, in save
2015-10-28 12:16:45.280 AM Tribler[48863]:   File "Tribler/Core/Utilities/configparser.pyo", line 56, in write_file
2015-10-28 12:16:45.280 AM Tribler[48863]:   File "codecs.pyo", line 878, in open
2015-10-28 12:16:45.281 AM Tribler[48863]: IOError: [Errno 2] No such file or directory: u'/Users/Dmole/.Tribler/tribler.conf'
2015-10-28 12:16:59.791 AM SIMBL Agent[36725]: warning: failed to get scripting definition from /Applications/Tribler.app; it may not be scriptable.
2015-10-28 12:16:59.802 AM Tribler[48869]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
2015-10-28 12:17:02.122 AM Tribler[48869]: Traceback (most recent call last):
2015-10-28 12:17:02.122 AM Tribler[48869]:   File "<string>", line 5, in <module>
2015-10-28 12:17:02.122 AM Tribler[48869]: ImportError: No module named csv
2015-10-28 12:17:02.271 AM Tribler[48869]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.5 instead of 10.10.5. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
2015-10-28 12:17:02.271 AM Tribler[48869]: 0   CarbonCore                          0x90295291 ___Gestalt_SystemVersion_block_invoke + 135
2015-10-28 12:17:02.271 AM Tribler[48869]: 1   libdispatch.dylib                   0x98878430 _dispatch_client_callout + 50
2015-10-28 12:17:02.271 AM Tribler[48869]: 2   libdispatch.dylib                   0x988783b7 dispatch_once_f + 251
2015-10-28 12:17:02.271 AM Tribler[48869]: 3   libdispatch.dylib                   0x98878477 dispatch_once + 31
2015-10-28 12:17:02.271 AM Tribler[48869]: 4   CarbonCore                          0x9020e69d _Gestalt_SystemVersion + 1050
2015-10-28 12:17:02.271 AM Tribler[48869]: 5   CarbonCore                          0x9020d7c0 Gestalt + 150
2015-10-28 12:17:02.271 AM Tribler[48869]: 6   libwx_macud-2.8.0.8.0.dylib         0x063f714b _Z14UMAInitToolboxtb + 43
2015-10-28 12:17:02.359 AM Tribler[48869]: GetDYLDEntryPointWithImage(/System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete,CacheDeleteCopyPurgeableSpaceWithInfo) failed.
2015-10-28 12:17:52.856 AM Tribler[48869]: Traceback (most recent call last):
2015-10-28 12:17:52.856 AM Tribler[48869]:   File "Tribler/Main/tribler_main.pyo", line 1112, in run
2015-10-28 12:17:52.856 AM Tribler[48869]:   File "Tribler/Main/tribler_main.pyo", line 175, in __init__
2015-10-28 12:17:52.856 AM Tribler[48869]:   File "Tribler/Main/tribler_main.pyo", line 399, in InitStage1
2015-10-28 12:17:52.856 AM Tribler[48869]: Exception
```

**Comment by whirm** [comment]
I see a few different errors here, I'll have a look today.

Thanks for the report!

**Comment by whirm** [comment]
Could you please check if this build works for you?

https://jenkins.tribler.org/job/Build-Tribler_OSX_next/166/

**Comment by Dmole** [comment]
Yes the app loads with that build.
side note: that link should be http because NET::ERR_CERT_AUTHORITY_INVALID

**Comment by whirm** [comment]
Great! Thanks for the testing.

Yes, it's a self signed certificate, we have to get a proper one for jenkins.
