### ISSUE TITLE
Exception on building circuits Tribler 6.5.0 RC 6

### ISSUE THREAD

**Issue by theodoor** [Tribler/tribler#1724]
Tribler crashes on building circuits. 

```The thread 0x3b9c has exited with code 0 (0x0).
Unhandled exception at 0x7265B9F0 (msvcr90.dll) in tribler.exe: 0xC0000005: Access violation reading location 0x00000020.```

**Comment by whirm** [comment]
Could you please provide all the info requested in `CONTRIBUTING.md`?

Thanks!

**Comment by theodoor** [comment]
*Version: 6.5.0 RC6
*OS: Windows 10 64 bit. 
*Step-by-step: Start up tribler, after circuits are build Tribler crashes. There are a few torrent in my tribler that are seeding and some are just added. 
*Log:
```ERROR   1447427518.61  LaunchManyCore:524   tlm: load check_point: exception while adding download <Tribler.Core.TorrentDef.TorrentDef object at 0x08FC13F0>
Traceback (most recent call last):
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 519, in resume_download
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 296, in add
AttributeError: 'NoneType' object has no attribute 'addExternalTorrent'
ERROR   1447427518.62  LaunchManyCore:524   tlm: load check_point: exception while adding download <Tribler.Core.TorrentDef.TorrentDef object at 0x08F139D0>
Traceback (most recent call last):
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 519, in resume_download
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 296, in add
AttributeError: 'NoneType' object has no attribute 'addExternalTorrent'
ERROR   1447427518.63  LaunchManyCore:524   tlm: load check_point: exception while adding download <Tribler.Core.TorrentDef.TorrentDef object at 0x09600AD0>
Traceback (most recent call last):
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 519, in resume_download
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 296, in add
AttributeError: 'NoneType' object has no attribute 'addExternalTorrent'
ERROR   1447427518.63  LaunchManyCore:524   tlm: load check_point: exception while adding download <Tribler.Core.TorrentDef.TorrentDef object at 0x0901F1B0>
Traceback (most recent call last):
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 519, in resume_download
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 296, in add
AttributeError: 'NoneType' object has no attribute 'addExternalTorrent'
ERROR   1447427518.64  LaunchManyCore:524   tlm: load check_point: exception while adding download <Tribler.Core.TorrentDef.TorrentDef object at 0x08E42B90>
Traceback (most recent call last):
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 519, in resume_download
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 296, in add
AttributeError: 'NoneType' object has no attribute 'addExternalTorrent'
ERROR   1447427518.64  LaunchManyCore:524   tlm: load check_point: exception while adding download <Tribler.Core.TorrentDef.TorrentDef object at 0x09600590>
Traceback (most recent call last):
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 519, in resume_download
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 296, in add
AttributeError: 'NoneType' object has no attribute 'addExternalTorrent'
ERROR   1447427518.64  LaunchManyCore:524   tlm: load check_point: exception while adding download <Tribler.Core.TorrentDef.TorrentDef object at 0x09600B30>
Traceback (most recent call last):
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 519, in resume_download
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 296, in add
AttributeError: 'NoneType' object has no attribute 'addExternalTorrent'
ERROR   1447427521.60    GuiDBHandler:253   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 434, in db_thread\n  File "Tribler\\Core\\CacheDB\\SqliteCacheDBHandler.pyo", line 2297, in getMyChannelId\n  File "Tribler\\dispersy\\util.pyo", line 45, in helper\n  File "Tribler\\Core\\CacheDB\\sqlitecachedb.pyo", line 372, in fetchone\n  File "Tribler\\Core\\CacheDB\\sqlitecachedb.pyo", line 300, in execute_read\n  File "Tribler\\dispersy\\util.pyo", line 45, in helper\n  File "Tribler\\Core\\CacheDB\\sqlitecachedb.pyo", line 253, in execute\n  File "Tribler\\Core\\CacheDB\\sqlitecachedb.pyo", line 186, in get_cursor\nAttributeError: \'NoneType\' object has no attribute \'cursor\'\n'
Traceback (most recent call last):
  File "wx\_core.pyo", line 14669, in <lambda>
  File "Tribler\Main\tribler_main.pyo", line 437, in wx_thread
  File "Tribler\Main\Utility\GuiDBHandler.pyo", line 254, in get
AttributeError: 'NoneType' object has no attribute 'cursor'
```
*Does not happen when I move away Appdata/.Tribler
*I have not installed any interfering software. 

Please let me know if you need more information!

**Comment by synctext** [comment]
@theodoor Thank you for those details. Strange crash...

**Comment by theodoor** [comment]
I can send you my whole %APPDATA% folder if that helps, or any more info you might want to know?

**Comment by whirm** [comment]
@theodoor could you mail me your `.Tribler/`? 
Thanks!

**Comment by theodoor** [comment]
I have mailed you my folder to the email-address found on your website.

**Comment by whirm** [comment]
@theodoor great, thx!

**Comment by lfdversluis** [comment]
@whirm I can take a look at the bug if you'd like. You mentioned something about the download path missing from the .conf file. If that's the case we could add a fall back to a default path or something.

Can you give me the .tribler folder (and what you have found out so far so I can pick up from where you are)

**Comment by whirm** [comment]
Forget about the the missing download path for now, it will only get triggered if you delete the stuff by hand and that's only done by us when debugging stuff.
I'll finish that branch when I have some time.
Just edit the paths on `tribler.conf` `libtribler.conf` and `dlcheckpoints/*` so they match with your machine instead of deleting the entries and expecting Tribler to fill them up for you.

I've mailed the .zip file to you.

**Comment by theodoor** [comment]
When I start the video player I get the following exception: 

'''Traceback (most recent call last):
  File "Tribler\Core\Video\VideoServer.pyo", line 43, in process_request_thread
  File "SocketServer.pyo", line 334, in finish_request
  File "Tribler\Core\Video\VideoServer.pyo", line 57, in __init__
  File "SocketServer.pyo", line 655, in __init__
  File "BaseHTTPServer.pyo", line 340, in handle
  File "BaseHTTPServer.pyo", line 328, in handle_one_request
  File "Tribler\Core\Video\VideoServer.pyo", line 130, in do_GET
  File "Tribler\Core\Video\VideoPlayer.pyo", line 119, in get_vod_stream
  File "Tribler\Core\Libtorrent\LibtorrentDownloadImpl.pyo", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'get_torrent_info'
Traceback (most recent call last):
  File "Tribler\Core\Video\VideoServer.pyo", line 43, in process_request_thread
  File "SocketServer.pyo", line 334, in finish_request
  File "Tribler\Core\Video\VideoServer.pyo", line 57, in __init__
  File "SocketServer.pyo", line 655, in __init__
  File "BaseHTTPServer.pyo", line 340, in handle
  File "BaseHTTPServer.pyo", line 328, in handle_one_request
  File "Tribler\Core\Video\VideoServer.pyo", line 130, in do_GET
  File "Tribler\Core\Video\VideoPlayer.pyo", line 119, in get_vod_stream
  File "Tribler\Core\Libtorrent\LibtorrentDownloadImpl.pyo", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'get_torrent_info'
'''

**Comment by lfdversluis** [comment]
@theodoor Is that with the same .tribler folder or a new one?

**Comment by theodoor** [comment]
The second error about the identifier is a new folder, I can send you this one as well if you want it :)

**Comment by lfdversluis** [comment]
Sure, I think this might be a different bug, so to be safe I can use that folder and see if I can reproduce the bug. I am now installing a windows 10 VM to make sure I match your settings.

**Comment by theodoor** [comment]
Sounds great! Where can I send it to? On your website I see only a contact form without uploading capabilities.

**Comment by lfdversluis** [comment]
Oh right, send it to {my github username} at gmail.com

**Comment by theodoor** [comment]
For some reason my .tribler folder is now 150 MB, with only one torrent. I am uploading right now to Google Drive and I will send you the link.

**Comment by lfdversluis** [comment]
Thanks, i'll await the link and take a look at it!

**Comment by whirm** [comment]
@lfdversluis You guys should focus on fixing this one so we can release 6.5. I think that would be a nice xmas gift to our users :D

**Comment by lfdversluis** [comment]
@whirm Yeah I have copied the .Tribler folder to the Proxmox, but I had to postpone it because no circuits were being built and therefore the segfault didn't trigger :p Are the leaseweb's back a.k.a. can I create circuits now?

**Comment by whirm** [comment]
Ow, I see.
I'll come by in a bit.

**Comment by whirm** [comment]
@lfdversluis the tunnel helpers are up and running now, you can continue working on this.

**Comment by whirm** [comment]
Some updates about this: The segfault happens on `msvcr90.dll` in a strlen() call made by libtorrent. It only happens when tunnels are enabled though, so the socks proxy may be passing some incorrect data to libtorrent. 

I'll build libtorrent with debugging symbols to investigate this further.

**Comment by devos50** [comment]
@whirm which version of libtorrent are you compiling? I have compiled libtorrent 1.0.7 32/64 bit files with debug symbols on the proxmox but that might not be the version that we are bundeling with Tribler.

**Comment by lfdversluis** [comment]
@whirm the current x64 builder has libtorrent 1.0.7. with debug symbols on them. Note that this is a build of current devel though.

**Comment by whirm** [comment]
@devos50 I've tried with the prebuilt 1.0.3 in case it worked but no dice (I've tried prebuilt 1.0.7 but the installer was missing the libtorrent dll, so it didn't even start).

I guess it will crash with any version we use, but you guys already told me that you couldn't reproduce it on you windows machines, so tomorrow I'll copy your libtorrent build to mine and see what I get.

**Comment by whirm** [comment]
I Forgot to update this issue, it was a bug in libtorrent, we ship the latest version on the installer now.
