### ISSUE TITLE
Internal Error at Startup (Error Report did not send)

### ISSUE THREAD

**Issue by gaenserich** [Tribler/tribler#1737]
Tribler starts its splash screen, but fails to fully launch, causing a error-report window to pop up (but the error report fails to send)

In the first text area of that window:
```
Tribler version: 6.4.3
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 210, in __init__
    s.start()
  File "/usr/share/tribler/Tribler/Core/Session.py", line 468, in start
    self.lm.register(self, self.sesslock)
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 178, in register
    self.init()
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 222, in init
    self.ltmgr = LibtorrentMgr(self.session, ignore_singleton=self.session.ignore_singleton)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 41, in __init__
    main_ltsession = self.get_session()
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 147, in get_session
    self.ltsessions[hops] = self.create_session(hops)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 124, in create_session
    ltsession.listen_on(listen_port, listen_port + 10)
RuntimeError: Die Adressfamilie wird von der Protokollfamilie nicht unterstützt
```

The second window doesn't allow me to copy and paste, but here are some of the highlights:
```
os.getcwd /usr/share/tribler
sys.executable /usr/sbin/python2
os posix
platform linux2
platform.details Linux-4.2.5-1-ARCH-x86_64-with-glibc2.2.5
platform.machine x86_64
python.version 2.7.10 (default, Sep 7 2015, 13:51:49) [GCC 5.2.0]
indebug False
sys.argv Tribler/Main/tribler.py
sys.argv --help
sys.path /usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode
sys.path /usr/lib/python2.7/site-packages/wx-2.8-gtk2-unicode
...
```

**Comment by whirm** [comment]
Could you read the issue reporting guidelines at `CONTRIBUTING.md` (shown when you created the issue) and provide the missing info please?

Thanks!

**Comment by whirm** [comment]
It would be nice if you can back up your `~/.Tribler` and see if the latest pre-release still fails for you.

**Comment by whirm** [comment]
Closing issue due to lack of feedback, please feel free to reopen it if you are still interested.
