### ISSUE TITLE
Error in windows guide for windows 10 64 bit

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1773]
While trying to install m2crypto on windows 10, 64 bit I get:

``` 
You are using pip version 7.0.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 223, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 268, in run
    wheel_cache
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 268, in populate_requirement_set
    wheel_cache=wheel_cache
  File "C:\Python27\lib\site-packages\pip\req\req_install.py", line 207, in from_line
    wheel_cache=wheel_cache)
  File "C:\Python27\lib\site-packages\pip\req\req_install.py", line 66, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2891, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', '\x97-egg')```

**Comment by whirm** [comment]
@devos50 not sure if it's a doc bug or otherwise, I'm adding the bug tag, feel free to replace it with something else.

**Comment by devos50** [comment]
This issue should be fixed in my PR.

**Comment by lfdversluis** [comment]
Was a unicode error. The check now, however, fails.
```
C:\Users\me>python -c "import M2Crypto"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\M2Crypto\__init__.py", line 22, in <module>
    import __m2crypto
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by devos50** [comment]
This issue appears to be related to missing DLLs. The virtual machine we were using didn't have the required DLL files. To solve this, we used Dependency Walker (http://www.dependencywalker.com) to find out which DLL files were missing. After downloading the Visual C++ redistributable package the error was gone. @lfdversluis will update the guide so this issue is solved.

**Comment by lfdversluis** [comment]
PR created #1865

**Comment by devos50** [comment]
@whirm can you close this one please?
