### ISSUE TITLE
Low disk space, I get it already

### ISSUE THREAD

**Issue by themusicgod1** [Tribler/tribler#1776]
If you leave tribler open for awhile with low disk space, it will open dozens of "You have low disk space" windows open. This gets to be quite the hassle closing all of them.

Tribler: 6.3.1+git20140902.9a5a2604-3
OS: Ubuntu 15.10

**Comment by whirm** [comment]
Yeah, I meant to create an issue for this but I kept forgetting.

Thanks for your report!

**Comment by whirm** [comment]
Turns out I had an unpushed partial fix for that!

@themusicgod1 could you give a try at this branch?

https://github.com/whirm/tribler/tree/stop_on_out_of_free_space

It should give you just one pop up window per download. 

It would be nice to stop all the downloads on the same file system automatically, but that would take more time and would need slightly different implementations for each OS.

**Comment by themusicgod1** [comment]
I can't get your branch to give me a popup on Ubuntu 14.04.  It silently fails when Fetching Torrent and if I didn't have the commandline open to see the error messages(coming), I'd never know that's what was happening.

**Comment by themusicgod1** [comment]
./tribler.sh	(wd: ~/tribler/tribler)
ERROR   1452277118.76        dispersy:2708  exception during handle_callback for dispersy-undo-own
Traceback (most recent call last):
  File "/home/makerspace/tribler/tribler/Tribler/dispersy/dispersy.py", line 2704, in store_update_forward
    messages[0].handle_callback(messages)
  File "/home/makerspace/tribler/tribler/Tribler/dispersy/dispersy.py", line 3878, in on_undo
    meta.undo_callback([(message.payload.member, message.payload.global_time, message.payload.packet) for message in sub_messages])
  File "/home/makerspace/tribler/tribler/Tribler/community/allchannel/community.py", line 465, in undo_votecast
    self._votecast_db.on_remove_vote_from_dispersy(channel_id, dispersy_id, redo)
  File "/home/makerspace/tribler/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 2243, in on_remove_vote_from_dispersy
    self._updateChannelVotes(channel_id)
  File "/home/makerspace/tribler/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 2321, in _updateChannelVotes
    self._db.execute_write("UPDATE _Channels SET nr_favorite = ?, nr_spam = ? WHERE id = ?", (nr_favorites, nr_spam, channel_id), commit=commit)
  File "/home/makerspace/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2369, in execute_write
    self._execute(sql, args)
  File "/home/makerspace/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2299, in invoke_func
    return func(*args, **kwargs)
  File "/home/makerspace/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2435, in _execute
    raise msg
FullError: FullError: database or disk is full

**Comment by themusicgod1** [comment]
running ./tribler.sh results in excweption

Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 87, in <module>
    __main__()
  File "Tribler/Main/tribler.py", line 77, in __main__
    run()
  File "Tribler/Main/tribler.py", line 59, in run
    from Tribler.Main.tribler_main import run as run_main
  File "/home/makerspace/tribler/tribler/Tribler/Main/tribler_main.py", line 38, in <module>
    from Tribler.Core.Upgrade.upgrade import TriblerUpgrader
  File "/home/makerspace/tribler/tribler/Tribler/Core/Upgrade/upgrade.py", line 8, in <module>
    from Tribler.Core.Upgrade.db_upgrader import DBUpgrader
  File "/home/makerspace/tribler/tribler/Tribler/Core/Upgrade/db_upgrader.py", line 17, in <module>
    from Tribler.Core.CacheDB.SqliteCacheDBHandler import TorrentDBHandler
  File "/home/makerspace/tribler/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 18, in <module>
    from Tribler.Core.CacheDB.sqlitecachedb import bin2str, str2bin
  File "/home/makerspace/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 12, in <module>
    from Tribler.dispersy.taskmanager import TaskManager
ImportError: No module named taskmanager

**Comment by whirm** [comment]
@themusicgod1 did you do a `git submodule update --init`?

**Comment by themusicgod1** [comment]
I didn't have python-requests and it seems to be a prerequisite in that branch...

**Comment by themusicgod1** [comment]
Yeah but i didn't have all the prereqs installed.  I was able to get it compiled & running (on a Ubuntu 16.04 box though ), running hard disk stress test now.

**Comment by devos50** [comment]
@whirm can you fix this one?

**Comment by whirm** [comment]
@themusicgod1 any feedback on this?

**Comment by whirm** [comment]
Closing it as the fix is on both `next` and `devel` @themusicgod1 feel free to reopen it if you still have issues.
