### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1803]
Stacktrace reported on the forums:

That's on OSX, 6.5-rc6

```
ERROR 1450111680.90 GuiDBHandler:253 'Traceback (most recent call last):\n File "Tribler\Main\Utility\GuiDBHandler.pyo", line 121, in wrapper\n File "Tribler\Main\tribler_main.pyo", line 669, in loadSessionCheckpoint\n File "Tribler\Core\Session.pyo", line 411, in load_checkpoint\n File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 454, in load_checkpoint\n File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
ERROR 1450111680.90 GuiDBHandler:270 'Traceback (most recent call last):\n File "Tribler\Main\Utility\GuiDBHandler.pyo", line 121, in wrapper\n File "Tribler\Main\tribler_main.pyo", line 669, in loadSessionCheckpoint\n File "Tribler\Core\Session.pyo", line 411, in load_checkpoint\n File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 454, in load_checkpoint\n File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
```

**Comment by lfdversluis** [comment]
Why did it close? Can you close this @whirm

**Comment by whirm** [comment]
you mean why didn't it close?
I guess you have to have permission to close it yourself?

**Comment by lfdversluis** [comment]
@whirm makes sense :+1:
