### ISSUE TITLE
"Unsupported address type" on community/tunnel/Socks5/conversion.py:149

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1817]
Found on a failed test run for #1783 

https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester/5279/testReport/Tribler.Test.test_hidden_community/TestHiddenCommunity/test_hidden_services/

```
CRITICAL 1451298521         _legacy:twisted:154  Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 248, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester@2/tribler/Tribler/community/tunnel/Socks5/server.py", line 53, in datagramReceived
    request = conversion.decode_udp_packet(data)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester@2/tribler/Tribler/community/tunnel/Socks5/conversion.py", line 221, in decode_udp_packet
    offset, destination_address = __decode_address(address_type, offset, data)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester@2/tribler/Tribler/community/tunnel/Socks5/conversion.py", line 149, in __decode_address
    raise ValueError("Unsupported address type")
exceptions.ValueError: Unsupported address type
```

**Comment by devos50** [comment]
@whirm do you have any idea what's causing this and how we could reproduce it?

**Comment by whirm** [comment]
I added added some more info for the next time this happened. I haven't catched it since then. 

I guess it was an IPV6 address. (we should really start thinking about supporting IPV6 BTW :D)

**Comment by devos50** [comment]
I haven't seen this issue in a long time, either in a test or when running Tribler regular. I will close the issue.
