### ISSUE TITLE
error when opening settings dialog

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1821]
latest next
```
h264 @ 0x7fbfbc0c2020] Missing reference picture
[h264 @ 0x7fbfbc11cb60] mmco: unref short failure
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/TopSearchPanel.py", line 158, in OnSettings
    self.guiutility.ShowPage('settings')
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/__init__.py", line 128, in invoke_func
    func(*args, **kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/GuiUtility.py", line 114, in ShowPage
    dialog = SettingsDialog()
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/settingsDialog.py", line 91, in __init__
    self._seeding_panel, self._seeding_id = self.__create_s4(tree_root, hsizer)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Main/vwxGUI/settingsDialog.py", line 653, in __create_s4
    radios[seeding_mode].SetValue(True)
KeyError: None
```

**Comment by synctext** [comment]
Confirmed fixed in latest next.
