### ISSUE TITLE
ValueError on launch

### ISSUE THREAD

**Issue by stevenroose** [Tribler/tribler#1841]
```
$ ./tribler.sh 
Traceback (most recent call last):
  File "/home/steven/git/tribler/Tribler/Main/tribler_main.py", line 992, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/home/steven/git/tribler/Tribler/Main/tribler_main.py", line 116, in __init__
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/home/steven/git/tribler/Tribler/Main/tribler_main.py", line 357, in InitStage1
    session = Session(self.sconfig, autoload_discovery=autoload_discovery)
  File "/home/steven/git/tribler/Tribler/Core/Session.py", line 119, in __init__
    self.keypair = permidmod.generate_keypair()
  File "/home/steven/git/tribler/Tribler/Core/permid.py", line 24, in generate_keypair
    ec_keypair = EC.gen_params(KEYPAIR_ECC_CURVE)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 269, in gen_params
    return EC(m2.ec_key_new_by_curve_name(curve), 1)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 106, in __init__
    assert m2.ec_key_type_check(ec), "'ec' type error"
ValueError: Received a NULL pointer.
```

I had to install a bunch of dependencies first, but ultimately, this error came up.

**Comment by stevenroose** [comment]
When I check out the latest release tag, I got this
```
$ ./tribler.sh 
ERROR   1451963672.90         tribler:52    Unable to use wxversion installed wxversions: ['3.0-gtk3']
Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 50, in <module>
    wxversion.select("2.8-unicode")
  File "/usr/lib64/python2.7/site-packages/wxversion.py", line 152, in select
    raise VersionError("Requested version of wxPython not found")
VersionError: Requested version of wxPython not found
Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 84, in <module>
    __main__()
  File "Tribler/Main/tribler.py", line 74, in __main__
    run()
  File "Tribler/Main/tribler.py", line 56, in run
    from Tribler.Main.tribler_main import run as run_main
  File "/home/steven/git/tribler/Tribler/Main/tribler_main.py", line 50, in <module>
    import wx
ImportError: No module named wx
```

Even though I installed `wxPython`.

**Comment by synctext** [comment]
thnx for this report.
M2Crypto seem to be missing EC crypto.
WXpython needs the 2.8 series.

Is this Debian?

**Comment by whirm** [comment]
@stevenroose I guess you are running a RH/Fedora based distro?

**Comment by stevenroose** [comment]
Yes, it's Fedora. Latest versions.

**Comment by devos50** [comment]
Wx3 support is still experimental. Yesterday we've added a conditional check: if wx3 is installed in the system, it is used by Tribler. If not, it falls back on wx2.8. This explains why your checkout of the latest release tag is failing.

For your first error: it seems that M2Crypto is not compiled with EC support. How did you install M2Crypto on your system?

**Comment by stevenroose** [comment]
From the Fedora package repo. It's `m2crypto-0.22.5-2.fc22.x86_64.rpm`

**Comment by whirm** [comment]
@stevenroose the m2crypto and openssl packages on Fedora are crippled due to patent-related fears. They re-enabled some ECCs recently, but not the ones Tribler needs. You can search for "fedora" on this repo to see some discussions about it.

**Comment by stevenroose** [comment]
Is a solution also discussed? I was planning on migrating away from Fedora
anyway, but that can take another several months..

**Comment by whirm** [comment]
You'll have to build your own libraries, or maybe see if anybody has created a repo with non-crippled versions of these packages?

**Comment by stevenroose** [comment]
I built m2crypto from their resource, but still got this error:
```
$ ./tribler.sh 
Traceback (most recent call last):
  File "/home/steven/git/tribler/Tribler/Main/tribler_main.py", line 992, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/home/steven/git/tribler/Tribler/Main/tribler_main.py", line 116, in __init__
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/home/steven/git/tribler/Tribler/Main/tribler_main.py", line 357, in InitStage1
    session = Session(self.sconfig, autoload_discovery=autoload_discovery)
  File "/home/steven/git/tribler/Tribler/Core/Session.py", line 119, in __init__
    self.keypair = permidmod.generate_keypair()
  File "/home/steven/git/tribler/Tribler/Core/permid.py", line 24, in generate_keypair
    ec_keypair = EC.gen_params(KEYPAIR_ECC_CURVE)
  File "/usr/lib64/python2.7/site-packages/M2Crypto-0.22.6rc3-py2.7-linux-x86_64.egg/M2Crypto/EC.py", line 269, in gen_params
    return EC(m2.ec_key_new_by_curve_name(curve), 1)
  File "/usr/lib64/python2.7/site-packages/M2Crypto-0.22.6rc3-py2.7-linux-x86_64.egg/M2Crypto/EC.py", line 106, in __init__
    assert m2.ec_key_type_check(ec), "'ec' type error"
ValueError: Received a NULL pointer.
```

**Comment by whirm** [comment]
@stevenroose you need to build openssl first and make sure m2crypto links against that.
