### ISSUE TITLE
Bug in refactored splash tick code

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1849]
That's on current `devel`
```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/jenkins/workspace/Test_tribler_devel/tribler/Tribler/Main/tribler_main.py", line 135, in on_startup_tick
    self.guiUtility.startup_splash.tick(args[0])
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16710, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the GaugeSplash object has been deleted, attribute access no longer allowed.
```

**Comment by whirm** [comment]
I guess that will also happen in `next`, better to get it fixed there and merge the fixes back to `devel`

**Comment by devos50** [comment]
On which OS does this happen? And does it happen every time?

**Comment by whirm** [comment]
I've seen it happen on a test run of `devel`, it's receiving events after the splash has been destroyed.

**Comment by devos50** [comment]
Could this be a race condition? If so, a simple if-statement to check whether the splash is not `None` should do it right?

**Comment by whirm** [comment]
Well, I don't think you should be getting update events after the splash screen is closed, right? So that would be just pushing the underlying issue under the rug.

**Comment by lfdversluis** [comment]
I would consider this 6.5 as it crashes 100% on windows. It is fixed now though :+1:

**Comment by whirm** [comment]
Oh, right, sorry

**Comment by devos50** [comment]
@whirm this one is fixed right?

**Comment by whirm** [comment]
Yup
