### ISSUE TITLE
Stacktrace while running full test suite

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1856]
``
Traceback (most recent call last):
  File "/home/laurens/Documents/thesis/tribler/Tribler/Test/test_as_server.py", line 293, in DoCheck
    if condition():
  File "/home/laurens/Documents/thesis/tribler/Tribler/Test/test_gui_dialogs.py", line 214, in has_connections_or_channel
    if self.frame.SRstatusbar.GetChannelConnections() > 10:
AttributeError: 'TestGuiDialogs' object has no attribute 'frame'
``

**Comment by whirm** [comment]
which branch is that?
