### ISSUE TITLE
Attribute error when running full test suite

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1857]
``
STraceback (most recent call last):
  File "/home/laurens/Documents/thesis/tribler/Tribler/Main/tribler_main.py", line 215, in __init__
    startWorker(consumer=None, workerFn=self.guiservthread_checkpoint_timer, delay=SESSION_CHECKPOINT_INTERVAL)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Main/Utility/GuiDBHandler.py", line 326, in startWorker
    name=jobID, delay=delay, uId=uId, retryOnBusy=retryOnBusy, priority=priority, workerType=workerType)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Main/Utility/GuiDBHandler.py", line 76, in Add
    if self.utility.abcquitting:
AttributeError: 'NoneType' object has no attribute 'abcquitting'
E..E.Traceback (most recent call last):
  File "/home/laurens/Documents/thesis/tribler/Tribler/Test/test_as_server.py", line 293, in DoCheck
    if condition():
  File "/home/laurens/Documents/thesis/tribler/Tribler/Test/test_remote_search.py", line 14, in <lambda>
    self.CallConditional(300, lambda: self.frame.SRstatusbar.GetConnections() > 0.75, callback,
AttributeError: 'TestMixedRemoteSearch' object has no attribute 'frame'
``

**Comment by whirm** [comment]
which branch is that?
