### ISSUE TITLE
Exception when closing tribler rc6

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1860]
Ran on windows 7, without virus scanner (scary!) and got the following when shutting down tribler:

Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 193] %1 is not a valid Win32 application
ERROR   1452596295.45    GuiDBHandler:253   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 434, in db_thread\n  File "Tribler\\Core\\CacheDB\\SqliteCacheDBHandler.pyo", line 2297, in getMyChannelId\n  File "Tribler\\dispersy\\util.pyo", line 45, in helper\n  File "Tribler\\Core\\CacheDB\\sqlitecachedb.pyo", line 372, in fetchone\n  File "Tribler\\Core\\CacheDB\\sqlitecachedb.pyo", line 300, in execute_read\n  File "Tribler\\dispersy\\util.pyo", line 45, in helper\n  File "Tribler\\Core\\CacheDB\\sqlitecachedb.pyo", line 253, in execute\n  File "Tribler\\Core\\CacheDB\\sqlitecachedb.pyo", line 186, in get_cursor\nAttributeError: \'NoneType\' object has no attribute \'cursor\'\n'
Traceback (most recent call last):
  File "wx\_core.pyo", line 14669, in <lambda>
  File "Tribler\Main\tribler_main.pyo", line 437, in wx_thread
  File "Tribler\Main\Utility\GuiDBHandler.pyo", line 254, in get
AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by lfdversluis** [comment]
duplicate of #1448
