### ISSUE TITLE
Incorrect config value for `emc_port`

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1924]
Report from [the forums](http://forum.tribler.org/t/tribler-6-5-rc7-ready-for-testing/3361/21):

Tribler 6.5-RC7, ubuntu 15.10 , when i try to click on the Settings button, nothing happens, and the log says:

```
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/TopSearchPanel.py", line 158, in OnSettings
self.guiutility.ShowPage('settings')
File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/__init__.py", line 128, in invoke_func
func(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/GuiUtility.py", line 122, in ShowPage
dialog = SettingsDialog()
File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/settingsDialog.py", line 92, in init
self.experimentalpanel, self.experimentalid = self._creates5(tree_root, hsizer)
File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/settingsDialog.py", line 709, in _creates5
self.emcport.SetValue(self.utility.read_config('emc_port'))
File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/widgets.py", line 439, in SetValue
wx.TextCtrl.SetValue(self, value)
File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_controls.py", line 1754, in SetValue
return controls.TextCtrl_SetValue(*args, **kwargs)
TypeError: String or Unicode type required
```
Sometimes it works when i click on it the first time, after that it wont.

**Comment by whirm** [comment]
Waiting from feedback from the user on the forum.

**Comment by synctext** [comment]
reproduced it on my Ubuntu 15.10 machine.
1) click settings
2) goto experimental -> enable Emercoin integration
3) change port number
4) try clicking on settings again, it fails

**Comment by cisf** [comment]
yes, i did activate the emercoin settings !

the log required on forum...
[cisf-tribler-9er6OynJ.log.zip](https://github.com/Tribler/tribler/files/121658/cisf-tribler-9er6OynJ.log.zip)

**Comment by synctext** [comment]
```
WARNING 1454940809.69       bootstrap:152   Could not resolve bootstrap candidate: dispersy1.st.tudelft.nl:6421
WARNING 1454940809.69       bootstrap:152   Could not resolve bootstrap candidate: dispersy2.st.tudelft.nl:6422
THIS SETTING WAS NOT DEFINED Tribler maxdownloadrate 0
THIS SETTING WAS NOT DEFINED Tribler i2ilistenport 57891
THIS SETTING WAS NOT DEFINED Tribler hide_buttons None
THIS SETTING WAS NOT DEFINED Tribler hide_columns None
THIS SETTING WAS NOT DEFINED Tribler column_sizes None
THIS SETTING WAS NOT DEFINED Tribler hide_columns None
THIS SETTING WAS NOT DEFINED Tribler column_sizes None
THIS SETTING WAS NOT DEFINED Tribler hide_columns None
THIS SETTING WAS NOT DEFINED Tribler column_sizes None
THIS SETTING WAS NOT DEFINED Tribler hide_columns None
THIS SETTING WAS NOT DEFINED Tribler column_sizes None
THIS SETTING WAS NOT DEFINED Tribler hide_columns None
THIS SETTING WAS NOT DEFINED Tribler column_sizes None
THIS SETTING WAS NOT DEFINED Tribler hide_columns None
THIS SETTING WAS NOT DEFINED Tribler column_sizes None
THIS SETTING WAS NOT DEFINED Tribler mintray 0
THIS SETTING WAS NOT DEFINED Tribler use_webui 0
WARNING 1454940812.32            util:75    0.70s <function _dispersy_claim_sync_bloom_filter_largest at 0x7f29f23500c8>
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1454940819.17       community:496   message from {192.168.1.5:7759 90.203.70.98:7759} cannot be found in the request cache, skipping it
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1454940819.76       community:496   message from {192.168.1.133:7759 87.223.64.252:7759} cannot be found in the request cache, skipping it
WARNING 1454940820.55       community:496   message from {192.168.1.12:7759 78.51.14.31:7759} cannot be found in the request cache, skipping it
WARNING 1454940820.55       community:496   message from {14.50.139.96:7759} cannot be found in the request cache, skipping it
WARNING 1454940820.56       community:496   message from {192.168.10.100:7759 39.116.204.104:7759} cannot be found in the request cache, skipping it
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
THIS SETTING WAS NOT DEFINED Tribler default_anonymity_enabled True
THIS SETTING WAS NOT DEFINED Tribler default_safeseeding_enabled True
THIS SETTING WAS NOT DEFINED Tribler showsaveas 1
THIS SETTING WAS NOT DEFINED Tribler mintray 0
THIS SETTING WAS NOT DEFINED Tribler maxdownloadrate 0
THIS SETTING WAS NOT DEFINED Tribler use_webui 0
THIS SETTING WAS NOT DEFINED Tribler webui_port 8080
THIS SETTING WAS NOT DEFINED Tribler emc_ip 127.0.0.1
TYPE OF EMC_PORT <type 'int'>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/TopSearchPanel.py", line 158, in OnSettings
    self.guiutility.ShowPage('settings')
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/__init__.py", line 128, in invoke_func
    func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/GuiUtility.py", line 122, in ShowPage
    dialog = SettingsDialog()
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/settingsDialog.py", line 92, in __init__
    self._experimental_panel, self._experimental_id = self.__create_s5(tree_root, hsizer)
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/settingsDialog.py", line 711, in __create_s5
    self._emc_port.SetValue(self.utility.read_config('emc_port'))
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/widgets.py", line 439, in SetValue
    wx.TextCtrl.SetValue(self, value)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_controls.py", line 1754, in SetValue
    return _controls_.TextCtrl_SetValue(*args, **kwargs)
TypeError: String or Unicode type required
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1454940822.31       community:496   message from {192.168.1.9:7759 83.25.87.134:7759} cannot be found in the request cache, skipping it
WARNING 1454940822.51       community:496   message from {192.168.10.100:7759 39.116.204.104:7759} cannot be found in the request cache, skipping it
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1454940822.69       community:496   message from {192.168.1.12:7759 78.51.14.31:7759} cannot be found in the request cache, skipping it
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1454940824.30       community:496   message from {192.168.1.9:7759 83.25.87.134:7759} cannot be found in the request cache, skipping it
WARNING 1454940824.36       community:496   message from {192.168.225.164:7759 24.240.22.6:7759} cannot be found in the request cache, skipping it
WARNING 1454940824.40       community:496   message from {192.168.2.12:7759 70.26.164.82:7759} cannot be found in the request cache, skipping it
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1454940826.24       community:496   message from {192.168.2.9:7759 82.168.93.26:7759} cannot be found in the request cache, skipping it
WARNING 1454940826.26       community:496   message from {192.168.10.102:7759 178.164.112.32:7759} cannot be found in the request cache, skipping it
WARNING 1454940826.27       community:496   message from {192.168.38.102:7759 92.221.92.114:26927} cannot be found in the request cache, skipping it
WARNING 1454940826.27       community:496   message from {192.168.1.12:7759 78.51.14.31:7759} cannot be found in the request cache, skipping it
WARNING 1454940826.41       community:496   message from {192.168.2.12:7759 70.26.164.82:7759} cannot be found in the request cache, skipping it
WARNING 1454940826.47       community:496   message from {192.168.1.5:7759 173.65.95.7:7759} cannot be found in the request cache, skipping it
WARNING 1454940826.51       community:496   message from {192.168.10.100:7759 39.116.204.104:7759} cannot be found in the request cache, skipping it
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1454940828.02       community:496   message from {169.254.26.127:7759 201.78.238.228:17012} cannot be found in the request cache, skipping it
WARNING 1454940828.26       community:496   message from {192.168.10.102:7759 178.164.112.32:7759} cannot be found in the request cache, skipping it
WARNING 1454940828.32       community:496   message from {192.168.1.111:7759 2.237.53.48:7759} cannot be found in the request cache, skipping it
WARNING 1454940828.34       community:496   message from {192.168.1.12:7759 100.1.116.184:7759} cannot be found in the request cache, skipping it
WARNING 1454940828.35       community:496   message from {169.254.37.24:7759 77.168.218.11:7759} cannot be found in the request cache, skipping it
WARNING 1454940828.41       community:496   message from {192.168.2.12:7759 70.26.164.82:7759} cannot be found in the request cache, skipping it
```
