### ISSUE TITLE
Trouble joining a channel with 106000 torrents

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2039]
On my Ubuntu box I found a large channel with numerous torrent files.
Joining this channel produces a Traceback and an eternal "loading, please wait" in the GUI.
Following errors are shown when running latest next branch, a3c30bfaf330c7d4f8cbffa90102673329a1edf3

Initial fix is removing this Traceback.

_Long-term fix is adding a new type of channel: without any wiki-style editing rights, consisting only of magnet links, scaling to potentially millions of items_.

```
WARNING 1458144402.23            util:75    0.75s <function _dispersy_claim_sync_bloom_filter_largest at 0x7f588b25e5f0>
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1458144403.19       community:496   message from {68.200.74.108:7759} cannot be found in the request cache, skipping it
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1458144407.07            util:75    0.59s <function _dispersy_claim_sync_bloom_filter_largest at 0x7f588b25e5f0>
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^playlist (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^dispersy-undo-other (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^dispersy-dynamic-settings (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^channel (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^dispersy-destroy-community (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^playlist (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^dispersy-undo-other (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^dispersy-dynamic-settings (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^channel (no authorization)
WARNING 1458144407.40        timeline:248   FAIL time:115693 user:3 -> permit^dispersy-destroy-community (no authorization)
WARNING 1458144410.38       community:1890  drop a 174 byte packet invalid response identifier [dispersy-introduction-response] from {83.149.70.6:6424}
WARNING 1458144410.38       community:1890  drop a 126 byte packet invalid response identifier [dispersy-introduction-response] from {83.149.70.6:6424}
WARNING 1458144410.38       community:1890  drop a 126 byte packet invalid response identifier [dispersy-introduction-response] from {83.149.70.6:6424}
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/channel.py", line 130, in do_gui
    self._on_data(total_items, nrfiltered, torrentList, playlists)
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/__init__.py", line 128, in invoke_func
    func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/channel.py", line 167, in _on_data
    self.list.SetData(playlists, torrents)
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/__init__.py", line 128, in invoke_func
    func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/vwxGUI/channel.py", line 451, in SetData
    torrent, TorrentListItem) for torrent in torrents]
KeyError: u'document'
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1458144412.11            util:75    0.63s <function _dispersy_claim_sync_bloom_filter_largest at 0x7f588b25e5f0>
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1458144412.97       community:1890  drop a 126 byte packet invalid response identifier [dispersy-introduction-response] from {83.149.70.6:6424}
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
WARNING 1458144415.30       community:1890  drop a 174 byte packet invalid response identifier [dispersy-introduction-response] from {83.149.70.6:6424}
THIS SETTING WAS NOT DEFINED Tribler seeding_mode None
```

**Comment by synctext** [comment]
Note the Dispersy warning from above log from: [_dispersy_claim_sync_bloom_filter_largest()](https://github.com/Tribler/dispersy/blob/master/community.py#L827)

**Comment by synctext** [comment]
Issues moved to: https://github.com/Tribler/tribler/issues/1150#issuecomment-368464123
