### ISSUE TITLE
Stacktrace when adding magnet link

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2066]
Apparently my magnet link I am testing with went down (within 1 minute of using it, working..) produced a frozen (grey) screen with the following trace:

```
Traceback (most recent call last):
  File "/home/laurens/Documents/thesis/tribler/Tribler/Main/vwxGUI/MainFrame.py", line 424, in startDownloadFromUrl
    tdef = TorrentDef.load_from_url(url)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/TorrentDef.py", line 136, in load_from_url
    response = requests.get(url, timeout=30, verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='tracker.bitreactor.to', port=2710): Max retries exceeded with url: /announce (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb62cd089d0>, 'Connection to tracker.bitreactor.to timed out. (connect timeout=30)'))
```

Tribler kept working, but the non-responsive GUI is a bit of a shame.

**Comment by devos50** [comment]
@whirm I would like to take a look at this one. Can you assign me?

**Comment by devos50** [comment]
The problem is related to the fact that downloading a torrent from an url is blocking. I will refactor it so it makes use of a Twisted `Agent`.

**Comment by lfdversluis** [comment]
@devos50 nope, the issue was that it was timing out, which was not catched. Refactor it to become asynchornous is indeed nice and hande (trap) the timeout exception. See my PR #2038 on how to use the redirectagent (which accepts a timeout param when constructing)

**Comment by devos50** [comment]
This one cannot happen anymore since @brussee refactored the torrent fetching system in #2423.
