### ISSUE TITLE
Stacktrace when having a duplicate download in the terminal

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2067]
Ran tribler from current `devel` with ./tribler.sh. Added a magnet link twice to test and got  an error as expected. I did however get a stacktrace in my terminal even tough Tribler itself did NOT crash.

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 217, in <lambda>
    lm_network_engine_wrapper_created_callback, pstate, initialdlstatus)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 264, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 272, in add_torrent
    raise DuplicateDownloadException()
Tribler.Core.exceptions.DuplicateDownloadException: <class 'Tribler.Core.exceptions.DuplicateDownloadException'>: None

CRITICAL 1459762524.83         _legacy:154   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 217, in <lambda>
    lm_network_engine_wrapper_created_callback, pstate, initialdlstatus)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 264, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/home/laurens/Documents/thesis/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 272, in add_torrent
    raise DuplicateDownloadException()
Tribler.Core.exceptions.DuplicateDownloadException: <class 'Tribler.Core.exceptions.DuplicateDownloadException'>: None
```

**Comment by whirm** [comment]
Don't forget to quote the stracktraces, they read way better like that

**Comment by whirm** [comment]
Did you get the dialog saying that the download was already there?

**Comment by lfdversluis** [comment]
@whirm yes

**Comment by devos50** [comment]
Since we now have an unhanded error observer that pushes crashes to the GUI over the events socket, this issue should be resolved. In fact, when a `DuplicateDownloadException` is raised during the request to add a new torrent to Tribler, the user gets a dialog that says that the download already exists.
