### ISSUE TITLE
non-ascii issues with Tribler 6.5.1

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2093]
Issue reported by user Fire in the forums:

http://forum.tribler.org/t/a-problem-about-east-asian-user-names/3420/2

```
Tribler 6.5.1 also has the same problem of 6.5.0.

I have a laptop and a desktop. I tested to install and run Tribler 6.5.1 on my computers.

64bit Korean Windows 7 were installed to my laptop and desktop. My laptop has an English computer name and my desktop has a Korean computer name.(Computer Name of Windows)

English Computer Name and English User Name: OK
English Computer Name and Korean User Name: Not run without an error message.
Korean Computer Name and English User Name or Korean User Name: Not run with an error message.

I could install and run Tribler 6.5.1 on my English user name account of my laptop. I could install it on my Korean user name account of my laptop, but it couldn't run on my Korean user name account without any error messages.

I could install Tribler 6.5.1 on my English and Korean user name accounts of my desktop, but it couldn't run with an error message, "tribler.exe.log".

Traceback (most recent call last):
File "Tribler\Main\tribler_main.pyo", line 1067, in run
File "Tribler\Main\tribler_main.pyo", line 147, in init
File "Tribler\Main\tribler_main.pyo", line 384, in InitStage1
File "Tribler\Core\Session.pyo", line 104, in init
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 0: ordinal not in range(128)

I could install and run Tribler 6.5.0 on my English user name account of my laptop. Tribler 6.5.0 could be installed but couldn't run on my Korean user name account of my desktop. I tested just two situations when I used Tribler 6.5.0, so I'm not sure the problem is same to 6.5.1. But I added "tribler.exe.log" message to this post, so you can find the problem.

And actually Tribler 6.5.1 runs on my Korean user name and English computer name laptop just for 0.1 second! But it turns off very shortly!
```

**Comment by whirm** [comment]
@lfdversluis do you want to have a look at this one?

**Comment by whirm** [comment]
Merged and manually tested on Windows and Linux.

@devos50 could you install the latest build of `next` on OSX and make sure that it works for you too?

Add non-ASCII chars in the nickname textbox on the settings window, save and restart Tribler.

**Comment by devos50** [comment]
@whirm confirmed to work on OS X.

**Comment by whirm** [comment]
thanks!
