### ISSUE TITLE
Tunnel community: CannotListenError: Couldn't listen on any:38438: [Errno 98] Address already in use.

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2109]
See https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/850/testReport/junit/Tribler.Test.test_tunnel_community_positive/TestTunnelCommunityPositive/test_anon_download/

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 190, in schedule_create_engine
    create_engine_wrapper_deferred = self.network_create_engine_wrapper(self.pstate_for_restart, initialdlstatus)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 285, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 257, in add_torrent
    ltsession = self.get_session(atp.pop('hops', 0))
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 187, in get_session
    self.ltsessions[hops] = self.create_session(hops)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 146, in create_session
    proxy_host, proxy_ports = proxy_settings[1]
exceptions.TypeError: 'NoneType' object is not iterable
```

**Comment by lfdversluis** [comment]
Maybe the one above was an error because another test messed up the state. See: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/850/artifact/output/test_runners_output/00003.err/*view*/

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py", line 458, in define_communities
    kargs=tunnel_kwargs)[0]
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/dispersy/dispersy.py", line 388, in define_auto_load
    community = community_cls.init_community(self, master, my_member, *args, **kargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/dispersy/community.py", line 226, in init_community
    community.initialize(*args, **kargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/community/tunnel/tunnel_community.py", line 302, in initialize
    self.socks_server.start()
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/community/tunnel/Socks5/server.py", line 310, in start
    self.twisted_ports.append(reactor.listenTCP(port, factory))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 478, in listenTCP
    p.startListening()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 984, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:38438: [Errno 98] Address already in use.
```

**Comment by whirm** [comment]
Quickly looking at the code, we should have a look at if the getter for this.

```
sessdefaults['tunnel_community']['socks5_listen_ports'] = [-1] * 5
```

is doing the right thing at picking the 5 random unused ports.

Also there's a hardcoded port in test_tunnel_base:

```
        self.tunnel_community.socks_server = Socks5Server(self, 1234)
```

We should go though all the tests and fix this kind of things.

**Comment by devos50** [comment]
@whirm in `test_tunnel_base`, the socks server is never started so the port does not matter.

**Comment by whirm** [comment]
Then test_tunnel_base should be cleaned up.

**Comment by synctext** [comment]
please document the stuff that was wrong with the tunnel (test) code for your thesis. can be just 4-8 lines.

**Comment by devos50** [comment]
I haven't seen this error in a long time, closing.
