### ISSUE TITLE
Test tried to insert a torrent it received from another peer shortly after closing

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2122]
I got the following stack trace:

```
Test raised 1 unhandled Twisted exceptions, last one was: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/RemoteTorrentHandler.py", line 478, in _success_callback
    self._remote_torrent_handler.save_torrent(tdef)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/dispersy/util.py", line 35, in helper
    return func(*args, **kargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/RemoteTorrentHandler.py", line 168, in save_torrent
    self.torrent_db.addExternalTorrent(tdef, extra_info={u"is_collected": 1, u"status": u"good"})
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 305, in addExternalTorrent
    self._addTorrentToDB(torrentdef, extra_info)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 407, in _addTorrentToDB
    database_dict = self._get_database_dict(torrentdef, extra_info)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 388, in _get_database_dict
    "category": self.category.calculateCategory(torrentdef.metainfo, torrentdef.get_name_as_unicode()),
exceptions.AttributeError: 'NoneType' object has no attribute 'calculateCategory'
```

Apparently, `RemoteTorrentHandler` received a torrent but the database has already been closed (i.e, the `close` method in `SQLiteCacheDBHandler.py` has been called).

**Comment by devos50** [comment]
I haven't seen this one in a while and it is definitely not present after #2555 is merged. I consider it as fixed.
