### ISSUE TITLE
Error when running tests - torrent checker seems to make a call after shutdown

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2134]
When running the tests, I came across the following error on Jenkins:

```
test_ffsearch (Tribler.Test.test_remote_search.TestMixedRemoteSearch) ... Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux@2/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux@2/tribler/Tribler/Core/Modules/tracker_manager.py", line 98, in update_tracker_info
    tracker_info = self._tracker_dict[tracker_url]
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

It seems that a call to `update_tracker_info` is being made after the shutdown has already been called.

**Comment by devos50** [comment]
This one is fixed already.
