### ISSUE TITLE
 Does not start / Crash after re-install 

### ISSUE THREAD

**Issue by EljoM** [Tribler/tribler#2158]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.md

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

6.5.1

##### Operating system and version: #####

windows 10

##### Actual behavior: #####

Install Tribler.exe 
After install Tribler should start after the last install OK. 
Tribler starts, i see a Tribler window for 0.5sec then Tribler moves so it seems below the taskbar and is gone. 

Tribler.exe win 32 process is running on background

##### Steps to reproduce the behavior: #####

as above, also with version 6.5.0

##### Relevant log file output: #####

https://forum.tribler.org/t/does-not-start-crash-after-re-install/3489
------------------------------
pymdht: utils.py py2exe: Frozen mode
pymdht: utils.py py2exe: bootstrap_stable C:\Program Files (x86)\Tribler\Tribler\Core\DecentralizedTracking\pymdht\core\bootstrap_stable
pymdht: utils.py py2exe: Frozen mode
pymdht: utils.py py2exe: bootstrap_unstable C:\Program Files (x86)\Tribler\Tribler\Core\DecentralizedTracking\pymdht\core\bootstrap_unstable
pymdht: use_cache ON!!
CRITICAL 1462125452.95 minitwisted:100 run

len(self.unstableip_port) == 5000, num_addrs: 40
ERROR 1462125452.96 LibtorrentMgr:131 LibtorrentMgr: could not restore dht state, starting from scratch
GUI started
GUI ready
GUI closing
GUI closed
ONEXIT deleting instances
Exception in thread GUITaskQueueThread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):Traceback (most recent call last):
File "Tribler\Main\tribler_main.pyo", line 1112, in run
File "Tribler\Main\tribler_main.pyo", line 175, in init
File "Tribler\Main\tribler_main.pyo", line 371, in InitStage1
File "Tribler\Main\globals.pyo", line 50, in get_default_dscfg_filename
File "ntpath.pyo", line 97, in join
TypeError: 'NoneType' object has no attribute 'getitem'
Traceback (most recent call last):
File "Tribler\Main\tribler_main.pyo", line 1112, in run
File "Tribler\Main\tribler_main.pyo", line 175, in init
File "Tribler\Main\tribler_main.pyo", line 371, in InitStage1
File "Tribler\Main\globals.pyo", line 50, in get_default_dscfg_filename
File "ntpath.pyo", line 97, in join
TypeError: 'NoneType' object has no attribute 'getitem'
Traceback (most recent call last):
File "Tribler\Main\tribler_main.pyo", line 1112, in run
File "Tribler\Main\tribler_main.pyo", line 175, in init
File "Tribler\Main\tribler_main.pyo", line 371, in InitStage1
File "Tribler\Main\globals.pyo", line 50, in get_default_dscfg_filename
File "ntpath.pyo", line 97, in join
TypeError: 'NoneType' object has no attribute 'getitem'

**Comment by whirm** [comment]
could you search your whole system for a file called "ntpath.pyo" and see if only the one on the Tribler install dir is found? It looks like the debugging infro provided doesn't match with the version of the file we bundle with Tribler.

**Comment by EljoM** [comment]
I had uninstalled the program after this problem. Closed my pc and went to bed. I red your question today and installed Tribler. I also wanted to download music from bundles.bittorrent .com /bundles/ big-gigantic and clicked on download. Tribler started normal and all problems are gone.....

**Comment by synctext** [comment]
@eljom that is great to hear! Thank you for getting back to us.

**Comment by whirm** [comment]
Hm, maybe Tribler was running while you upgraded it? v6.6 checks for Tribler to be running but 6.5.x still doesn't. That would explain some files being locked and so not replaced.

Enjoy Tribler!
