### ISSUE TITLE
[devel] I get this backtrace periodically

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2194]
##### Tribler version/branch+revision:

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel
##### Relevant log file output:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/vi/home/tribler/tribler/Tribler/Main/vwxGUI/channel.py", line 1424, in update_panel
    self.RebuildRssPanel()
  File "/home/vi/home/tribler/tribler/Tribler/Main/vwxGUI/channel.py", line 1345, in RebuildRssPanel
    self.BuildRssPanel(self.managepage, self.gridSizer)
  File "/home/vi/home/tribler/tribler/Tribler/Main/vwxGUI/channel.py", line 1297, in BuildRssPanel
    urls = my_channel_object.get_rss_feed_url_list()
AttributeError: 'NoneType' object has no attribute 'get_rss_feed_url_list'
```

**Comment by devos50** [comment]
We won't prioritise this since this issue will most probably be fixed in the new GUI.

**Comment by Nubro01** [comment]
FYI
