### ISSUE TITLE
Watchdog tripped during test (possibly due to leveldb lock)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2204]
When running the tests, I got several watchdog tripped logs, see below.

Is there something going wrong with the shutdown procedure maybe?

```
test_confirmationdialog (Tribler.Test.test_gui_dialogs.TestGuiDialogs) ... watchog wx thread *******TRIPPED!******, hasn't been set for 10.0495 secs.
disabling it and printing traces for all threads.:

*** STACKTRACE - START ***


### ThreadID: 139734143723264 Thread name: Notifier-timer-channelcast
Locals by frame, innermost last:
/usr/lib/python2.7/threading.py:359 wait:
/usr/lib/python2.7/threading.py:614 wait:
/usr/lib/python2.7/threading.py:1071 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734403770112 Thread name: Notifier-timer-activities
Locals by frame, innermost last:
/usr/lib/python2.7/threading.py:359 wait:
/usr/lib/python2.7/threading.py:614 wait:
/usr/lib/python2.7/threading.py:1071 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139735894218496 Thread name: MainThread
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py:942 OnExit:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/vwxGUI/__init__.py:122 invoke_func:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py:1062 run:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/test_as_server.py:566 startTest:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/test_gui_dialogs.py:225 test_confirmationdialog:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/test_as_server.py:81 check:
/usr/lib/python2.7/unittest/case.py:329 run:
/usr/lib/python2.7/unittest/case.py:393 __call__:
/usr/lib/python2.7/dist-packages/nose/case.py:151 runTest:
/usr/lib/python2.7/dist-packages/nose/case.py:133 run:
/usr/lib/python2.7/dist-packages/nose/case.py:45 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/core.py:62 run:
/usr/lib/python2.7/dist-packages/nose/core.py:207 runTests:
/usr/lib/python2.7/unittest/main.py:95 __init__:
|         argv = ['/usr/bin/nosetests', '-v', '--with-xcoverage', '--xunit-file=/home/jenkins/workspace/GH_Tribler_PR_tests_linux/output/7_nosetests.xml.part', '--with-xunit', '--all-modules', '--traverse-namespace', '--cover-package=Tribler', '--cover-tests', '--cover-inclusive', 'Tribler/Test/Core/Modules/RestApi/test_channels_endpoints.py', 'Tribler/Test/Core/Modules/test_watch_folder.py', 'Tribler/Test/Core/test_downloadconfig.py', 'Tribler/Test/test_tunnel_base.py', 'Tribler/Test/test_gui_dialogs.py', 'Trib...
/usr/lib/python2.7/dist-packages/nose/core.py:121 __init__:
|          env = {'BUILD_URL': 'https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/1159/', 'NOSE_TESTS_TO_RUN': 'Tribler/Test/', 'BUILD_TAG': 'jenkins-GH_Tribler_PR_tests_linux-1159', 'ghprbAuthorRepoGitUrl': 'https://github.com/devos50/tribler.git', 'TRACKER_CMD': '', 'SHELL': '/bin/bash', 'ghprbTriggerAuthorLogin': 'devos50', 'REMOTE_WORKSPACE_DIR': './', 'ghprbAddTestResults': 'false', 'ROOT_BUILD_CAUSE': 'GHPRBCAUSE', 'BUILD_NUMBER': '1159', 'XDG_RUNTIME_DIR': '/run/user/1001', 'JOB_URL': 'https://jen...
|       config = Config(addPaths=True, args=(), configSection='nosetests', debug=None, debugLog=None, env={}, exclude=None, files=[], firstPackageWins=False, getTestCaseNamesCompat=False, ignoreFiles=[<_sre.SRE_Pattern object at 0x7f16cc464cb0>, <_sre.SRE_Pattern object at 0x7f16cc3bccb0>, <_sre.SRE_Pattern object at 0x7f16cc4ffdb0>], ignoreFilesDefaultStrings=['^\\.', '^_', '^setup\\.py$'], include=None, includeExe=False, logStream=<open file '<stderr>', mode 'w' at 0x7f16cc5461e0>, loggingConfig=None, options=...
/usr/bin/nosetests:9 <module>:

### ThreadID: 139735820293888 Thread name: Twisted
Locals by frame, innermost last:
/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py:379 doPoll:
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1206 mainLoop:
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1194 run:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/twisted_thread.py:55 _reactor_runner:
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139735387465472 Thread name: PoolThread-twisted.internet.reactor-0
Locals by frame, innermost last:
/usr/lib/python2.7/threading.py:340 wait:
/usr/lib/python2.7/Queue.py:168 get:
/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py:45 work:
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734991767296 Thread name: StandaloneEndpoint
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/dispersy/endpoint.py:186 _loop:
|      packets = [(('77.224.210.78', 7759), '\x00\x02\xfb\x04\xdf\x936\x95\x87\xec\x8f\xd9\xb7EY\x18o\xa3V\xcf\xfd\xa8\xf6\x00T0R0\x10\x06\x07*\x86H\xce=\x02\x01\x06\x05+\x81\x04\x00\x1a\x03>\x00\x04\x01\x9fn\x06I\xad\xcdQi\xe3\xc1T\xff\xd1\x9d\x85\x02\xd9\x86R\xabs\xbej\x1f.X[\xa0q\x01\x9b\x99\xa9\xfe\xf0\xebV^\xf3oSa\xdeb\x87\xfa\xd9ka\x83q\x08jC\xf1g(\xc1\x1f\x00\x00\x00\x00\x00\x01\xa9\x7f\x91^>\xb6\x86\xfc\xc0\xa8\x01k\x1eOM\xe0\xd2N\x1eO\x01p\xa0\x00,m\x19U\xcf\x00a\xe7ntD\x9a=\x1b\x89\xd5\x94\x7f\xfbD\xb7...
|         data = '\x00\x02\xfb\x04\xdf\x936\x95\x87\xec\x8f\xd9\xb7EY\x18o\xa3V\xcf\xfd\xa8\xf6\x00T0R0\x10\x06\x07*\x86H\xce=\x02\x01\x06\x05+\x81\x04\x00\x1a\x03>\x00\x04\x01\x9fn\x06I\xad\xcdQi\xe3\xc1T\xff\xd1\x9d\x85\x02\xd9\x86R\xabs\xbej\x1f.X[\xa0q\x01\x9b\x99\xa9\xfe\xf0\xebV^\xf3oSa\xdeb\x87\xfa\xd9ka\x83q\x08jC\xf1g(\xc1\x1f\x00\x00\x00\x00\x00\x01\xa9\x7f\x91^>\xb6\x86\xfc\xc0\xa8\x01k\x1eOM\xe0\xd2N\x1eO\x01p\xa0\x00,m\x19U\xcf\x00a\xe7ntD\x9a=\x1b\x89\xd5\x94\x7f\xfbD\xb7\xdb\xfedZi\xa5|\xd8\x0046\...
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734845519616 Thread name: DHT
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py:181 run_one_step:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py:103 run2:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py:91 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139735405561600 Thread name: WatchDog
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/instrumentation.py:184 print_all_stacks:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/instrumentation.py:153 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734493800192 Thread name: VideoHTTPServerThread-1
Locals by frame, innermost last:
/usr/lib/python2.7/SocketServer.py:155 _eintr_retry:
/usr/lib/python2.7/SocketServer.py:236 serve_forever:
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734837126912 Thread name: StandaloneEndpoint
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/dispersy/endpoint.py:186 _loop:
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

*** STACKTRACE - END ***

ok
test_debugframe (Tribler.Test.test_gui_dialogs.TestGuiDialogs) ... Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py", line 154, in __init__
    s.start()
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Session.py", line 436, in start
    self.lm.register(self, self.sesslock, autoload_discovery=self.autoload_discovery)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 107, in register
    self.torrent_store = LevelDbStore(self.session.get_torrent_store_dir())
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/leveldbstore.py", line 84, in __init__
    self._db = self._leveldb(os.path.relpath(store_dir, os.getcwdu()))
LevelDBError: IO error: lock collected_torrents/LOCK: already held by process
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 213, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/dispersy/discovery/community.py", line 783, in clean_and_save
    with open(self.filename, 'w') as fp:
exceptions.IOError: [Errno 2] No such file or directory: u'/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tmp/tmp2rBWyq_tribler_test_session/dot.Tribler/peercache.txt'
Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py", line 922, in OnExit
    torrent_db._db.clean_db(randint(0, 24) == 0, exiting=True)
AttributeError: 'NoneType' object has no attribute '_db'
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/vwxGUI/__init__.py", line 122, in invoke_func
    func(*args, **kwargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py", line 928, in OnExit
    self.utility.session.shutdown(hacksessconfcheckpoint=False)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Session.py", line 446, in shutdown
    deferred = self.lm.early_shutdown()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 633, in early_shutdown
    self.version_check_manager.stop()
exceptions.AttributeError: 'NoneType' object has no attribute 'stop'
watchog wx thread *******TRIPPED!******, hasn't been set for 10.1882 secs.
disabling it and printing traces for all threads.:

*** STACKTRACE - START ***


### ThreadID: 139734403770112 Thread name: Notifier-timer-channelcast
Locals by frame, innermost last:
/usr/lib/python2.7/threading.py:359 wait:
/usr/lib/python2.7/threading.py:614 wait:
/usr/lib/python2.7/threading.py:1071 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139735405561600 Thread name: WatchDog
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/instrumentation.py:184 print_all_stacks:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/instrumentation.py:153 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139735387465472 Thread name: PoolThread-twisted.internet.reactor-0
Locals by frame, innermost last:
/usr/lib/python2.7/threading.py:340 wait:
/usr/lib/python2.7/Queue.py:168 get:
/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py:45 work:
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139735894218496 Thread name: MainThread
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py:942 OnExit:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/vwxGUI/__init__.py:122 invoke_func:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py:1062 run:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/test_as_server.py:566 startTest:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/test_gui_dialogs.py:247 test_debugframe:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/test_as_server.py:81 check:
/usr/lib/python2.7/unittest/case.py:329 run:
/usr/lib/python2.7/unittest/case.py:393 __call__:
/usr/lib/python2.7/dist-packages/nose/case.py:151 runTest:
/usr/lib/python2.7/dist-packages/nose/case.py:133 run:
/usr/lib/python2.7/dist-packages/nose/case.py:45 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/suite.py:224 run:
/usr/lib/python2.7/dist-packages/nose/suite.py:177 __call__:
/usr/lib/python2.7/dist-packages/nose/core.py:62 run:
/usr/lib/python2.7/dist-packages/nose/core.py:207 runTests:
/usr/lib/python2.7/unittest/main.py:95 __init__:
|         argv = ['/usr/bin/nosetests', '-v', '--with-xcoverage', '--xunit-file=/home/jenkins/workspace/GH_Tribler_PR_tests_linux/output/7_nosetests.xml.part', '--with-xunit', '--all-modules', '--traverse-namespace', '--cover-package=Tribler', '--cover-tests', '--cover-inclusive', 'Tribler/Test/Core/Modules/RestApi/test_channels_endpoints.py', 'Tribler/Test/Core/Modules/test_watch_folder.py', 'Tribler/Test/Core/test_downloadconfig.py', 'Tribler/Test/test_tunnel_base.py', 'Tribler/Test/test_gui_dialogs.py', 'Trib...
/usr/lib/python2.7/dist-packages/nose/core.py:121 __init__:
|          env = {'BUILD_URL': 'https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/1159/', 'NOSE_TESTS_TO_RUN': 'Tribler/Test/', 'BUILD_TAG': 'jenkins-GH_Tribler_PR_tests_linux-1159', 'ghprbAuthorRepoGitUrl': 'https://github.com/devos50/tribler.git', 'TRACKER_CMD': '', 'SHELL': '/bin/bash', 'ghprbTriggerAuthorLogin': 'devos50', 'REMOTE_WORKSPACE_DIR': './', 'ghprbAddTestResults': 'false', 'ROOT_BUILD_CAUSE': 'GHPRBCAUSE', 'BUILD_NUMBER': '1159', 'XDG_RUNTIME_DIR': '/run/user/1001', 'JOB_URL': 'https://jen...
|       config = Config(addPaths=True, args=(), configSection='nosetests', debug=None, debugLog=None, env={}, exclude=None, files=[], firstPackageWins=False, getTestCaseNamesCompat=False, ignoreFiles=[<_sre.SRE_Pattern object at 0x7f16cc464cb0>, <_sre.SRE_Pattern object at 0x7f16cc3bccb0>, <_sre.SRE_Pattern object at 0x7f16cc4ffdb0>], ignoreFilesDefaultStrings=['^\\.', '^_', '^setup\\.py$'], include=None, includeExe=False, logStream=<open file '<stderr>', mode 'w' at 0x7f16cc5461e0>, loggingConfig=None, options=...
/usr/bin/nosetests:9 <module>:

### ThreadID: 139735820293888 Thread name: Twisted
Locals by frame, innermost last:
/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py:396 doPoll:
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1206 mainLoop:
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1194 run:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/twisted_thread.py:55 _reactor_runner:
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734837126912 Thread name: StandaloneEndpoint
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/dispersy/endpoint.py:186 _loop:
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734845519616 Thread name: DHT
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py:159 run_one_step:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py:103 run2:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py:91 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734493800192 Thread name: VideoHTTPServerThread-1
Locals by frame, innermost last:
/usr/lib/python2.7/SocketServer.py:155 _eintr_retry:
/usr/lib/python2.7/SocketServer.py:236 serve_forever:
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

### ThreadID: 139734991767296 Thread name: StandaloneEndpoint
Locals by frame, innermost last:
/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/dispersy/endpoint.py:186 _loop:
|      packets = [(('77.224.210.78', 7759), '\x00\x02\xfb\x04\xdf\x936\x95\x87\xec\x8f\xd9\xb7EY\x18o\xa3V\xcf\xfd\xa8\xf6\x00T0R0\x10\x06\x07*\x86H\xce=\x02\x01\x06\x05+\x81\x04\x00\x1a\x03>\x00\x04\x01\x9fn\x06I\xad\xcdQi\xe3\xc1T\xff\xd1\x9d\x85\x02\xd9\x86R\xabs\xbej\x1f.X[\xa0q\x01\x9b\x99\xa9\xfe\xf0\xebV^\xf3oSa\xdeb\x87\xfa\xd9ka\x83q\x08jC\xf1g(\xc1\x1f\x00\x00\x00\x00\x00\x01\xa9\x7f\x91^>\xb6\x86\xfc\xc0\xa8\x01k\x1eOM\xe0\xd2N\x1eO\x01p\xa0\x00,m\x19U\xcf\x00a\xe7ntD\x9a=\x1b\x89\xd5\x94\x7f\xfbD\xb7...
|         data = '\x00\x02\xfb\x04\xdf\x936\x95\x87\xec\x8f\xd9\xb7EY\x18o\xa3V\xcf\xfd\xa8\xf6\x00T0R0\x10\x06\x07*\x86H\xce=\x02\x01\x06\x05+\x81\x04\x00\x1a\x03>\x00\x04\x01\x9fn\x06I\xad\xcdQi\xe3\xc1T\xff\xd1\x9d\x85\x02\xd9\x86R\xabs\xbej\x1f.X[\xa0q\x01\x9b\x99\xa9\xfe\xf0\xebV^\xf3oSa\xdeb\x87\xfa\xd9ka\x83q\x08jC\xf1g(\xc1\x1f\x00\x00\x00\x00\x00\x01\xa9\x7f\x91^>\xb6\x86\xfc\xc0\xa8\x01k\x1eOM\xe0\xd2N\x1eO\x01p\xa0\x00,m\x19U\xcf\x00a\xe7ntD\x9a=\x1b\x89\xd5\x94\x7f\xfbD\xb7\xdb\xfedZi\xa5|\xd8\x0046\...
/usr/lib/python2.7/threading.py:754 run:
/usr/lib/python2.7/threading.py:801 __bootstrap_inner:
/usr/lib/python2.7/threading.py:774 __bootstrap:

*** STACKTRACE - END ***
```

**Comment by devos50** [comment]
Haven't seen this watchdog error in a very long time so I'm considering this issue as fixed. The described GUI test also got removed by now.
