### ISSUE TITLE
Paths fo torrents are decoded as utf-8 which may lead to an error

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2236]
Problem is in line ` File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/APIImplementation/maketorrent.py", line 246, in pathlist2filename
    return fullpath.decode('utf-8')`

It will lead to a `exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 62: invalid continuation byte` if it's not utf-8. Many alphabets will cause a crash thus. Should be encoded and decoded as unicode/utf-16 or so I guess.

**Comment by whirm** [comment]
How did you trigger this?

**Comment by lfdversluis** [comment]
I got it from a test run this morning. https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/1430/testReport/junit/Tribler.Test.test_remote_search/TestRemoteChannelSearch/test_channel_search/

**Comment by whirm** [comment]
For future reference:

```
Test raised 1 unhandled Twisted exceptions, last one was: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/RemoteTorrentHandler.py", line 472, in _success_callback
    tdef = TorrentDef.load_from_dict(meta_info)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/TorrentDef.py", line 153, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/TorrentDef.py", line 109, in _create
    maketorrent.copy_metainfo_to_input(t.metainfo, t.input)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/APIImplementation/maketorrent.py", line 334, in copy_metainfo_to_input
    outpath = pathlist2filename(file['path'])
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/APIImplementation/maketorrent.py", line 246, in pathlist2filename
    return fullpath.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 62: invalid continuation byte
```

**Comment by whirm** [comment]
utf-16 would be just guessing again, I guess the nicest way would be to use `chardet` as we will be receiving torrents of all sorts.
