### ISSUE TITLE
StackTrace triggered by multichain due to "Missing member"

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2262]
Running Devel on Ubuntu and doing an anonymous download. Circuits are less then 400 seconds old.

commit 03685f3cf5895aa69060da213959d2b862cc2506
Merge: 9a98642 1699f1b
Author: Elric Milon whirm@users.noreply.github.com
Date:   Mon Jun 6 15:42:25 2016 +0200

```
Merge pull request #2261 from lfdversluis/issue-2259-tunnel-helper-exit-node-flag

Made the exit node option a flag rather instead of argument.
```

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/multichain/community.py", line 392, in on_tunnel_remove
    self.schedule_block(candidate, bytes_up, bytes_down)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/multichain/community.py", line 139, in schedule_block
    self.publish_signature_request_message(candidate, total_amount_sent_mb, total_amount_received_mb)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/multichain/community.py", line 153, in publish_signature_request_message
    message = self.create_signature_request_message(candidate, up, down)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/multichain/community.py", line 178, in create_signature_request_message
    payload=payload)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/message.py", line 525, in impl
    return self.Implementation(self, authentication_impl, resolution_impl, distribution_impl, destination_impl, payload_impl, *args, **kargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/message.py", line 366, in __init__
    self._conversion.decode_message(LoopbackCandidate(), self._packet, verify=sign, allow_empty_signature=True)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/conversion.py", line 1202, in decode_message
    decode_functions.authentication(placeholder)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/conversion.py", line 1121, in _decode_double_member_authentication
    raise DelayPacketByMissingMember(self._community, member_id)
Tribler.dispersy.message.DelayPacketByMissingMember: Missing member

```

**Comment by pimveldhuisen** [comment]
This is essentially expected behavior as long as we have a tunnel community with a mix of multichain and non-multichain members. Tribler attempts to send a multichain request to someone it made a tunnel with, but it fails to find this member in the multichain community. It might need to be handled better though, did this actually crash Tribler or just show up in the terminal?

**Comment by devos50** [comment]
@pimveldhuisen this will crash in Tribler 7. Recently, this error got reported by one of our alpha testers.

I guess it's not that hard to fix: if our other target member is not in the multichain community, we should catch the exception and log it.
