### ISSUE TITLE
Exception on current devel

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2271]
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/Test_tribler_devel@2/tribler/Tribler/Main/tribler_main.py", line 1010, in run
    abc.OnExit()
  File "/home/jenkins/workspace/Test_tribler_devel@2/tribler/Tribler/Main/vwxGUI/__init__.py", line 122, in invoke_func
    func(*args, **kwargs)
  File "/home/jenkins/workspace/Test_tribler_devel@2/tribler/Tribler/Main/tribler_main.py", line 841, in OnExit
    self.i2i_server.stop()
  File "/home/jenkins/workspace/Test_tribler_devel@2/tribler/Tribler/Utilities/Instance2Instance.py", line 48, in stop
    return self.listenport.stopListening()
AttributeError: 'NoneType' object has no attribute 'stopListening
```

https://jenkins.tribler.org/job/Test_tribler_devel/1292/testReport/junit/Tribler.Test.test_i2i_download/TestI2IDownload/test_i2i_running/

Weird line in there:

```
DEBUG   1465393086    GuiDBHandler:GUIDBProducer:99   GUIDBHandler: adding Task(tribler_main.py:195 (__init__))
CRITICAL 1465393086         _legacy:twisted:154  Unhandled error in Deferred:
CRITICAL 1465393086         _legacy:twisted:154  
```

**Comment by devos50** [comment]
I haven't seen this error in a very long time and we removed the I2I server anyway so this should never happen again.
