### ISSUE TITLE
Tribler cannot send half-signed multichain blocks to the multichain crawler

### ISSUE THREAD

**Issue by pimveldhuisen** [Tribler/tribler#2282]
You might come across this error in the multichain branch:

`ERROR   1465723300.46        dispersy:1747  exception during handle_callback for crawl_request
Traceback (most recent call last):
  File "/home/pim/Tribler/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/home/pim/Tribler/tribler/Tribler/community/multichain/community.py", line 290, in received_crawl_request
    self.crawl_requested(message.candidate, message.payload.requested_sequence_number)
  File "/home/pim/Tribler/tribler/Tribler/community/multichain/community.py", line 300, in crawl_requested
    payload=block.to_payload()) for block in blocks]
  File "/home/pim/Tribler/tribler/Tribler/dispersy/message.py", line 525, in impl
    return self.Implementation(self, authentication_impl, resolution_impl, distribution_impl, destination_impl, payload_impl, *args, **kargs)
  File "/home/pim/Tribler/tribler/Tribler/dispersy/message.py", line 362, in __init__
    self._packet = self._conversion.encode_message(self, sign=sign)
  File "/home/pim/Tribler/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pim/Tribler/tribler/Tribler/dispersy/conversion.py", line 994, in encode_message
    payload = encode_functions.payload(message)
  File "/home/pim/Tribler/tribler/Tribler/community/multichain/conversion.py", line 128, in _encode_crawl_response
    return encode_block_crawl(payload),
  File "/home/pim/Tribler/tribler/Tribler/community/multichain/conversion.py", line 220, in encode_block_crawl
    payload.public_key_responder, payload.signature_responder))
error: integer out of range for 'Q' format code`

This is the result of Tribler trying to send a half-signed block to the crawler.
Since we initiate the responder part of a block with -1 as an (explicitly invalid) placeholder for the total_up_responder en total_down_responder, this leads to a value error when encoding this as an unsigned int.

I see at least 2 potential solutions:
1) Switching to a half-block database system ("true halves")
2) Using a value of 0 as a placeholder. This makes it harder to recognize the value as invalid, but this should be possible by checking the 'previous_hash_responder' for an invalid hash.

(I can be assigned to this issue)

**Comment by pimveldhuisen** [comment]
@Captain-Coder Do you foresee any problems with solution 2?

**Comment by synctext** [comment]
if this creates a small need to upgrade the DB code, we could..

**Comment by Captain-Coder** [comment]
It seems identifying half signed blocks is done by checking against the responder hash being empty. In such cases the values in the responder total_up/total_down are very much "don't care".

Another option would be to:
3) use the max value of the Q format code (unsigned 64 bits iirc) as "invalid" (encoded as all 1s), but this is less attractive from a python point of view since python can handle arbitrary large numbers. So it is not the last number of the range of allowed numbers.
4) switch the format to signed values, for now no one will hit the cap before we change the master member again in a more final release.

**Comment by pimveldhuisen** [comment]
I will implement a switch to 0 by default then. Switching to unsigned seems like a waste of a bit and to make the format less intuitive/elegant.
