### ISSUE TITLE
REST API throws errors in console when performing a torrent search

### ISSUE THREAD

**Issue by pimveldhuisen** [Tribler/tribler#2287]
When searching for any string in the Tribler gui, I get this error:

`Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/pim/Tribler/tribler/Tribler/Core/Modules/restapi/events_endpoint.py", line 57, in on_search_results_torrents
    "result": convert_db_torrent_to_json(torrent)}) + '\n')
  File "/home/pim/Tribler/tribler/Tribler/Core/Modules/restapi/util.py", line 20, in convert_db_torrent_to_json
    return {"id": torrent[0], "infohash": torrent[1].encode('hex'), "name": torrent[2], "size": torrent[3],
exceptions.KeyError: 0`

The search does work, but this should probably be fixed or handled.

**Comment by pimveldhuisen** [comment]
@devos50 ?

**Comment by devos50** [comment]
@pimveldhuisen I'm aware of the issue but thanks for reporting it! It is due to the fact that remote torrent results are not handled correctly yet since they have a totally different format than torrents in the local database. I've fixed it already in #2264 but that's waiting for another fix. I will create this tomorrow morning and try to get it merged. After that, this issue is solved.

**Comment by pimveldhuisen** [comment]
@devos50 Allright, it's no problem for me specifically, just thought it would be good for you to know :)
