### ISSUE TITLE
Error when running test on devel (due to DefaultDownloadStartupConfig singleton)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2289]
When running tests on devel, the following error is raised:

```
nosetests Tribler/Test/Core -xv
...
test_convert_default_download_config (Tribler.Test.Core.Upgrade.test_pickle_converter.TestPickleConverter) ... ERROR

======================================================================
ERROR: test_convert_default_download_config (Tribler.Test.Core.Upgrade.test_pickle_converter.TestPickleConverter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler_endpoints/Tribler/Test/test_as_server.py", line 81, in check
    result = fun(*argv, **kwargs)
  File "/Users/martijndevos/Documents/tribler_endpoints/Tribler/Test/Core/Upgrade/test_pickle_converter.py", line 43, in test_convert_default_download_config
    PickleConverter(self.mock_session).convert_default_download_config()
  File "/Users/martijndevos/Documents/tribler_endpoints/Tribler/Core/Upgrade/pickle_converter.py", line 136, in convert_default_download_config
    ddsconfig = DefaultDownloadStartupConfig()
  File "/Users/martijndevos/Documents/tribler_endpoints/Tribler/Core/DownloadConfig.py", line 225, in __init__
    raise RuntimeError("DefaultDownloadStartupConfig is singleton")
RuntimeError: DefaultDownloadStartupConfig is singleton
```

**Comment by ardhipoetra** [comment]
Second this. 

One of the workaround is to delete the instance of `DefaultDownloadStartupConfig` in `tearDown`. I used an instance in a class, and need to manually invalidate it in my test case.

**Comment by devos50** [comment]
@ardhipoetra I will PR a fix today ;)
