### ISSUE TITLE
Error on mac when running credit mining test

### ISSUE THREAD

**Issue by ardhipoetra** [Tribler/tribler#2303]
This error sometime occurs in PR #2064. It seems there is a race condition, but I can't find exactly the problem. 
```
======================================================================
ERROR: test rss source
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Test/Core/CreditMining/test_creditmining_sys.py", line 229, in tearDown
    super(TestBoostingManagerSysRSS, self).tearDown()
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Test/Core/CreditMining/test_creditmining_sys.py", line 84, in tearDown
    super(TestBoostingManagerSys, self).tearDown()
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Test/test_as_server.py", line 284, in tearDown
    super(TestAsServer, self).tearDown(annotate=False)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Core/Utilities/twisted_thread.py", line 157, in g
    d = func(*args, **kargs)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Test/test_as_server.py", line 168, in tearDown
    process_unhandled_twisted_exceptions()
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Test/util.py", line 130, in check_exceptions
    % (num_twisted_exceptions, self._twisted_exceptions[-1]['log_text']))
Exception: Test raised 5 unhandled Twisted exceptions, last one was: Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Core/Libtorrent/__init__.py", line 27, in <lambda>
    lambda_f = lambda a = args, kwa = kwargs: invoke_func(*a, **kwa)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Core/Libtorrent/__init__.py", line 28, in invoke_func
    download.session.lm.threadpool.add_task(lambda_f, 1)
exceptions.AttributeError: 'NoneType' object has no attribute 'add_task'
```

**Comment by devos50** [comment]
I haven't encountered this error in the tests after many runs. Also, the `add_task` method got removed in #2573.
