### ISSUE TITLE
Error in API tests

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2307]
```
Testing whether the API returns a formatted 500 error if ValueError is raised ... Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Utilities\twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\APIImplementation\threadpoolmanager.py", line 50, in caller
    fun(*args, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Libtorrent\LibtorrentMgr.py", line 482, in do_dht_check
    lt_session = self.get_session()
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Libtorrent\LibtorrentMgr.py", line 186, in get_session
    if hops not in self.ltsessions:
exceptions.TypeError: argument of type 'NoneType' is not iterable
```

Reference: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win64/1528/artifact/output/test_runners_output/0.err/*view*/

**Comment by lfdversluis** [comment]
Investigated this bug. Line 482 is invoked by the taskmanager, however after shutdown. 

`_task_check_dht` only gets called by `_schedule_next_check` which registers this call on the taskmanager. The shutdown function has `self.cancel_all_pending_tasks()` so that seems to be ok.
` self.ltsessions` can only be set to `None` in the `shutdown` function, so this error seems to be unlucky timing?
