### ISSUE TITLE
log:443   Unhandled Error

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2312]
Running bleeding edge devel on an Ubuntu 14.04 box, straight from the cmdline.
Multi-chain enabled. I think I was on the main search page. Suddenly a freeze and complete lockup. Waited 2+ minutes, but Tribler died.

commit b72db1ace90bef7cc6504dcea8891e9c10eee3c6
Merge: 588dad4 b63b518
Author: Elric Milon whirm@users.noreply.github.com
Date:   Fri Jun 17 15:07:53 2016 +0200

```
Merge pull request #2310 from pimveldhuisen/multichain-half-signed-value-fix

Multichain half signed value fix
```

```
~/GIT-pulls/tribler$ env PYTHONPATH=.:"$PYTHONPATH" python Tribler/Main/tribler.py
ERROR   1466273085.94             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 324, in connectionLost
    self.protocol.doStop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 683, in doStop
    assert self.numPorts > 0
exceptions.AssertionError: 

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 324, in connectionLost
    self.protocol.doStop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 683, in doStop
    assert self.numPorts > 0
exceptions.AssertionError: 
```

**Comment by devos50** [comment]
I haven't seen this issue in a long time so I'm closing it. Feel free to reopen when it pops up again.
