### ISSUE TITLE
exceptions.AttributeError: 'Port' object has no attribute 'socket'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2315]
New error I've never seen before. Pulled the latest devel and running on Ubuntu 14.04.

commit 3729f7e05b06b076bfeb69ba3463435cbeb3b428
Merge: b72db1a b306cd5
Author: Elric Milon whirm@users.noreply.github.com
Date:   Mon Jun 20 11:01:46 2016 +0200
    Merge pull request #2269 from Captain-Coder/twistd_crawler  
    Made crawler into twistd plugin and systemd service unit

```
INFO    1466445043.99       community:308   initializing:  MultiChainCommunity
WARNING 1466445065.35       community:1890  drop a 126 byte packet invalid response identifier [dispersy-introduction-response] from {131.180.27.155:6423}
WARNING 1466445096.47       community:1890  drop a 126 byte packet invalid response identifier [dispersy-introduction-response] from {131.180.27.155:6423}
WARNING 1466445149.92       community:1890  drop a 129 byte packet invalid puncture identifier [dispersy-puncture] from {95.211.155.142:50638}
WARNING 1466445149.92       community:1890  drop a 126 byte packet invalid response identifier [dispersy-introduction-response] from {83.149.70.6:6424}
ERROR   1466445181.50             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 325, in connectionLost
    self.socket.close()
exceptions.AttributeError: 'Port' object has no attribute 'socket'

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 325, in connectionLost
    self.socket.close()
exceptions.AttributeError: 'Port' object has no attribute 'socket'
```

**Comment by devos50** [comment]
@synctext have you seen this error recently? I guess this one is caused by the UDP tracker lookups done by our torrent health checker. Chances are that this one got fixed after refactoring of that module.

**Comment by devos50** [comment]
I think it's fixed since I haven't received reports about this error anymore.
