### ISSUE TITLE
Links on the README of the Tribler repo are broken

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2320]
They redirect to http://tribler.readthedocs.io/en/devel/contributing.html which does not exist.

**Comment by devos50** [comment]
Ah, the `readthedocs` hook is probably configured incorrectly. @whirm I believe you own the account that maintains the readthedocs entries of Tribler right? Can you take a look?

**Comment by whirm** [comment]
There's nothing to configure, you either have the hook or you don't.

**Comment by whirm** [comment]
From the readthedocs log:
```
python -mvirtualenv --no-site-packages /home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel
python /home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/tribler/.cache/pip sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1
cat conf.py
python /home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/local/lib/python2.7/site-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/local/lib/python2.7/site-packages/sphinx/application.py", line 435, in setup_extension
    err)
ExtensionError: Could not import extension sphinxcontrib.httpdomain (exception: No module named sphinxcontrib.httpdomain)

Extension error:
Could not import extension sphinxcontrib.httpdomain (exception: No module named sphinxcontrib.httpdomain)
```

**Comment by q155128** [comment]
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 318, in saveAll
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\MainFrame.pyo", line 648, in Restart
pywintypes.error: (2, 'FindExecutable', '\xcf\xb5\xcd\xb3\xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xce\xc4\xbc\xfe\xa1\xa3')
Traceback (most recent call last):
  File "Tribler\Main\Dialogs\CreateTorrentDialog.pyo", line 248, in create_torrents
  File "Tribler\Core\Utilities\torrent_utils.pyo", line 60, in create_torrent_file
RuntimeError: 系统找不到指定的路径。
Traceback (most recent call last):
  File "Tribler\Main\Dialogs\CreateTorrentDialog.pyo", line 252, in create_torrents
  File "Tribler\Core\Utilities\torrent_utils.pyo", line 57, in create_torrent_file
ArgumentError: Python argument types in
    create_torrent.add_url_seed(create_torrent, list)
did not match C++ signature:
    add_url_seed(struct libtorrent::create_torrent {lvalue}, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)
Traceback (most recent call last):
  File "Tribler\Main\Dialogs\CreateTorrentDialog.pyo", line 248, in create_torrents
  File "Tribler\Core\Utilities\torrent_utils.pyo", line 60, in create_torrent_file
RuntimeError: 系统找不到指定的路径。
 win7 x64

**Comment by whirm** [comment]
@q155128 please create issues for problems unrelated to this one (also, please read CONTRIBUTING.rst).

**Comment by devos50** [comment]
@whirm I'm using the `sphinxcontrib-httpdomain` package for the HTTP API rendering part so it's required to build the packages. Apparently, you can add a pip-file or something in the admin settings of `readthedocs` as described [here](https://github.com/rtfd/readthedocs.org/issues/479). Could you please try that and add `sphinxcontrib-httpdomain2` to it?

**Comment by whirm** [comment]
@devos50 it now looks for a requirements file at `doc/requirements` please, make a PR adding that.
