### ISSUE TITLE
exceptions.AttributeError: 'NoneType' object has no attribute 'execute'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2327]
Error upon Tribler close when running bleeding edge Devel on Ubuntu 14.04.

git log |head
commit 113ff1bdd6a0e4f67c86b0c6bb30520fc1e30b45
Author: Elric Milon <whirm@users.noreply.github.com>
Date:   Tue Jun 21 14:34:25 2016 +0200
    Merge pull request #2306 from lfdversluis/fix-general-excepts-channel-community    
    Refactored general except in channel community

```
INFO    1466664603.65       community:287   Crawler: Received crawl request from node WJQVGnlIqLfsb5WJWyvmFopx4GM=, from sequence number 3474
INFO    1466664604.41       community:287   Crawler: Received crawl request from node mfrKpuaArsxg/1ix/RlGKKVdbfw=, from sequence number 3474
ERROR   1466664613.69 LibtorrentDownloadImpl:742   Resume data cancelled
ERROR   1466664613.71 LibtorrentDownloadImpl:742   Resume data cancelled
INFO    1466664614.25       community:130   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:47856} UP: 2460 DOWN: 4187825
ERROR   1466664614.26             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 378, in on_tunnel_remove
    self.schedule_block(candidate, tunnel.bytes_up, tunnel.bytes_down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 138, in schedule_block
    self.publish_signature_request_message(candidate, total_amount_sent_mb, total_amount_received_mb)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 152, in publish_signature_request_message
    message = self.create_signature_request_message(candidate, up, down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 166, in create_signature_request_message
    total_up_requester, total_down_requester = self._get_next_total(up, down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 344, in _get_next_total
    total_up, total_down = self.persistence.get_total(self._public_key)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/database.py", line 267, in get_total
    db_result = self.execute(db_query, (public_key, public_key)).fetchone()
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/database.py", line 293, in execute
    result = self._cursor.execute(statement, bindings)
exceptions.AttributeError: 'NoneType' object has no attribute 'execute'

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 378, in on_tunnel_remove
    self.schedule_block(candidate, tunnel.bytes_up, tunnel.bytes_down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 138, in schedule_block
    self.publish_signature_request_message(candidate, total_amount_sent_mb, total_amount_received_mb)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 152, in publish_signature_request_message
    message = self.create_signature_request_message(candidate, up, down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 166, in create_signature_request_message
    total_up_requester, total_down_requester = self._get_next_total(up, down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 344, in _get_next_total
    total_up, total_down = self.persistence.get_total(self._public_key)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/database.py", line 267, in get_total
    db_result = self.execute(db_query, (public_key, public_key)).fetchone()
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/database.py", line 293, in execute
    result = self._cursor.execute(statement, bindings)
exceptions.AttributeError: 'NoneType' object has no attribute 'execute'
```

**Comment by Captain-Coder** [comment]
This should be fixed by [2380](https://github.com/Tribler/tribler/pull/2380)

**Comment by synctext** [comment]
Thnx for that.. Closing...
