### ISSUE TITLE
Pydeadobjerror in tests

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2329]
```
======================================================================
ERROR: Test whether adding a torrent def to a channel works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/test_as_server.py", line 281, in tearDown
    super(TestAsServer, self).tearDown(annotate=False)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/twisted_thread.py", line 157, in g
    d = func(*args, **kargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/test_as_server.py", line 166, in tearDown
    process_unhandled_exceptions()
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/util.py", line 112, in check_exceptions
    raise Exception("Test raised %d unhandled exceptions, last one was: %s" % (exc_counter, last_exc))
Exception: Test raised 2 unhandled exceptions, last one was: PyDeadObjectError('The C++ part of the ActivityPanel object has been deleted, attribute access no longer allowed.',)
-------------------- >> begin captured logging << --------------------
```

Reference: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2141/artifact/output/test_runners_output/00010.err/*view*/

**Comment by whirm** [comment]
Please paste both exceptions if they are not the same

**Comment by lfdversluis** [comment]
Sure. But the other is only printed half.

```
Exception in thread WatchDog (most likely raised during interpreter shutdown):Exception in thread WatchDog (most likely raised during interpreter shutdown):Exception in thread WatchDog (most likely raised during interpreter shutdown):Exception in thread WatchDog (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
 
Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/instrumentation.py", line 139, in run
 Exception in thread WatchDog (most likely raised during interpreter shutdown):Exception in thread WatchDog (most likely raised during interpreter shutdown):Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/instrumentation.py", line 139, in runException in thread WatchDog (most likely raised during interpreter shutdown):Exception in thread WatchDog (most likely raised during interpreter shutdown):
Exception in thread WatchDog (most likely raised during interpreter shutdown):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 168, in acquire

Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/instrumentation.py", line 139, in run

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
 
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
+ FAILURE=1
+ rm -fR /home/jenkins/workspace/GH_Tribler_PR_tests_linux/tmp/tmp.nuTSlM1KW6
+ exit 1
+ FAILURE=1
+ kill %Xvnc
+ exit 1
```

**Comment by devos50** [comment]
`Test whether adding a torrent def to a channel works` is not a GUI tests so I guess that tests that are running before these tests, are leaving observers behind (probably `Tribler.Test.test_gui_general.TestGuiGeneral`). See https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2394/artifact/output/test_runners_output/00009.err/*view*/.

Also, the linked error is caused by this line: https://github.com/Tribler/tribler/blob/devel/Tribler/Main/vwxGUI/home.py#L889, which was added by @pimveldhuisen recently.

**Comment by whirm** [comment]
@pimveldhuisen Could you have a look and check if this is a regression introduced by your commits?

**Comment by devos50** [comment]
This one cannot happen anymore since wx is removed from the tests.
