### ISSUE TITLE
Error in REST API when fetching all discovered channels on win32 tester

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2333]
I got the following error on the Windows 32-bit tester:

```
======================================================================
FAIL: Testing whether the API returns inserted channels when fetching discovered channels
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Test\test_as_server.py", line 81, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Utilities\twisted_thread.py", line 151, in errback
    failure.raiseException()
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Test\Core\Modules\RestApi\test_channels_endpoints.py", line 79, in verify_channels
    self.assertEqual(channels_json['channels'][i]['name'], 'Test channel %d' % i)
AssertionError: u'Test channel 2' != 'Test channel 0'
-------------------- >> begin captured logging << --------------------
```

Apparently, we cannot make any assumptions on the order of incoming data. We should remove this check.

**Comment by whirm** [comment]
You can still check that you receive all the channels you are waiting for

**Comment by devos50** [comment]
@whirm yeah I'm doing that in #2334, I'm still checking whether I have received the right amount of channels.

**Comment by whirm** [comment]
But you are not checking for the right message format then
