### ISSUE TITLE
twisted_utils.py: reactor.threadpool is NoneType

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2340]
Since #2323 on startup of twisted plugin on Android:

```
 Unhandled Error
 Traceback (most recent call last):
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 417, in fireEvent
     DeferredList(beforeResults).addCallback(self._continueFiring)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
     callbackKeywords=kw)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
     self._runCallbacks()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
     current.result = callback(current.result, *args, **kw)
 --- <exception caught here> ---
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 430, in _continueFiring
     callable(*args, **kwargs)
   File "/data/user/0/org.tribler.android/files/tribler_plugin.py", line 93, in start_tribler
     upgrader = self.session.prestart()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Session.py", line 192, in prestart
     self.upgrader.run()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Upgrade/upgrade.py", line 39, in run
     failed, has_to_upgrade = self.check_should_upgrade()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 46, in helper
     return blockingCallFromThread(reactor, func, *args, **kargs)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
     return f(*args, **kwargs)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Upgrade/upgrade.py", line 97, in check_should_upgrade
     self.notify_done()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Upgrade/upgrade.py", line 79, in notify_done
     self.session.notifier.notify(NTFY_UPGRADER, NTFY_FINISHED, None)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/CacheDB/Notifier.py", line 126, in notify
     callInThreadPool(task, *args)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Utilities/twisted_utils.py", line 46, in callInThreadPool
     if isInThreadPool():
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Utilities/twisted_utils.py", line 56, in isInThreadPool
     return current_thread() in reactor.threadpool.threads
 exceptions.AttributeError: 'NoneType' object has no attribute 'threads'
```

**Comment by brussee** [comment]
Same interface: #2325
https://github.com/twisted/twisted/blob/twisted-15.5.0/twisted/internet/interfaces.py#L1268

**Comment by devos50** [comment]
@brussee interesting, can you try this "fix"? https://github.com/Tribler/tribler/pull/2325. Note that this is probably **not** the solution but I'm suspecting that it is caused by something else.

**Comment by whirm** [comment]
That probably means the reactor hasn't been started before the blocking call on thread tries to schedule something on the threadpool

**Comment by brussee** [comment]
@whirm This is a major bug, since it is in the twisted plugin and not specific to Android at all.

**Comment by whirm** [comment]
@brussee I'll have a look

**Comment by brussee** [comment]
Fixed on next
