### ISSUE TITLE
Error in credit mining tests on Mac (causing the tests to hang)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2348]
```
test archive mode. Use diretory because easier to fetch torrent ... Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 168, in start
    self()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 213, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Policies/BoostingManager.py", line 336, in _select_torrent
    for infohash, torrent in self.torrents.iteritems():
exceptions.RuntimeError: dictionary changed size during iteration
```

See https://jenkins.tribler.org/job/GH_Tribler_PR_tests_mac/1953/

**Comment by lfdversluis** [comment]
Should this be closed now? With #2350
