### ISSUE TITLE
Tunnel community failing due to increase_bytes_sent

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2352]
This is on current `devel`/`next`

```
2016-06-29T11:29:30+0200 [-] Factory starting on 42287
2016-06-29T11:29:30+0200 [twisted.internet.protocol.Factory#info] Starting factory <twisted.internet.protocol.Factory instance at 0x7fb3ccd385f0>
2016-06-29T11:29:30+0200 [-] Factory starting on 43427
2016-06-29T11:29:30+0200 [twisted.internet.protocol.Factory#info] Starting factory <twisted.internet.protocol.Factory instance at 0x7fb3ccd387e8>
2016-06-29T11:29:30+0200 [-] Factory starting on 26048
2016-06-29T11:29:30+0200 [twisted.internet.protocol.Factory#info] Starting factory <twisted.internet.protocol.Factory instance at 0x7fb3ccd38a28>
2016-06-29T11:29:30+0200 [-] Factory starting on 30735
2016-06-29T11:29:30+0200 [twisted.internet.protocol.Factory#info] Starting factory <twisted.internet.protocol.Factory instance at 0x7fb3ccd38c68>
2016-06-29T11:29:30+0200 [-] Factory starting on 39282
2016-06-29T11:29:30+0200 [twisted.internet.protocol.Factory#info] Starting factory <twisted.internet.protocol.Factory instance at 0x7fb3ccd38ea8>
2016-06-29T11:29:30+0200 [-] Tribler started
2016-06-29T11:29:45+0200 [Socks5Connection,1,127.0.0.1] SocksUDPConnection starting on 57883
2016-06-29T11:29:45+0200 [Socks5Connection,1,127.0.0.1] Starting protocol <Tribler.community.tunnel.Socks5.server.SocksUDPConnection instance at 0x7fb3ccc482d8>
ERROR   1467192590.34        dispersy:1747  exception during handle_callback for extend
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1129, in on_extend
    message.payload.key)))
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1379, in increase_bytes_sent
    "RelayRoute or TunnelExitSocket")
TypeError: Increase_bytes_sent() was called with an object that is not a Circuit, RelayRoute or TunnelExitSocket
ERROR   1467192596.59        dispersy:1747  exception during handle_callback for extend
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1129, in on_extend
    message.payload.key)))
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1379, in increase_bytes_sent
    "RelayRoute or TunnelExitSocket")
TypeError: Increase_bytes_sent() was called with an object that is not a Circuit, RelayRoute or TunnelExitSocket
ERROR   1467192605.23        dispersy:1747  exception during handle_callback for extend
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1129, in on_extend
    message.payload.key)))
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1379, in increase_bytes_sent
    "RelayRoute or TunnelExitSocket")
TypeError: Increase_bytes_sent() was called with an object that is not a Circuit, RelayRoute or TunnelExitSocket
ERROR   1467192625.23        dispersy:1747  exception during handle_callback for extend
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1129, in on_extend
    message.payload.key)))
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1379, in increase_bytes_sent
    "RelayRoute or TunnelExitSocket")
TypeError: Increase_bytes_sent() was called with an object that is not a Circuit, RelayRoute or TunnelExitSocket
ERROR   1467192627.73        dispersy:1747  exception during handle_callback for extend
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1129, in on_extend
    message.payload.key)))
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1379, in increase_bytes_sent
    "RelayRoute or TunnelExitSocket")
TypeError: Increase_bytes_sent() was called with an object that is not a Circuit, RelayRoute or TunnelExitSocket
ERROR   1467192642.74        dispersy:1747  exception during handle_callback for extend
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1129, in on_extend
    message.payload.key)))
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1379, in increase_bytes_sent
    "RelayRoute or TunnelExitSocket")
TypeError: Increase_bytes_sent() was called with an object that is not a Circuit, RelayRoute or TunnelExitSocket
2016-06-29T11:31:10+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7fb3cccd05f0>
ERROR   1467192674.91        dispersy:1747  exception during handle_callback for extend
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1129, in on_extend
    message.payload.key)))
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/tunnel_community.py", line 1379, in increase_bytes_sent
    "RelayRoute or TunnelExitSocket")
TypeError: Increase_bytes_sent() was called with an object that is not a Circuit, RelayRoute or TunnelExitSocket
```

**Comment by synctext** [comment]
@pimveldhuisen  can this be fixed before pending summer break? Put this on multichain wiki.

**Comment by synctext** [comment]
@Captain-Coder All yours for 2 weeks...:-)
