### ISSUE TITLE
Credit mining tests are highly unstable

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2378]
This is from @brussee 's PR:

https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win32/1855/

Tribler.Test.Core.CreditMining.test_creditmining_sys.TestBoostingManagerSysChannel.test_chn_max_torrents

```
DEBUG   1467220105 torrent_checker:TorrentChecker:203  Tracker[DHT, DHT], finished: 0, failed: 0
DEBUG   1467220106 torrent_checker:TorrentChecker:201  total sessions: 1
DEBUG   1467220106 torrent_checker:TorrentChecker:203  Tracker[DHT, DHT], finished: 0, failed: 0
CRITICAL 1467220106         _legacy:twisted:154  Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Utilities\twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Libtorrent\__init__.py", line 27, in <lambda>
    lambda_f = lambda a = args, kwa = kwargs: invoke_func(*a, **kwa)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Libtorrent\__init__.py", line 28, in invoke_func
    download.session.lm.threadpool.add_task(lambda_f, 1)
exceptions.AttributeError: 'NoneType' object has no attribute 'add_task'

CRITICAL 1467220106         _legacy:twisted:154  Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Utilities\twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Libtorrent\__init__.py", line 27, in <lambda>
    lambda_f = lambda a = args, kwa = kwargs: invoke_func(*a, **kwa)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Libtorrent\__init__.py", line 28, in invoke_func
    download.session.lm.threadpool.add_task(lambda_f, 1)
exceptions.AttributeError: 'NoneType' object has no attribute 'add_task'
```

**Comment by ardhipoetra** [comment]
This is weird, I make sure I cleaned up properly and previously all the tests was okay. Do you have any clue why this happen, @whirm?

**Comment by whirm** [comment]
It's trying to schedule stuff after or before the launchmanycore threadpool exists.

**Comment by devos50** [comment]
I disabled these tests in #2382 until they are stable again.

**Comment by brussee** [comment]
```
Regression

Tribler.Test.Core.CreditMining.test_creditmining_sys.TestBoostingManagerSysRSS.test_rss (from nosetests)
Failing for the past 1 build (Since Failed#2324 )
Took 13 sec.
Error Message

The reactor had readers/writers left
```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2324/testReport/junit/Tribler.Test.Core.CreditMining.test_creditmining_sys/TestBoostingManagerSysRSS/test_rss/

**Comment by ardhipoetra** [comment]
Might be related to #2303

**Comment by brussee** [comment]
Tribler.Test.Core.CreditMining.test_creditmining_sys.TestBoostingManagerSysChannel.test_chn_lookup (from nosetests)
Test raised 1 unhandled Twisted exceptions
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win64/2080/testReport/junit/Tribler.Test.Core.CreditMining.test_creditmining_sys/TestBoostingManagerSysChannel/test_chn_lookup/

**Comment by brussee** [comment]
Tribler.Test.Core.CreditMining.test_creditmining_sys.TestBoostingManagerSysChannel.test_chn_lookup (from nosetests)
Test raised 1 unhandled Twisted exceptions
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win64/2080/testReport/junit/Tribler.Test.Core.CreditMining.test_creditmining_sys/TestBoostingManagerSysChannel/test_chn_lookup/

**Comment by brussee** [comment]
Tribler.Test.Core.CreditMining.test_creditmining.TestBoostingManagerPolicies.test_fallback_policy (from nosetests)

Start failed [4, 2] vs [{'num_seeders': -4, 'creation_date': 4, 'num_leechers': -4, 'metainfo': <Tribler.Test.Core.CreditMining.mock_creditmining.MockMeta object at 0x7f4e62906910>}, {'num_seeders': -2, 'creation_date': 2, 'num_leechers': -2, 'metainfo': <Tribler.Test.Core.CreditMining.mock_creditmining.MockMeta object at 0x7f4e62906990>}]

https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2517/testReport/junit/Tribler.Test.Core.CreditMining.test_creditmining/TestBoostingManagerPolicies/test_fallback_policy/

**Comment by brussee** [comment]
```
Tribler.Test.Core.CreditMining.test_creditmining_sys.TestBoostingManagerSysChannel.test_chn_max_torrents (from nosetests)
Failing for the past 1 build (Since Failed#2108 )
Took 15 sec.
Error Message

Test raised 1 unhandled Twisted exceptions:
[{'log_namespace': u'log_legacy', 'log_time': 1467905237.96, 'format': '%(log_legacy)s', 'log_system': '-', 'log_legacy': <twisted.logger._stdlib.StringifiableFromEvent object at 0x00000000080B1400>, 'log_level': <LogLevel=critical>, 'system': '-', 'isError': 1, 'failure': <twisted.python.failure.Failure exceptions.TypeError: argument of type 'NoneType' is not iterable>, 'time': 1467905237.96, 'log_text': 'Unhandled Error\nTraceback (most recent call last):\n  File "C:\\Python27\\lib\\threading.py", line 763, in run\n    self.__target(*self.__args, **self.__kwargs)\n  File "C:\\workspace\\jenkins\\workspace\\GH_Tribler_PR_tests_win64\\tribler\\Tribler\\Core\\Utilities\\twisted_thread.py", line 55, in _reactor_runner\n    reactor.run(installSignalHandlers=False)\n  File "C:\\Python27\\lib\\site-packages\\twisted\\internet\\base.py", line 1194, in run\n    self.mainLoop()\n  File "C:\\Python27\\lib\\site-packages\\twisted\\internet\\base.py", line 1203, in mainLoop\n    self.runUntilCurrent()\n--- <exception caught here> ---\n  File "C:\\Python27\\lib\\site-packages\\twisted\\internet\\base.py", line 825, in runUntilCurrent\n    call.func(*call.args, **call.kw)\n  File "C:\\workspace\\jenkins\\workspace\\GH_Tribler_PR_tests_win64\\tribler\\Tribler\\Core\\APIImplementation\\threadpoolmanager.py", line 50, in caller\n    fun(*args, **kwargs)\n  File "C:\\workspace\\jenkins\\workspace\\GH_Tribler_PR_tests_win64\\tribler\\Tribler\\Core\\Libtorrent\\LibtorrentMgr.py", line 482, in do_dht_check\n    lt_session = self.get_session()\n  File "C:\\workspace\\jenkins\\workspace\\GH_Tribler_PR_tests_win64\\tribler\\Tribler\\Core\\Libtorrent\\LibtorrentMgr.py", line 186, in get_session\n    if hops not in self.ltsessions:\nexceptions.TypeError: argument of type \'NoneType\' is not iterable\n', 'log_format': u'{log_text}', 'message': (), 'why': None}]
```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win64/2108/testReport/junit/Tribler.Test.Core.CreditMining.test_creditmining_sys/TestBoostingManagerSysChannel/test_chn_max_torrents/

**Comment by ardhipoetra** [comment]
Thanks for the report, @brussee

**Comment by ardhipoetra** [comment]
I think this should be closed because all the PR fixing it are merged already.
