### ISSUE TITLE
No module named Policies.BoostingPolicy on latest build from devel branch.

### ISSUE THREAD

**Issue by NoNameForMee** [Tribler/tribler#2383]
I have just tried the latest build, https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/620/ on my Ubuntu 16.04 64b machine however it fails to start.
I suspect this issue can be traced to https://github.com/Tribler/tribler/pull/2361 (with commit cebd228ec71f2b25ace31a1b428c73dee16f4656) which was not merged to the [devel](/Tribler/tribler/tree/devel) branch but only to the [next](/Tribler/tribler/tree/next) branch, while the "Policies" are used in the latest commits on devel.

Log message contains the following:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/tribler.py", line 95, in <module>
    __main__()
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/tribler.py", line 85, in __main__
    run()
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/tribler.py", line 67, in run
    from Tribler.Main.tribler_main import run as run_main
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/tribler_main.py", line 11, in <module>
    from Tribler.Core.Modules.process_checker import ProcessChecker
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Modules/process_checker.py", line 3, in <module>
    from Tribler.Core.SessionConfig import SessionStartupConfig
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/SessionConfig.py", line 26, in <module>
    from Tribler.Policies.BoostingPolicy import CreationDatePolicy, BoostingPolicy
ImportError: No module named Policies.BoostingPolicy

**Comment by ardhipoetra** [comment]
I think it should wait until commit https://github.com/Tribler/tribler/commit/cebd228ec71f2b25ace31a1b428c73dee16f4656 to be merged into `devel`.

**Comment by synctext** [comment]
@NoNameForMee our key priority now is a stable Next branch. We need a release in 10 days for PR purposes. At some point all bugfix changes within Next will be copied into Devel.

Thnx for looking at Tribler so closely! we can certainly use more critical eyes of software developers.

**Comment by devos50** [comment]
We made some changes to the way the `setup.py` file is structured, see https://github.com/Tribler/tribler/commit/83b47823a23ea12c351fddd11083a42ef33ab492. This issue should be fixed by now. Please reopen this issue if you experience problems related to this.
