### ISSUE TITLE
Nose ReactorAlreadyRunning

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2386]
Upon starting the nosetests on Android:
```
Exception in thread Twisted:
Traceback (most recent call last):
  File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl-sqlite3/armeabi-v7a/python2/python-install/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl-sqlite3/armeabi-v7a/python2/python-install/lib/python2.7/threading.py", line 505, in run
  File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 1193, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 1173, in startRunning
    ReactorBase.startRunning(self)
  File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 682, in startRunning
    raise error.ReactorAlreadyRunning()
ReactorAlreadyRunning
```

**Comment by brussee** [comment]
from Tribler.Core.Utilities.twisted_thread import threaded_reactor

# Export global reactor variable, as Twisted does
reactor, reactor_thread = threaded_reactor()
reactor.run()
```
 Traceback (most recent call last):
   File "Triblerd.py", line 36, in <module>
     Triblerd().test()
   File "Triblerd.py", line 29, in test
     reactor.run()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 1193, in run
     self.startRunning(installSignalHandlers=installSignalHandlers)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 1173, in startRunning
     ReactorBase.startRunning(self)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 682, in startRunning
     raise error.ReactorAlreadyRunning()
 twisted.internet.error.ReactorAlreadyRunning
```

**Comment by brussee** [comment]
Nose needs no reactor to be installed and the dispersy tests are not compatible with running the tribler tests.
