### ISSUE TITLE
register_task should always be called from the reactor thread

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2403]
On current devel: 

```
commit 63f49df0c2ffca5da9bc8e80abee1aad1aa0645f
Merge: 3ee8432 f067eb2
Author: Elric Milon <whirm@users.noreply.github.com>
Date:   Fri Jul 1 13:15:04 2016 +0200

    Merge pull request #2393 from whirm/next_to_devel

    Next to devel
```

```
Traceback (most recent call last):
  File "/Users/system/Documents/thesis/tribler/Tribler/Main/tribler_main.py", line 151, in __init__
    session.start()
  File "/Users/system/Documents/thesis/tribler/Tribler/Core/Session.py", line 466, in start
    startup_deferred = self.lm.register(self, self.sesslock)
  File "/Users/system/Documents/thesis/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 110, in register
    self.torrent_store = LevelDbStore(self.session.get_torrent_store_dir())
  File "/Users/system/Documents/thesis/tribler/Tribler/Core/leveldbstore.py", line 86, in __init__
    self._writeback_lc = self.register_task("flush cache ", LoopingCall(self.flush))
  File "/Users/system/Documents/thesis/tribler/Tribler/dispersy/taskmanager.py", line 38, in register_task
    assert isInIOThread()
```

**Comment by whirm** [comment]
Have you tried `next` ?

**Comment by lfdversluis** [comment]
Too.

```
Traceback (most recent call last):
  File "/Users/system/Documents/thesis/tribler/Tribler/Main/tribler_main.py", line 151, in __init__
    session.start()
  File "/Users/system/Documents/thesis/tribler/Tribler/Core/Session.py", line 463, in start
    startup_deferred = self.lm.register(self, self.sesslock)
  File "/Users/system/Documents/thesis/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 110, in register
    self.torrent_store = LevelDbStore(self.session.get_torrent_store_dir())
  File "/Users/system/Documents/thesis/tribler/Tribler/Core/leveldbstore.py", line 86, in __init__
    self._writeback_lc = self.register_task("flush cache ", LoopingCall(self.flush))
  File "/Users/system/Documents/thesis/tribler/Tribler/dispersy/taskmanager.py", line 38, in register_task
    assert isInIOThread()
```

**Comment by devos50** [comment]
This is due to the fact that we are calling `register_task` many times from a non-reactor thread. The `isInIOThread` check is introduced in https://github.com/Tribler/dispersy/commit/539e82243b64f0482d3fbc79164510a31864e27c.

**Comment by devos50** [comment]
This should be ok now.
