### ISSUE TITLE
Unstable test_normal_torrent in Tribler.Test.API.test_seeding.TestSeeding

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2411]
```
I: ======================================================================
I: ERROR: test_normal_torrent (Tribler.Test.API.test_seeding.TestSeeding)
I: ----------------------------------------------------------------------
I: Traceback (most recent call last):
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/test_as_server.py", line 73, in check
I:     result = fun(*argv, **kwargs)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 96, in test_normal_torrent
I:     self.subtest_is_seeding()
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 104, in subtest_is_seeding
I:     s.send(CHOKE)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/btconn.py", line 117, in send
I:     self.s.send(tobinary(len(data)))
I: error: [Errno 32] Broken pipe
I: ----------------------------------------------------------------------
```

```
I: ======================================================================
I: ERROR: test_normal_torrent (Tribler.Test.API.test_seeding.TestSeeding)
I: ----------------------------------------------------------------------
I: Traceback (most recent call last):
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/test_as_server.py", line 73, in check
I:     result = fun(*argv, **kwargs)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 96, in test_normal_torrent
I:     self.subtest_is_seeding()
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 102, in subtest_is_seeding
I:     s.read_handshake_medium_rare()
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/btconn.py", line 100, in read_handshake_medium_rare
I:     data = self._readn(68)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/btconn.py", line 149, in _readn
I:     raise ex
I: error: [Errno 104] Connection reset by peer
I: ----------------------------------------------------------------------
```

**Comment by brussee** [comment]
Note that these 3 tests have recently worked once on some point on Android.

**Comment by whirm** [comment]
I don't think I've ever seen this failure on windows/linux/osx.

@brussee do they fail 100% of the time?

If so, could you please do a bisect run to see when it started failing?

**Comment by brussee** [comment]
99.9% of the time: I have seen them work once on Android.

No not easily, because python runs inside a service process on Android that does not have granular control from the outside.

**Comment by devos50** [comment]
@brussee is this issue only on Android?

**Comment by brussee** [comment]
Take a look at the most recent nosetests on Android:
[nosetests-2.xml.zip](https://github.com/Tribler/tribler/files/613323/nosetests-2.xml.zip)

You can run all tests at any time on one of the dev phones.
