### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'formatters' in tunnel_helper_plugin.py

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2467]
```
07-14 13:50:25.340 8355-8374/? I/Triblerd: Unhandled Error
07-14 13:50:25.340 8355-8374/? I/Triblerd: Traceback (most recent call last):
07-14 13:50:25.340 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/python/usage.py", line 447, in __str__
07-14 13:50:25.340 8355-8374/? I/Triblerd:     return self.getSynopsis() + '\n' + self.getUsage(width=None)
07-14 13:50:25.341 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/python/usage.py", line 483, in getUsage
07-14 13:50:25.341 8355-8374/? I/Triblerd:     for (cmd, short, parser, desc) in self.subCommands:
07-14 13:50:25.341 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/application/app.py", line 596, in subCommands
07-14 13:50:25.341 8355-8374/? I/Triblerd:     for plug in sorted(plugins, key=attrgetter('tapname')):
07-14 13:50:25.341 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/plugin.py", line 213, in getPlugins
07-14 13:50:25.341 8355-8374/? I/Triblerd:     allDropins = getCache(package)
07-14 13:50:25.341 8355-8374/? I/Triblerd: --- <exception caught here> ---
07-14 13:50:25.341 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/plugin.py", line 171, in getCache
07-14 13:50:25.341 8355-8374/? I/Triblerd:     provider = pluginModule.load()
07-14 13:50:25.341 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/python/modules.py", line 389, in load
07-14 13:50:25.341 8355-8374/? I/Triblerd:     return self.pathEntry.pythonPath.moduleLoader(self.name)
07-14 13:50:25.341 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
07-14 13:50:25.341 8355-8374/? I/Triblerd:     topLevelPackage = _importAndCheckStack(trialname)
07-14 13:50:25.341 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/python/reflect.py", line 242, in _importAndCheckStack
07-14 13:50:25.341 8355-8374/? I/Triblerd:     return __import__(importName)
07-14 13:50:25.341 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/plugins/tunnel_helper_plugin.py", line 106, in <module>
07-14 13:50:25.342 8355-8374/? I/Triblerd:     logging.config.fileConfig("logger.conf")
07-14 13:50:25.342 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python27.zip/logging/config.py", line 70, in fileConfig
07-14 13:50:25.342 8355-8374/? I/Triblerd:     
07-14 13:50:25.342 8355-8374/? I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python27.zip/logging/config.py", line 106, in _create_formatters
07-14 13:50:25.342 8355-8374/? I/Triblerd:     
07-14 13:50:25.342 8355-8374/? I/Triblerd:   File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl-sqlite3/armeabi-v7a/python2/python-install/lib/python2.7/ConfigParser.py", line 599, in get
07-14 13:50:25.342 8355-8374/? I/Triblerd:     
07-14 13:50:25.342 8355-8374/? I/Triblerd: ConfigParser.NoSectionError: No section: 'formatters'
```

**Comment by devos50** [comment]
@brussee do you still experience this?

**Comment by brussee** [comment]
Not recently.
