### ISSUE TITLE
False negative: "Network is unreachable"

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2472]
The network should have been reachable (nothing changed at that time) and Tribler should have retried at some point...

```
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd: Unhandled Error
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd: Traceback (most recent call last):
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 417, in fireEvent
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     DeferredList(beforeResults).addCallback(self._continueFiring)
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     callbackKeywords=kw)
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     self._runCallbacks()
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     current.result = callback(current.result, *args, **kw)
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd: --- <exception caught here> ---
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 430, in _continueFiring
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     callable(*args, **kwargs)
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/tribler_plugin.py", line 97, in start_tribler
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     self.session.start()
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Session.py", line 466, in start
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     startup_deferred = self.lm.register(self, self.sesslock)
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/APIImplementation/LaunchManyCore.py", line 163, in register
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     self.dispersy = Dispersy(endpoint, working_directory)
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/dispersy/dispersy.py", line 138, in __init__
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     self._lan_address = self._get_lan_address(True)
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/dispersy/dispersy.py", line 231, in _get_lan_address
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     return (interface.address if interface else get_lan_address_without_netifaces()), \
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 298, in get_lan_address_without_netifaces
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     s.connect(("192.0.2.0", 80)) # TEST-NET-1, guaranteed to not be connected => no callbacks
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:   File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl-sqlite3/armeabi-v7a/python2/python-install/lib/python2.7/socket.py", line 224, in meth
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd:     
07-14 21:30:47.532 3107-3121/org.tribler.android:service_Triblerd I/Triblerd: socket.error: [Errno 101] Network is unreachable
```

**Comment by devos50** [comment]
I'm pretty sure that this one has been fixed in https://github.com/tribler/dispersy/commit/de64731adfe78047968d62022c7b4e93c3e7615c
