### ISSUE TITLE
Zope.interface is not bundled in the experimental release .dmg file

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2502]
I'm getting the following error in my log when trying to start Tribler:

```
27-07-16 17:23:29,912 Tribler[39610]: Traceback (most recent call last):
27-07-16 17:23:29,912 Tribler[39610]:   File "/Applications/Tribler.app/Contents/Resources/__boot__.py", line 421, in <module>
27-07-16 17:23:29,912 Tribler[39610]:     _run()
27-07-16 17:23:29,912 Tribler[39610]:   File "/Applications/Tribler.app/Contents/Resources/__boot__.py", line 358, in _run
27-07-16 17:23:29,912 Tribler[39610]:     exec(compile(source, path, 'exec'), globals(), globals())
27-07-16 17:23:29,912 Tribler[39610]:   File "/Applications/Tribler.app/Contents/Resources/tribler.py", line 47, in <module>
27-07-16 17:23:29,913 Tribler[39610]:     from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
27-07-16 17:23:29,913 Tribler[39610]:   File "Tribler/Core/Utilities/twisted_thread.pyo", line 8, in <module>
27-07-16 17:23:29,913 Tribler[39610]:   File "twisted/__init__.pyo", line 55, in <module>
27-07-16 17:23:29,913 Tribler[39610]:   File "twisted/__init__.pyo", line 39, in _checkRequirements
27-07-16 17:23:29,913 Tribler[39610]: ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.
```

It works on another OS X laptop, why remains a miracle for me. I noticed that the `zope.interface` package is not copied to the `site-packages` in the final .app.

**Comment by whirm** [comment]
Who tested the DMG?

**Comment by devos50** [comment]
I did, on my laptop it worked but on my iMac I got this error.

**Comment by whirm** [comment]
hm, different osx versions?

**Comment by whirm** [comment]
AFAIK OSX comes with twisted bundled so it should ship its dependencies?

**Comment by devos50** [comment]
@whirm apparently, the `zope` directory, was in a location that could not be found in Tribler. I've fixed it and it is now bundled correctly. I will test the build on another iMac tonight.

**Comment by devos50** [comment]
Works fine now!
