### ISSUE TITLE
Get MyChannel overview TypeError

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2517]
Should check if my_channel is not None before accessing my_channel[1] and my_channel[2]:

```
8-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: ERROR:[Failure instance: Traceback: <type 'exceptions.TypeError'>: 'NoneType' object is not subscriptable
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/protocols/basic.py:571:dataReceived
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/http.py:1720:lineReceived
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/http.py:1799:allContentReceived
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/http.py:832:requestReceived
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: --- <exception caught here> ---
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/server.py:183:process
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/server.py:234:render
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/resource.py:250:render
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Modules/restapi/channels/my_channel_endpoint.py:49:render_GET
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: ]
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: Traceback (most recent call last):
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/server.py", line 183, in process
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:     self.render(resrc)
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:     body = resrc.render(self)
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:     return m(request)
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Modules/restapi/channels/my_channel_endpoint.py", line 49, in render_GET
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:     return json.dumps({'mychannel': {'identifier': my_channel[1].encode('hex'), 'name': my_channel[2],
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: TypeError: 'NoneType' object is not subscriptable
```

**Comment by brussee** [comment]
Somehow my_channel is None, according to the stack trace below, after checking my_channel_id is None.
```
        my_channel_id = self.channel_db_handler.getMyChannelId()
        if my_channel_id is None:
            request.setResponseCode(http.NOT_FOUND)
            return json.dumps({"error": NO_CHANNEL_CREATED_RESPONSE_MSG})

        my_channel = self.channel_db_handler.getChannel(my_channel_id)

        return json.dumps({'mychannel': {'identifier': my_channel[1].encode('hex'), 'name': my_channel[2],
                                         'description': my_channel[3]}})
```

**Comment by brussee** [comment]
**Cause:** channel_db_handler.getChannel calls _getChannels() which does not return channels with empty names.
```
            if name.strip() == '':
                continue
```

**Comment by brussee** [comment]
Effectively this creates an unrecoverable state when the user creates MyChannel with an empty name, because you can never edit it after creating due to the mentioned filter.

**Comment by lfdversluis** [comment]
Good find.

**Comment by devos50** [comment]
I would propose the same solution here as we did for the torrents: when there is an empty channel name in the database, rename it to 'unnamed channel'. In addition, don't allow these empty channel names in the database.
