### ISSUE TITLE
[devel] Errors logged to console

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2531]
##### Tribler version/branch+revision:

9f1d4d94d1a2df32b42a57017d1246d568821876 devel
##### Relevant log file output:

For all/most of downloads:

```
ERROR   1472497939.37  LaunchManyCore:637   Exception while checkpointing: tails-i386-2.3
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 634, in network_checkpoint_callback
    self.save_download_pstate(infohash, pstate)
  File "/home/vi/home/tribler/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 808, in save_download_pstate
    self.downloads[infohash].save_resume_data())
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/taskmanager.py", line 41, in register_task
    assert not self.is_pending_task_active(name), name
AssertionError: save_pstate 1862.259269
```

**Comment by devos50** [comment]
@vi thank you for your bug report! We will investigate it.

@ardhipoetra it seems related to the saving process of resume data. Are you able to take a look at it?
