### ISSUE TITLE
Tribbler not starting: Missing File?

### ISSUE THREAD

**Issue by avemt1** [Tribler/tribler#2549]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.md

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
6.5.2
#### Operating system and version: #####
Windows 10 pro
##### Expected behavior: #####
Application GUI displaying
##### Actual behavior: #####
Log file notification
##### Steps to reproduce the behavior: #####
Install, ununstall, clear app data, Manually clear registry by 'Find' function, Reinstall
##### Relevant log file output: #####
Log: Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 105, in register
  File "Tribler\Core\leveldbstore.pyo", line 76, in __init__
LevelDBError: Corruption: 1 missing files; e.g.: collected_torrents/000007.sst

Log.old: Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 105, in register
  File "Tribler\Core\leveldbstore.pyo", line 76, in __init__
LevelDBError: Corruption: 1 missing files; e.g.: collected_torrents/000007.sst
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 1057, in run
  File "Tribler\Utilities\Instance2Instance.pyo", line 42, in __init__
  File "socket.pyo", line 228, in meth
error: [Errno 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 1057, in run
  File "Tribler\Utilities\Instance2Instance.pyo", line 42, in __init__
  File "socket.pyo", line 228, in meth
error: [Errno 10061] No connection could be made because the target machine actively refused it

**Comment by avemt1** [comment]
It was one of my Anti-virus. I use both Malwarebytes and Spybot Search and Destroy +AV. I will test and inform which is causing the issue, and a possible fix.

**Comment by avemt1** [comment]
The problem was Malwarebytes. It was reading the Log file in C:/Users/(User)/AppData/Roaming/.Tribler/collected_torrents/00000#.log as a malicious file. If anyone has this problem also, please go into your settings and add the .tribler folder listed above to the exclusion list.
