### ISSUE TITLE
Tribler from "next" fails to start when database is from "devel".

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2551]
##### Tribler version/branch+revision:

e79b6dd2247f53ca764559280cc0997299a1e673 next
##### Operating system and version:

Debian i686
##### Expected behavior:

Tribler can start even after experimenting with dev versions (while preserving download list if possible or clearing them with a confirmation window if not).

Tribler never fails to start up and show the most of UI if VLC can't be initialized. Absence of embedded video player doesn't affect non-video-related features of Tribler.
##### Actual behavior:

Tribler fails with internal error after showing message about database version incompatibility. Inability to find VLC-related object is reported as a cause.
##### Steps to reproduce the behavior:

Have multiple downloads added by multiple versions of Tribler, stable, next and devel. Then try switching from devel (or from the new_gui pull request branch) to next.
##### Relevant log file output:

```
INFO    1474657102.22       community:308   initializing:  MultiChainCommunity
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Main/tribler_main.py", line 211, in __init__
    wx.CallLater(3000, vlcwrap._init_vlc)
AttributeError: 'NoneType' object has no attribute '_init_vlc'
INFO    1474657156.08       community:288   Crawler: Received crawl request from node 12xKh+QUoQm3bbLt5Nd1vALVbQw=, from sequence number 1490
INFO    1474657156.09       community:315   Crawler: No blocks
ERROR   1474657165.20   sqlitecachedb:282   cachedb: ===Twisted===
SQL Type: <type 'unicode'>
-----
COMMIT;
-----
None
======
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 271, in execute
    return cur.execute(sql)
  File "src/cursor.c", line 231, in resetcursor
SQLError: SQLError: cannot commit - no transaction is active
ERROR   1474657165.22   sqlitecachedb:227   COMMIT FAILED
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 225, in commit_now
    self.execute(u"COMMIT;")
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 284, in execute
    raise msg
SQLError: SQLError: cannot commit - no transaction is active
ERROR   1474657165.22        database:388   SQLError: cannot commit - no transaction is active [/home/vi/home/tribler/.Tribler/sqlite/dispersy.db]
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/database.py", line 386, in commit
    callback(exiting=exiting)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 37, in helper
    return func(*args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 225, in commit_now
    self.execute(u"COMMIT;")
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 284, in execute
    raise msg
SQLError: SQLError: cannot commit - no transaction is active
INFO    1474657205.71       community:288   Crawler: Received crawl request from node 12xKh+QUoQm3bbLt5Nd1vALVbQw=, from sequence number 1490
INFO    1474657205.71       community:315   Crawler: No blocks
ERROR   1474657221.92   sqlitecachedb:282   cachedb: ===Twisted===
SQL Type: <type 'unicode'>
-----
COMMIT;
-----
None
======
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 271, in execute
    return cur.execute(sql)
  File "src/cursor.c", line 231, in resetcursor
SQLError: SQLError: cannot commit - no transaction is active
ERROR   1474657221.92   sqlitecachedb:227   COMMIT FAILED
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 225, in commit_now
    self.execute(u"COMMIT;")
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 284, in execute
    raise msg
SQLError: SQLError: cannot commit - no transaction is active
ERROR   1474657221.92        database:388   SQLError: cannot commit - no transaction is active [/home/vi/home/tribler/.Tribler/sqlite/dispersy.db]
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/database.py", line 386, in commit
    callback(exiting=exiting)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 37, in helper
    return func(*args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 225, in commit_now
    self.execute(u"COMMIT;")
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 284, in execute
    raise msg
SQLError: SQLError: cannot commit - no transaction is active

(tribler.py:17620): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(tribler.py:17620): GLib-GObject-CRITICAL **: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(tribler.py:17620): Gtk-CRITICAL **: IA__gtk_window_set_modal: assertion 'GTK_IS_WINDOW (window)' failed

INFO    1474657260.70       community:288   Crawler: Received crawl request from node 12xKh+QUoQm3bbLt5Nd1vALVbQw=, from sequence number 1490
INFO    1474657260.70       community:315   Crawler: No blocks

ERROR   1474657281.92   sqlitecachedb:282   cachedb: ===Twisted===
SQL Type: <type 'unicode'>
-----
COMMIT;
-----
None
======
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 271, in execute
    return cur.execute(sql)
  File "src/cursor.c", line 231, in resetcursor
SQLError: SQLError: cannot commit - no transaction is active
ERROR   1474657281.92   sqlitecachedb:227   COMMIT FAILED
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 225, in commit_now
    self.execute(u"COMMIT;")
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 284, in execute
    raise msg
SQLError: SQLError: cannot commit - no transaction is active
ERROR   1474657281.93        database:388   SQLError: cannot commit - no transaction is active [/home/vi/home/tribler/.Tribler/sqlite/dispersy.db]
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/database.py", line 386, in commit
    callback(exiting=exiting)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 37, in helper
    return func(*args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 225, in commit_now
    self.execute(u"COMMIT;")
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/vi/home/tribler/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/vi/home/tribler/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 284, in execute
    raise msg
SQLError: SQLError: cannot commit - no transaction is active

INFO    1474657315.70       community:288   Crawler: Received crawl request from node 12xKh+QUoQm3bbLt5Nd1vALVbQw=, from sequence number 1490
INFO    1474657315.70       community:315   Crawler: No blocks

^C
```

**Comment by vi** [comment]
Tribler from "next" does work with `~/.Tribler` moved away.

Fortunately, going back to "devel" restored the downloads list. While adding a bunch of dummy empty downloads and one random non-empty download along the way although...

**Comment by devos50** [comment]
Thanks for reporting!

**Comment by devos50** [comment]
@vi these kind of issues might be due to the fact that the `devel` branch contains some code that upgrades the database structure to make it compatible with Tribler 7. This causes the database to be incompatible with older versions.

However, your log suggests that our vlcwrapper is not correctly initialised. I'm not sure what's causing this exactly, but the vlcwrapper is removed in Tribler 7 (in fact, everything video-player related will be in the GUI). Also, the next branch will soon be removed and replaced with the code from devel.

So I won't give priority to this issue. Please reopen the issue if you have any more comments or another problem related to this issue.
