### ISSUE TITLE
ImportError: No module named twisted.internet

### ISSUE THREAD

**Issue by trask1** [Tribler/tribler#2560]
- [ x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Operating system and version: 4.7.5-1-ARCH#####

 $ ./tribler.sh 

Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 47, in <module>
    from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
  File "/home/usr/Desktop/tribler/Tribler/Core/Utilities/twisted_thread.py", line 8, in <module>
    from twisted.internet import reactor
ImportError: No module named twisted.internet

**Comment by devos50** [comment]
@trask1 Tribler requires Twisted to function (https://www.archlinux.org/packages/extra/x86_64/python2-twisted/). Can you make sure that this dependency is installed?

**Comment by devos50** [comment]
Closing this issue due to inactivity. Please reopen this issue if you experience the problem again 👍
