### ISSUE TITLE
Ubuntu installer error: Reading configspec failed: Config file not found

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2611]
The latest build from devel (https://jenkins.tribler.org/job/Build_Tribler_devel/153/) fails to install on Ubuntu 16.04

Install messages and log file error:
```
sudo dpkg -i Downloads/tribler_7.0.0-exp1-2-gdc80820_all.deb 
(Reading database ... 407455 files and directories currently installed.)
Preparing to unpack .../tribler_7.0.0-exp1-2-gdc80820_all.deb ...
Unpacking tribler (7.0.0-exp1-2-gdc80820) over (7.0.0-exp1-2-gdc80820) ...
Setting up tribler (7.0.0-exp1-2-gdc80820) ...
Processing triggers for gconf2 (3.2.6-3ubuntu6) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for menu (2.1.47ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
XPS13:~>tribler
Starting Tribler...


Traceback (most recent call last):
  File "Tribler/Main/tribler_main.py", line 930, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "Tribler/Main/tribler_main.py", line 111, in __init__
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "Tribler/Main/tribler_main.py", line 328, in InitStage1
    session = Session(self.sconfig, autoload_discovery=autoload_discovery)
  File "Tribler/Core/Session.py", line 183, in __init__
    self.tribler_config = TriblerConfig(self)
  File "Tribler/Core/Config/tribler_config.py", line 15, in __init__
    self.config = ConfigObj(config_path, configspec=CONFIGSPEC_PATH)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1325, in _load
    self._handle_configspec(configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1948, in _handle_configspec
    raise IOError('Reading configspec failed: %s' % e)
IOError: Reading configspec failed: Config file not found: "Tribler/../Tribler/Core/Config/config.spec".


XPS13:/usr/share/tribler>cat Tribler/../Tribler/Core/Config/config.spec
[general]
family_filter = boolean(default=True)
```

Trivial fix, just goto the /usr/share/tribler/Tribler dir:
```
XPS13:share/tribler/Tribler>/usr/bin/python2.7 -m Tribler.Main.tribler
INFO    1478529145.58       community:307   initializing:  MultiChainCommunity
```

python-libnacl seems an unlisted dependency..

Old 6,5 GUI starts as usual.

**Comment by devos50** [comment]
Apparently, my fixes to the Debian builder are not completely available on the repo somehow and it's running the wrong script. I will figure out what's causing this.

Also, we bundle `libnacl` with Dispersy so it's not a dependency that should be added to `debian/control`.

**Comment by devos50** [comment]
@synctext please try this build: https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/679/

**Comment by devos50** [comment]
Verified to be fixed
