### ISSUE TITLE
Seg Fault when posting log, triggered by seek: exceptions.RuntimeError: torrent already exists in session

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2613]
While testing [alpha build](https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/679/) on Ubuntu 16.04

To reproduce: 1) stream Pioneer One 2) wait till playing, 3) seek to middle 4) observe TraceBack 5) send report 6) Segmentation fault (core dumped)

```
WARNING:TunnelLogger:Got pong (4273931391) from ('95.211.155.142', 54025), I am <Member 6 165a79f84c4bfcc5df6d53fa6d46bd7b04d18159>
WARNING:TunnelLogger:Got pong (422936437) from ('95.211.155.142', 5273), I am <Member 6 165a79f84c4bfcc5df6d53fa6d46bd7b04d18159>
WARNING:TunnelLogger:Got pong (236260966) from ('95.211.155.142', 56297), I am <Member 6 165a79f84c4bfcc5df6d53fa6d46bd7b04d18159>
WARNING:TunnelLogger:Got pong (1767615903) from ('95.211.155.142', 5273), I am <Member 6 165a79f84c4bfcc5df6d53fa6d46bd7b04d18159>
WARNING:TunnelLogger:Got pong (1144275925) from ('77.162.19.178', 55554), I am <Member 6 165a79f84c4bfcc5df6d53fa6d46bd7b04d18159>
WARNING:TunnelLogger:Got pong (2073684807) from ('77.162.19.178', 55554), I am <Member 6 165a79f84c4bfcc5df6d53fa6d46bd7b04d18159>
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 67, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 208, in schedule_create_engine
    self.pstate_for_restart, initialdlstatus, share_mode=share_mode)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 308, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 272, in add_torrent
    torrent_handle = ltsession.add_torrent(encode_atp(atp))
exceptions.RuntimeError: torrent already exists in session

ERROR:VideoRequestHandler:sent wrong amount, wanted 366831226 got 10223616
WARNING:Timeline:FAIL time:6 user:2934 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:2935 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:1797 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:2936 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:2937 -> permit^channel (no authorization)
ERROR:LibtorrentDownloadImpl:Resume data cancelled
ERROR:LibtorrentDownloadImpl:Resume data cancelled
ERROR:LibtorrentDownloadImpl:Resume data cancelled
ERROR:root:Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 101, in check_queue
    raise RuntimeError(data)
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 67, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 208, in schedule_create_engine
    self.pstate_for_restart, initialdlstatus, share_mode=share_mode)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 308, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 272, in add_torrent
    torrent_handle = ltsession.add_torrent(encode_atp(atp))
exceptions.RuntimeError: torrent already exists in session


WARNING:Socks5Server:No session accepted this data from 88.162.108.146:57996
WARNING:Socks5Server:No session accepted this data from 5.79.74.31:6881
WARNING:Socks5Server:No session accepted this data from 85.21.183.6:51413
```

**Comment by devos50** [comment]
@synctext do you still get this one in the latest build?

**Comment by synctext** [comment]
no idea, GUI locks up after few seconds with new tracker error.

**Comment by devos50** [comment]
@synctext can you check with the latest build?

**Comment by devos50** [comment]
Closing this issue due to inactivity
