### ISSUE TITLE
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xa1 in position 34: invalid start byte

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2615]
While running latest alpha, after Dispersy already gave another TraceBack and perhaps died.

```
WARNING:Timeline:FAIL time:6 user:17610 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:17611 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:17612 -> permit^channel (no authorization)
WARNING:SearchCommunity:message from {192.168.254.16:7759 14.2.77.217:7759} cannot be found in the request cache, skipping it
WARNING:Timeline:FAIL time:6 user:17615 -> permit^channel (no authorization)
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/events_endpoint.py", line 139, in on_torrent_discovered
    self.write_data(json.dumps({"type": "torrent_discovered", "event": args[0]}))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xa1 in position 34: invalid start byte

WARNING:AllChannelCommunity:drop a 123 byte packet duplicate message by member^global_time (1) [dispersy-undo-own] from {192.168.0.3:7759 50.89.188.120:7759}
WARNING:AllChannelCommunity:drop a 123 byte packet duplicate message by member^global_time (1) [dispersy-undo-own] from {192.168.0.3:7759 50.89.188.120:7759}
ERROR:root:Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 101, in check_queue
    raise RuntimeError(data)
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/events_endpoint.py", line 139, in on_torrent_discovered
    self.write_data(json.dumps({"type": "torrent_discovered", "event": args[0]}))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xa1 in position 34: invalid start byte


WARNING:TunnelLogger:Removing relay 3850354308 unload
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
WARNING:TunnelLogger:Removing relay 927781133 unload
WARNING:TunnelLogger:Removing relay 2826112533 unload
WARNING:TunnelLogger:Removing relay 1188879011 unload
WARNING:TunnelLogger:Removing relay 1522936104 unload
WARNING:TunnelLogger:Removing relay 3433527609 unload
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
WARNING:TunnelLogger:Removing relay 153103290 unload
WARNING:TunnelLogger:Removing relay 4205191621 unload
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
WARNING:TunnelLogger:Removing relay 4195962125 unload
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
WARNING:TunnelLogger:Removing relay 1353309523 unload
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
WARNING:TunnelLogger:Removing relay 794590036 unload
WARNING:TunnelLogger:Removing relay 1199687260 unload
WARNING:TunnelLogger:Removing relay 3888567266 unload
WARNING:TunnelLogger:Removing relay 2765509479 unload
WARNING:TunnelLogger:Removing relay 1136348264 unload
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
WARNING:TunnelLogger:Removing relay 2946991986 unload
WARNING:TunnelLogger:Removing relay 967759989 unload
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
WARNING:TunnelLogger:Removing relay 890742783 unload
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
WARNING:TunnelLogger:Received message for unknown circuit ID: 1353309523
WARNING:TunnelLogger:Received message for unknown circuit ID: 2946991986
WARNING:TunnelLogger:Received message for unknown circuit ID: 2946991986
ERROR:root:Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/widgets/editchannelpage.py", line 234, in on_torrent_to_channel_added
    if 'added' in result:
TypeError: argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 785, in early_shutdown
ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/tribler_request_manager.py", line 74, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
    success = yield self.dispersy.stop()
RuntimeError: Dispersy is not running
Stopping Tribler...
Tribler stopped!!
Stopping Tribler...
```

**Comment by devos50** [comment]
That's weird: apparently, there is an invalid (unicode) character inside the discovered torrent. We should account for this.
