### ISSUE TITLE
exceptions.KeyError: '['

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2630]
When playing with the [latest Tribler 7 build](https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/691/) the events socket dropped and this error appeared within the logs.
```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 50, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/share/tribler/Tribler/dispersy/endpoint.py", line 250, in dispersythread_data_came_in
    u"standalone_ep")
  File "/usr/share/tribler/Tribler/dispersy/dispersy.py", line 1483, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp, source)
  File "/usr/share/tribler/Tribler/dispersy/community.py", line 2022, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/usr/share/tribler/Tribler/dispersy/community.py", line 2079, in _on_batch_cache
    messages.append(conversion.decode_message(candidate, packet, source=source))
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/usr/share/tribler/Tribler/dispersy/conversion.py", line 1219, in decode_message
    placeholder.offset, placeholder.payload = decode_functions.payload(placeholder, placeholder.offset, payload)
  File "/usr/share/tribler/Tribler/community/search/conversion.py", line 126, in _decode_search_response
    offset, payload = decode(data, offset)
  File "/usr/share/tribler/Tribler/Core/Utilities/encoding.py", line 337, in decode
    return _a_decode_mapping[stream[index]](stream, index + 1, int(stream[offset + 1:index]), _a_decode_mapping)
  File "/usr/share/tribler/Tribler/Core/Utilities/encoding.py", line 254, in _a_decode_tuple
    offset, value = mapping[stream[index]](stream, index + 1, int(stream[offset:index]), mapping)
  File "/usr/share/tribler/Tribler/Core/Utilities/encoding.py", line 220, in _a_decode_list
    offset, value = mapping[stream[index]](stream, index + 1, int(stream[offset:index]), mapping)
  File "/usr/share/tribler/Tribler/Core/Utilities/encoding.py", line 254, in _a_decode_tuple
    offset, value = mapping[stream[index]](stream, index + 1, int(stream[offset:index]), mapping)
exceptions.KeyError: '['

```

**Comment by qstokkink** [comment]
This seems like a search response which was sent without being `encode()`ed
