### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2631]
This is on Windows 10 Prerelease 14965, [bugreport copied from forum](https://forum.tribler.org/t/tribler-7-0-is-undergoing-internal-testing-ready-soon/3757/6)

Installed on my E: drive, because C: is am M2 SSD, but when starting Tribler complained value not c: but a switch to e: apparently failed.
uninstalled and reinstalled on C: and program started normally, but screen disappeared at soon as I picked settings, with the console
screen showing

```
Traceback (most recent call last):
File "TriblerGUI\tribler_request_manager.py", line 74, in on_finished
File "lib\json__init__.py", line 338, in loads
File "lib\json\decoder.py", line 366, in decode
File "lib\json\decoder.py", line 384, in raw_decode
ValueError: No JSON object could be decoded
```

**Comment by Nubro01** [comment]
Trid again and copied the console log
--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring

  File "TriblerGUI\core_manager.py", line 64, in start_tribler

  File "Tribler\dispersy\util.py", line 46, in helper

  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread

  File "Tribler\Core\Session.py", line 522, in start

  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 119, in register

  File "Tribler\Core\leveldbstore.py", line 84, in __init__

  File "lib\ntpath.py", line 529, in relpath

exceptions.ValueError: path is on drive C:, start on drive E:

**Comment by Nubro01** [comment]
Uninstalled, but current version detected excisting version, but I was unable to change c:\program files\tribler to E:\program files\tribler. so I manually removed old version.
Reinstalled on C:, clicked settings and ......

Qt: Untested Windows version 10.0 detected!
Warning: option --plugin-path no longer exists.
Warning: option --plugin-path no longer exists.
will connect to events endpoint
QSslSocket: cannot resolve TLSv1_1_client_method
QSslSocket: cannot resolve TLSv1_2_client_method
QSslSocket: cannot resolve TLSv1_1_server_method
QSslSocket: cannot resolve TLSv1_2_server_method
got error: 1
got error - starting Tribler core...
Qt: Untested Windows version 10.0 detected!
will connect to events endpoint
<PyQt5.QtNetwork.QNetworkReply object at 0x0000000006241EE8>
---- got event data ----
{"type": "events_start", "event": {"tribler_started": true, "version": "7.0.0-exp1-6-g4f51b8e"}}
{"type": "upgrader_finished"}
{"type": "tribler_started"}

ERROR:root:Traceback (most recent call last):
  File "TriblerGUI\widgets\settingspage.py", line 46, in initialize_with_settings
KeyError: 'showsaveas'

Error in sys.excepthook:
Traceback (most recent call last):
  File "TriblerGUI\tribler_window.py", line 55, in on_exception
  File "TriblerGUI\dialogs\feedbackdialog.py", line 19, in __init__
  File "lib\site-packages\PyQt5\uic\__init__.py", line 224, in loadUi
  File "lib\site-packages\PyQt5\uic\Loader\loader.py", line 72, in loadUi
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 949, in parse
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 774, in createUserInterface
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 752, in traverseWidgetTree
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 463, in createLayout
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 752, in traverseWidgetTree
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 506, in handleItem
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 752, in traverseWidgetTree
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 226, in createWidget
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 752, in traverseWidgetTree
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 463, in createLayout
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 752, in traverseWidgetTree
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 506, in handleItem
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 752, in traverseWidgetTree
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 217, in createWidget
  File "lib\site-packages\PyQt5\uic\uiparser.py", line 179, in setupObject
  File "lib\site-packages\PyQt5\uic\properties.py", line 415, in setProperties
AttributeError: 'QPlainTextEdit' object has no attribute 'setPlaceholderText'

Original exception was:
Traceback (most recent call last):
  File "TriblerGUI\widgets\settingspage.py", line 46, in initialize_with_settings
KeyError: 'showsaveas'
got error: 2

**Comment by devos50** [comment]
@Nubro01 thank you for your report!

It seems that you have a rather old build and various things have been changed already. The last error you linked (regarding the `keyError`): the `showsaveas` field is not fetched from the Tribler core anymore so that one cannot happen anymore. Also, the `AttributeError` has been fixed already.

The `ValueError` (`exceptions.ValueError: path is on drive C:, start on drive E:`) needs some more investigation however.

**Comment by devos50** [comment]
@synctext @Nubro01 new build with fixes for various issues: https://jenkins.tribler.org/job/Build_Tribler_devel/167/
