### ISSUE TITLE
Error when sending notification on torrent removal

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2638]
```
ERROR:Dispersy:exception during handle_callback for dispersy-dynamic-settings
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/Tribler/dispersy/dispersy.py", line 1744, in _update
    messages[0].handle_callback(messages)
  File "/Users/martijndevos/Documents/tribler/Tribler/community/channel/community.py", line 1128, in on_dynamic_settings
    Community.on_dynamic_settings(self, *args, **kwargs)
  File "/Users/martijndevos/Documents/tribler/Tribler/dispersy/community.py", line 3599, in on_dynamic_settings
    self._update_timerange(meta, globaltime_range[0], globaltime_range[1])
  File "/Users/martijndevos/Documents/tribler/Tribler/dispersy/community.py", line 3631, in _update_timerange
    meta.undo_callback([(message.authentication.member, message.distribution.global_time, message) for message in undo])
  File "/Users/martijndevos/Documents/tribler/Tribler/community/channel/community.py", line 442, in _disp_undo_torrent
    self._channelcast_db.on_remove_torrent_from_dispersy(self._channel_id, dispersy_id, redo)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 1537, in on_remove_torrent_from_dispersy
    "dispersy_cid": dispersy_cid.encode('hex')})
AttributeError: 'buffer' object has no attribute 'encode'
```

**Comment by qstokkink** [comment]
`dispersy_cid` is the raw data read from the database, which is a (read-only) `buffer` where a `str` seems to be expected, simply casting `dispersy_cid` to string should solve this without any issues.
