### ISSUE TITLE
No route to host error when running Tribler

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2647]
```
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 85, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
return callWithContext({"system": lp}, func, *args, **kw)
File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
return context.call({ILogContext: newCtx}, func, *args, **kw)
File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)
File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
return func(*args,**kw)
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
why = getattr(selectable, method)()
File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 227, in doRead
data, addr = self.socket.recvfrom(self.maxPacketSize)
socket.error: [Errno 113] No route to host
```

**Comment by devos50** [comment]
Actually, this error is quite common as indicated by the amount of bug reports received.

I've discussed this issue with someone else and finding the root cause of this error is not easy: it can be due to firewall issues or ISPs blocking hosts/ports. My suggestion is to log this error and not interrupt Tribler when this happens.
