### ISSUE TITLE
"exceptions.ValueError: Received a NULL pointer."

### ISSUE THREAD

**Issue by d33tah** [Tribler/tribler#2687]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

```
✗ git describe
initial_import-11989-g1725b60
```

##### Operating system and version: #####

Fedora release 24 

##### Expected behavior: #####

Tribler starts

##### Actual behavior: #####

```
Traceback (most recent call last):
  File "/home/d/workspace/0_src/tribler/Tribler/Main/tribler_main.py", line 989, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/home/d/workspace/0_src/tribler/Tribler/Main/tribler_main.py", line 115, in __init__
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/home/d/workspace/0_src/tribler/Tribler/Main/tribler_main.py", line 342, in InitStage1
    session = Session(self.sconfig, autoload_discovery=autoload_discovery)
  File "/home/d/workspace/0_src/tribler/Tribler/Core/Session.py", line 124, in __init__
    self.keypair = permidmod.generate_keypair()
  File "/home/d/workspace/0_src/tribler/Tribler/Core/permid.py", line 25, in generate_keypair
    ec_keypair = EC.gen_params(KEYPAIR_ECC_CURVE)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 269, in gen_params
    return EC(m2.ec_key_new_by_curve_name(curve), 1)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 106, in __init__
    assert m2.ec_key_type_check(ec), "'ec' type error"
ValueError: Received a NULL pointer.
```

##### Steps to reproduce the behavior: #####

On Fedora 24:

```
sudo yum install python-qt5 python2-configobj rb_libtorrent-python2
sudo pip install libnacl
./tribler.sh
```

**Comment by devos50** [comment]
Thanks for the report! That looks like a M2Crypto issue where the generation of the EC curve goes wrong. We will investigate it.

**Comment by devos50** [comment]
The default `M2Crypto` on Fedora does not have support for the specific EC curve we are using (`NID_sect233k1`). Please see #616 and #893 for more instructions about this. I will close this issue since we have received more reports about this.
