### ISSUE TITLE
Unable to add torrent from URL

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2693]
##### Tribler version/branch+revision: #####

b97f36e from #2691
743adf0 from devel

##### Operating system and version: #####

Linux Debian amd64, Awesome window manager

##### Expected behavior: #####

Can download https://tails.boum.org/torrents/files/tails-i386-2.9.1.torrent using Tribler

##### Actual behavior: #####

After pressing Download button (file list already displayed), error message shown (see backtrace).

##### Relevant log file output: #####

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py", line 270, in render_PUT
    unicode(parameters['uri'][0], 'utf-8'), download_config)
  File "/home/tribler/tribler/Tribler/Core/Session.py", line 282, in start_download_from_uri
    return self.lm.ltmgr.start_download_from_uri(uri, dconfig=dconfig)
  File "/home/tribler/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 515, in start_download_from_uri
    return self.start_download_from_url(uri, dconfig=dconfig)
  File "/home/tribler/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/tribler/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/tribler/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 530, in start_download_from_url
    deferred = TorrentDef.load_from_url(url)
  File "/home/tribler/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/tribler/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/tribler/tribler/Tribler/Core/TorrentDef.py", line 150, in load_from_url
    deferred = http_get(url)
  File "/home/tribler/tribler/Tribler/Core/Utilities/utilities.py", line 207, in http_get
    None)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 1592, in request
    parsedURI = URI.fromBytes(uri)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 629, in fromBytes
    scheme, netloc, path, params, query, fragment = http.urlparse(uri)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 169, in urlparse
    raise TypeError("url must be bytes, not unicode")
TypeError: url must be bytes, not unicode
```

##### Workaround ######

Download as file, add torrent from file.

**Comment by devos50** [comment]
Thanks for the report!
