### ISSUE TITLE
Dependencies on old wx GUI in the credit mining tests

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2703]
There are still dependencies in the credit mining tests on classes used in the old GUI. These should be fixed before #2700 can be merged safely.

Stack trace:

```
======================================================================
ERROR: Failure: ImportError (No module named Utility.GuiDBTuples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/Core/CreditMining/test_creditmining.py", line 14, in <module>
    from Tribler.Core.CreditMining.BoostingSource import ent2chr
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/CreditMining/BoostingSource.py", line 25, in <module>
    from Tribler.Core.CreditMining.credit_mining_util import TorrentManagerCM, ent2chr
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/CreditMining/credit_mining_util.py", line 13, in <module>
    from Tribler.Main.Utility.GuiDBTuples import CollectedTorrent, RemoteTorrent, NotCollectedTorrent, Channel, \
ImportError: No module named Utility.GuiDBTuples
```

**Comment by devos50** [comment]
@ardhipoetra are you able to take a look at this?

**Comment by ardhipoetra** [comment]
I'm quite conflicted in this. The dependencies you mentioned is a "model" class. Some of them are used as a helper from the database as well. I can't find similar type of class outside the 'Main' package. 

Refactoring can be done, but it will take quite a time since I also work on my thesis now. What do you think?

**Comment by devos50** [comment]
There is also another dependency on the GUI in the Core: https://github.com/Tribler/tribler/blob/devel/Tribler/Core/CreditMining/BoostingSource.py#L29

@ardhipoetra didn't you refactor these a while ago?

**Comment by devos50** [comment]
@ardhipoetra never mind, you did it on the `next` branch. I will back port these as soon as possible 👍

**Comment by ardhipoetra** [comment]
I even forgot about that. Working on two or more branch (`devel` and `next`) has made me drunk.
