### ISSUE TITLE
Issues in copy_shallow_candidate

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2708]
I received two bug reports regarding the new `copy_shallow_candidate` method:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 91, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AssertionError'>: ('37646364656438636563643736366330633032396639643335656130366136666332363166363738', 40)
lib\site-packages\twisted\internet\base.py:1195:run
lib\site-packages\twisted\internet\base.py:1204:mainLoop
lib\site-packages\twisted\internet\base.py:825:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:149:maybeDeferred
Tribler\dispersy\util.py:37:helper
Tribler\community\tunnel\tunnel_community.py:445:do_circuits
Tribler\community\tunnel\tunnel_community.py:484:do_remove
Tribler\community\tunnel\tunnel_community.py:691:remove_relay
Tribler\community\tunnel\tunnel_community.py:534:copy_shallow_candidate
Tribler\dispersy\dispersy.py:466:get_member
]
```

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 91, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AssertionError'>: Only one of the three optional arguments may be passed: (0, '', '')
lib\site-packages\twisted\internet\base.py:1195:run
lib\site-packages\twisted\internet\base.py:1204:mainLoop
lib\site-packages\twisted\internet\base.py:825:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:149:maybeDeferred
Tribler\dispersy\util.py:37:helper
Tribler\community\tunnel\tunnel_community.py:445:do_circuits
Tribler\community\tunnel\tunnel_community.py:484:do_remove
Tribler\community\tunnel\tunnel_community.py:691:remove_relay
Tribler\community\tunnel\tunnel_community.py:534:copy_shallow_candidate
Tribler\dispersy\dispersy.py:462:get_member
]
```

@qstokkink can you take a look at these?

**Comment by qstokkink** [comment]
On it. Should be fixed in the next few minutes.

**Comment by devos50** [comment]
@qstokkink that was fast :D

**Comment by qstokkink** [comment]
@devos50 I had exactly the same error for the TunnelExitSocket, so I knew exactly what was going wrong.
