### ISSUE TITLE
Unsupported address type when receiving tunnel data

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2710]
```
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 91, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
return callWithContext({"system": lp}, func, *args, **kw)
File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
return context.call({ILogContext: newCtx}, func, *args, **kw)
File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)
File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
return func(*args,**kw)
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
why = getattr(selectable, method)()
File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 208, in doRead
return self._dataReceived(data)
File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
rval = self.protocol.dataReceived(data)
File "/usr/share/tribler/Tribler/community/tunnel/Socks5/server.py", line 114, in dataReceived
if not self._try_request():
File "/usr/share/tribler/Tribler/community/tunnel/Socks5/server.py", line 169, in _try_request
offset, request = conversion.decode_request(0, self.buffer)
File "/usr/share/tribler/Tribler/community/tunnel/Socks5/conversion.py", line 174, in decode_request
offset, destination_address = __decode_address(address_type, offset, data)
File "/usr/share/tribler/Tribler/community/tunnel/Socks5/conversion.py", line 149, in __decode_address
raise ValueError("Unsupported address type %r" % address_type )
exceptions.ValueError: Unsupported address type 5
```

@qstokkink maybe we should just log this error and not raise an exception?

**Comment by qstokkink** [comment]
@devos50 Hmm.. in this case I think it would be best to extend the `try`: https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/Socks5/server.py#L179
