### ISSUE TITLE
OSX error: Symbol not found: _XML_SetHashSalt

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2721]
![20170114_214043](https://cloud.githubusercontent.com/assets/325224/21960983/4d4b7edc-dafd-11e6-959e-95d2f4d8ad26.jpg)

Latest 7.0 alpah2 fails to install on MacOS 10.10.5 without a popup or other easy to cut-and-paste errors. When the .dmg installer was clicked, new /Volume/tribler appeared. Starting a terminal and executing the 4th installer tribler app with  ```/tribler\ 4.app/Contents/MacOS/tribler``` yields the following error:
```
./tribler\ 4.app/Contents/MacOS/tribler

Failed to execute script pyi_rth_pkgres
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py",
line 389, in load_module
  File "pkg_resources.py", line 706, in <module>
  File "pkg_resources.py", line 709, in Environment
  File "pkg_resources.py", line 148, in get_supported_platform
  File "pkg_resources.py", line 241, in _macosx_vers
  File "platform.py", line 809, in mac_ver
  File "platform.py", line 786, in _mac_ver_xml
  File "plistlib.py", line 78, in readPlist
  File "plistlib.py", line 401, in parse
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "xml/parsers/expat.py", line 4, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 546, in load_module
ImportError: dlopen(/Applications/tribler 4.app/Contents/MacOS/pyexpat.so, 2): Symbol not found:
_XML_SetHashSalt
  Referenced from: /Applications/tribler 4.app/Contents/MacOS/pyexpat.so (which was built for Mac OS X 10.11)
  Expected in: /usr/lib/libexpat.1.dylib  in /Applications/tribler 4.app/Contents/MacOS/pyexpat.so
```

The ```which was built for Mac OS X 10.11``` sounds like a failure reason.

**Comment by devos50** [comment]
Ok, it seems that we need to build on the lowest OS version we support. The builders currently have 10.11 installed. If we wish to support 10.10, the whole system has to be reinstalled which requires some time.

**Comment by devos50** [comment]
I will take the Mac Mini home over the weekend so I can spent some time installing OS X 10.10 and making sure that everything is working correctly again.

**Comment by devos50** [comment]
Mission accomplished! Also tested it on newer versions of macOS (10.12) and it works fine.

![tribler7_10_10](https://cloud.githubusercontent.com/assets/1707075/22176461/49a630a2-e00b-11e6-9dae-0fd597bcc609.png)

@synctext please try out the latest build (https://jenkins.tribler.org/job/Build_Tribler_devel/206/)

**Comment by synctext** [comment]
yeah! it runs...
