### ISSUE TITLE
Ubuntu 14.04 LTS: Package python-pyqt5.qtsvg is not installed.

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2722]
14.04 LTS gives some install trouble for latest Alpha 2. Dropping support or dive into a fix?

```
pouwelse@johan-X1-Carbon:~$ sudo dpkg -i /home/pouwelse/Desktop/Download_Dir_Chromium/tribler_7.0.0-alpha2-2-gbdbc8d7_all.deb (Reading database ... 514999 files and directories currently installed.)
Preparing to unpack .../tribler_7.0.0-alpha2-2-gbdbc8d7_all.deb ...
Unpacking tribler (7.0.0-alpha2-2-gbdbc8d7) over (7.0.0-alpha2-2-gbdbc8d7) ...
dpkg: dependency problems prevent configuration of tribler:
 tribler depends on python-libtorrent (>= 0.16.18); however:
  Version of python-libtorrent on system is 0.16.13-1ubuntu2.1.
 tribler depends on python-pyqt5; however:
  Package python-pyqt5 is not installed.
 tribler depends on python-pyqt5.qtsvg; however:
  Package python-pyqt5.qtsvg is not installed.

dpkg: error processing package tribler (--install):
 dependency problems - leaving unconfigured
Processing triggers for gconf2 (3.2.6-0ubuntu2) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Errors were encountered while processing:
 tribler
pouwelse@johan-X1-Carbon:~$ sudo apt-get install pyqt5-dev pyqt5-dev-tools python3-pyqt5.qtsql python3-pyqt5.qtsvg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 pyqt5-dev : Depends: python3-sip-dev but it is not going to be installed
 pyqt5-dev-tools : Depends: python3-pyqt5 (= 5.2.1+dfsg-1ubuntu1) but it is not going to be installed
 python3-pyqt5.qtsql : Depends: python3-pyqt5 (= 5.2.1+dfsg-1ubuntu1) but it is not going to be installed
 python3-pyqt5.qtsvg : Depends: python3-pyqt5 (= 5.2.1+dfsg-1ubuntu1) but it is not going to be installed
 tribler : Depends: python-libtorrent (>= 0.16.18) but 0.16.13-1ubuntu2.1 is to be installed
           Depends: python-pyqt5 but it is not installable
           Depends: python-pyqt5.qtsvg but it is not installable
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
pouwelse@johan-X1-Carbon:~$ sudo pip install pyqt5-dev
Downloading/unpacking pyqt5-dev
  Could not find any downloads that satisfy the requirement pyqt5-dev
Cleaning up...
No distributions at all found for pyqt5-dev
Storing debug log for failure in /home/pouwelse/.pip/pip.log
pouwelse@johan-X1-Carbon:~$ sudo pip install pyqt5
Downloading/unpacking pyqt5
  Could not find any downloads that satisfy the requirement pyqt5
Cleaning up...
No distributions at all found for pyqt5
Storing debug log for failure in /home/pouwelse/.pip/pip.log

```

**Comment by devos50** [comment]
It seems that PyQt5 for Python 2 is available in apt-get starting from 14.10 (http://askubuntu.com/questions/662595/best-way-to-install-pyqt5-for-python-2-7-on-ubuntu-14-04). I would suggest to stop the support for 14.04 and add a notice in the readme.

**Comment by synctext** [comment]
```
pouwelse@johan-X1-Carbon:~$ pip install python-qt5
Downloading/unpacking python-qt5
  Downloading python-qt5-0.1.10.zip (57.5MB): 12.2MB downloaded
Cleaning up...
Operation cancelled by user
Storing debug log for failure in /tmp/tmpmADMY7
pouwelse@johan-X1-Carbon:~$ sudo pip install python-qt5
[sudo] password for pouwelse: 
Downloading/unpacking python-qt5
  Downloading python-qt5-0.1.10.zip (57.5MB): 57.5MB downloaded
  Running setup.py (path:/tmp/pip_build_root/python-qt5/setup.py) egg_info for package python-qt5
    
    
    The binaries distributed with this version are Windows only,
    
    - If you are on linux, look at
    github.com/pyqt/python-qt5/wiki/Compiling-PyQt5-on-Ubuntu-12.04.
    
    - If you are on OS X, look at the OSX specific port:
    github.com/pyqt/python-qt5-mavericks
    
    
Cleaning up...
No files/directories in /tmp/pip_build_root/python-qt5/pip-egg-info (from PKG-INFO)
Storing debug log for failure in /home/pouwelse/.pip/pip.log
pouwelse@johan-X1-Carbon:~$ cd /usr/share/tribler
pouwelse@johan-X1-Carbon:/usr/share/tribler$ ls
logger.conf  run_tribler.py  swift  Tribler  TriblerGUI  twisted
pouwelse@johan-X1-Carbon:/usr/share/tribler$ python run_tribler.py 
Traceback (most recent call last):
  File "run_tribler.py", line 8, in <module>
    from TriblerGUI.tribler_app import TriblerApplication
  File "/usr/share/tribler/TriblerGUI/tribler_app.py", line 3, in <module>
    from PyQt5.QtCore import QEvent
ImportError: No module named PyQt5.QtCore
```

**Comment by synctext** [comment]
Yes, let's drop support for Ubuntu 14.04 LTS.

**Comment by synctext** [comment]
Looong list of additional dependancies on Ubuntu 16.04, just documenting them here.
```sudo apt-get install python-pyqt5 python-pyqt5.qtsvg python-twisted libjs-excanvas libqt5help5 libqt5designer5 libqt5clucene5```

Extracted from 7.0 Alpha2 install.
```
pouwelse@johan-X1-Carbon:~$ sudo dpkg -i /home/pouwelse/Desktop/Download_Dir_Chromium/tribler_7.0.0-alpha2-4-g19ecae7_all.deb 
Selecting previously unselected package tribler.
(Reading database ... 587188 files and directories currently installed.)
Preparing to unpack .../tribler_7.0.0-alpha2-4-g19ecae7_all.deb ...
Unpacking tribler (7.0.0-alpha2-4-g19ecae7) ...
dpkg: dependency problems prevent configuration of tribler:
 tribler depends on libjs-excanvas; however:
  Package libjs-excanvas is not installed.
 tribler depends on python-twisted; however:
  Package python-twisted is not installed.
 tribler depends on python-pyqt5; however:
  Package python-pyqt5 is not installed.
 tribler depends on python-pyqt5.qtsvg; however:
  Package python-pyqt5.qtsvg is not installed.

dpkg: error processing package tribler (--install):
 dependency problems - leaving unconfigured
Processing triggers for gconf2 (3.2.6-3ubuntu6) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Errors were encountered while processing:
 tribler
pouwelse@johan-X1-Carbon:~$ sudo apt-get install python-pyqt5 python-pyqt5.qtsvg python-twisted libjs-excanvas
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 python-pyqt5 : Depends: libqt5designer5 (>= 5.0.2) but it is not going to be installed
                Depends: libqt5help5 (>= 5.3.0) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
pouwelse@johan-X1-Carbon:~$ sudo apt-get install python-pyqt5 python-pyqt5.qtsvg python-twisted libjs-excanvas libqt5help5 libqt5designer5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libqt5help5 : Depends: libqt5clucene5 (>= 5.0.2) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
pouwelse@johan-X1-Carbon:~$ sudo apt-get install python-pyqt5 python-pyqt5.qtsvg python-twisted libjs-excanvas libqt5help5 libqt5designer5 libqt5clucene5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  python-pyqt5-dbg
The following NEW packages will be installed:
  libjs-excanvas libqt5clucene5 libqt5designer5 libqt5help5 python-pyqt5 python-pyqt5.qtsvg python-twisted
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 5,295 kB/5,344 kB of archives.
After this operation, 22.0 MB of additional disk space will be used.
Get:1 http://nl.archive.ubuntu.com/ubuntu xenial/universe amd64 libqt5designer5 amd64 5.5.1-3build1 [2,719 kB]
Get:2 http://nl.archive.ubuntu.com/ubuntu xenial/universe amd64 libqt5clucene5 amd64 5.5.1-3build1 [264 kB]
Get:3 http://nl.archive.ubuntu.com/ubuntu xenial/universe amd64 libqt5help5 amd64 5.5.1-3build1 [183 kB]
Get:4 http://nl.archive.ubuntu.com/ubuntu xenial/universe amd64 python-pyqt5 amd64 5.5.1+dfsg-3ubuntu4 [2,105 kB]
Get:5 http://nl.archive.ubuntu.com/ubuntu xenial/universe amd64 python-pyqt5.qtsvg amd64 5.5.1+dfsg-3ubuntu4 [23.1 kB]
Fetched 5,295 kB in 2s (1,849 kB/s)           
Selecting previously unselected package libjs-excanvas.
(Reading database ... 588612 files and directories currently installed.)
Preparing to unpack .../libjs-excanvas_0.r3-4_all.deb ...
Unpacking libjs-excanvas (0.r3-4) ...
Selecting previously unselected package python-twisted.
Preparing to unpack .../python-twisted_16.0.0-1_all.deb ...
Unpacking python-twisted (16.0.0-1) ...
Selecting previously unselected package libqt5designer5:amd64.
Preparing to unpack .../libqt5designer5_5.5.1-3build1_amd64.deb ...
Unpacking libqt5designer5:amd64 (5.5.1-3build1) ...
Selecting previously unselected package libqt5clucene5:amd64.
Preparing to unpack .../libqt5clucene5_5.5.1-3build1_amd64.deb ...
Unpacking libqt5clucene5:amd64 (5.5.1-3build1) ...
Selecting previously unselected package libqt5help5:amd64.
Preparing to unpack .../libqt5help5_5.5.1-3build1_amd64.deb ...
Unpacking libqt5help5:amd64 (5.5.1-3build1) ...
Selecting previously unselected package python-pyqt5.
Preparing to unpack .../python-pyqt5_5.5.1+dfsg-3ubuntu4_amd64.deb ...
Unpacking python-pyqt5 (5.5.1+dfsg-3ubuntu4) ...
Selecting previously unselected package python-pyqt5.qtsvg.
Preparing to unpack .../python-pyqt5.qtsvg_5.5.1+dfsg-3ubuntu4_amd64.deb ...
Unpacking python-pyqt5.qtsvg (5.5.1+dfsg-3ubuntu4) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Setting up libjs-excanvas (0.r3-4) ...
Setting up python-twisted (16.0.0-1) ...
Setting up libqt5designer5:amd64 (5.5.1-3build1) ...
Setting up libqt5clucene5:amd64 (5.5.1-3build1) ...
Setting up libqt5help5:amd64 (5.5.1-3build1) ...
Setting up python-pyqt5 (5.5.1+dfsg-3ubuntu4) ...
Setting up python-pyqt5.qtsvg (5.5.1+dfsg-3ubuntu4) ...
Setting up tribler (7.0.0-alpha2-4-g19ecae7) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
```
