### ISSUE TITLE
DelayMessageByProof error in Dispersy

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2742]
Received this in the crash reporter:

```
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 91, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AssertionError'>: [DelayMessageByProof('DelayMessageByProof',), <Tribler.dispersy.message.Implementation object at 0x7ff90e50e0d0>]
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1194:run
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1203:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:825:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/usr/share/tribler/Tribler/dispersy/community.py:1217:take_step
/usr/share/tribler/Tribler/dispersy/community.py:2673:create_introduction_request
/usr/share/tribler/Tribler/dispersy/community.py:2113:flush_batch_cache
/usr/share/tribler/Tribler/dispersy/community.py:2050:_process_message_batch
/usr/share/tribler/Tribler/dispersy/community.py:2092:_on_batch_cache
/usr/share/tribler/Tribler/dispersy/community.py:2179:on_messages
]
```

@qstokkink can you say anything about this issue?

**Comment by qstokkink** [comment]
This is a very, very nasty one. This happens if a delay or drop (in this case delay) is processed at the same time as the original message. Ergo, some mechanism is trying to both delay/drop at the same time as process the same exact message.

I have seen this happen more when mixing messages in the Protobuf project. There are certain exotic ways for this to happen in vanilla Dispersy/Tribler as well.

Counter-intuitively, the correct way to handle this would be to process the message (and remove it from the delayed_value and delayed_keys and such). This sounds easy, but Dispersy is rather.. iffy about this sort of thing. This will not be a quick fix, is what I'm trying to say.

**Comment by devos50** [comment]
@qstokkink thanks, I also got this one, related?

```
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 91, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/usr/share/tribler/TriblerGUI/core_manager.py", line 61, in start_tribler_core
reactor.run()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
self.mainLoop()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
self.runUntilCurrent()
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
call.func(*call.args, **call.kw)
File "/usr/share/tribler/Tribler/dispersy/community.py", line 2050, in _process_message_batch
return self._on_batch_cache(meta, batch)
File "/usr/share/tribler/Tribler/dispersy/community.py", line 2092, in _on_batch_cache
self.on_messages(messages)
File "/usr/share/tribler/Tribler/dispersy/community.py", line 2179, in on_messages
assert all(message.delayed not in possibly_messages for message in possibly_messages if isinstance(message, DelayMessage)), possibly_messages # delayed messages cannot be accepted
exceptions.AssertionError: [<Tribler.dispersy.message.Implementation object at 0x7f11081aad90>, <Tribler.dispersy.message.Implementation object at 0x7f11081aab10>, <Tribler.dispersy.message.Implementation object at 0x7f11081aa890>, <Tribler.dispersy.message.Implementation object at 0x7f11081aa610>, <Tribler.dispersy.message.Implementation object at 0x7f11081aa390>, <Tribler.dispersy.message.Implementation object at 0x7f11081aa110>, <Tribler.dispersy.message.Implementation object at 0x7f11081b2e50>, <Tribler.dispersy.message.Implementation object at 0x7f11081b2bd0>, <Tribler.dispersy.message.Implementation object at 0x7f11081b2950>, <Tribler.dispersy.message.Implementation object at 0x7f11081b26d0>, <Tribler.dispersy.message.Implementation object at 0x7f11081b2450>, <Tribler.dispersy.message.Implementation object at 0x7f11081b21d0>, <Tribler.dispersy.message.Implementation object at 0x7f110818ef10>, <Tribler.dispersy.message.Implementation object at 0x7f110818ec90>, <Tribler.dispersy.message.Implementation object at 0x7f110818ea10>, <Tribler.dispersy.message.Implementation object at 0x7f110818e790>, <Tribler.dispersy.message.Implementation object at 0x7f110818e510>, <Tribler.dispersy.message.Implementation object at 0x7f110818e290>, <Tribler.dispersy.message.Implementation object at 0x7f11081a6fd0>, <Tribler.dispersy.message.Implementation object at 0x7f11081a6d50>, <Tribler.dispersy.message.Implementation object at 0x7f11081a6ad0>, <Tribler.dispersy.message.Implementation object at 0x7f11081a6850>, <Tribler.dispersy.message.Implementation object at 0x7f11081a65d0>, <Tribler.dispersy.message.Implementation object at 0x7f11081a6350>, <Tribler.dispersy.message.Implementation object at 0x7f11081a60d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108292e10>, <Tribler.dispersy.message.Implementation object at 0x7f1108292b90>, <Tribler.dispersy.message.Implementation object at 0x7f1108292910>, <Tribler.dispersy.message.Implementation object at 0x7f1108292690>, <Tribler.dispersy.message.Implementation object at 0x7f1108292410>, <Tribler.dispersy.message.Implementation object at 0x7f1108292190>, <Tribler.dispersy.message.Implementation object at 0x7f1108296ed0>, <Tribler.dispersy.message.Implementation object at 0x7f1108296c50>, <Tribler.dispersy.message.Implementation object at 0x7f11082969d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108296750>, <Tribler.dispersy.message.Implementation object at 0x7f11082964d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108296250>, <Tribler.dispersy.message.Implementation object at 0x7f110829af90>, <Tribler.dispersy.message.Implementation object at 0x7f110829ad10>, <Tribler.dispersy.message.Implementation object at 0x7f110829aa90>, <Tribler.dispersy.message.Implementation object at 0x7f110829a810>, <Tribler.dispersy.message.Implementation object at 0x7f110829a590>, <Tribler.dispersy.message.Implementation object at 0x7f110829a310>, <Tribler.dispersy.message.Implementation object at 0x7f110829a090>, <Tribler.dispersy.message.Implementation object at 0x7f11082a7dd0>, <Tribler.dispersy.message.Implementation object at 0x7f11082a7b50>, <Tribler.dispersy.message.Implementation object at 0x7f11082a78d0>, <Tribler.dispersy.message.Implementation object at 0x7f11082a7650>, <Tribler.dispersy.message.Implementation object at 0x7f11082a73d0>, <Tribler.dispersy.message.Implementation object at 0x7f11082a7150>, <Tribler.dispersy.message.Implementation object at 0x7f11082a5e90>, <Tribler.dispersy.message.Implementation object at 0x7f11082a5c10>, <Tribler.dispersy.message.Implementation object at 0x7f11082a5990>, <Tribler.dispersy.message.Implementation object at 0x7f11082a5710>, <Tribler.dispersy.message.Implementation object at 0x7f11082a5490>, <Tribler.dispersy.message.Implementation object at 0x7f11082a5210>, <Tribler.dispersy.message.Implementation object at 0x7f1108295f50>, <Tribler.dispersy.message.Implementation object at 0x7f1108295cd0>, <Tribler.dispersy.message.Implementation object at 0x7f1108295a50>, <Tribler.dispersy.message.Implementation object at 0x7f11082957d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108295550>, <Tribler.dispersy.message.Implementation object at 0x7f11082952d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108295050>, <Tribler.dispersy.message.Implementation object at 0x7f11082b1d90>, <Tribler.dispersy.message.Implementation object at 0x7f11082b1b10>, <Tribler.dispersy.message.Implementation object at 0x7f11082b1890>, <Tribler.dispersy.message.Implementation object at 0x7f11082b1610>, <Tribler.dispersy.message.Implementation object at 0x7f11082b1390>, <Tribler.dispersy.message.Implementation object at 0x7f11082b1110>, <Tribler.dispersy.message.Implementation object at 0x7f11082a0e50>, <Tribler.dispersy.message.Implementation object at 0x7f11082a0bd0>, <Tribler.dispersy.message.Implementation object at 0x7f11082a0950>, <Tribler.dispersy.message.Implementation object at 0x7f11082a06d0>, <Tribler.dispersy.message.Implementation object at 0x7f11082a0450>, <Tribler.dispersy.message.Implementation object at 0x7f11082a01d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108287f10>, <Tribler.dispersy.message.Implementation object at 0x7f1108287c90>, <Tribler.dispersy.message.Implementation object at 0x7f1108287a10>, <Tribler.dispersy.message.Implementation object at 0x7f1108287790>, <Tribler.dispersy.message.Implementation object at 0x7f1108287510>, <Tribler.dispersy.message.Implementation object at 0x7f1108287290>, <Tribler.dispersy.message.Implementation object at 0x7f110828afd0>, <Tribler.dispersy.message.Implementation object at 0x7f110828ad50>, <Tribler.dispersy.message.Implementation object at 0x7f110828aad0>, <Tribler.dispersy.message.Implementation object at 0x7f110828a850>, <Tribler.dispersy.message.Implementation object at 0x7f110828a5d0>, <Tribler.dispersy.message.Implementation object at 0x7f110828a350>, <Tribler.dispersy.message.Implementation object at 0x7f110828a0d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108234e10>, <Tribler.dispersy.message.Implementation object at 0x7f1108234b90>, <Tribler.dispersy.message.Implementation object at 0x7f1108234910>, <Tribler.dispersy.message.Implementation object at 0x7f1108234690>, <Tribler.dispersy.message.Implementation object at 0x7f1108234410>, <Tribler.dispersy.message.Implementation object at 0x7f1108234190>, <Tribler.dispersy.message.Implementation object at 0x7f1108209ed0>, <Tribler.dispersy.message.Implementation object at 0x7f1108209c50>, <Tribler.dispersy.message.Implementation object at 0x7f11082099d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108209750>, <Tribler.dispersy.message.Implementation object at 0x7f11082094d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108209250>, <Tribler.dispersy.message.Implementation object at 0x7f1108231f90>, <Tribler.dispersy.message.Implementation object at 0x7f1108231d10>, <Tribler.dispersy.message.Implementation object at 0x7f1108231a90>, <Tribler.dispersy.message.Implementation object at 0x7f1108231810>, <Tribler.dispersy.message.Implementation object at 0x7f1108231590>, <Tribler.dispersy.message.Implementation object at 0x7f1108231310>, <Tribler.dispersy.message.Implementation object at 0x7f1108231090>, <Tribler.dispersy.message.Implementation object at 0x7f1108239dd0>, <Tribler.dispersy.message.Implementation object at 0x7f1108239b50>, <Tribler.dispersy.message.Implementation object at 0x7f11082398d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108239650>, <Tribler.dispersy.message.Implementation object at 0x7f11082393d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108239150>, <Tribler.dispersy.message.Implementation object at 0x7f1108205e90>, <Tribler.dispersy.message.Implementation object at 0x7f1108205c10>, <Tribler.dispersy.message.Implementation object at 0x7f1108205990>, <Tribler.dispersy.message.Implementation object at 0x7f1108205710>, <Tribler.dispersy.message.Implementation object at 0x7f1108205490>, <Tribler.dispersy.message.Implementation object at 0x7f1108205210>, <Tribler.dispersy.message.Implementation object at 0x7f1108200f50>, <Tribler.dispersy.message.Implementation object at 0x7f1108200cd0>, <Tribler.dispersy.message.Implementation object at 0x7f1108200a50>, <Tribler.dispersy.message.Implementation object at 0x7f11082007d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108200550>, <Tribler.dispersy.message.Implementation object at 0x7f11082002d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108200050>, <Tribler.dispersy.message.Implementation object at 0x7f110820dd90>, <Tribler.dispersy.message.Implementation object at 0x7f110820db10>, <Tribler.dispersy.message.Implementation object at 0x7f110820d890>, <Tribler.dispersy.message.Implementation object at 0x7f110820d610>, <Tribler.dispersy.message.Implementation object at 0x7f110820d390>, <Tribler.dispersy.message.Implementation object at 0x7f110820d110>, <Tribler.dispersy.message.Implementation object at 0x7f1108208e50>, <Tribler.dispersy.message.Implementation object at 0x7f1108208bd0>, <Tribler.dispersy.message.Implementation object at 0x7f1108208950>, <Tribler.dispersy.message.Implementation object at 0x7f11082086d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108208450>, <Tribler.dispersy.message.Implementation object at 0x7f11082081d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108213f10>, <Tribler.dispersy.message.Implementation object at 0x7f1108213c90>, <Tribler.dispersy.message.Implementation object at 0x7f1108213a10>, <Tribler.dispersy.message.Implementation object at 0x7f1108213790>, <Tribler.dispersy.message.Implementation object at 0x7f1108213510>, <Tribler.dispersy.message.Implementation object at 0x7f1108213290>, <Tribler.dispersy.message.Implementation object at 0x7f1108222fd0>, <Tribler.dispersy.message.Implementation object at 0x7f1108222d50>, <Tribler.dispersy.message.Implementation object at 0x7f1108222ad0>, <Tribler.dispersy.message.Implementation object at 0x7f1108222850>, <Tribler.dispersy.message.Implementation object at 0x7f11082225d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108222350>, <Tribler.dispersy.message.Implementation object at 0x7f11082220d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108237590>, <Tribler.dispersy.message.Implementation object at 0x7f11082378d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108237390>, <Tribler.dispersy.message.Implementation object at 0x7f11083384d0>, <Tribler.dispersy.message.Implementation object at 0x7f1108255d90>, <Tribler.dispersy.message.Implementation object at 0x7f1108255dd0>, <Tribler.dispersy.message.Implementation object at 0x7f1108247e50>, <Tribler.dispersy.message.Implementation object at 0x7f1108247390>, DelayMessageByProof('DelayMessageByProof',), <Tribler.dispersy.message.Implementation object at 0x7f1108247310>]
```

**Comment by devos50** [comment]
Also, if it's not a quick fix, I think we should postpone it to Tribler 7.1 or later. Is it easy to modify the code in such a way that this does not crash Tribler?

**Comment by qstokkink** [comment]
@devos50 (1) Yes, that's the same thing.

(2) Currently, if you do a hard-remove of this assertion or catch it, Dispersy will crash horribly later. The only way - which I could find and works 100% of the time - to work around this, is to handle messages in `on_messages` one-by-one. Correct execution is guaranteed this way. The added benefit to this, is that the system becomes more predictable and better to work with if you are mixing up the incoming messages instead of processing batches (which I needed in my specific case).
There is some theoretical performance loss doing this though, in certain situations.

Of course the batch-based approach would be the one I posted earlier. Which is what Dispersy was designed for.

**Comment by devos50** [comment]
@qstokkink ok, in that case, I think we should not tamper with Dispersy too much now, especially since it's an issue that only occurs in a very small amount of the runs. We should discuss this when we are going to modify Dispersy but that will probably be somewhere later this year.

Also, I think a performance lose in favour of predictability in Dispersy is not something that we should do (at least not now): Dispersy is already responsible for a huge amount of CPU cycles, making it already unusable on devices with less resources like a Raspberry Pi. While Dispersy was not designed to run on such devices, I think if we move to an asynchronous Dispersy, things will improve and we can also take a look at this and the way we process messages.

Finally, I think we need a better QA process for Dispersy before we make such changes.

**Comment by synctext** [comment]
Deleting and burning ```DelayMessageByProof()``` is on my ToDo list.

In steps we can re-factor this out I hope in 7.x series. By using atomic processing and message-with-proof-inclusions (a.k.a. signatures). Similar to how we got rid of lots of delayed messages by using full public key inclusion. Dispersy has some design assumptions (bandwidth-efficiency-above-all-else) that we need to replace with simplicity-and-correctness-are-key.

**Comment by devos50** [comment]
@qstokkink I've received this report again yesterday, twice. I think we should do something about it. How easy do you think it is to remove batch processing? Or is there any other easy solution like ignoring the message (don't know the impact of this change)?

**Comment by qstokkink** [comment]
@devos50 The __temporary__ easy workaround would be to do the following in `community.py`:

```python
def on_messages(messages):
    return sum(self._on_messages([m]) for m in messages)

def _on_messages(messages):
   # old on_messages code here
```

This effectively negates any batching complications and is completely safe.

Completely removing batching would probably take a few weeks.

**Comment by devos50** [comment]
@qstokkink thanks for the suggestion. Unfortunately, the units tests are broken for the PR with your proposed modification (https://jenkins.tribler.org/job/dispersy/job/GH/job/PR/job/Unit_tests_linux/1852/) so I should try to fix them first before we merge it.

**Comment by qstokkink** [comment]
@devos50 I just had a look at the failed tests. All of the failures are expected.

- The previous behavior was to process messages and delay a batch of remaining messages when a message is not ready yet.
 - The fix's behavior is to handle as many messages as possible and delay/drop the ones that are not ready yet.

The fix will not cause 'wrong' handling of messages: as far as Dispersy is concerned (outside of testing) this simply simulates a really small batch window or badly timed message arrivals between the processing of batches.

The reason for the old behavior (which may seem to only hurt throughput) is the following: if message A has to be delayed then message B, coming after A, is more likely to also have to be delayed as they are the same type of message. This is anecdotal evidence, but from what I have seen, more messages can be processed than have to be delayed though. This is why the fix usually causes a boost in responsiveness, but in some situations (like I mentioned in a previous post) when there are a lot of messages which need to be delayed, cause a performance loss.

**Comment by qstokkink** [comment]
@devos50 Something else you can do is replace the assertion with this:

```python

possibly_messages = [message for message in possibly_messages if (not isinstance(message, DelayMessage) or (message.delayed not in possibly_messages))]

```

This keeps the batching behavior, which, for now, might be better.

**Comment by synctext** [comment]
Stability and correctness would be great for Tribler/Dispersy.
Small performance hit for disabling batching sounds very much OK for me.

Should be removed cleanly later I think.
