### ISSUE TITLE
Tribler crashes when visiting Trust page

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#2816]
On 1b4f68beb6ce96ebd41e6b176cb82a2d4497042d.

##### Operating system and version: #####
Ubuntu 16.10. `~/.Tribler` didn't exist.

##### Expected behavior: #####
When clicking on the star in the top-right corner, the trust page is shown.

##### Actual behavior: #####
Crash with stack trace
```Traceback (most recent call last):
  File "/home/user/tribler/TriblerGUI/widgets/trustpage.py", line 104, in received_multichain_blocks
    self.plot_absolute_values()
  File "/home/user/tribler/TriblerGUI/widgets/trustpage.py", line 124, in plot_absolute_values
    self.trust_plot.compute_initial_figure()
  File "/home/user/tribler/TriblerGUI/widgets/trustpage.py", line 64, in compute_initial_figure
    self.draw()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 158, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2319, in draw
    a.draw(renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 1108, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 951, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 898, in iter_ticks
    for i, val in enumerate(majorLocs)]
  File "/usr/lib/python2.7/dist-packages/matplotlib/dates.py", line 484, in __call__
    dt = num2date(x, self.tz)
  File "/usr/lib/python2.7/dist-packages/matplotlib/dates.py", line 419, in num2date
    return _from_ordinalf(x, tz)
  File "/usr/lib/python2.7/dist-packages/matplotlib/dates.py", line 271, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
ValueError: ordinal must be >= 1```

**Comment by devos50** [comment]
Good find, thanks!
