### ISSUE TITLE
matplotlib is confused about the QT version

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2823]
I run into this error on startup since the trust screen was added:
```
ERROR:root:Traceback (most recent call last):
  File "run_tribler.py", line 21, in <module>
    window = TriblerWindow()
  File "/home/quinten/tribler/tribler/TriblerGUI/tribler_window.py", line 101, in __init__
    uic.loadUi(get_ui_file_path('mainwindow.ui'), self)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/__init__.py", line 222, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 980, in parse
    actor(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 787, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 249, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 462, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 505, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 462, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 505, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 249, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 240, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 204, in setupObject
    obj = self.factory.createQObject(clsname, name, args, is_attribute)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/objcreator.py", line 106, in createQObject
    factory = self.findQObjectType(classname)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/objcreator.py", line 131, in findQObjectType
    w = module.search(classname)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/Loader/qobjectcreator.py", line 115, in search
    module = __import__(mname, {}, {}, (cls,))
  File "/home/quinten/tribler/tribler/TriblerGUI/widgets/trustpage.py", line 7, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvas
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

This can be solved by explicitly pointing matplotlib to QT5 in [`trustpage.py` line 2](https://github.com/Tribler/tribler/blob/devel/TriblerGUI/widgets/trustpage.py#L2):
```python
import matplotlib
matplotlib.use('Qt5Agg')
```

**Comment by devos50** [comment]
Hmm weird that I didn't have this in the code since I learned about it when I started integrating matplotlib and Qt5. I guess I forgot about it when worked without setting the backend explicitly...
