### ISSUE TITLE
Tribler 7 GUI freezes after a couple of days

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#2842]
##### Tribler version/branch+revision: #####
```
$ git log
commit 4d4ef144dc0d94110a350716cfe059d4c08da373
Merge: 1905399 038efde
Author: Martijn de Vos <mdmartijndevos@gmail.com>
Date:   Mon Feb 27 16:13:54 2017 +0100

    Merge pull request #2818 from vandenheuvel/fix_rewrite_tracker_utils
    
    Rewrite tracker_utils to use urlparse
$ git status
On branch devel
Your branch is up-to-date with 'origin/devel'.
```
(this is a pull from last week as it takes a couple of days for this issue to trigger)

##### Operating system and version: #####
Linux Mint 18.1 with Python 2.7.12 in a vm

##### Expected behavior: #####
GUI always stays responsive

##### Actual behavior: #####
After having Tribler 7 open for a couple of days, the GUI becomes unresponsive. The GUI is not updated anymore and (if the GUI was still open at first) when you switch windows the whole GUI window disappears / becomes transparent. The tray icon is still visible but also unresponsive. All other threads seem to be running still, eg when you forcibly close Tribler and restart it downloads have progressed and/or finished. This behaviour has occurred repeatedly the last couple of months.

##### Steps to reproduce the behavior: #####
Because it takes some time for this issue to trigger, it's difficult to test why/when this happens exactly. Not sure if just keeping the window open will reproduce it or that the vm is an issue here.

##### Relevant log file output: #####
Not sure how to debug this, no errors are showing in the STDERR output (but scrollback is limited) and no log file exists in ~/.Tribler or /var/log/. I start tribler as follows:
```
$ cd ~/bin/tribler
$ git pull
$ ./tribler.sh
```
Please let me know how I can help to debug this issue :)

**Comment by mrspits4ever** [comment]
just a suggestion but maybe the bug will trigger agian if you change your date/time a few days forward/back?

**Comment by qstokkink** [comment]
I have had an issue in the past (on Windows) where the GUI would lock up until input was received in the terminal window. It's a long shot, but you could try it.

**Comment by pimlie** [comment]
Unfortunately the suggestions didnt work, at the moment the GUI is not frozen but does not update either. So I can click through the whole GUI but download & upload speed columns do not change, e.g it says 1.7kB/s download but when I check current traffic on my router it is >10Mb/s. I can click through the Details/Files/Trackers/Peers tabs but it says Peers 0 and no updated info. Then when I close Tribler (normally, not forced) it exits with a Segmentation fault. 

I will see if I can capture some more info by running tribler through gdb.

**Comment by pimlie** [comment]
So the GUI didnt update anymore since somewhere last night but now when I close Tribler gdb is stuck at 100% cpu and doesnt return to a (gdb) prompt. Not sure what is happening here. 

I used the following cmd to start tribler: `gdb --args python2.7 ~/bin/tribler/run_tribler.py`

**Comment by Dmole** [comment]
I see this happen in a few minutes on v7b for MacOS (maybe the screen sleep triggers it).
Progress will show 5% of 5GB restart Tribler and it's instantly at 100%.

**Comment by synctext** [comment]
Hopefully we got the cause now: #2876 
We're working on a Beta2 and hopefully that is more stable.

**Comment by devos50** [comment]
I've started a Tribler instance on one of our VMs to see whether I can reproduce this issue.

**Comment by devos50** [comment]
Also, I'm starting to think that Tribler might have run out of memory. I will monitor the memory closely to see whether this is the case.

**Comment by synctext** [comment]
Hmmm. Would it be easy and helpful to print memusage to logfile, say, 4 times a day or if goes beyond 1GByte or other magic number? Put in debug panel for our Windows users?

**Comment by Dmole** [comment]
My experience of a stalled UI was not due to low memory (unless it was maybe Python VM memory) more likely The horrible IO scheduler in MacOS not being accounted for. (if one thread asks for 50GB then another asks for 1b the second thread is not getting an answer for a long time.) Time to use Ubuntu on the desktop again.

**Comment by synctext** [comment]
started tribler through gdb, got GUI freeze and obtained this debug info:
```
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fcd700 (LWP 723) "python" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  2    Thread 0x7fffe41de700 (LWP 730) "QXcbEventReader" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  3    Thread 0x7fffd9ec7700 (LWP 731) "dconf worker" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  4    Thread 0x7fffd96c6700 (LWP 732) "gmain" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  5    Thread 0x7fffd8ec5700 (LWP 733) "gdbus" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  8    Thread 0x7fffc7029700 (LWP 738) "Qt bearer threa" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  9    Thread 0x7fffc802b700 (LWP 741) "threaded-ml" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  10   Thread 0x7fffaa3e8700 (LWP 743) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  12   Thread 0x7fffa8c52700 (LWP 747) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  14   Thread 0x7fff9b7fe700 (LWP 764) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  16   Thread 0x7fff9a7fc700 (LWP 768) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  162  Thread 0x7fff31feb700 (LWP 944) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  163  Thread 0x7fff317ea700 (LWP 945) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  164  Thread 0x7fff30fe9700 (LWP 946) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  166  Thread 0x7fff34ff1700 (LWP 948) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  167  Thread 0x7fff357f2700 (LWP 949) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  168  Thread 0x7fff35ff3700 (LWP 950) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  169  Thread 0x7fffa9be7700 (LWP 951) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  170  Thread 0x7fff9bfff700 (LWP 952) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  914  Thread 0x7fff27fd7700 (LWP 1932) "python" 0x00007ffff4f9c6a2 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
  917  Thread 0x7fff26fd5700 (LWP 1939) "python" 0x00007ffff4f9c6a2 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
  918  Thread 0x7fff267d4700 (LWP 1940) "python" 0x00007ffff4f9c6a2 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
  919  Thread 0x7fff25fd3700 (LWP 1942) "python" 0x00007ffff4f9c6a2 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
  928  Thread 0x7fff1dfc3700 (LWP 1954) "python" 0x00007ffff4f9c6a2 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
  935  Thread 0x7fff1a7bc700 (LWP 1964) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  936  Thread 0x7fff1afbd700 (LWP 1968) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  937  Thread 0x7fff1b7be700 (LWP 1969) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  938  Thread 0x7fff1bfbf700 (LWP 1970) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  939  Thread 0x7fff1c7c0700 (LWP 1971) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  940  Thread 0x7fff9affd700 (LWP 1972) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  941  Thread 0x7fff99ffb700 (LWP 1973) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  943  Thread 0x7fff98ff9700 (LWP 1975) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  944  Thread 0x7fff7ae1d700 (LWP 1976) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  945  Thread 0x7fff7a61c700 (LWP 1977) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  946  Thread 0x7fff79e1b700 (LWP 1978) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  947  Thread 0x7fff7961a700 (LWP 1979) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  948  Thread 0x7fff78e19700 (LWP 1980) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  949  Thread 0x7fff5bfff700 (LWP 1981) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  950  Thread 0x7fff5b7fe700 (LWP 1982) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  951  Thread 0x7fff5affd700 (LWP 1983) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  952  Thread 0x7fff5a7fc700 (LWP 1984) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  953  Thread 0x7fff59ffb700 (LWP 1985) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  954  Thread 0x7fff597fa700 (LWP 1986) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  955  Thread 0x7fff58ff9700 (LWP 1987) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  956  Thread 0x7fff3bfff700 (LWP 1988) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  957  Thread 0x7fff3b7fe700 (LWP 1989) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  958  Thread 0x7fff3affd700 (LWP 1991) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  959  Thread 0x7fff3a7fc700 (LWP 1992) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  960  Thread 0x7fff39ffb700 (LWP 1993) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  961  Thread 0x7fff397fa700 (LWP 1994) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  962  Thread 0x7fff38ff9700 (LWP 1995) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  963  Thread 0x7fff387f8700 (LWP 1996) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  964  Thread 0x7fff37ff7700 (LWP 1997) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  965  Thread 0x7fff377f6700 (LWP 1998) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  966  Thread 0x7fff36ff5700 (LWP 1999) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  967  Thread 0x7fff367f4700 (LWP 2000) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  968  Thread 0x7fff347f0700 (LWP 2001) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  969  Thread 0x7fff33fef700 (LWP 2002) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  970  Thread 0x7fff337ee700 (LWP 2003) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
  971  Thread 0x7fff32fed700 (LWP 2004) "python" 0x00007ffff4f9c6a2 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
  972  Thread 0x7fff997fa700 (LWP 2005) "Qt HTTP thread" 0x00007ffff78ebb5d in poll () at ../sysdeps/unix/syscall-template.S:84
* 973  Thread 0x7fff327ec700 (LWP 2011) "python" 0x00007ffff4f5fa5b in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) WARNING:SearchCommunity:message from {192.168.1.154:7759 80.229.24.107:50383} cannot be found in the request cache, skipping it
WARNING:TunnelLogger:Received message for unknown circuit ID: 3439718530
WARNING:TunnelLogger:Received message for unknown circuit ID: 3594152572
WARNING:TunnelLogger:Received message for unknown circuit ID: 1887997779
bt
#0  0x00007ffff4f5fa5b in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff4f5fbcf in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4f9c6a2 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4f56ab3 in g_main_context_new () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff62da329 in QEventDispatcherGlibPrivate::QEventDispatcherGlibPrivate(_GMainContext*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff62da401 in QEventDispatcherGlib::QEventDispatcherGlib(QObject*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff60a28d0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff60a3838 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff7bc16ba in start_thread (arg=0x7fff327ec700) at pthread_create.c:333
#9  0x00007ffff78f782d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) WARNING:SearchCommunity:message from <Candidate 218.215.96.180:16866> cannot be found in the request cache, skipping it
WARNING:SearchCommunity:message from {211.186.25.17:7759} cannot be found in the request cache, skipping it
```

**Comment by synctext** [comment]
hmm:
```
/Downloads>ps -eLf | grep -i tribler | wc -l
84

Downloads>ps -eLf | grep -i tri
pouwelse   721   702   721  0    1 15:48 pts/20   00:00:01 gdb -ex r --args python run_tribler.py
pouwelse   723   721   723  0   62 15:48 pts/20   00:00:36 /usr/bin/python run_tribler.py
pouwelse   723   721   730  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   731  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   732  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   733  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   738  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   741  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   743  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   747  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   764  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   768  0   62 15:48 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   944  0   62 15:51 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   945  0   62 15:51 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   946  0   62 15:51 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   948  0   62 15:51 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   949  0   62 15:51 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   950  0   62 15:51 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   951  0   62 15:51 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721   952  0   62 15:51 pts/20   00:00:00 /usr/bin/python run_tribler.py
pouwelse   723   721  1932  2   62 16:03 pts/20   00:03:03 /usr/bin/python run_tribler.py
[snip]
```

**Comment by synctext** [comment]
thread created by tracker checking?
```
XPS13:/tmp>ps -eLf | grep tribler | wc -l
118
XPS13:/tmp>ps -eLf | grep tribler | wc -l
36
```

**Comment by synctext** [comment]
```
ps -eLf | grep -i trib | wc -l
29
```

Much less threads now! Started the new 7.0 RC2 and hopefully the Freeze issue is fixed.
