### ISSUE TITLE
get_uniformed_tracker_url: ValueError, invalid literal for int() with base 10: '80 udp'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2860]
While running 7 .0 Beta on Ubuntu (part of the 26MByte log file).

```
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 345, in addExternalTorrentNoDef
    torrent_id = self._addTorrentToDB(torrentdef, extra_info)
  File "/usr/share/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 431, in _addTorrentToDB
    self._addTorrentTracker(torrent_id, torrentdef, extra_info)
  File "/usr/share/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 485, in _addTorrentTracker
    tracker_url = get_uniformed_tracker_url(announce)
  File "/usr/share/tribler/Tribler/Core/Utilities/tracker_utils.py", line 47, in get_uniformed_tracker_url
    if not url.port:
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '80 udp'
```

**Comment by vandenheuvel** [comment]
Please assign this to me.
