### ISSUE TITLE
TrustChain error: assert len(requester[1].public_key) == PK_LENGTH

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2861]
```
ERROR:StandaloneEndpoint:Ignored assertion error in Dispersy
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/dispersy/endpoint.py", line 253, in dispersythread_data_came_in
    u"standalone_ep")
  File "/usr/share/tribler/Tribler/dispersy/dispersy.py", line 1489, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp, source)
  File "/usr/share/tribler/Tribler/dispersy/community.py", line 2022, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/usr/share/tribler/Tribler/dispersy/community.py", line 2092, in _on_batch_cache
    self.on_messages(messages)
  File "/usr/share/tribler/Tribler/dispersy/community.py", line 2209, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/usr/share/tribler/Tribler/dispersy/dispersy.py", line 1725, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/usr/share/tribler/Tribler/dispersy/dispersy.py", line 1750, in _update
    messages[0].handle_callback(messages)
  File "/usr/share/tribler/Tribler/dispersy/community.py", line 2366, in on_signature_request
    new_submsg = message.payload.message.authentication.allow_signature_func(message.payload.message)
  File "/usr/share/tribler/Tribler/community/multichain/community.py", line 217, in allow_signature_request
    self.persist_signature_response(message)
  File "/usr/share/tribler/Tribler/community/multichain/community.py", line 256, in persist_signature_response
    block = DatabaseBlock.from_signature_response_message(message)
  File "/usr/share/tribler/Tribler/community/multichain/database.py", line 390, in from_signature_response_message
    responder[0], sha256(encode_block(payload, requester, responder)).digest(),
  File "/usr/share/tribler/Tribler/community/multichain/conversion.py", line 188, in encode_block
    assert len(requester[1].public_key) == PK_LENGTH
AssertionError
```

**Comment by devos50** [comment]
I'm not really sure what went wrong here. Apparently, the public key of a requester has an invalid format and this is most probably a bug. As indicated by the error message, we ignored this error so the signature response has never been processed. I will postpone this issue to a later milestone.

**Comment by devos50** [comment]
Since we moved TrustChain to IPv8 and made a significant amount of improvements there, I'm pretty sure this issue is resolved.
