### ISSUE TITLE
Tribler unable to start on Windows with no-ASCI profile name

### ISSUE THREAD

**Issue by PetrNemecek** [Tribler/tribler#2862]
##### Tribler version/branch+revision: #####
Tribler_7.0.0-beta_x64
##### Operating system and version: #####
Windows 10 x64

##### Actual behavior: #####
Crashes during startup

##### Steps to reproduce the behavior: #####
my real OS variable:
USERPROFILE: C:\Users\Petr Němeček

tribler sees it like this:
USERPROFILE: C:\Users\Petr N�me�ek

##### Relevant log file output: #####
`Traceback (most recent call last):
  File "TriblerGUI\core_manager.py", line 128, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent
    
  File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback
    
  File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
    
  File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks
    
--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring
    
  File "TriblerGUI\core_manager.py", line 60, in start_tribler
    
  File "Tribler\dispersy\util.py", line 46, in helper
    
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
    
  File "Tribler\Core\Session.py", line 558, in start
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 112, in register
    
  File "Tribler\Core\leveldbstore.py", line 88, in __init__
    
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u011b' in position 15: ordinal not in range(128)`

**Comment by vandenheuvel** [comment]
This is what [these methods](https://github.com/Tribler/tribler/blob/devel/Tribler/Main/hacks.py#L24) are supposed to fix.

**Comment by devos50** [comment]
@vandenheuvel the path to leveldb is not given by an environment variable. The problem here is that our leveldb library for Windows does not support unicode paths since it's not compiled for unicode. Supporting unicode requires some additional flags when compiling or some code modification but this is probably not easy. I will postpone this past Tribler 7.
