### ISSUE TITLE
Bad handling of invalid BitTorrent files.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2873]
##### Tribler version/branch+revision: #####

devel d12a8515b4f3fd976030b2bb04e2796dd5788499

##### Steps to reproduce the behavior: #####

1. Start Tribler core
2. Open Tribler GUI
3. Press "+" -> "Import torrent from file"
4. Specify a text file that is not a correct BitTorrent file

##### Expected behavior: #####

Proper closable error message about invalid file

##### Actual behavior: #####

A very wide modal box with inaccessible buttions:

![10](https://cloud.githubusercontent.com/assets/173219/24073699/9a09a48e-0c0c-11e7-8a3c-9acd5f761942.png)

##### Relevant log file output: #####

Core:

```
ERROR   1489852304.49    rest_manager:53    [Failure instance: Traceback: <class 'Boost.Python.ArgumentError'>: Python argument types in
    libtorrent.bdecode(NoneType)
did not match C++ signature:
    bdecode(bytes)
/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py:571:dataReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1692:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1781:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:768:requestReceived
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:183:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:234:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/home/tribler/tribler/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py:85:render_GET
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py", line 85, in render_GET
    metainfo_deferred.callback(bdecode(fix_torrent(filename)))
ArgumentError: Python argument types in
    libtorrent.bdecode(NoneType)
did not match C++ signature:
    bdecode(bytes)
```

**Comment by devos50** [comment]
That error is not very user-friendly instead. I've captured the exact error and returned a human-readable string. Will be included in my next fixes PR. Thanks for the report!
