### ISSUE TITLE
sqlite3.OperationalError: no such column: total_up

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2916]
##### Tribler version/branch+revision: #####

50c5fa119d51784d94ad5b045970336623765b42 devel

Tribler's profile persist though chain of devel updates

##### Operating system and version: #####

Linux

##### Steps #####

Browse and sort downloads

##### Relevant log file output: #####

```
Traceback (most recent call last):
  File "/home/tribler/tribler/TriblerGUI/event_request_manager.py", line 92, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 390, in startReactor
    self.config, oldstdout, oldstderr, self.profiler, reactor)
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 311, in runReactorWithLogging
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/tribler/tribler/Tribler/community/multichain/community.py", line 157, in sign_block
    block = MultiChainBlock.create(self.persistence, self.my_member.public_key, linked)
  File "/home/tribler/tribler/Tribler/community/multichain/block.py", line 289, in create
    blk = database.get_latest(public_key)
  File "/home/tribler/tribler/Tribler/community/multichain/database.py", line 109, in get_latest
    u"WHERE public_key = ?)", (buffer(public_key), buffer(public_key)))
  File "/home/tribler/tribler/Tribler/community/multichain/database.py", line 78, in _get
    db_result = self.execute(_header + query, params).fetchone()
  File "/home/tribler/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/tribler/tribler/Tribler/dispersy/database.py", line 308, in execute
    result = self._cursor.execute(statement, bindings)
sqlite3.OperationalError: no such column: total_up
```

**Comment by devos50** [comment]
@qstokkink could you take a look at this one? Probably due to the merge of true halves.

**Comment by qstokkink** [comment]
Every `_get()` includes a `_header` statement which selects all of the columns in `_columns`: https://github.com/Tribler/tribler/blob/devel/Tribler/community/multichain/database.py#L44. This contains `total_up`. To fix this we need to update the `_columns` to the new structure.
