### ISSUE TITLE
Tribler Fails to launch

### ISSUE THREAD

**Issue by inpothet** [Tribler/tribler#2923]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.0.0 R1

##### Operating system and version: #####
Windows 10 Version 1703

##### Expected behavior: #####
Tribler starting and UI loads

##### Actual behavior: #####
Tribler not starting and infinite cogs spinning
##### Steps to reproduce the behavior: #####
Start Tribler on latest windows 10
##### Relevant log file output: #####
    Qt: Untested Windows version 10.0 detected!
    Warning: option --plugin-path no longer exists.
    Warning: option --plugin-path no longer exists.
    Qt: Untested Windows version 10.0 detected!
    Unhandled Error
    Traceback (most recent call last):
    File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent

    File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback

    File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks

    File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks

    --- <exception caught here> ---
    File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring

    File "TriblerGUI\core_manager.py", line 60, in start_tribler

    File "Tribler\dispersy\util.py", line 46, in helper

    File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread

    File "Tribler\Core\Session.py", line 550, in start

    File "Tribler\Core\Modules\restapi\rest_manager.py", line 33, in start

    File "lib\site-packages\twisted\internet\posixbase.py", line 478, in listenTCP

    File "lib\site-packages\twisted\internet\tcp.py", line 983, in startListening

    twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:8085: [Errno 10048] Only one 
    usage of each socket address (protocol/network address/port) is normally permitted.

    QIODevice::write: device not open

**Comment by devos50** [comment]
@inpothet thank you for your report. Do you have something running on port `8085` by chance?

**Comment by qstokkink** [comment]
Judging by the double `Qt: Untested Windows version 10.0 detected!`, the lack of Session singleton error and the port-in-use stacktrace, this seems like the multiprocessing library didn't detect the forked process as being the child and is running the "main" process' code on the child. I hope my assessment is wrong, as this would be a bitch to fix.

**Comment by inpothet** [comment]
@devos50 
Okay found the culprit and kicked it out now
@qstokkink So you are using the anniversary update, I'm on the creator update

**Comment by qstokkink** [comment]
In that case, this is related to #2807: it was decided that port configuration will be implemented in Tribler v7.1.
