### ISSUE TITLE
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 17: ordinal not in range(128)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2946]
Tribler crash, while using windows 8 64-bit

[Reported on our forum in multiple posts](https://forum.tribler.org/users/Mosomi)
```python
Traceback (most recent call last):
File "TriblerGUI\core_manager.py", line 128, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent
File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback
File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks
--- ---
File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring
File "TriblerGUI\core_manager.py", line 60, in start_tribler
File "Tribler\dispersy\util.py", line 46, in helper
File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
File "Tribler\Core\Session.py", line 558, in start
File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 112, in register
File "Tribler\Core\leveldbstore.py", line 88, in init
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 17: ordinal not in range(128)
```
EDIT: completely forgot to mention tribler crashing and then gives above error (including Tribler 7 release candidate 1)

**Comment by qstokkink** [comment]
Related to #2862 . At some point we really need to make an ASCII local soft link workaround on Windows. It's not pretty, but it'll work.

**Comment by devos50** [comment]
@qstokkink @synctext This issue is very hard to to fix right now. It requires us to recompile the leveldb library for Windows with support for unicode (which was already cumbersome to compile). See this related issue: https://github.com/happynear/py-leveldb-windows/issues/1.

If we really want it for Tribler 7, I will give it a try but it's quite hard to give an estimate how long it will take since it requires me to rewrite some of the leveldb C++ code.

**Comment by qstokkink** [comment]
@devos50 If you think it's too much for 7.0: we could also take the quick and dirty workaround for now and recompile later for 7.1 👍

**Comment by devos50** [comment]
@qstokkink ah I didn't see the workaround on that page. I think that would be the best solution for now. Let's first write a unit test that captures this bug and then use the encoding workaround to fix the bug.

**Comment by synctext** [comment]
OK. another_hack.py it is then...

**Comment by devos50** [comment]
@qstokkink it turns out that this issue can be fixed if we change to plyvel on Windows (which we can bundle) and create the database like:

```
import plyvel
db = plyvel.DB("our_unicode_string".decode('windows-1252'), create_if_missing=True)
```

This seems to work on the windows machine I've tested it on 👍

**Comment by qstokkink** [comment]
@devos50 Nice 👍, I'll close #2949 in favor of that solution.

**Comment by devos50** [comment]
@qstokkink could you please test https://jenkins.tribler.org/job/pers/job/Build-Tribler_Win64_devos50/2/artifact/tribler/dist/Tribler_7.0.0-plyvel_x64.exe to see whether everything still works as expected (and that our unicode issue is fixed of course)? I've tested it on a fresh Windows 10 machine where I've added unicode to the path of the leveldb store. This seems to work :)

**Comment by qstokkink** [comment]
@devos50 Sure, give me a minute though, I don't have the plyvel backend on my machine.

**Comment by devos50** [comment]
@qstokkink you don't need to, it's included in the .exe bundle.

**Comment by qstokkink** [comment]
@devos50 I'm getting this when running the .exe:
![popup](https://cloud.githubusercontent.com/assets/3630389/26542915/0ad19bf4-445c-11e7-8a91-9a0125cba7bc.png)

**Comment by devos50** [comment]
@qstokkink That's weird. What if you run it as administrator?

**Comment by qstokkink** [comment]
@devos50 same thing

**Comment by devos50** [comment]
@qstokkink maybe the download is corrupt?

**Comment by qstokkink** [comment]
```python

Traceback (most recent call last):
  File "TriblerGUI\core_manager.py", line 133, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent
    
  File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback
    
  File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
    
  File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks
    
--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring
    
  File "TriblerGUI\core_manager.py", line 60, in start_tribler
    
  File "Tribler\dispersy\util.py", line 46, in helper
    
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
    
  File "Tribler\Core\Session.py", line 558, in start
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 178, in register
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 255, in init
    
  File "Tribler\dispersy\util.py", line 46, in helper
    
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
    
  File "Tribler\dispersy\dispersy.py", line 1618, in start
    
  File "Tribler\dispersy\database.py", line 113, in open
    
  File "Tribler\dispersy\database.py", line 141, in _initial_statements
    
sqlite3.DatabaseError: file is encrypted or is not a database
```

**Comment by devos50** [comment]
@qstokkink that's not related to leveldb but this seems to be an issue of the sqlite3 backend. Do you get the same if you use the RC2 .exe?

**Comment by qstokkink** [comment]
@devos50 No on rc2 I get:

```python
Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent

  File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback

  File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks

  File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks

--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring

  File "TriblerGUI\core_manager.py", line 60, in start_tribler

  File "Tribler\dispersy\util.py", line 46, in helper

  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread

  File "Tribler\Core\Session.py", line 558, in start

  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 112, in register

  File "Tribler\Core\leveldbstore.py", line 65, in __init__

exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u6f22' in position 3: ordinal not in range(128)

ERROR:root:Traceback (most recent call last):
  File "TriblerGUI\core_manager.py", line 133, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent

  File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback

  File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks

  File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks

--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring

  File "TriblerGUI\core_manager.py", line 60, in start_tribler

  File "Tribler\dispersy\util.py", line 46, in helper

  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread

  File "Tribler\Core\Session.py", line 558, in start

  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 112, in register

  File "Tribler\Core\leveldbstore.py", line 65, in __init__

exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u6f22' in position 3: ordinal not in range(128)
```

**Comment by devos50** [comment]
@qstokkink did you only change the leveldb path in the `libtribler.conf` file or did you change the complete state directory?

**Comment by qstokkink** [comment]
@devos50 I set:

```
[metadata]
store_dir = C:\漢\collected_metadata
[torrent_store]
dir = C:\漢\collected_torrents
```

The rest is on default. Tribler is running from a non-unicode path. SQLite is in `C:\Users\goqs\AppData\Roaming\.Tribler\sqlite`.

**Comment by devos50** [comment]
@qstokkink I have no idea why this happens. Does it also happen if you (temporarily) remove the Tribler state directory?

**Comment by devos50** [comment]
@qstokkink also, are you able to open the database with a sqlite browser?

**Comment by qstokkink** [comment]
@devos50 If i remove the state dir it works (ofc. this places the leveldb storage on an ASCII path in my case). Also, yes I can read the (old) database in a browser.

**Comment by devos50** [comment]
@qstokkink what if you run Tribler from source (my `various_fixes_tribler7` branch)?

**Comment by qstokkink** [comment]
@devos50 whoa wait, once I changed the same settings as before it suddenly works with the new `.Tribler` dir..

**Comment by devos50** [comment]
@qstokkink you mean with the old `.Tribler` directory right? Maybe there was some hidden character in a path where it doesn't belong?

**Comment by qstokkink** [comment]
@devos50 I'm not sure, it is reproducible with the old folder though. As for a fresh check though, I can confirm this works.

**Comment by devos50** [comment]
@qstokkink and if you run Tribler from source?

**Comment by qstokkink** [comment]
@devos50 I'll check. For now the only difference between the two folders (disregarding the database contents) seems to be a `dispersy.db-shm` and a `dispersy.db-wal` file in the `sqlite` folder.
