### ISSUE TITLE
Opening fails if there are pre-existing ~/.Tribler files

### ISSUE THREAD

**Issue by sum01** [Tribler/tribler#2963]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
`v7.0.0-rc2`
##### Operating system and version: #####
`4.11.2-1-ARCH` Linux
##### Expected behavior: #####
Open Tribler and have it run as normal.
##### Actual behavior: #####
It will only open if there are no `~/.Tribler` files (I haven't tested deleting certain files, just the whole folder), otherwise it immediately fails and gives me an error log. Although it does work as expected if you never close it after the first time opening it.
##### Steps to reproduce the behavior: #####
Open Tribler, close it, then open it again (assuming fresh install). After the first open it continuously gives the same error.
##### Relevant log file output: #####
```
Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 133, in on_received_state
    raise RuntimeError(state['last_exception'])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 428, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
    callable(*args, **kwargs)
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 60, in start_tribler
    session.start()
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Core/Session.py", line 558, in start
    startup_deferred = self.lm.register(self, self.sesslock)
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 178, in register
    self.init()
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 298, in init
    self.ltmgr.initialize()
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 70, in initialize
    self.get_session().start_upnp()
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 193, in get_session
    self.ltsessions[hops] = self.create_session(hops)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 157, in create_session
    self.set_proxy_settings(ltsession, *proxy_settings)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 202, in set_proxy_settings
    proxy_settings.port = int(server[1])
exceptions.TypeError: int() argument must be a string or a number, not 'NoneType'

```

**Comment by synctext** [comment]
@sum01 Do you know which prior version of Tribler created that .Tribler directory?

```proxy_settings.port = int(server[1])``` the proxy setting conversion seems to go bad.

**Comment by sum01** [comment]
@synctext That would be v7.0.0-alpha3 I guess, although I've since wiped the `~/.Tribler` folder and get the same result after one relaunch (so it works once after wiping the folder).

**Comment by tetsuo55** [comment]
i have the same error
`Qt: Untested Windows version 10.0 detected!
Warning: option --plugin-path no longer exists.
Warning: option --plugin-path no longer exists.
QSslSocket: cannot resolve TLSv1_1_client_method
QSslSocket: cannot resolve TLSv1_2_client_method
QSslSocket: cannot resolve TLSv1_1_server_method
QSslSocket: cannot resolve TLSv1_2_server_method
Qt: Untested Windows version 10.0 detected!
Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent
  File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback
  File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
  File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks
--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring
  File "TriblerGUI\core_manager.py", line 60, in start_tribler
  File "Tribler\dispersy\util.py", line 46, in helper
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
  File "Tribler\Core\Session.py", line 558, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 178, in register
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 298, in init
  File "Tribler\dispersy\util.py", line 46, in helper
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 70, in initialize
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 193, in get_session
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 157, in create_session
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 202, in set_proxy_settings
exceptions.TypeError: int() argument must be a string or a number, not 'NoneType'
ERROR:root:Traceback (most recent call last):
  File "TriblerGUI\core_manager.py", line 133, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent
  File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback
  File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
  File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks
--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring
  File "TriblerGUI\core_manager.py", line 60, in start_tribler
  File "Tribler\dispersy\util.py", line 46, in helper
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
  File "Tribler\Core\Session.py", line 558, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 178, in register
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 298, in init
  File "Tribler\dispersy\util.py", line 46, in helper
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 70, in initialize
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 193, in get_session
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 157, in create_session
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 202, in set_proxy_settings
exceptions.TypeError: int() argument must be a string or a number, not 'NoneType'`

The in my case the folder was created by 
v7.0.0-rc2

My last action was removing the only finished torrent in the download queue.

**Comment by devos50** [comment]
Ok, this was due to a mistake from my side. I've fixed it and I will open a PR soon.
