### ISSUE TITLE
Tribler unstartable after crash

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2970]
My Tribler crashed today and upon restarting I got (every time):

```bash

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 417, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 430, in _continueFiring
    callable(*args, **kwargs)
  File "/home/quinten/tribler/tribler/TriblerGUI/core_manager.py", line 53, in start_tribler
    process_checker = ProcessChecker()
  File "/home/quinten/tribler/tribler/Tribler/Core/Modules/process_checker.py", line 29, in __init__
    elif file_pid != os.getpid() and not ProcessChecker.is_pid_running(int(file_pid)):
exceptions.ValueError: invalid literal for int() with base 10: ''

ERROR:root:No json object could be decoded from data: 
ERROR:root:No json object could be decoded from data: 
ERROR:root:No json object could be decoded from data: 
ERROR:root:No json object could be decoded from data: 
ERROR:root:No json object could be decoded from data: 
ERROR:root:No json object could be decoded from data: 
   ... json error repeats infinitely
```

Once I removed `triblerd.lock` from the state dir, Tribler could start again.

**Comment by devos50** [comment]
Interesting, the write to the `pid` file could have gone wrong. next time you get this error, please post the content of `triblerd.lock` since it does not contain an integer obviously.

To fix this error, we should catch the `ValueError`, remove the current lock file and attempt to run Tribler.
