### ISSUE TITLE
Trust Page requiring wrong dataformat

### ISSUE THREAD

**Issue by MaxVanDeursen** [Tribler/tribler#2992]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
devel b5ac1be98340c1f2df85dd2bba188cf0e3f1032e
##### Operating system and version: #####
Ubuntu 17.04
##### Expected behavior: #####
When I open the TrustPage after I have collected some blocks, it shows me a graph with the correct information according to the blocks.
##### Actual behavior: #####
When I open the TrustPage, Tribler crashes with `ValueError: time data '323031372d30362d31332031303a34303a3030' does not match format '%Y-%m-%d %H:%M:%S'`.

##### Steps to reproduce the behavior: #####
1. Get a Block inside the database.
2. Open the Trust Page.

##### Relevant log file output: #####
`ERROR:root:Traceback (most recent call last):
  File "/home/max/git/tribler/TriblerGUI/widgets/trustpagegraph.py", line 109, in received_multichain_blocks
    self.plot_absolute_values()
  File "/home/max/git/tribler/TriblerGUI/widgets/trustpagegraph.py", line 119, in plot_absolute_values
    plot_data[1].append(datetime.datetime.strptime(block["insert_time"], "%Y-%m-%d %H:%M:%S"))
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '323031372d30362d31332031303a34303a3030' does not match format '%Y-%m-%d %H:%M:%S'`

Please note that this most probably has something to do with the timestamp of SQLite3, for which DEFAULT CURRENT_TIMESTAMP is used. As far as I have read, this is [dependent on the sqlite3_step()](https://sqlite.org/lang_datefunc.html) call, which in it's turn is [VSF dependent](https://sqlite.org/c3ref/step.html)

**Comment by MaxVanDeursen** [comment]
@devos50 Can you assign me please? It's a quick fix which is much easier than expected. It's simply decoding it from HEX...
