### ISSUE TITLE
Change Setting and restart will crash Tribler (need to remove all Tribler setting file to recover)

### ISSUE THREAD

**Issue by Halbon** [Tribler/tribler#2994]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
RC2
##### Operating system and version: #####
Windows 10 Home 1703
##### Expected behavior: #####
Shut down Tribler and re-start it would resume a normal operation.
##### Actual behavior: #####
Shut down Tribler and re-start will end up in the application crash, no longer continue.
##### Steps to reproduce the behavior: #####
Go to Settings.
change Anonymity...Proxy Downloading...to the middle (2 hops).
Save.
Close Tribler.
Restart Tribler.

I had seen crash like this after Windows update or anything that reboots my PC.
I thought Tribler closed immaturely, which corrupted the setting files.
However, it was simpler issue.
I think i can go on and use it UNLESS I restart Tribler.
I lose all my torrents every time.

##### Relevant log file output: #####
Traceback (most recent call last):
  File "TriblerGUI\core_manager.py", line 133, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent
    
  File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback
    
  File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
    
  File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks
    
--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring
    
  File "TriblerGUI\core_manager.py", line 60, in start_tribler
    
  File "Tribler\dispersy\util.py", line 46, in helper
    
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
    
  File "Tribler\Core\Session.py", line 558, in start
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 178, in register
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 298, in init
    
  File "Tribler\dispersy\util.py", line 46, in helper
    
  File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread
    
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 70, in initialize
    
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 193, in get_session
    
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 157, in create_session
    
  File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 202, in set_proxy_settings
    
exceptions.TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by devos50** [comment]
This was my mistake (messed up something with the settings dictionary) but it should be fixed in the next RC!

**Comment by Halbon** [comment]
@devos50 
Thanks! that would be great because I cannot try to download any minimum seed torrent because every time I shutdown, I have to re-import...

**Comment by devos50** [comment]
I've fixed this one already in https://github.com/Tribler/tribler/commit/f1efdecffe5ac317213a808df6584a57e5109253

**Comment by Halbon** [comment]
Is it possible to get RC3 soon? I can't really test with this bug and I
can't recommend others to use it either (in same Windows environment).
Thanks!

**Comment by padhtalikhtanahi** [comment]
Based on  [f1efdec](https://github.com/Tribler/tribler/commit/f1efdecffe5ac317213a808df6584a57e5109253) mentioned by devos50. Those who are having this issue and using GNU/Linux, can fix it by:

go to "/usr/share/tribler/Tribler/Core/Libtorrent/"

edit and save 'LibtorrentMgr.py' - line 200 from:
`if server:`
to:
` if server and server[0] and server[1]:`

Than recompile the file (delete 'LibtorrentMgr.pyc' first). In terminal:
` python -m py_compile LibtorrentMgr.py`

Hope this helps!
