### ISSUE TITLE
Missing dependency on Linux

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3023]
On latest devel, 650367121ca451f722873b148df52bf71a959d42.

When starting Tribler using `tribler.sh` an `ImportError` is raised from `TriblerGUI/core_manager.py`: `ImportError: No module named keyring`.

**Comment by sum01** [comment]
Having the same issue on Linux `4.11.6-3-ARCH`
```
Traceback (most recent call last):
  File "run_tribler.py", line 9, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/usr/share/tribler/TriblerGUI/tribler_window.py", line 18, in <module>
    from TriblerGUI.core_manager import CoreManager
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 4, in <module>
    import keyring
ImportError: No module named keyring
```

**Comment by sum01** [comment]
Installed `python2-keyring` and `python2-keyrings-alt`, but now it doesn't find `dispersy.taskmanager`
```
Traceback (most recent call last):
  File "run_tribler.py", line 9, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/usr/share/tribler/TriblerGUI/tribler_window.py", line 18, in <module>
    from TriblerGUI.core_manager import CoreManager
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 10, in <module>
    from Tribler.community.market.wallet.btc_wallet import BitcoinWallet
  File "/usr/share/tribler/Tribler/community/market/wallet/btc_wallet.py", line 13, in <module>
    from Tribler.community.market.wallet.wallet import InsufficientFunds, Wallet
  File "/usr/share/tribler/Tribler/community/market/wallet/wallet.py", line 8, in <module>
    from Tribler.dispersy.taskmanager import TaskManager
ImportError: No module named dispersy.taskmanager
```
