### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_peer_info'

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3039]
- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
nothing to commit, working directory clean

##### Operating system and version: #####
Ubuntu 16.04

Checking my log files for errors after I received a couple of them the last couple of days. This error I encountered multiple times. I am runing tribler next in a docker container which I connect to through vnc/novnc. I was looking at [this](http://urlgone.com/67a007/) topic when this error happened repeatedly.

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/tribler/TriblerGUI/core_manager.py", line 63, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/tribler/Tribler/dispersy/requestcache.py", line 213, in _on_timeout
    cache.on_timeout()
  File "/opt/tribler/Tribler/community/tunnel/tunnel_community.py", line 61, in on_timeout
    self.community.remove_circuit(self.number, reason)
  File "/opt/tribler/Tribler/community/tunnel/hidden_community.py", line 203, in remove_circuit
    super(HiddenTunnelCommunity, self).remove_circuit(circuit_id, additional_info, destroy)
  File "/opt/tribler/Tribler/community/tunnel/tunnel_community.py", line 624, in remove_circuit
    for d, s in ltmgr.torrents.values() if s == ltmgr.get_session(d.get_hops())}
  File "/opt/tribler/Tribler/community/tunnel/tunnel_community.py", line 624, in <dictcomp>
    for d, s in ltmgr.torrents.values() if s == ltmgr.get_session(d.get_hops())}
exceptions.AttributeError: 'NoneType' object has no attribute 'get_peer_info'
```

**Comment by pimlie** [comment]
Happened another time, but with a different trace. This time I was removing finished torrents:

```
Traceback (most recent call last):
  File "/opt/tribler/TriblerGUI/event_request_manager.py", line 99, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get_peer_info'
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:798:runUntilCurrent
/opt/tribler/Tribler/dispersy/util.py:230:_callFromThread
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1274:unwindGenerator
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/opt/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py:581:sesscb_states_callback
/opt/tribler/Tribler/dispersy/util.py:37:helper
/opt/tribler/Tribler/community/tunnel/hidden_community.py:283:monitor_downloads
/opt/tribler/Tribler/community/tunnel/hidden_community.py:203:remove_circuit
/opt/tribler/Tribler/community/tunnel/tunnel_community.py:624:remove_circuit
/opt/tribler/Tribler/community/tunnel/tunnel_community.py:624:<dictcomp>
]
```
