### ISSUE TITLE
TypeError: Non-base32 digit found

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3042]
- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
nothing to commit, working directory clean

##### Operating system and version: #####
Ubuntu 16.04

Another one I just encoutered, happened with [this](http://mgnet.me/cwt09E6) torrent. Btw, the error message is directly displayed in the 'Download torrent' popup where normally the files within the torrent are displayed. The error message is very long and is not broken on to a new line, so the popup is veeeerrrryyy width and actually goes off screen.

```
ERROR:RESTRequest:[Failure instance: Traceback: <type 'exceptions.TypeError'>: Non-base32 digit found
/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py:571:dataReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1657:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1736:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:762:requestReceived
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:183:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:234:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/opt/tribler/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py:102:render_GET
/opt/tribler/Tribler/Core/Utilities/utilities.py:249:parse_magnetlink
/usr/lib/python2.7/base64.py:229:b32decode
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/opt/tribler/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py", line 102, in render_GET
    self.infohash = parse_magnetlink(uri)[1]
  File "/opt/tribler/Tribler/Core/Utilities/utilities.py", line 249, in parse_magnetlink
    xt = b32decode(encoded_infohash)
  File "/usr/lib/python2.7/base64.py", line 229, in b32decode
    raise TypeError('Non-base32 digit found')
TypeError: Non-base32 digit found
```

**Comment by qstokkink** [comment]
This seems to be an uppercase issue:

```python
>>> b32decode('apctqfwnowubxzoidazgaj2ba6fs6juc'.upper())
"\x03\xc58\x16\xcdu\xa8\x1b\xe5\xc8\x182`'A\x07\x8b/&\x82"
>>> b32decode('apctqfwnowubxzoidazgaj2ba6fs6juc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\base64.py", line 229, in b32decode
    raise TypeError('Non-base32 digit found')
TypeError: Non-base32 digit found
```
