### ISSUE TITLE
AttributeError: 'pmem' object has no attribute 'uss'

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#3092]
##### Tribler version/branch+revision: #####

devel 1be8574c7758395b0a3101100dd58e8e709090c6

##### Operating system and version: #####

Linux Debian mostly stretch

##### Steps to reproduce the behavior: #####

1. Start Tribler core after some hiarus, without access to X DISPLAY to prevent messages about keychain showing up.

##### Expected behavior: #####

No critical log messages gets printed

#### Actual ####

Error shows up. Then Tribler seems to be working.

##### Relevant log file output: #####

```
2017-09-13T23:42:41+0300 [-] Tribler started
2017-09-13T23:42:59+0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2017-09-13T23:42:59+0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1199, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1208, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 828, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/tribler/tribler/Tribler/Core/Modules/resource_monitor.py", line 48, in check_resources
	    self.memory_data.append((time_seconds, self.process.memory_full_info().uss))
	exceptions.AttributeError: 'pmem' object has no attribute 'uss'
```

**Comment by devos50** [comment]
This is fixed by the next `next-to-devel` update.
