### ISSUE TITLE
OperationalError: no such table: blocks

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#3093]
##### Tribler version/branch+revision: #####

devel 1be8574c7758395b0a3101100dd58e8e709090c6

##### Actual behavior: #####

Tribler GUI exited while being on home page

##### Relevant log file output: #####

```
ERROR   1505337571.00        dispersy:1245  exception during handle_callback for dispersy-introduction-request
Traceback (most recent call last):
  File "/home/tribler/tribler/Tribler/dispersy/dispersy.py", line 1240, in _update
    messages[0].handle_callback(messages)
  File "/home/tribler/tribler/Tribler/dispersy/community.py", line 2518, in on_introduction_request
    introduced = self.dispersy_get_introduce_candidate(candidate)
  File "/home/tribler/tribler/Tribler/community/trustchain/community.py", line 458, in dispersy_get_introduce_candidate
    total_trust = sum([self.get_trust(candidate.get_member()) for candidate in eligible])
  File "/home/tribler/tribler/Tribler/community/triblerchain/community.py", line 211, in get_trust
    block = self.persistence.get_latest(member.public_key)
  File "/home/tribler/tribler/Tribler/community/trustchain/database.py", line 76, in get_latest
    u"WHERE public_key = ?)", (buffer(public_key), buffer(public_key)))
  File "/home/tribler/tribler/Tribler/community/trustchain/database.py", line 45, in _get
    db_result = self.execute(self.get_sql_header() + query, params).fetchone()
  File "/home/tribler/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/tribler/tribler/Tribler/dispersy/database.py", line 308, in execute
    result = self._cursor.execute(statement, bindings)
OperationalError: no such table: blocks
```
```

**Comment by vi** [comment]
Also happens without GUI running. Note that glocal recheck is undergoing (and maybe getting stalled by this).

**Comment by synctext** [comment]
thnx for reporting this and other wonderful bugs. Baffling how you manage to get so much testing done!

Trying to understand how this bug got triggered. This was with a clean megacache/database and a quick close? You have seen this now once, repeats 100% or on rare occasions gets triggered?

**Comment by vi** [comment]
> Baffling how you manage to get so much testing done!

Just occasionally running Tribler from the devel branch and reporting failing things along the way. I rarely do testing for it's own.

----

The backtrace in question keeps on appearin in console.

**Comment by devos50** [comment]
This should be fixed already.
