### ISSUE TITLE
Do send reports arrive

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3095]
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
Indeed it is still a big mess under Windows 10 insider build 16362
##### Tribler version/branch+revision: #####
September 11th build
##### Operating system and version: #####
Windows 10 insider build 16362
##### Steps to reproduce the behavior: #####
Start Tribler en while running it abends and I am able to send a report
##### Relevant log file output: #####
Warning: option --plugin-path no longer exists.
Warning: option --plugin-path no longer exists.
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_alpn_selected
Unhandled Error
Traceback (most recent call last):
  File "lib\multiprocessing\process.py", line 114, in run

  File "TriblerGUI\core_manager.py", line 105, in start_tribler_core

  File "lib\site-packages\twisted\internet\base.py", line 1243, in run

  File "lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop

--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent

  File "Tribler\dispersy\endpoint.py", line 253, in dispersythread_data_came_in

  File "Tribler\dispersy\dispersy.py", line 979, in on_incoming_packets

  File "Tribler\dispersy\community.py", line 2028, in on_incoming_packets

  File "Tribler\dispersy\community.py", line 2085, in _on_batch_cache

  File "Tribler\dispersy\util.py", line 150, in wrapper

  File "Tribler\dispersy\conversion.py", line 1251, in decode_message

  File "Tribler\community\market\conversion.py", line 180, in _decode_decline_match

  File "Tribler\community\market\conversion.py", line 110, in _decode_payload

exceptions.IndexError: tuple index out of range

ERROR:root:Traceback (most recent call last):
  File "TriblerGUI\event_request_manager.py", line 123, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "lib\multiprocessing\process.py", line 114, in run

  File "TriblerGUI\core_manager.py", line 105, in start_tribler_core

  File "lib\site-packages\twisted\internet\base.py", line 1243, in run

  File "lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop

--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent

  File "Tribler\dispersy\endpoint.py", line 253, in dispersythread_data_came_in

  File "Tribler\dispersy\dispersy.py", line 979, in on_incoming_packets

  File "Tribler\dispersy\community.py", line 2028, in on_incoming_packets

  File "Tribler\dispersy\community.py", line 2085, in _on_batch_cache

  File "Tribler\dispersy\util.py", line 150, in wrapper

  File "Tribler\dispersy\conversion.py", line 1251, in decode_message

  File "Tribler\community\market\conversion.py", line 180, in _decode_decline_match

  File "Tribler\community\market\conversion.py", line 110, in _decode_payload

exceptions.IndexError: tuple index out of range

QWindowsWindow::setGeometry: Unable to set geometry 600x470+420+206 on QWidgetWindow/'FormWindow'. Resulting geometry:  600x745+420+206 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 389x469, maximum size: 16777215x16777215).
QWindowsWindow::setGeometry: Unable to set geometry 600x470+420+206 on QWidgetWindow/'FormWindow'. Resulting geometry:  600x745+420+206 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 389x469, maximum size: 16777215x16777215).

**Comment by Nubro01** [comment]
Please let me know if the reports that I send do arrive. These latest build are not very useable!

**Comment by devos50** [comment]
@Nubro01 the reports arrive, however, we are currently focussing on getting the Tribler 7 release very stable. We expect a new release within two weeks.

It appears that you are using our bleeding-edge development builds. They have become a bit unstable due to the addition of a decentralized market which needs to be stabilized. We will focus on that after Tribler 7 has been released. Thank you for your understanding.

(your issue here is actually quite easy to fix and I will do that as soon as I can)
