### ISSUE TITLE
Tribler exception at second startup

### ISSUE THREAD

**Issue by remielowik** [Tribler/tribler#3098]
##### Tribler version/branch+revision: #####
7.0 RC2
##### Operating system and version: #####
Ubuntu 16.10 x64
docker image : dorowu/ubuntu-desktop-lxde-vnc:latest
##### Steps to reproduce the behavior: #####
start docker
install all required packages
install rc2 deb
run tribler, first time it works
set watch folder
quit tribler
reopen tribler and get exception
##### Relevant log file output: #####
Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 133, in on_received_state
    raise RuntimeError(state['last_exception'])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 417, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 430, in _continueFiring
    callable(*args, **kwargs)
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 60, in start_tribler
    session.start()
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Core/Session.py", line 558, in start
    startup_deferred = self.lm.register(self, self.sesslock)
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 178, in register
    self.init()
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 298, in init
    self.ltmgr.initialize()
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/usr/share/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 70, in initialize
    self.get_session().start_upnp()
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 193, in get_session
    self.ltsessions[hops] = self.create_session(hops)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 157, in create_session
    self.set_proxy_settings(ltsession, *proxy_settings)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 202, in set_proxy_settings
    proxy_settings.port = int(server[1])
exceptions.TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by devos50** [comment]
This is a known issue and solved in RC3.
