### ISSUE TITLE
Error in tests on devel

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3111]
Got the following error when running the tests on devel:

```
Tuples differ: (2, ('127.0.0.1', [5, 4, 3, 2,... != (2, ('127.0.0.1', [5, 4, 3, 2,...

First differing element 2:
u'None'
''

- (2, ('127.0.0.1', [5, 4, 3, 2, 1]), u'None')
?                                     - ----

+ (2, ('127.0.0.1', [5, 4, 3, 2, 1]), '')
Stacktrace

Traceback (most recent call last):
  File "c:\python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\test_as_server.py", line 58, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\Core\Upgrade\test_config_upgrade_70_71.py", line 33, in test_read_test_libtribler_conf
    self.assertEqual(result_config.get_anon_proxy_settings(), (2, ("127.0.0.1", [5, 4, 3, 2, 1]), ''))
  File "c:\python27\lib\unittest\case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "c:\python27\lib\unittest\case.py", line 753, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "c:\python27\lib\unittest\case.py", line 724, in assertSequenceEqual
    self.fail(msg)
  File "c:\python27\lib\unittest\case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Tuples differ: (2, ('127.0.0.1', [5, 4, 3, 2,... != (2, ('127.0.0.1', [5, 4, 3, 2,...

First differing element 2:
u'None'
''

- (2, ('127.0.0.1', [5, 4, 3, 2, 1]), u'None')
?                                     - ----

+ (2, ('127.0.0.1', [5, 4, 3, 2, 1]), '')
```

**Comment by qstokkink** [comment]
This is what happens when `unicode(None)` is executed, where this happens I do not know.

**Comment by qstokkink** [comment]
2nd observation: I get the same error when running on Ubuntu, why aren't the Linux tests failing on this?

**Comment by qstokkink** [comment]
I added some print statements to the test. This is weird. I added:

```python
print "Field value:", result_config.config["libtorrent"]["anon_proxy_auth"]
print "get_anon_proxy_settings() value:", result_config.get_anon_proxy_settings()[2]
print "get_anon_proxy_settings():", result_config.get_anon_proxy_settings()
```

The output:
```python
Field value: None
get_anon_proxy_settings() value: None
get_anon_proxy_settings(): (2, ('127.0.0.1', [5, 4, 3, 2, 1]), u'None')
```
