### ISSUE TITLE
ImportError: No module named lib (electrum)

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3114]
Got the following error on Tribler(devel) installation in Debian machine. 
```python
Traceback (most recent call last):
  File "run_tribler.py", line 14, in <module>
	from TriblerGUI.tribler_window import TriblerWindow
  File "/usr/share/tribler/TriblerGUI/tribler_window.py", line 18, in <module>
	from TriblerGUI.core_manager import CoreManager
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 10, in <module>
	from Tribler.community.market.wallet.btc_wallet import BitcoinWallet
  File "/usr/share/tribler/Tribler/community/market/wallet/btc_wallet.py", line 16, in <module>
	imp.load_module('electrum', *imp.find_module('lib'))
ImportError: No module named lib
```

**Comment by qstokkink** [comment]
\* `devel` contains the 7.1 release

**Comment by devos50** [comment]
@xoriole please verify that the electrum submodule has been installed:

```
git submodule init
git submodule update
```

Then it should work.

**Comment by NoNameForMee** [comment]
I just tried installing the latest build of tribler devel (from https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/819/) and got a similar error where the GUI basically stated "No module named lib" so this issue still appears to be present.
