### ISSUE TITLE
keyring InitError: Failed to unlock the collection!

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3126]
I got the endless gears on startup with this error on the terminal on `devel`:

```
Exception in thread tribler-pipe-read:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/quinten/tribler/tribler/TriblerGUI/core_manager.py", line 173, in <lambda>
    pipe_thread = Thread(target=lambda: self.pipe_wait(parent_conn), name="tribler-pipe-read")
  File "/home/quinten/tribler/tribler/TriblerGUI/core_manager.py", line 160, in pipe_wait
    child_conn.send(keyring.get_password('tribler', arg['username']))
  File "/home/quinten/.local/lib/python2.7/site-packages/keyring/core.py", line 41, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/quinten/.local/lib/python2.7/site-packages/keyring/backends/SecretService.py", line 58, in get_password
    collection = self.get_preferred_collection()
  File "/home/quinten/.local/lib/python2.7/site-packages/keyring/backends/SecretService.py", line 52, in get_preferred_collection
    raise InitError("Failed to unlock the collection!")
InitError: Failed to unlock the collection!
```

**Comment by devos50** [comment]
@qstokkink on which OS does this happen?

**Comment by qstokkink** [comment]
@devos50 Oh sorry: this is Ubuntu 16.10 .

**Comment by xoriole** [comment]
@qstokkink Is this bug still present?

**Comment by qstokkink** [comment]
Yes, you can simply click cancel when it asks for your password.
