### ISSUE TITLE
DuplicateTorrentFileError when adding a new torrent

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3139]
When adding a new torrent to my channel I always get a DuplicateTorrentFileError:
```
ERROR   1507298962.87 base_channels_endpoint:34    <class 'Tribler.Core.exceptions.DuplicateTorrentFileError'>: This torrent file already exists in your channel.
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/channels/channels_torrents_endpoint.py", line 133, in render_PUT
    self.session.add_torrent_def_to_channel(channel[0], torrent_def, extra_info, forward=True)
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 788, in add_torrent_def_to_channel
    raise DuplicateTorrentFileError("This torrent file already exists in your channel.")
DuplicateTorrentFileError: <class 'Tribler.Core.exceptions.DuplicateTorrentFileError'>: This torrent file already exists in your channel.
```

**Comment by qstokkink** [comment]
This seems to be fixed in the latest `next`.
