### ISSUE TITLE
Error opening Tribler 6.5.2 in Windows 10 pro, ver 1709

### ISSUE THREAD

**Issue by Yeoman742** [Tribler/tribler#3177]
##### Operating system and version: #####

Traceback (most recent call last):
  File "tribler_exe.py", line 127, in <module>
  File "Tribler\Main\tribler.pyo", line 82, in __main__
    
  File "Tribler\Main\tribler.pyo", line 64, in run
    
  File "Tribler\Main\tribler_main.pyo", line 52, in <module>
    
  File "wx\__init__.pyo", line 45, in <module>
    
  File "wx\_core.pyo", line 4, in <module>
    
  File "wx\_core_.pyo", line 12, in <module>
    
  File "wx\_core_.pyo", line 10, in __load
    
ImportError: DLL load failed: The operating system cannot run %1.

Program will not open!

**Comment by devos50** [comment]
We are about to release Tribler 7 so please try to run this version instead. You can download it here: https://github.com/tribler/tribler/releases
