### ISSUE TITLE
Error with missing configuration options

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3201]
Received this one in the error reporter:

```
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 423, in on_start_download_action
File "TriblerGUI\tribler_window.py", line 262, in perform_start_download_request
KeyError: 'default_number_hops'
```

**Comment by qstokkink** [comment]
Probably fixed in `devel`.

**Comment by qstokkink** [comment]
I did manage to make this fail with `default_number_hops =`:

```
ERROR   1510238676.67  tribler_window:78    Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/TriblerGUI/tribler_window.py", line 429, in on_start_download_action
    self.dialog.dialog_widget.files_list_view.topLevelItemCount())
  File "/home/quinten/Documents/tribler/TriblerGUI/tribler_window.py", line 267, in perform_start_download_request
    anon_hops = int(self.tribler_settings['Tribler']['default_number_hops']) if anon_download else 0
ValueError: invalid literal for int() with base 10: ''
```

**Comment by qstokkink** [comment]
We don't have enough information to solve this. We'll have to wait for a more extensive error report.

**Comment by devos50** [comment]
Closing due to lack of feedback.
