### ISSUE TITLE
Add support for IPV6 when tunneling data

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3202]
There are some reports in the crash report tool about IPV6:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 99, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\python\log.py", line 103, in callWithLogger

File "lib\site-packages\twisted\python\log.py", line 86, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 122, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 85, in callWithContext

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite

File "lib\site-packages\twisted\internet\tcp.py", line 208, in doRead

File "lib\site-packages\twisted\internet\tcp.py", line 214, in _dataReceived

File "Tribler\community\tunnel\Socks5\server.py", line 116, in dataReceived

File "Tribler\community\tunnel\Socks5\server.py", line 171, in _try_request

File "Tribler\community\tunnel\Socks5\conversion.py", line 180, in decode_request

File "Tribler\community\tunnel\Socks5\conversion.py", line 152, in __decode_address

Tribler.community.tunnel.Socks5.conversion.IPV6AddrError: IPV6 support not implemented
```

We should consider adding support for IPV6 at one point.

**Comment by egbertbouman** [comment]
The upcoming 8.0 release should have IPv6 support.
