### ISSUE TITLE
Unhandled exception in the TorrentChecker

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3206]
See these reports:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 99, in on_read_data
RuntimeError: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: UDP tracker failed for url udp://open.demonii.com:1337
]
```

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 99, in on_read_data
RuntimeError: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: UDP tracker failed for url udp://tracker.pow7.com:80
]
```

**Comment by qstokkink** [comment]
This is the source:
https://github.com/Tribler/tribler/blob/d7b5e230e20dccf8251b9144d8385edf0b8a8f76/Tribler/Core/TorrentChecker/session.py#L492-L495

**Comment by ichorid** [comment]
Everything changed in 7.5...
