### ISSUE TITLE
Port can be zero for Dispersy candidate, resulting in AssertionError

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3268]
See the following error we received in the crash reporter:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 99, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 63, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1195, in run

File "lib\site-packages\twisted\internet\base.py", line 1204, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 798, in runUntilCurrent

File "Tribler\Core\TFTP\handler.py", line 233, in data_came_in

File "Tribler\Core\TFTP\handler.py", line 325, in _handle_new_request

File "Tribler\Core\TFTP\handler.py", line 563, in _send_oack_packet

File "Tribler\Core\TFTP\handler.py", line 516, in _send_packet

File "Tribler\dispersy\candidate.py", line 30, in __init__

exceptions.AssertionError: ('182.30.65.219', 0)
```

**Comment by qstokkink** [comment]
Ah, because the TFTP handler is a direct Endpoint handler (/listener) it doesn't go through the standard valid Candidate check (https://github.com/Tribler/dispersy/blob/devel/endpoint.py#L250).

[dispersy.util.is_valid_address_or_log()](https://github.com/Tribler/dispersy/blob/devel/util.py#L292) should be called manually in the TFTP handler `data_came_in()`
