### ISSUE TITLE
Invalid argument: not an sstable (bad magic number)

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3302]
Platform:	Windows-10-10.0.16299-SP0
Machine:	AMD64
Python  : 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 99, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 65, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1243, in run

File "lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent

File "Tribler\Core\TFTP\handler.py", line 234, in data_came_in

File "Tribler\Core\TFTP\handler.py", line 306, in _handle_new_request

File "Tribler\Core\TFTP\handler.py", line 350, in _load_torrent

File "lib\_abcoll.py", line 382, in get

File "Tribler\Core\leveldbstore.py", line 86, in __getitem__

File "Tribler\Core\plyveladapter.py", line 9, in Get

File "plyvel\_plyvel.pyx", line 303, in plyvel._plyvel.DB.get (plyvel/_plyvel.cpp:4384)

File "plyvel\_plyvel.pyx", line 103, in plyvel._plyvel.db_get (plyvel/_plyvel.cpp:1942)

File "plyvel\_plyvel.pyx", line 86, in plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1799)

plyvel._plyvel.Error: Invalid argument: not an sstable (bad magic number)
``

**Comment by xoriole** [comment]
Found a related issue [google/leveldb](https://github.com/google/leveldb/issues/408)

**Comment by devos50** [comment]
Hmm, if I read the related issue, I guess it's something inside the leveldb/plyvel wrapper and I think we won't be able to solve this issue. Shall we postpone this issue to 7.1 or maybe even backlog?

Just an idea, it might be helpful if we do some kind of 'consistency check' when starting Tribler. This includes some small tests to see whether the databases are not corrupt. If they are, we make a backup of the old database and create a new one. This action should reported to the user.

**Comment by qstokkink** [comment]
I believe this is linked to #3308 (correct me if I'm wrong).

**Comment by xoriole** [comment]
@qstokkink Yes but it does not fix the issue.

**Comment by xoriole** [comment]
No solution yet available for this issue and the original issue from [[google/leveldb]](https://github.com/google/leveldb/issues/408) is still open. 

Since we do not use LevelDB anymore, this issue is not relevant for us so I'm closing this issue here. Feel free to open in the future if necessary.
