### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3306]
See the crash report from the reporter [(#11897)](http://reporter.tribler.org/stacktrace/11897)
```python
Traceback (most recent call last):
File "TriblerGUI\core_manager.py", line 140, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\internet\base.py", line 428, in fireEvent

File "lib\site-packages\twisted\internet\defer.py", line 321, in addCallback

File "lib\site-packages\twisted\internet\defer.py", line 310, in addCallbacks

File "lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 441, in _continueFiring

File "TriblerGUI\core_manager.py", line 62, in start_tribler

File "Tribler\dispersy\util.py", line 46, in helper

File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread

File "Tribler\Core\Session.py", line 562, in start

File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 184, in register

File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 262, in init

File "Tribler\dispersy\util.py", line 46, in helper

File "Tribler\dispersy\util.py", line 225, in blockingCallFromThread

File "Tribler\dispersy\dispersy.py", line 1618, in start

File "Tribler\dispersy\database.py", line 113, in open

File "Tribler\dispersy\database.py", line 140, in _initial_statements

sqlite3.OperationalError: database is locked
```

**Comment by qstokkink** [comment]
We should probably check for this in `check_os.py`.

**Comment by ichorid** [comment]
RIP Dispersy
