### ISSUE TITLE
Metainfo not a dict

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3314]
See this error from the crash reporter:

```
Traceback (most recent call last):
File "TriblerGUI/event_request_manager.py", line 99, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "multiprocessing/process.py", line 114, in run

File "TriblerGUI/core_manager.py", line 65, in start_tribler_core

File "twisted/internet/base.py", line 1199, in run

File "twisted/internet/base.py", line 1208, in mainLoop

--- <exception caught here> ---
File "twisted/internet/base.py", line 828, in runUntilCurrent

File "Tribler/dispersy/util.py", line 150, in wrapper

File "Tribler/Core/TFTP/handler.py", line 192, in _process_callbacks

File "Tribler/Core/TFTP/handler.py", line 261, in <lambda>

File "Tribler/dispersy/util.py", line 37, in helper

File "Tribler/Core/RemoteTorrentHandler.py", line 601, in _on_download_successful

File "Tribler/Core/TorrentDef.py", line 105, in load_from_memory

File "Tribler/Core/TorrentDef.py", line 119, in _create

File "Tribler/Core/Utilities/utilities.py", line 29, in validTorrentFile

exceptions.ValueError: metainfo not dict
```

Simply catching the ValueError in the TFTP response callback and logging it should be sufficient I think.

**Comment by devos50** [comment]
I believe it's impossible for this issue to occur since the code is already wrapped in a `try/finally` block. Even with a unit test, I'm unable to reproduce it (on the same platform as the crash report). See https://github.com/Tribler/tribler/blob/next/Tribler/Core/RemoteTorrentHandler.py#L606.

My only explanation, for now, is some black magic within the Python interpreter. Therefore I will close this issue unless someone else has a better idea or it happens again.

**Comment by devos50** [comment]
Nvm, I made a mistake in my unit test :)
