### ISSUE TITLE
PSUtil can throw an AccessDenied error

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3345]
See the following crash report:

```
Traceback (most recent call last):
File "TriblerGUI\debug_window.py", line 157, in tab_changed
File "TriblerGUI\debug_window.py", line 169, in system_tab_changed
File "TriblerGUI\debug_window.py", line 272, in load_open_files_tab
File "lib\site-packages\psutil\__init__.py", line 1207, in open_files
File "lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
AccessDenied: psutil.AccessDenied (pid=4840)
```

**Comment by ichorid** [comment]
Latest 7.4exp1 Py3 build:
```python
ERROR   1572981618.84          resource_monitor:134  (ResourceMonitor)  Failed to get memory full info: psutil.AccessDenied (pid=4120)
```
