### ISSUE TITLE
Error when starting devel branch

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3399]
```
Traceback (most recent call last):
  File "twisted/internet/base.py", line 420, in fireEvent
    
  File "twisted/internet/defer.py", line 319, in addCallback
    
  File "twisted/internet/defer.py", line 308, in addCallbacks
    
  File "twisted/internet/defer.py", line 651, in _runCallbacks
    
--- <exception caught here> ---
  File "twisted/internet/base.py", line 433, in _continueFiring
    
  File "TriblerGUI/core_manager.py", line 108, in start_tribler
    session.start()
  File "Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "Tribler/Core/Session.py", line 463, in start
    startup_deferred = self.lm.register(self, self.session_lock)
  File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 190, in register
    self.init()
  File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 352, in init
    self.ltmgr.initialize()
  File "Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "Tribler/dispersy/util.py", line 225, in blockingCallFromThread
    return f(*args, **kwargs)
  File "Tribler/Core/Libtorrent/LibtorrentMgr.py", line 88, in initialize
    self.get_session().start_upnp()
  File "Tribler/Core/Libtorrent/LibtorrentMgr.py", line 222, in get_session
    self.ltsessions[hops] = self.create_session(hops)
  File "Tribler/Core/Libtorrent/LibtorrentMgr.py", line 142, in create_session
    ltsession = lt.session(lt.fingerprint(*fingerprint), flags=0) if hops == 0 else lt.session(flags=0)
Boost.Python.ArgumentError: Python argument types in
    fingerprint.__init__(fingerprint, str, int, int, int)
did not match C++ signature:
    __init__(_object*, char const* id, int major, int minor, int revision, int tag)
```

**Comment by devos50** [comment]
@synctext I'm working on it (we saw your bug report)!

**Comment by synctext** [comment]
Fixed! in https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/lastSuccessfulBuild/artifact/tribler_7.1.0-mining-preview_all.deb
Now another polish issue, the credit-mining preview has credit mining off by default. Is it a small fix to turn in on by default for a few days in devel or that branch? please do if you find it good idea.

**Comment by devos50** [comment]
@synctext it seems that you should manually select a channel and click the 'mine' button.

I will make one more small change and then push a new preview version.

**Comment by synctext** [comment]
Seems I was unclear...It's off by default in the settings screen, every user now needs to enable it. then they can click in channel-min-button.

**Comment by devos50** [comment]
@synctext ah I see. Yeah I already forgot that I had to enable it in the settings menu. I agree with enabling it by default and it should be a small fix. This should also go in #3390.

**Comment by devos50** [comment]
Pushed new preview: https://github.com/Tribler/tribler/releases/tag/v7.1.0-mining-preview.

**Comment by devos50** [comment]
This issue was related to the tag I put on the release and is fixed already.
