### ISSUE TITLE
 exceptions.RuntimeError: torrent already exists in session

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3402]
From reporter (Tribler 7.0.0)
```python
Traceback (most recent call last):
File "TriblerGUI/event_request_manager.py", line 99, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "multiprocessing/process.py", line 114, in run

File "TriblerGUI/core_manager.py", line 65, in start_tribler_core

File "twisted/internet/base.py", line 1199, in run

File "twisted/internet/base.py", line 1208, in mainLoop

--- <exception caught here> ---
File "twisted/internet/base.py", line 828, in runUntilCurrent

File "Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 240, in schedule_create_engine

File "Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 341, in network_create_engine_wrapper

File "Tribler/Core/Libtorrent/LibtorrentMgr.py", line 304, in add_torrent

exceptions.RuntimeError: torrent already exists in session
```

Related: #3044

**Comment by qstokkink** [comment]
Hmm.. this might be related to this line:

https://github.com/Tribler/tribler/blob/309988168026dd2146ace8881e00ba78b4ad0883/Tribler/Core/Libtorrent/LibtorrentMgr.py#L282

Being changed into these lines:
https://github.com/Tribler/tribler/blob/3907045ac2ca5eb68fdb85b58e21b49458f245c5/Tribler/Core/Libtorrent/LibtorrentMgr.py#L300-L301

Since the fix of the related issue.

**Comment by synctext** [comment]
Please do a 7.0.1 release if you found a bug plus we have a fix. No rush, we have Monday morning to do it.

**Comment by devos50** [comment]
@qstokkink the functionality of the `sha1_hash` and `big_number` methods are similar, I've checked this in the source code of the libtorrent bindings.

**Comment by qstokkink** [comment]
@devos50 it's more the `unhexlify` part I'm concerned about. This might be an inconsistency between versions. I remember the above working for me and the `unhexlify` working for @egbertbouman .

**Comment by arvidn** [comment]
if it helps, there's a flag in ``add_torrent_params`` to make it not be an error to add the same torrent twice. Instead you just get back the ``torrent_handle`` to the existing torrent.
