### ISSUE TITLE
Issue when loading recent picked locations in the GUI

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3430]
See the following crash report:

```
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/tribler_app.py", line 17, in on_app_message
self.handle_uri(msg)
File "/usr/share/tribler/TriblerGUI/tribler_app.py", line 22, in handle_uri
self.activation_window().process_uri_request()
File "/usr/share/tribler/TriblerGUI/tribler_window.py", line 290, in process_uri_request
self.start_download_from_uri(uri)
File "/usr/share/tribler/TriblerGUI/tribler_window.py", line 465, in start_download_from_uri
self.dialog = StartDownloadDialog(self, self.download_uri)
File "/usr/share/tribler/TriblerGUI/dialogs/startdownloaddialog.py", line 75, in __init__
recent_locations = [url.decode('hex') for url in current_settings.split(",")]
File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
output = binascii.a2b_hex(input)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-25: ordinal not in range(128)
```

**Comment by qstokkink** [comment]
Related to #3421 .
