### ISSUE TITLE
NotImplementedError: SSL support unavailable

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3441]
From reporter (Tribler 7.0.0)
> I added an RSS feed and now Tribler crashes on boot every single time

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 99, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 65, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1243, in run

File "lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 878, in runUntilCurrent

File "Tribler\Core\Modules\channel\channel_rss.py", line 114, in _task_scrape

File "Tribler\Core\Modules\channel\channel_rss.py", line 111, in parse_feed

File "Tribler\Core\Modules\channel\channel_rss.py", line 267, in parse

File "Tribler\Core\Utilities\utilities.py", line 215, in http_get

File "lib\site-packages\twisted\web\client.py", line 1633, in request

File "lib\site-packages\twisted\web\client.py", line 1617, in _getEndpoint

File "lib\site-packages\twisted\web\client.py", line 1494, in endpointForURI

File "lib\site-packages\twisted\web\client.py", line 857, in raiseNotImplemented

exceptions.NotImplementedError: SSL support unavailable
```

**Comment by devos50** [comment]
It seems that the PyOpenssl package is corrupt or missing. As we discussed yesterday, this issue can have many root causes and I'm not sure whether it's a good idea to focus too long on this specific issue, unless there are multiple reports of the same error. Therefore, I suggest to move this issue to another milestone.

**Comment by qstokkink** [comment]
I second this motion

**Comment by xoriole** [comment]
I agree. Moving it to 7.1

**Comment by slrslr** [comment]
I think i found similar error in tribler-core-info.log and i have same Tribler version (7.0.0), this time 64bit and i am on WIndows 10 64bit.

> INFO    1518170456.25         session:241   Error when querying http tracker: [Failure instance: Traceback: <type 'exceptions.NotImplementedError'>: SSL support unavailable
> lib\site-packages\twisted\internet\defer.py:567:_startRunCallbacks
> lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
> lib\site-packages\twisted\internet\defer.py:459:callback
> lib\site-packages\twisted\internet\defer.py:567:_startRunCallbacks
> --- <exception caught here> ---
> lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
> lib\site-packages\twisted\web\client.py:2081:_handleResponse
> lib\site-packages\twisted\web\client.py:2063:_handleRedirect
> lib\site-packages\twisted\web\client.py:1633:request
> lib\site-packages\twisted\web\client.py:1617:_getEndpoint
> lib\site-packages\twisted\web\client.py:1494:endpointForURI
> lib\site-packages\twisted\web\client.py:857:raiseNotImplemented

**Comment by egbertbouman** [comment]
From the website of Win32OpenSSL (https://slproweb.com/products/Win32OpenSSL.html): "OpenSSL 1.1.0 is quite different from previous releases. Users should install BOTH the 1.0.2 series (LTS) and the 1.1.0 series for maximum application compatibility.".

Maybe we're missing one on the Windows 64-bit builder?

**Comment by xoriole** [comment]
New report of the same issue.
Platform - Windows-10-10.0.16299-SP0 - AMD64
>1. Adding an RSS Feed: https://yts.am/rss (#12926) 
>2. Unable to launch tribler (#12932)

I'm able to reproduce the bug so will investigate more on it.

**Comment by qstokkink** [comment]
I reproduced it and fixed it as follows, in `utilities.py`:

```python
def http_get(uri):

    def _on_response(response):
        if response.code == http.OK:
            return readBody(response)
        raise HttpError(response)

    agent = Agent(reactor)
    try:
        deferred = agent.request(
            'GET',
            uri,
            Headers({'User-Agent': ['Tribler ' + version_id]}),
            None)
        deferred.addCallback(_on_response)
        return deferred
    except:
        return fail()
```
