### ISSUE TITLE
Can not submit report about "Unexpected error", nothing happen

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#3456]
##### Tribler version/branch+revision: #####
7.0.0 x64 downloaded today from tribler.org, previously i used alpha version so i have %appdata%/.Tribler from previous version. Before alpha i had 6.x version.
##### Operating system and version: #####
Windows 10 64bit
##### Issue: #####
Hello, when I added torrent by providing magnet link that included a few tens of trackers. Save location already existed, i already have all files downloaded, i just wanted to seed. Then i got popup window entitled "Unexpected error" and invitation to send report to developers.

> Traceback (most recent call last):
  File "TriblerGUI\tribler_window.py", line 488, in on_start_download_action
  File "TriblerGUI\tribler_window.py", line 321, in perform_start_download_request
  File "lib\encodings\hex_codec.py", line 24, in hex_encode
UnicodeEncodeError: 'ascii' codec can't encode character u'\u010d' in position 11: ordinal not in range(128)

"SEND REPORT" button was clicked, but nothing happen many minutes.

In Tribler configuration, i see "Log directory" field and it is empty. I found some logs in C:\Users\me\AppData\Roaming\.Tribler\logs\tribler-(core/gui)-(error/info).log, not sure which one contains needed data and what are footprints of these log entries.

Some interesting errors i also found in tribler-core-error.log: https://pastebin.com/M3HtsYxY

**Comment by themusicgod1** [comment]
same thing, ubuntu artful 17.10 / next  7.0.1 next 0f36719e6

**Comment by qstokkink** [comment]
Thanks for the reports. Here is the compilation for my fellow developers:

```python
Traceback (most recent call last):
  File "Tribler\dispersy\dispersy.py", line 1240, in _update
  File "Tribler\dispersy\community.py", line 3164, in on_missing_proof
  File "Tribler\dispersy\timeline.py", line 120, in check
AttributeError: 'NoneType' object has no attribute 'name'
```

```python
Traceback (most recent call last):
  File "lib\site-packages\twisted\web\server.py", line 184, in process
  File "lib\site-packages\twisted\web\server.py", line 235, in render
  File "lib\site-packages\twisted\web\resource.py", line 250, in render
  File "Tribler\Core\Modules\restapi\channels\channels_torrents_endpoint.py", line 276, in render_DELETE
  File "Tribler\community\channel\community.py", line 440, in remove_torrents
  File "Tribler\dispersy\community.py", line 3398, in create_undo
AssertionError: create_undo was called without having the permission to undo
```

```python
ERROR   1518174428.19        dispersy:1245  exception during handle_callback for dispersy-missing-proof
Traceback (most recent call last):
  File "Tribler\dispersy\dispersy.py", line 1240, in _update
  File "Tribler\dispersy\community.py", line 3164, in on_missing_proof
  File "Tribler\dispersy\timeline.py", line 120, in check
AttributeError: 'NoneType' object has no attribute 'name'
```

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 190, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 241, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py", line 293, in render_PUT
    unicode(parameters['uri'][0], 'utf-8'), download_config)
  File "/usr/share/tribler/Tribler/Core/Session.py", line 313, in start_download_from_uri
    return self.lm.ltmgr.start_download_from_uri(uri, dconfig=dconfig)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 568, in start_download_from_uri
    return succeed(self.start_download_from_magnet(uri, dconfig=dconfig))
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 592, in start_download_from_magnet
    return self.start_download(tdef=tdef, dconfig=dconfig)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 627, in start_download
    raise DuplicateDownloadException("This download already exists.")
DuplicateDownloadException: <class 'Tribler.Core.exceptions.DuplicateDownloadException'>: This download already exists.
```

```python
ERROR   1521219897.63  tribler_window:84    Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/tribler_request_manager.py", line 351, in <lambda>
    network_reply.finished.connect(lambda: reply_callback(network_reply))
  File "/usr/share/tribler/TriblerGUI/tribler_request_manager.py", line 236, in reply_callback
    self.on_finished(reply, capture_errors)
  File "/usr/share/tribler/TriblerGUI/tribler_request_manager.py", line 276, in on_finished
    self.show_error(TriblerRequestWorker.get_message_from_error(json_result))
AttributeError: type object 'TriblerRequestWorker' has no attribute 'get_message_from_error'
```

**Comment by devos50** [comment]
Dispersy is end-of-life so we won't consider fixing the Dispersy-related issues. Sending the report should also be fixed already. I will close this issue. Please reopen it if you encounter any error regarding the error reports.

**Comment by Dmole** [comment]
@devos50 The unable to send "traceback/environment/comments" for "unexpected error" window happening again on V7.1.0.

**Comment by devos50** [comment]
@Dmole could you be a bit more specific on what happened? Did the window just freeze? Also, is there any interesting log output in the `%APPDATA%\roaming\.Tribler\logs` directory?

**Comment by Dmole** [comment]
@devos50 the button changed to "Sending..." but after 10 minutes I considered it busted.

I had to scrap my .Tribler due to other bugs but I'll look if it happens again.

**Comment by synctext** [comment]
Had same thing happen. Error after a crash, unable to send report. Have photo of error report.

**Comment by devos50** [comment]
There was an error in the machine that handles new reports. It is fixed now 👍
