### ISSUE TITLE
twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3468]
From reporter - Tribler 7.0.1 (#12653) 
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 102, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 65, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1243, in run

File "lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 878, in runUntilCurrent

File "lib\site-packages\twisted\internet\tcp.py", line 292, in connectionLost

File "lib\site-packages\twisted\web\http.py", line 2190, in connectionLost

File "lib\site-packages\twisted\internet\base.py", line 99, in cancel

twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
```

**Comment by devos50** [comment]
My new application tester managed to reproduce this after ~30 minutes of running :)

```
INFO    1527428944.20                   session:257  (HttpTrackerSession)  Error when querying http tracker: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.CancelledError'>:
] http://www.psychocydd.co.uk:2710/announce
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 130, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 929, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1616, in _connectionLost_WAITING
    self._disconnectParser(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1538, in _disconnectParser
    parser.connectionLost(reason)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 544, in connectionLost
    self.response._bodyDataFinished(Failure())
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 929, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1185, in _bodyDataFinished_CONNECTED
    self._bodyProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 2119, in connectionLost
    b''.join(self.dataBuffer)))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 498, in errback
    self._startRunCallbacks(fail)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 558, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError: 

ERROR   1527428944.21            tribler_window:89   (root)  Traceback (most recent call last):
  File "/var/lib/tribler/tribler/TriblerGUI/event_request_manager.py", line 127, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 130, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 929, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1616, in _connectionLost_WAITING
    self._disconnectParser(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1538, in _disconnectParser
    parser.connectionLost(reason)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 544, in connectionLost
    self.response._bodyDataFinished(Failure())
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 929, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1185, in _bodyDataFinished_CONNECTED
    self._bodyProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 2119, in connectionLost
    b''.join(self.dataBuffer)))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 498, in errback
    self._startRunCallbacks(fail)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 558, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError:
```
