### ISSUE TITLE
TFTP - InvalidOptionException

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3514]
From reporter - Tribler 7.0.1 (#13028)
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 102, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 65, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1243, in run

File "lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent

File "Tribler\Core\TFTP\handler.py", line 221, in data_came_in

File "Tribler\Core\TFTP\packet.py", line 201, in decode_packet

File "Tribler\Core\TFTP\packet.py", line 167, in _decode_oack

File "Tribler\Core\TFTP\packet.py", line 76, in _decode_options

Tribler.Core.TFTP.exception.InvalidOptionException: Unknown option['\xf5\xa4ecksum']
```

**Comment by devos50** [comment]
Should be trivial to fix by catching it.
