### ISSUE TITLE
fix_torrent request error

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3527]
I got this after adding a torrent on the latest `next`:
![afbeelding](https://user-images.githubusercontent.com/3630389/37826285-168a0842-2e93-11e8-8750-474b6f8a8da4.png)

```json
{
   "error":{
      "message":"",
      "code":"IOError",
      "handled":false,
      "trace":[
         "  File \"/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py\", line 195, in process\n    self.render(resrc)\n",
         "  File \"/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py\", line 255, in render\n    body = resrc.render(self)\n",
         "  File \"/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py\", line 250, in render\n    return m(request)\n",
         "  File \"/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py\", line 298, in render_PUT\n    unquote_plus(unicode(parameters['uri'][0], 'utf-8')), download_config)\n",
         "  File \"/home/quinten/Documents/tribler/Tribler/Core/Session.py\", line 215, in start_download_from_uri\n    return self.lm.ltmgr.start_download_from_uri(uri, dconfig=download_config)\n",
         "  File \"/home/quinten/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py\", line 625, in start_download_from_uri\n    return succeed(self.start_download(torrentfilename=argument, dconfig=dconfig))\n",
         "  File \"/home/quinten/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py\", line 668, in start_download\n    torrent_data = fix_torrent(torrentfilename)\n",
         "  File \"/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py\", line 427, in fix_torrent\n    f = open(file_path, 'rb')\n"
      ]
   }
}
```

**Comment by qstokkink** [comment]
There was a hidden error in the terminal:
```
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py", line 97, in render_GET
    metainfo_deferred.callback(bdecode(fix_torrent(filename)))
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 427, in fix_torrent
    f = open(file_path, 'rb')
IOError: [Errno 2] No such file or directory: u'/home/quinten/Downloads/\u9b54\u6cd5\u4f7f\u3044\u306e\u5ac1\u30c6\u30fc\u30de\u300c\u74b0\u300d\uff0f\u7cf8\u5947\u306f\u306a.torrent'
```

**Comment by qstokkink** [comment]
Probably related to #3510, @xoriole .
