### ISSUE TITLE
Last three builds abend at start up, last is build 10042018

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3579]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
yes
##### Tribler version/branch+revision: #####
7.1
##### Operating system and version: #####
Windows Insider preview 17639
##### Steps to reproduce the behavior: #####
Start Tribler
##### Expected behavior: #####
Normal startup
##### Actual behavior: #####
Abend
##### Relevant log file output: #####
[tribler-gui-error.log](https://github.com/Tribler/tribler/files/1895437/tribler-gui-error.log)
[tribler-gui-info.log](https://github.com/Tribler/tribler/files/1895438/tribler-gui-info.log)
[crash-report.log](https://github.com/Tribler/tribler/files/1895439/crash-report.log)

**Comment by qstokkink** [comment]
Apparently an environment variable is being set with a non-string (int or something):

```python
ERROR   1523376806.54  tribler_window:89    Traceback (most recent call last):
  File "TriblerGUI\core_manager.py", line 65, in on_request_error
  File "TriblerGUI\core_manager.py", line 76, in start_tribler_core
  File "lib\subprocess.py", line 390, in __init__
  File "lib\subprocess.py", line 640, in _execute_child
TypeError: environment can only contain strings
```

**Comment by qstokkink** [comment]
We could probably do something like the following on https://github.com/Tribler/tribler/blob/next/TriblerGUI/core_manager.py#L72 : 

```python
custom_env = {str(k): str(v) for k, v in os.environ.iteritems()}
```

**Comment by devos50** [comment]
@qstokkink would this also work with unicode paths (i.e. the `PATH` variable)?

**Comment by qstokkink** [comment]
@devos50 That would make it slightly more complicated:

```python
custom_env = {(k if isinstance(k, basestring) else str(k)): (v if isinstance(v, basestring) else str(v)) for k, v in os.environ.iteritems()}
```

**Comment by devos50** [comment]
@qstokkink let me verify whether this works on Windows 👍

**Comment by qstokkink** [comment]
@devos50 sure 👍

**Comment by devos50** [comment]
@qstokkink I didn't realise you code strips out all unicode strings which is undesirable I guess. We have to deal with unicode strings being passed in the subprocess environment unfortunately.

**Comment by qstokkink** [comment]
The `x if isinstance(x, basestring) else str(x)` should only cast `x` to `str` if it is not `unicode` or `str` already.

**Comment by xoriole** [comment]
```python
Windows exception: code 0x0000000d

Thread 0x00001214 (most recent call first):
  File "lib\logging\__init__.py", line 882 in emit
  File "lib\logging\__init__.py", line 759 in handle
  File "lib\logging\__init__.py", line 1336 in callHandlers
  File "lib\logging\__init__.py", line 1296 in handle
  File "lib\logging\__init__.py", line 1286 in _log
  File "lib\logging\__init__.py", line 1167 in info
  File "lib\logging\__init__.py", line 1629 in info
  File "run_tribler.py", line 101 in <module>
```
The other log present in the crash report.

**Comment by devos50** [comment]
After searching for a bit, it seems that passing unicode in environment when using `subprocess` is simply not possible.

Alternatively, we might refactor the code and pass these variables as arguments, _however_, `subprocess` also doesn't support unicode in the system arguments... we might solve that with this library: https://pypi.python.org/pypi/subprocessww. Thoughts?

**Comment by qstokkink** [comment]
I guess the alternative is this:
https://stackoverflow.com/a/11442604

**Comment by Nubro01** [comment]
Build from 11-04-2018 same problem.

[tribler-gui-info.log](https://github.com/Tribler/tribler/files/1899959/tribler-gui-info.log)
[tribler-core-error.log](https://github.com/Tribler/tribler/files/1899960/tribler-core-error.log)
[tribler-core-info.log](https://github.com/Tribler/tribler/files/1899961/tribler-core-info.log)
[crash-report.log](https://github.com/Tribler/tribler/files/1899962/crash-report.log)
[tribler-gui-error.log](https://github.com/Tribler/tribler/files/1899963/tribler-gui-error.log)

**Comment by xoriole** [comment]
@Nubro01 Could you try this specific [experimental build](https://jenkins.tribler.org/job/pers/job/Build-Tribler_Win64_sandip/lastSuccessfulBuild/artifact/tribler/dist/Tribler_7.0.1-19-g194b181be_x64.exe) and let us know if it solves the issue?

It seems to us that the problem could be because of some environmental variables specific to your system hence a specific build only for you. We would very much appreciate your cooperation on solving this issue.

**Comment by Nubro01** [comment]
The build could not be found, I was probably to late.
________________________________
Van: Sandip Pandey <notifications@github.com>
Verzonden: donderdag 12 april 2018 16:12
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Last three builds abend at start up, last is build 10042018 (#3579)


@Nubro01<https://github.com/Nubro01> Could you try this specific experimental build<https://jenkins.tribler.org/job/pers/job/Build-Tribler_Win64_sandip/lastSuccessfulBuild/artifact/tribler/dist/Tribler_7.0.1-19-g194b181be_x64.exe> and let us know if it solves the issue?

It seems to us that the problem could be because of some environmental variables specific to your system hence a specific build only for you. We would very much appreciate your cooperation on solving this issue.

**Comment by Nubro01** [comment]
I adjusted the url and selected the file manually. Installing now!
________________________________
Van: Ron Nuberg <nubro01@hotmail.com>
Verzonden: donderdag 12 april 2018 19:06
Aan: Tribler/tribler; Tribler/tribler
CC: Mention
Onderwerp: Re: [Tribler/tribler] Last three builds abend at start up, last is build 10042018 (#3579)

The build could not be found, I was probably to late.
________________________________
Van: Sandip Pandey <notifications@github.com>
Verzonden: donderdag 12 april 2018 16:12
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Last three builds abend at start up, last is build 10042018 (#3579)


@Nubro01<https://github.com/Nubro01> Could you try this specific experimental build<https://jenkins.tribler.org/job/pers/job/Build-Tribler_Win64_sandip/lastSuccessfulBuild/artifact/tribler/dist/Tribler_7.0.1-19-g194b181be_x64.exe> and let us know if it solves the issue?

It seems to us that the problem could be because of some environmental variables specific to your system hence a specific build only for you. We would very much appreciate your cooperation on solving this issue.

**Comment by Nubro01** [comment]
Startup is continueing with this test build. Shutdown however is still not normal. I replied on the received mail with logs of last shutdown.
