### ISSUE TITLE
Tribler crashes on memory dump from GUI

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3598]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler exp1-122

##### Operating system and version: #####
Winsdows 10

##### Steps to reproduce the behavior: #####
Go to debug and select memory dump for GUI

##### Expected behavior: #####
Get memory dump in json (I think)

##### Actual behavior: #####
Get empty json file and GUI part of tribler crashes, though console still remains and logs info. 

##### Relevant log file output: #####
(Might be from two attemps, or the same one, as i can't tell from the traceback.)

Windows exception: code 0x000006ba

Current thread 0x0000326c (most recent call first):
  File "TriblerGUI\debug_window.py", line 473 in on_memory_dump_button_clicked
  File "TriblerGUI\debug_window.py", line 129 in <lambda>
  File "run_tribler.py", line 95 in <module>
Windows exception: access violation

Current thread 0x0000326c (most recent call first):
  File "lib\site-packages\meliae\scanner.py", line 69 in dump_all_referenced
  File "lib\site-packages\meliae\scanner.py", line 139 in dump_all_objects
  File "TriblerGUI\debug_window.py", line 483 in on_memory_dump_button_clicked
  File "TriblerGUI\debug_window.py", line 130 in <lambda>
  File "run_tribler.py", line 95 in <module>

**Comment by xoriole** [comment]
This seems specific to windows. I cannot reproduce it in Linux version.

**Comment by Thomasedv** [comment]
Also fail to make a memory dump of the core, with this error in the log:

![image](https://user-images.githubusercontent.com/1584461/39119492-4a09d366-46ec-11e8-89d4-61b9ce60dc02.png)

Current memory usage by tribler is at 6 GB.

![image](https://user-images.githubusercontent.com/1584461/39119571-7b0fa36e-46ec-11e8-87c6-e44b06982b0e.png)

**Comment by xoriole** [comment]
Thank you for the log and the memory graph. This is helpful.

**Comment by xoriole** [comment]
```python
Traceback (most recent call last):
File "TriblerGUI\debug_window.py", line 481, in <lambda>
File "TriblerGUI\debug_window.py", line 496, in on_memory_dump_data_available
File "TriblerGUI\dialogs\confirmationdialog.py", line 47, in show_error
File "TriblerGUI\dialogs\confirmationdialog.py", line 16, in __init__
File "TriblerGUI\dialogs\dialogcontainer.py", line 15, in __init__
AttributeError: 'DebugWindow' object has no attribute 'resize_event'
```
Additional error log on memory dump. Occurs only on windows.

**Comment by devos50** [comment]
The error posted by @xoriole (with the `resize_event`) has been fixed already.

**Comment by ichorid** [comment]
Meliae is dead for us.
