### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x7b [downloads_endpoint]

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3599]
```python
ERROR   1524636953.43    rest_manager:54    [Failure instance: Traceback: <type 'exceptions.UnicodeDecodeError'>: 'utf8' codec can't decode byte 0x7b in position 0: could not dump:
    dict[downloads]->list->dict[name]->str::'\xc0\xd0\xce\xcd'
lib\site-packages\twisted\protocols\basic.py:571:dataReceived
lib\site-packages\twisted\web\http.py:1964:lineReceived
lib\site-packages\twisted\web\http.py:2059:allContentReceived
lib\site-packages\twisted\web\http.py:869:requestReceived
--- <exception caught here> ---
lib\site-packages\twisted\web\server.py:184:process
lib\site-packages\twisted\web\server.py:235:render
lib\site-packages\twisted\web\resource.py:250:render
Tribler\Core\Modules\restapi\downloads_endpoint.py:247:render_GET
Tribler\Core\Utilities\json_util.py:100:dumps
]
Traceback (most recent call last):
  File "lib\site-packages\twisted\web\server.py", line 184, in process
  File "lib\site-packages\twisted\web\server.py", line 235, in render
  File "lib\site-packages\twisted\web\resource.py", line 250, in render
  File "Tribler\Core\Modules\restapi\downloads_endpoint.py", line 247, in render_GET
  File "Tribler\Core\Utilities\json_util.py", line 100, in dumps
UnicodeDecodeError: 'utf8' codec can't decode byte 0x7b in position 0: could not dump:
    dict[downloads]->list->dict[name]->str::'\xc0\xd0\xce\xcd'
```

**Comment by qstokkink** [comment]
For reference, the offending entry is the following:

```json
{
    "downloads": [
        {
            "name": "\xc0\xd0\xce\xcd"
        }
    ]
}
```

**Comment by qstokkink** [comment]
It seems like the torrent has to be added in the LaunchManyCore `add()` with the offending `tdef`: https://github.com/Tribler/tribler/blob/next/Tribler/Core/APIImplementation/LaunchManyCore.py#L438

**Comment by qstokkink** [comment]
This might be unicode for `샐컍`?

**Comment by devos50** [comment]
Another related report from the forums:

```
‘utf8’ codec can’t decode byte 0x3a in position 52: could not dump:
dict[downloads]->list->dict[name]->str::’[March_2014] [Platinum] (pthc pedo) virginz.info 15 \xeb\xe5\xf2\xed\xff\xff \xe0\xed\xff \xe8\xe3\xf0\xe0\xe5\xf2 \xf1 \xe2\xe8\xe1\xf0\xe0\xf2\xee\xf0\xee\xec (\xef\xe5\xe4\xee,\xe4\xe5\xf2\xe8,\xe4\xe5\xe2\xee\xf7\xea\xe8,\xec\xe0\xeb\xee\xeb\xe5\xf2\xea\xe8).rar’
dict[downloads]->list->dict[name]->str::’(pthc pedo) 3\xeb\xe5\xf1\xe1\
```

**Comment by qstokkink** [comment]
I wonder what font encoding that is though.
My best guesses for this text are:

`[March_2014] [Platinum] (pthc <FILTERED>) virginz.info 15 ëåòíÿÿ àíÿ èãðàåò ñ âèáðàòîðîì (ïåäî,äåòè,äåâî÷êè,ìàëîëåòêè).rar`
`[March_2014] [Platinum] (pthc <FILTERED>) virginz.info 15 ÙÕ‗Ý   ÓÝ  ÞÒ­ÓÕ‗ ± ÔÞß­Ó‗¯­¯ý (´Õõ¯,õÕ‗Þ,õÕÔ¯¸ÛÞ,ýÓÙ¯ÙÕ‗ÛÞ).rar`

**Comment by qstokkink** [comment]
I would like to propose checking the name on the following line and changing it to a `utf-8` compatible string:

https://github.com/Tribler/tribler/blob/next/Tribler/Core/TorrentDef.py#L493
