### ISSUE TITLE
Issue with installation on Ubuntu 18.04 

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3601]
There seem to be a problem with Tribler installation on latest 18.04 Ubuntu (beta) related to sqlite. We should have a deployment test for it as soon as a stable release 18.04 is released in few days.

```python
apsw.SQLError: SQLError: no such module: fts4
```
```python
Traceback (most recent call last):
File "/home/vader/src/TRIBLER/tribler/TriblerGUI/core_manager.py", line 114, in on_received_state
raise RuntimeError(state['last_exception'])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 428, in fireEvent
DeferredList(beforeResults).addCallback(self._continueFiring)
File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
callbackKeywords=kw)
File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
self._runCallbacks()
File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
callable(*args, **kwargs)
File "run_tribler.py", line 52, in start_tribler
session.start()
File "/home/vader/src/TRIBLER/tribler/Tribler/dispersy/util.py", line 46, in helper
return blockingCallFromThread(reactor, func, *args, **kargs)
File "/home/vader/src/TRIBLER/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
return f(*args, **kwargs)
File "/home/vader/src/TRIBLER/tribler/Tribler/Core/Session.py", line 466, in start
self.start_database()
File "/home/vader/src/TRIBLER/tribler/Tribler/dispersy/util.py", line 46, in helper
return blockingCallFromThread(reactor, func, *args, **kargs)
File "/home/vader/src/TRIBLER/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
return f(*args, **kwargs)
File "/home/vader/src/TRIBLER/tribler/Tribler/Core/Session.py", line 451, in start_database
self.sqlite_db.initialize()
File "/home/vader/src/TRIBLER/tribler/Tribler/dispersy/util.py", line 46, in helper
return blockingCallFromThread(reactor, func, *args, **kargs)
File "/home/vader/src/TRIBLER/tribler/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
return f(*args, **kwargs)
File "/home/vader/src/TRIBLER/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 85, in initialize
self._open_connection()
File "/home/vader/src/TRIBLER/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 181, in _open_connection
cursor.execute(sql_script)
File "src/cursor.c", line 236, in resetcursor

apsw.SQLError: SQLError: no such module: fts4
```

Related: #2608

**Comment by xoriole** [comment]
This issue was encountered in Ubuntu 18.04 beta release but does not seem to occur in the official release so closing it for now.
