### ISSUE TITLE
test_torrent_store_delete accessing real state directory

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3608]
`Tribler.Test.Core.test_session.TestSession.test_torrent_store_delete` should be using a temporary state directory, it is however using the real one:

```
======================================================================
ERROR: test_torrent_store_delete (Tribler.Test.Core.test_session.TestSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\test_as_server.py", line 58, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\Core\test_session.py", line 36, in test_torrent_store_delete
    session.lm.torrent_store = LevelDbStore(session.config.get_torrent_store_dir())
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\leveldbstore.py", line 71, in __init__
    rmtree(self._store_dir)
  File "c:\python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'%APPDATA%\\.Tribler\\collected_torrents\\000005.ldb'
-------------------- >> begin captured logging << --------------------
```

**Comment by qstokkink** [comment]
After some discussion, this appears to be an overarching config problem. I'm increasing the priority of this.

**Comment by devos50** [comment]
I'll try to fix this one 👍

**Comment by qstokkink** [comment]
We fixed this by removing the `.ldb` files from `u'%APPDATA%\\.Tribler\\collected_torrents\\'`. Adding them there again should reproduce this.

**Comment by qstokkink** [comment]
* AND having the other process running and accessing these `ldb` files of course.

**Comment by qstokkink** [comment]
For now we could just keep a Tribler instance running and it will probably fail by itself eventually.

**Comment by qstokkink** [comment]
As I can also no longer reproduce this, my best guess is that this got fixed while refactoring LevelDB previously.
