### ISSUE TITLE
Socket error: non-blocking socket operation

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3638]
From reporter - Tribler 7.1.0-exp2 on Windows-10-10.0.17134-SP0 x64
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 127, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'socket.error'>: [Errno 10035] Een niet-blokkerende socketbewerking kan niet onmiddellijk worden voltooid
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\pyipv8\ipv8_service.py:109:on_tick
Tribler\pyipv8\ipv8\peerdiscovery\churn.py:63:take_step
Tribler\pyipv8\ipv8\messaging\interfaces\udp\endpoint.py:21:send
lib\site-packages\twisted\internet\udp.py:298:write
]
```

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 127, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'socket.error'>: [Errno 10035] Een niet-blokkerende socketbewerking kan niet onmiddellijk worden voltooid
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\dispersy\community.py:1223:take_step
Tribler\dispersy\community.py:2766:create_introduction_request
Tribler\dispersy\util.py:150:wrapper
Tribler\dispersy\dispersy.py:1290:_forward
Tribler\dispersy\dispersy.py:1336:_send
Tribler\dispersy\endpoint.py:434:send
Tribler\dispersy\endpoint.py:455:send_packet
Tribler\pyipv8\ipv8\messaging\interfaces\udp\endpoint.py:21:send
lib\site-packages\twisted\internet\udp.py:298:write
]
```

**Comment by qstokkink** [comment]
This is due to IPv8 switching endpoint backend.

**Comment by qstokkink** [comment]
@xoriole I assume this is Windows?

**Comment by xoriole** [comment]
yes, Windows-10-10.0.17134-SP0 x64 version

**Comment by qstokkink** [comment]
Twisted's UDP implementation is known to have some problems on Windows.

**Comment by qstokkink** [comment]
Ok, after reading into this a bit: this seems to be the notification mechanism that is telling us that the packet is dropped (due to a buffer being full somewhere).

**Comment by qstokkink** [comment]
@ichorid do you want to take this one?

**Comment by ichorid** [comment]
@qstokkink, sure, I'll take this one.

**Comment by xoriole** [comment]
Yet another traceback with socket error
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 127, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'socket.error'>: [Errno 22] Invalid argument
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1243:run
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1252:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:878:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/usr/share/tribler/Tribler/pyipv8/ipv8_service.py:109:on_tick
/usr/share/tribler/Tribler/pyipv8/ipv8/peerdiscovery/churn.py:63:take_step
/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/interfaces/udp/endpoint.py:21:send
/usr/lib/python2.7/dist-packages/twisted/internet/udp.py:298:write
]
```

**Comment by ichorid** [comment]
@devos50 created a pull request for this: https://github.com/Tribler/py-ipv8/pull/148
