### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3651]
Occasionally occurs on shutdown.
```python
ERROR   1527600174.46              rest_manager:53   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.TypeError'>: 'NoneType' object is not iterable
/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py:571:dataReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:2013:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:2104:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:866:requestReceived
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:195:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:255:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/home/sandip/tudelft/tribler/Tribler/Core/Modules/restapi/trustchain_endpoint.py:87:render_GET
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py:14:helper
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py:26:blockingCallFromThread
/home/sandip/tudelft/tribler/Tribler/community/triblerchain/community.py:44:get_statistics
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py:80:get_latest
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py:49:_get
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/sandip/tudelft/tribler/Tribler/Core/Modules/restapi/trustchain_endpoint.py", line 87, in render_GET
    return json.dumps({'statistics': triblerchain_community.get_statistics()})
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py", line 14, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py", line 26, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/sandip/tudelft/tribler/Tribler/community/triblerchain/community.py", line 44, in get_statistics
    latest_block = self.persistence.get_latest(public_key)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 80, in get_latest
    u"WHERE public_key = ?)", (buffer(public_key), buffer(public_key)))
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 49, in _get
    db_result = list(self.execute(self.get_sql_header() + query, params, fetch_all=False))
TypeError: 'NoneType' object is not iterable
```

**Comment by devos50** [comment]
The GUI periodically (every minute) makes a request to fetch the latest token balance. We should stop this loop when shutting down obviously 👍
