### ISSUE TITLE
Request error

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3688]
![afbeelding](https://user-images.githubusercontent.com/3630389/41897234-06dd2b34-7927-11e8-8df9-3dd42fe411fb.png)

On latest next when adding a download.

```python
ERROR   1530000068.54              rest_manager:53   (RESTRequest)  [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: no such column: type
/home/quinten/.local/lib/python2.7/site-packages/twisted/protocols/basic.py:571:dataReceived
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/http.py:2013:lineReceived
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/http.py:2104:allContentReceived
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/http.py:866:requestReceived
--- <exception caught here> ---
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py:195:process
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py:255:render
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py:250:render
/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/trustchain_endpoint.py:86:render_GET
/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/util.py:14:helper
/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/util.py:26:blockingCallFromThread
/home/quinten/Documents/tribler/Tribler/Core/Modules/wallet/tc_wallet.py:170:get_statistics
/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py:123:get_latest
/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py:64:_get
/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/database.py:41:wrapper
/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/database.py:305:execute
]
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/trustchain_endpoint.py", line 86, in render_GET
    return json.dumps({'statistics': self.session.lm.wallets['MB'].get_statistics()})
  File "/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/util.py", line 14, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/util.py", line 26, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/wallet/tc_wallet.py", line 170, in get_statistics
    latest_block = self.trustchain.persistence.get_latest(public_key, block_type='tribler_bandwidth')
  File "/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 123, in get_latest
    (buffer(public_key), block_type, buffer(public_key), block_type))
  File "/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 64, in _get
    db_result = list(self.execute(self.get_sql_header() + query, params, fetch_all=False))
  File "/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/database.py", line 41, in wrapper
    return f(self, *args, **kwargs)
  File "/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/database.py", line 305, in execute
    result = self._cursor.execute(statement, bindings)
OperationalError: no such column: type
```

**Comment by qstokkink** [comment]
This is probably due to running a development build.
