### ISSUE TITLE
OperationalError: no such column: type

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3691]
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/sandip/tudelft/tribler/Tribler/Core/Modules/restapi/trustchain_endpoint.py", line 86, in render_GET
    return json.dumps({'statistics': self.session.lm.wallets['MB'].get_statistics()})
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py", line 14, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py", line 26, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/sandip/tudelft/tribler/Tribler/Core/Modules/wallet/tc_wallet.py", line 170, in get_statistics
    latest_block = self.trustchain.persistence.get_latest(public_key, block_type='tribler_bandwidth')
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 123, in get_latest
    (buffer(public_key), block_type, buffer(public_key), block_type))
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 64, in _get
    db_result = list(self.execute(self.get_sql_header() + query, params, fetch_all=False))
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/database.py", line 41, in wrapper
    return f(self, *args, **kwargs)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/database.py", line 305, in execute
    result = self._cursor.execute(statement, bindings)
OperationalError: no such column: type
```

**Comment by devos50** [comment]
@xoriole which version number do you have stored in the database?
