### ISSUE TITLE
Socket error 10054 when running Tribler

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3713]
Extracted this one from the bug reporter (happened on 7.0.1):

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 102, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\threading.py", line 774, in __bootstrap

File "lib\threading.py", line 801, in __bootstrap_inner

File "lib\threading.py", line 754, in run

File "lib\site-packages\twisted\_threads\_threadworker.py", line 46, in work

--- <exception caught here> ---
File "lib\site-packages\twisted\_threads\_team.py", line 190, in doWork

File "lib\site-packages\twisted\python\threadpool.py", line 258, in inContext

File "lib\site-packages\twisted\internet\threads.py", line 49, in onResult

File "lib\site-packages\twisted\internet\base.py", line 997, in callFromThread

File "lib\site-packages\twisted\internet\base.py", line 566, in wakeUp

File "lib\site-packages\twisted\internet\posixbase.py", line 91, in wakeUp

File "lib\site-packages\twisted\python\util.py", line 815, in untilConcludes

socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host
```

**Comment by devos50** [comment]
The error format seems to change in Python 3:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\python\log.py", line 86, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 122, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 85, in callWithContext

File "lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\udp.py", line 249, in doRead

File "Tribler\pyipv8\ipv8\messaging\interfaces\udp\endpoint.py", line 34, in datagramReceived

File "Tribler\pyipv8\ipv8\messaging\interfaces\endpoint.py", line 60, in notify_listeners

File "lib\site-packages\twisted\internet\base.py", line 1032, in callFromThread

File "lib\site-packages\twisted\internet\base.py", line 587, in wakeUp

File "lib\site-packages\twisted\internet\posixbase.py", line 91, in wakeUp

File "lib\site-packages\twisted\python\util.py", line 815, in untilConcludes

builtins.ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by devos50** [comment]
This should be fixed by the recent refactoring of the unhandled error observer.
