### ISSUE TITLE
Build 301 jul 12 13:15 fails with Windows 10 build 17713

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3736]
##### Operating system and version: #####
Windows 10 Insider build 17713
##### Steps to reproduce the behavior: #####
Install build 301 and start up, dump is send, it says. I hope this is true?
##### Expected behavior: #####
Normal startup
##### Actual behavior: #####
Abend with dump send?

**Comment by devos50** [comment]
@Nubro01 I suppose you mean this error?

```
Traceback (most recent call last):
File "TriblerGUI\core_manager.py", line 114, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\internet\base.py", line 428, in fireEvent

File "lib\site-packages\twisted\internet\defer.py", line 321, in addCallback

File "lib\site-packages\twisted\internet\defer.py", line 310, in addCallbacks

File "lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 441, in _continueFiring

File "run_tribler.py", line 73, in start_tribler

File "Tribler\pyipv8\ipv8\util.py", line 14, in helper

File "Tribler\pyipv8\ipv8\util.py", line 26, in blockingCallFromThread

File "Tribler\Core\Session.py", line 479, in start

File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 222, in register

File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 403, in init

File "Tribler\pyipv8\ipv8\util.py", line 14, in helper

File "Tribler\pyipv8\ipv8\util.py", line 26, in blockingCallFromThread

File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 290, in load_ipv8_overlays

File "Tribler\community\market\community.py", line 176, in __init__

File "Tribler\community\market\community.py", line 228, in enable_matchmaker

File "Tribler\community\market\core\orderbook.py", line 385, in restore_from_database

File "Tribler\community\market\database.py", line 310, in get_ticks

File "Tribler\pyipv8\ipv8\database.py", line 41, in wrapper

File "Tribler\pyipv8\ipv8\database.py", line 305, in execute

sqlite3.OperationalError: no such table: ticks
```

I made some changes to the market community and updated the schema of the database that stores market information. I'm able to reproduce this error and found the bug. I will fix it as soon as I can.

To fix this, please remove the `market.db` file from the `sqlite` directory in the Tribler state directory. It will be recreated when you start Tribler. After that, Tribler should work again.
