### ISSUE TITLE
Error: 'NoneType' object has no attribute 'stop'

### ISSUE THREAD

**Issue by FFY00** [Tribler/tribler#3743]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

###### I tried with both versions
  - Tag: `v7.1.0-exp3`
  - Version (release.revision.commit): `7.1.0.exp3.r61.1ce64a526`
  - Latest version of the submodules

##### Operating system and version: #####
Arch Linux, up-to-date as of 14 Jul 2018 4pm.

##### Steps to reproduce the behavior: #####
Open tribler.

##### Expected behavior: #####
Sucessefully launch tribler

##### Actual behavior: #####
Says in the loading screen and I get the error below.

##### Relevant log file output: #####
  - `v7.1.0-exp3`
```
ERROR:root:Fault Handler module not found.
INFO    1531585449.98        single_application:23   (root)  __init__()
INFO    1531585450.04        single_application:49   (root)    self._outSocket.error() = '3'
INFO    1531585450.04        single_application:60   (root)  __init__(): returning
INFO    1531585450.55     event_request_manager:145  (TriblerGUI)  Will connect to events endpoint
INFO    1531585450.57     event_request_manager:51   (TriblerGUI)  Got Tribler core error: 1
INFO    1531585451.01                   backend:153  (keyring.backend)  Loading Gnome
INFO    1531585451.02                   backend:153  (keyring.backend)  Loading Google
INFO    1531585451.02                   backend:153  (keyring.backend)  Loading Windows (alt)
INFO    1531585451.02                   backend:153  (keyring.backend)  Loading file
INFO    1531585451.02                   backend:153  (keyring.backend)  Loading keyczar
INFO    1531585451.02                   backend:153  (keyring.backend)  Loading multi
INFO    1531585451.02                   backend:153  (keyring.backend)  Loading pyfs
INFO    1531585451.02                   backend:153  (keyring.backend)  Loading SecretService
INFO    1531585451.03                   backend:153  (keyring.backend)  Loading kwallet
INFO    1531585451.03                   backend:153  (keyring.backend)  Loading macOS
INFO    1531585451.03                   backend:153  (keyring.backend)  Loading windows
Traceback (most recent call last):
  File "run_tribler.py", line 63, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 22, in start_tribler_core
    from Tribler.Core.Session import Session
  File "/home/anubis/git/pkg/tribler/src/tribler/Tribler/Core/Session.py", line 20, in <module>
    from Tribler.Core.APIImplementation.LaunchManyCore import TriblerLaunchMany
  File "/home/anubis/git/pkg/tribler/src/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 28, in <module>
    from Tribler.Core.Video.VideoServer import VideoServer
  File "/home/anubis/git/pkg/tribler/src/tribler/Tribler/Core/Video/VideoServer.py", line 14, in <module>
    from cherrypy.lib.httputil import get_ranges
  File "/usr/lib/python2.7/site-packages/cherrypy/__init__.py", line 76, in <module>
    from . import _cprequest, _cpserver, _cptree, _cplogging, _cpconfig
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 8, in <module>
    from cherrypy.process.servers import ServerAdapter
  File "/usr/lib/python2.7/site-packages/cherrypy/process/__init__.py", line 14, in <module>
    from . import plugins, servers
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 126, in <module>
    import portend
  File "/usr/lib/python2.7/site-packages/portend.py", line 18, in <module>
    from tempora import timing
  File "/usr/lib/python2.7/site-packages/tempora/timing.py", line 137, in <module>
    class BackoffDelay(six.Iterator):
  File "/usr/lib/python2.7/site-packages/tempora/timing.py", line 225, in BackoffDelay
    @jaraco.functools.save_method_args
AttributeError: 'module' object has no attribute 'save_method_args'
ERROR   1531585455.04            tribler_window:89   (root)  Traceback (most recent call last):
  File "/home/anubis/git/pkg/tribler/src/tribler/TriblerGUI/tribler_window.py", line 847, in closeEvent
    self.close_tribler()
  File "/home/anubis/git/pkg/tribler/src/tribler/TriblerGUI/tribler_window.py", line 844, in close_tribler
    self.token_refresh_timer.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
```

  - `7.1.0.exp3.r61.1ce64a526`
```
ERROR:root:Fault Handler module not found.
INFO    1531585097.98        single_application:23   (root)  __init__()
INFO    1531585098.04        single_application:49   (root)    self._outSocket.error() = '3'
INFO    1531585098.04        single_application:60   (root)  __init__(): returning
INFO    1531585098.56     event_request_manager:145  (TriblerGUI)  Will connect to events endpoint
INFO    1531585098.58     event_request_manager:51   (TriblerGUI)  Got Tribler core error: 1
INFO    1531585099.16                   backend:153  (keyring.backend)  Loading Gnome
INFO    1531585099.18                   backend:153  (keyring.backend)  Loading Google
INFO    1531585099.18                   backend:153  (keyring.backend)  Loading Windows (alt)
INFO    1531585099.18                   backend:153  (keyring.backend)  Loading file
INFO    1531585099.18                   backend:153  (keyring.backend)  Loading keyczar
INFO    1531585099.18                   backend:153  (keyring.backend)  Loading multi
INFO    1531585099.18                   backend:153  (keyring.backend)  Loading pyfs
INFO    1531585099.18                   backend:153  (keyring.backend)  Loading SecretService
INFO    1531585099.20                   backend:153  (keyring.backend)  Loading kwallet
INFO    1531585099.20                   backend:153  (keyring.backend)  Loading macOS
INFO    1531585099.20                   backend:153  (keyring.backend)  Loading windows
Traceback (most recent call last):
  File "run_tribler.py", line 84, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 43, in start_tribler_core
    from Tribler.Core.Session import Session
  File "/home/anubis/git/tribler/Tribler/Core/Session.py", line 20, in <module>
    from Tribler.Core.APIImplementation.LaunchManyCore import TriblerLaunchMany
  File "/home/anubis/git/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 28, in <module>
    from Tribler.Core.Video.VideoServer import VideoServer
  File "/home/anubis/git/tribler/Tribler/Core/Video/VideoServer.py", line 14, in <module>
    from cherrypy.lib.httputil import get_ranges
  File "/usr/lib/python2.7/site-packages/cherrypy/__init__.py", line 76, in <module>
    from . import _cprequest, _cpserver, _cptree, _cplogging, _cpconfig
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 8, in <module>
    from cherrypy.process.servers import ServerAdapter
  File "/usr/lib/python2.7/site-packages/cherrypy/process/__init__.py", line 14, in <module>
    from . import plugins, servers
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 126, in <module>
    import portend
  File "/usr/lib/python2.7/site-packages/portend.py", line 18, in <module>
    from tempora import timing
  File "/usr/lib/python2.7/site-packages/tempora/timing.py", line 137, in <module>
    class BackoffDelay(six.Iterator):
  File "/usr/lib/python2.7/site-packages/tempora/timing.py", line 225, in BackoffDelay
    @jaraco.functools.save_method_args
AttributeError: 'module' object has no attribute 'save_method_args'
ERROR   1531585130.92            tribler_window:89   (root)  Traceback (most recent call last):
  File "/home/anubis/git/tribler/TriblerGUI/tribler_window.py", line 847, in closeEvent
    self.close_tribler()
  File "/home/anubis/git/tribler/TriblerGUI/tribler_window.py", line 844, in close_tribler
    self.token_refresh_timer.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
```

##### Note #####
It would be really helpful for packagers like me that you versioned the submodules. Having them pull the latest commit seems like a bad idea. I am interested to move Tribler to the official Arch Linux `community` repo but I need a bit more stability, and by this, I mean reproducible builds :smile:. It there any way I could contact you directly to talk about this? Perhaps IRC or Discord? Thanks in advance,

**Comment by devos50** [comment]
This bug seems to be Arch-specific, see https://bugs.archlinux.org/task/59311. This link also suggests a workaround: Install community/python-tempora 1.12. Does that help?

Regarding versioning of submodules, this is up to @qstokkink since he is the maintainer of the IPv8 package, which is a submodule of Tribler. The other submodule Tribler uses, Electrum, is already versioned.

You can contact us directly on our Freenode IRC channel #tribler. I'm always online in that channel to help users with questions. 👍

**Comment by FFY00** [comment]
Installing `python-tempora` does not to help. `python-jaraco` needs to be updated. I am gonna close this as it's none of your fault (sorry about that). I'll pop up by the IRC sometime.
