### ISSUE TITLE
Illegal config.spec

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3744]
The default value of `bootstrap_override` crashes Tribler on startup:

https://github.com/Tribler/tribler/blob/313b8050f882032e5be9bfa150de35df20bbe3be/Tribler/Core/Config/config.spec#L95

**Comment by qstokkink** [comment]
I have a valid bootstrap setting as follows:

```
[ipv8]
    bootstrap_override = ,
```

**Comment by qstokkink** [comment]
Empty string launches, but:

```python

ERROR   1531733769.82            tribler_window:89   (root)  Traceback (most recent call last):
  File "C:\Users\goqs\Documents\tribler\TriblerGUI\core_manager.py", line 114, in on_received_state
    raise RuntimeError(state['last_exception'])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 420, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 319, in addCallback
    callbackKeywords=kw)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 308, in addCallbacks
    self._runCallbacks()
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 433, in _continueFiring
    callable(*args, **kwargs)
  File "run_tribler.py", line 73, in start_tribler
    session.start()
  File "C:\Users\goqs\Documents\tribler\Tribler\pyipv8\ipv8\util.py", line 14, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "C:\Users\goqs\Documents\tribler\Tribler\pyipv8\ipv8\util.py", line 26, in blockingCallFromThread
    return f(*args, **kwargs)
  File "C:\Users\goqs\Documents\tribler\Tribler\Core\Session.py", line 479, in start
    startup_deferred = self.lm.register(self, self.session_lock)
  File "C:\Users\goqs\Documents\tribler\Tribler\Core\APIImplementation\LaunchManyCore.py", line 183, in register
    if self.session.config.get_ipv8_bootstrap_override():
  File "C:\Users\goqs\Documents\tribler\Tribler\Core\Config\tribler_config.py", line 296, in get_ipv8_bootstrap_override
    ip_port_tuple = (val[0], int(val[1])) if val else None
exceptions.IndexError: tuple index out of range
```

**Comment by qstokkink** [comment]
```
bootstrap_override = string(default='')
```

Seems to work.
