### ISSUE TITLE
Crash when updating torrent metainfo

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3819]
See the reporter:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 127, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
Tribler\Core\Libtorrent\LibtorrentMgr.py:591:_task_process_alerts
Tribler\Core\Libtorrent\LibtorrentMgr.py:539:got_metainfo
lib\site-packages\twisted\internet\defer.py:459:callback
lib\site-packages\twisted\internet\defer.py:567:_startRunCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\Modules\restapi\torrentinfo_endpoint.py:70:on_got_metainfo
Tribler\Core\CacheDB\SqliteCacheDBHandler.py:533:update_torrent_with_metainfo
Tribler\Core\CacheDB\SqliteCacheDBHandler.py:513:updateTorrent
Tribler\Core\CacheDB\sqlitecachedb.py:370:update
Tribler\Core\CacheDB\sqlitecachedb.py:326:execute_write
Tribler\pyipv8\ipv8\util.py:14:helper
Tribler\pyipv8\ipv8\util.py:26:blockingCallFromThread
Tribler\Core\CacheDB\sqlitecachedb.py:295:execute
].
```

It might be caused by the fact that we implicitly assume that the `num_seeders` and `num_leechers` field always contain integer values?

**Comment by qstokkink** [comment]
@devos50 `update_torrent_with_metainfo` does not pass `num_seeders` or `num_leechers` as keyword arguments:

https://github.com/Tribler/tribler/blob/0c1fdca39dee3b5a4666b183a72bd4e45c87d1c4/Tribler/Core/CacheDB/SqliteCacheDBHandler.py#L533

It also seems that the infohash is properly escaped:

https://github.com/Tribler/tribler/blob/0c1fdca39dee3b5a4666b183a72bd4e45c87d1c4/Tribler/Core/CacheDB/SqliteCacheDBHandler.py#L511

My guess would be that the `name` is not escaped to ASCII and instead is some unicode string.

**Comment by qstokkink** [comment]
Can reproduce in tests if I change the torrent name to `'\xc3Something awesome (2015)'`:

```python
 Traceback from the reactor's thread:
   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/quinten/Documents/tribler/Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py", line 190, in test_update_torrent_from_metainfo
    self.tdb.update_torrent_with_metainfo(infohash, metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 533, in update_torrent_with_metainfo
    self.updateTorrent(infohash, notify=False, name=name, num_files=num_files, length=length)
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 513, in updateTorrent
    self._db.update(self.table_name, where, **kw)
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 370, in update
    self.execute_write(sql, arg)
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 326, in execute_write
    self.execute(sql, args)
  File "/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/util.py", line 14, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/quinten/Documents/tribler/Tribler/pyipv8/ipv8/util.py", line 26, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 295, in execute
    raise msg
```
