### ISSUE TITLE
Issue with Tribler tunnel community

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3826]
```python
ERROR   1535358646.99                 community:680  (TriblerTunnelCommunity)  Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 677, in on_packet_from_circuit
    self.decode_map_private[data[22]](source_address, data, circuit_id)
  File "/home/sandip/tudelft/tribler/Tribler/community/triblertunnel/community.py", line 184, in on_balance_request_cell
    if request.should_forward:
AttributeError: 'NoneType' object has no attribute 'should_forward'
```

**Comment by devos50** [comment]
Probably happens between restarts of Tribler. adding a check whether the request exists should fix this issue 👍
