### ISSUE TITLE
Locale error in bitcoinlib

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3855]
```python
Traceback (most recent call last):
File "TriblerGUI/core_manager.py", line 114, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "twisted/internet/base.py", line 420, in fireEvent

File "twisted/internet/defer.py", line 319, in addCallback

File "twisted/internet/defer.py", line 308, in addCallbacks

File "twisted/internet/defer.py", line 651, in _runCallbacks

--- <exception caught here> ---
File "twisted/internet/base.py", line 433, in _continueFiring

File "run_tribler.py", line 73, in start_tribler

File "Tribler/pyipv8/ipv8/util.py", line 14, in helper

File "Tribler/pyipv8/ipv8/util.py", line 26, in blockingCallFromThread

File "Tribler/Core/Session.py", line 487, in start

File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 226, in register

File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 406, in init

File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module

File "Tribler/Core/Modules/wallet/btc_wallet.py", line 4, in <module>

File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module

File "bitcoinlib/__init__.py", line 20, in <module>

File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module

File "bitcoinlib/encoding.py", line 30, in <module>

File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module

File "bitcoinlib/main.py", line 52, in <module>

exceptions.EnvironmentError: Locale is currently set to 'US-ASCII'. This library needs the locale set to UTF-8 to function properly
```

**Comment by devos50** [comment]
On which machine did you see this?

It seems that this library really wants us to set the locale to `UTF-8`, which might not be the default setting on a machine.

**Comment by xoriole** [comment]
From reporter - Darwin-17.4.0-x86_64-i386-64bit
 [[2018-09-05]](http://reporter.tribler.org/crashreport_daily/2018-09-05) [#16006](http://reporter.tribler.org/stacktrace/16006)
