### ISSUE TITLE
Bitcoin wallet tests occasionally timing out on Mac

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3876]
From the test runner:

```
======================================================================
FAIL: Test the creating, opening, transactions and balance query of a Bitcoin (testnet) wallet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tribler/Documents/workspace2/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Test/test_as_server.py", line 56, in check
    result = fun(*argv, **kwargs)
  File "/Users/tribler/Documents/workspace2/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/pyipv8/ipv8/test/util.py", line 149, in wrapper
    % timeout)
TimeExpired: timeout expired before end of test (10.000000 s.)
-------------------- >> begin captured logging << --------------------
INFO    1536935166              db:bitcoinlib.db:35   Using Database /var/folders/3r/gp7dl3b92bq5cqzf0m1w4b3h0000gn/T/tmpJula2J_tribler_test_session/database/bitcoinlib.sqlite
INFO    1536935169      btc_wallet:BitcoinTestnetWallet:54   Creating wallet in /var/folders/3r/gp7dl3b92bq5cqzf0m1w4b3h0000gn/T/tmpJula2J_tribler_test_session
INFO    1536935169         wallets:bitcoinlib.wallets:789  Create new wallet 'tribler_testnet'
INFO    1536935170         wallets:bitcoinlib.wallets:1047 Opening wallet 'tribler_testnet'
INFO    1536935171         wallets:bitcoinlib.wallets:991  New key(s) created for parent_id 3
INFO    1536935171         wallets:bitcoinlib.wallets:991  New key(s) created for parent_id 4
INFO    1536935171         wallets:bitcoinlib.wallets:991  New key(s) created for parent_id 5
INFO    1536935172         wallets:bitcoinlib.wallets:991  New key(s) created for parent_id 6
INFO    1536935172         wallets:bitcoinlib.wallets:991  New key(s) created for parent_id 7
INFO    1536935173         wallets:bitcoinlib.wallets:991  New key(s) created for parent_id 8
INFO    1536935173              db:bitcoinlib.db:35   Using Database /var/folders/3r/gp7dl3b92bq5cqzf0m1w4b3h0000gn/T/tmpJula2J_tribler_test_session/database/bitcoinlib.sqlite
INFO    1536935173         wallets:bitcoinlib.wallets:1047 Opening wallet 'tribler_testnet'
WARNING 1536935173        services:bitcoinlib.services.services:152  bitcoind.testnet.gettransactions(([u'mvJZwx7eZM6ffvR5o7MvgeYGshi9G22S7k', u'mrWMZ4Dpdv2U9vqXWBogCJzoyse61Enqk3'],)) Error __init__() got an unexpected keyword argument 'strict'
DEBUG   1536935173      baseclient:bitcoinlib.services.baseclient:72   Url request https://testnet.bitgo.com/api/v1/address/mvJZwx7eZM6ffvR5o7MvgeYGshi9G22S7k/tx?skip=0&limit=100
DEBUG   1536935174  connectionpool:urllib3.connectionpool:818  Starting new HTTPS connection (1): testnet.bitgo.com
--------------------- >> end captured logging << ---------------------
```

It seems that these tests are initiating an HTTPS request to the 'outside world', even when opening the wallet initially. Also, there seems to be an error in the `gettransactions` but this is probably a bug inside `bitcoinlib` itself.

**Comment by ichorid** [comment]
@devos50, please check if https://github.com/Tribler/tribler/pull/3874 solves this problem

**Comment by devos50** [comment]
#3874 does not solve this issue. It is caused by something else, namely the fact that bitcoinlib is doing requests when initializing a wallet (which I did not expect). If for some reason the external API is slow with responding, the test timeout might trigger. On my machine, I got the duration of these tests close to 8 seconds when blocking the HTTP requests to the Bitcoin APIs.
