### ISSUE TITLE
Tribler search errors out on non-ASCII characters

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#3890]
Version: next, devel.
Steps to reproduce the problem: insert some non-ASCII string (e.g. "всем привет!") in Tribler GUI search field and press "Enter".

Error:
```python
Traceback (most recent call last):
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/web/server.py", line 198, in process
    self.render(resrc)
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/web/server.py", line 258, in render
    body = resrc.render(self)
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/tmp/triblerTribler/Core/Modules/restapi/search_endpoint.py", line 84, in render_GET
    self.session.search_remote_torrents(keywords)
  File "/tmp/triblerTribler/Core/Session.py", line 684, in search_remote_torrents
    return self.lm.search_manager.search_for_torrents(keywords)
  File "/tmp/triblerTribler/pyipv8/ipv8/util.py", line 14, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/tmp/triblerTribler/pyipv8/ipv8/util.py", line 26, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/tmp/triblerTribler/Core/Modules/search_manager.py", line 61, in search_for_torrents
    self.session.lm.popularity_community.send_torrent_search_request(keywords)
  File "/tmp/triblerTribler/community/popularity/community.py", line 265, in send_torrent_search_request
    self.send_content_info_request(SEARCH_TORRENT_REQUEST, query)
  File "/tmp/triblerTribler/community/popularity/community.py", line 228, in send_content_info_request
    packet = self.create_message_packet(MSG_CONTENT_INFO_REQUEST, content_request)
  File "/tmp/triblerTribler/community/popularity/pubsub.py", line 188, in create_message_packet
    payload = payload if isinstance(payload, list) else payload.to_pack_list()
  File "/tmp/triblerTribler/community/popularity/payload.py", line 273, in to_pack_list
    ('varlenH', encode_values(self.query_list)),
  File "/tmp/triblerTribler/community/popularity/payload.py", line 8, in encode_values
    return ''.join([pack('!H', len(value)) + str(value) for value in values])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
```

**Comment by ichorid** [comment]
Seems like we are not applying 'unicode sandwich' ideology in Tribler project. 
Everything that goes in should be decoded to unicode. Everything that goes out should be converted to UTF-8.

**Comment by ichorid** [comment]
Basically, every test string in our test base should include some non-ASCII characters. That's a big undertaking on its own.
