### ISSUE TITLE
UDPEndpoint is unexpectedly closed

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3905]
Tribler 7.1.0-rc1  - [[#16554](http://reporter.tribler.org/stacktrace/16554)         of [2018-09-24](http://reporter.tribler.org/crashreport_daily/2018-09-24)]
Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic 
Up time: 41049.2412751
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 130, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "run_tribler.py", line 84, in <module>
start_tribler_core(base_path, api_port)
File "run_tribler.py", line 76, in start_tribler_core
reactor.run()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1243, in run
self.mainLoop()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1252, in mainLoop
self.runUntilCurrent()
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 878, in runUntilCurrent
call.func(*call.args, **call.kw)
File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 267, in do_check
tunnel_community.build_tunnels(self.get_hops())
File "/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 220, in build_tunnels
self.do_circuits()
File "/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 197, in do_circuits
if not self.create_circuit(circuit_length):
File "/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 317, in create_circuit
circuit.unverified_hop.dh_first_part)))
File "/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 474, in send_cell
return self.send_message(candidates, message_type, packet, circuit_id if circuit_id else payload.circuit_id)
File "/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 493, in send_message
return self.send_packet(candidates, message_type, packet)
File "/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 498, in send_packet
self.endpoint.send(address, packet)
File "/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/interfaces/udp/endpoint.py", line 39, in send
self.assert_open()
File "/usr/share/tribler/Tribler/pyipv8/ipv8/messaging/interfaces/udp/endpoint.py", line 71, in assert_open
raise EndpointClosedException(self)
Tribler.pyipv8.ipv8.messaging.interfaces.endpoint.EndpointClosedException: <class 'Tribler.pyipv8.ipv8.messaging.interfaces.udp.endpoint.UDPEndpoint'> is unexpectedly closed
```

**Comment by qstokkink** [comment]
https://github.com/Tribler/tribler/blob/67b3fd92e500700fea44f3e67da2bc920ae709dd/Tribler/Core/APIImplementation/LaunchManyCore.py#L934-L950

I'm guessing data is trying to go out while Dispersy has already closed the Endpoint. We should probably not crash on this though.

**Comment by qstokkink** [comment]
Nope that wasn't it. You then simply get a lot of:

```
INFO    1538052971.94                  dispersy:989  (Dispersy)  dropping 1 packets as dispersy is not running
```

In retrospect, if we look at the stack trace, you can see that IPv8 owns the endpoint.
