### ISSUE TITLE
SqliteCacheDBHandler errors running latest next

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3910]
```
ERROR   1538052531.49      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance "\xf1\xb6\x86\xc1Q:'\xfc\xc5\x8c\xa7k\xc6(^\x16\x83\x11J0" 1481712438 u'100 Balls - Android.apk' ((u'100 Balls - Android.apk', 27350000L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144390}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.52      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\xb7>\n\xf4\t*\xc6\xa16U\x81<W2\x14\xd7\xd3g\x06\x8e' 1481712441 u'10000000 - Android.apk' ((u'10000000 - Android.apk', 16168078L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144391}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.52      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\xcf\x85\xfe\xe4-\xeeO&\t "C\xa8\xd7\x148\x16\xcbU\xd3' 1481712590 u'Cars And Guns 3D - Android.apk' ((u'Cars And Guns 3D - Android.apk', 27415589L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144392}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.52      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance 'nj\x97\xc7R\xb6\xe0\x9b\x1cgK\xdc\xf9\xff\xfa\xa5\xe9i\x13\xf5' 1481712684 u'com.bowengames.pullingusa.apk' ((u'com.bowengames.pullingusa.apk', 45754844L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144393}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.52      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\xb73\xfc\xf8\xd4\x8f\x92R\x01\x08\x82\t\xa0\xc7"\n\x81\xba\xd1q' 1481712833 u'com.inknippon.paidthemansionofmenace.apk' ((u'com.inknippon.paidthemansionofmenace.apk', 51495590L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144394}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '^\xc1\x89\xe0\x88\x80\xe4v\xfc\xfdL\xc5\x995\xd5;\xb2\x16\xb3\xfa' 1481712867 u'com.littleinferno.google.apk' ((u'com.littleinferno.google.apk', 15313787L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144395}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\x1f\nC\xc3S3c\xf5\xc7\xf9\xb7\xd09\xcc\no\xa7\xa966' 1481712875 u'com.mageeks.android.pro.militarytruck.apk' ((u'com.mageeks.android.pro.militarytruck.apk', 31862990L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144396}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance 'r\xa2T\x12j~\xbdur\xa9L\xden7\xc5\x0e\xa2\xc0\xe0\xd8' 1481712887 u'com.microids.HdOv25.HdO20000Leagues.freemium.apk' ((u'com.microids.HdOv25.HdO20000Leagues.freemium.apk', 5098153L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144397}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\n\xeb\x11k/\xdd&\xc7\x98\xd49\x06\xc1j\xed\xaab\xd5\xe6\x86' 1481713043 u'com.volcanodiscovery.upgrade.apk' ((u'com.volcanodiscovery.upgrade.apk', 319352L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144398}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\xf2\xff:\xabH\xb1b\xb8\xc2\xaf\xf45\x88EO\xcd\xc5.\xb4A' 1481713231 u'Iron Fist Boxing - Android.apk' ((u'Iron Fist Boxing - Android.apk', 2545399L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144399}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '?\xff\xe3\x00G\x03e6\xca\xb9\xcdI\x06\x8e\x1aQ\x0e\xd6\xaa\x8f' 1481713358 u'org.dmfs.caldav.lib.apk' ((u'org.dmfs.caldav.lib.apk', 1411880L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144400}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\xab\xee\x1ba\xd9\x10Gj\x15\xba&\xf9\xb3\xdf\xd5w\x17\xa2d\x11' 1481713502 u'Tangram Pro - Android.apk' ((u'Tangram Pro - Android.apk', 1491403L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144401}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\xe7\xa3\xcc\xe5\xc9\x8e\x10\xce3\xb9I\x9a/G\xa4_\x936\x9b\x81' 1481713509 u'The End Run Mayan Apocalypse - Android.apk' ((u'The End Run Mayan Apocalypse - Android.apk', 5721967L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144402}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance "M\xaf\x08\xddG\x85\xfa.<r\xd78\x8a\xc0\xf3\xce9'\x87i" 1481713602 u'The Graveyard - Android.apk' ((u'The Graveyard - Android.apk', 19118335L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144403}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
ERROR   1538052531.53      SqliteCacheDBHandler:356  (TorrentDBHandler)  Could not create a TorrentDef instance '\x9a!\x80\xadL\xb8\xa4\xe7\xa9\x19\xf41U\x04\xe5\xe3\x11\x8f\xde\r' 1481713604 u'The Great Fusion - Android.apk' ((u'The Great Fusion - Android.apk', 41314399L),) ('http://tracker.thepiratebay.org:80/announce udp://tracker.thepiratebay.org:80/announce',) {'dispersy_id': 144404}
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 344, in addExternalTorrentNoDef
    torrentdef = TorrentDef.load_from_dict(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 191, in load_from_dict
    return TorrentDef._create(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/TorrentDef.py", line 144, in _create
    metainfo_fixed = create_valid_metainfo(metainfo)
  File "/home/quinten/Documents/tribler/Tribler/Core/Utilities/utilities.py", line 275, in create_valid_metainfo
    raise ValueError('announce URL bad')
ValueError: announce URL bad
```

**Comment by qstokkink** [comment]
Only looks like a bug because we print the entire stacktrace.
