### ISSUE TITLE
Plyvel IOError: Could not create random access file

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3955]
From error reporter ( [ #16931](http://reporter.tribler.org/stacktrace/16931)) - Tribler 7.1.0  
Date: [2018-10-10](http://reporter.tribler.org/crashreport_daily/2018-10-10)

platform	Windows-10-10.0.17134-SP0 (AMD64)
python	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
tribler_uptime	294.606999874

Stacktrace:
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'plyvel._plyvel.IOError'>: IO error: C:\Users\Blake\AppData\Roaming\.Tribler\collected_torrents\000263.ldb: Could not create random access file.
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\Core\leveldbstore.py:141:flush
Tribler\Core\plyveladapter.py:25:Write
plyvel\_plyvel.pyx:599:plyvel._plyvel.WriteBatch.write (plyvel/_plyvel.cpp:9519)
plyvel\_plyvel.pyx:80:plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1689)
]
```

**Comment by xoriole** [comment]
More LevelDB errors for Tribler v7.1.2
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'plyvel._plyvel.CorruptionError'>: Corruption: corrupted compressed block contents
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\Core\leveldbstore.py:141:flush
Tribler\Core\plyveladapter.py:25:Write
plyvel\_plyvel.pyx:599:plyvel._plyvel.WriteBatch.write (plyvel/_plyvel.cpp:9519)
plyvel\_plyvel.pyx:83:plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1749)
]
```

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'plyvel._plyvel.CorruptionError'>: Corruption: bad entry in block
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\Core\leveldbstore.py:141:flush
Tribler\Core\plyveladapter.py:25:Write
plyvel\_plyvel.pyx:599:plyvel._plyvel.WriteBatch.write (plyvel/_plyvel.cpp:9519)
plyvel\_plyvel.pyx:83:plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1749)
]
```

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'plyvel._plyvel.IOError'>: IO error: WinMmapFile.Append::UnmapCurrentRegion or MapNewRegion: : Acceso denegado.

lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\Core\leveldbstore.py:141:flush
Tribler\Core\plyveladapter.py:25:Write
plyvel\_plyvel.pyx:599:plyvel._plyvel.WriteBatch.write (plyvel/_plyvel.cpp:9519)
plyvel\_plyvel.pyx:80:plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1689)
]
```

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'plyvel._plyvel.IOError'>: IO error: WinMmapFile.Sync::FlushFileBuffers: : The request could not be performed because of an I/O device error.

lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\Core\leveldbstore.py:141:flush
Tribler\Core\plyveladapter.py:25:Write
plyvel\_plyvel.pyx:599:plyvel._plyvel.WriteBatch.write (plyvel/_plyvel.cpp:9519)
plyvel\_plyvel.pyx:80:plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1689)
]
```
These are either IOError or CorruptionError in Windows 10. The cause of this error is still unknown. 
Comment in one of the report:
> just stopped working [(#17961)](http://reporter.tribler.org/stacktrace/17961)

**Comment by xoriole** [comment]
Apparently, this issue has been for quite a long time.
https://github.com/Tribler/tribler/issues/1837
