### ISSUE TITLE
Socket error 10053 - connection aborted by the software

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3958]
Socket error 10053 - connection aborted by the software. Unlike other socket error, we should try to recover from this one by attempting to re-establish the connection.
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "run_tribler.py", line 84, in <module>

File "run_tribler.py", line 76, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1243, in run

File "lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent

File "Tribler\pyipv8\ipv8\messaging\interfaces\endpoint.py", line 44, in _deliver_later

File "Tribler\dispersy\endpoint.py", line 470, in on_packet

File "Tribler\dispersy\endpoint.py", line 493, in data_came_in

File "lib\site-packages\twisted\internet\base.py", line 997, in callFromThread

File "lib\site-packages\twisted\internet\base.py", line 566, in wakeUp

File "lib\site-packages\twisted\internet\posixbase.py", line 91, in wakeUp

File "lib\site-packages\twisted\python\util.py", line 815, in untilConcludes

socket.error: [Errno 10053] De software op uw hostcomputer heeft een verbinding verbroken
```

**Comment by xoriole** [comment]
This is windows specific error. Possible reasons:
- An established connection was aborted by the software in your host machine.
- The TCP/IP Connection was aborted by Windows. This was possibly due to a data transmission timeout or protocol error.
- The virtual circuit was terminated due to a time-out or other failure. The application should close the socket as it is no longer usable.

[Reference](https://wiki.pscs.co.uk/how_to:10053)
