### ISSUE TITLE
"The Volume must be a valid whole number."

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3959]
Why is the minimum BTC buy is $6,219 USD  (1 BTC)?

also "float division by zero" if any sane rate is used BTC/MB=0.0001

**Comment by devos50** [comment]
The GUI should be able to deal with floating point numbers. Thanks for reporting this, I will check it out!

**Comment by xoriole** [comment]
Reported stacktrace
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/widgets/marketpage.py", line 181, in on_received_bids
self.update_filter_bids_list()
File "/usr/share/tribler/TriblerGUI/widgets/marketpage.py", line 197, in update_filter_bids_list
self.create_widget_item_from_tick(self.window().bids_list, bid, is_ask=False))
File "/usr/share/tribler/TriblerGUI/widgets/marketpage.py", line 143, in create_widget_item_from_tick
return TickWidgetItem(tick_list, tick, asset1_prec, asset2_prec)
File "/usr/share/tribler/TriblerGUI/widgets/tickwidgetitem.py", line 17, in __init__
self.price = float(self.total_volume) / float(prec_div(tick["assets"]["second"]["amount"], asset2_prec))
ZeroDivisionError: float division by zero
```
