### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3968]
From error reporter - Tribler 7.1.0
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\homepage.py", line 89, in received_popular_torrents
File "TriblerGUI\widgets\home_recommended_item.py", line 83, in update_with_torrent
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by xoriole** [comment]
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\homepage.py", line 89, in received_popular_torrents
File "TriblerGUI\widgets\home_recommended_item.py", line 85, in update_with_torrent
AttributeError: 'NoneType' object has no attribute 'lower'
```
Still prevalent in v7.1.2. The actual cause seems to be category not set in the json results instead of no results.

**Comment by xoriole** [comment]
PR https://github.com/Tribler/tribler/pull/4019 addresses this issue along with other similar NoneType issues. Closing this issue here.
