### ISSUE TITLE
Error in latest devel

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3980]
No longer works out of the box (without channel 2.0 enabled).
When creating My Channel (When clicking `Create Channel`):

```python
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 198, in process
    self.render(resrc)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 258, in render
    body = resrc.render(self)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/channels/channels_discovered_endpoint.py", line 128, in render_PUT
    channel_id = self.session.create_channel(unicode(parameters['name'][0], 'utf-8'), description, mode)
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 720, in create_channel
    return self.lm.channel_manager.create_channel(name, description, mode)
AttributeError: 'NoneType' object has no attribute 'create_channel'
```

![afbeelding](https://user-images.githubusercontent.com/3630389/47485005-7b6ac680-d83d-11e8-94e7-c3547c485d64.png)

**Comment by ichorid** [comment]
closed for the same reason as https://github.com/Tribler/tribler/issues/3981
