### ISSUE TITLE
Crash when committing new channel torrent

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3981]
When clicking `Apply Changes` (with channel 2.0 enabled):

```python
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 198, in process
    self.render(resrc)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 258, in render
    body = resrc.render(self)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/channels/my_channel_endpoint.py", line 125, in render_POST
    self.session.lm.updated_my_channel(torrent_path)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 562, in updated_my_channel
    self.add(tdef, dcfg)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 615, in add
    self.rtorrent_handler.save_torrent(tdef, write_my_pref)
  File "/home/quinten/Documents/tribler/Tribler/Core/RemoteTorrentHandler.py", line 159, in save_torrent
    if self.torrent_db.hasTorrent(infohash):
AttributeError: 'NoneType' object has no attribute 'hasTorrent'
```

![afbeelding](https://user-images.githubusercontent.com/3630389/47487177-3a28e580-d842-11e8-8144-c22a3f99bad4.png)

**Comment by ichorid** [comment]
You had Dispersy disabled in your config file. At this moment GigaChannel is not ready yet to run without Dispersy.
