### ISSUE TITLE
exceptions.TypeError: ord() expected a character, but string of length 0 found

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3987]
From error reporter - Tribler 7.1.2

Platform: Windows-10-10.0.17134-SP0 (AMD64)
Uptime:	25.1840000153

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "run_tribler.py", line 86, in <module>

File "run_tribler.py", line 78, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1243, in run

File "lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent

File "Tribler\dispersy\endpoint.py", line 512, in dispersythread_data_came_in

File "Tribler\dispersy\dispersy.py", line 979, in on_incoming_packets

File "Tribler\dispersy\community.py", line 2028, in on_incoming_packets

File "Tribler\dispersy\community.py", line 2085, in _on_batch_cache

File "Tribler\dispersy\util.py", line 150, in wrapper

File "Tribler\dispersy\conversion.py", line 1251, in decode_message

File "Tribler\community\search\conversion.py", line 130, in _decode_search_response

File "Tribler\pyipv8\ipv8\messaging\deprecated\encoding.py", line 355, in decode

File "Tribler\pyipv8\ipv8\messaging\deprecated\encoding.py", line 271, in _a_decode_tuple

File "Tribler\pyipv8\ipv8\messaging\deprecated\encoding.py", line 237, in _a_decode_list

File "Tribler\pyipv8\ipv8\messaging\deprecated\encoding.py", line 269, in _a_decode_tuple

exceptions.TypeError: ord() expected a character, but string of length 0 found
```

**Comment by qstokkink** [comment]
Hmm.. we should probably add a general `try` `except` in `File "Tribler\dispersy\endpoint.py", line 512, in dispersythread_data_came_in`.

**Comment by qstokkink** [comment]
As `7.2` will be a Dispersy-less release, this will no longer be an issue.
