### ISSUE TITLE
Error in market order page: ZeroDivisionError

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3993]
From error reporter - Tribler [[#17729]](http://reporter.tribler.org/stacktrace/17729)

```python
Traceback (most recent call last):
File "TriblerGUI\widgets\marketorderspage.py", line 51, in on_received_orders
File "TriblerGUI\widgets\orderwidgetitem.py", line 18, in __init__
ZeroDivisionError: float division by zero
```

**Comment by xoriole** [comment]
Fixed by #4019
