### ISSUE TITLE
Tribler not starting with latest bitcoinlib version

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4001]
When using bitcoinlib `0.4.1`:

```
ERROR   1541154665.35            tribler_window:83   (root)  Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/TriblerGUI/core_manager.py", line 114, in on_received_state
    raise RuntimeError(state['last_exception'])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(*args, **kwargs)
  File "run_tribler.py", line 75, in start_tribler
    session.start()
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 486, in start
    startup_deferred = self.lm.register(self, self.session_lock)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 234, in register
    self.init()
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 418, in init
    btc_wallet = BitcoinWallet(wallet_path)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/wallet/btc_wallet.py", line 28, in __init__
    from bitcoinlib.wallets import wallet_exists, HDWallet
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/__init__.py", line 21, in <module>
    import bitcoinlib.mnemonic
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/mnemonic.py", line 26, in <module>
    class Mnemonic:
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/mnemonic.py", line 35, in Mnemonic
    def __init__(self, language=DEFAULT_LANGUAGE):
exceptions.NameError: name 'DEFAULT_LANGUAGE' is not defined
```

After downgrading to `0.3.37` it works.

**Comment by devos50** [comment]
Adding `DEFAULT_LANGUAGE='english'` to https://github.com/Tribler/tribler/blob/next/Tribler/Core/Modules/bitcoinlib_main.py should fix this.

**Comment by qstokkink** [comment]
New error with that fix:

```
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(*args, **kwargs)
  File "run_tribler.py", line 75, in start_tribler
    session.start()
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 486, in start
    startup_deferred = self.lm.register(self, self.session_lock)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 234, in register
    self.init()
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 418, in init
    btc_wallet = BitcoinWallet(wallet_path)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/wallet/btc_wallet.py", line 28, in __init__
    from bitcoinlib.wallets import wallet_exists, HDWallet
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/__init__.py", line 22, in <module>
    import bitcoinlib.keys
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/keys.py", line 34, in <module>
    from bitcoinlib.networks import Network, DEFAULT_NETWORK, network_by_value
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/networks.py", line 143, in <module>
    class Network:
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/networks.py", line 152, in Network
    def __init__(self, network_name=DEFAULT_NETWORK):
exceptions.NameError: name 'DEFAULT_NETWORK' is not defined
```

**Comment by qstokkink** [comment]
Added `DEFAULT_NETWORK = 'bitcoin'`, now:

```
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(*args, **kwargs)
  File "run_tribler.py", line 75, in start_tribler
    session.start()
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 486, in start
    startup_deferred = self.lm.register(self, self.session_lock)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 234, in register
    self.init()
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 418, in init
    btc_wallet = BitcoinWallet(wallet_path)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/wallet/btc_wallet.py", line 28, in __init__
    from bitcoinlib.wallets import wallet_exists, HDWallet
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/__init__.py", line 23, in <module>
    import bitcoinlib.transactions
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/transactions.py", line 617, in <module>
    class Input:
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/transactions.py", line 829, in Input
    def update_scripts(self, hash_type=SIGHASH_ALL, recreate_all=False):
exceptions.NameError: name 'SIGHASH_ALL' is not defined
```

**Comment by qstokkink** [comment]
Copied over all fields, now this:

```
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(*args, **kwargs)
  File "run_tribler.py", line 75, in start_tribler
    session.start()
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 486, in start
    startup_deferred = self.lm.register(self, self.session_lock)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 234, in register
    self.init()
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 418, in init
    btc_wallet = BitcoinWallet(wallet_path)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/wallet/btc_wallet.py", line 38, in __init__
    if wallet_exists(self.wallet_name, databasefile=self.db_path):
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/wallets.py", line 92, in wallet_exists
    if wallet in [x['name'] for x in wallets_list(databasefile)]:
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/wallets.py", line 63, in wallets_list
    wallets = session.query(DbWallet).all()
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2737, in all
    return list(self)
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/quinten/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: wallets.witness_type [SQL: u'SELECT wallets.id AS wallets_id, wallets.name AS wallets_name, wallets.owner AS wallets_owner, wallets.network_name AS wallets_network_name, wallets.purpose AS wallets_purpose, wallets.scheme AS wallets_scheme, wallets.witness_type AS wallets_witness_type, wallets.encoding AS wallets_encoding, wallets.main_key_id AS wallets_main_key_id, wallets.multisig_n_required AS wallets_multisig_n_required, wallets.sort_keys AS wallets_sort_keys, wallets.parent_id AS wallets_parent_id, wallets_1.id AS wallets_1_id, wallets_1.name AS wallets_1_name, wallets_1.owner AS wallets_1_owner, wallets_1.network_name AS wallets_1_network_name, wallets_1.purpose AS wallets_1_purpose, wallets_1.scheme AS wallets_1_scheme, wallets_1.witness_type AS wallets_1_witness_type, wallets_1.encoding AS wallets_1_encoding, wallets_1.main_key_id AS wallets_1_main_key_id, wallets_1.multisig_n_required AS wallets_1_multisig_n_required, wallets_1.sort_keys AS wallets_1_sort_keys, wallets_1.parent_id AS wallets_1_parent_id, wallets_2.id AS wallets_2_id, wallets_2.name AS wallets_2_name, wallets_2.owner AS wallets_2_owner, wallets_2.network_name AS wallets_2_network_name, wallets_2.purpose AS wallets_2_purpose, wallets_2.scheme AS wallets_2_scheme, wallets_2.witness_type AS wallets_2_witness_type, wallets_2.encoding AS wallets_2_encoding, wallets_2.main_key_id AS wallets_2_main_key_id, wallets_2.multisig_n_required AS wallets_2_multisig_n_required, wallets_2.sort_keys AS wallets_2_sort_keys, wallets_2.parent_id AS wallets_2_parent_id \nFROM wallets LEFT OUTER JOIN wallets AS wallets_2 ON wallets.id = wallets_2.parent_id LEFT OUTER JOIN wallets AS wallets_1 ON wallets_2.id = wallets_1.parent_id'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by devos50** [comment]
What if you remove the bitcoinlib database? Does the error persist?

**Comment by qstokkink** [comment]
Found it, the schema of `wallets.db` changed. Removing that file solved this.

**Comment by qstokkink** [comment]
I'm not sure what to do with the `wallets.db` issue, unassigning myself.
