### ISSUE TITLE
Deployment tests failing on Devel

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4004]
Deployment test is failing with the following error.
We'll most likely need to update PyInstaller spec to fix it.
```python
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "twisted/internet/base.py", line 420, in fireEvent
    
  File "twisted/internet/defer.py", line 319, in addCallback
    
  File "twisted/internet/defer.py", line 308, in addCallbacks
    
  File "twisted/internet/defer.py", line 651, in _runCallbacks
    
--- <exception caught here> ---
  File "twisted/internet/base.py", line 433, in _continueFiring
    
  File "run_tribler.py", line 75, in start_tribler
    
  File "Tribler/Core/Session.py", line 486, in start
    
  File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 234, in register
    
  File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 493, in init
    
  File "Tribler/Core/Modules/MetadataStore/store.py", line 75, in __init__
    
  File "pony/orm/core.py", line 698, in bind
    
  File "pony/orm/core.py", line 713, in _bind
    
  File "pony/utils/utils.py", line 219, in import_module
    
exceptions.ImportError: No module named dbproviders.sqlite
```

**Comment by xoriole** [comment]
PR #4006 fixes the issue with Pony and deployment tests pass for all 64bit machines but there seems to be an another issue with vlc plugins causing deployment tests to fail 32 bit windows.
```
[0061fd38] main libvlc error: stale plugins cache: modified C:\Program Files\Tribler\VLC\plugins\access\libaccess_concat_plugin.dll
[0061fd38] main libvlc error: stale plugins cache: modified C:\Program Files\Tribler\VLC\plugins\access\libaccess_imem_plugin.dll
...
[0061fd38] main libvlc error: stale plugins cache: modified C:\Program Files\Tribler\VLC\plugins\video_output\libwgl_plugin.dll
[0061fd38] main libvlc error: stale plugins cache: modified C:\Program Files\Tribler\VLC\plugins\video_output\libwingdi_plugin.dll
```

**Comment by xoriole** [comment]
Deployment tests on Win32 bit machines are failing:
```python
Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 417, in fireEvent
    
  File "lib\site-packages\twisted\internet\defer.py", line 317, in addCallback
    
  File "lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
    
  File "lib\site-packages\twisted\internet\defer.py", line 649, in _runCallbacks
    
--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring
    
  File "run_tribler.py", line 75, in start_tribler
    
  File "Tribler\Core\Session.py", line 486, in start
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 234, in register
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 493, in init
    
  File "Tribler\Core\Modules\MetadataStore\store.py", line 78, in __init__
    
  File "lib\site-packages\pony\orm\core.py", line 788, in execute
    
  File "lib\site-packages\pony\orm\core.py", line 800, in _exec_raw_sql
    
  File "lib\site-packages\pony\orm\core.py", line 863, in _exec_sql
    
  File "lib\site-packages\pony\orm\core.py", line 1686, in reconnect
    
  File "lib\site-packages\pony\orm\core.py", line 861, in _exec_sql
    
  File "<auto generated wrapper of execute() function>", line 2, in execute
    
  File "lib\site-packages\pony\orm\dbapiprovider.py", line 61, in wrap_dbapi_exceptions
    
pony.orm.dbapiprovider.OperationalError: near "NOT": syntax error
```

**Comment by xoriole** [comment]
The issue with pony is resolved and the deployment tests on devel are stable so I'm closing this issue.
