### ISSUE TITLE
OverflowError: bad numeric conversion: positive overflow

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4007]
From error reporter - Tribler v7.1.2

Platform: Linux-4.15.0-34-generic-x86_64-with-LinuxMint-18.3-sylvia
Uptime:	7.4413869381 sec

```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 130, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "run_tribler.py", line 86, in <module>
start_tribler_core(base_path, api_port)
File "run_tribler.py", line 78, in start_tribler_core
reactor.run()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
self.mainLoop()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
self.runUntilCurrent()
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
call.func(*call.args, **call.kw)
File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 229, in schedule_create_engine
checkpoint_disabled=checkpoint_disabled)
File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 354, in network_create_engine_wrapper
return self.ltmgr.add_torrent(self, atp).addCallbacks(on_torrent_added, on_torrent_failed)
File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 312, in add_torrent
ltsession = self.get_session(atp.pop('hops', 0))
File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 230, in get_session
self.ltsessions[hops] = self.create_session(hops)
File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 217, in create_session
ltsession.set_settings(ltsession_settings)
exceptions.OverflowError: bad numeric conversion: positive overflow
```

**Comment by xoriole** [comment]
I haven't seent this issue in the newer version and we have updated libtorrent as well so I'm closing this issue for now. If this issue is reported further in the future we should investigate more.
