### ISSUE TITLE
Some random GUI errors

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4018]
Some random GUI errors - Tribler v7.1.2

**Issue 1**
```python
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 655, in on_start_download_action
AttributeError: 'NoneType' object has no attribute 'request_mgr'
```

**Issue 2**
```python
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 681, in on_confirm_add_directory_dialog
File "lib\nturl2path.py", line 67, in pathname2url
File "lib\urllib.py", line 1299, in quote
KeyError: u'\u0418'
```

**Issue 3**
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\downloadspage.py", line 334, in on_remove_download_dialog
AttributeError: 'NoneType' object has no attribute 'close_dialog'
```

**Issue 4**
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/widgets/settingspage.py", line 165, in on_use_monochrome_icon_checkbox_changed
self.window().update_tray_icon(use_monochrome_icon)
File "/usr/share/tribler/TriblerGUI/tribler_window.py", line 277, in update_tray_icon
self.tray_icon.setIcon(QIcon(QPixmap(get_image_path('monochrome_tribler.png'))))
AttributeError: 'NoneType' object has no attribute 'setIcon'
```

**Issue 5**
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\downloadwidgetitem.py", line 86, in __lt__
AttributeError: 'QTreeWidgetItem' object has no attribute 'download_info'
```

**Issue 6**
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\homepage.py", line 89, in received_popular_torrents
File "TriblerGUI\widgets\home_recommended_item.py", line 85, in update_with_torrent
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Issue 7**
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\marketorderspage.py", line 51, in on_received_orders
File "TriblerGUI\widgets\orderwidgetitem.py", line 18, in __init__
ZeroDivisionError: float division by zero
```

**Issue 8**
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get_state'
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\Core\CreditMining\CreditMiningManager.py:272:select_torrents
]
```

**Issue 9**
```python
Traceback (most recent call last):
File "TriblerGUI\dialogs\startdownloaddialog.py", line 133, in on_received_metainfo
AttributeError: 'NoneType' object has no attribute 'dialog_widget'
```

**Issue 10**
```python
Traceback (most recent call last):
File "TriblerGUI\core_manager.py", line 101, in on_received_state
KeyError: 'state'
```

**Comment by xoriole** [comment]
Fixed in #4019
