### ISSUE TITLE
UnicodeDecodeError in REST endpoints

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4022]
From error reporter - Tribler v7.1.2
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.UnicodeDecodeError'>: 'utf8' codec can't decode byte 0x75 in position 33: could not dump:
dict[error]->str::'TCP connection timed out: 10060: \x90...\xc5\
lib\site-packages\twisted\internet\base.py:1080:connectionFailed
lib\site-packages\twisted\internet\endpoints.py:246:clientConnectionFailed
lib\site-packages\twisted\internet\defer.py:496:errback
lib\site-packages\twisted\internet\defer.py:563:_startRunCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:649:_runCallbacks
Tribler\Core\Modules\restapi\torrentinfo_endpoint.py:93:on_lookup_error
Tribler\Core\Utilities\json_util.py:100:dumps
]
```
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.UnicodeDecodeError'>: 'utf8' codec can't decode byte 0x75 in position 33: could not dump:
dict[error]->str::'TCP connection timed out: 10060: \x90\...\xc5\
lib\site-packages\twisted\internet\base.py:1080:connectionFailed
lib\site-packages\twisted\internet\endpoints.py:246:clientConnectionFailed
lib\site-packages\twisted\internet\defer.py:496:errback
lib\site-packages\twisted\internet\defer.py:563:_startRunCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:649:_runCallbacks
Tribler\Core\Modules\restapi\downloads_endpoint.py:304:on_error
Tribler\Core\Utilities\json_util.py:100:dumps
]
```

The issue seems to be 
>request.write(json.dumps({"error": failure.getErrorMessage()}))

**Comment by xoriole** [comment]
Fixed by #4036
