### ISSUE TITLE
Error in OrmBindings

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4023]
While running latest devel:

```python
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 198, in process
    self.render(resrc)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 258, in render
    body = resrc.render(self)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/torrents_endpoint.py", line 319, in render_GET
    magnet = torrent_md.get_magnet()
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py", line 22, in get_magnet
    (str(self.infohash).encode('hex'), str(self.title).encode('utf8'))) + \
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4a9' in position 0: ordinal not in range(128)
```

**Comment by ichorid** [comment]
@qstokkink , could you please tell what you were doing when you got this error?

**Comment by qstokkink** [comment]
I added a torrent to my channel. Which already had one torrent in (which had a unicode character name).
