### ISSUE TITLE
SQLError during shutdown: cannot commit - no transaction is active

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4028]
Occasionally, during shutdown the following log is observed. 
> SQLError: cannot commit - no transaction is active
```python
INFO    1542365691.13                   Session:800  (Session)  Tribler shutdown state notification:Shutting down SQLite Database...
INFO    1542365691.13             sqlitecachedb:237  (SQLiteCacheDB)  Start committing...
ERROR   1542365691.13             sqlitecachedb:294  (SQLiteCacheDB)  cachedb: ===MainThread===
SQL Type: <type 'unicode'>
-----
COMMIT;
-----
None
======
Traceback (most recent call last):
  File "/home/sandip/tudelft/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 283, in execute
    return cur.execute(sql)
  File "src/cursor.c", line 236, in resetcursor
SQLError: SQLError: cannot commit - no transaction is active
ERROR   1542365691.15             sqlitecachedb:240  (SQLiteCacheDB)  COMMIT FAILED
Traceback (most recent call last):
  File "/home/sandip/tudelft/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 238, in commit_now
    self.execute(u"COMMIT;")
  File "/home/sandip/tudelft/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 296, in execute
    raise msg
SQLError: SQLError: cannot commit - no transaction is active
ERROR   1542365691.15         shutdown_endpoint:47   (ShutdownEndpoint)  SQLError: cannot commit - no transaction is active
```
Note that SQLite is the last thing that is closed before the API manager.

**Comment by qstokkink** [comment]
We should probably catch this when trying to commit:

https://github.com/Tribler/tribler/blob/e9ae69bef51d6d9168c77b478eb59e4fa6279cb2/Tribler/Core/CacheDB/sqlitecachedb.py#L95

Then log the error and continue to close the database connection.
