### ISSUE TITLE
Error in credit mining - select torrents

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4046]
From error reporter - Tribler v7.1.2
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.IndexError'>: list index out of range
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\Core\CreditMining\CreditMiningManager.py:279:select_torrents
Tribler\Core\DownloadState.py:196:get_availability
]
```

> merged_bitfields[i] += 1

**Comment by devos50** [comment]
I also got this error a few days ago but I forgot to post. This is probably not exclusive to credit mining since I didn't have any credit mining downloads running (only channel downloads).

```
INFO    1542364299.08                 community:84   (Request)  Timeout for ping to Peer<79.101.198.181:45520, Yd9hihkNrS3tpT7p9W8RdmXzlnI=>
INFO    1542364299.08                 community:84   (Request)  Timeout for ping to Peer<185.253.96.164:8785, AqiX4Gl90QN/91uHy+n4x/pamcc=>
ERROR   1542364299.12                 community:124  (GigaChannelCommunity)  We are downloading channel , but no database entry exists!
ERROR   1542364299.12                 community:124  (GigaChannelCommunity)  We are downloading channel ?]??_?)???6?q@???, but no database entry exists!
INFO    1542364300.14       CreditMiningManager:320  (CreditMiningManager)  0 active download(s), 0 bytes uploaded
ERROR   1542364300.16                 community:124  (GigaChannelCommunity)  We are downloading channel , but no database entry exists!
ERROR   1542364300.18                 community:124  (GigaChannelCommunity)  We are downloading channel ?]??_?)???6?q@???, but no database entry exists!
ERROR   1542364300.78              rest_manager:62   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.IndexError'>: list index out of range
/Library/Python/2.7/site-packages/twisted/web/http.py:2054:lineReceived
/Library/Python/2.7/site-packages/twisted/web/http.py:2145:allContentReceived
/Library/Python/2.7/site-packages/twisted/web/http.py:890:requestReceived
/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/restapi/rest_manager.py:96:process
--- <exception caught here> ---
/Library/Python/2.7/site-packages/twisted/web/server.py:197:process
/Library/Python/2.7/site-packages/twisted/web/server.py:257:render
/Library/Python/2.7/site-packages/twisted/web/resource.py:250:render
/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py:234:render_GET
/Users/martijndevos/Documents/tribler/Tribler/Core/DownloadState.py:196:get_availability
]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/web/server.py", line 197, in process
    self.render(resrc)
  File "/Library/Python/2.7/site-packages/twisted/web/server.py", line 257, in render
    body = resrc.render(self)
  File "/Library/Python/2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py", line 234, in render_GET
    "destination": download.get_dest_dir(), "availability": state.get_availability(),
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/DownloadState.py", line 196, in get_availability
    merged_bitfields[i] += 1
IndexError: list index out of range
```

**Comment by devos50** [comment]
It seems to be caused by inconsistent lengths of the `have` field for peers in the same swarm. How this is possible is unknown for me, but I could purposefully send a `have` bitfield with an incorrect length. I.e. we should never trust input from other swarms.

@egbertbouman do you have any idea how we can fix this?

**Comment by egbertbouman** [comment]
@devos50 I guess we should get the number of pieces from the torrent itself (which has been verified by libtorrent) and also check that the piece index that we get from peers does not exceed this value.
