### ISSUE TITLE
Gigachannel error in Windows tests

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4071]
I observed this error when running the tests on Windows:

```
======================================================================
ERROR: Test whether we can remove a torrent from your channel using the API
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "c:\python27\lib\site-packages\twisted\internet\utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "c:\python27\lib\site-packages\twisted\internet\utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\test_as_server.py", line 56, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\Core\Modules\RestApi\Channels\test_channels_torrents_endpoint.py", line 594, in test_remove_single_torrent_from_my_channel
    my_channel.commit_channel_torrent()
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Modules\MetadataStore\OrmBindings\channel_metadata.py", line 194, in commit_channel_torrent
    new_infohash = self.update_channel_torrent(self.staged_entries_list)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Modules\MetadataStore\OrmBindings\channel_metadata.py", line 145, in update_channel_torrent
    os.makedirs(channel_dir)
  File "c:\python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 206] The filename or extension is too long: u'C:\\workspace\\jenkins2\\workspace\\GH_Tribler_PR_Tests\\GH_Tribler_PR_tests_win64\\tribler\\Tribler\\Test\\temp\\TestModifyChantChannelTorrentEndpoint_tribler_test_session_TK3BLQ\\dot.Tribler\\channels\\1e24447e68edef132522bbc199fc558e969010511fb01f072b95c42a205b'
```

**Comment by devos50** [comment]
Fixed by making the Jenkins job name shorter.

**Comment by synctext** [comment]
Can we create a Windows/Linux subdirectory test? If user wants to install Tribler in a 257 char long subdir, we throw an error. (or future polish)

**Comment by devos50** [comment]
Yes, this is something @ichorid and I discussed. Tribler should never crash, even if channel name paths are too long. This error should be captured and displayed to the user in a meaningful way. We have not received any error report so far regarding this issue.

This is probably something for another issue.

**Comment by qstokkink** [comment]
You should be able to use 32k length paths in Windows by using `u"\\\\?\\%s" % abspathname`.
