### ISSUE TITLE
Issue with bitcoinlib in MacOS

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4074]
```python
Traceback (most recent call last):
File "TriblerGUI/core_manager.py", line 114, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "twisted/internet/base.py", line 420, in fireEvent

File "twisted/internet/defer.py", line 319, in addCallback

File "twisted/internet/defer.py", line 308, in addCallbacks

File "twisted/internet/defer.py", line 651, in _runCallbacks

--- <exception caught here> ---
File "twisted/internet/base.py", line 433, in _continueFiring

File "run_tribler.py", line 83, in start_tribler

File "Tribler/pyipv8/ipv8/util.py", line 49, in helper

File "Tribler/pyipv8/ipv8/util.py", line 61, in blockingCallFromThread

File "Tribler/Core/Session.py", line 489, in start

File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 229, in register

File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 419, in init

File "Tribler/Core/Modules/wallet/btc_wallet.py", line 38, in __init__

File "/Applications/Tribler.app/Contents/MacOS/bitcoinlib/wallets.py", line 92, in wallet_exists
if wallet in [x['name'] for x in wallets_list(databasefile)]:
File "/Applications/Tribler.app/Contents/MacOS/bitcoinlib/wallets.py", line 63, in wallets_list
wallets = session.query(DbWallet).all()
File "sqlalchemy/orm/query.py", line 2737, in all

File "sqlalchemy/orm/query.py", line 2889, in __iter__

File "sqlalchemy/orm/query.py", line 2912, in _execute_and_instances

File "sqlalchemy/engine/base.py", line 948, in execute

File "sqlalchemy/sql/elements.py", line 269, in _execute_on_connection

File "sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement

File "sqlalchemy/engine/base.py", line 1200, in _execute_context

File "sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception

File "sqlalchemy/util/compat.py", line 203, in raise_from_cause

File "sqlalchemy/engine/base.py", line 1193, in _execute_context

File "sqlalchemy/engine/default.py", line 507, in do_execute

sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) no such column: wallets.witness_type [SQL: u'SELECT wallets.id AS wallets_id, wallets.name AS wallets_name, wallets.owner AS wallets_owner, wallets.network_name AS wallets_network_name, wallets.purpose AS wallets_purpose, wallets.scheme AS wallets_scheme, wallets.witness_type AS wallets_witness_type, wallets.encoding AS wallets_encoding, wallets.main_key_id AS wallets_main_key_id, wallets.multisig_n_required AS wallets_multisig_n_required, wallets.sort_keys AS wallets_sort_keys, wallets.parent_id AS wallets_parent_id, wallets_1.id AS wallets_1_id, wallets_1.name AS wallets_1_name, wallets_1.owner AS wallets_1_owner, wallets_1.network_name AS wallets_1_network_name, wallets_1.purpose AS wallets_1_purpose, wallets_1.scheme AS wallets_1_scheme, wallets_1.witness_type AS wallets_1_witness_type, wallets_1.encoding AS wallets_1_encoding, wallets_1.main_key_id AS wallets_1_main_key_id, wallets_1.multisig_n_required AS wallets_1_multisig_n_required, wallets_1.sort_keys AS wallets_1_sort_keys, wallets_1.parent_id AS wallets_1_parent_id, wallets_2.id AS wallets_2_id, wallets_2.name AS wallets_2_name, wallets_2.owner AS wallets_2_owner, wallets_2.network_name AS wallets_2_network_name, wallets_2.purpose AS wallets_2_purpose, wallets_2.scheme AS wallets_2_scheme, wallets_2.witness_type AS wallets_2_witness_type, wallets_2.encoding AS wallets_2_encoding, wallets_2.main_key_id AS wallets_2_main_key_id, wallets_2.multisig_n_required AS wallets_2_multisig_n_required, wallets_2.sort_keys AS wallets_2_sort_keys, wallets_2.parent_id AS wallets_2_parent_id \nFROM wallets LEFT OUTER JOIN wallets AS wallets_2 ON wallets.id = wallets_2.parent_id LEFT OUTER JOIN wallets AS wallets_1 ON wallets_2.id = wallets_1.parent_id'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by devos50** [comment]
This issue is related to different bitcoinlib versions. We discussed this issue a while ago and decided to not include the upgrade script for bitcoinlib (since only a very small number of users actually created a bitcoin wallet in Tribler). Removing the `wallet` directory in the Tribler state dir should "fix" this.

**Comment by synctext** [comment]
To clarify, this bug is only triggered if you created a Bitcoin wallet through the GUI.
