### ISSUE TITLE
PackError: Failed to unserialize TruncatedChannelPlayloadBlob

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4137]
Latest devel is spammed with the following traceback logs:
```python
ERROR   1546863710.17                 community:287  (GigaChannelCommunity)  Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/community.py", line 284, in on_packet
    self.decode_map[msg_id](source_address, data)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/lazy_community.py", line 36, in wrapper
    unpacked = self.serializer.unpack_to_serializables(payloads, remainder[23:])
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 373, in unpack_to_serializables
    sys.exc_info()[2])
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 369, in unpack_to_serializables
    serializable.optional_format_list, offset)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 315, in unpack_multiple
    sys.exc_info()[2])
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 307, in unpack_multiple
    unpacked, unpacked_size = self.unpack(format, data, current_offset)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 283, in unpack
    return NestedPayload(self).unpack_from(format, data, offset)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 77, in unpack_from
    unpacked = self.serializer.unpack_to_serializables([serializable_class], raw)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 373, in unpack_to_serializables
    sys.exc_info()[2])
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 369, in unpack_to_serializables
    serializable.optional_format_list, offset)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 315, in unpack_multiple
    sys.exc_info()[2])
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 307, in unpack_multiple
    unpacked, unpacked_size = self.unpack(format, data, current_offset)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 284, in unpack
    return self._packers[format].unpack_from(data, offset)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 175, in unpack_from
    out = super(DefaultStruct, self).unpack_from(buffer, offset)
PackError: Failed to unserialize TruncatedChannelPlayloadBlob
PackError: Could not pack item 0: <class 'Tribler.community.gigachannel.payload.TruncatedChannelPayload'>
PackError: Failed to unserialize TruncatedChannelPayload
PackError: Could not pack item 0: 20s
error: unpack_from requires a buffer of at least 20 bytes

```

**Comment by qstokkink** [comment]
Probably because people are using other branches with different wire formats without changing the community identifier. I think this can be closed.
