### ISSUE TITLE
Orders cannot be completed on the marketplace

### ISSUE THREAD

**Issue by MattSkala** [Tribler/tribler#4148]
##### Tribler version/branch+revision: #####
devel#9d5e2a1cf9995113954216d626c347a8ce726474
https://github.com/MattSkala/bitcoinlib (a patched version of bitcoinlib with support for saving raw transactions, PR not yet merged in the official repo)

##### Operating system and version: #####
Ubuntu 16.04

##### Steps to reproduce the behavior: #####
1. Place a bid in the BTC/MB pair
2. Place a matching ask in the same pair

##### Expected behavior: #####
The orders should be matched and the trade performed.

##### Actual behavior: #####
A market transaction is created with the pending status, but the trade is not performed and the order expires.

##### Relevant log file output: #####
```
2019-01-14 09:17:48+0100 [-] INFO:OrderManager:Ask order created with id: 22403ab62cf279355450fb9b69816cca834a059b.3
2019-01-14 09:17:48+0100 [-] INFO:TrustChainCommunity:Signed block to 30303030 (Block 0ea44938 from ...51e65150:4 links ...30303030:0 for {'tick': {'trader_id': '22403ab62cf279355450fb9b69816cca834a059b', 'timestamp': 1547453868.099689, 'timeout': 3600, 'traded': 0, 'order_number': 3, 'assets': {'second': {'amount': 4403L, 'type': 'MB'}, 'first': {'amount': 374647L, 'type': 'BTC'}}}, 'version': 2} type ask) validation result (<function partial_next at 0x7f92fd193de8>, [])
2019-01-14 09:17:48+0100 [-] INFO:MarketCommunity:Inserting tick <Ask P: 0.011752, Q: 374647 BTC, O: 22403ab62cf279355450fb9b69816cca834a059b.3> from 22403ab62cf279355450fb9b69816cca834a059b.3, asset pair: 374647 BTC 4403 MB
2019-01-14 09:17:48+0100 [-] WARNING:DatabaseOrderBook:Invalid tick inserted in order book.
2019-01-14 09:17:48+0100 [-] INFO:MarketCommunity:Ask created with asset pair 374647 BTC 4403 MB
2019-01-14 09:17:48+0100 [-] 127.0.0.1 - - [14/Jan/2019:08:17:47 +0000] "PUT /market/asks HTTP/1.1" 200 17 "-" "python-requests/2.21.0"
2019-01-14 09:17:48+0100 [-] INFO:MarketCommunity:Sending match message with id 400b17a1768dc5af8e17, order id 22403ab62cf279355450fb9b69816cca834a059b.3 and tick order id b49ea564c321e52581419f729c19932564a9b016.8 to trader 22403ab62cf279355450fb9b69816cca834a059b (quantity: 374647)
2019-01-14 09:17:49+0100 [-] ERROR:DHTDiscoveryCommunity:Got ping-response with unknown identifier, dropping packet
2019-01-14 09:17:51+0100 [-] INFO:PopularityCommunity:Content to publish: 0
2019-01-14 09:17:51+0100 [-] INFO:CreditMiningManager:0 active download(s), 0 bytes uploaded
2019-01-14 09:17:51+0100 [-] INFO:Dispersy:estimate someones WAN address is ('109.173.152.79', 30908) (WAN was ('109.173.152.79', 30987), LAN stays ('192.168.100.9', 48853))
2019-01-14 09:17:51+0100 [-] INFO:Dispersy:estimate someones WAN address is ('109.173.152.79', 30908) (WAN was ('109.173.152.79', 31054), LAN stays ('192.168.100.9', 48853))
2019-01-14 09:17:52+0100 [-] INFO:Dispersy:estimate someones WAN address is ('73.153.51.182', 7759) (WAN was ('109.175.184.192', 19172), LAN stays ('192.168.1.11', 7759))
2019-01-14 09:17:55+0100 [-] 127.0.0.1 - - [14/Jan/2019:08:17:54 +0000] "GET /downloads?get_pieces=1 HTTP/1.1" 200 17 "-" "Mozilla/5.0"
2019-01-14 09:17:55+0100 [-] INFO:CreditMiningManager:0 active download(s), 0 bytes uploaded
2019-01-14 09:17:56+0100 [-] INFO:Request:Timeout for ping to Peer<5.79.71.187:35010, K86FHJw+2sZcoVZZM2ffFyJEpPA=>
2019-01-14 09:17:56+0100 [-] INFO:PopularityCommunity:Content to publish: 0
2019-01-14 09:17:57+0100 [-] INFO:MarketCommunity:We received a match message for order 22403ab62cf279355450fb9b69816cca834a059b.3 (matched quantity: 374647)
2019-01-14 09:17:57+0100 [-] INFO:TransactionManager:Transaction created with id: b49ea564c321e52581419f729c19932564a9b016.2, asset pair 374647 BTC 4403 MB
2019-01-14 09:17:57+0100 [-] ERROR:MarketCommunity:Exception occurred while handling packet!
2019-01-14 09:17:57+0100 [-] Traceback (most recent call last):
2019-01-14 09:17:57+0100 [-]   File "/usr/local/lib/python2.7/dist-packages/Tribler/pyipv8/ipv8/community.py", line 284, in on_packet
2019-01-14 09:17:57+0100 [-]     self.decode_map[msg_id](source_address, data)
2019-01-14 09:17:57+0100 [-]   File "/usr/local/lib/python2.7/dist-packages/Tribler/pyipv8/ipv8/lazy_community.py", line 49, in wrapper
2019-01-14 09:17:57+0100 [-]     return func(self, Peer(auth.public_key_bin, source_address), *output)
2019-01-14 09:17:57+0100 [-]   File "/usr/local/lib/python2.7/dist-packages/Tribler/community/market/community.py", line 1258, in received_start_transaction
2019-01-14 09:17:57+0100 [-]     incoming_address, outgoing_address = self.get_order_addresses(order)
2019-01-14 09:17:57+0100 [-]   File "/usr/local/lib/python2.7/dist-packages/Tribler/community/market/community.py", line 347, in get_order_addresses
2019-01-14 09:17:57+0100 [-]     WalletAddress(self.wallets[order.assets.first.asset_id].get_address())
2019-01-14 09:17:57+0100 [-]   File "/usr/local/lib/python2.7/dist-packages/Tribler/community/market/core/wallet_address.py", line 13, in __init__
2019-01-14 09:17:57+0100 [-]     raise ValueError("Wallet address must be a string")
2019-01-14 09:17:57+0100 [-] ValueError: Wallet address must be a string
2019-01-14 09:17:57+0100 [-]
2019-01-14 09:17:58+0100 [-] INFO:MarketCommunity:We received a match message for order 22403ab62cf279355450fb9b69816cca834a059b.3 (matched quantity: 374647)
2019-01-14 09:17:58+0100 [-] INFO:MarketCommunity:Sending decline match message with match id 697c38d3007533a3ba8c to trader 0435c98718863b3f90c83c84302718542e3260ef (ip: 77.229.13.248, port: 34791)
```

**Comment by MattSkala** [comment]
Both BTC and MB addresses seem to created correctly.

```
{
	"wallets": {
		"TBTC": {
			"name": "Testnet BTC",
			"unlocked": true,
			"created": false,
			"precision": 8,
			"address": "",
			"min_unit": 100000,
			"balance": {
				"available": 0,
				"currency": "BTC",
				"precision": 8,
				"pending": 0
			}
		},
		"BTC": {
			"name": "Bitcoin",
			"unlocked": true,
			"created": true,
			"precision": 8,
			"address": "192VkM42aDzTtGQNTEaNKnamXHtpa44eCV",
			"min_unit": 100000,
			"balance": {
				"available": 500000,
				"currency": "BTC",
				"precision": 8,
				"pending": 0
			}
		},
		"MB": {
			"name": "Tokens (MB)",
			"unlocked": true,
			"created": true,
			"precision": 0,
			"address": "TGliTmFDTFBLOhXh+i3suBoZlwU3HlMbMi6lFKVR8V1KdySwBI/xDGh5H6NqwKaMdOfQNSNtsn8f5lwbMN9QEEol+Iea1lHmUVA=",
			"min_unit": 1,
			"balance": {
				"available": 472,
				"currency": "MB",
				"precision": 0,
				"pending": 0
			}
		}
	}
}
```

**Comment by devos50** [comment]
@MattSkala with my latest commit you should see the type of the wallet address if this error occurs (https://github.com/Tribler/tribler/blob/devel/Tribler/community/market/core/wallet_address.py#L13). It might be unicode?

**Comment by MattSkala** [comment]
@devos50 Indeed, the BTC address is of type `unicode`, MB address is `str`.

**Comment by devos50** [comment]
Right. I will make a fix in a moment.

**Comment by devos50** [comment]
@MattSkala see #4153

**Comment by devos50** [comment]
> response [500] No free outputs to spend

It looks like you do not have enough funds in your wallet?

**Comment by MattSkala** [comment]
The BTC address shown in Tribler and returned via API is `192VkM42aDzTtGQNTEaNKnamXHtpa44eCV` and there should be enough funds on it.

In the previous log there are 3 addresses mentioned. Looking into the `keys` table of the `.Tribler/wallets/wallets.sqlite` database, they refer to:
```
12xEVnJsEyHJ72W5phsWgdv1Sotef7Qa6r, m/44'/0'/0'/0/0, address index 0
1Myg8ghJLuwAbkCZSeiMQ2vT8gqCdSD2vt, m/44'/0'/0'/1/0, tribler_change
192VkM42aDzTtGQNTEaNKnamXHtpa44eCV, m/44'/0'/0'/0/1, tribler_payments
```

It looks like it fails to find utxos on the first address and then doesn't check the other addresses.

**Comment by MattSkala** [comment]
Sending BTC using the `/wallets/BTC/transfer` endpoint works properly, so there should not be an issue with bitcoinlib. I don't know what triggered the previous warning, but I haven't seen it during subsequent testing.

However, I still haven't been able to perform a trade on the market. I can't find any relevant errors in the log. I can only see that the `tx_init` block is created, but it seems that nothing interesting happens after that. I'm not sure how to debug this.

**Comment by devos50** [comment]
@MattSkala creation of the `tx_init` block indicates that the trade has started. This means that one of the counterparties should start exchanging the assets. Do you see anything in the logs that indicates this?

It also might be that the `get_transactions` is not working correctly and that it does not correctly observe the incoming transaction. Please drop by at our office if you want some more help debugging this 👍

**Comment by devos50** [comment]
Great to hear! 👍
