### ISSUE TITLE
Tribler 7.1.5 not starting on Ubuntu: Address already in use.

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4157]
Huge log ```736M Jan 17 10:40 ```. After Tribler stopped improperly with packet-of-death, upgraded to latest version on Ubuntu 18.04:
```
ERROR:root:Fault Handler module not found.
INFO    1547717491.34        single_application:23   (root)  __init__()
INFO    1547717491.68        single_application:49   (root)    self._outSocket.error() = '0'
INFO    1547717491.68        single_application:52   (root)  received QLocalSocket.ConnectionRefusedError; removing server.
INFO    1547717491.68        single_application:64   (root)  close()
INFO    1547717491.68        single_application:71   (root)  close(): returning
INFO    1547717491.68        single_application:60   (root)  __init__(): returning
INFO    1547717493.19     event_request_manager:151  (TriblerGUI)  Will connect to events endpoint
INFO    1547717495.84     event_request_manager:53   (TriblerGUI)  Got Tribler core error: 401
WARNING 1547717495.86     event_request_manager:142  (TriblerGUI)  Events connection dropped, attempting to reconnect
INFO    1547717496.39     event_request_manager:151  (TriblerGUI)  Will connect to events endpoint
INFO    1547717498.21                    driver:124  (root)  Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO    1547717498.25                    driver:124  (root)  Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 428, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 441, in _continueFiring
    callable(*args, **kwargs)
  File "run_tribler.py", line 83, in start_tribler
    session.start()
  File "/usr/share/tribler/Tribler/pyipv8/ipv8/util.py", line 49, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/usr/share/tribler/Tribler/pyipv8/ipv8/util.py", line 61, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Core/Session.py", line 480, in start
    self.lm.api_manager.start()
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/rest_manager.py", line 34, in start
    self.site = reactor.listenTCP(self.session.config.get_http_api_port(), site, interface="127.0.0.1")
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 980, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:8085: [Errno 98] Address already in use.

INFO    1547717501.17     event_request_manager:53   (TriblerGUI)  Got Tribler core error: 401
WARNING 1547717501.17     event_request_manager:142  (TriblerGUI)  Events connection dropped, attempting to reconnect
```

**Comment by devos50** [comment]
@synctext you probably have a zombie process running that claimed port 8085. Could you check for that?

**Comment by devos50** [comment]
We assume that there was indeed a zombie process running, therefore we will close this issue. Please reopen it if the problem persists.
