### ISSUE TITLE
Pymdht - Non-optional key (a:port) not found

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4159]
Found a pymddht traceback
```python
ERROR   1548000555.74                controller:218  (dht)  Error while decoding dht message
Traceback (most recent call last):
  File "/home/sireto/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/controller.py", line 214, in on_datagram_received
    msg = self.msg_f.incoming_msg(datagram)
  File "/home/sireto/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/message.py", line 165, in incoming_msg
    msg = IncomingMsg(self.private_dht_name, datagram)
  File "/home/sireto/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/message.py", line 322, in __init__
    self._sanitize_query()
  File "/home/sireto/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/message.py", line 419, in _sanitize_query
    self.bt_port = self._get_int(ARGS, PORT)
  File "/home/sireto/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/message.py", line 373, in _get_int
    v = self._get_value(k, kk)
  File "/home/sireto/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/message.py", line 353, in _get_value
    raise MsgError, 'Non-optional key (%s:%s) not found' % (k, kk)
MsgError: Non-optional key (a:port) not found
```
We should disable it by default.

**Comment by devos50** [comment]
`pymdht` is removed now, closing this issue.
