### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 4 bytes

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4160]
From error reporter - Tribler 7.1.5
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 133, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\python\log.py", line 86, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 122, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 85, in callWithContext

File "lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\udp.py", line 249, in doRead

File "Tribler\Core\TorrentChecker\session.py", line 381, in datagramReceived

struct.error: unpack_from requires a buffer of at least 4 bytes
```

**Comment by qstokkink** [comment]
Right now we assume that what we get from the socket always contains at least an integer. We should add a check and log if it is not satisfied:

```python
if data or len(data) >= 4:
```
