### ISSUE TITLE
Crash on token mining page

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4183]
The application tester caught the following error:

```
ERROR:Executor:Tribler crashed after uptime of 4431.65499997 sec! Stack trace: Traceback (most recent call last):
  File "TriblerGUI\widgets\tokenminingpage.py", line 167, in on_received_downloads
  File "TriblerGUI\widgets\tokenminingpage.py", line 47, in compute_initial_figure
  File "lib\site-packages\matplotlib\__init__.py", line 1898, in inner
  File "lib\site-packages\matplotlib\axes\_axes.py", line 1407, in plot
  File "lib\site-packages\matplotlib\axes\_base.py", line 1793, in add_line
  File "lib\site-packages\matplotlib\axes\_base.py", line 1815, in _update_line_limits
  File "lib\site-packages\matplotlib\lines.py", line 989, in get_path
  File "lib\site-packages\matplotlib\lines.py", line 676, in recache
  File "lib\site-packages\numpy\core\numeric.py", line 531, in asarray
TypeError: float() argument must be a string or a number
```

**Comment by devos50** [comment]
Also happens on the ‘devel’ branch.
