### ISSUE TITLE
TypeError: bad operand type for abs(): 'NoneType'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4216]
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/widgets/homepage.py", line 89, in received_popular_torrents
self.window().home_page_table_view.cellWidget(cur_ind % 3, cur_ind / 3).update_with_torrent(torrent)
File "/usr/share/tribler/TriblerGUI/widgets/home_recommended_item.py", line 90, in update_with_torrent
self.detail_label.setText("Size: " + format_size(torrent["size"]))
File "/usr/share/tribler/TriblerGUI/utilities.py", line 14, in format_size
if abs(num) < 1024.0:
TypeError: bad operand type for abs(): 'NoneType'
```

**Comment by qstokkink** [comment]
Judging from the existing code, it seems like fields *could* be None:

https://github.com/Tribler/tribler/blob/373b85117ca34bfc7b769c31dc5bd200118d146b/Tribler/Core/Modules/restapi/torrents_endpoint.py#L86
