### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'is_valid'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4217]
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 133, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'dict' object has no attribute 'is_valid'
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1199:run
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1208:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:828:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:610:_task_process_alerts
/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:406:process_alert
/usr/share/tribler/Tribler/Core/Libtorrent/__init__.py:16:invoke_func
]
```

**Comment by qstokkink** [comment]
Looks like the alert's handle is a dictionary.

**Comment by devos50** [comment]
@xoriole isn't this one fixed already?

**Comment by xoriole** [comment]
@devos50 No, that is not fixed yet. That is probably on adding rss feed but wasn't able to reproduce that.

**Comment by qstokkink** [comment]
Summary of discussion: [rss_alert](https://libtorrent.org/manual.html) is the only alert that has a `handle` attribute which is not a `torrent_handle`, therefore we think this is what could cause this.

**Comment by ichorid** [comment]
```python
ERROR   1551474080.18            tribler_window:67   (root)  Traceback (most recent call last):
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/TriblerGUI/event_request_manager.py", line 135, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback (failure with no frames): <type 'exceptions.RuntimeError'>: Value was not stored
]
```
Got crash with this error once in latest devel. Related?
