### ISSUE TITLE
Tribler 7.3 alpha does not install lz4 and pony on Ubuntu

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4224]
.deb package tested "Alpha1" https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Custom/33/

```
INFO    1550053970.38     event_request_manager:53   (TriblerGUI)  Got Tribler core error: 1
Traceback (most recent call last):
  File "run_tribler.py", line 95, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 46, in start_tribler_core
    from Tribler.Core.Session import Session
  File "/usr/share/tribler/Tribler/Core/Session.py", line 21, in <module>
    from Tribler.Core.APIImplementation.LaunchManyCore import TriblerLaunchMany
  File "/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 25, in <module>
    from Tribler.Core.Modules.MetadataStore.store import MetadataStore
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/store.py", line 7, in <module>
    import lz4.frame
ImportError: No module named lz4.frame
```

**Comment by devos50** [comment]
@ichorid The `lz4` package is not in the `debian/control` file in #4090 yet.

**Comment by ichorid** [comment]
Debian provides a horribly outdated version of `lz4` Python binding that does not support the required incremental compression feature. We'll have to install it by `pip`.

**Comment by xoriole** [comment]
I spent some time in building a snap package for tribler. The package and dependencies seems ok but have problems with some system shared object files.
```python
sandip@sandip-OptiPlex-9020:~/tudelft/tribler-snap$ tribler-bittorrent.tribler 
ERROR   1550486500.54               run_tribler:131  (root)  
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libblas.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/run_tribler.py", line 113, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/TriblerGUI/tribler_window.py", line 29, in <module>
    from TriblerGUI.debug_window import DebugWindow
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/TriblerGUI/debug_window.py", line 15, in <module>
    import matplotlib
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 123, in <module>
    from . import cbook
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/matplotlib/cbook/__init__.py", line 36, in <module>
    import numpy as np
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libblas.so.3: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/run_tribler.py", line 132, in <module>
    error_and_exit("Import Error", "Import error: {0}".format(ie))
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/check_os.py", line 27, in error_and_exit
    root = Tk()
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /usr/share/tcltk/tcl8.6 /snap/tribler-bittorrent/x1/usr/lib/tcl8.6 /snap/tribler-bittorrent/x1/lib/tcl8.6 /snap/tribler-bittorrent/x1/usr/library /snap/tribler-bittorrent/x1/library /snap/tribler-bittorrent/x1/tcl8.6.8/library /snap/tribler-bittorrent/tcl8.6.8/library



This probably means that Tcl wasn't installed properly.
```
Related: 
https://forum.snapcraft.io/t/shared-libraries/2424
https://github.com/apache/incubator-mxnet/issues/5290

The snapcraft build yaml is available here
https://github.com/xoriole/tribler-snap/blob/master/snap/snapcraft.yaml

**Comment by qstokkink** [comment]
Did you try supplying a `init.tcl`?

**Comment by xoriole** [comment]
```python
ERROR   1550501687.39               run_tribler:131  (root)  No module named backports.functools_lru_cache
Traceback (most recent call last):
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/run_tribler.py", line 113, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/TriblerGUI/tribler_window.py", line 29, in <module>
    from TriblerGUI.debug_window import DebugWindow
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/TriblerGUI/debug_window.py", line 15, in <module>
    import matplotlib
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 127, in <module>
    from matplotlib.rcsetup import defaultParams, validate_backend, cycler
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/matplotlib/rcsetup.py", line 29, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/dist-packages/matplotlib/fontconfig_pattern.py", line 32, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named backports.functools_lru_cache
Traceback (most recent call last):
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/run_tribler.py", line 132, in <module>
    error_and_exit("Import Error", "Import error: {0}".format(ie))
  File "/snap/tribler-bittorrent/x1/usr/share/tribler/check_os.py", line 27, in error_and_exit
    root = Tk()
  File "/snap/tribler-bittorrent/x1/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /usr/share/tcltk/tcl8.6 /snap/tribler-bittorrent/x1/usr/lib/tcl8.6 /snap/tribler-bittorrent/x1/lib/tcl8.6 /snap/tribler-bittorrent/x1/usr/library /snap/tribler-bittorrent/x1/library /snap/tribler-bittorrent/x1/tcl8.6.8/library /snap/tribler-bittorrent/tcl8.6.8/library



This probably means that Tcl wasn't installed properly.
```
Seems issue with matplotlib now

**Comment by qstokkink** [comment]
We probably need to explicitly install `pip install backports.functools_lru_cache`.

**Comment by xoriole** [comment]
After struggling with matplotlib and several other dependencies, now its QT's turn.

```python
sandip@sandip-OptiPlex-9020:~/tudelft/tribler-snap$ tribler-bittorrent.tribler 
INFO    1550742317.46              font_manager:1071 (matplotlib.font_manager)  font search path ['/snap/tribler-bittorrent/x1/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf', '/snap/tribler-bittorrent/x1/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/afm', '/snap/tribler-bittorrent/x1/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
INFO    1550742318.38              font_manager:1458 (matplotlib.font_manager)  generated new fontManager
INFO    1550742319.57        single_application:23   (root)  __init__()
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by qstokkink** [comment]
Possibly this answer? https://stackoverflow.com/a/25437758
