### ISSUE TITLE
ValueError: year is out of range

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4326]
After rebasing to new devel:
```python
ERROR   1551977540.15            tribler_window:67   (root)  Traceback (most recent call last):
  File "/home/vader/src/TRIBLER/tribler_ichorid/TriblerGUI/widgets/tablecontentmodel.py", line 91, in data
    if column in self.column_display_filters else data
  File "/home/vader/src/TRIBLER/tribler_ichorid/TriblerGUI/widgets/tablecontentmodel.py", line 168, in <lambda>
    u'updated': lambda date: pretty_date(date // 1000),
  File "/home/vader/src/TRIBLER/tribler_ichorid/TriblerGUI/utilities.py", line 96, in pretty_date
    diff = now - datetime.fromtimestamp(time)
ValueError: year is out of range
```

**Comment by ichorid** [comment]
You should really use `torren_date` field for that, BTW.

**Comment by cclauss** [comment]
If we have to touch this code, can we make the error text a bit more helpful?
> ValueError: year (1925) is out of range

**Comment by devos50** [comment]
@cclauss The exact error definition is defined by the `datetime` object. In #4329 I catch this error so it should not happen anymore.
