### ISSUE TITLE
UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4328]
Latest `devel` after rebase. My PR #4327 errors out on Windows with this:
@cclauss  is to `git-blame`.

```python
======================================================================
ERROR: test_monitor_download_insert_torrent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\python27\lib\site-packages\twisted\python\failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Test\Core\CreditMining\test_credit_mining_manager.py", line 108, in setUp
    yield super(TestCreditMiningManager, self).setUp()
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Test\test_as_server.py", line 278, in setUp
    self.tribler_started_deferred = self.session.start()
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Core\Session.py", line 409, in start
    startup_deferred = self.lm.register(self, self.session_lock)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Core\APIImplementation\LaunchManyCore.py", line 153, in register
    self.init()
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Core\APIImplementation\LaunchManyCore.py", line 309, in init
    self.ltmgr.initialize()
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Core\Libtorrent\LibtorrentMgr.py", line 98, in initialize
    self.get_session().start_upnp()
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Core\Libtorrent\LibtorrentMgr.py", line 249, in get_session
    self.ltsessions[hops] = self.create_session(hops)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Core\Libtorrent\LibtorrentMgr.py", line 185, in create_session
    codecs.decode(mid, 'raw_unicode_escape'))
UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 10-11: truncated \uXXXX
```

**Comment by devos50** [comment]
This issue is actively affecting our unit tests and could crash Tribler instances. We cannot release with this error. I will have a look tomorrow.

**Comment by cclauss** [comment]
Revert #4316? -- I don't like using the `codecs` module anyway and `raw_unicode_escape` seems worrisome too.

**Comment by devos50** [comment]
@cclauss yes, please do so.

**Comment by devos50** [comment]
I'm able to reproduce it with a string like `\u`, will post more details tomorrow.

**Comment by cclauss** [comment]
I believe that the merge of #4330 closes this issue.

**Comment by devos50** [comment]
@cclauss I think so too.
