### ISSUE TITLE
Tribler crashes with "message too long" error

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4391]
Latest Tribler `devel`:
```python
Traceback (most recent call last):
  File "/home/vader/src/TRIBLER/Tribler/TriblerGUI/event_request_manager.py", line 136, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/udp.py", line 249, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/home/vader/src/TRIBLER/Tribler/Tribler/Core/TorrentChecker/session.py", line 391, in datagramReceived
    self.tracker_sessions.pop(transaction_id).handle_response(data)
  File "/home/vader/src/TRIBLER/Tribler/Tribler/Core/TorrentChecker/session.py", line 565, in handle_response
    self.handle_connection_response(response)
  File "/home/vader/src/TRIBLER/Tribler/Tribler/Core/TorrentChecker/session.py", line 609, in handle_connection_response
    self.socket_mgr.send_request(message, self)
  File "/home/vader/src/TRIBLER/Tribler/Tribler/Core/TorrentChecker/session.py", line 381, in send_request
    self.transport.write(data, (tracker_session.ip_address, tracker_session.port))
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/udp.py", line 304, in write
    raise error.MessageLengthError("message too long")
twisted.internet.error.MessageLengthError: Message is too long to send: message too long.
```

**Comment by ichorid** [comment]
Still crashes with latest `devel`

**Comment by qstokkink** [comment]
Judging from this line..

https://github.com/Tribler/tribler/blob/97eec99d9c09135f76e1ee2fbda3bdca5d74850c/Tribler/Core/TorrentChecker/session.py#L591

..the `self._infohash_list` has too many infohashes in it and should be limited to a certain size before sending. As the `'!qii'` takes 16 bytes, the infohash limit should be somewhere around 60~70.
