### ISSUE TITLE
Tribler 7.2.2 Runtime error

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4395]
```python
Traceback (most recent call last):
  File "TriblerGUI\core_manager.py", line 114, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "lib\site-packages\twisted\internet\base.py", line 428, in fireEvent
    
  File "lib\site-packages\twisted\internet\defer.py", line 321, in addCallback
    
  File "lib\site-packages\twisted\internet\defer.py", line 310, in addCallbacks
    
  File "lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    
--- <exception caught here> ---
  File "lib\site-packages\twisted\internet\base.py", line 441, in _continueFiring
    
  File "run_tribler.py", line 83, in start_tribler
    
  File "Tribler\pyipv8\ipv8\util.py", line 35, in helper
    
  File "Tribler\pyipv8\ipv8\util.py", line 47, in blockingCallFromThread
    
  File "Tribler\Core\Session.py", line 495, in start
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 242, in register
    
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 422, in init
    
  File "Tribler\Core\Modules\wallet\btc_wallet.py", line 26, in __init__
    
  File "Tribler\Core\Modules\bitcoinlib_main.py", line 77, in initialize_lib
    
  File "C:\PROGRA~1\Tribler\bitcoinlib\__init__.py", line 22, in <module>
    import bitcoinlib.keys
  File "C:\PROGRA~1\Tribler\bitcoinlib\keys.py", line 30, in <module>
    import scrypt
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    
  File "lib\site-packages\scrypt\__init__.py", line 1, in <module>
    
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    
  File "lib\site-packages\scrypt\scrypt.py", line 15, in <module>
    
  File "lib\ctypes\__init__.py", line 440, in LoadLibrary
    
  File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 136, in __init__
    
  File "lib\ctypes\__init__.py", line 362, in __init__
    
exceptions.WindowsError: [Error 1114] A dynamic link library (DLL) initialization routine failed
```
```
os.getcwd          :     C:\Program Files\Tribler
sys.executable     :     C:\Program Files\Tribler\tribler.exe
os                 :     nt
platform           :     win32
platform.details   :     Windows-10-10.0.17763
platform.machine   :     AMD64
python.version     :     2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)
tribler_uptime     :     95.2960000038
sys.argv           :     C:\Program Files\Tribler\tribler.exe
sys.path           :     C:\PROGRA~1\Tribler
```

Reported in the forum; message from the user:
>I’m getting a runtime error (A program attempted to access the c library incorrectly) while Tribler loads. I have uninstalled and deleted all file (AppData and registry entries) and reinstalled and I’m getting the same error.

**Comment by qstokkink** [comment]
Quick translation of the traceback: for some reason `import scrypt` causes the dll load failure. Specifically here: https://github.com/holgern/py-scrypt/blob/master/scrypt/scrypt.py#L15:

```python
_scrypt = cdll.LoadLibrary(imp.find_module('_scrypt')[1])
```

This suggests that the scrypt dll shipped with Tribler is corrupt (or built for the wrong architecture).
