### ISSUE TITLE
str(OrderId(TraderId(b'0'), OrderNumber(1))) is b'0'.1

### ISSUE THREAD

**Issue by cclauss** [Tribler/tribler#4403]
How should we deal with this readability problem?

Python 3 treats bytes and strings differently and the first half of this string is __bytes__ and the second half is __str__.
```
FAIL: test_str (Tribler.Test.Community.Market.test_order.OrderIDTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/test_tribler_python3@2/tribler/Tribler/Test/Community/Market/test_order.py", line 198, in test_str
    self.assertEquals('0.1', str(self.order_id))
AssertionError: '0.1' != "b'0'.1"
- 0.1
+ b'0'.1

======================================================================
FAIL: test_conversion (Tribler.Test.Community.Market.test_transaction.TransactionIdTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/test_tribler_python3@2/tribler/Tribler/Test/Community/Market/test_transaction.py", line 66, in test_conversion
    self.assertEqual('0.1', str(self.transaction_id))
AssertionError: '0.1' != "b'0'.1"
- 0.1
+ b'0'.1
```

**Comment by qstokkink** [comment]
Seems like, in this case, the `bytes` should be cast to a `str` for visual representation.

**Comment by cclauss** [comment]
@devos50 What should be the __output of print(OrderId(TraderId(b'0'), OrderNumber(1)))__ ?

**Comment by devos50** [comment]
@cclauss this should be `0.1`.

**Comment by devos50** [comment]
When printing the string we should cast the `bytes` to `str` I guess, like @qstokkink suggested?
