### ISSUE TITLE
no Tribler shutdown after 10 hours

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4404]
V7.2.2 on Ubuntu 18.04.2 LTS. Tribler does not shutdown after considerable uptime.
![Screenshot from 2019-03-20 09-01-45](https://user-images.githubusercontent.com/325224/54668398-16b34f80-4aef-11e9-9135-d3f619583020.png)

Hunting in logs:

```
ERROR   1550313184.98              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1550433112.29              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1550435784.95              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1550435805.51              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1550867233.98              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1550867277.50              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1551545534.74              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
INFO    1552411613.83        single_application:23   (root)  __init__()
INFO    1552411614.13        single_application:49   (root)    self._outSocket.error() = '2'
INFO    1552411614.13        single_application:60   (root)  __init__(): returning
INFO    1552570330.11               run_tribler:139  (root)  Shutting down Tribler
```

Another file:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 2764, in dataReceived
    negotiatedProtocol = self._channel.transport.negotiatedProtocol
AttributeError: 'Server' object has no attribute 'negotiatedProtocol'
ERROR   1553068882.04              rest_manager:108  (RESTRequest)  Tribler shutdown in process. Not accepting any more request - <RESTRequest at 0x7fe04423e638 method=GET uri=/downloads?get_pieces=1 clientproto=HTTP/1.1>
ERROR   1553068882.05              rest_manager:77   (RESTRequest)  [Failure instance: Traceback (failure with no frames): <type 'exceptions.Exception'>: Tribler is shutting down
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 2764, in dataReceived
    negotiatedProtocol = self._channel.transport.negotiatedProtocol
AttributeError: 'Server' object has no attribute 'negotiatedProtocol'
ERROR   1553068913.74              rest_manager:108  (RESTRequest)  Tribler shutdown in process. Not accepting any more request - <RESTRequest at 0x7fe052e93ab8 method=GET uri=/downloads?get_pieces=1 clientproto=HTTP/1.1>
ERROR   1553068913.74              rest_manager:77   (RESTRequest)  [Failure instance: Traceback (failure with no frames): <type 'exceptions.Exception'>: Tribler is shutting down
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 2764, in dataReceived
    negotiatedProtocol = self._channel.transport.negotiatedProtocol
AttributeError: 'Server' object has no attribute 'negotiatedProtocol'
```

Core info file:
```
WARNING 1553069091.00                   handler:240  (TftpHandler)  got non-existing session from 85.137.235.59:7759, id = 13408
WARNING 1553069091.76                   handler:490  (TftpHandler)  TFTP[28461 S 86.90.48.164:7759][bc80a5aa83406a0a2c540757c5b901398361c122.torrent] ignore old block number ACK 41 < 42
INFO    1553069092.17            LaunchManyCore:63   (DualStackDiscoveryCommunity)  Dropping introduction response from (210.84.27.136, 7759): too many peers!
INFO    1553069092.63                   handler:152  (TftpHandler)  TFTP[34075 C 24.151.99.5:7759][0cf7833e73134d1c1e6e060ccdf44d66080d743c.torrent] timed out
INFO    1553069092.63                   handler:137  (TftpHandler)  TFTP[52621 C 62.194.123.84:6521][0cf7833e73134d1c1e6e060ccdf44d66080d743c.torrent] started
INFO    1553069094.23                   handler:260  (TftpHandler)  TFTP[14709 S 89.217.29.155:7759][fb73efc08cae093b9e786363606c1bc32cbb8451.torrent] finished
INFO    1553069095.13                   handler:152  (TftpHandler)  TFTP[52621 C 62.194.123.84:6521][0cf7833e73134d1c1e6e060ccdf44d66080d743c.torrent] timed out
INFO    1553069095.13                   handler:137  (TftpHandler)  TFTP[45371 C 67.87.118.9:55543][0cf7833e73134d1c1e6e060ccdf44d66080d743c.torrent] started
INFO    1553069095.92                   handler:260  (TftpHandler)  TFTP[771 S 89.217.29.155:7759][fae3e73227a9987c280d212c9df5c78441a2fa62.torrent] finished
ERROR   1553069096.29              rest_manager:108  (RESTRequest)  Tribler shutdown in process. Not accepting any more request - <RESTRequest at 0x7fe052d8b710 method=GET uri=/downloads?get_pieces=1 clientproto=HTTP/1.1>
ERROR   1553069096.31              rest_manager:77   (RESTRequest)  [Failure instance: Traceback (failure with no frames): <type 'exceptions.Exception'>: Tribler is shutting down
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 2764, in dataReceived
    negotiatedProtocol = self._channel.transport.negotiatedProtocol
AttributeError: 'Server' object has no attribute 'negotiatedProtocol'
```

Guess this is old GUI error:
```

ERROR   1548837012.54            tribler_window:73   (root)  Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/widgets/tokenminingpage.py", line 167, in on_received_downloads
    self.trust_plot.compute_initial_figure()
  File "/usr/share/tribler/TriblerGUI/widgets/tokenminingpage.py", line 47, in compute_initial_figure
    self.axes.plot(self.plot_data[1], self.plot_data[0][0], label="Upload(MB)", marker='o')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1898, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 1407, in plot
    self.add_line(line)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 1793, in add_line
    self._update_line_limits(line)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 1815, in _update_line_limits
    path = line.get_path()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/lines.py", line 989, in get_path
    self.recache()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/lines.py", line 676, in recache
    x = np.asarray(xconv, np.float_)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number

ERROR   1549714838.22              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1549716498.71              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1549716621.94              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
ERROR   1549718982.17              debug_window:195  (DebugWindow)  Failed to stop refresh timer in Debug pane
```

**Comment by xoriole** [comment]
>ERROR   1553068913.74              rest_manager:108  (RESTRequest)  Tribler shutdown in process. Not accepting any more request - **<RESTRequest at 0x7fe052e93ab8 method=GET uri=/downloads?get_pieces=1 clientproto=HTTP/1.1>**
ERROR   1553068913.74              rest_manager:77   (RESTRequest)  [Failure instance: Traceback (failure with no frames): <type 'exceptions.Exception'>: Tribler is shutting down
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 2764, in dataReceived
    negotiatedProtocol = self._channel.transport.negotiatedProtocol
AttributeError: 'Server' object has no attribute 'negotiatedProtocol'

This seems to the latest logs. When tribler shutdown process is initiated, the core stops accepting any request which is probably the cause of this stacktrace. This should be handled better. Also, we should change the order of stopping the core and the timers.
```python
            self.core_manager.stop()
            self.core_manager.shutting_down = True
            self.downloads_page.stop_loading_downloads()
            request_queue.clear()

            # Stop the token balance timer
            if self.token_refresh_timer:
                self.token_refresh_timer.stop()
```

**Comment by ichorid** [comment]
Hail asyncio!

**Comment by devos50** [comment]
I'm not sure if this error is actually fixed by `asyncio`. I believe we still have occasional issues on Tribler shutdown (as pointed out by @synctext recently).

**Comment by ichorid** [comment]
That deserves another issue than. The information in this one is outadate due to the move.
