### ISSUE TITLE
snap doesn't start (missing libvlc dependency)

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#4418]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.2.0-exp1

##### Operating system and version: #####
Fedora Workstation 29

##### Steps to reproduce the behavior: #####
1. sudo dnf install snapd -y && reboot
2. Login to an X11 GNOME session ([Tribler doesn’t start under Wayland](https://github.com/Tribler/tribler/issues/4367))
2. [sudo snap install --edge tribler-bittorrent --devmode](https://github.com/Tribler/tribler/pull/4240#issuecomment-467404148)
3. tribler-bittorrent

##### Expected behavior: #####
Should start. snaps are supposed to bundle all required dependencies.

##### Actual behavior: #####

Fails to start.

##### Relevant log file output: #####

    INFO    1553166501.97        single_application:23   (root)  __init__()
    INFO    1553166501.98        single_application:49   (root)    self._outSocket.error() = '0'
    INFO    1553166501.98        single_application:52   (root)  received QLocalSocket.ConnectionRefusedError; removing server.
    INFO    1553166501.98        single_application:64   (root)  close()
    INFO    1553166501.98        single_application:71   (root)  close(): returning
    INFO    1553166501.98        single_application:60   (root)  __init__(): returning
    QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
    ERROR   1553166502.64            tribler_window:67   (root)  Traceback (most recent call last):
      File "/snap/tribler-bittorrent/3/usr/share/tribler/run_tribler.py", line 120, in <module>
        window = TriblerWindow()
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/tribler_window.py", line 153, in __init__
        self.video_player_page.initialize_player()
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/widgets/videoplayerpage.py", line 49, in initialize_player
        self.instance = vlc.Instance()
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/vlc.py", line 1957, in __new__
        return libvlc_new(len(args), args)
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/vlc.py", line 4413, in libvlc_new
        ctypes.c_void_p, ctypes.c_int, ListPOINTER(ctypes.c_char_p))
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/vlc.py", line 336, in _Cfunction
        raise NameError('no function %r' % (name,))
    NameError: no function 'libvlc_new'

    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/tribler_window.py", line 70, in on_exception
        self.delete_tray_icon()
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/tribler_window.py", line 271, in delete_tray_icon
        if self.tray_icon:
    AttributeError: 'TriblerWindow' object has no attribute 'tray_icon'

    Original exception was:
    Traceback (most recent call last):
      File "/snap/tribler-bittorrent/3/usr/share/tribler/run_tribler.py", line 120, in <module>
        window = TriblerWindow()
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/tribler_window.py", line 153, in __init__
        self.video_player_page.initialize_player()
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/widgets/videoplayerpage.py", line 49, in initialize_player
        self.instance = vlc.Instance()
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/vlc.py", line 1957, in __new__
        return libvlc_new(len(args), args)
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/vlc.py", line 4413, in libvlc_new
        ctypes.c_void_p, ctypes.c_int, ListPOINTER(ctypes.c_char_p))
      File "/snap/tribler-bittorrent/3/usr/share/tribler/TriblerGUI/vlc.py", line 336, in _Cfunction
        raise NameError('no function %r' % (name,))
    NameError: no function 'libvlc_new'

cc/@xoriole

**Comment by xoriole** [comment]
Thank you for reporting. I'll publish a new updated edge version tomorrow. Would be nice if you could test.

**Comment by qstokkink** [comment]
@xoriole what's the status of this?

**Comment by xoriole** [comment]
This should be fixed already

**Comment by qstokkink** [comment]
Alright, then I'll close this.
