### ISSUE TITLE
No module named typing

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#4462]
##### Tribler version/branch+revision: #####
tribler_7.3.0-beta1_all.deb

##### Operating system and version: #####
Ubuntu 18.04
```
python --version
Python 2.7.15rc1
```
##### Steps to reproduce the behavior: #####
Launch Tribler

##### Expected behavior: #####
Usable

##### Actual behavior: #####
Gears forever? (5 min +)

##### Relevant log file output: #####
```
cat ~/.Tribler/logs/*
```

.

```
cat  /tmp/*-tribler-*
INFO    1555377829.40        single_application:28   (root)  __init__()
INFO    1555377829.49        single_application:54   (root)    self._outSocket.error() = '2'
INFO    1555377829.49        single_application:64   (root)  __init__(): returning
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
INFO    1555377830.64     event_request_manager:154  (TriblerGUI)  Will connect to events endpoint
INFO    1555377830.72     event_request_manager:56   (TriblerGUI)  Got Tribler core error: 1
Traceback (most recent call last):
  File "run_tribler.py", line 96, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 47, in start_tribler_core
    from Tribler.Core.Session import Session
  File "/usr/share/tribler/Tribler/Core/Session.py", line 23, in <module>
    from Tribler.Core.Modules.restapi.rest_manager import RESTManager
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/rest_manager.py", line 15, in <module>
    from Tribler.Core.Modules.restapi.root_endpoint import RootEndpoint
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/root_endpoint.py", line 10, in <module>
    from Tribler.Core.Modules.restapi.market_endpoint import MarketEndpoint
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/market_endpoint.py", line 5, in <module>
    from Tribler.Core.Modules.restapi.market.asks_bids_endpoint import AsksEndpoint, BidsEndpoint
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/market/__init__.py", line 6, in <module>
    from Tribler.community.market.community import MarketCommunity
  File "/usr/share/tribler/Tribler/community/market/community.py", line 18, in <module>
    from Tribler.community.market.core.matching_engine import MatchingEngine, PriceTimeStrategy
  File "/usr/share/tribler/Tribler/community/market/core/matching_engine.py", line 7, in <module>
    from Tribler.community.market.core.orderbook import OrderBook
  File "/usr/share/tribler/Tribler/community/market/core/orderbook.py", line 15, in <module>
    from Tribler.community.market.core.side import Side
  File "/usr/share/tribler/Tribler/community/market/core/side.py", line 3, in <module>
    from Tribler.community.market.core.pricelevel_list import PriceLevelList
  File "/usr/share/tribler/Tribler/community/market/core/pricelevel_list.py", line 3, in <module>
    from typing import Any, Dict, List  # pylint: disable=unused-import
ImportError: No module named typing
```

1) version should be logged
2) /tmp/triblerapp should be cleand up on Exception
3) Same "No module named typing" after `rm -r ~/.Tribler`

**Comment by Dmole** [comment]
```
pip install typing
```
is a workaround, but that should be part of the deb or app.

**Comment by qstokkink** [comment]
It seems #4405 introduced a new dependency without updating the docs or deb file.
