### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4479]
When running latest Beta2 of 7.3 on Ubuntu and visiting the new 'trust graph' with empty megacache:
```
ERROR   1556800842.19              rest_manager:80   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.TypeError'>: unhashable type: 'dict'
/usr/lib/python2.7/dist-packages/twisted/web/http.py:2013:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:2104:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:866:requestReceived
/usr/share/tribler/Tribler/Core/Modules/restapi/rest_manager.py:114:process
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:195:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:255:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/usr/share/tribler/Tribler/Core/Modules/restapi/trustview_endpoint.py:68:render_GET
/usr/share/tribler/Tribler/Core/Modules/restapi/trustview_endpoint.py:35:initialize_graph
/usr/share/tribler/Tribler/Core/Modules/TrustCalculation/local_view.py:29:__init__
/usr/share/tribler/Tribler/Core/Modules/TrustCalculation/local_view.py:78:lay_down_nodes
/usr/lib/python2.7/dist-packages/networkx/classes/function.py:333:set_node_attributes
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/trustview_endpoint.py", line 68, in render_GET
    self.initialize_graph()
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/trustview_endpoint.py", line 35, in initialize_graph
    self.local_view = NodeVision(self.node_id)
  File "/usr/share/tribler/Tribler/Core/Modules/TrustCalculation/local_view.py", line 29, in __init__
    self.pos = self.lay_down_nodes()
  File "/usr/share/tribler/Tribler/Core/Modules/TrustCalculation/local_view.py", line 78, in lay_down_nodes
    nx.set_node_attributes(self.graph, new_pos, 'pos')
  File "/usr/lib/python2.7/dist-packages/networkx/classes/function.py", line 333, in set_node_attributes
    G.node[node][name] = value
TypeError: unhashable type: 'dict'
```

**Comment by devos50** [comment]
So we cannot rely on the `networkx` package provided by `apt-get`? If so, we should update our `debian.control` file accordingly and install `networkx` from `pip` in our post-install script.

**Comment by qstokkink** [comment]
We should close this once we updated our `debian/control` and `debian/tribler.postinst`.
