### ISSUE TITLE
Segmentation fault: <Libtorrent::combine_path()+23>

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#448]
Suggested action: upgrade Libtorrent to 0.16.16.0

While running for a while the latest git devel I got a crash. Tribler has been running stable for many months on both my computers. The only difference was that last night I was running Python without the "-O". The error reports provides a hint where this comes from: <Libtorrent::combine_path()+23>.

![tribler_6 3pre_segfault__libtorrent_combine_path](https://f.cloud.github.com/assets/325224/2169325/1a96469a-9558-11e3-8ab5-be6a3f0193a6.png)

commit 2333572c1f6eecde4cc4b89ee2b3f9f0778130c8
Merge: 7bd4210 2ada27e
Author: NielsZeilemaker <niels@zeilemaker.nl>
Date:   Thu Feb 13 15:10:24 2014 +0100

```
ALIEN:~/GITHUB/tribler>git submodule update
Submodule path 'Tribler/SwiftEngine': checked out '53c17650d1aa4baa2d805e3c388b52d98cd518d5'
Submodule path 'Tribler/dispersy': checked out '1f462a7ae90cc4e9b72b6f82bfc007b9e91280c4'
ALIEN:~/GITHUB/tribler>git submodule sync
Synchronizing submodule url for 'Tribler/SwiftEngine'
Synchronizing submodule url for 'Tribler/dispersy'
ALIEN:~/GITHUB/tribler>run-
run-mailcap     run-no-O        run-parts       run-with-aspell 
ALIEN:~/GITHUB/tribler>run-no-O 
GUI started
GUI ready
ERROR   1392305672.13    GuiDBHandler:262   'Traceback (most recent call last):\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/Utility/GuiDBHandler.py", line 126, in wrapper\n    result = workerFn(*args, **kwargs)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/tribler_main.py", line 725, in loadSessionCheckpoint\n    convertDownloadCheckpoints(dir)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/Utility/compat.py", line 127, in convertDownloadCheckpoints\n    old_checkpoint = pickle.load(old_file)\n  File "/usr/lib/python2.7/pickle.py", line 1378, in load\n    return Unpickler(file).load()\n  File "/usr/lib/python2.7/pickle.py", line 858, in load\n    dispatch[key](self)\n  File "/usr/lib/python2.7/pickle.py", line 880, in load_eof\n    raise EOFError\nEOFError\n'
ERROR   1392305672.13    GuiDBHandler:279   'Traceback (most recent call last):\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/Utility/GuiDBHandler.py", line 126, in wrapper\n    result = workerFn(*args, **kwargs)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/tribler_main.py", line 725, in loadSessionCheckpoint\n    convertDownloadCheckpoints(dir)\n  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/Utility/compat.py", line 127, in convertDownloadCheckpoints\n    old_checkpoint = pickle.load(old_file)\n  File "/usr/lib/python2.7/pickle.py", line 1378, in load\n    return Unpickler(file).load()\n  File "/usr/lib/python2.7/pickle.py", line 858, in load\n    dispatch[key](self)\n  File "/usr/lib/python2.7/pickle.py", line 880, in load_eof\n    raise EOFError\nEOFError\n'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/vwxGUI/list_item.py", line 312, in ShowSelected
    DoubleLineListItem.ShowSelected(self)
TypeError: unbound method ShowSelected() must be called with DoubleLineListItem instance as first argument (got _wxPyDeadObject instance instead)
ERROR   1392324593.49   sqlitecachedb:2438  ===Dispersy===
SQL Type: <type 'unicode'>
-----
UPDATE Torrent SET comment=?,insert_time=?,name=?,num_leechers=?,status_id=?,num_seeders=?,secret=?,creation_date=?,num_files=?,length=?,source_id=?,torrent_file_name=?,swift_torrent_hash=?,relevance=?,category_id=?,infohash=?,thumbnail=? where torrent_id = 1008556
-----
[u'None', 1392324593L, u'Wuthering.Heights.2011.DVDSCR.XviD-ViP3R', -1, 1, -1, 0, 0, 3, 848052840, 1, '/home/pouwelse/Desktop/TriblerDownloads/collected_torrent_files/d7e74d052c6b25766a3f6b18d8a3ee42fde698c9', '1+dNBSxrJXZqP2sY2KPuQv3mmMk=', 0.0, 1, '+z0srJaJquVi2aRXdUDXr7V0B/k=', False]
======
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2428, in _execute
    result = cur.execute(sql, args)
  File "src/cursor.c", line 231, in resetcursor
ConstraintError: ConstraintError: column swift_torrent_hash is not unique
ERROR   1392324593.49        callback:692   non-fatal exception occurred [ConstraintError: column swift_torrent_hash is not unique]
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/callback.py", line 664, in _one_task
    result = call[0](*call[1], **call[2])
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/RemoteTorrentHandler.py", line 295, in do_db
    self.torrent_db.addExternalTorrent(tdef, extra_info={'filename': swiftpath, 'swift_torrent_hash': sdef.get_roothash(), 'status': 'good'})
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 460, in addExternalTorrent
    self._addTorrentToDB(torrentdef, source, extra_info)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 611, in _addTorrentToDB
    self._db.update('Torrent', where=where, **database_dict)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 552, in update
    self.execute_write(sql, arg)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2381, in execute_write
    self._execute(sql, args)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2314, in invoke_func
    return func(*args, **kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2439, in _execute
    raise msg
ConstraintError: ConstraintError: column swift_torrent_hash is not unique
Segmentation fault (core dumped)
ALIEN:~/GITHUB/tribler>
ALIEN:~/GITHUB/tribler>ls -lah /tmp/pouwelse-tribler.log 
-rw-r--r-- 1 pouwelse pouwelse 7.2K Jan 27 15:53 /tmp/pouwelse-tribler.log
```

**Comment by LipuFei** [comment]
@synctext @whirm Haven't seen this one. Could we close this one?

**Comment by whirm** [comment]
@LipuFei fine by me
