### ISSUE TITLE
Exceptions after converting database

### ISSUE THREAD

**Issue by loadletter** [Tribler/tribler#4502]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
tribler_7.3.0-beta2-68-g06c218336
##### Operating system and version: #####
Debian 9
##### Steps to reproduce the behavior: #####
Start tribler 7.3 with an older version database, I've alredy included mine in issue #4440
##### Expected behavior: #####
Database conversion completes
##### Actual behavior: #####
Database conversion doesn't complete
##### Relevant log file output: #####
```
INFO    1558194553.52              rest_manager:54   (RESTManager)  Starting REST API on port 8085
INFO    1558194553.54     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
INFO    1558194572.23              db72_to_pony:335  (TriblerUpgrader)  Converted old torrents: 114275/152780 0.098699 
INFO    1558194581.12              db72_to_pony:335  (TriblerUpgrader)  Converted old torrents: 114575/152780 0.198530 
ERROR   1558194581.12   tribler_request_manager:339  (root)  No json object could be decoded from data: 
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>

ERROR   1558194589.47                   upgrade:68   (TriblerUpgrader)  Error in Upgrader callback chain: [Failure instance: Traceback: <type 'exceptions.TypeError'>: expected string or buffer
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:498:errback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:565:_startRunCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:651:_runCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1355:gotResult
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1297:_inlineCallbacks
/usr/lib/python2.7/dist-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
/usr/share/tribler/Tribler/Core/Upgrade/db72_to_pony.py:401:do_migration
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
/usr/share/tribler/Tribler/Core/Upgrade/db72_to_pony.py:316:convert_discovered_torrents
/usr/share/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py:47:__init__
/usr/share/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py:50:add_tracker
/usr/share/tribler/Tribler/Core/Utilities/tracker_utils.py:60:get_uniformed_tracker_url
/usr/lib/python2.7/re.py:146:search
]
```
The exception is raised when get_uniformed_tracker_url gets a tracker_url == None
```
        # Rule out truncated URLs
        if re.search(truncated_url_detector, tracker_url):
            continue
```
Adding before that line
```
        if tracker_url == None:
            tracker_url = ''
```

Makes the conversion complete but then this happens
```
INFO    1558196143.11              db72_to_pony:335  (TriblerUpgrader)  Converted old torrents: 151830/152780 0.906724 
INFO    1558196155.05              db72_to_pony:335  (TriblerUpgrader)  Converted old torrents: 152566/152780 1.287935 
INFO    1558196165.47              db72_to_pony:335  (TriblerUpgrader)  Converted old torrents: 153515/152780 0.001943 
INFO    1558196169.26           tracker_manager:40   (TrackerManager)  No tracker blacklist file found at /home/user/.Tribler/tracker_blacklist.txt.
ERROR   1558196169.26            LaunchManyCore:271  (TriblerLaunchMany)  bitcoinlib library cannot be loaded: No module named bitcoinlib.wallets
INFO    1558196169.31                 community:120  (DHTDiscoveryCommunity)  DHT community initialized (peer mid dbd693da46e85248d040ad7559373864663a0573)
INFO    1558196169.33          order_repository:122  (DatabaseOrderRepository)  Memory order repository used
INFO    1558196169.33    transaction_repository:123  (DatabaseTransactionRepository)  Database transaction repository used
INFO    1558196169.33             order_manager:18   (OrderManager)  Market order manager initialized
INFO    1558196169.33       transaction_manager:20   (TransactionManager)  Transaction manager initialized
INFO    1558196169.33                 community:207  (MarketCommunity)  Market community initialized with mid dbd693da46e85248d040ad7559373864663a0573
INFO    1558196169.53            LaunchManyCore:623  (TriblerLaunchMany)  tlm: not resuming checkpoint because download has already been added
INFO    1558196169.54     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
WARNING 1558196169.71            tribler_window:348  (root)  Received duplicate Tribler Core started event
ERROR   1558196171.35              ipv8_service:144  (root)  Exception occurred while trying to walk!
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/pyipv8/ipv8_service.py", line 141, in on_tick
    strategy.take_step()
  File "/usr/share/tribler/Tribler/community/gigachannel/sync_strategy.py", line 19, in take_step
    self.overlay.send_random_to(peer)
  File "/usr/share/tribler/Tribler/community/gigachannel/community.py", line 77, in send_random_to
    blob = entries_to_chunk(md_list, maximum_payload_size)[0] if md_list else None
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py", line 71, in entries_to_chunk
    ''.join(metadata.serialized_delete() if metadata.status == TODELETE else metadata.serialized()))
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_node.py", line 140, in serialized
    return ''.join(self._serialized(key))
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_node.py", line 132, in _serialized
    return self._payload_class(key=key, **self.to_dict())._serialized()
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/serialization.py", line 265, in __init__
    **kwargs)
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/serialization.py", line 210, in __init__
    **kwargs)
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/serialization.py", line 165, in __init__
    **kwargs)
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/serialization.py", line 105, in __init__
    raise InvalidSignatureException("Tried to create payload with wrong signature")
InvalidSignatureException: <class 'Tribler.Core.exceptions.InvalidSignatureException'>: Tried to create payload with wrong signature

ERROR   1558196171.85              ipv8_service:144  (root)  Exception occurred while trying to walk!
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/pyipv8/ipv8_service.py", line 141, in on_tick
    strategy.take_step()
  File "/usr/share/tribler/Tribler/community/gigachannel/sync_strategy.py", line 19, in take_step
    self.overlay.send_random_to(peer)
  File "/usr/share/tribler/Tribler/community/gigachannel/community.py", line 77, in send_random_to
    blob = entries_to_chunk(md_list, maximum_payload_size)[0] if md_list else None
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py", line 71, in entries_to_chunk
    ''.join(metadata.serialized_delete() if metadata.status == TODELETE else metadata.serialized()))
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_node.py", line 140, in serialized
    return ''.join(self._serialized(key))
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_node.py", line 132, in _serialized
    return self._payload_class(key=key, **self.to_dict())._serialized()
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/serialization.py", line 265, in __init__
    **kwargs)
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/serialization.py", line 210, in __init__
    **kwargs)
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/serialization.py", line 165, in __init__
    **kwargs)
  File "/usr/share/tribler/Tribler/Core/Modules/MetadataStore/serialization.py", line 105, in __init__
    raise InvalidSignatureException("Tried to create payload with wrong signature")
InvalidSignatureException: <class 'Tribler.Core.exceptions.InvalidSignatureException'>: Tried to create payload with wrong signature

```

**Comment by devos50** [comment]
Thank you for your extensive report! We will investigate this and solve the issue 👍 

@ichorid could you have a look at this one?
