### ISSUE TITLE
InvalidSignatureException: <class 'Tribler.Core.exceptions.InvalidSignatureException'>: Tried to create payload with wrong signature

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4510]
Caught by deployment tester
```python
ERROR   1558527326.91                  __init__:1601 (root)  Exception occurred while trying to walk!
Traceback (most recent call last):
  File "Tribler\pyipv8\ipv8_service.py", line 141, in on_tick
  File "Tribler\community\gigachannel\sync_strategy.py", line 19, in take_step
  File "Tribler\community\gigachannel\community.py", line 77, in send_random_to
  File "Tribler\Core\Modules\MetadataStore\OrmBindings\channel_metadata.py", line 71, in entries_to_chunk
  File "Tribler\Core\Modules\MetadataStore\OrmBindings\channel_node.py", line 140, in serialized
  File "Tribler\Core\Modules\MetadataStore\OrmBindings\channel_node.py", line 132, in _serialized
  File "Tribler\Core\Modules\MetadataStore\serialization.py", line 265, in __init__
  File "Tribler\Core\Modules\MetadataStore\serialization.py", line 210, in __init__
  File "Tribler\Core\Modules\MetadataStore\serialization.py", line 165, in __init__
  File "Tribler\Core\Modules\MetadataStore\serialization.py", line 105, in __init__
InvalidSignatureException: <class 'Tribler.Core.exceptions.InvalidSignatureException'>: Tried to create payload with wrong signature
```

**Comment by ichorid** [comment]
This happens when you move from beta2 to beta3 without deleting `metadata.db` generated by beta2. `LEGACY` metadata identifier has changed between versions, so it tries to gossip the legacy entries. I'll make the upgrader automatically delete the older beta database.

**Comment by kozlovsky** [comment]
Re-encountered in 7.5.4, @ichorid can you check it?

**Comment by ichorid** [comment]
I guess the best solution is to make invalid entries self-destruct on this exception...
