### ISSUE TITLE
Our documentation build is failing

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4519]
our readthedocs documentation is not building correctly:

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
[autosummary] generating autosummary for: building/building.rst, building/building_on_osx.rst, building/building_on_windows.rst, contributing.rst, development/development.rst, development/development_on_linux.rst, development/development_on_osx.rst, development/development_on_windows.rst, development_methodology.rst, index.rst, ..., restapi/rssfeeds.rst, restapi/search.rst, restapi/settings.rst, restapi/state.rst, restapi/statistics.rst, restapi/torrentinfo.rst, restapi/torrents.rst, restapi/wallets.rst, trustchain.rst, twisted101.rst
Failed to import 'Tribler.Core.Modules.restapi.market.asks_bids_endpoint': no module named Tribler.Core.Modules.restapi.market.asks_bids_endpoint
Failed to import 'Tribler.Core.Modules.restapi.market.orders_endpoint': no module named Tribler.Core.Modules.restapi.market.orders_endpoint
Failed to import 'Tribler.Core.Modules.restapi.market.transactions_endpoint': no module named Tribler.Core.Modules.restapi.market.transactions_endpoint
Failed to import 'Tribler.Core.Modules.restapi.channels.channels_rss_endpoint': no module named Tribler.Core.Modules.restapi.channels.channels_rss_endpoint
Failed to import 'Tribler.Core.Modules.restapi.channels.channels_torrents_endpoint': no module named Tribler.Core.Modules.restapi.channels.channels_torrents_endpoint
Failed to import 'Tribler.Core.Modules.restapi.channels.channels_playlists_endpoint': no module named Tribler.Core.Modules.restapi.channels.channels_playlists_endpoint
Failed to import 'Tribler.Core.Modules.restapi.channels.channels_discovered_endpoint': no module named Tribler.Core.Modules.restapi.channels.channels_discovered_endpoint
Failed to import 'Tribler.Core.Modules.restapi.search_endpoint': no module named Tribler.Core.Modules.restapi.search_endpoint
Failed to import 'Tribler.Core.Modules.restapi.torrentinfo_endpoint': no module named Tribler.Core.Modules.restapi.torrentinfo_endpoint
Failed to import 'Tribler.Core.Modules.restapi.events_endpoint': no module named Tribler.Core.Modules.restapi.events_endpoint
Failed to import 'Tribler.Core.Modules.restapi.channels.my_channel_endpoint': no module named Tribler.Core.Modules.restapi.channels.my_channel_endpoint
Failed to import 'Tribler.Core.Modules.restapi.settings_endpoint': no module named Tribler.Core.Modules.restapi.settings_endpoint
Failed to import 'Tribler.Core.Modules.restapi.channels.channels_subscription_endpoint': no module named Tribler.Core.Modules.restapi.channels.channels_subscription_endpoint
Failed to import 'Tribler.Core.Modules.restapi.downloads_endpoint': no module named Tribler.Core.Modules.restapi.downloads_endpoint
Failed to import 'Tribler.Core.Modules.restapi.channels.channels_popular_endpoint': no module named Tribler.Core.Modules.restapi.channels.channels_popular_endpoint
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 31 source files that are out of date
updating environment: 31 added, 0 changed, 0 removed
reading sources... [  3%] building/building
reading sources... [  6%] building/building_on_osx
reading sources... [  9%] building/building_on_windows
reading sources... [ 12%] contributing
reading sources... [ 16%] development/development
reading sources... [ 19%] development/development_on_linux
reading sources... [ 22%] development/development_on_osx
reading sources... [ 25%] development/development_on_windows
reading sources... [ 29%] development_methodology
reading sources... [ 32%] index
reading sources... [ 35%] introduction
reading sources... [ 38%] restapi/channels_discovered
reading sources... [ 41%] restapi/channels_popular
reading sources... [ 45%] restapi/channels_subscribed
reading sources... [ 48%] restapi/debug
reading sources... [ 51%] restapi/downloads
reading sources... [ 54%] restapi/events
reading sources... [ 58%] restapi/introduction
reading sources... [ 61%] restapi/market
reading sources... [ 64%] restapi/mychannel
reading sources... [ 67%] restapi/playlists
reading sources... [ 70%] restapi/rssfeeds
reading sources... [ 74%] restapi/search
reading sources... [ 77%] restapi/settings
reading sources... [ 80%] restapi/state
reading sources... [ 83%] restapi/statistics
reading sources... [ 87%] restapi/torrentinfo
reading sources... [ 90%] restapi/torrents
reading sources... [ 93%] restapi/wallets
reading sources... [ 96%] trustchain
reading sources... [100%] twisted101

/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:8: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:8: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:8: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:8: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:8: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:8: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:8: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:22: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/development/development.rst:3: WARNING: Duplicate explicit target name: "here".
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/index.rst:11: WARNING: toctree contains reference to nonexisting document u'architecture'
../README.rst:3: WARNING: Duplicate explicit target name: "here".
../README.rst:3: WARNING: Duplicate explicit target name: "here".
WARNING: autodoc: failed to import module u'channels.channels_discovered_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named channels
WARNING: autodoc: failed to import module u'channels.channels_popular_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named channels
WARNING: autodoc: failed to import module u'channels.channels_subscription_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named channels
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/Core/Modules/restapi/debug_endpoint.py:docstring of Tribler.Core.Modules.restapi.debug_endpoint.DebugLogEndpoint.render_GET:15: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/Core/Modules/restapi/debug_endpoint.py:docstring of Tribler.Core.Modules.restapi.debug_endpoint.DebugLogEndpoint.render_GET:17: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/Core/Modules/restapi/debug_endpoint.py:docstring of Tribler.Core.Modules.restapi.debug_endpoint.DebugLogEndpoint.render_GET:21: WARNING: Block quote ends without a blank line; unexpected unindent.
WARNING: autodoc: failed to import module u'downloads_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named pony.orm
WARNING: autodoc: failed to import module u'events_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "../Tribler/Core/Modules/restapi/events_endpoint.py", line 6, in <module>
    from ipv8.messaging.anonymization.tunnel import Circuit
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/messaging/anonymization/tunnel.py", line 116, in <module>
    class TunnelExitSocket(Tunnel, DatagramProtocol, TaskManager):
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/restapi/introduction.rst:76: WARNING: toctree contains reference to nonexisting document u'restapi/variables'
WARNING: autodoc: failed to import module u'market.asks_bids_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "../Tribler/Core/Modules/restapi/market/__init__.py", line 6, in <module>
    from Tribler.community.market.community import MarketCommunity
  File "../Tribler/community/market/community.py", line 134, in <module>
    class MarketCommunity(Community, BlockListener):
  File "../Tribler/community/market/community.py", line 138, in MarketCommunity
    master_peer = Peer(unhexlify("4c69624e61434c504b3ab5bb7dc5a3a61de442585122b24c9f752469a212dc6d8ffa3d42bbf9c2f8d10"
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/peer.py", line 23, in __init__
    self.key = default_eccrypto.key_from_public_bin(key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/keyvault/crypto.py", line 107, in key_from_public_bin
    return LibNaCLPK(string[10:])
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/keyvault/public/libnaclkey.py", line 27, in __init__
    pk, vk = (binarykey[:libnacl.crypto_box_SECRETKEYBYTES],
TypeError: slice indices must be integers or None or have an __index__ method

WARNING: autodoc: failed to import module u'market.orders_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "../Tribler/Core/Modules/restapi/market/__init__.py", line 6, in <module>
    from Tribler.community.market.community import MarketCommunity
  File "../Tribler/community/market/community.py", line 134, in <module>
    class MarketCommunity(Community, BlockListener):
  File "../Tribler/community/market/community.py", line 138, in MarketCommunity
    master_peer = Peer(unhexlify("4c69624e61434c504b3ab5bb7dc5a3a61de442585122b24c9f752469a212dc6d8ffa3d42bbf9c2f8d10"
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/peer.py", line 23, in __init__
    self.key = default_eccrypto.key_from_public_bin(key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/keyvault/crypto.py", line 107, in key_from_public_bin
    return LibNaCLPK(string[10:])
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/keyvault/public/libnaclkey.py", line 27, in __init__
    pk, vk = (binarykey[:libnacl.crypto_box_SECRETKEYBYTES],
TypeError: slice indices must be integers or None or have an __index__ method

WARNING: autodoc: failed to import module u'market.transactions_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "../Tribler/Core/Modules/restapi/market/__init__.py", line 6, in <module>
    from Tribler.community.market.community import MarketCommunity
  File "../Tribler/community/market/community.py", line 134, in <module>
    class MarketCommunity(Community, BlockListener):
  File "../Tribler/community/market/community.py", line 138, in MarketCommunity
    master_peer = Peer(unhexlify("4c69624e61434c504b3ab5bb7dc5a3a61de442585122b24c9f752469a212dc6d8ffa3d42bbf9c2f8d10"
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/peer.py", line 23, in __init__
    self.key = default_eccrypto.key_from_public_bin(key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/keyvault/crypto.py", line 107, in key_from_public_bin
    return LibNaCLPK(string[10:])
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/Tribler/pyipv8/ipv8/keyvault/public/libnaclkey.py", line 27, in __init__
    pk, vk = (binarykey[:libnacl.crypto_box_SECRETKEYBYTES],
TypeError: slice indices must be integers or None or have an __index__ method

WARNING: autodoc: failed to import module u'channels.my_channel_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named channels
WARNING: autodoc: failed to import module u'channels.channels_playlists_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named channels
WARNING: autodoc: failed to import module u'channels.channels_rss_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named channels
WARNING: autodoc: failed to import module u'search_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named pony.orm
WARNING: autodoc: failed to import module u'settings_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "../Tribler/Core/Modules/restapi/settings_endpoint.py", line 7, in <module>
    from Tribler.Core.CreditMining.CreditMiningManager import CreditMiningManager
  File "../Tribler/Core/CreditMining/CreditMiningManager.py", line 21, in <module>
    from Tribler.Core.TorrentDef import TorrentDefNoMetainfo
  File "../Tribler/Core/TorrentDef.py", line 19, in <module>
    from Tribler.Core.Utilities.utilities import http_get, is_valid_url, parse_magnetlink
  File "../Tribler/Core/Utilities/utilities.py", line 21, in <module>
    from twisted.internet.ssl import ClientContextFactory
RuntimeError: sys.path must be a list of directory names

WARNING: autodoc: failed to import module u'torrentinfo_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named lz4.frame
WARNING: autodoc: failed to import module u'channels.channels_torrents_endpoint' from module u'Tribler.Core.Modules.restapi'; the following exception was raised:
No module named channels
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  3%] building/building
writing output... [  6%] building/building_on_osx
writing output... [  9%] building/building_on_windows
writing output... [ 12%] contributing
writing output... [ 16%] development/development
writing output... [ 19%] development/development_on_linux
writing output... [ 22%] development/development_on_osx
writing output... [ 25%] development/development_on_windows
writing output... [ 29%] development_methodology
writing output... [ 32%] index
writing output... [ 35%] introduction
writing output... [ 38%] restapi/channels_discovered
writing output... [ 41%] restapi/channels_popular
writing output... [ 45%] restapi/channels_subscribed
writing output... [ 48%] restapi/debug
writing output... [ 51%] restapi/downloads
writing output... [ 54%] restapi/events
writing output... [ 58%] restapi/introduction
writing output... [ 61%] restapi/market
writing output... [ 64%] restapi/mychannel
writing output... [ 67%] restapi/playlists
writing output... [ 70%] restapi/rssfeeds
writing output... [ 74%] restapi/search
writing output... [ 77%] restapi/settings
writing output... [ 80%] restapi/state
writing output... [ 83%] restapi/statistics
writing output... [ 87%] restapi/torrentinfo
writing output... [ 90%] restapi/torrents
writing output... [ 93%] restapi/wallets
writing output... [ 96%] trustchain
writing output... [100%] twisted101

building/building_on_windows.rst:1: WARNING: undefined label: tribler_dev_windows (if the link has no caption the label must precede a section header)
/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/building/building_on_windows.rst:1: WARNING: undefined label: tribler_dev_windows (if the link has no caption the label must precede a section header)
generating indices... genindex http-routingtable py-modindex
highlighting module code... [ 25%] Tribler.Core.Modules.restapi.debug_endpoint
highlighting module code... [ 50%] Tribler.Core.Modules.restapi.state_endpoint
highlighting module code... [ 75%] Tribler.Core.Modules.restapi.statistics_endpoint
highlighting module code... [100%] Tribler.Core.Modules.restapi.wallets_endpoint

writing additional pages... search
copying static files... WARNING: html_static_path entry u'/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/_static' does not exist
done
copying readthedocs static files... done
copying searchtools... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 42 warnings.

The HTML pages are in _build/html.
```

**Comment by qstokkink** [comment]
@devos50 this is fixed now, right?

**Comment by devos50** [comment]
Yes!
