### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4524]
From error reporter - Tribler 7.3.0 - beta3
```python
Traceback (most recent call last):
File "TriblerGUI\core_manager.py", line 118, in on_received_state
RuntimeError: [Failure instance: Traceback: <type 'exceptions.ValueError'>: The filename, directory name, or volume label syntax is incorrect
run_tribler.py:85:start_tribler
Tribler\Core\Session.py:432:start
lib\site-packages\twisted\internet\defer.py:321:addCallback
lib\site-packages\twisted\internet\defer.py:310:addCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\Session.py:429:load_checkpoint
Tribler\Core\Session.py:384:load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:570:load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:567:do_load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:599:resume_download
Tribler\Core\TorrentDef.py:115:load_from_dict
Tribler\Core\TorrentDef.py:68:__init__
]
```

```
Traceback (most recent call last):
File "TriblerGUI\core_manager.py", line 118, in on_received_state
RuntimeError: [Failure instance: Traceback: <type 'exceptions.ValueError'>: La syntaxe du nom de fichier, de r\xe9pertoire ou de volume est incorrecte
run_tribler.py:85:start_tribler
Tribler\Core\Session.py:432:start
lib\site-packages\twisted\internet\defer.py:321:addCallback
lib\site-packages\twisted\internet\defer.py:310:addCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\Session.py:429:load_checkpoint
Tribler\Core\Session.py:384:load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:570:load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:567:do_load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:599:resume_download
Tribler\Core\TorrentDef.py:115:load_from_dict
Tribler\Core\TorrentDef.py:68:__init__
]
```

**Comment by ichorid** [comment]
The paths system is not completely Unicode-proof. To reproduce something like this, run Tribler with
`env TSTATEDIR="/tmp/лололол" ./tribler.sh`

**Comment by ichorid** [comment]
In Python2, `str` is bytes. Libtorrent returns `str` for paths. Tribler saves download checkpoints as `config` files, which are essentially just stripped Python dicts code. Also, on Windows one really can produce a *malformed* filesystem path, while on Unix there is no such thing because any bytes string can be interpreted as a correct path.

3 months ago @devos50 removed our old Python-base torrent metainfo checker in favor of Libtorrent-based one in https://github.com/Tribler/tribler/blob/b26512ec5fbb6ad5e70262af534c6fba59bc0c66/Tribler/Core/TorrentDef.py#L66
As our old checker was written in Python, it was completely fine saving and loading metainfo for torrent state to and from `config` files.

Here is my theory (still have to figure out how to prove it):
when a path in a torrent metainfo contains non-ascii-characters, it is handled out as bytes by Libtorrent. These bytes are `str` in python2, and are properly saved to disk as `\x`-escaped bytes. However, when loaded from disk, these are interpreted as an ascii-string (which is correct). Windows then tries to interpret `\` as path components and it obviously can't.

**Comment by xoriole** [comment]
Reopening referencing error report [#25093](http://reporter.tribler.org/stacktrace/25093)- Tribler 7.3.0-beta5
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.ValueError'>: La sintassi del nome del file, della directory o del volume non \xe8 corretta
lib\site-packages\twisted\internet\defer.py:1442:gotResult
lib\site-packages\twisted\internet\defer.py:1389:_inlineCallbacks
lib\site-packages\twisted\internet\defer.py:459:callback
lib\site-packages\twisted\internet\defer.py:567:_startRunCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\Session.py:429:load_checkpoint
Tribler\Core\Session.py:384:load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:573:load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:570:do_load_checkpoint
Tribler\Core\APIImplementation\LaunchManyCore.py:602:resume_download
Tribler\Core\TorrentDef.py:133:load_from_dict
Tribler\Core\TorrentDef.py:86:__init__
]
```
