### ISSUE TITLE
GigaChannel manager startup breaks on empty personal channel

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4598]
Latest devel:
```python
 File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/Core/Modules/gigachannel_manager.py", line 94, in service_channels
    self.remove_cruft_channels()
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/Core/Modules/gigachannel_manager.py", line 89, in remove_cruft_channels
    if bytes(d.get_def().infohash) not in subscribed_infohashes]
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/Core/TorrentDef.py", line 265, in get_name_utf8
    return escape_as_utf8(self.get_name(), self.get_encoding())
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/Core/TorrentDef.py", line 259, in get_name
    return self.torrent_parameters['name']
KeyError: 'name'
```

Seems like Tribler can't restore 'name' field from `.state` file.

**Comment by ichorid** [comment]
Accompanied by this one:
```python
ERROR   1561210273.98            LaunchManyCore:591  (TriblerLaunchMany)  Exception while loading pstate: None
Traceback (most recent call last):
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/Core/APIImplementation/LaunchManyCore.py", line 583, in load_download_pstate_noexc
    basename = hexlify(infohash) + '.state'
TypeError: b2a_hex() argument 1 must be string or buffer, not None
```

**Comment by ichorid** [comment]
After doing some debugging, this is triggered by me only doing nested channels support half-way.

**Comment by devos50** [comment]
Also got this one, see #4602. However, I got some more info:

```python
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/Library/Python/2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/Library/Python/2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 520, in sesscb_states_callback
    safename = tdef.get_name_as_unicode()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 281, in get_name_as_unicode
    if "name.utf-8" in self.metainfo["info"]:
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```
