### ISSUE TITLE
Sequence of errors after creating a channel, killing Tribler and restarting it

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4602]
I get the following sequence of errors after I created a channel, hard-crashed Tribler and restarted it again.

```
--stack--
  File "run_tribler.py", line 96, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 88, in start_tribler_core
    reactor.run()
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 1266, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 1246, in startRunning
    ReactorBase.startRunning(self)
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 759, in startRunning
    self.fireSystemEvent('startup')
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 710, in fireSystemEvent
    event.fireEvent()
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(*args, **kwargs)
  File "run_tribler.py", line 85, in start_tribler
    session.start()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Session.py", line 438, in start
    return startup_deferred.addCallback(load_checkpoint).addCallback(start_gigachannel_manager)
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Session.py", line 437, in start_gigachannel_manager
    self.lm.gigachannel_manager.start()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/gigachannel_manager.py", line 57, in start
    TorrentDef.load_from_dict(my_channel.consolidate_channel_torrent())
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 137, in load_from_dict
    return TorrentDef(metainfo=metainfo)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 71, in __init__
    traceback.print_stack()
ERROR   1561377003.55            LaunchManyCore:591  (TriblerLaunchMany)  Exception while loading pstate: None
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 583, in load_download_pstate_noexc
    basename = hexlify(infohash) + '.state'
TypeError: must be string or buffer, not None
ERROR   1561377003.55       gigachannel_manager:60   (GigaChannelManager)  Error when tried to resume personal channel seeding on GigaChannel Manager startup
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/gigachannel_manager.py", line 58, in start
    self.updated_my_channel(tdef)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/gigachannel_manager.py", line 238, in updated_my_channel
    self.session.lm.add(tdef, dcfg)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 378, in add
    setup_deferred.addCallback(self.on_download_handle_created)
AttributeError: 'NoneType' object has no attribute 'addCallback'
ERROR   1561377003.56       gigachannel_manager:96   (GigaChannelManager)  Error when tried to check for cruft channels
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/gigachannel_manager.py", line 94, in service_channels
    self.remove_cruft_channels()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/gigachannel_manager.py", line 89, in remove_cruft_channels
    if bytes(d.get_def().infohash) not in subscribed_infohashes]
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 269, in get_name_utf8
    return escape_as_utf8(self.get_name(), self.get_encoding())
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 263, in get_name
    return self.torrent_parameters['name']
KeyError: 'name'
INFO    1561377003.77     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
WARNING 1561377003.81            tribler_window:353  (root)  Received duplicate Tribler Core started event
ERROR   1561377003.83              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.KeyError'>: 'name'
/Library/Python/2.7/site-packages/twisted/web/http.py:2099:lineReceived
/Library/Python/2.7/site-packages/twisted/web/http.py:2190:allContentReceived
/Library/Python/2.7/site-packages/twisted/web/http.py:917:requestReceived
/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/restapi/rest_manager.py:118:process
--- <exception caught here> ---
/Library/Python/2.7/site-packages/twisted/web/server.py:199:process
/Library/Python/2.7/site-packages/twisted/web/server.py:259:render
/Library/Python/2.7/site-packages/twisted/web/resource.py:250:render
/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py:238:render_GET
/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py:269:get_name_utf8
/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py:263:get_name
]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/web/server.py", line 199, in process
    self.render(resrc)
  File "/Library/Python/2.7/site-packages/twisted/web/server.py", line 259, in render
    body = resrc.render(self)
  File "/Library/Python/2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py", line 238, in render_GET
    tdef.get_name_utf8(), tdef.get_infohash()) if download.get_channel_download() else tdef.get_name_utf8()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 269, in get_name_utf8
    return escape_as_utf8(self.get_name(), self.get_encoding())
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 263, in get_name
    return self.torrent_parameters['name']
KeyError: 'name'
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/Library/Python/2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/Library/Python/2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 520, in sesscb_states_callback
    safename = tdef.get_name_as_unicode()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 281, in get_name_as_unicode
    if "name.utf-8" in self.metainfo["info"]:
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

I also printed the stack when calling the `__init__` method of `TorrentDef`. A quick look seems to indicate that the problem could be related to `consolidate_channel_torrent()` returning `None`. Probably I got a corrupted channel torrent or something similar?

**Comment by qstokkink** [comment]
Related to #4598?

**Comment by qstokkink** [comment]
Actually, mostly duplicate of #4598, except for the following:

```python
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/Library/Python/2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/Library/Python/2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 520, in sesscb_states_callback
    safename = tdef.get_name_as_unicode()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/TorrentDef.py", line 281, in get_name_as_unicode
    if "name.utf-8" in self.metainfo["info"]:
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by devos50** [comment]
Marked as duplicate
