### ISSUE TITLE
Error when switching channel download to one hop

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4605]
```python
ERROR   1561381744.26        downloads_endpoint:499  (DownloadSpecificEndpoint)  [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith'
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py:460:callback
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py:1418:_inlineCallbacks
/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py:435:update_download_hops
/home/quinten/Documents/tribler/Tribler/Core/Session.py:242:start_download_from_tdef
/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py:354:add
/home/quinten/Documents/tribler/Tribler/Core/DownloadConfig.py:81:get_dest_dir
/usr/lib/python2.7/posixpath.py:70:join
]
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 435, in update_download_hops
    self.session.start_download_from_tdef(download.tdef, dscfg, pstate=pstate)
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 242, in start_download_from_tdef
    return self.lm.add(torrent_definition, download_startup_config, pstate=pstate, hidden=hidden)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 354, in add
    if not os.path.isdir(dscfg.get_dest_dir()):
  File "/home/quinten/Documents/tribler/Tribler/Core/DownloadConfig.py", line 81, in get_dest_dir
    dest_dir = os.path.join(self.state_dir, dest_dir)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by devos50** [comment]
Can confirm

**Comment by qstokkink** [comment]
There may be something wrong with our `TorrentDef` class, considering #4598. We should look into the recent changes.
