### ISSUE TITLE
Unicode error on duplicate download

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4613]
When adding a torrent to my channel which was already there.

```python
INFO    1561455321.27            LaunchManyCore:364  (TriblerLaunchMany)  Torrent already exists in the downloads. Infohash:47f24c339f76098366bf193e67e427e5e4b321e9
ERROR   1561455321.34              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\U0001f4a9' in position 0: ordinal not in range(128)
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/http.py:2115:_finishRequestBody
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/http.py:2190:allContentReceived
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/http.py:917:requestReceived
/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/rest_manager.py:118:process
--- <exception caught here> ---
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py:198:process
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py:258:render
/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py:250:render
<auto generated wrapper of render_PUT() function>:2:render_PUT
/home/quinten/.local/lib/python2.7/site-packages/pony/orm/core.py:528:new_func
/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/mychannel_endpoint.py:323:render_PUT
<auto generated wrapper of add_torrent_to_channel() function>:2:add_torrent_to_channel
/home/quinten/.local/lib/python2.7/site-packages/pony/orm/core.py:515:new_func
/home/quinten/Documents/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py:296:add_torrent_to_channel
/home/quinten/Documents/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py:252:metadata_conflicting
]
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 198, in process
    self.render(resrc)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/server.py", line 258, in render
    body = resrc.render(self)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "<auto generated wrapper of render_PUT() function>", line 2, in render_PUT
  File "/home/quinten/.local/lib/python2.7/site-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/restapi/mychannel_endpoint.py", line 323, in render_PUT
    my_channel.add_torrent_to_channel(torrent_def, extra_info)
  File "<auto generated wrapper of add_torrent_to_channel() function>", line 2, in add_torrent_to_channel
  File "/home/quinten/.local/lib/python2.7/site-packages/pony/orm/core.py", line 515, in new_func
    return func(*args, **kwargs)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py", line 296, in add_torrent_to_channel
    if old_torrent.metadata_conflicting(new_entry_dict):
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py", line 252, in metadata_conflicting
    if (comp not in b) or (str(a[comp]) == str(b[comp])):
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4a9' in position 0: ordinal not in range(128)
```

**Comment by qstokkink** [comment]
Seems to be cause by `str` casting:

```python
>>> a = u'\U0001f4a9'
>>> str(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by qstokkink** [comment]
However, under Python 3:

```python
>>> a = u'\U0001f4a9'
>>> str(a)
'💩'
```

**Comment by qstokkink** [comment]
We can trivially fix this by using `unicode` instead of `str`:

```python
>>> str(u'\U0001f4a9')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
>>> unicode(u'\U0001f4a9')
u'\U0001f4a9'
```
