### ISSUE TITLE
Crash when clicking debug tab

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4623]
```python
ERROR   1561469701.07            tribler_window:74   (root)  Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/TriblerGUI/tribler_window.py", line 915, in clicked_menu_button_debug
    self.debug_window = DebugWindow(self.tribler_settings, self.tribler_version)
  File "/home/quinten/Documents/tribler/TriblerGUI/debug_window.py", line 156, in __init__
    self.window().debug_tab_widget.setTabEnabled(2, settings and settings['trustchain']['enabled'])
TypeError: setTabEnabled(self, int, bool): argument 2 has unexpected type 'NoneType
```

**Comment by qstokkink** [comment]
```python
>>> print {0: None} and {0: None}[0]
None
```

**Comment by xoriole** [comment]
This should already be fixed by now
