### ISSUE TITLE
Tribler crashes with new PyQt version.

### ISSUE THREAD

**Issue by Zerophase** [Tribler/tribler#4666]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.3.0 beta6

##### Operating system and version: #####
Up to date Arch Linux.

##### Steps to reproduce the behavior: #####
Install Tribler on an Arch Linux distribution.

##### Expected behavior: #####
Tribler opens.

##### Actual behavior: #####
Tribler fails to find libraries and crashes before opening. It's an issue with Arch Linux updating to PyQt 5.13.

##### Relevant log file output: #####
https://pastebin.com/LaDR4vTy

**Comment by xoriole** [comment]
@Zerophase Thank you for reporting. 

From the logs, it seems more like Unicode issue than PyQt5 itself. Some Unicode characters in `mainwindow.ui` are not parsed properly.
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2193' in position 0: ordinal not in range(128)
```

**Comment by qstokkink** [comment]
This seems worse than just `PyQt5`, even in the `ETree` package in the Python base:

```python
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 716, in addHeader
   status_tip = props.getProperty(elem, 'statusTip')
 File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 389, in getProperty
   return self._getChild("property", elem, name, default)
 File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 382, in _getChild
   for prop in elem.findall(elem_tag):
 File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 390, in findall
   return ElementPath.findall(self, path, namespaces)
 File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 293, in findall
   return list(iterfind(elem, path, namespaces))
 File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 276, in iterfind
   for select in selector:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2193' in position 0: ordinal not in range(128)
```

Apparently it is loading a status tip from XML (which appears on the bottom of the main screen - which we don't use) and it encounters the `u'\u2193'` character (which is not a human readable character).

Weird. Seems like there is something fundamentally wrong with Python.

**Comment by MeadowHillSoftware** [comment]
I'm having the same problem with 7.3.0 Beta 4 on Manjaro:

ERROR:root:Fault Handler module not found.
INFO    1563637355.13        single_application:28   (root)  __init__()
qt5ct: using qt5ct plugin
INFO    1563637355.20        single_application:54   (root)    self._outSocket.error() = '2'
INFO    1563637355.20        single_application:64   (root)  __init__(): returning
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
ERROR   1563637355.99            tribler_window:74   (root)  Traceback (most recent call last):
  File "run_tribler.py", line 120, in <module>
    window = TriblerWindow()
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 138, in __init__
    uic.loadUi(get_ui_file_path('mainwindow.ui'), self)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/__init__.py", line 227, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 1030, in parse
    actor(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 716, in addHeader
    status_tip = props.getProperty(elem, 'statusTip')
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 389, in getProperty
    return self._getChild("property", elem, name, default)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 382, in _getChild
    for prop in elem.findall(elem_tag):
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 390, in findall
    return ElementPath.findall(self, path, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 293, in findall
    return list(iterfind(elem, path, namespaces))
  File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 276, in iterfind
    for select in selector:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2193' in position 0: ordinal not in range(128)

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 77, in on_exception
    self.delete_tray_icon()
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 289, in delete_tray_icon
    if self.tray_icon:
AttributeError: 'TriblerWindow' object has no attribute 'tray_icon'

Original exception was:
Traceback (most recent call last):
  File "run_tribler.py", line 120, in <module>
    window = TriblerWindow()
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 138, in __init__
    uic.loadUi(get_ui_file_path('mainwindow.ui'), self)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/__init__.py", line 227, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 1030, in parse
    actor(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 716, in addHeader
    status_tip = props.getProperty(elem, 'statusTip')
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 389, in getProperty
    return self._getChild("property", elem, name, default)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 382, in _getChild
    for prop in elem.findall(elem_tag):
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 390, in findall
    return ElementPath.findall(self, path, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 293, in findall
    return list(iterfind(elem, path, namespaces))
  File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 276, in iterfind
    for select in selector:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2193' in position 0: ordinal not in range(128)

Since this is related to Unicode characters, could this be font-related? I seem to recall receiving a font update not long before this happened.

**Comment by synctext** [comment]
We fixed lots of errors in Beta6 and now today RC1. Could you try that?

**Comment by qstokkink** [comment]
Correction to my earlier post: in `UTF-16`, `\u2193` is the down arrow.

You could try editing the first line in every file in this folder: https://github.com/Tribler/tribler/tree/devel/TriblerGUI/qt_resources .

From: `<?xml version="1.0" encoding="UTF-8"?>`
To: `<?xml version="1.0" encoding="UTF-16"?>`

Note: this is a bit of a long shot.

**Comment by devos50** [comment]
I suspect this is related to the fact that we are using the Unicode symbol for the down arrow in the trust page. Besides this crash, I noticed they do not correctly render when running Tribler in a packaged (frozen) environment on Mac. I would suggest to use images instead.

**Comment by qstokkink** [comment]
If we can just use images, let's do that then. Also, as this is actually making Tribler unusable let's fix this before the `7.3` release.

**Comment by MeadowHillSoftware** [comment]
Changing "UTF-8" to "UTF-16" results in this error:

ERROR:root:Fault Handler module not found.
Traceback (most recent call last):
  File "run_tribler.py", line 115, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 46, in <module>
    fc_home_recommended_item, _ = uic.loadUiType(get_ui_file_path('home_recommended_item.ui'))
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/__init__.py", line 199, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix, import_from)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/Compiler/compiler.py", line 111, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 1013, in parse
    document = parse(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: encoding specified in XML declaration is incorrect: line 1, column 30

**Comment by MeadowHillSoftware** [comment]
RC1 crashes too. Skimming the error message, it looks the same (other than some line numbers changing):

ERROR:root:Fault Handler module not found.
INFO    1563817584.49        single_application:28   (root)  __init__()
qt5ct: using qt5ct plugin
INFO    1563817584.55        single_application:54   (root)    self._outSocket.error() = '2'
INFO    1563817584.55        single_application:64   (root)  __init__(): returning
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
ERROR   1563817585.28            tribler_window:73   (root)  Traceback (most recent call last):
  File "run_tribler.py", line 127, in <module>
    window = TriblerWindow()
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 137, in __init__
    uic.loadUi(get_ui_file_path('mainwindow.ui'), self)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/__init__.py", line 227, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 1030, in parse
    actor(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 716, in addHeader
    status_tip = props.getProperty(elem, 'statusTip')
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 389, in getProperty
    return self._getChild("property", elem, name, default)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 382, in _getChild
    for prop in elem.findall(elem_tag):
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 390, in findall
    return ElementPath.findall(self, path, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 293, in findall
    return list(iterfind(elem, path, namespaces))
  File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 276, in iterfind
    for select in selector:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2193' in position 0: ordinal not in range(128)

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 76, in on_exception
    self.delete_tray_icon()
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 287, in delete_tray_icon
    if self.tray_icon:
AttributeError: 'TriblerWindow' object has no attribute 'tray_icon'

Original exception was:
Traceback (most recent call last):
  File "run_tribler.py", line 127, in <module>
    window = TriblerWindow()
  File "/home/user/MHS/tribler/TriblerGUI/tribler_window.py", line 137, in __init__
    uic.loadUi(get_ui_file_path('mainwindow.ui'), self)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/__init__.py", line 227, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 1030, in parse
    actor(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/uiparser.py", line 716, in addHeader
    status_tip = props.getProperty(elem, 'statusTip')
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 389, in getProperty
    return self._getChild("property", elem, name, default)
  File "/usr/lib/python2.7/site-packages/PyQt5/uic/properties.py", line 382, in _getChild
    for prop in elem.findall(elem_tag):
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 390, in findall
    return ElementPath.findall(self, path, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 293, in findall
    return list(iterfind(elem, path, namespaces))
  File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 276, in iterfind
    for select in selector:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2193' in position 0: ordinal not in range(128)

**Comment by devos50** [comment]
Hmm on second inspection, it seems that the down arrow is used on the downloads page. It has been there for almost 3 years now.

One obvious solution would be to replace the down (and up) arrow with `(down)` and `(up)` strings but I would rather find out the root cause of this. It seems that the `ascii` codec is used and that it tries to encode a UTF-8 character.

**Comment by devos50** [comment]
@MeadowHillSoftware I just made a new release where I replaced the up/down arrows with text. Could you please check out [this build](https://jenkins-ci.tribler.org/job/_One-Click-Release-Custom/96/) and let us know whether it works for you?

**Comment by MeadowHillSoftware** [comment]
RC1 Build #96 is working.

**Comment by devos50** [comment]
Great to hear! Please re-open the issue if it happens again 👍
