### ISSUE TITLE
Typing `'` into search bar shows error message

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4669]
##### Tribler version/branch+revision: #####

v7.3.0-beta6

##### Steps to reproduce the behavior: #####

1. Open Tribler
2. Type `'` into the search field (or text containing it)
3. Press Enter

##### Expected behavior: #####

It search for keywords containing apostrophe or just ignores the character

##### Actual behavior: #####

Error message is being displayed, no results are shown

##### Relevant log file output: #####

```
ERROR   1562798467.86              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <class 'pony.orm.dbapiprovider.OperationalError'>: fts5: syntax error near "'"
/usr/lib/python2.7/dist-packages/twisted/web/http.py:2099:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:2190:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:917:requestReceived
/home/tribler/tribler/Tribler/Core/Modules/restapi/rest_manager.py:118:process
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:199:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:259:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/home/tribler/tribler/Tribler/Core/Modules/restapi/search_endpoint.py:159:render_GET
/home/tribler/tribler/Tribler/Core/Modules/restapi/metadata_endpoint.py:60:get_total_count
<auto generated wrapper of get_entries_count() function>:2:get_entries_count
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:528:new_func
/home/tribler/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py:221:get_entries_count
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6189:count
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6150:_aggregate
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:941:_exec_sql
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:1771:reconnect
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:939:_exec_sql
<auto generated wrapper of execute() function>:2:execute
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py:61:wrap_dbapi_exceptions
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 199, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 259, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/search_endpoint.py", line 159, in render_GET
    return self.get_total_count(self.session.lm.mds.TorrentMetadata, sanitized, search_uuid=search_uuid)
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/metadata_endpoint.py", line 60, in get_total_count
    total_count = md_class.get_entries_count(**sanitized)
  File "<auto generated wrapper of get_entries_count() function>", line 2, in get_entries_count
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/home/tribler/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py", line 221, in get_entries_count
    return cls.get_entries_query(**kwargs).count()
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 6189, in count
    return query._aggregate('COUNT', distinct)
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 6150, in _aggregate
    cursor = query._database._exec_sql(sql, arguments)
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 941, in _exec_sql
    connection = cache.reconnect(e)
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 1771, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 939, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 61, in wrap_dbapi_exceptions
    raise OperationalError(e)
OperationalError: fts5: syntax error near "'"
ERROR   1562798467.92           search_endpoint:135  (SearchEndpoint)  Error while performing DB search: [Failure instance: Traceback: <class 'pony.orm.dbapiprovider.OperationalError'>: fts5: syntax error near "'"
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
/usr/lib/python2.7/threading.py:754:run
/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py:46:work
/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:250:inContext
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/lib/python2.7/dist-packages/twisted/python/context.py:122:callWithContext
/usr/lib/python2.7/dist-packages/twisted/python/context.py:85:callWithContext
/home/tribler/tribler/Tribler/Core/Modules/restapi/search_endpoint.py:118:search_db
<auto generated wrapper of get_entries() function>:2:get_entries
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:515:new_func
/home/tribler/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py:216:get_entries
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6130:__getitem__
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6132:_fetch
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6239:__init__
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:5773:_actual_fetch
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:941:_exec_sql
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:1771:reconnect
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:939:_exec_sql
<auto generated wrapper of execute() function>:2:execute
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py:61:wrap_dbapi_exceptions
]
ERROR   1562798467.99   tribler_request_manager:339  (root)  No json object could be decoded from data: 
INFO    1562798468.49       CreditMiningManager:342  (CreditMiningManager)  Downloading: 0, Uploading: 0, Stopped: 0
INFO    1562798468.49       CreditMiningManager:344  (CreditMiningManager)  0 active download(s), 0.000 MB uploaded, 0.000 MB downloaded
INFO    1562798470.07                 community:167  (GigaChannelCommunity)  Started remote search for query:Dictator's
ERROR   1562798470.07              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <class 'pony.orm.dbapiprovider.OperationalError'>: fts5: syntax error near "'"
/usr/lib/python2.7/dist-packages/twisted/web/http.py:2099:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:2190:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:917:requestReceived
/home/tribler/tribler/Tribler/Core/Modules/restapi/rest_manager.py:118:process
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:199:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:259:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/home/tribler/tribler/Tribler/Core/Modules/restapi/search_endpoint.py:159:render_GET
/home/tribler/tribler/Tribler/Core/Modules/restapi/metadata_endpoint.py:60:get_total_count
<auto generated wrapper of get_entries_count() function>:2:get_entries_count
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:528:new_func
/home/tribler/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py:221:get_entries_count
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6189:count
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6150:_aggregate
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:941:_exec_sql
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:1771:reconnect
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:939:_exec_sql
<auto generated wrapper of execute() function>:2:execute
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py:61:wrap_dbapi_exceptions
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 199, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 259, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/search_endpoint.py", line 159, in render_GET
    return self.get_total_count(self.session.lm.mds.TorrentMetadata, sanitized, search_uuid=search_uuid)
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/metadata_endpoint.py", line 60, in get_total_count
    total_count = md_class.get_entries_count(**sanitized)
  File "<auto generated wrapper of get_entries_count() function>", line 2, in get_entries_count
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/home/tribler/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py", line 221, in get_entries_count
    return cls.get_entries_query(**kwargs).count()
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 6189, in count
    return query._aggregate('COUNT', distinct)
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 6150, in _aggregate
    cursor = query._database._exec_sql(sql, arguments)
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 941, in _exec_sql
    connection = cache.reconnect(e)
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 1771, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py", line 939, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/home/tribler/.local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 61, in wrap_dbapi_exceptions
    raise OperationalError(e)
OperationalError: fts5: syntax error near "'"
ERROR   1562798470.07           search_endpoint:135  (SearchEndpoint)  Error while performing DB search: [Failure instance: Traceback: <class 'pony.orm.dbapiprovider.OperationalError'>: fts5: syntax error near "'"
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
/usr/lib/python2.7/threading.py:754:run
/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py:46:work
/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:250:inContext
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/lib/python2.7/dist-packages/twisted/python/context.py:122:callWithContext
/usr/lib/python2.7/dist-packages/twisted/python/context.py:85:callWithContext
/home/tribler/tribler/Tribler/Core/Modules/restapi/search_endpoint.py:118:search_db
<auto generated wrapper of get_entries() function>:2:get_entries
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:515:new_func
/home/tribler/tribler/Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py:216:get_entries
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6130:__getitem__
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6132:_fetch
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:6239:__init__
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:5773:_actual_fetch
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:941:_exec_sql
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:1771:reconnect
/home/tribler/.local/lib/python2.7/site-packages/pony/orm/core.py:939:_exec_sql
<auto generated wrapper of execute() function>:2:execute
```

**Comment by ichorid** [comment]
Confirmed, working on a patch.
