### ISSUE TITLE
IPv6 not supported on SOCKS

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4705]
7.3-rc1, five reports:

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\python\log.py", line 103, in callWithLogger

File "lib\site-packages\twisted\python\log.py", line 86, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 122, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 85, in callWithContext

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite

File "lib\site-packages\twisted\internet\tcp.py", line 208, in doRead

File "lib\site-packages\twisted\internet\tcp.py", line 214, in _dataReceived

File "Tribler\Core\Socks5\connection.py", line 57, in dataReceived

File "Tribler\Core\Socks5\connection.py", line 109, in _try_request

File "Tribler\Core\Socks5\conversion.py", line 179, in decode_request

File "Tribler\Core\Socks5\conversion.py", line 151, in __decode_address

Tribler.Core.Socks5.conversion.IPV6AddrError: IPV6 support not implemented
```

**Comment by devos50** [comment]
Fixed already by #4697
