### ISSUE TITLE
Trust screen is broken on devel

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4717]
As reported in #4713, clicking on the trust page in the GUI crashes Tribler with the following error:

```
Traceback (most recent call last):
File "/mnt/Binary/Tribler/tribler/TriblerGUI/widgets/trustgraphpage.py", line 320, in on_received_data
self.trust_plot.graph = json_graph.node_link_graph(data['graph_data'])
File "/usr/lib/python2.7/site-packages/networkx/readwrite/json_graph/node_link.py", line 158, in node_link_graph
graph = graph.to_directed()
File "/usr/lib/python2.7/site-packages/networkx/classes/graph.py", line 1583, in to_directed
G.graph.update(deepcopy(self.graph))
File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
y = copier(x, memo)
File "/usr/lib/python2.7/copy.py", line 256, in _deepcopy_dict
for key, value in x.iteritems():
UnicodeEncodeError: 'ascii' codec can't encode character u'\u25cf' in position 100: ordinal not in range(128)
```

**Comment by devos50** [comment]
@egbertbouman could you please have a look at this issue?

**Comment by xoriole** [comment]
Fixed with `pyqtgraph` implementation
