### ISSUE TITLE
(RC2) UnicodeEncodeError: 'ascii' codec can't encode character u'\u25cf' in position 105: ordinal not in range(128)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4731]
From the error reporter (issue #26094):

```
Traceback (most recent call last):
File "/home/<RETRACTED>/programs/tribler/TriblerGUI/widgets/trustgraphpage.py", line 320, in on_received_data
self.trust_plot.graph = json_graph.node_link_graph(data['graph_data'])
File "/usr/lib/python2.7/site-packages/networkx/readwrite/json_graph/node_link.py", line 158, in node_link_graph
graph = graph.to_directed()
File "/usr/lib/python2.7/site-packages/networkx/classes/graph.py", line 1583, in to_directed
G.graph.update(deepcopy(self.graph))
File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
y = copier(x, memo)
File "/usr/lib/python2.7/copy.py", line 256, in _deepcopy_dict
for key, value in x.iteritems():
UnicodeEncodeError: 'ascii' codec can't encode character u'\u25cf' in position 105: ordinal not in range(128)
```

**Comment by xoriole** [comment]
Trust graph based on `pyqtgraph` https://github.com/Tribler/tribler/pull/4734 does not use `networkx` to generate the graph in the GUI so we can wait for the release to see if this is still present.
