### ISSUE TITLE
Issue with channel download - [7.3.0-RC4]

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4768]
From reporter - `Tribler 7.3.0-RC4`
Platform: `Linux-5.2.8-arch1-1-ARCH-x86_64-with-glibc2.2.5`

```python
Traceback (most recent call last):
File "/home/user/programs/tribler/TriblerGUI/widgets/downloadspage.py", line 150, in on_received_downloads
item.update_with_download(download)
File "/home/user/programs/tribler/TriblerGUI/widgets/downloadwidgetitem.py", line 52, in update_with_download
self.update_item()
File "/home/user/programs/tribler/TriblerGUI/widgets/downloadwidgetitem.py", line 59, in update_item
if self.download_info["name"] == u"<old version of your channel>":
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-12: ordinal not in range(128)
```

**Comment by qstokkink** [comment]
Possibly the name is in `'ascii'` format with non-ascii characters:

```python
>>> if "\x80" == u"<old version of your channel>":
...  print "hi"
...
__main__:1: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>>> if "\x60" == u"<old version of your channel>":
...  print "hi"
...
>>> if u"\x80" == u"<old version of your channel>":
...  print "hi"
...
```

**Comment by ichorid** [comment]
python2:
```python
>>> b = b'\xc3\xa0'
>>> b == u"bla"
UnicodeWarning: Unicode equal comparison...

>>> b + u"bla"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

>>> b + "bla"
'\xc3\xa0bla'
```

python3:
```python
>>> b == u"bla"
False
>>> b == "bla"
False
```

In other words, the user's Python interpreter raises an error where our interpreters only do a warning. For me, makeing the right side of comparison to use the string type native to the interpreter seems like the best solution.

**Comment by ichorid** [comment]
Hmm.. Actually, the comparison is ever false, because it uses magic string. I'll just remove the feature.
