### ISSUE TITLE
UnicodeEncodeError - update torrent details tab

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4777]
Version: 7.3.0
Platform: Linux-5.2.9-arch1-1-ARCH-x86_64-with-glibc2.2.5
Uptime:21.2033410072
Report: [26575](http://reporter.tribler.org/stacktrace/26575)

```python
Traceback (most recent call last):
File "/home/gemdude46/programs/tribler/TriblerGUI/widgets/downloadspage.py", line 280, in on_download_item_clicked
self.window().download_details_widget.update_with_download(self.selected_items[0].download_info)
File "/home/gemdude46/programs/tribler/TriblerGUI/widgets/downloadsdetailstabwidget.py", line 38, in update_with_download
self.update_pages(new_download=did_change)
File "/home/gemdude46/programs/tribler/TriblerGUI/widgets/downloadsdetailstabwidget.py", line 100, in update_pages
status_string = DLSTATUS_STRINGS[eval(self.current_download["status"])]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by devos50** [comment]
As far as I know, the `status` field should only contain ascii-compatible characters. We have seen more weird unicode issues on Arch linux.

**Comment by ichorid** [comment]
`eval` were remove earlier by @xoriole . Closing this one.
