### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4789]
Observed this error in one of the PRs (Tests on Windows 64-bit [Py3]):

```
======================================================================
ERROR: Testing whether the API returns the right download when a download is added
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64_py3\tribler\Tribler\Test\Core\Modules\RestApi\base_api_test.py", line 79, in tearDown
    yield super(AbstractBaseApiTest, self).tearDown()
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\python\failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64_py3\tribler\Tribler\Test\test_as_server.py", line 335, in tearDown
    yield super(TestAsServer, self).tearDown()
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64_py3\tribler\Tribler\Test\test_as_server.py", line 205, in tearDown
    super(AbstractServer, self).tearDown()
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64_py3\tribler\Tribler\Test\test_as_server.py", line 81, in tearDown
    shutil.rmtree(six.text_type(temp_dir), ignore_errors=False)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\workspace\\jenkins2\\workspace\\GH_Tribler_PR_Tests\\PR_win64_py3\\tribler\\Tribler\\Test\\temp\\TestMetadataDownloadEndpoint_tribler_test_session_ORDKD0\\dot.Tribler\\channels\\591ebc0b1274c65794f907e17ee23dda0182a28b3a6b3dc2\\1567592175003.mdblob.lz4'
-------------------- >> begin captured logging << --------------------
```

**Comment by ichorid** [comment]
Fixed by #4806
