### ISSUE TITLE
[py3] TypeError: keys must be str, int, float, bool or None, not bytes

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4791]
When navigating to the token balance screen:

```
ERROR   1567609358.36              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <class 'TypeError'>: keys must be str, int, float, bool or None, not bytes
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/http.py:2146:lineReceived
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/http.py:2237:allContentReceived
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/http.py:937:requestReceived
/Users/martijndevos/Documents/tribler/Tribler/Core/Modules/restapi/rest_manager.py:118:process
--- <exception caught here> ---
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/server.py:217:process
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/server.py:284:render
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/resource.py:265:render
/Users/martijndevos/Documents/tribler/Tribler/pyipv8/ipv8/REST/trustchain_endpoint.py:143:render_GET
/Users/martijndevos/Documents/tribler/Tribler/pyipv8/ipv8/REST/base_endpoint.py:28:twisted_dumps
/Users/martijndevos/Documents/tribler/Tribler/pyipv8/ipv8/REST/json_util.py:98:dumps
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py:231:dumps
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py:199:encode
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py:257:iterencode
]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/server.py", line 217, in process
    self.render(resrc)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/server.py", line 284, in render
    body = resrc.render(self)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/web/resource.py", line 265, in render
    return m(request)
  File "/Users/martijndevos/Documents/tribler/Tribler/pyipv8/ipv8/REST/trustchain_endpoint.py", line 143, in render_GET
    return self.twisted_dumps({"blocks": blocks_list})
  File "/Users/martijndevos/Documents/tribler/Tribler/pyipv8/ipv8/REST/base_endpoint.py", line 28, in twisted_dumps
    return json.dumps(obj, ensure_ascii).encode('utf-8')
  File "/Users/martijndevos/Documents/tribler/Tribler/pyipv8/ipv8/REST/json_util.py", line 98, in dumps
    return json.dumps(obj, ensure_ascii=ensure_ascii)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not bytes
```

**Comment by devos50** [comment]
This is actually an IPv8 issue: converting a `TrustchainBlock` object to a dictionary results in values with type `bytes`, which is incompatible with the `twisted_dumps` method.

**Comment by qstokkink** [comment]
Note: this should be fixed in the endpoint, not the block class.

**Comment by qstokkink** [comment]
This is probably fixed by https://github.com/Tribler/py-ipv8/commit/e9ccd95049bab61ee43300f8dc6c49ecd21333c3#diff-a4544aafb87f5d0e5587e64021102735L448-L449

This *should* already be fixed by the latest pointer update, but feel free to reopen if the problem reoccurs.
