### ISSUE TITLE
[py3] builtins.RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4794]
Observed this error during the py3 tests:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/jenkins/ci/workspace/Test_tribler_devel_py3/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/hidden_services.py", line 183, in do_peer_discovery
    for info_hash, swarm in self.swarms.items():
builtins.RuntimeError: dictionary changed size during iteration
```

**Comment by devos50** [comment]
This is already fixed in IPv8, after updating the pointer the tests should consistently pass.
