### ISSUE TITLE
"not JSON serializable" error on chaning settings in the GUI

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4808]
When trying to change some settings in the GUI and save the changes

```python
Traceback (most recent call last):
  File "/home/vader/src/TRIBLER/Tribler/TriblerGUI/widgets/settingspage.py", line 483, in save_settings
    method='POST', raw_data=json.dumps(settings_data))
  File "/home/vader/src/TRIBLER/Tribler/Tribler/Core/Utilities/json_util.py", line 98, in dumps
    return json.dumps(obj, ensure_ascii=ensure_ascii)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by devos50** [comment]
The key/values in the settings dictionary are probably `bytes`, which indeed cannot be serialized by the `json` library.
