### ISSUE TITLE
EndpointClosedException on Tribler shutown

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4819]
When closing Tribler (current `devel`, Python2):
```python
ERROR   1567946544.21              ipv8_service:148  (root)  Exception occurred while trying to walk!
Traceback (most recent call last):
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8_service.py", line 145, in on_tick
    strategy.take_step()
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/community/gigachannel/sync_strategy.py", line 21, in take_step
    self.overlay.send_random_to(peer)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/community/gigachannel/community.py", line 86, in send_random_to
    self.endpoint.send(peer.address, self.ezr_pack(self.NEWS_PUSH_MESSAGE, RawBlobPayload(self.gossip_blob)))
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8/messaging/interfaces/udp/endpoint.py", line 42, in send
    self.assert_open()
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8/messaging/interfaces/udp/endpoint.py", line 78, in assert_open
    raise EndpointClosedException(self)
EndpointClosedException: <class 'ipv8.messaging.interfaces.udp.endpoint.UDPEndpoint'> is unexpectedly closed
```

**Comment by ichorid** [comment]
Components shutdown should happen from top to bottom. Which component handles IPv8 communities shutdown?

**Comment by qstokkink** [comment]
@ichorid did you use `origin/master` for IPv8? The submodule pointer was not updated yet, the current submodule pointer still has this bug.

**Comment by ichorid** [comment]
Can't reproduce with the latest `devel`.
