### ISSUE TITLE
Build issue in macOS

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4835]
```python
Ts-Mac-mini:tribler tribler$ /Users/tribler/Documents/sandip/tribler/dist/tribler.app/Contents/MacOS/tribler
Traceback (most recent call last):
  File "run_tribler.py", line 115, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "TriblerGUI/tribler_window.py", line 48, in <module>
    from TriblerGUI.debug_window import DebugWindow
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "TriblerGUI/debug_window.py", line 17, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvas
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "matplotlib/backends/backend_qt5agg.py", line 13, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "matplotlib/figure.py", line 38, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "matplotlib/colorbar.py", line 36, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "matplotlib/contour.py", line 23, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "matplotlib/text.py", line 33, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "matplotlib/backend_bases.py", line 77, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "PIL/Image.py", line 57, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lib-tk/FixTk.py", line 74, in <module>
OSError: [Errno 20] Not a directory: '/Users/tribler/Documents/sandip/tribler/dist/tribler.app/Contents/MacOS/tcl'
[36599] Failed to execute script run_tribler
```

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/4837
