### ISSUE TITLE
Python3 - RuntimeError object has no attribute 'message'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4849]
```python
Traceback (most recent call last):
  File "twisted/python/context.py", line 85, in callWithContext
    
  File "Tribler/Core/APIImplementation/LaunchManyCore.py", line 565, in sesscb_states_callback
    self.bootstrap.fetch_bootstrap_peers()
  File "Tribler/Core/bootstrap.py", line 84, in fetch_bootstrap_peers
    self.dht.connect_peer(bytes(unhexlify(mid))).addCallbacks(on_success, on_failure)
  File "twisted/internet/defer.py", line 311, in addCallbacks
    
--- <exception caught here> ---
  File "twisted/internet/defer.py", line 654, in _runCallbacks
    
  File "Tribler/Core/bootstrap.py", line 77, in on_failure
    self._logger.error("Failed to get DHT response:%s", failure.value.message)
builtins.AttributeError: 'RuntimeError' object has no attribute 'message'

```

https://github.com/Tribler/tribler/blob/5d631d7263705b177787ca4d70bf6bb0b96a18e9/Tribler/Core/bootstrap.py#L76-L77

**Comment by xoriole** [comment]
On running a build created by PyInstaller on Python3 installed as Deb file. Seems it conflicts with the existing PATH.
![python3-linux-build1](https://user-images.githubusercontent.com/1442867/65414354-d0b7ab00-ddf3-11e9-8013-b242cbdf9732.png)
