### ISSUE TITLE
Trust graph - KeyError: 'num_tx'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4866]
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\trustgraphpage.py", line 217, in on_received_data
File "TriblerGUI\widgets\trustgraphpage.py", line 266, in update_gui_labels
KeyError: 'num_tx'
```
Reporter [#27695](http://reporter.tribler.org/stacktrace/27695)

```
platform win32
platform.details Windows-7-6.1.7601-SP1
platform.machine AMD64
python.version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
indebug True
tribler_uptime 17312.1849999
```

This seems to have occured because of internal server error on returning response from `trustview_endpoint`.
```
request_23 trustview?depth=1 GET None (time: 1569533546.57, code: 200)
request_24 trustview?depth=2 GET None (time: 1569533548.64, code: 200)
request_25 trustview?depth=3 GET None (time: 1569533551.57, code: 200)
request_26 trustchain/statistics GET None (time: 1569533551.6, code: 200)
request_27 ipv8/trustchain/users/4c69624e61434c504b3af32776d41e302529a31192a16ccc4650b52a780d2e0d2bbf37c85366a2e82a1eb37cd615980dbc8816923b1a2521451421919bc2490b4c2ccbcff33563751fea/blocks GET None (time: 1569533551.6, code: 200)
request_28 downloads?get_pieces=1 GET None (time: 1569533557.42, code: 200)
request_29 shutdown PUT None (time: 1569533559.29, code: 200)
request_30 trustview?depth=4 GET None (time: 1569533581.75, code: 500)
```

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/4971
