### ISSUE TITLE
Unicode error decoding magnet link to download

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4867]
```python
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 748, in on_start_download_action
File "TriblerGUI\tribler_window.py", line 444, in perform_start_download_request
File "TriblerGUI\tribler_request_manager.py", line 287, in perform_request
File "TriblerGUI\tribler_request_manager.py", line 28, in tribler_urlencode
File "TriblerGUI\tribler_request_manager.py", line 39, in tribler_urlencode_single
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 106: ordinal not in range(128)
```
Report [#27647](http://reporter.tribler.org/stacktrace/27647)
```
platform win32
platform.details Windows-10-10.0.16299-SP0
platform.machine AMD64
python.version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
indebug True
tribler_uptime 982.180000067
```

**Comment by ichorid** [comment]
From the report we see that the problem is that the magnet user tried to paste in Tribler contained a garbled Unicode character, which made Python2 to choke on it.
As all strings are unicode in Python3 now, we dismiss this report.
