### ISSUE TITLE
TypeError: list indices must be integers, not str when clicking balance

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4903]
When clicking on balance (latest devel):

```
ERROR   1571750621.05            tribler_window:108  (root)  Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/TriblerGUI/widgets/trustpage.py", line 96, in received_trustchain_blocks
    self.plot_absolute_values()
  File "/home/quinten/Documents/tribler/TriblerGUI/widgets/trustpage.py", line 110, in plot_absolute_values
    self.trust_plot.add_data(timestamp, [block["transaction"]["total_down"], block["transaction"]["total_up"]])
TypeError: list indices must be integers, not str
```

I printed the contents of `block["transaction"]`, which was the following:

```python
[64, {u'down': 111989733, u'total_down': 147610665, u'up': 0, u'total_up': 0}]
```

**Comment by qstokkink** [comment]
Woop, this is actually an issue with the latest IPv8.
