### ISSUE TITLE
Error when balance is too big

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4904]
When clicking on the balance:

```python
ERROR   1571752934.05            tribler_window:108  (root)  Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 175, in boundingRect
    (ymn, ymx) = self.dataBounds(ax=1)
  File "/home/quinten/.local/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 132, in dataBounds
    if any(np.isinf(b)):
TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by qstokkink** [comment]
This would be trivially fixed by imposing a maximum:

```patch
diff --git a/TriblerGUI/widgets/trustpage.py b/TriblerGUI/widgets/trustpage.py
index a19d4ab16..fbba7ac2b 100644
--- a/TriblerGUI/widgets/trustpage.py
+++ b/TriblerGUI/widgets/trustpage.py
@@ -107,6 +107,7 @@ class TrustPage(QWidget):
 
             num_bandwidth_blocks += 1
             timestamp = time.mktime(datetime.datetime.strptime(block["insert_time"], "%Y-%m-%d %H:%M:%S").timetuple())
-            self.trust_plot.add_data(timestamp, [block["transaction"]["total_down"], block["transaction"]["total_up"]])
+            self.trust_plot.add_data(timestamp, [min(block["transaction"]["total_down"], 10000000),
+                                                 min(block["transaction"]["total_up"], 10000000)])
 
         self.trust_plot.render_plot()
```

But the graph would also be wrong.
