### ISSUE TITLE
UnicodeDecodeError: invalid continuation byte

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4920]
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\python\log.py", line 86, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 122, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 85, in callWithContext

File "lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\udp.py", line 249, in doRead

File "Tribler\Core\Socks5\udp_connection.py", line 39, in datagramReceived

File "Tribler\Core\Socks5\conversion.py", line 234, in decode_udp_packet

File "Tribler\Core\Socks5\conversion.py", line 152, in __decode_address

File "lib\site-packages\six.py", line 888, in ensure_str

builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 24: invalid continuation byte
```

**Comment by ichorid** [comment]
Fixed by #4950
