### ISSUE TITLE
Libtorrent endpoint GET error on Py3

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4932]
Newest Tribler 7.4exp1-64, Win10.

The error is silently written to the log file, nothing is shown to the user, Tribler continues to function normally.

```python
ERROR   1572981245.44              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <class 'TypeError'>: a bytes-like object is required, not 'str'
lib\site-packages\twisted\web\http.py:2146:lineReceived
lib\site-packages\twisted\web\http.py:2237:allContentReceived
lib\site-packages\twisted\web\http.py:937:requestReceived
Tribler\Core\Modules\restapi\rest_manager.py:118:process
--- <exception caught here> ---
lib\site-packages\twisted\web\server.py:217:process
lib\site-packages\twisted\web\server.py:284:render
lib\site-packages\twisted\web\resource.py:265:render
Tribler\Core\Modules\restapi\libtorrent_endpoint.py:75:render_GET
Tribler\Core\Utilities\unicode.py:71:hexlify
]
Traceback (most recent call last):
  File "lib\site-packages\twisted\web\server.py", line 217, in process
  File "lib\site-packages\twisted\web\server.py", line 284, in render
  File "lib\site-packages\twisted\web\resource.py", line 265, in render
  File "Tribler\Core\Modules\restapi\libtorrent_endpoint.py", line 75, in render_GET
  File "Tribler\Core\Utilities\unicode.py", line 71, in hexlify
TypeError: a bytes-like object is required, not 'str'
```

```python
ERROR   1569399937.09              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Downloads\\\xd0\x9f\xd0-foo-bar.torrent'
lib\site-packages\twisted\web\http.py:1964:lineReceived
lib\site-packages\twisted\web\http.py:2059:allContentReceived
lib\site-packages\twisted\web\http.py:869:requestReceived
Tribler\Core\Modules\restapi\rest_manager.py:118:process
--- <exception caught here> ---
lib\site-packages\twisted\web\server.py:184:process
lib\site-packages\twisted\web\server.py:235:render
lib\site-packages\twisted\web\resource.py:250:render
Tribler\Core\Modules\restapi\torrentinfo_endpoint.py:139:render_GET
Tribler\Core\Modules\restapi\torrentinfo_endpoint.py:116:on_file
Tribler\Core\TorrentDef.py:114:load
]
Traceback (most recent call last):
  File "lib\site-packages\twisted\web\server.py", line 184, in process
  File "lib\site-packages\twisted\web\server.py", line 235, in render
  File "lib\site-packages\twisted\web\resource.py", line 250, in render
  File "Tribler\Core\Modules\restapi\torrentinfo_endpoint.py", line 139, in render_GET
  File "Tribler\Core\Modules\restapi\torrentinfo_endpoint.py", line 116, in on_file
  File "Tribler\Core\TorrentDef.py", line 114, in load
```

Probably related log errors found nearby:
```python
ERROR   1570903694.70              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 2] No such file or directory: u'C:\\\\\\Users\\USER\\AppData\\Local\\Temp\\\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd bar (\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd foo) [1010101, \ufffd\ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd].torrent'
```

**Comment by ichorid** [comment]
Oops, these logs are from the older version...
