### ISSUE TITLE
Incorrect number of pieces in torrent file

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4933]
Latest 7.4.0exp1-64 on Windows10.

```python
ERROR   1572981608.91            LaunchManyCore:617  (TriblerLaunchMany)  tlm: could not restore tdef from metainfo dict: incorrect number of piece hashes in torrent file {...}
Traceback (most recent call last):
  File "Tribler\Core\TorrentDef.py", line 79, in __init__
RuntimeError: incorrect number of piece hashes in torrent file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 615, in resume_download
  File "Tribler\Core\TorrentDef.py", line 132, in load_from_dict
  File "Tribler\Core\TorrentDef.py", line 81, in __init__
ValueError: incorrect number of piece hashes in torrent file
```

**Comment by ichorid** [comment]
@egbertbouman , could you please comment on this? I can provide the offending conf file, if necessary.

**Comment by ichorid** [comment]
I found the problem.
When using 
```python
value = ast.literal_eval(value)
```
on Python code strings containing Python strings containing `\\'` sequence, it silently drops one slash. For example: `\xfb%\\'\x93` becomes `\xfb%\'\x93`.

**Comment by ichorid** [comment]
So, the real problem is that the regexp adding `b` to a string in py2-generated dicts can sometimes trigger on the *contents* of the said string. There is no true way to solve this besides implementing a state-machine, or running the thing through a native interpreter, that is py2.
