### ISSUE TITLE
Issue with NoneType address encoding

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4951]
I think this should be handled at IPv8 level than Tribler.
Stacktrace:
```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\python\log.py", line 86, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 122, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 85, in callWithContext

File "lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\udp.py", line 249, in doRead

File "Tribler\Core\Socks5\udp_connection.py", line 45, in datagramReceived

File "Tribler\community\triblertunnel\dispatcher.py", line 87, in on_socks5_udp_data

File "Tribler\pyipv8\ipv8\messaging\anonymization\community.py", line 512, in send_data

File "Tribler\pyipv8\ipv8\messaging\anonymization\community.py", line 498, in send_cell

File "Tribler\pyipv8\ipv8\messaging\anonymization\payload.py", line 68, in to_bin

File "Tribler\pyipv8\ipv8\messaging\anonymization\payload.py", line 23, in encode_address

File "Tribler\pyipv8\ipv8\util.py", line 26, in <lambda>

builtins.TypeError: 'NoneType' object is not iterable
```

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/4950
