### ISSUE TITLE
Documentation builder is broken

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4952]
```python
Traceback (most recent call last):
  File "/home/tribler/.local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/tribler/.local/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/tribler/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/tribler/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/tribler/.local/lib/python3.6/site-packages/sphinx/util/logging.py", line 219, in pending_warnings
    memhandler.flushTo(logger)
  File "/home/tribler/.local/lib/python3.6/site-packages/sphinx/util/logging.py", line 184, in flushTo
    logger.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 861, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 720, in filter
    result = f.filter(record)
  File "/home/tribler/.local/lib/python3.6/site-packages/sphinx/util/logging.py", line 404, in filter
    raise SphinxWarning(location + ":" + message)
sphinx.errors.SphinxWarning: /home/tribler/tudelft/tribler/Tribler/Core/Modules/restapi/metadata_endpoint.py:docstring of Tribler.Core.Modules.restapi.metadata_endpoint.MetadataPublicKeyEndpoint:3:Unknown target name: "id".

```

**Comment by ichorid** [comment]
Is it only MetadataStore's fault? If it is, how can I reproduce the error?

**Comment by xoriole** [comment]
You can simply try to build the docs to reproduce the issue.
```
cd tribler/docs
sphinx-build . _build/html -W -v
```
https://github.com/Tribler/tribler/blob/a8a1a091361fb8e070a42100c85b3c2651532605/Tribler/Core/Modules/restapi/metadata_endpoint.py#L95-L101
Line 100 (`<id_>`) seems to be the issue for some reason.

**Comment by qstokkink** [comment]
That is the Sphinx (rst) way of linking to a resource of the name `id`, which is not defined. You can probably escape the underscore.

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/4964
