### ISSUE TITLE
[Py3] infohash - a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4961]
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "run_tribler.py", line 95, in <module>

File "run_tribler.py", line 84, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1283, in run

File "lib\site-packages\twisted\internet\base.py", line 1292, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 913, in runUntilCurrent

File "Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py", line 231, in schedule_create_engine

File "Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py", line 329, in network_create_engine_wrapper

File "Tribler\Core\Libtorrent\LibtorrentMgr.py", line 334, in add_torrent

File "Tribler\Core\Utilities\unicode.py", line 71, in hexlify

builtins.TypeError: a bytes-like object is required, not 'str'
```

https://github.com/Tribler/tribler/blob/06d3680323757ea0700f4fb519e3646c6edb7059/Tribler/Core/Libtorrent/LibtorrentMgr.py#L319-L334

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/4963
