### ISSUE TITLE
Resume data failed to save: torrent has no metadata

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4985]
Tribler-7.4.0-exp2, Win10

```python
INFO    1575206079.86             LibtorrentMgr:671  (LibtorrentMgr)  start_download: Starting in VOD mode
ERROR   1575206081.50    LibtorrentDownloadImpl:805  (LibtorrentDownloadImpl)  Resume data failed to save: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
INFO    1575206091.40                    tunnel:469  (Swarm)  Skipping lookup for swarm b'...'
INFO    1575206101.40                    tunnel:462  (Swarm)  Performing DHT lookup for swarm b'...'
INFO    1575206109.52    LibtorrentDownloadImpl:452  (LibtorrentDownloadImpl)  LibtorrentDownloadImpl: skipping set_piece_priority
Traceback (most recent call last):
  File "Tribler\Core\Video\VideoServer.py", line 102, in process_request_thread
  File "lib\socketserver.py", line 360, in finish_request
  File "Tribler\Core\Video\VideoServer.py", line 124, in __init__
  File "lib\socketserver.py", line 720, in __init__
  File "lib\http\server.py", line 426, in handle
  File "lib\http\server.py", line 414, in handle_one_request
  File "Tribler\Core\Video\VideoServer.py", line 197, in do_GET
  File "Tribler\Core\Video\VideoServer.py", line 76, in get_vod_stream
  File "Tribler\Core\Video\VideoServer.py", line 91, in get_vod_destination
AttributeError: 'LibtorrentDownloadImpl' object has no attribute 'get_selected_files'
ERROR   1575206111.41                      util:68   (ipv8.util)  Deferred errback fired: [Failure instance: Traceback (failure with no frames): <class 'RuntimeError'>: Peers request timeout
```

This could be due to corrupted `.conf` statefiles present in the `dlcheckpoints` directory. Anyways, the error should be handled gracefully and the offending statefile should be deleted (and probably re-downloaded from DHT).

**Comment by egbertbouman** [comment]
Looks like `download.get_selected_files()` should be `download.config.get_selected_files()`. Also the related unit test should be fixed to reflect this.
