### ISSUE TITLE
Libtorrent debug panel: hexlify - bytes object required, not 'str'

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4986]
Tribler-7.4.0-exp2, Windows10, when clicking Debug->libtorrent->settings.

ERROR   1575207547.56              rest_manager:83   (RESTRequest)  [Failure instance: Traceback: <class 'TypeError'>: a bytes-like object is required, not 'str'
lib\site-packages\twisted\web\http.py:2146:lineReceived
lib\site-packages\twisted\web\http.py:2237:allContentReceived
lib\site-packages\twisted\web\http.py:937:requestReceived
Tribler\Core\Modules\restapi\rest_manager.py:118:process
--- <exception caught here> ---
lib\site-packages\twisted\web\server.py:217:process
lib\site-packages\twisted\web\server.py:284:render
lib\site-packages\twisted\web\resource.py:265:render
Tribler\Core\Modules\restapi\libtorrent_endpoint.py:75:render_GET
Tribler\Core\Utilities\unicode.py:81:hexlify
]
Traceback (most recent call last):
  File "lib\site-packages\twisted\web\server.py", line 217, in process
  File "lib\site-packages\twisted\web\server.py", line 284, in render
  File "lib\site-packages\twisted\web\resource.py", line 265, in render
  File "Tribler\Core\Modules\restapi\libtorrent_endpoint.py", line 75, in render_GET
  File "Tribler\Core\Utilities\unicode.py", line 81, in hexlify
TypeError: a bytes-like object is required, not 'str'

**Comment by egbertbouman** [comment]
Looks like LibtorrentMgr.ltsettings itself is changed (instead of a copy), so the second time you request the settings, it will fail.
