### ISSUE TITLE
Tribler 7.4 dec 12th version does not continue, stays on loading.

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#5003]
INFO    1576232399.76        single_application:28   (root)  __init__()
INFO    1576232399.78        single_application:54   (root)    self._outSocket.error() = '2'
INFO    1576232399.78        single_application:64   (root)  __init__(): returning
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
INFO    1576232401.08     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
INFO    1576232405.48     event_request_manager:79   (TriblerGUI)  Got Tribler core error: 1
INFO    1576232405.98     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
Traceback (most recent call last):
  File "run_tribler.py", line 95, in <module>
  File "run_tribler.py", line 43, in start_tribler_core
  File "C:\Users\tribler\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "Tribler\Core\Session.py", line 21, in <module>
  File "C:\Users\tribler\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "Tribler\Core\APIImplementation\LaunchManyCore.py", line 29, in <module>
  File "C:\Users\tribler\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "Tribler\pyipv8\ipv8_service.py", line 22, in <module>
  File "C:\Users\tribler\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "Tribler\pyipv8\ipv8\attestation\noodle\community.py", line 14, in <module>
ModuleNotFoundError: No module named 'ujson'
[12860] Failed to execute script run_tribler
INFO    1576232410.35     event_request_manager:79   (TriblerGUI)  Got Tribler core error: 1
INFO    1576232410.85     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
INFO    1576232415.26     event_request_manager:79   (TriblerGUI)  Got Tribler core error: 1
INFO    1576232415.76     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
INFO    1576232420.17     event_request_manager:79   (TriblerGUI)  Got Tribler core error: 1
INFO    1576232420.67     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint

These last lines keep reappearing and normal screen keeps shsowing Loading and nothing happens!

**Comment by devos50** [comment]
Thanks for your report!

We are currently testing an advanced version of our integrated blockchain, which will be included in our next, upcoming experimental release. This introduces a few new dependencies. It seems that these dependencies are not included correctly in the windows build.

Since we are still working on fine-tuning this release, I will close this issue for now.
