### ISSUE TITLE
Issue with conversion of config to 7.4

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5007]
```python
Traceback (most recent call last):
File "TriblerGUI/core_manager.py", line 121, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "site-packages/twisted/internet/base.py", line 434, in fireEvent

File "site-packages/twisted/internet/defer.py", line 322, in addCallback

File "site-packages/twisted/internet/defer.py", line 311, in addCallbacks

File "site-packages/twisted/internet/defer.py", line 654, in _runCallbacks

--- <exception caught here> ---
File "site-packages/twisted/internet/base.py", line 447, in _continueFiring

File "run_tribler.py", line 81, in start_tribler

File "Tribler/Core/Session.py", line 412, in start

File "Tribler/Core/Upgrade/upgrade.py", line 93, in run

File "Tribler/Core/Upgrade/upgrade.py", line 172, in upgrade_config_to_74

File "Tribler/Core/Upgrade/config_converter.py", line 226, in convert_config_to_tribler74

File "lib2to3/refactor.py", line 361, in refactor_string
name, err.__class__.__name__, err)
File "lib2to3/refactor.py", line 358, in refactor_string
tree = self.driver.parse_string(data)
File "lib2to3/pgen2/driver.py", line 104, in parse_string
return self.parse_tokens(tokens, debug)
File "lib2to3/pgen2/driver.py", line 72, in parse_tokens
if p.addtoken(type, value, (prefix, start)):
File "lib2to3/pgen2/parse.py", line 116, in addtoken
ilabel = self.classify(type, value, context)
File "lib2to3/pgen2/parse.py", line 172, in classify
raise ParseError("bad token", type, value, context)
lib2to3.pgen2.parse.ParseError: bad token: type=58, value=' ', context=('', (1, 459))
```
platform darwin
platform.details Darwin-17.4.0-x86_64-i386-64bit
platform.machine x86_64
python.version 3.7.4 (v3.7.4:e09359112e, Jul 8 2019, 14:54:52)
[Clang 6.0 (clang-600.0.57)]
tribler_uptime 7.563759088516235
User: 0

**Comment by devos50** [comment]
This issue is fixed by https://github.com/Tribler/tribler/pull/5008
