### ISSUE TITLE
ModuleNotFoundError: No module named 'orjson'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5033]
When running latest 7.4.0 Noodle2 on Ubuntu 18.04.2 LTS:

```
INFO    1577791173.90        single_application:28   (root)  __init__()
INFO    1577791174.07        single_application:54   (root)    self._outSocket.error() = '2'
INFO    1577791174.07        single_application:64   (root)  __init__(): returning
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
INFO    1577791175.13     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
INFO    1577791175.19     event_request_manager:79   (TriblerGUI)  Got Tribler core error: 1
INFO    1577791175.72     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
INFO    1577791175.72     event_request_manager:79   (TriblerGUI)  Got Tribler core error: 1
INFO    1577791176.25     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
INFO    1577791176.25     event_request_manager:79   (TriblerGUI)  Got Tribler core error: 1
INFO    1577791176.77     event_request_manager:132  (TriblerGUI)  Will connect to events endpoint
INFO    1577791176.77     event_request_manager:79   (TriblerGUI)  Got Tribler core error: 1
Traceback (most recent call last):
  File "run_tribler.py", line 95, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 43, in start_tribler_core
    from Tribler.Core.Session import Session
  File "/usr/share/tribler/Tribler/Core/Session.py", line 23, in <module>
    from Tribler.Core.Modules.restapi.rest_manager import RESTManager
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/rest_manager.py", line 19, in <module>
    from Tribler.Core.Modules.restapi.root_endpoint import RootEndpoint
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/root_endpoint.py", line 3, in <module>
    from anydex.restapi.root_endpoint import RootEndpoint as AnyDexRootEndpoint
  File "/usr/share/tribler/Tribler/anydex/anydex/restapi/root_endpoint.py", line 4, in <module>
    from ipv8.REST.root_endpoint import RootEndpoint as IPv8RootEndpoint
  File "/usr/share/tribler/Tribler/pyipv8/ipv8/REST/root_endpoint.py", line 12, in <module>
    from .noodle_endpoint import NoodleEndpoint
  File "/usr/share/tribler/Tribler/pyipv8/ipv8/REST/noodle_endpoint.py", line 4, in <module>
    from ..attestation.noodle.community import NoodleCommunity
  File "/usr/share/tribler/Tribler/pyipv8/ipv8/attestation/noodle/community.py", line 15, in <module>
    import orjson as json
ModuleNotFoundError: No module named 'orjson'
```

**Comment by synctext** [comment]
temp fix: ```sudo pip3 install orjson```

```
Collecting orjson
  Downloading https://files.pythonhosted.org/packages/63/23/fbe5af5ba2334953b2c0bf6873bc5593da7d3585f36692fe0e2953b6b92e/orjson-2.1.3-cp36-cp36m-manylinux1_x86_64.whl (173kB)
    100% |████████████████████████████████| 174kB 3.0MB/s 
Installing collected packages: orjson
Successfully installed orjson-2.1.3
```

**Comment by devos50** [comment]
Thanks for reporting! Cherry-picking https://github.com/xoriole/tribler/commit/4b81d39e868e9fbbdeda87f0301f41ffe28fe7c7 on our release branch should fix this 👍

**Comment by devos50** [comment]
Fixed!
