### ISSUE TITLE
TypeError: ufunc 'isinf' not supported for the input types (Noodle release)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5034]
When clicking the token balance button:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 175, in boundingRect
(ymn, ymx) = self.dataBounds(ax=1)
File "/usr/local/lib/python3.6/dist-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 132, in dataBounds
if any(np.isinf(b)):
TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by devos50** [comment]
Anyone knows if this is still an issue?

**Comment by devos50** [comment]
It seems that the token balance screen works now on Linux.
