### ISSUE TITLE
AIOHTTP name or service not known

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5044]
Latest `devel`, after leaving Tribler running for a few days:

```python
ERROR   1578371623.06                   session:374  (Session)  Got unhandled error: [Errno -2] Name or service not known
  File "/home/vader/src/TRIBLER/py37venv2/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/vader/src/TRIBLER/py37venv2/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
ERROR   1578371623.07            tribler_window:109  (root)  Traceback (most recent call last):
  File "/home/vader/src/TRIBLER/Tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 113, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Errno -2] Name or service not known
```

**Comment by ichorid** [comment]
@egbertbouman , could you please look at this? It happened just after a torrent checker failing to connect to a tracker, so that may be related.

**Comment by ichorid** [comment]
Haven't seen this in a while. Closing.
