### ISSUE TITLE
IPv8 import conflict with AnyDex

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5057]
When running the tunnel helper script on our infrastructure (latest `devel` commit), I get the following error:

```
Jan 17 17:17:37 prxmx3 python3[28437]: Traceback (most recent call last):
Jan 17 17:17:37 prxmx3 python3[28437]:   File "src/tribler-core/run_tribler_headless.py", line 16, in <module>
Jan 17 17:17:37 prxmx3 python3[28437]:     from tribler_core.session import Session
Jan 17 17:17:37 prxmx3 python3[28437]:   File "/opt/tribler/src/tribler-core/tribler_core/session.py", line 47, in <module>
Jan 17 17:17:37 prxmx3 python3[28437]:     from tribler_core.modules.metadata_store.gigachannel_manager import GigaChannelManager
Jan 17 17:17:37 prxmx3 python3[28437]:   File "/opt/tribler/src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py", line 4, in <module>
Jan 17 17:17:37 prxmx3 python3[28437]:     from ipv8.taskmanager import TaskManager, task
Jan 17 17:17:37 prxmx3 python3[28437]: ImportError: cannot import name 'task' from 'ipv8.taskmanager' (/opt/tribler/src/anydex/anydex/../pyipv8/ipv8/taskmanager.py)
```

Most likely, the IPv8 of AnyDex gets prioritised over the one that Tribler provides.

**Comment by devos50** [comment]
The error is in the `__init__` file of the `tribler_core` module, where `dir_path` is assigned a wrong path. Will fix in a moment.
