### ISSUE TITLE
Error when trying anonymous downloading (on testnet)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5058]
I just updated our tunnel infrastructure and I observe the following error when trying to perform anonymous downloading:

```
Jan 17 19:51:38 prxmx3 python3[5915]: Traceback (most recent call last):
Jan 17 19:51:38 prxmx3 python3[5915]:   File "/opt/tribler/src/pyipv8/ipv8/community.py", line 324, in on_packet
Jan 17 19:51:38 prxmx3 python3[5915]:     result = handler(source_address, data)
Jan 17 19:51:38 prxmx3 python3[5915]:   File "/opt/tribler/src/pyipv8/ipv8/lazy_community.py", line 39, in wrapper
Jan 17 19:51:38 prxmx3 python3[5915]:     return func(self, Peer(auth.public_key_bin, source_address), *unpacked)
Jan 17 19:51:38 prxmx3 python3[5915]:   File "/opt/tribler/src/pyipv8/ipv8/messaging/anonymization/community.py", line 927, in on_destroy
Jan 17 19:51:38 prxmx3 python3[5915]:     self.remove_exit_socket(circuit_id, "Got destroy")
Jan 17 19:51:38 prxmx3 python3[5915]:   File "/opt/tribler/src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py", line 428, in remove_exit_socket
Jan 17 19:51:38 prxmx3 python3[5915]:     self.tribler_session.notifier.notify(NTFY.TUNNEL_REMOVE, exit_socket, additional_info)
Jan 17 19:51:38 prxmx3 python3[5915]:   File "/opt/tribler/src/tribler-core/tribler_core/notifier.py", line 28, in notify
Jan 17 19:51:38 prxmx3 python3[5915]:     callback(*args)
Jan 17 19:51:38 prxmx3 python3[5915]: TypeError: circuit_removed() missing 2 required positional arguments: 'circuit' and 'additional_info'
```

The only nodes deployed are on testnet and controlled by me. They run the latest commit on `devel`.

This seems to be some kind of error in the notifier?

**Comment by devos50** [comment]
The error seems to be in the `run_tunnel_helper.py` script, namely [here](https://github.com/Tribler/tribler/blob/devel/src/tribler-core/run_tunnel_helper.py#L100). I fixed it in my `various_fixes` PR.
