### ISSUE TITLE
[7.4.0] RuntimeError: [Failure instance: Traceback: <class 'AssertionError'>: INFOHASH has invalid length: 48

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5089]
From the error reporter:

```
Traceback (most recent call last):
File "TriblerGUI\core_manager.py", line 121, in on_received_state
RuntimeError: [Failure instance: Traceback: <class 'AssertionError'>: INFOHASH has invalid length: 48
Tribler\Core\Modules\gigachannel_manager.py:112:service_channels
Tribler\Core\Modules\gigachannel_manager.py:150:check_channels_updates
lib\site-packages\twisted\internet\defer.py:1613:unwindGenerator
lib\site-packages\twisted\internet\defer.py:1529:_cancellableInlineCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:1418:_inlineCallbacks
Tribler\Core\Modules\gigachannel_manager.py:226:download_channel
Tribler\Core\TorrentDef.py:494:__init__
]
```

**Comment by ichorid** [comment]
48 bytes is the length of channel directory name (`dirname`). There is literally no way in the code how `dirname` can get into the `infohash` field there. Until we get more reports like this, I will call it a user messing with their DB.

**Comment by devos50** [comment]
There has been another report, by another user, containing the same stack trace. This might be worthwhile to investigate.

In both reports, it seems to happen shortly after starting Tribler.

**Comment by devos50** [comment]
Oh, there is another one, with length 49 :D

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'AssertionError'>: INFOHASH has invalid length: 49
Tribler\Core\Modules\gigachannel_manager.py:112:service_channels
Tribler\Core\Modules\gigachannel_manager.py:150:check_channels_updates
lib\site-packages\twisted\internet\defer.py:1613:unwindGenerator
lib\site-packages\twisted\internet\defer.py:1529:_cancellableInlineCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:1418:_inlineCallbacks
Tribler\Core\Modules\gigachannel_manager.py:226:download_channel
Tribler\Core\TorrentDef.py:494:__init__
]
```

**Comment by ichorid** [comment]
:flushed:
