### ISSUE TITLE
[7.4.0] TypeError: setIcon(self, QIcon): argument 1 has unexpected type 'NoneType'

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5097]
From the error reporter:

```
Traceback (most recent call last):
File "TriblerGUI\widgets\downloadspage.py", line 342, in on_remove_download_dialog
File "TriblerGUI\widgets\videoplayerpage.py", line 244, in reset_player
TypeError: setIcon(self, QIcon): argument 1 has unexpected type 'NoneType'
```

I think that it is unable to find one of the images when resetting the video player.

**Comment by ichorid** [comment]
That's a race condition between `initialize_player` and `on_play_pause_button_click` triggered by `eventFilter`.
