### ISSUE TITLE
[7.4.0] SystemError: <built-in function kill> returned a result with an error set

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5105]
From the reporter:

```
OSError: [WinError 6] Controlador no válido
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 1057, in clicked_force_shutdown
File "Tribler\Core\Modules\process_checker.py", line 33, in __init__
File "Tribler\Core\Modules\process_checker.py", line 39, in is_process_running
File "Tribler\Core\Modules\process_checker.py", line 51, in is_pid_running
SystemError: <built-in function kill> returned a result with an error set
```

**Comment by ichorid** [comment]
fixed with #5122
