### ISSUE TITLE
Could not deserialize key data

### ISSUE THREAD

**Issue by consciencia** [Tribler/tribler#5113]
System: Fedora 31
Version: 7.4.1 (1.10)

On startup, I got:

`Traceback (most recent call last):
  File "run_tribler.py", line 95, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 43, in start_tribler_core
    from Tribler.Core.Session import Session
  File "/home/box/Apps/Tribler/tribler-7.4.1/Tribler/Core/Session.py", line 21, in <module>
    from Tribler.Core.APIImplementation.LaunchManyCore import TriblerLaunchMany
  File "/home/box/Apps/Tribler/tribler-7.4.1/Tribler/Core/APIImplementation/LaunchManyCore.py", line 25, in <module>
    from ipv8.peerdiscovery.community import DiscoveryCommunity, PeriodicSimilarity
  File "/usr/local/lib/python3.7/site-packages/ipv8/peerdiscovery/community.py", line 54, in <module>
    class DiscoveryCommunity(Community):
  File "/usr/local/lib/python3.7/site-packages/ipv8/peerdiscovery/community.py", line 57, in DiscoveryCommunity
    master_peer = Peer(unhexlify("3081a7301006072a8648ce3d020106052b81040027038192000403b3ab059ced"
  File "/usr/local/lib/python3.7/site-packages/ipv8/peer.py", line 24, in __init__
    self.key = default_eccrypto.key_from_public_bin(key)
  File "/usr/local/lib/python3.7/site-packages/ipv8/keyvault/crypto.py", line 108, in key_from_public_bin
    return M2CryptoPK(keystring=string)
  File "/usr/local/lib/python3.7/site-packages/ipv8/keyvault/public/m2crypto.py", line 32, in __init__
    encodestring(keystring))
  File "/usr/local/lib/python3.7/site-packages/ipv8/keyvault/public/m2crypto.py", line 48, in key_from_pem
    return serialization.load_pem_public_key(pem, backend=default_backend())
  File "/usr/lib64/python3.7/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 20, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/usr/lib64/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1071, in load_pem_public_key
    self._handle_key_loading_error()
  File "/usr/lib64/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1329, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
`

**Comment by qstokkink** [comment]
It seems key loading is not working _at all_ for you, this is most likely caused by the OpenSSL version on your system.

Could you provide:

 - Your python-cryptography version (`python -c "import cryptography; print cryptography.__version__"`).
 - Your OpenSSL version (`openssl version -v`).

**Comment by consciencia** [comment]
python-crypto: 2.6.1
OpenSSL 1.1.1d FIPS  10 Sep 2019

Also found issue with `PIL.ImageQt`, I had to rename it to `PIL.Image` in order to not crash on import.

**Comment by qstokkink** [comment]
It seems there were some problems with this combination in the past (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=940547).

However, newer versions of python-cryptography apparently fix this issue. Could you update your python-cryptography version and try again?

**Comment by consciencia** [comment]
It fixed this issue, but new issue arised.

`Traceback (most recent call last):
  File "run_tribler.py", line 95, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 43, in start_tribler_core
    from Tribler.Core.Session import Session
  File "/home/box/Apps/tribler/tribler-7.4.1/Tribler/Core/Session.py", line 21, in <module>
    from Tribler.Core.APIImplementation.LaunchManyCore import TriblerLaunchMany
  File "/home/box/Apps/tribler/tribler-7.4.1/Tribler/Core/APIImplementation/LaunchManyCore.py", line 40, in <module>
    from Tribler.Core.Modules.MetadataStore.store import MetadataStore
  File "/home/box/Apps/tribler/tribler-7.4.1/Tribler/Core/Modules/MetadataStore/store.py", line 16, in <module>
    from Tribler.Core.Modules.MetadataStore.OrmBindings import (
  File "/home/box/Apps/tribler/tribler-7.4.1/Tribler/Core/Modules/MetadataStore/OrmBindings/channel_peer.py", line 7, in <module>
    from Tribler.pyipv8.ipv8.database import database_blob
ModuleNotFoundError: No module named 'Tribler.pyipv8.ipv8'`

And second question, how to solve that PIL problem?

**Comment by qstokkink** [comment]
Could you verify that your `/box/Apps/tribler/tribler-7.4.1/Tribler/py-ipv8` is not empty? If it is empty, and you checked out using git, you can fix this by executing `git submodule update --init` from within the Tribler repository (alternatively if you don't have `git` installed you could fill the `Tribler/py-ipv8` and `Tribler/anydex` folders manually by downloading the zip files from GitHub).

If `/box/Apps/tribler/tribler-7.4.1/Tribler/py-ipv8` is not empty, there is probably some Python path issue (but that's harder to fix so I'll wait for feedback before we go into that).

I don't know what is causing your `PIL.ImageQt` problem. I'm not that into the `Qt` side of things. @devos50 do you know what may be causing this?

**Comment by consciencia** [comment]
Directory `/home/box/Apps/tribler/tribler-7.4.1/Tribler/pyipv8` is empty. 
I did not use git clone, I just downloaded zip file from page listing repository tags. Did the same with the `py-ipv8`. 
At first, it failed to import stuff from `py-ipv8` so I locally installed `py-ipv8` using `pip install .` called in `/home/box/Apps/tribler/py-ipv8-1.10`.
It helped and I run to the other mentioned problems after that, so I'm fairly surprised that there are still problems with ipv8 imports...

It would be amazing If some guide for running tribler for people with non debian distributions existed. At first I though installing this app will be matter of minutes...

**Comment by qstokkink** [comment]
Well you're definitely doing things the hard way running from source and using the GitHub zip files on a platform we don't actively support. You'll need some extra steps.

> It would be amazing If some guide for running tribler for people with non debian distributions existed. At first I though installing this app will be matter of minutes...

We have this (though no developer has really attempted to use Fedora before): https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_linux.rst

> It helped and I run to the other mentioned problems after that, so I'm fairly surprised that there are still problems with ipv8 imports...

In Tribler `ipv8` is used as a subpackage, by also installing `ipv8` system-wide you basically made your Python schizophrenic, causing it to not really work.

Specifically you will need to fill your `Tribler/anydex` and `Tribler/pyipv8` folders with the following contents (use the download button from the following pages to get the specific version):

 - `Tribler/anydex`: https://github.com/Tribler/anydex-core/tree/4438588a468553fc6df220183543888bcdc964c7
 - `Tribler/pyipv8`: https://github.com/Tribler/py-ipv8/tree/cef38fc98421936519a454a26dda31f92cf56650

That, coupled with all of the system and `pip` requirements from the `Development on Linux` documentation I linked before *should* be all you need though.

**Comment by consciencia** [comment]
It works now. Thank you.

I know Im doing it the hard way, but I had no other choice because fedora is not supported.
