### ISSUE TITLE
Crash when downloading bootstrap torrent

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5188]
Latest `devel`, Linux:
```
[PID:30514] 2020-03-06 21:59:15,612 - ERROR <session:372> Session.unhandled_error_observer(): Got unhandled error: unsupported operand type(s) for /: 'NoneType' and 'str'
  File "/home/vader/.pyenv/versions/3.7.4/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/tribler/src/pyipv8/ipv8/taskmanager.py", line 104, in done_cb
    future.result()
  File "/home/tribler/src/pyipv8/ipv8/taskmanager.py", line 13, in interval_runner
    await task(*args)
  File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 701, in _invoke_states_cb
    await result
  File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 718, in sesscb_states_callback
    await self.update_hops(download, hops)
  File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 642, in update_hops
    self.start_download(tdef=download.tdef, config=config)
  File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 501, in start_download
    if not config.get_dest_dir().is_dir():
  File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/download_config.py", line 77, in get_dest_dir
    dest_dir = self.state_dir / dest_dir
Traceback (most recent call last):
File "/home/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: File "/home/vader/.pyenv/versions/3.7.4/lib/python3.7/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/home/tribler/src/pyipv8/ipv8/taskmanager.py", line 104, in done_cb
future.result()
File "/home/tribler/src/pyipv8/ipv8/taskmanager.py", line 13, in interval_runner
await task(*args)
File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 701, in _invoke_states_cb
await result
File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 718, in sesscb_states_callback
await self.update_hops(download, hops)
File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 642, in update_hops
self.start_download(tdef=download.tdef, config=config)
File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 501, in start_download
if not config.get_dest_dir().is_dir():
File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/download_config.py", line 77, in get_dest_dir
dest_dir = self.state_dir / dest_dir
```

**Comment by ichorid** [comment]
Disabling bootstrap download fixes this problem. So, it must be related to the latest experimental change of using hidden services for it.
