### ISSUE TITLE
Error while encoding address

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#5191]
From the reporter:

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: File "lib\asyncio\events.py", line 88, in _run
File "lib\asyncio\selector_events.py", line 965, in _read_ready
File "src\tribler-core\tribler_core\modules\tunnel\socks5\udp_connection.py", line 51, in datagram_received
File "src\tribler-core\tribler_core\modules\tunnel\community\dispatcher.py", line 91, in on_socks5_udp_data
File "ipv8\messaging\anonymization\community.py", line 490, in send_data
File "ipv8\messaging\anonymization\community.py", line 476, in send_cell
File "ipv8\messaging\anonymization\payload.py", line 66, in to_bin
File "ipv8\messaging\anonymization\payload.py", line 23, in encode_address
```

**Comment by qstokkink** [comment]
This looks very similar to #4951 .
