### ISSUE TITLE
[7.5.0-exp2] crash on start 

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5192]
Traceback (most recent call last):
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError:   File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "ipv8/taskmanager.py", line 104, in done_cb
  File "ipv8/taskmanager.py", line 13, in interval_runner
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 701, in _invoke_states_cb
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 718, in sesscb_states_callback
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 642, in update_hops
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py", line 501, in start_download
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-core/tribler_core/modules/libtorrent/download_config.py", line 77, in get_dest_dir

**Comment by egbertbouman** [comment]
Thanks for the report! This should be fixed in https://github.com/Tribler/tribler/pull/5190.
