### ISSUE TITLE
RuntimeError: Task already exists: 'unload_pex'

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5226]
7.5.0-rc1 from Reporter:
```python
Traceback (most recent call last):
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: Traceback (most recent call last):
File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
self._callback(*self._args)
File "ipv8/taskmanager.py", line 108, in done_cb
File "ipv8/taskmanager.py", line 14, in interval_runner
File "/usr/lib/python3.6/asyncio/coroutines.py", line 212, in coro
res = func(*args, **kw)
File "ipv8/messaging/anonymization/hidden_services.py", line 196, in do_circuits
File "ipv8/messaging/anonymization/community.py", line 209, in do_circuits
File "ipv8/messaging/anonymization/community.py", line 243, in do_remove
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py", line 433, in remove_exit_socket
File "ipv8/messaging/anonymization/hidden_services.py", line 234, in remove_exit_socket
File "ipv8/taskmanager.py", line 90, in register_task
RuntimeError: Task already exists: 'unload_pex'
```

**Comment by ichorid** [comment]
closed by https://github.com/Tribler/py-ipv8/pull/718
