### ISSUE TITLE
[7.5.0-rc1] resolving tracker: task already exists

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5241]
From reporter:

```python
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: Traceback (most recent call last):
File "ipv8\messaging\anonymization\tunnel.py", line 157, in sendto
OSError: illegal IP address string passed to inet_aton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "ipv8\taskmanager.py", line 108, in done_cb
File "ipv8\messaging\anonymization\tunnel.py", line 131, in create_transport
File "ipv8\messaging\anonymization\tunnel.py", line 161, in sendto
File "ipv8\taskmanager.py", line 90, in register_task
RuntimeError: Task already exists: 'resolving_'tracker.internetwarriors.net''
```

**Comment by qstokkink** [comment]
This seems to be already fixed in the latest IPv8.
