### ISSUE TITLE
[devel] test_watchdog_event_debug randomly failing on Mac

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5254]
Also see [here](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_mac/514/artifact/output/test_runners_output/3.err/*view*/).

```
======================================================================
FAIL: test_watchdog_event_debug (test_instrumentation.TriblerCoreTestWatchDog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/asynctest/case.py", line 352, in _run_test_method
    result = method()
  File "/Users/tribler/Documents/workspace2/workspace/GH_Tribler_PR_Tests/PR_async_mac/tribler/src/tribler-core/tribler_core/tests/tools/test_as_server.py", line 53, in check
    result = fun(*argv, **kwargs)
  File "/Users/tribler/Documents/workspace2/workspace/GH_Tribler_PR_Tests/PR_async_mac/tribler/src/tribler-core/tribler_core/tests/test_instrumentation.py", line 104, in test_watchdog_event_debug
    self.assertTrue(self._printe_event.wait(1))
AssertionError: False is not true
```

**Comment by devos50** [comment]
I haven't seen this failure for a long time. Closing this issue.
