### ISSUE TITLE
[7.5-RC3] KeyError: b'name' when loading checkpoints

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5276]
As reported by a user running Tribler 7.5 RC3:

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: b'name'
--LONG TEXT--
Traceback (most recent call last):
File "src\run_tribler.py", line 95, in start_tribler
File "src\tribler-core\tribler_core\session.py", line 454, in start
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 737, in load_checkpoints
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 760, in load_checkpoint
KeyError: b'name'
--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': KeyError(b'name'), 'future': <Task finished coro=<start_tribler_core.<locals>.start_tribler() done, defined at src\run_tribler.py:64> exception=KeyError(b'name')>}
```

**Comment by devos50** [comment]
Fixed by #5278
