### ISSUE TITLE
[7.5-RC3] pony.orm.dbapiprovider.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5277]
As reported by a user running Tribler 7.5 RC3:

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: disk I/O error
--LONG TEXT--
Traceback (most recent call last):
File "lib\site-packages\pony\orm\dbapiprovider.py", line 53, in wrap_dbapi_exceptions
File "lib\site-packages\pony\orm\dbapiprovider.py", line 270, in execute
sqlite3.OperationalError: disk I/O error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "ipv8\taskmanager.py", line 123, in done_cb
File "ipv8\taskmanager.py", line 17, in interval_runner
File "src\tribler-core\tribler_core\modules\torrent_checker\torrent_checker.py", line 108, in check_random_tracker
File "lib\site-packages\pony\orm\core.py", line 6162, in __getitem__
File "lib\site-packages\pony\orm\core.py", line 6164, in _fetch
File "lib\site-packages\pony\orm\core.py", line 6271, in __init__
File "lib\site-packages\pony\orm\core.py", line 5804, in _actual_fetch
File "lib\site-packages\pony\orm\core.py", line 945, in _exec_sql
File "lib\site-packages\pony\orm\core.py", line 1779, in reconnect
File "lib\site-packages\pony\utils\utils.py", line 95, in reraise
File "lib\site-packages\pony\orm\core.py", line 943, in _exec_sql
File "<string>", line 2, in execute
File "lib\site-packages\pony\orm\dbapiprovider.py", line 67, in wrap_dbapi_exceptions
pony.orm.dbapiprovider.OperationalError: disk I/O error
--CONTEXT--
{'message': "Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...k I/O error')>) at ipv8\\taskmanager.py:120", 'exception': OperationalError('disk I/O error'), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...k I/O error')>) at ipv8\taskmanager.py:120>}
```

**Comment by devos50** [comment]
@ichorid what would be the best course of action to handle this error? I think we should catch and log this particular `OperationalError`. Or is there any other preferred error handling method?

**Comment by ichorid** [comment]
I don't think we should catch and handle this at all. This error is an IO error, which is beyond our reach. The user should be notified about this kind of thing clearly, and Tribler should crash. This is expected behavior.

**Comment by devos50** [comment]
I think a crashing Tribler is never expected behaviour, and detrimental to user satisfaction. In particular, we can easily catch this error and make sure Tribler continues to function (assuming that this error happens once in a blue moon). Catching this error would only result in a missing check of a tracker, which can be performed later. Also, the error presented to the user is not really clear in the sense that the user should know how to proceed.

Unfortunately, we cannot really reproduce this error, which makes reasoning about these kinds of failures hard. If the error does not pop up too often, I'm totally fine with moving the issue to the backlog milestone and discuss it later if we want to enhance error handling to include failing disk reads/writes. We can link any I/O error we find (e.g., due to database writes or libtorrent failures) to this issue. @ichorid do you agree with this?

**Comment by synctext** [comment]
nasty error!
btw seems we need more time to get the release branch sorted. please advertise RC4 on the tribler.org frontpage a week for extra attention and testing.

**Comment by ichorid** [comment]
@devos50 , I agree that we should move it to backlog and see how it fares in the wild after the release. 

Note that this error is not about just the torrent checker, but about all the interactions with the DB. If we catch it and log it instead of reporting and showing it to the user, this could start causing all kinds of weird DB-consistentcy-relater errors and silently deteriorate the user experience.

If this error is caused by us (e.g. bad thread usage), we need more crash reports to debug it. If it is not caused by us, we too need more crash reports to know how to react to it.

**Comment by devos50** [comment]
> btw seems we need more time to get the release branch sorted. please advertise RC4 on the tribler.org frontpage a week for extra attention and testing.

@synctext will do that later today!
