### ISSUE TITLE
[7.5.0-RC5] KeyError: 'infohash'

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5291]
Happened on Tribler 7.5.0-RC5 (Ubuntu 19.10):

```
Traceback (most recent call last):
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py", line 197, in <lambda>
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/widgets/lazytableview.py", line 55, in on_download_button_clicked
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/utilities.py", line 17, in index2uri
KeyError: 'infohash'
```

**Comment by devos50** [comment]
Fixed by #5292
