### ISSUE TITLE
Invalid torrent handle error on change hop count

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5355]
When changing hops count this sometimes happen:

```python
[PID:15074] 2020-06-10 13:00:23,023 - ERROR <download:435> Download.save_resume_data(): Resume data failed to save: <class 'tribler_core.exceptions.SaveResumeDataError'>: torrent has no metadata
[PID:15074] 2020-06-10 13:00:23,028 - ERROR <download:435> Download.save_resume_data(): Resume data failed to save: <class 'tribler_core.exceptions.SaveResumeDataError'>: torrent has no metadata
[PID:15074] 2020-06-10 13:00:23,028 - ERROR <download:435> Download.save_resume_data(): Resume data failed to save: <class 'tribler_core.exceptions.SaveResumeDataError'>: torrent has no metadata
[PID:15074] 2020-06-10 13:00:23,033 - ERROR <downloads_endpoint:450> DownloadsEndpoint.update_download(): invalid torrent handle used
Traceback (most recent call last):
  File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py", line 448, in update_download
    await self.session.dlmgr.update_hops(download, anon_hops)
  File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/download_manager.py", line 646, in update_hops
    await self.remove_download(download)
  File "/home/tribler/src/tribler-core/tribler_core/modules/libtorrent/download_manager.py", line 612, in remove_download
    ltsession.remove_torrent(handle, int(remove_content))
RuntimeError: invalid torrent handle used
```

**Comment by devos50** [comment]
Could this happen when changing the hop count of torrents that do not have metadata yet?

**Comment by ichorid** [comment]
Yes, that happens typically if you just add a torrent, and change the number of hops immediately.

**Comment by drew2a** [comment]
I unsuccessfully tried to reproduce this issue on the latest main. Seems to be fixed.
