### ISSUE TITLE
AttributeError: 'int' object has no attribute 'time'

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5363]
Caught by the app tester:

```
[PID:44363] 2020-06-12 17:46:47,261 - ERROR <tribler_window:107> root.on_exception(): Traceback (most recent call last):
  File "tribler_gui/widgets/downloadspage.py", line 148, in load_downloads
  File "tribler_gui/tribler_request_manager.py", line 178, in __init__
  File "tribler_gui/tribler_request_manager.py", line 100, in add_request
  File "tribler_gui/tribler_request_manager.py", line 95, in evict_timed_out_requests
AttributeError: 'int' object has no attribute 'time'

ERROR:Executor:********** TRIBLER CRASHED **********
ERROR:Executor:Tribler crashed after uptime of 3090.547427892685 sec!
```

I suspect that line 94 in `tribler_request_manager.py` is incorrectly enumerating over dictionary keys, instead of values. The keys of the `self.requests_in_flight` are integers, which will fail with the above error.

**Comment by devos50** [comment]
Unfortunately, this issue is not solved yet:

```
[PID:2456] 2020-06-12 19:03:54,987 - ERROR <tribler_window:107> root.on_exception(): Traceback (most recent call last):
  File "src\tribler-gui\tribler_gui\widgets\leftmenuplaylist.py", line 49, in perform_get_files_request
  File "src\tribler-gui\tribler_gui\tribler_request_manager.py", line 178, in __init__
  File "src\tribler-gui\tribler_gui\tribler_request_manager.py", line 100, in add_request
  File "src\tribler-gui\tribler_gui\tribler_request_manager.py", line 95, in evict_timed_out_requests
AttributeError: 'tuple' object has no attribute 'time'

ERROR:Executor:********** TRIBLER CRASHED **********
```

https://jenkins-ci.tribler.org/job/Deployment-Tests/job/Run_Tribler_Release/job/Run_Win10_64bit/1027/console
