### ISSUE TITLE
[7.5-rc5] SQLAlchemy error on threads

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5367]
When running Tribler 7.5-rc5 on a folder of an older Tribler version the log shows this:

```python
[SQL: SELECT wallets.id AS wallets_id, wallets.name AS wallets_name, wallets.owner AS wallets_owner, wallets.network_name AS wallets_network_name, wallets.purpose AS wallets_purpose, wallets.scheme AS wallets_scheme, wallets.witness_type AS wallets_witness_type, wallets.encoding AS wallets_encoding, wallets.main_key_id AS wallets_main_key_id, wallets.multisig_n_required AS wallets_multisig_n_required, wallets.sort_keys AS wallets_sort_keys, wallets.parent_id AS wallets_parent_id, wallets.multisig AS wallets_multisig, wallets.cosigner_id AS wallets_cosigner_id, wallets.key_path AS wallets_key_path, wallets.default_account_id AS wallets_default_account_id, wallets_1.id AS wallets_1_id, wallets_1.name AS wallets_1_name, wallets_1.owner AS wallets_1_owner, wallets_1.network_name AS wallets_1_network_name, wallets_1.purpose AS wallets_1_purpose, wallets_1.scheme AS wallets_1_scheme, wallets_1.witness_type AS wallets_1_witness_type, wallets_1.encoding AS wallets_1_encoding, wallets_1.main_key_id AS wallets_1_main_key_id, wallets_1.multisig_n_required AS wallets_1_multisig_n_required, wallets_1.sort_keys AS wallets_1_sort_keys, wallets_1.parent_id AS wallets_1_parent_id, wallets_1.multisig AS wallets_1_multisig, wallets_1.cosigner_id AS wallets_1_cosigner_id, wallets_1.key_path AS wallets_1_key_path, wallets_1.default_account_id AS wallets_1_default_account_id, wallets_2.id AS wallets_2_id, wallets_2.name AS wallets_2_name, wallets_2.owner AS wallets_2_owner, wallets_2.network_name AS wallets_2_network_name, wallets_2.purpose AS wallets_2_purpose, wallets_2.scheme AS wallets_2_scheme, wallets_2.witness_type AS wallets_2_witness_type, wallets_2.encoding AS wallets_2_encoding, wallets_2.main_key_id AS wallets_2_main_key_id, wallets_2.multisig_n_required AS wallets_2_multisig_n_required, wallets_2.sort_keys AS wallets_2_sort_keys, wallets_2.parent_id AS wallets_2_parent_id, wallets_2.multisig AS wallets_2_multisig, wallets_2.cosigner_id AS wallets_2_cosigner_id, wallets_2.key_path AS wallets_2_key_path, wallets_2.default_account_id AS wallets_2_default_account_id 
FROM wallets LEFT OUTER JOIN wallets AS wallets_2 ON wallets.id = wallets_2.parent_id LEFT OUTER JOIN wallets AS wallets_1 ON wallets_2.id = wallets_1.parent_id]
(Background on this error at: http://sqlalche.me/e/e3q8)

[PID:10423] 2020-06-13 10:47:53,032 - INFO - TrustChainCommunity(466) - Requesting crawl of node b'03c33e66' (blocks 3 to 3) with id 11652
[PID:10423] 2020-06-13 10:47:53,226 - INFO - TrustChainCommunity(379) - Block validation result <function ValidationResult.partial_next at 0x7f299b210dd0>, [], (Block b'ff3a4000' from ...b'f08dd10f':1 links ...b'2bf42705':0 for {b'up': 0, b'down': 13870041, b'total_up': 0, b'total_down': 13870041} type b'tribler_bandwidth')
[PID:10423] 2020-06-13 10:47:54,351 - INFO - TrustChainCommunity(379) - Block validation result <function ValidationResult.invalid at 0x7f299b210f80>, ['Total down is lower than expected compared to the preceding block', 'Previous hash is not equal to the hash id of the previous block'], (Block b'5bf75598' from ...b'0578efc7':15 links ...b'fb7ae571':0 for {b'up': 0, b'down': 1845251, b'total_up': 0, b'total_down': 26137950} type b'tribler_bandwidth')
[PID:10423] 2020-06-13 10:47:54,351 - INFO - TrustChainCommunity(306) - Failed to process half block (error Block could not be validated: <function ValidationResult.invalid at 0x7f299b210f80>, ['Total down is lower than expected compared to the preceding block', 'Previous hash is not equal to the hash id of the previous block'])
[PID:10423] 2020-06-13 10:47:54,615 - ERROR <base:689> sqlalchemy.pool.impl.NullPool._finalize_fairy(): Exception during reset or similar
Traceback (most recent call last):
  File "/home/vader/.pyenv/versions/tribler3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/home/vader/.pyenv/versions/tribler3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/home/vader/.pyenv/versions/tribler3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 531, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139816804585600 and this is thread id 139816048060160.
[PID:10423] 2020-06-13 10:47:54,633 - ERROR <base:273> sqlalchemy.pool.impl.NullPool._close_connection(): Exception closing connection <sqlite3.Connection object at 0x7f29750943b0>
Traceback (most recent call last):
  File "/home/vader/.pyenv/versions/tribler3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/home/vader/.pyenv/versions/tribler3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/home/vader/.pyenv/versions/tribler3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 531, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139816804585600 and this is thread id 139816048060160.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vader/.pyenv/versions/tribler3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/home/vader/.pyenv/versions/tribler3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 537, in do_close
    dbapi_connection.close()
```

**Comment by devos50** [comment]
A group of students is currently working to fix compatibility with bitcoinlib. Therefore, I suggest disabling the Bitcoin wallet for the moment being, until their code is merged.
