### ISSUE TITLE
[7.5.0-RC5] Python int too large to convert to C long

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5369]
From the error reporter (7.5.0-RC5):

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: Python int too large to convert to C long
--LONG TEXT--
Traceback (most recent call last):
File "src\run_tribler.py", line 95, in start_tribler
File "src\tribler-core\tribler_core\session.py", line 452, in start
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 95, in initialize
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 245, in get_session
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 230, in create_session
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 565, in set_session_settings
OverflowError: Python int too large to convert to C long
--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': OverflowError('Python int too large to convert to C long'), 'future': <Task finished coro=<start_tribler_core.<locals>.start_tribler() done, defined at src\run_tribler.py:64> exception=OverflowError('Python int too large to convert to C long')>}
```

**Comment by devos50** [comment]
As a first step towards a solution for this, we could catch _any_ error that occurs when setting the session settings, and include the erroneous settings in the bug report. This would at least allow us to see which fields are malformed.

**Comment by devos50** [comment]
This can easily be reproduced by entering a value higher than `2^64` for the libtorrent upload/download speed rate (at least on 64-bit platforms).
