### ISSUE TITLE
[7.5.0-RC5] Error when fetching bootstrap download peers

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5370]
From the error reporter:

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: 
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "ipv8\taskmanager.py", line 123, in done_cb
File "ipv8\taskmanager.py", line 17, in interval_runner
File "src\tribler-core\tribler_core\modules\bootstrap.py", line 55, in fetch_bootstrap_peers
File "src\tribler-core\tribler_core\modules\libtorrent\download.py", line 477, in get_peerlist
RuntimeError
--CONTEXT--
{'message': 'Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...untimeError()>) at ipv8\\taskmanager.py:120', 'exception': RuntimeError(), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...untimeError()>) at ipv8\taskmanager.py:120>}
```

**Comment by devos50** [comment]
I found out that this error only happened once on Windows 32-bit and might be fixed after the upgrade to libtorrent 1.2.7. So before catching this `RuntimeError`, I first want to observe if this error pops up again when we release 7.5.2. If so, we will re-open this issue.
