### ISSUE TITLE
[7.5.0-RC5] TypeError: a bytes-like object is required, not 'str' (in debug window)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5371]
From the error reporter:

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\debug_window.py", line 750, in <lambda>
File "src\tribler-gui\tribler_gui\debug_window.py", line 763, in on_libtorrent_session_received
File "src\tribler-gui\tribler_gui\debug_window.py", line 771, in save_to_file
TypeError: a bytes-like object is required, not 'str'
```

**Comment by ichorid** [comment]
duplicate of closed #5334
