### ISSUE TITLE
[7.5.0-RC5] asyncio.base_futures.InvalidStateError: invalid state

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5372]
From the error reporter (this issue is actually reported quite a lot):

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: invalid state
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "lib\asyncio\selector_events.py", line 965, in _read_ready
File "src\tribler-core\tribler_core\modules\torrent_checker\torrentchecker_session.py", line 231, in datagram_received
asyncio.base_futures.InvalidStateError: invalid state
--CONTEXT--
{'message': 'Exception in callback _SelectorDatagramTransport._read_ready()', 'exception': InvalidStateError('invalid state'), 'handle': <Handle _SelectorDatagramTransport._read_ready()>}
```

**Comment by devos50** [comment]
Reproduced by the app tester (win10-64bit): https://jenkins-ci.tribler.org/job/Deployment-Tests/job/Run_Tribler_Release/job/Run_Win10_64bit/1030/console
