### ISSUE TITLE
[7.5.0-rc6] ipv8 UNIQUE constraint failed: public_key, sequence_number

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5375]
From reporter:

```python

Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\core_manager.py", line 118, in on_received_state
RuntimeError: UNIQUE constraint failed: blocks.public_key, blocks.sequence_number
--LONG TEXT--
Traceback (most recent call last):
File "src\run_tribler.py", line 95, in start_tribler
File "src\tribler-core\tribler_core\session.py", line 440, in start
File "src\tribler-core\tribler_core\session.py", line 169, in load_ipv8_overlays
File "ipv8\attestation\trustchain\community.py", line 64, in __init__
File "ipv8\attestation\trustchain\database.py", line 43, in __init__
File "ipv8\attestation\trustchain\database.py", line 419, in open
File "ipv8\database.py", line 129, in open
File "ipv8\database.py", line 232, in _prepare_version
File "ipv8\attestation\trustchain\database.py", line 440, in check_database
File "ipv8\database.py", line 53, in wrapper
File "ipv8\database.py", line 331, in executescript
sqlite3.IntegrityError: UNIQUE constraint failed: blocks.public_key, blocks.sequence_number

--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': IntegrityError('UNIQUE constraint failed: blocks.public_key, blocks.sequence_number'), 'future': <Task finished coro=<start_tribler_core.<locals>.start_tribler() done, defined at src\run_tribler.py:64> exception=IntegrityError('UNIQUE constraint failed: blocks.public_key, blocks.sequence_number')>}
```

**Comment by ichorid** [comment]
@qstokkink , @grimadas ?

**Comment by qstokkink** [comment]
This happens on upgrading the database schema. Looking at the code, it should go wrong in one of these upgrade conditions (https://github.com/Tribler/py-ipv8/blob/master/ipv8/attestation/trustchain/database.py#L408-L416):

```python
        elif current_version == 5:
            return self.get_sql_create_blocks_table("double_spends", "public_key, sequence_number, block_hash")
        elif current_version == 7:
            # Make sure that everything in the sqlite database is stored as BLOB.
            return u"""
            UPDATE blocks SET type=CAST(type AS BLOB), tx=CAST(tx AS BLOB), public_key=CAST(public_key AS BLOB),
                              link_public_key=CAST(link_public_key AS BLOB), previous_hash=CAST(previous_hash AS BLOB),
                              signature=CAST(signature AS BLOB), block_hash=CAST(block_hash AS BLOB);
            """
```

**Comment by ichorid** [comment]
Is it that bad? Is it a blocker?

**Comment by qstokkink** [comment]
Well, at least the workaround is easy: remove the old trustchain database.

**Comment by ichorid** [comment]
That's not what we want from the standpoint of user experience...

**Comment by qstokkink** [comment]
I agree, though it is the default solution presented in the FAQ though: https://www.tribler.org/faq.html

So, to answer your question, I'd definitely consider this a bug -- but not a blocker.

**Comment by devos50** [comment]
Reproduced it by adding a new block, one with a `BLOB` type public key and another one with `TEXT` type public key:

```
INSERT INTO blocks VALUES("test", "", "1", 3, "test", 3, "", "", 12345, 0, "");
INSERT INTO blocks VALUES("test", "", X'31', 3, "test", 3, "", "", 12345, 0, "");
```
