### ISSUE TITLE
[devel] Connect call failed ('::1', 80, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 80)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5428]
I observed this error during the hidden seeding test on Mac and Windows, also see [here](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_mac/730/testReport/junit/test_full_session.test_hidden_services/TestHiddenServices/test_hidden_services/):

```
ERROR   1593594974     taskmanager:TriblerTunnelCommunity:135  Task resulted in error: local variable 'writer' referenced before assignment
Traceback (most recent call last):
  File "/Users/tribler/jenkins/workspace/GH_Tribler_PR_Tests/PR_mac/tribler/src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py", line 604, in on_http_request
    reader, writer = await open_connection(*target_address)
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1033, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 80, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 80)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tribler/jenkins/workspace/GH_Tribler_PR_Tests/PR_mac/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/Users/tribler/jenkins/workspace/GH_Tribler_PR_Tests/PR_mac/tribler/src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py", line 618, in on_http_request
    writer.close()
UnboundLocalError: local variable 'writer' referenced before assignment
```

**Comment by qstokkink** [comment]
If `open_connection` fails, the `writer` variable is not set. This can be easily resolved by declaring the variable before the `open_connection` call (by initializing with `None` for example) and checking if the `writer` is `None` before calling `close()`.

A separate --and more pressing issue-- is that the `open_connection` call fails on Mac in the first place.

**Comment by devos50** [comment]
It also seems to be failing [on Windows 64-bit](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_win64/ws/output/test_runners_output/5.err/*view*/).

**Comment by qstokkink** [comment]
I'm guessing it's now actually trying to connect to this fake tracker:

https://github.com/Tribler/tribler/blob/fd748afb85b2919cd58bf08c198c6260724edda0/src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_base.py#L171

**Comment by egbertbouman** [comment]
This was fixed by https://github.com/Tribler/tribler/pull/5429.
