### ISSUE TITLE
get_metainfo timeout error

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5431]
Latest 7.5.1

```python
[PID:119559] 2020-07-02 18:26:23,827 - ERROR <taskmanager:135> GigaChannelManager.done_cb(): Task resulted in error: 
Traceback (most recent call last):
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py", line 255, in download_channel
    metainfo = await self.session.dlmgr.get_metainfo(bytes(channel.infohash), timeout=60, hops=0)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/modules/libtorrent/download_manager.py", line 414, in get_metainfo
    metainfo = download.tdef.get_metainfo() or await wait_for(shield(download.future_metainfo), timeout)
  File "/home/vader/.pyenv/versions/3.8.2/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

**Comment by ichorid** [comment]
Unfortunately, `TimeoutError` in Asyncio is not the same as the builtin `TimeoutError` in Python. In `release-7.5` the proper one was used. Then it probably slipped through during the backmerge.
