### ISSUE TITLE
MacOS: aiohttp OSError 22

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5440]
7.5.1, **MacOS**
```
platform.details Darwin-19.5.0-x86_64-i386-64bit
platform.machine x86_64
python.version 3.7.4 (v3.7.4:e09359112e, Jul 8 2019, 14:54:52)
```

```python
Traceback (most recent call last):
File "tribler_gui/event_request_manager.py", line 112, in on_read_data
RuntimeError: [Errno 22] Invalid argument
--LONG TEXT--
Traceback (most recent call last):
File "asyncio/events.py", line 88, in _run
File "site-packages/aiohttp/web_protocol.py", line 221, in connection_made
File "site-packages/aiohttp/tcp_helpers.py", line 23, in tcp_keepalive
OSError: [Errno 22] Invalid argument

--CONTEXT--
{'message': 'Exception in callback RequestHandler.connection_made(<_SelectorSoc...e, bufsize=0>>)', 'exception': OSError(22, 'Invalid argument'), 'handle': <Handle RequestHandler.connection_made(<_SelectorSoc...e, bufsize=0>>)>}

**Comment by devos50** [comment]
Unfortunately, there is not much I can find about this issue. We could ignore the error, just like some other obscure low-level exceptions?

**Comment by ichorid** [comment]
Let's ignore it for now.

**Comment by xoriole** [comment]
@ichorid Can we close this?
