### ISSUE TITLE
[devel] AttributeError: 'UDPTrackerProtocol' object has no attribute 'transport' (during tests)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5456]
This issue seems to happen when running the tests on the `devel` branch, see [here](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_linux/770/artifact/output/test_runners_output/00000.err/*view*/):

```
DEBUG   1594217514 torrent_checker:TorrentChecker:315  Session created for tracker udp://localhost:28880
WARNING 1594217514 torrent_checker:TorrentChecker:147  Got session error for URL DHT: Metainfo lookup error
ERROR   1594217514         session:Session:367  Unhandled exception occurred! 'UDPTrackerProtocol' object has no attribute 'transport'
--LONG TEXT--
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 962, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/src/tribler-core/tribler_core/tests/tools/tracker/udp_tracker.py", line 35, in datagram_received
    self.send_connection_reply(host, port)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/src/tribler-core/tribler_core/tests/tools/tracker/udp_tracker.py", line 59, in send_connection_reply
    self.transport.write(response_msg, (host, port))
AttributeError: 'UDPTrackerProtocol' object has no attribute 'transport'
```

**Comment by egbertbouman** [comment]
This is fixed in https://github.com/Tribler/tribler/commit/1aa2d08c221c1f38d476decaccbe68a6d9414199, but still needs merging into devel.

**Comment by devos50** [comment]
Ah great, thanks for letting me know 👍 

Let's do a release-to-devel after #5455 is merged.

**Comment by devos50** [comment]
Should be fixed now.
