### ISSUE TITLE
[devel] TypeError: data argument must be a bytes-like object, not 'NoneType' (Tunnel HTTP Support)

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#5463]
I just encountered this error in ~~7.5~~ master branch. Seems like 

https://github.com/Tribler/tribler/blob/c42109754b6c4cce3459dcb90d94118f35f698b2/src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py#L669

is somehow returning None

In that case core crashes as below, 

```
[PID:17022] 2020-07-10 19:04:10,150 - INFO - TunnelDispatcher(99) - Got response from ('tracker.aletorrenty.pl', 2710): None
[PID:17022] 2020-07-10 19:04:10,160 - ERROR <session:367> Session.unhandled_error_observer(): Unhandled exception occurred! data argument must be a bytes-like object, not 'NoneType'
--LONG TEXT--
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/boogie/src/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/boogie/src/tribler/src/tribler-core/tribler_core/modules/tunnel/community/dispatcher.py", line 103, in on_socks5_tcp_data
    tcp_connection.transport.write(response)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 890, in write
    raise TypeError(f'data argument must be a bytes-like object, '
TypeError: data argument must be a bytes-like object, not 'NoneType'

--CONTEXT--
{'message': 'Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe... \'NoneType\'")>) at /home/boogie/src/tribler/src/pyipv8/ipv8/taskmanager.py:128', 'exception': TypeError("data argument must be a bytes-like object, not 'NoneType'"), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe... 'NoneType'")>) at /home/boogie/src/tribler/src/pyipv8/ipv8/taskmanager.py:128>}
[PID:16875] 2020-07-10 19:04:10,224 - ERROR <tribler_window:107> root.on_exception(): Traceback (most recent call last):
  File "/home/boogie/src/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 112, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: data argument must be a bytes-like object, not 'NoneType'
--LONG TEXT--
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/boogie/src/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/boogie/src/tribler/src/tribler-core/tribler_core/modules/tunnel/community/dispatcher.py", line 103, in on_socks5_tcp_data
    tcp_connection.transport.write(response)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 890, in write
    raise TypeError(f'data argument must be a bytes-like object, '
TypeError: data argument must be a bytes-like object, not 'NoneType'

--CONTEXT--
{'message': 'Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe... \'NoneType\'")>) at /home/boogie/src/tribler/src/pyipv8/ipv8/taskmanager.py:128', 'exception': TypeError("data argument must be a bytes-like object, not 'NoneType'"), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe... 'NoneType'")>) at /home/boogie/src/tribler/src/pyipv8/ipv8/taskmanager.py:128>}

```

**Comment by egbertbouman** [comment]
Thanks for letting us know! Looks like it's a timeout. This should be fixed by adding an if-statement.

**Comment by hbiyik** [comment]
yep

https://github.com/hbiyik/tribler/commit/a86b1ae18df6752558bca7174f9e2d57e3883fdc

**Comment by devos50** [comment]
Note that our master branch dates back to March 26, 2019 and is not really updated.

**Comment by hbiyik** [comment]
Sorry my bad, i meant devel branch

**Comment by devos50** [comment]
Thanks, updated the issue title 👍
