### ISSUE TITLE
Our hidden services test fails when running multiple test suites on Windows at the same time

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5505]
I found that when running multiple test suites on Windows at the same time makes the hidden services test fail with the following stack trace:

```
======================================================================
ERROR: Test the hidden services overlay by constructing an end-to-end circuit and downloading a torrent over it
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\site-packages\asynctest\case.py", line 300, in run
    self._tearDown()
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\site-packages\asynctest\case.py", line 257, in _tearDown
    self.loop.run_until_complete(self.tearDown())
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\site-packages\asynctest\case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\modules\tunnel\test_full_session\test_tunnel_base.py", line 62, in tearDown
    await TestAsServer.tearDown(self)
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\test_as_server.py", line 291, in tearDown
    await super(TestAsServer, self).tearDown()
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\test_as_server.py", line 197, in tearDown
    super(AbstractServer, self).tearDown()
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\test_as_server.py", line 68, in tearDown
    self.remove_directory(temp_dir, ignore_errors=False)
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\test_as_server.py", line 74, in remove_directory
    shutil.rmtree("\\\\?\\" + str(directory), ignore_errors=ignore_errors)
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\shutil.py", line 613, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '\\\\?\\E:\\jenkins\\workspace\\GH_Tribler_PR_Tests\\PR_win64\\tribler\\src\\tribler-core\\tribler_core\\tests\\tools\\temp\\TestHiddenServices_tribler_test_session_TUR2LGN4\\TriblerDownloads\\video.avi'
```

**Comment by devos50** [comment]
It is very likely that this issue is fixed by our improvements to the tests (e.g., pytest migration + using mocked IPv8). I will re-open it when the issue occurs again.
