### ISSUE TITLE
Our readthedocs documentation fails to build

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5519]
The `extract_swagger.py` seems to try and start a server:

```
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/conf.py", line 69, in <module>
    asyncio.run(extract_swagger('restapi/swagger.yaml'))
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/extract_swagger.py", line 19, in extract_swagger
    await api_manager.start()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/src/tribler-core/tribler_core/restapi/rest_manager.py", line 105, in start
    await self.site.start()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('::1', 8085, 0, 0): cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/conf.py", line 69, in <module>
    asyncio.run(extract_swagger('restapi/swagger.yaml'))
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/extract_swagger.py", line 19, in extract_swagger
    await api_manager.start()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/src/tribler-core/tribler_core/restapi/rest_manager.py", line 105, in start
    await self.site.start()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('::1', 8085, 0, 0): cannot assign requested address


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/conf.py", line 69, in <module>
    asyncio.run(extract_swagger('restapi/swagger.yaml'))
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/doc/extract_swagger.py", line 19, in extract_swagger
    await api_manager.start()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/devel/src/tribler-core/tribler_core/restapi/rest_manager.py", line 105, in start
    await self.site.start()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/devel/lib/python3.7/site-packages/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('::1', 8085, 0, 0): cannot assign requested address

```

Also see [here](https://readthedocs.org/projects/tribler/builds/11513285/).

**Comment by qstokkink** [comment]
Probably the address should be `127.0.0.1` instead of `::1`.
