### ISSUE TITLE
[devel] Test whether a torrent is correctly seeded

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5562]
I noticed the following error during the Windows 64-bit tests:

```
======================================================================
ERROR: Test whether a torrent is correctly seeded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\site-packages\asynctest\case.py", line 297, in run
    self._run_test_method(testMethod)
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\site-packages\asynctest\case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\site-packages\asynctest\case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\tools.py", line 12, in wrapper
    await wait_for(coro(*args, **kwargs), timeout)
  File "c:\users\tribler\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError: 
-------------------- >> begin captured logging << --------------------
DEBUG   1600182239 selector_events:asyncio:59   Using selector: SelectSelector
DEBUG   1600182240 proactor_events:asyncio:623  Using proactor: IocpProactor
INFO    1600182240         session:Session:388  Session is using state directory: E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 8431
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 8431 for [libtorrent~port]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 22542
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 22542 for [libtorrent~anon_listen_port]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 10713
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 10713 for [tunnel_community~socks5_listen_ports~0]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 55394
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 55394 for [tunnel_community~socks5_listen_ports~1]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 31688
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 31688 for [tunnel_community~socks5_listen_ports~2]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 22468
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 22468 for [tunnel_community~socks5_listen_ports~3]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 12058
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 12058 for [tunnel_community~socks5_listen_ports~4]
INFO    1600182240 tracker_manager:TrackerManager:38   No tracker blacklist file found at E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\tracker_blacklist.txt.
INFO    1600182240 download_manager:DownloadManager:240  could not load libtorrent state, got exception: FileNotFoundError(2, 'No such file or directory'). starting from scratch
DEBUG   1600182240 download_manager:DownloadManager:255  Started libtorrent session for 0 hops on port 8431
DEBUG   1600182240 download_manager:DownloadManager:387  Updating IP filter ['1.1.1.1']
DEBUG   1600182240 download_manager:DownloadManager:255  Started libtorrent session for 1 hops on port 22542
DEBUG   1600182240 download_manager:DownloadManager:720  Starting the download state callback with interval 1.000000
WARNING 1600182240        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_STARTED
INFO    1600182240         session:Session:388  Session is using state directory: E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\2
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 59952
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 59952 for [libtorrent~port]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 7500
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 7500 for [libtorrent~anon_listen_port]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 29846
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 29846 for [tunnel_community~socks5_listen_ports~0]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 40140
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 40140 for [tunnel_community~socks5_listen_ports~1]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 41852
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 41852 for [tunnel_community~socks5_listen_ports~2]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 26770
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 26770 for [tunnel_community~socks5_listen_ports~3]
DEBUG   1600182240   network_utils:tribler_core.utilities.network_utils:38   Got a working random port 27334
DEBUG   1600182240  tribler_config:TriblerConfig:111  Get random port 27334 for [tunnel_community~socks5_listen_ports~4]
INFO    1600182240 tracker_manager:TrackerManager:38   No tracker blacklist file found at E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\2\tracker_blacklist.txt.
INFO    1600182240 download_manager:DownloadManager:240  could not load libtorrent state, got exception: FileNotFoundError(2, 'No such file or directory'). starting from scratch
DEBUG   1600182240 download_manager:DownloadManager:255  Started libtorrent session for 0 hops on port 59952
DEBUG   1600182240 download_manager:DownloadManager:387  Updating IP filter ['1.1.1.1']
DEBUG   1600182240 download_manager:DownloadManager:255  Started libtorrent session for 1 hops on port 7500
DEBUG   1600182240 download_manager:DownloadManager:720  Starting the download state callback with interval 1.000000
WARNING 1600182240        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_STARTED
DEBUG   1600182240 download_manager:DownloadManager:492  Starting download: filename: None, torrent def: <tribler_core.modules.libtorrent.torrentdef.TorrentDef object at 0x0000000007BB39A0>
DEBUG   1600182240        download:Download:128  Setup: 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667
DEBUG   1600182240        download:Download:275  Saving download config to file E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\2\dlcheckpoints\9d5b2dbc52807325bfc28d688f2bb03f8d1e7667.conf
DEBUG   1600182240 download_manager:DownloadManager:556  Adding handle 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667
DEBUG   1600182241        download:Download:169  Added torrent 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667
DEBUG   1600182241        download:Download:239  Setting IP filter for 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667 to False
DEBUG   1600182241        download:Download:239  Setting IP filter for 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667 to False
DEBUG   1600182241        download:Download:239  Setting IP filter for 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667 to False
DEBUG   1600182241 download_manager:DownloadManager:492  Starting download: filename: None, torrent def: <tribler_core.modules.libtorrent.torrentdef.TorrentDef object at 0x0000000007BB39A0>
DEBUG   1600182241        download:Download:128  Setup: 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667
DEBUG   1600182241        download:Download:275  Saving download config to file E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\dlcheckpoints\9d5b2dbc52807325bfc28d688f2bb03f8d1e7667.conf
DEBUG   1600182241 download_manager:DownloadManager:556  Adding handle 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667
DEBUG   1600182242        download:Download:169  Added torrent 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667
DEBUG   1600182242        download:Download:239  Setting IP filter for 9d5b2dbc52807325bfc28d688f2bb03f8d1e7667 to False
DEBUG   1600182242        download:Download:275  Saving download config to file E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\2\dlcheckpoints\9d5b2dbc52807325bfc28d688f2bb03f8d1e7667.conf
DEBUG   1600182242        download:Download:275  Saving download config to file E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\2\dlcheckpoints\9d5b2dbc52807325bfc28d688f2bb03f8d1e7667.conf
DEBUG   1600182243        download:Download:275  Saving download config to file E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\dlcheckpoints\9d5b2dbc52807325bfc28d688f2bb03f8d1e7667.conf
INFO    1600182300         session:Session:588  Tribler shutdown state notification:Saving configuration...
WARNING 1600182300        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_SHUTDOWN_STATE
INFO    1600182300         session:Session:588  Tribler shutdown state notification:Checkpointing Downloads...
WARNING 1600182300        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_SHUTDOWN_STATE
DEBUG   1600182300        download:Download:574  Stopping b'video.avi'
DEBUG   1600182300        download:Download:275  Saving download config to file E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\dlcheckpoints\9d5b2dbc52807325bfc28d688f2bb03f8d1e7667.conf
INFO    1600182300         session:Session:588  Tribler shutdown state notification:Shutting down Downloads...
WARNING 1600182300        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_SHUTDOWN_STATE
INFO    1600182300         session:Session:588  Tribler shutdown state notification:Shutting down Libtorrent Manager...
WARNING 1600182300        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_SHUTDOWN_STATE
INFO    1600182300         session:Session:588  Tribler shutdown state notification:Saving configuration...
WARNING 1600182300        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_SHUTDOWN_STATE
INFO    1600182300         session:Session:588  Tribler shutdown state notification:Checkpointing Downloads...
WARNING 1600182300        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_SHUTDOWN_STATE
DEBUG   1600182300        download:Download:574  Stopping b'video.avi'
DEBUG   1600182301        download:Download:275  Saving download config to file E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\tribler-core\tribler_core\tests\tools\temp\TestSeeding_tribler_test_session_ORWRORLR\dot.Tribler\2\dlcheckpoints\9d5b2dbc52807325bfc28d688f2bb03f8d1e7667.conf
INFO    1600182301         session:Session:588  Tribler shutdown state notification:Shutting down Downloads...
WARNING 1600182301        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_SHUTDOWN_STATE
INFO    1600182301         session:Session:588  Tribler shutdown state notification:Shutting down Libtorrent Manager...
WARNING 1600182301        notifier:Notifier:25   Called notification on a non-existing subject NTFY.TRIBLER_SHUTDOWN_STATE
DEBUG   1600182301  test_as_server:TestSeeding:293  test_as_server: Number of threads still running 2
DEBUG   1600182301  test_as_server:TestSeeding:295  Thread still running MainThread, daemon: False, instance: <_MainThread(MainThread, started 5960)>
DEBUG   1600182301  test_as_server:TestSeeding:295  Thread still running WatchDog, daemon: True, instance: <WatchDog(WatchDog, started daemon 6388)>
--------------------- >> end captured logging << ---------------------
```

**Comment by devos50** [comment]
I haven't seen this error since the migration to pytest (and I've executed these tests many times already). Closing this issue for now.
