### ISSUE TITLE
[7.5.2] asyncio.exceptions.TimeoutError during version check

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5564]
As reported on Windows (report 34877 and 34909):

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 116, in on_read_data
RuntimeError: 
--LONG TEXT--
Traceback (most recent call last):
File "src\tribler-core\tribler_core\modules\versioncheck_manager.py", line 45, in check_new_version_api
File "lib\site-packages\aiohttp\client.py", line 582, in _request
File "lib\site-packages\aiohttp\helpers.py", line 596, in __exit__
asyncio.exceptions.TimeoutError
--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': TimeoutError(), 'future': <Task finished name='Task-208843' coro=<VersionCheckManager.check_new_version_api() done, defined at src\tribler-core\tribler_core\modules\versioncheck_manager.py:42> exception=TimeoutError()>}
```

**Comment by qstokkink** [comment]
Seems like simply catching `TimeoutError` in the existing `try .. except` block would fix this.

https://github.com/Tribler/tribler/blob/cfaf8bd5fac3c17057e0590d7a12a984bb344cf5/src/tribler-core/tribler_core/modules/versioncheck_manager.py#L31-L44
