### ISSUE TITLE
[7.5.2] TypeError: Invalid discriminator attribute value for ChannelMetadata. Expected: 400, got: 220

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5567]
@synctext observed this error in 7.5.2. Relevant log output:

```
[PID:20194] 2020-09-13 09:46:48,913 - INFO - TorrentChecker(132) - Selected 1 new torrents to check on tracker: http://www.mvgroup.org:2710/announc
[PID:20194] 2020-09-13 09:46:48,982 - ERROR <taskmanager:135> GigaChannelCommunity.done_cb(): Task resulted in error: Invalid discriminator attribute value for ChannelMetadata. Expected: 400, got: 220
Traceback (most recent call last):
  File "ipv8/taskmanager.py", line 131, in done_cb
  File "tribler_core/modules/metadata_store/community/gigachannel_community.py", line 204, in on_blob
  File "concurrent/futures/thread.py", line 57, in run
  File "tribler_core/modules/metadata_store/community/gigachannel_community.py", line 175, in _process_received_blob
  File "tribler_core/modules/metadata_store/community/gigachannel_community.py", line 154, in _update_db_with_blob
  File "tribler_core/modules/metadata_store/store.py", line 295, in process_compressed_mdblob
  File "tribler_core/modules/metadata_store/store.py", line 328, in process_squashed_mdblob
  File "<string>", line 2, in process_payload
  File "pony/orm/core.py", line 515, in new_func
  File "tribler_core/modules/metadata_store/store.py", line 462, in process_payload
  File "pony/orm/core.py", line 5072, in set
  File "pony/orm/core.py", line 5146, in _keyargs_to_avdicts_
  File "pony/orm/core.py", line 2594, in validate
  File "pony/utils/utils.py", line 106, in throw
TypeError: Invalid discriminator attribute value for ChannelMetadata. Expected: 400, got: 220
```

**Comment by devos50** [comment]
@ichorid can you have a look at this one?

**Comment by ichorid** [comment]
This looks like a Pony bug. Fortunately, we now have @kozlovsky  with us 😉 

Alexander?

**Comment by kozlovsky** [comment]
It does not look like a Pony bug to me.

As I understand it, in the received payload, a serialized node has a class `CollectionNode`. On the current machine, the node with the same `public_key` belongs to a class `ChannelMetadata` (a subclass of `CollectionNode`). Then the code of `process_payload` assigns all node attributes from the received payload, including a discriminator attribute, effectively trying to convert the `ChannelMetadata` instance to `CollectionNode` instance. Is it the correct logic?
