### ISSUE TITLE
Devel build failing

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5647]
Devel build on Windows is failing with the following stacktrace
```python
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\core_manager.py", line 68, in on_core_finished
RuntimeError: The Tribler core has unexpectedly finished with exit code -1 and status: 0!

Traceback (most recent call last):
File "src\run_tribler.py", line 102, in <module>
File "src\run_tribler.py", line 29, in start_tribler_core
File "C:\Users\tribler\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "src\tribler-core\tribler_core\session.py", line 43, in <module>
File "C:\Users\tribler\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "src\tribler-core\tribler_core\modules\ipv8_module_catalog.py", line 75, in <module>
File "ipv8\loader.py", line 168, in decorator
ModuleNotFoundError: No module named 'tribler_core.modules.tunnel'
[12216] Failed to execute script run_tribler
```
The build artifact for test is present in this job
https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Win64/105/

**Comment by qstokkink** [comment]
Ah yes, I switched to lazy-loading. Now PyInstaller can't find the modules anymore
