### ISSUE TITLE
[7.5.3] RemoteQueryCommunity - got an unexpected keyword argument 'infohash'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5677]
From error reporter [#36133](http://reporter.tribler.org/stacktrace/36133) 
```python
Traceback (most recent call last):
File "tribler_gui/event_request_manager.py", line 138, in <lambda>
File "tribler_gui/event_request_manager.py", line 80, in on_error
tribler_gui.event_request_manager.CoreConnectTimeoutError: Could not connect with the Tribler Core within 60 seconds
[PID:2608] 2020-10-23 14:44:34,910 - ERROR <taskmanager:135> RemoteQueryCommunity.done_cb(): Task resulted in error: get_entries_query() got an unexpected keyword argument 'infohash'
Traceback (most recent call last):
File "ipv8/taskmanager.py", line 131, in done_cb
File "tribler_core/modules/metadata_store/community/remote_query_community.py", line 124, in on_remote_select
File "tribler_core/modules/metadata_store/orm_bindings/metadata_node.py", line 140, in get_entries_threaded
File "concurrent/futures/thread.py", line 57, in run
File "tribler_core/modules/metadata_store/orm_bindings/metadata_node.py", line 135, in _get_results
File "<string>", line 2, in get_entries
File "pony/orm/core.py", line 528, in new_func
File "tribler_core/modules/metadata_store/orm_bindings/metadata_node.py", line 150, in get_entries
TypeError: get_entries_query() got an unexpected keyword argument 'infohash'
```
Platform: Linux
Tribler uptime : 22818 seconds ~ 6.3hrs

@ichorid @drew2a can you have a look at this?

**Comment by ichorid** [comment]
Well, I am officially at loss here... Let's wait for more cases.

**Comment by drew2a** [comment]
It might be related to https://github.com/Tribler/tribler/pull/5657

There is the test to a new attribute: https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py#L280

Anyway, it looks like my bug.

**Comment by ichorid** [comment]
Well, it was immediately obvious it was related to #5657. What puzzled me, however, was that you tested it properly and I would expect this kind of bug from *pre 7.5.3 versions*, not from 7.5.3 itself :thinking: 

Thus, this is most probably the result of someone checking out half-ready release from GIT.

**Comment by drew2a** [comment]
I see the exception while trying to debug the tests.

So, my assumption the following:
1. Bug is presented
2. The tests are hiding the exception for some reason

If it is true, then we should:
1. Fix the bug (it is easy)
2. Fix the tests
3. Fix the potential vulnerability through which you can crush Tribler instance by forming a "wrong" query

**Comment by ichorid** [comment]
>The tests are hiding the exception for some reason

That's worrying...
