### ISSUE TITLE
[7.5.3] Version checker - local variable 'response_dict' referenced before assignment

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5678]
From error reporter [#36093](http://reporter.tribler.org/stacktrace/36093) 
```python
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 116, in on_read_data
RuntimeError: local variable 'response_dict' referenced before assignment
--LONG TEXT--
Traceback (most recent call last):
File "src\tribler-core\tribler_core\modules\versioncheck_manager.py", line 60, in check_new_version_api
UnboundLocalError: local variable 'response_dict' referenced before assignment

--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': UnboundLocalError("local variable 'response_dict' referenced before assignment"), 'future': <Task finished name='Task-171' coro=<VersionCheckManager.check_new_version_api() done, defined at src\tribler-core\tribler_core\modules\versioncheck_manager.py:42> exception=UnboundLocalError("local variable 'response_dict' referenced before assignment")>}
```
Platform: Windows-10
Uptime: 981.57 seconds

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/5695
