### ISSUE TITLE
[7.5.3] Overflow error when setting libtorrent sessions

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5680]
From error reporter - [#36155](http://reporter.tribler.org/stacktrace/36155) 
```python

Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 116, in on_read_data
RuntimeError: Overflow error when setting libtorrent sessions with settings: {'upload_rate_limit': 1024, 'download_rate_limit': 1023999999998976}
--LONG TEXT--
Traceback (most recent call last):
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 593, in set_session_settings
OverflowError: Python int too large to convert to C long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "src\run_tribler.py", line 81, in start_tribler
File "src\tribler-core\tribler_core\session.py", line 460, in start
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 107, in initialize
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 265, in get_session
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 247, in create_session
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 597, in set_session_settings
OverflowError: Overflow error when setting libtorrent sessions with settings: {'upload_rate_limit': 1024, 'download_rate_limit': 1023999999998976}

--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': OverflowError("Overflow error when setting libtorrent sessions with settings: {'upload_rate_limit': 1024, 'download_rate_limit': 1023999999998976}"), 'future': <Task finished name='Task-1' coro=<start_tribler_core.<locals>.start_tribler() done, defined at src\run_tribler.py:50> exception=OverflowError("Overflow error when setting libtorrent sessions with settings: {'upload_rate_limit': 1024, 'download_rate_limit': 1023999999998976}")>}
```

**Comment by xoriole** [comment]
I can reproduce the issue. After setttings this big integer limit, it shows the following libtorrent issue but the setting is still saved. Then on subsequent start of Tribler, it crashes with the above stacktrace.

![Screenshot from 2020-10-24 17-57-08](https://user-images.githubusercontent.com/1442867/97086268-799d8e80-1622-11eb-9367-f1ecd7477290.png)

**Comment by xoriole** [comment]
Fixed in https://github.com/Tribler/tribler/pull/5704
