### ISSUE TITLE
Our giga channel validation experiment is broken

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5686]
Even though our [gigachannel validation experiment](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_gigachannels/) is passing, there are no channels created, nor shared. This is likely due to the fact that we are not explicitly checking whether the right amount of channels are created, and fail the job if this is not the case.

Current visual output:

![completed_channels](https://user-images.githubusercontent.com/1707075/97279070-c9ef3900-183a-11eb-9bf3-dbf268ac729b.png)

I also noticed the following stack trace in the experiment logs, which should be an entry point for debugging/fixing:

```
2020-10-24 04:31:11,017:ERROR:Unhandled exception occurred! type object 'ChannelMetadata' has no attribute 'get_my_channel'
--LONG TEXT--
Traceback (most recent call last):
  File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_gigachannels/gumby/gumby/util.py", line 39, in delay_runner
    await task(*args)
  File "/home/pouwelse/python3/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_gigachannels/gumby/gumby/modules/tribler_module.py", line 206, in add_torrents_to_channel
    my_channel = self.session.mds.ChannelMetadata.get_my_channel()
AttributeError: type object 'ChannelMetadata' has no attribute 'get_my_channel'
```

**Comment by devos50** [comment]
@ichorid do you want to have a look at this?

**Comment by drew2a** [comment]
Seems to be working now:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/13798583/159729187-660f8112-5747-4d08-a64b-ceb99e8b23b1.png">
