### ISSUE TITLE
[7.12.1] OverflowError: Python int too large to convert to C long (in tribler_core.modules.libtorrent.download.on_add_torrent_alert)

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5713]
Stack:
```python
[
Traceback (most recent call last):, 
  File "src\tribler-gui\tribler_gui\event_request_manager.py", line 116, in on_read_data, 
RuntimeError: Python int too large to convert to C long, 
--LONG TEXT--, 
Traceback (most recent call last):, 
  File "lib\asyncio\events.py", line 81, in _run, 
  File "ipv8\taskmanager.py", line 131, in done_cb, 
  File "ipv8\taskmanager.py", line 18, in interval_runner, 
  File "ipv8\util.py", line 55, in call_async, 
  File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 464, in _task_process_alerts, 
  File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 350, in process_alert, 
  File "src\tribler-core\tribler_core\modules\libtorrent\download.py", line 220, in process_alert, 
  File "src\tribler-core\tribler_core\modules\libtorrent\download.py", line 181, in on_add_torrent_alert, 
OverflowError: Python int too large to convert to C long, 
--CONTEXT--, 
{'message': "Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...t to C long')>) at ipv8\\taskmanager.py:128", 'exception': OverflowError('Python int too large to convert to C long'), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...t to C long')>) at ipv8\taskmanager.py:128>}
]
```

Issue: http://131.180.27.167:9000/organizations/tribler/issues/41/?project=2&query=is%3Aunresolved+version%3A7.5.4&statsPeriod=14d

**Comment by kozlovsky** [comment]
I think the error is in this line:
```
# Limit the amount of connections if we have specified that
self.handle.set_max_connections(self.session.config.get_libtorrent_max_conn_download())
```
Probably a user manually sets too large a parameter value in their config.

We can add `max` to cut too large values, or do nothing.

**Comment by drew2a** [comment]
No reports for the last 3 months. The issue considered unimportant.

**Comment by kozlovsky** [comment]
Occurred again in Tribler 7.12.1 (single user, three times). A user commented: "I started downloading the file."
```
OverflowError: Python int too large to convert to C long
  File "asyncio\events.py", line 81, in _run
  File "ipv8\taskmanager.py", line 131, in done_cb
  File "ipv8\taskmanager.py", line 18, in interval_runner
  File "ipv8\util.py", line 35, in call_async
  File "tribler\core\components\libtorrent\download_manager\download_manager.py", line 526, in _task_process_alerts
  File "tribler\core\components\libtorrent\download_manager\download_manager.py", line 406, in process_alert
  File "tribler\core\components\libtorrent\download_manager\download.py", line 245, in process_alert
  File "tribler\core\components\libtorrent\download_manager\download.py", line 210, in on_add_torrent_alert
```

**Comment by qstokkink** [comment]
You can reproduce this as follows:

1. Go to the "CONNECTION" settings tab.
2. Enter a very large number in "Max connections per download".
3. Start downloading a torrent.

![reproduced](https://github.com/Tribler/tribler/assets/3630389/2f68e638-51ac-4366-8623-a45ec4a652b6)
