### ISSUE TITLE
[7.5.4] SSL handshake failed on verifying the certificate

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5714]
Stack:
```
[
Traceback (most recent call last):, 
  File "/home/<RETRACTED>/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 116, in on_read_data, 
    raise RuntimeError(json_dict["event"]["text"]), 
RuntimeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056), 
--LONG TEXT--, 
Traceback (most recent call last):, 
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete, 
    raise handshake_exc, 
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata, 
    self._sslobj.do_handshake(), 
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake, 
    self._sslobj.do_handshake(), 
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056), 
--CONTEXT--, 
{'message': 'SSL handshake failed on verifying the certificate', 'exception': SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'), 'transport': <_SelectorSocketTransport fd=79 read=polling write=<idle, bufsize=0>>, 'protocol': <asyncio.sslproto.SSLProtocol object at 0xab3c37d0>}
]
```

**Comment by drew2a** [comment]
No reports for the last 3 months. The issue considered fixed.
