### ISSUE TITLE
[7.5.4] Exception: Tribler is shutting down

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5715]
Stack:
```
[
Traceback (most recent call last):, 
  File "src\tribler-gui\tribler_gui\event_request_manager.py", line 138, in <lambda>, 
  File "src\tribler-gui\tribler_gui\event_request_manager.py", line 80, in on_error, 
tribler_gui.event_request_manager.CoreConnectTimeoutError: Could not connect with the Tribler Core within 60 seconds, 
[PID:8592] 2020-11-01 18:45:18,015 - ERROR <rest_manager:38> tribler_core.restapi.rest_manager.error_middleware(): Tribler is shutting down, 
Traceback (most recent call last):, 
  File "src\tribler-core\tribler_core\restapi\rest_manager.py", line 35, in error_middleware, 
Exception: Tribler is shutting down
]
```

**Comment by devos50** [comment]
Shouldn't we attach this issue to a milestone?

**Comment by drew2a** [comment]
This issue looks like an issue about `lack of information`.

Probably I can fix it by adding sentry on the customer side.
