### ISSUE TITLE
Bandwidth accounting crashes Tribler if disconnected from network

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5730]
Steps to reproduce:
1. Disable network connectivity
2. Run Tribler
3. Wait for a minute

```python
Traceback (most recent call last):
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-gui/tribler_gui/event_request_manager.py", line 102, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Cannot choose from an empty sequence
--LONG TEXT--
Traceback (most recent call last):
  File "/home/vader/.pyenv/versions/3.8.2/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/taskmanager.py", line 18, in interval_runner
    await task(*args)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/util.py", line 35, in call_async
    return func(*args, **kwargs)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/modules/bandwidth_accounting/community.py", line 157, in query_random_peer
    random_peer = self.random.choice(peers)
  File "/home/vader/.pyenv/versions/3.8.2/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

--CONTEXT--
{'message': "Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...ty sequence')>) at /home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/taskmanager.py:128", 'exception': IndexError('Cannot choose from an empty sequence'), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...ty sequence')>) at /home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/taskmanager.py:128>}

```

**Comment by devos50** [comment]
Oh, forgot about that case hehe...
