### ISSUE TITLE
Validation experiments broken

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5750]
Setting the number of instances/nodes to 1, and setting the `GUMBY_DEBUG` env variable to 1, reveals the following stack trace for the [DHT experiment](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_dht/):

```
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,569:INFO:Unable to load gumby.modules.tribler_module as a local module, exception: No module named 'faker'
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,572:ERROR:Unable to import tribler_module from /var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/modules as gumby.modules.tribler_module: No module named 'faker'
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,572:ERROR:Unable to import gumby.modules.tribler_module.TriblerModule (from tribler_module:1)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: NoneType: None
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,572:INFO:Loaded module: gumby.modules.tribler_module.TriblerModule
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:INFO:Loaded module: experiments.dht.dht_module.DHTModule
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:INFO:Load experiment module DHTModule
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:DEBUG:Registered callback add_walking_strategy target <bound method IPv8OverlayExperimentModule.add_walking_strategy of <experiments.dht.dht_module.DHTModule object at 0x2aaabc541ef0>>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:DEBUG:Registered callback do_dht_announce target <bound method DHTModule.do_dht_announce of <experiments.dht.dht_module.DHTModule object at 0x2aaabc541ef0>>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:DEBUG:Registered callback find target <bound method DHTModule.find of <experiments.dht.dht_module.DHTModule object at 0x2aaabc541ef0>>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:DEBUG:Registered callback introduce_one_peer target <bound method IPv8OverlayExperimentModule.introduce_one_peer of <experiments.dht.dht_module.DHTModule object at 0x2aaabc541ef0>>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:DEBUG:Registered callback introduce_peers target <bound method IPv8OverlayExperimentModule.introduce_peers of <experiments.dht.dht_module.DHTModule object at 0x2aaabc541ef0>>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:DEBUG:Registered callback introduce_peers_dht target <bound method DHTModule.introduce_peers_dht of <experiments.dht.dht_module.DHTModule object at 0x2aaabc541ef0>>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:DEBUG:Registered callback store target <bound method DHTModule.store of <experiments.dht.dht_module.DHTModule object at 0x2aaabc541ef0>>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-11-26 09:31:55,576:ERROR:Task exception was never retrieved
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: future: <Task finished coro=<delay_runner() done, defined at /var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/util.py:37> exception=Exception('No IPv8 provider module loaded. Load an implementation of BaseIPv8Module (with has_ipv8 = True) before loading the %s module', 'DHTModule')>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: Traceback (most recent call last):
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/util.py", line 39, in delay_runner
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     await task(*args)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/home/pouwelse/python3/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     ssl_handshake_timeout=ssl_handshake_timeout)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/home/pouwelse/python3/lib/python3.7/asyncio/base_events.py", line 1002, in _create_connection_transport
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     protocol = protocol_factory()
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/sync.py", line 368, in __call__
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     p = self.protocol(self.vars)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/experiment.py", line 78, in __init__
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     self.scenario_runner.add_scenario(self.scenario_file)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/scenario.py", line 117, in add_scenario
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     line[preproc_match.end():].strip())
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/experiment.py", line 472, in _preproc_module
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     stuff.on_module_load(self)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/modules/experiment_module.py", line 98, in alt_on_module_load
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     cls._the_instance = cls(experiment)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/experiments/dht/dht_module.py", line 19, in __init__
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     super(DHTModule, self).__init__(experiment, DHTDiscoveryCommunity)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/modules/community_experiment_module.py", line 26, in __init__
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     self.ipv8_provider.ipv8_available.add_done_callback(lambda f: self.on_ipv8_available(f.result()))
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/modules/community_experiment_module.py", line 51, in ipv8_provider
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     "with has_ipv8 = True) before loading the %s module", self.__class__.__name__)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: Exception: ('No IPv8 provider module loaded. Load an implementation of BaseIPv8Module (with has_ipv8 = True) before loading the %s module', 'DHTModule')
INFO:ProcessRunner:[] ERR: 2020-11-26 09:31:55,581:DEBUG:Lost connection with: ('10.141.0.3', 43951) with ID 1
```

**Comment by qstokkink** [comment]
Seems like there is a new dependency: the `faker` package.

**Comment by devos50** [comment]
This dependency seems to be added [in this commit](https://github.com/tribler/tribler/commit/30b602d52a485c75057a6c546e2e84d2502bef66).

@drew2a For every dependency added to Tribler, we have to update _all_ our infrastructure. In general, we try to keep the number of external dependencies to an absolute minimum and only add new dependencies if absolutely necessary. Over the past years, we have done much pruning to get rid of unnecessary dependencies (e.g., `cherrypy`, `M2Crypto`, `feedparser`).

Please keep in mind that the validation experiments will likely fail when you install dependencies. Since you might  not have access to the DAS5 yet, I will install this dependency there, which hopefully fixes the experiment. Furthermore, did you update all the builder (Windows, Mac and Linux) with this dependency? Otherwise, the packaged Tribler will fail to run.

**Comment by devos50** [comment]
Seems to work again after installing `sentry-sdk` and `Faker` on the machines 👍
