### ISSUE TITLE
Anonymization community: cache number already in use

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5846]
Latest `devel`, randomly appear in the log:

```python
[PID:27493] 2020-12-11 21:15:27,035 - ERROR <taskmanager:135> TriblerTunnelCommunity.done_cb(): Task resulted in error: This number is already in use '1503337235'
Traceback (most recent call last):
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/messaging/anonymization/community.py", line 693, in on_create
    result = await self.should_join_circuit(payload, source_address)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py", line 219, in should_join_circuit
    self.request_cache.add(BalanceRequestCache(self, circuit_id, balance_future))
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/modules/tunnel/community/caches.py", line 9, in __init__
    super(BalanceRequestCache, self).__init__(community.request_cache, "balance-request", circuit_id)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/pyipv8/ipv8/requestcache.py", line 20, in __init__
    raise RuntimeError("This number is already in use '%s'" % number)
RuntimeError: This number is already in use '1503337235'
```

**Comment by egbertbouman** [comment]
This looks like a combination of a circuit ID collision and not checking the `RequestCache` before adding to it.
