### ISSUE TITLE
Integer overflow on bandwidth payout

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5891]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 6207, in _aggregate
    try: result = cache.query_results[query_key]
KeyError: {'code_key': 1406...504, 'vartypes': {(0, 'public_key', 140600...9504): <class 'bytes'>, (0, '.0', 14060...89504): <pony.orm.ormtypes.SetType object at 0x7fe0318e28b8>}, 'left_join': False, 'filters': (), 'fixed_param_values': {}, 'limit': None, 'offset': None, 'distinct': None, 'aggr_func': ('SUM', None, None), 'for_update': False, 'nowait': False, 'skip_locked': False, 'inner_join_syntax': False, 'attrs_to_prefetch': (), 'arguments_key': (b'LibNaCLPK:<REDACTED>',)}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/dbapiprovider.py", line 55, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/dbapiprovider.py", line 279, in execute
    else: cursor.execute(sql, arguments)
sqlite3.OperationalError: integer overflow
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/tribler/src/pyipv8/ipv8/community.py", line 461, in on_packet
    result = handler(source_address, data)
  File "/opt/tribler/src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py", line 344, in on_payout
    self.bandwidth_community.database.BandwidthTransaction.insert(tx)
  File "<string>", line 2, in insert
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/opt/tribler/src/tribler-core/tribler_core/modules/bandwidth_accounting/transaction.py", line 167, in insert
    db.BandwidthHistory(timestamp=timestamp, balance=bandwidth_database.get_my_balance())
  File "/opt/tribler/src/tribler-core/tribler_core/modules/bandwidth_accounting/database.py", line 137, in get_my_balance
    return self.get_balance(self.my_pub_key)
  File "<string>", line 2, in get_balance
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 515, in new_func
    return func(*args, **kwargs)
  File "/opt/tribler/src/tribler-core/tribler_core/modules/bandwidth_accounting/database.py", line 130, in get_balance
    return self.get_total_given(public_key) - self.get_total_taken(public_key)
  File "<string>", line 2, in get_total_given
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 515, in new_func
    return func(*args, **kwargs)
  File "/opt/tribler/src/tribler-core/tribler_core/modules/bandwidth_accounting/database.py", line 120, in get_total_given
    return sum(transaction.amount for transaction in self.BandwidthTransaction
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 5589, in aggrfunc
    return getattr(select(arg), std_func.__name__)(*args[1:], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 6230, in sum
    return query._aggregate('SUM', distinct)
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 6209, in _aggregate
    cursor = query._database._exec_sql(sql, arguments)
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 949, in _exec_sql
    connection = cache.reconnect(e)
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 1784, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/core.py", line 947, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<string>", line 2, in execute
  File "/usr/local/lib/python3.7/dist-packages/pony/orm/dbapiprovider.py", line 72, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: integer overflow
```

**Comment by devos50** [comment]
The root cause of this issue is already fixed in #5855, but exit nodes are particularly vulnerable to this due to their high balances.

**Comment by xoriole** [comment]
As mentioned by @devos50 , this should be fixed already but should still be tested on the exit nodes.

**Comment by drew2a** [comment]
I could not say better: "If this was still an issue, we would have known about it by now (3 years later). I think it's safe to just close the issue".
