### ISSUE TITLE
[7.7.0] TypeError: <lambda>() takes 0 positional arguments but 1 was given (in downloadsdetailstabwidget.on_right_click_file_item)

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5901]
User comment:
> I have a torrent that has some files disabled so I can download them when I am ready / have room. Right click to enable. Crash
```
Traceback (most recent call last):
File "src\run_tribler.py", line 179, in <module>
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
File "src\tribler-gui\tribler_gui\widgets\downloadsdetailstabwidget.py", line 183, in on_right_click_file_item
tribler_gui.utilities.CreationTraceback

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\utilities.py", line 385, in trackback_wrapper
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

**Comment by kozlovsky** [comment]
Both of [these lines](https://github.com/Tribler/tribler/blob/devel/src/tribler-gui/tribler_gui/widgets/downloadsdetailstabwidget.py#L183-L185) generate exceptions:
```python
        connect(include_action.triggered, lambda: self.on_files_included(selected_files_info))
        include_action.setEnabled(True)
        connect(exclude_action.triggered, lambda: self.on_files_excluded(selected_files_info))
```

**Comment by drew2a** [comment]
### How to reproduce

Right-click on 

![image](https://user-images.githubusercontent.com/13798583/103764836-410c2f00-502d-11eb-8914-2729201e92ad.png)
