### ISSUE TITLE
[7.7.0] TypeError: on_reload_torrent_info() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5902]
```
Traceback (most recent call last):
File "src\run_tribler.py", line 179, in <module>
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
File "src\tribler-gui\tribler_gui\single_application.py", line 118, in _on_ready_read
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
File "src\tribler-gui\tribler_gui\tribler_app.py", line 32, in on_app_message
File "src\tribler-gui\tribler_gui\tribler_app.py", line 37, in handle_uri
File "src\tribler-gui\tribler_gui\tribler_window.py", line 532, in process_uri_request
File "src\tribler-gui\tribler_gui\tribler_window.py", line 833, in start_download_from_uri
File "src\tribler-gui\tribler_gui\dialogs\startdownloaddialog.py", line 61, in __init__
tribler_gui.utilities.CreationTraceback

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\utilities.py", line 385, in trackback_wrapper
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
TypeError: on_reload_torrent_info() takes 1 positional argument but 2 were given
```

**Comment by kozlovsky** [comment]
Duplicate of #5903
