### ISSUE TITLE
[7.7.0] TypeError: on_reload_torrent_info() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5903]
https://github.com/Tribler/tribler/blob/devel/src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py#L61
```
Traceback (most recent call last):
File "src\run_tribler.py", line 179, in <module>
File "src\tribler-gui\tribler_gui\widgets\tablecontentdelegate.py", line 190, in editorEvent
File "src\tribler-gui\tribler_gui\widgets\tableiconbuttons.py", line 40, in check_clicked
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
File "src\tribler-gui\tribler_gui\widgets\lazytableview.py", line 124, in start_download_from_index
File "src\tribler-gui\tribler_gui\tribler_window.py", line 833, in start_download_from_uri
File "src\tribler-gui\tribler_gui\dialogs\startdownloaddialog.py", line 61, in __init__
tribler_gui.utilities.CreationTraceback

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\utilities.py", line 385, in trackback_wrapper
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
TypeError: on_reload_torrent_info() takes 1 positional argument but 2 were given
```

**Comment by drew2a** [comment]
Can reproduce with the stack:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2141, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2132, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1441, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/run_tribler.py", line 179, in <module>
    sys.exit(app.exec_())
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py", line 190, in editorEvent
    result = control.check_clicked(event, model, option, index)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/widgets/tableiconbuttons.py", line 40, in check_clicked
    self.clicked.emit(index)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 382, in trackback_wrapper
    callback(*args, **kwargs)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/widgets/lazytableview.py", line 124, in start_download_from_index
    self.window().start_download_from_uri(index2uri(index))
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 833, in start_download_from_uri
    self.dialog = StartDownloadDialog(self, self.download_uri)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py", line 61, in __init__
    connect(self.dialog_widget.anon_download_checkbox.clicked, self.on_reload_torrent_info)
tribler_gui.utilities.CreationTraceback

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 385, in trackback_wrapper
    raise exc from source_exc
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 382, in trackback_wrapper
    callback(*args, **kwargs)
TypeError: on_reload_torrent_info() takes 1 positional argument but 2 were given
```

### How to reproduce

Click on:

![image](https://user-images.githubusercontent.com/13798583/103762065-c3462480-5028-11eb-92fd-46151046c56f.png)
