### ISSUE TITLE
No space to upgrade

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5907]
What is the best course of action if there is not enough storage to copy the previous version state directory and continue with the upgrade? (Reported in error reporter)
```python
Traceback (most recent call last):
File "src\run_tribler.py", line 179, in <module>
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 150, in connect
tribler_gui.utilities.CreationTraceback

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\utilities.py", line 385, in trackback_wrapper
File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 150, in <lambda>
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 84, in on_error
tribler_gui.event_request_manager.CoreConnectTimeoutError: Could not connect with the Tribler Core within 60 seconds
[PID:18788] 2021-01-06 11:05:53,877 - ERROR <base_events:1707> asyncio.default_exception_handler(): Task exception was never retrieved
future: <Task finished name='Task-1' coro=<start_tribler_core.<locals>.start_tribler() done, defined at src\run_tribler.py:53> exception=OSError(28, 'No space left on device')>
Traceback (most recent call last):
File "src\run_tribler.py", line 62, in start_tribler
File "src\tribler-core\tribler_core\upgrade\version_manager.py", line 171, in fork_state_directory_if_necessary
File "src\tribler-core\tribler_core\upgrade\version_manager.py", line 133, in copy_state_directory
File "lib\shutil.py", line 415, in copy
File "lib\shutil.py", line 261, in copyfile
OSError: [Errno 28] No space left on device: 'C:\\Users\\<User>\\AppData\\Roaming\\.Tribler\\7.7\\ecpub_multichain.pem'
```

With monthly releases scheduled, this could be an issue for many. We should start removing old state directories.

**Comment by qstokkink** [comment]
+1 on this. My disk also quickly ran out of space with 8 GB of state per version. Tribler has become too fat to run normally for me and I need to manually remove databases to run it 😞.

**Comment by drew2a** [comment]
I see only one reason to keep the old state directory: in case of migration failure, we can rollback to the previous version manually.

If this is true, then we need only one old state directory (backup) and during a really short period of time.

**Comment by ichorid** [comment]
Well, it is time to design a dialog window that will show the user an option to clean up the previous config dirs...

**Comment by kozlovsky** [comment]
Do we really need such a dialog? Probably we can delete all previous directories except the previous one on startup.

**Comment by ichorid** [comment]
> Do we really need such a dialog? Probably we can delete all previous directories except the previous one on startup.

Sounds safe enough...

**Comment by synctext** [comment]
> Tribler has become too fat to run normally for me and I need to manually remove databases to run it 

Same problem here. I dont see the need to preserve multiple state directories, so no need to bother the user with this. Always keep only 1 "emergency" backup.

**Comment by snakyjake1** [comment]
I would also like to suggest to not upgrade if there's no space available to upgrade.

**Comment by snakyjake1** [comment]
At the moment, I've got multiple folders of presumably failed upgrade attempts that are prefixed with "unused..."

**Comment by snakyjake1** [comment]
What happens to the folders if you downgrade?

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/7496
