### ISSUE TITLE
[7.7.0] KeyError: 'infohash' (in triblertablecontrollers.py:135)

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5909]
```
Traceback (most recent call last):, 
  File "src\run_tribler.py", line 179, in <module>, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\event_request_manager.py", line 116, in on_read_data, 
  File "src\tribler-gui\tribler_gui\event_request_manager.py", line 77, in tribler_started_event, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\tribler_window.py", line 488, in on_tribler_started, 
  File "src\tribler-gui\tribler_gui\widgets\channelcontentswidget.py", line 124, in initialize_content_page, 
  File "src\tribler-gui\tribler_gui\widgets\triblertablecontrollers.py", line 297, in __init__, 
  File "src\tribler-gui\tribler_gui\widgets\triblertablecontrollers.py", line 93, in __init__, 
  File "src\tribler-gui\tribler_gui\widgets\triblertablecontrollers.py", line 195, in __init__, 
  File "src\tribler-gui\tribler_gui\widgets\triblertablecontrollers.py", line 53, in __init__, 
tribler_gui.utilities.CreationTraceback, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 385, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\widgets\triblertablecontrollers.py", line 54, in <lambda>, 
  File "src\tribler-gui\tribler_gui\widgets\triblertablecontrollers.py", line 135, in check_torrent_health, 
KeyError: 'infohash'
```
[Here](https://github.com/Tribler/tribler/blob/abd610cda9efc01972ce59ed66d7de9d3434472e/src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py#L135):
```python
class HealthCheckerMixin:
    def check_torrent_health(self, data_item, forced=False):
        # TODO: <not relevant for this bug>
        infohash = data_item[u'infohash']
        ...
```
I think the fix should be similar to [this](https://github.com/Tribler/tribler/pull/5292/files) one. I mean:
```python
if data_item['type'] != REGULAR_TORRENT:
    return
```

**Comment by drew2a** [comment]
### How to reproduce

Click on `Health` column for any folder:

![image](https://user-images.githubusercontent.com/13798583/103882905-85f79a80-50ed-11eb-8785-5b5c53c2542f.png)
