### ISSUE TITLE
[7.7.0] RuntimeError: wrapped C/C++ object of type ChannelContentModel has been deleted

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5911]
```
Traceback (most recent call last):, 
  File "src\run_tribler.py", line 179, in <module>, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\widgets\triblertablecontrollers.py", line 88, in _on_filter_input_change, 
  File "src\tribler-gui\tribler_gui\widgets\tablecontentmodel.py", line 379, in reset, 
  File "src\tribler-gui\tribler_gui\widgets\tablecontentmodel.py", line 61, in reset, 
  File "src\tribler-gui\tribler_gui\widgets\tablecontentmodel.py", line 424, in perform_query, 
  File "src\tribler-gui\tribler_gui\widgets\tablecontentmodel.py", line 184, in perform_query, 
  File "src\tribler-gui\tribler_gui\tribler_request_manager.py", line 176, in __init__, 
tribler_gui.utilities.CreationTraceback, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 385, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\widgets\tablecontentmodel.py", line 212, in on_query_results, 
RuntimeError: wrapped C/C++ object of type ChannelContentModel has been deleted
```
[tablecontentmodel.py:212](https://github.com/Tribler/tribler/blob/d977acb366f2e2a7d03b43f5f16606300a19ba46/src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py#L212e)

**Comment by drew2a** [comment]
Can't reproduce.

**Comment by drew2a** [comment]
### Investigation
`RemoteTableModel` instance creates:
* on every query, made by a user
* when a user enters any channel in UI

That means dozens of these models have been created during short user interaction with Tribler.

Every model have callback `on_query_results` that will be called from these places:
* `ChannelContentModel.on_new_entry_reveived`
* `PersonalChannelModel.on_query_results`
* `RemoteTableModel.perform_query`

My guess is: after some time garbage collector starts to remove these models. Then if callback will be called (after `TriblerNetworkRequest` response, for example) then we will see `RuntimeError: wrapped C/C++ object of type ChannelContentModel has been deleted` error.
