### ISSUE TITLE
[7.7.0] AttributeError: 'DebugWindow' object has no attribute 'escape_pressed'

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5915]
User comment:
> Crashed when creating merory dump of GUI. (Made dump because of memory leak)

```
Traceback (most recent call last):, 
  File "run_tribler.py", line 179, in <module>, 
  File "tribler_gui/tribler_window.py", line 1019, in clicked_menu_button_debug, 
  File "tribler_gui/debug_window.py", line 79, in __init__, 
tribler_gui.utilities.CreationTraceback, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "tribler_gui/utilities.py", line 385, in trackback_wrapper, 
  File "tribler_gui/utilities.py", line 382, in trackback_wrapper, 
  File "tribler_gui/debug_window.py", line 79, in <lambda>, 
  File "tribler_gui/debug_window.py", line 747, in on_memory_dump_button_clicked, 
  File "tribler_gui/dialogs/confirmationdialog.py", line 53, in show_error, 
  File "tribler_gui/dialogs/confirmationdialog.py", line 48, in __init__, 
AttributeError: 'DebugWindow' object has no attribute 'escape_pressed'
```

**Comment by drew2a** [comment]
### How to reproduce
Click on (any location)
![image](https://user-images.githubusercontent.com/13798583/104181066-367fda00-541f-11eb-832c-13a8b2d50e10.png)

**Comment by drew2a** [comment]
The issue is fixed, but the fix uncovers another problem:

![image](https://user-images.githubusercontent.com/13798583/104183198-a5126700-5422-11eb-8fc3-ef54b269d237.png)

**Comment by qstokkink** [comment]
`meliae` doesn't exist anymore 😃 #3603
