### ISSUE TITLE
Build artifacts from devel are failing to run - Missing dependency Pillow

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5943]
Built artifacts from devel are failing to run complaining about a missing dependency `Pillow` while the build from branch `release-7.7` seems to work fine.

https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build/148/

**Comment by xoriole** [comment]
Issue with bundling faker
```
45515 INFO: Loading module hook "hook-faker.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 20, in walk_packages
  File "/home/jupiter/.local/lib/python3.8/site-packages/faker/__init__.py", line 1, in <module>
    from faker.factory import Factory
  File "/home/jupiter/.local/lib/python3.8/site-packages/faker/factory.py", line 7, in <module>
    from faker.config import AVAILABLE_LOCALES, DEFAULT_LOCALE, PROVIDERS
  File "/home/jupiter/.local/lib/python3.8/site-packages/faker/config.py", line 3, in <module>
    from faker.utils.loading import find_available_locales, find_available_providers
  File "/home/jupiter/.local/lib/python3.8/site-packages/faker/utils/loading.py", line 7, in <module>
    from typing import List, Set
  File "/home/jupiter/.local/lib/python3.8/site-packages/typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/home/jupiter/.local/lib/python3.8/site-packages/typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```
