### ISSUE TITLE
Opening Debug Pane with keyboard shortcut raises an exception

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5958]
Opening Debug Pane with keyboard shortcut CTRL + D raises an exception
```python
tribler_gui.utilities.CreationTraceback: 
  File "/home/<user>/tudelft/release/tribler/src/run_tribler.py", line 175, in <module>
    window = TriblerWindow()
  File "/home/<user>/tudelft/release/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 158, in __init__
    connect(self.debug_pane_shortcut.activated, self.clicked_menu_button_debug)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<user>/tudelft/release/tribler/src/tribler-gui/tribler_gui/utilities.py", line 391, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/home/<user>/tudelft/release/tribler/src/tribler-gui/tribler_gui/utilities.py", line 388, in trackback_wrapper
    callback(*args, **kwargs)
TypeError: clicked_menu_button_debug() missing 1 required positional argument: 'index'
```

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/5959
