### ISSUE TITLE
[7.7.1] TypeError: clicked_menu_button_debug() missing 1 required positional argument: 'index'

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5966]
[Here:](https://github.com/Tribler/tribler/blob/b29e4a6739d57e887bc9a738584d1ee84d1669d2/src/tribler-gui/tribler_gui/tribler_window.py#L216)

```
tribler_gui.utilities.CreationTraceback: 
  File "/Users/kozlovsky/dev/tribler/src/run_tribler.py", line 175, in <module>
    window = TriblerWindow()
  File "/Users/kozlovsky/dev/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 216, in __init__
    connect(self.debug_pane_shortcut.activated, self.clicked_menu_button_debug)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kozlovsky/dev/tribler/src/tribler-gui/tribler_gui/utilities.py", line 391, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/Users/kozlovsky/dev/tribler/src/tribler-gui/tribler_gui/utilities.py", line 388, in trackback_wrapper
    callback(*args, **kwargs)
TypeError: clicked_menu_button_debug() missing 1 required positional argument: 'index'
```

How to reproduce: run Tribler, press `Cmd+D`

**Comment by kozlovsky** [comment]
Duplicate of #5958
