### ISSUE TITLE
ErrorHandler.gui_error() in tribler-gui-error.log when being shut down

### ISSUE THREAD

**Issue by dertuxmalwieder** [Tribler/tribler#6039]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

7.8.0 release

##### Operating system and version: #####

macOS 11

##### Steps to reproduce the behavior: #####

Shut down Tribler.

##### Expected behavior: #####

No errors should appear.

##### Actual behavior: #####

An error appears in `tribler-gui-error.log`.

##### Relevant log file output: #####

```
[PID:33644] 2021-03-30 11:49:23,438 - ERROR <error_handler:37> ErrorHandler.gui_error(): tribler_gui.utilities.CreationTraceback: 
  File "run_tribler.py", line 179, in <module>
  File "tribler_gui/utilities.py", line 388, in trackback_wrapper
  File "tribler_gui/core_manager.py", line 90, in on_request_error
  File "tribler_gui/core_manager.py", line 117, in start_tribler_core


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tribler_gui/utilities.py", line 391, in trackback_wrapper
  File "tribler_gui/utilities.py", line 388, in trackback_wrapper
  File "tribler_gui/core_manager.py", line 65, in on_core_finished
  File "tribler_gui/core_manager.py", line 152, in on_finished
RuntimeError: wrapped C/C++ object of type CoreManager has been deleted
```

Potentially relevant context from `tribler-gui-info.log`:

```
[PID:33644] 2021-03-30 11:49:23,407 - INFO - root(190) - Shutting down Tribler
[PID:33644] 2021-03-30 11:49:23,438 - ERROR - ErrorHandler(37) - tribler_gui.utilities.CreationTraceback: 
  File "run_tribler.py", line 179, in <module>
  File "tribler_gui/utilities.py", line 388, in trackback_wrapper
  File "tribler_gui/core_manager.py", line 90, in on_request_error
  File "tribler_gui/core_manager.py", line 117, in start_tribler_core


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tribler_gui/utilities.py", line 391, in trackback_wrapper
  File "tribler_gui/utilities.py", line 388, in trackback_wrapper
  File "tribler_gui/core_manager.py", line 65, in on_core_finished
  File "tribler_gui/core_manager.py", line 152, in on_finished
RuntimeError: wrapped C/C++ object of type CoreManager has been deleted

[PID:33644] 2021-03-30 11:49:23,439 - INFO - SentryReporter(268) - Event from exception: wrapped C/C++ object of type CoreManager has been deleted
[PID:33644] 2021-03-30 11:49:23,441 - INFO - SentryReporter(340) - Before send strategy: SentryStrategy.SEND_SUPPRESSED
```

**Comment by kozlovsky** [comment]
Should be fixed in #6619 or #6960
