### ISSUE TITLE
TriblerTunnelCommunity: request cache number already in use

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6070]
Getting this line over and over. Ubuntu 20.04, latest `main`

```python


[PID:37789] 2021-04-23 19:22:40,664 - ERROR <taskmanager:135> TriblerTunnelCommunity.done_cb(): Task resulted in error: This number is already in use '2737'
Traceback (most recent call last):
  File "/home/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/tribler/src/pyipv8/ipv8/messaging/anonymization/community.py", line 777, in on_extend
    cache = CreateRequestCache(self, payload.identifier, to_circuit_id, circuit_id, candidate, extend_candidate)
  File "/home/tribler/src/pyipv8/ipv8/messaging/anonymization/caches.py", line 14, in __init__
    super().__init__(community.request_cache, "create", identifier)
  File "/home/tribler/src/pyipv8/ipv8/requestcache.py", line 20, in __init__
    raise RuntimeError("This number is already in use '%s'" % number)
RuntimeError: This number is already in use '2737'

```

**Comment by egbertbouman** [comment]
This needs to be fixed in IPv8 (https://github.com/Tribler/py-ipv8/pull/985).

**Comment by ichorid** [comment]
Fixed by @egbertbouman in https://github.com/Tribler/py-ipv8/pull/985
