### ISSUE TITLE
[7.9.0] AttributeError: 'SearchResultsModel' object has no attribute 'create_new_channel' (in channelcontentswidget.py)

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6073]
[Here](https://github.com/Tribler/tribler/blob/991af143959cc2aacf07d5c46aa44137797e724d/src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py#L320):

```python
# channelcontentswidget.py
class ChannelContentsWidget(...):
    ...
    def create_new_channel(self, checked):
        NewChannelDialog(self, self.model.create_new_channel)
```

```
tribler_gui.utilities.CreationTraceback: , 
  File "src\run_tribler.py", line 201, in <module>, 
  File "src\tribler-gui\tribler_gui\tribler_window.py", line 182, in __init__, 
  File "src\tribler-gui\tribler_gui\widgets\channelcontentswidget.py", line 138, in initialize_content_page, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 391, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 388, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\widgets\channelcontentswidget.py", line 320, in create_new_channel, 
AttributeError: 'SearchResultsModel' object has no attribute 'create_new_channel'
```

**Comment by kozlovsky** [comment]
Similar: `AttributeError: 'DiscoveredChannelsModel' object has no attribute 'create_new_channel'`
(same traceback)

**Comment by ichorid** [comment]
Reproduced by adding `sleep(50)` to `get_channels_contents`. If it takes too much time to load the channel contents, the channel edit controls are still visible and the user got an opportunity to click on of those, which produces an error in combination with the non-personal channel model. A classic GUI race condition.

**Comment by ichorid** [comment]
The same happens in #6074
