### ISSUE TITLE
[7.10.0-GIT] AttributeError: 'function' object has no attribute 'seed' (in sentry_reporter.py)

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6075]
User comment:
>  I was trying to start Tribler using the ./tribler.sh command mentioned in the README.md

[Here](https://github.com/Tribler/tribler/blob/58234a1e5258719d3913fc9c8f9882a7beb40317/src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py#L301):
```python
class SentryReporter:
    ...
    @staticmethod
    def set_user(user_id):
        ...
        user_id_hash = md5(user_id).hexdigest()
        ...
        Faker.seed(user_id_hash)
        ...
```

```
Traceback (most recent call last):, 
  File "/home/<user>/tribler/src/run_tribler.py", line 95, in start_tribler, 
    await session.start(), 
  File "/home/<user>/tribler/src/tribler-core/tribler_core/session.py", line 280, in start, 
    SentryReporter.set_user(user_id_str), 
  File "/home/<user>/tribler/src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py", line 301, in set_user, 
    Faker.seed(user_id_hash), 
AttributeError: 'function' object has no attribute 'seed'
```

**Comment by drew2a** [comment]
it may be a consequence of missed Faker dependency: https://github.com/Tribler/tribler/blob/6c963068d8233f17da8c2f9852dd64252b4d6ab0/src/requirements.txt#L19
