### ISSUE TITLE
Unstable Linux tests: no event loop

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6087]
Test [fail regularly](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_linux_pytest/1299/) with:
```python

src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py:9: in <module>
    from ipv8.test.messaging.anonymization import test_community
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/local/lib/python3.8/dist-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
src/pyipv8/ipv8/test/messaging/anonymization/test_community.py:5: in <module>
    from ...base import TestBase
src/pyipv8/ipv8/test/base.py:16: in <module>
    get_event_loop().set_debug(True)
/usr/lib/python3.8/asyncio/events.py:639: in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
E   RuntimeError: There is no current event loop in thread 'Dummy-1'.
```

**Comment by qstokkink** [comment]
This is an asyncio error which usually occurs when calling the event loop in a forked off process (using `multiprocessing` for example). 

How or why this would happen with our codebase, I do not know.

**Comment by qstokkink** [comment]
This is my best guess as to what is happening:

 1. Pytest is hooked into the import system and rewrites, recompiles and reloads files/modules [that are named `conftest`, start with `test_` or end with `_test`](https://github.com/pytest-dev/pytest/blob/da66f004133e6c6ed5081854146c0ceffd3f144e/src/_pytest/assertion/rewrite.py#L211-L230). Apparently its injecting some required logic for assertions into the source files.
 2. The import `from ipv8.test.messaging.anonymization import test_community` was not part of the orginal pytest dir's located modules and needs a rewrite as the module name starts with `test_`.
 3. The rewrite happens in the middle of importing Python modules and reconstructing the event loop for the process fork.
 4. Sometimes the event loop is there, sometimes it is not -> crash.
 
If I guessed correctly, [adding the string `PYTEST_DONT_REWRITE` to the `ipv8/test/messaging/anonymization/test_community.py` file docstring seems to solve this](https://github.com/pytest-dev/pytest/blob/da66f004133e6c6ed5081854146c0ceffd3f144e/src/_pytest/assertion/rewrite.py#L764-L766) (prepending this string to the file in the Jenkins job should be an easy way to verify this).

There are way too many moving parts in here to say for sure though. This needs some extensive evaluation.

**Comment by qstokkink** [comment]
Until this is properly fixed, we can run the unit tests sequentially (which is slow, yes) to at least have stable unit tests.

**Comment by qstokkink** [comment]
I modified the `Test_tribler_main` Jenkins job to automatically prepend the `ipv8/test/messaging/anonymization/test_community.py` with `"""PYTEST_DONT_REWRITE"""`. After that, I ran `Test_tribler_main` 10 times without triggering this failure (which would be our longest streak without encountering this). So far, this confirms my intuition. However, perhaps I was just lucky. Let's keep an eye on this.

If this temporary solution holds (i.e., if my intuition was correct), the long term solution would be to refactor `MockDHTProvider` into its own class in the IPv8 codebase.

**Comment by qstokkink** [comment]
Found a failure: https://jenkins-ci.tribler.org/job/Test_tribler_main/348/
`"""PYTEST_DONT_REWRITE"""` **did not help**. There is something else going on.

**Comment by qstokkink** [comment]
After more digging I found this commit: https://github.com/escapewindow/scriptworker/commit/14b4c112f3d1b38b2a28fa4e52d89a44d52a82f3

This commit suggests that `pytest-asyncio` is unloading the main event loop. In that case, simply catching this `RuntimeError` in IPv8 should be fine. We can then set the debug mode on the event loop in the test `setUp()` specially for `pytest`. This approach is not ideal as we may lose asyncio errors in between the module load and `setUp()`, but I think it's the best we can do.

Moving `MockDHTProvider` to its own class to avoid rewriting is still also probably a prudent thing to do.

I'll create a PR on IPv8 for these changes.

**Comment by qstokkink** [comment]
[Different issue] To follow up on this, this was probably the real error all along (https://jenkins-ci.tribler.org/job/Test_tribler_main/354/console):

```
INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E               File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 323, in _main
INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR> E                 self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/usr/local/lib/python3.8/dist-packages/xdist/remote.py", line 72, in pytest_runtestloop
INTERNALERROR> E                 self.run_one_test(torun)
INTERNALERROR> E               File "/usr/local/lib/python3.8/dist-packages/xdist/remote.py", line 89, in run_one_test
INTERNALERROR> E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR> E                 self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR> E                 next(gen)  # first yield
INTERNALERROR> E               File "/usr/local/lib/python3.8/dist-packages/pytest_timeout.py", line 104, in pytest_runtest_protocol
INTERNALERROR> E                 timeout_setup(item)
INTERNALERROR> E               File "/usr/local/lib/python3.8/dist-packages/pytest_timeout.py", line 207, in timeout_setup
INTERNALERROR> E                 signal.signal(signal.SIGALRM, handler)
INTERNALERROR> E               File "/usr/lib/python3.8/signal.py", line 47, in signal
INTERNALERROR> E                 handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
INTERNALERROR> E             ValueError: signal only works in main thread
INTERNALERROR> E           assert False
INTERNALERROR> 
INTERNALERROR> /usr/local/lib/python3.8/dist-packages/xdist/dsession.py:187: AssertionError
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jenkins/.local/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/xdist/dsession.py", line 174, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('src/tribler-core/tribler_core/config/tests/test_tribler_config.py::test_get_path_absolute', <WorkerController gw5>)
INTERNALERROR> assert not 'src/tribler-core/tribler_core/config/tests/test_tribler_config.py::test_get_path_absolute'
```

**Comment by qstokkink** [comment]
Supposedly this will be fixed if we update the `pytest-timeout` plugin to version `2.0.0` or higher.

**Comment by ichorid** [comment]
@xoriole , could you please upgrade the plugin on our testers?

**Comment by xoriole** [comment]
All three platform (Linux, MacOS and Windows) testers now have the latest master of `pytest-timeout` installed

**Comment by qstokkink** [comment]
@xoriole could you also do this for `builder_linux` (the frontpage `README` tester)?

**Comment by qstokkink** [comment]
Found two new bugs (#6166 and #GitHubUnicorn), so far O.P. not encountered within the last 10 runs.

**Comment by qstokkink** [comment]
Seems fixed.

**Comment by ichorid** [comment]
For reference, we are using two packages providing independend asyncio-related fixtures:
 * `aiohttp` provides `loop` fixture
 * `pytest-asyncio` plugin provides `event_loop` fixture and `pytest.mark.asyncio` decorator

Bad news: these things don't match. I.e. when you combine `loop` fixture with `pytest.mark.asyncio` decorator, you get semi-random crashes, etc. So, we should use the same loop generator everywhere.
