### ISSUE TITLE
Can't build Tribler on MacOS. Python and PyInstaller versions recommended.

### ISSUE THREAD

**Issue by ku9nov** [Tribler/tribler#6124]
##### Tribler version/branch+revision: #####
main and release 7.9
##### Operating system and version: #####
macOS Catalina 10.15
##### Steps to reproduce the behavior: #####
run makedist_macos.sh
##### Expected behavior: #####
its build
##### Actual behavior: #####
depending on which python and pyinstaller to use, the errors are very different:
python 3.9.5 pyisntaller 4.3:

`
 zsh: segmentation fault
`

python 3.7 pyinstaller from 3.5 to 4:

`
Please install the following dependencies to continue:
 pip3 install pyqtgraph
 apt install python-libtorrent
`

from 4 to 4.3:

`
Tribler - found missing dependencies in both!
Please install the following dependencies to continue:
 apt install python-libtorrent
`

If create deb package on ubuntu without GUI:

`
Please install the following dependencies to continue:
 pip3 install pyqtgraph
`

python 3.8 is the same and:

```
[53866] mod is NULL - structTraceback (most recent call last):
  File "struct.py", line 14, in <module>
ImportError: cannot import name '_clearcache' from '_struct' (unknown location)
[53866] mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "PyInstaller/loader/pyimod02_archive.py", line 30, in <module>
ModuleNotFoundError: No module named 'struct'
[53866] mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "PyInstaller/loader/pyimod03_importers.py", line 26, in <module>
ModuleNotFoundError: No module named 'pyimod02_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[53866] Failed to execute script pyiboot01_bootstrap
```

and many other errors
but if we use the startup script, then everything is fine
Could you please clarify which versions I need to use?
I would like to create my own dmg package. I put together a deb package on kubunta easily. But I would like to learn how to collect on all platforms. Thank you.

**Comment by devos50** [comment]
That's unfortunate to hear. I just tested it out with Python 3.9.5, Pyinstaller 4.3 and MacOS 11.3.1. Running the following command from the root directory (latest commit on the `main` branch) seems to successfully build Triber:

```
pyinstaller tribler.spec
```

You indicate that you are using our build script on Mac, however, this script requires quite some other dependencies and you might want to try the above command first. Could you let me know if the above command works?

**Comment by ku9nov** [comment]
@devos50 the result is the same.
I have to try on 11 version?

**Comment by devos50** [comment]
Well, you could upgrade to MacOS 11 if you wish, but I'm not sure if it would fix the problem.

Could you check under which Python version the `pyinstaller` command runs? You can find out the location of the Python script being executed by running `which pyinstaller` and by looking at the file located at the output path. If you are unsure how to find this version, you can also post the content of this file here 👍 

Also, you get no information besides the segmentation fault when running the `pyinstaller` command?

**Comment by ku9nov** [comment]
@devos50 now im pull main branch
```
admin@Mac-mini-admin tribler % which pyinstaller
/usr/local/bin/pyinstaller
admin@Mac-mini-admin tribler % cat /usr/local/bin/pyinstaller

#!/usr/local/opt/python@3.9/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from PyInstaller.__main__ import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
admin@Mac-mini-admin tribler % python3 -m PyInstaller tribler.spec    
115 INFO: PyInstaller: 4.3
115 INFO: Python: 3.9.5
....
```
after build 
```
admin@Mac-mini-admin tribler % ./dist/tribler.app/Contents/MacOS/tribler
[26683] mod is NULL - structTraceback (most recent call last):
  File "struct.py", line 14, in <module>
ImportError: cannot import name '_clearcache' from '_struct' (unknown location)
[26683] mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "PyInstaller/loader/pyimod02_archive.py", line 30, in <module>
ModuleNotFoundError: No module named 'struct'
[26683] mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "PyInstaller/loader/pyimod03_importers.py", line 26, in <module>
ModuleNotFoundError: No module named 'pyimod02_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[26683] Failed to execute script pyiboot01_bootstrap
```

**Comment by devos50** [comment]
Thanks for your response. Good to know that the build process finishes, although it seems to build a broken `.app`. I incorrectly assumed that the errors you posted were related to PyInstaller.

I checked it out locally and I'm getting the exact same error when running the resulting `.app`. I also checked out our main build process that we use to build the `.app` file we distributed, and it seems we are using PyInstaller 4.2 and Python 3.8 to build Tribler, also see [here](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-MacOS/243/console).

Downgrading my PyInstaller version to 4.2 gives the segmentation fault when running the `.app`, see below. I suspect this happens when importing one of the libraries (e.g., `libtorrent`).

```
martijndevos@iMac-van-Martijn dist % ./tribler.app/Contents/MacOS/tribler
INFO:__main__:Sentry has been initialised in normal mode
INFO:__main__:Root state dir: /Users/martijndevos/.Tribler
INFO:__main__:Running in "normal" mode
INFO:__main__:Enabling a workaround for macOS Big Sur
INFO:tribler_gui:Load logger config: /Users/martijndevos/.Tribler
[PID:33410] 2021-05-24 10:53:02,164 - INFO - tribler_core.dependencies(78) - Check for missing dependencies. Scope: both
[PID:33410] 2021-05-24 10:53:02,379 - INFO - tribler_core.check_os(226) - Check and enable code tracing. Process name: "gui". Log dir: "/Users/martijndevos/.Tribler"
[PID:33410] 2021-05-24 10:53:02,380 - INFO - tribler_core.check_os(208) - Enable fault handler: "/Users/martijndevos/.Tribler"
[PID:33410] 2021-05-24 10:53:02,381 - INFO - tribler_core.check_os(49) - Check environment
[PID:33410] 2021-05-24 10:53:02,381 - INFO - tribler_core.check_os(80) - Should kill other Tribler instances
[PID:33410] 2021-05-24 10:53:02,382 - INFO - tribler_core.check_os(88) - Old PID: -1. Current PID: 33410
[PID:33410] 2021-05-24 10:53:02,382 - INFO - tribler_core.check_os(54) - Check free space
zsh: segmentation fault  ./tribler.app/Contents/MacOS/tribler
```

So for now, I think using Python 3.8 in combination with PyInstaller 4.2 is the way to go. Nonetheless, I think it's important to check out what's causing our build to fail. Thanks for reporting!

**Comment by ku9nov** [comment]
@devos50 unfortunately 3.8.4 and 4.2 do not give the desired result. Always:
```
Tribler -  found missing dependencies in both!
Please install the following dependencies to continue:
 
 apt install python-libtorrent 
```
libtorrent:
```
admin@Mac-mini-admin tribler % brew info libtorrent-rasterbar
libtorrent-rasterbar: stable 1.2.10 (bottled), HEAD
C++ bittorrent library with Python bindings
https://www.libtorrent.org/
Conflicts with:
  libtorrent-rakshasa (because they both use the same libname)
/usr/local/Cellar/libtorrent-rasterbar/1.2.10_1 (279 files, 29.2MB) *
  Built from source on 2021-05-24 at 16:47:30
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libtorrent-rasterbar.rb
License: BSD-3-Clause
==> Dependencies
Build: pkg-config ✔
Required: boost ✔, boost-python3 ✔, openssl@1.1 ✔, python@3.9 ✔
==> Options
--HEAD
	Install HEAD version
```

**Comment by devos50** [comment]
Well, that's not unexpected. You most likely installed libtorrent using brew, which is dependent on Python 3.9 (since it includes Python bindings). Since the libtorrent bindings specifically target Python 3.9, they will fail to run when compiling it with Python 3.8.

The only option I can see here is to compile libtorrent, including the Python bindings, manually. This, unfortunately, is not an easy task and requires some knowledge but as long as the PyInstaller issue with Python 3.9 is not fixed, I don't see an alternative solution. Please ensure that you point to your Python 3.8 installation by setting the appropriate compilation flags. Let us know if you run into any issues and we help you further 👍 .

**Comment by devos50** [comment]
Hmm, a similar issue has been posted [here](https://github.com/borgbackup/borg/issues/5622). The issue might be related to MacOS Gatekeeper preventing the Python std library from being loaded. I just tried to disable GateKeeper but that is also not fixing it 👎
