### ISSUE TITLE
AttributeError: 'QTextEdit' object has no attribute 'setMarkdown' when viewing channel with description

### ISSUE THREAD

**Issue by scribblemaniac** [Tribler/tribler#6172]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

v7.10.0-RC2 (.deb build)

##### Operating system and version: #####

Ubuntu 21.04

##### Steps to reproduce the behavior: #####

These are the steps I took to create the issue, some of them may not be necessary:
1. With v7.10.0-exp1, create a channel with an image and rich text description.
2. With v7.10.0-RC2, open up the channel from My Channels. The exception will then occur the first time this channel is viewed for each application session.

##### Expected behavior: #####

No exception occurs and the channel image and description are properly displayed.

##### Actual behavior: #####

An exception occurs as indicated by a popup dialog. The channel image and description are not displayed, even if the channel is reloaded.

##### Relevant log file output: #####

From the error dialog:
```
tribler_gui.utilities.CreationTraceback: 
  File "src/run_tribler.py", line 213, in <module>
  File "src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
  File "src/tribler-gui/tribler_gui/tribler_request_manager.py", line 121, in <lambda>
  File "src/tribler-gui/tribler_gui/tribler_request_manager.py", line 220, in on_finished
  File "src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
  File "src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py", line 309, in on_query_results
  File "src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
  File "src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py", line 247, in on_model_info_changed
  File "src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py", line 413, in update_labels
  File "src/tribler-gui/tribler_gui/widgets/channeldescriptionwidget.py", line 299, in initialize_with_channel
  File "src/tribler-gui/tribler_gui/tribler_request_manager.py", line 180, in __init__


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/tribler-gui/tribler_gui/utilities.py", line 398, in trackback_wrapper
  File "src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
  File "src/tribler-gui/tribler_gui/widgets/channeldescriptionwidget.py", line 243, in _on_description_received
AttributeError: 'QTextEdit' object has no attribute 'setMarkdown'
```

**Comment by ichorid** [comment]
Confirmed. :+1:  This only happens in the Pyinstaller-packaged version of Tribler. We have to update our PyQT to 5.14 or later :facepalm:

**Comment by ichorid** [comment]
@xoriole , could you please update the builders?

**Comment by xoriole** [comment]
PyQt5 in all builders are updated to 5.15.x

**Comment by ichorid** [comment]
We should probably update the `requirements.txt` to reflect the 5.14+ requirement...
