### ISSUE TITLE
[devel] KeyError: 'max_peers'

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6189]
When navigating to the `IPv8` -> `overlays` tab in the Tribler debug panel, I get the following error:

```
tribler_gui.utilities.CreationTraceback: 
  File "/Users/<user>/Documents/tribler/src/run_tribler.py", line 213, in <module>
    sys.exit(app.exec_())
  File "/Users/<user>/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/Users/<user>/Documents/tribler/src/tribler-gui/tribler_gui/debug_window.py", line 210, in ipv8_tab_changed
    self.run_with_timer(self.load_ipv8_communities_tab)
  File "/Users/<user>/Documents/tribler/src/tribler-gui/tribler_gui/debug_window.py", line 152, in run_with_timer
    call_fn()
  File "/Users/<user>/Documents/tribler/src/tribler-gui/tribler_gui/debug_window.py", line 368, in load_ipv8_communities_tab
    TriblerNetworkRequest("ipv8/overlays", self.on_ipv8_community_stats)
  File "/Users/<user>/Documents/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 178, in __init__
    connect(self.received_json, self.reply_callback)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<user>/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 398, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/Users/<user>/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/Users/<user>/Documents/tribler/src/tribler-gui/tribler_gui/debug_window.py", line 386, in on_ipv8_community_stats
    item.setForeground(3, self._colored_peer_count(peer_count, overlay["max_peers"]))
KeyError: 'max_peers'
```

**Comment by devos50** [comment]
There was a mismatch with my local IPv8 version 👍
