### ISSUE TITLE
readthedocs documentation build failing

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6194]
Since ~2 weeks, the build process on the readthedocs servers is failing with the following error:

```
Running Sphinx v4.0.2

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/conf.py", line 63, in <module>
    from tribler_core.restapi.root_endpoint import RootEndpoint
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/restapi/root_endpoint.py", line 3, in <module>
    from tribler_core.modules.bandwidth_accounting.bandwidth_endpoint import BandwidthEndpoint
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/modules/bandwidth_accounting/bandwidth_endpoint.py", line 9, in <module>
    from tribler_core.restapi.rest_endpoint import HTTP_NOT_FOUND, RESTEndpoint, RESTResponse
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/restapi/rest_endpoint.py", line 6, in <module>
    from tribler_core.session import Session
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/session.py", line 20, in <module>
    from ipv8_service import IPv8
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8_service.py", line 22, in <module>
    from ipv8.messaging.anonymization.community import TunnelCommunity
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/community.py", line 14, in <module>
    from .payload import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/payload.py", line 6, in <module>
    from ...messaging.anonymization.tunnelcrypto import CryptoException
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/tunnelcrypto.py", line 8, in <module>
    from libnacl.aead import AEAD
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1246, in _get_spec
TypeError: 'Mock' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 217, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 168, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 336, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/conf.py", line 63, in <module>
    from tribler_core.restapi.root_endpoint import RootEndpoint
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/restapi/root_endpoint.py", line 3, in <module>
    from tribler_core.modules.bandwidth_accounting.bandwidth_endpoint import BandwidthEndpoint
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/modules/bandwidth_accounting/bandwidth_endpoint.py", line 9, in <module>
    from tribler_core.restapi.rest_endpoint import HTTP_NOT_FOUND, RESTEndpoint, RESTResponse
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/restapi/rest_endpoint.py", line 6, in <module>
    from tribler_core.session import Session
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/session.py", line 20, in <module>
    from ipv8_service import IPv8
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8_service.py", line 22, in <module>
    from ipv8.messaging.anonymization.community import TunnelCommunity
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/community.py", line 14, in <module>
    from .payload import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/payload.py", line 6, in <module>
    from ...messaging.anonymization.tunnelcrypto import CryptoException
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/tunnelcrypto.py", line 8, in <module>
    from libnacl.aead import AEAD
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1246, in _get_spec
TypeError: 'Mock' object is not iterable


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/conf.py", line 63, in <module>
    from tribler_core.restapi.root_endpoint import RootEndpoint
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/restapi/root_endpoint.py", line 3, in <module>
    from tribler_core.modules.bandwidth_accounting.bandwidth_endpoint import BandwidthEndpoint
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/modules/bandwidth_accounting/bandwidth_endpoint.py", line 9, in <module>
    from tribler_core.restapi.rest_endpoint import HTTP_NOT_FOUND, RESTEndpoint, RESTResponse
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/restapi/rest_endpoint.py", line 6, in <module>
    from tribler_core.session import Session
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/session.py", line 20, in <module>
    from ipv8_service import IPv8
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8_service.py", line 22, in <module>
    from ipv8.messaging.anonymization.community import TunnelCommunity
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/community.py", line 14, in <module>
    from .payload import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/payload.py", line 6, in <module>
    from ...messaging.anonymization.tunnelcrypto import CryptoException
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/pyipv8/ipv8/messaging/anonymization/tunnelcrypto.py", line 8, in <module>
    from libnacl.aead import AEAD
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1246, in _get_spec
TypeError: 'Mock' object is not iterable
```

Note that we do not see this error in our own [documentation builder job](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_build_docs/) since that job runs on a machine with all dependencies installed (which is not the case when building on the readthedocs servers).

**Comment by xoriole** [comment]
This issue should be fixed after merging https://github.com/Tribler/tribler/pull/6102

**Comment by xoriole** [comment]
Builds are passing now. Closing this issue.
<img width="958" alt="Screenshot 2021-07-14 at 13 30 32" src="https://user-images.githubusercontent.com/1442867/125615004-09e99921-f6a9-4047-8993-25b16418b32c.png">
