### ISSUE TITLE
Debian build on `main` branch is failiing

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#6223]
Debian build on `main` branch is failing with the following stacktrace while `release/7.10` branch builds fine.

```python
+ build/debian/makedist_debian.sh
Setting venv to /home/jenkins/venv
Traceback (most recent call last):
  File "build/update_version_from_git.py", line 57, in <module>
    run_command('dch -v {} New upstream release.'.format(version_id).split())
  File "build/update_version_from_git.py", line 16, in run_command
    p = Popen(cmd, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dch'
77 INFO: PyInstaller: 4.2
77 INFO: Python: 3.8.5
90 INFO: Platform: Linux-5.4.44-1-pve-x86_64-with-glibc2.27
92 INFO: UPX is not available.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jenkins/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 124, in <module>
    run()
  File "/home/jenkins/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/jenkins/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/jenkins/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/jenkins/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "tribler.spec", line 28, in <module>
    from tribler_core.modules.ipv8_module_catalog import get_hiddenimports as ipv8_module_imports
ModuleNotFoundError: No module named 'tribler_core.modules.ipv8_module_catalog'
cp: cannot stat 'dist/tribler': No such file or directory
dpkg-deb: building package 'tribler' in 'tribler_7.10.0-52-g0e7ad1a90_all.deb'.
```
Jenkins build: [#301](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Ubuntu64/301/console)

**Comment by devos50** [comment]
I think the `from tribler_core.modules.ipv8_module_catalog` got removed so you should also remove that from the `tribler.spec` file 👍

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/6302
