### ISSUE TITLE
Ubuntu 18.04.2 - Tribler crashes

### ISSUE THREAD

**Issue by Davem734** [Tribler/tribler#6228]
#### Please, fill all relevant items: ####

- [x ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.10.0
##### Operating system and version: #####
Ubuntu 18.04.2
##### Steps to reproduce the behavior: #####
Run Tribler
##### Expected behavior: #####
Tribler runs
##### Actual behavior: #####
Tribler crashes 
##### Relevant log file output: #####
tribler_gui.utilities.CreationTraceback: 
  File "run_tribler.py", line 213, in <module>
  File "tribler_gui/utilities.py", line 395, in trackback_wrapper
  File "tribler_gui/core_manager.py", line 97, in on_request_error
  File "tribler_gui/core_manager.py", line 177, in start_tribler_core

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tribler_gui/utilities.py", line 398, in trackback_wrapper
  File "tribler_gui/utilities.py", line 395, in trackback_wrapper
  File "tribler_gui/core_manager.py", line 87, in on_core_finished
RuntimeError: The Tribler core has unexpectedly finished with exit code 6 and status: 1!

**Comment by Davem734** [comment]
Rebooting Ubuntu resolved the issue for now. I will post an update if the problem happens again ...
