### ISSUE TITLE
GUI feedback dialog tests results in (additional) error

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6233]
Tribler 7.10 (and probably earlier): on testing sending crash data (feedback dialog) `test_feedback_dialog_report_sent`

```python
  File "/home/<user>/my_SRC/TRIBLER/tribler_ichorid/src/tribler-gui/tribler_gui/tests/test_gui.py", line 225, in test_feedback_dialog_report_sent
    dialog = FeedbackDialog(window, "Tribler GUI Test to test sending crash report works", "1.2.3", 23)
  File "/home/<user>/my_SRC/TRIBLER/tribler_ichorid/src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py", line 66, in __init__
    connect(self.send_report_button.clicked, self.on_send_clicked)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<user>/my_SRC/TRIBLER/tribler_ichorid/src/tribler-gui/tribler_gui/utilities.py", line 398, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/home/<user>/my_SRC/TRIBLER/tribler_ichorid/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/home/<user>/my_SRC/TRIBLER/tribler_ichorid/src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py", line 169, in on_send_clicked
    self.on_report_sent()
TypeError: on_report_sent() missing 1 required positional argument: 'response'
```

**Comment by ichorid** [comment]
@devos50 , could you please take this one, since you're already refactoring the GUI tester?

**Comment by devos50** [comment]
I'm not refactoring the GUI tests at all but I'll have a look at it.

**Comment by ichorid** [comment]
Hmm... :thinking: 
I've must have misunderstood you during the last meeting. Anyway, thanks! :pray: 
This should be easy to fix.
