### ISSUE TITLE
[main] Tribler build broken

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6249]
Building Tribler is broken after merging #6206, on all platforms, see [here](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build/258/).

Stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "tribler.spec", line 28, in <module>
    from tribler_core.modules.ipv8_module_catalog import get_hiddenimports as ipv8_module_imports
ModuleNotFoundError: No module named 'tribler_core.modules.ipv8_module_catalog'
```

**Comment by xoriole** [comment]
Build on MacOS, Windows and Linux is fixed but there is an issue on building the source tar.
```python
+ python3 build/update_version_from_git.py
Traceback (most recent call last):
  File "build/update_version_from_git.py", line 57, in <module>
    run_command('dch -v {} New upstream release.'.format(version_id).split())
  File "build/update_version_from_git.py", line 16, in run_command
    p = Popen(cmd, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dch': 'dch'
```
https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build/261/

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/6302
