### ISSUE TITLE
[main] AttributeError: 'NoneType' object has no attribute 'initialize'

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6251]
After merging #6206 I'm getting the following (silent) stack trace immediately after start when running Tribler with an empty state directory:

```
[PID:77036] 2021-08-12 16:23:14,110 - ERROR <ipv8_service:169> root.on_tick(): Exception occurred while trying to walk!
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8_service.py", line 167, in on_tick
    strategy.take_step()
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/peerdiscovery/discovery.py", line 79, in take_step
    self.overlay.get_new_introduction()
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/community.py", line 466, in get_new_introduction
    self.bootstrap()
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/community.py", line 172, in bootstrap
    self._initialize_bootstrappers()
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/community.py", line 160, in _initialize_bootstrappers
    future = ensure_future(bootstrapper.initialize(self))
AttributeError: 'NoneType' object has no attribute 'initialize'
```

Possibly related to #6250. I've confirmed that I have the latest IPv8 submodule checked out.

**Comment by kozlovsky** [comment]
Thanks, I was able to reproduce it on my machine, the PR should fix the problem
