### ISSUE TITLE
[main] readthedocs build failing (ImportError: cannot import name 'cached_property' from 'functools' )

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6261]
Our readthedocs build is failing with the following stack trace:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 327, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/conf.py", line 63, in <module>
    from tribler_core.restapi.root_endpoint import RootEndpoint
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/restapi/root_endpoint.py", line 20, in <module>
    from tribler_core.restapi.trustview_endpoint import TrustViewEndpoint
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/restapi/trustview_endpoint.py", line 1, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.7/functools.py)
```

It seems that the trustview endpoint has been refactored in #6206 and an import from `functools` (built-in library) has been added. This function is only available in Python 3.8+ but readthedocs uses Python 3.7 to compile the documentation.

**Comment by qstokkink** [comment]
I believe you can switch ReadTheDocs to Python 3.8 (through a config file) by using the `latest` [`build.image`](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-image) and then setting your [`python.version`](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version) to `3.8`.

**Comment by xoriole** [comment]
Setting the python version to 3.8 fixes this issue but it raises the following issue:
```python
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/sysadmin/tudelft/dev/docs/tribler/envs/fix-documentation/lib/python3.8/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/sysadmin/tudelft/dev/docs/tribler/doc/conf.py", line 64, in <module>
    from tribler_core.restapi.root_endpoint import RootEndpoint
  File "/home/sysadmin/tudelft/dev/docs/tribler/src/tribler-core/tribler_core/restapi/root_endpoint.py", line 4, in <module>
    from tribler_core.modules.bandwidth_accounting.bandwidth_endpoint import BandwidthEndpoint
  File "/home/sysadmin/tudelft/dev/docs/tribler/src/tribler-core/tribler_core/modules/bandwidth_accounting/bandwidth_endpoint.py", line 5, in <module>
    from ipv8.REST.schema import schema
ModuleNotFoundError: No module named 'ipv8'

```

**Comment by xoriole** [comment]
Import error was because of the missing recursive import. https://github.com/Tribler/tribler/pull/6329 fixes the issue.
