### ISSUE TITLE
[main] Tribler gets stuck on loading screen after component crash

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6263]
After the crash of #6262 my Tribler window was stuck in the "Loading..." screen. Even worse, it was impossible to CTRL+C to death.

![screenshot](https://user-images.githubusercontent.com/3630389/129885867-ea3a9466-ad50-4867-87a1-09127b806da4.png)

**Comment by qstokkink** [comment]
I got the following error once the "force shutdown" appeared, probably related:

```python
Traceback (most recent call last):
  File "/home/<user>/Documents/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 1088, in clicked_force_shutdown
    process_checker = ProcessChecker()
TypeError: __init__() missing 1 required positional argument: 'state_directory'
```

**Comment by drew2a** [comment]
I see the same behavior after the error has been sent to Sentry:
![image](https://user-images.githubusercontent.com/13798583/134156412-5650e6e7-c63c-4f0e-bb5f-8937996f2b4e.png)
 
```python
[PID:2669] 2021-09-21 12:34:28,177 - ERROR <error_handler:37> ErrorHandler.gui_error(): tribler_gui.utilities.CreationTraceback: 
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/run_tribler.py", line 131, in <module>
    sys.exit(app.exec_())
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 97, in on_request_error
    self.start_tribler_core(core_args=core_args, core_env=core_env)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 177, in start_tribler_core
    connect(self.core_process.finished, self.on_core_finished)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 398, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 87, in on_core_finished
    raise RuntimeError(exception_msg)
RuntimeError: The Tribler core has unexpectedly finished with exit code 1 and status: 0!

Traceback (most recent call last):

(Timestamp: 1632220468177, traceback timestamp: 1632220467564)
```

**Comment by drew2a** [comment]
The issue is not fixed.

How to reproduce:
1. Go to `notifier.py`
2. Add line `raise Exception('test')` to 
```python
    def notify(self, subject, *args):
        # We have to call the notifier callbacks through call_soon_threadsafe
        # because the notify method could have been called from a non-reactor thread
        raise Exception('test')
        self._loop.call_soon_threadsafe(self._notify, subject, *args)
```

Note: before the grand refactoring this trick did not lead to stuck.

![image](https://user-images.githubusercontent.com/13798583/140087209-7e104337-c3b0-404a-b444-20aa6261c0bc.png)

**Comment by drew2a** [comment]
The issue is probably solved not fully. My Triber is newer stuck on the loading screen in case of an error, but It also not shows me the error.

### How to reproduce:
1. Change TagsDb to:
```python
    @staticmethod
    def define_binding(db):
        class Peer(db.Entity):
            id = orm.PrimaryKey(int, auto=True)
            public_key = orm.Required(bytes, unique=True)
+           public_key1= orm.Required(bytes, unique=True)
            added_at = orm.Optional(datetime.datetime, default=datetime.datetime.utcnow)
            operations = orm.Set(lambda: TorrentTagOp)
```
2. Run Tribler

### Actual behavior

In ~ 50% runs I don't see an error report on the GUI side. But I see an exception in the core logs:

```python
[PID:29566] 2021-11-03 19:37:01,034 - ERROR <exception_handler:85> CoreExceptionHandler.unhandled_error_observer(): Unhandled exception occurred! no such column: Peer.public_key1
--LONG TEXT--
Traceback (most recent call last):
  File "/Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/pony/orm/dbapiprovider.py", line 55, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/pony/orm/dbapiprovider.py", line 278, in execute
    if arguments is None: cursor.execute(sql)
sqlite3.OperationalError: no such column: Peer.public_key1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-core/tribler_core/components/base.py", line 160, in start
    await self.run()
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-core/tribler_core/components/tag/tag_component.py", line 31, in run
    self.tags_db = TagDatabase(str(db_path))
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-core/tribler_core/components/tag/db/tag_db.py", line 20, in __init__
    self.instance.generate_mapping(create_tables=True)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/pony/orm/core.py", line 1147, in generate_mapping
    if create_tables: database.create_tables(check_tables)
  File "<string>", line 2, in create_tables
  File "/Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/pony/orm/core.py", line 533, in new_func
    result = func(*args, **kwargs)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/pony/orm/core.py", line 1214, in create_tables
    if check_tables: database.schema.check_tables(database.provider, connection)
  File "/Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/pony/orm/dbschema.py", line 78, in check_tables
    provider.execute(cursor, sql)
  File "<string>", line 2, in execute
  File "/Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/pony/orm/dbapiprovider.py", line 72, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such column: Peer.public_key1

--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': ComponentStartupException('TagComponent'), 'future': <Task finished name='Task-63' coro=<Session._reraise_startup_exception_in_separate_task.<locals>.exception_reraiser() done, defined at /Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-core/tribler_core/components/base.py:113> exception=ComponentStartupException('TagComponent')>}
```

**Comment by kozlovsky** [comment]
I can't reproduce it locally, but my current hypothesis is that we have a race condition in notifications from Core to GUI. Probably the notification about an exception gets lost if the exception happens too early during the Tribler startup. I'm investigating this.
