### ISSUE TITLE
[main] Exception in LibtorrentComponentImp.start() is reported to Sentry incorrectly

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6274]
During an attempt to repeat this error: https://github.com/Tribler/tribler/issues/6262 we found that the corresponding Sentry report looks incorrect. 

#### The problem

The root error is not presented in the report.
Incorrect Sentry report: https://sentry.tribler.org/organizations/tribler/issues/842/?project=7

![image](https://user-images.githubusercontent.com/13798583/130219546-de0116c4-e685-4de1-9f3a-11eb7b73cc65.png)

#### The root exception (correct):

```python
[PID:2276] 2021-08-18 12:45:28,131 - ERROR <base:161> LibtorrentComponent.start(): Exception in LibtorrentComponentImp.start(): KeyError:'/channels'
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/libtorrent.py", line 48, in run
    rest_manager.get_endpoint(endpoint).download_manager = download_manager
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/restapi/rest_manager.py", line 98, in get_endpoint
    return self.root_endpoint.endpoints['/' + name]
KeyError: '/channels'
```

**Comment by drew2a** [comment]
This also happened after the big PR (сс @ichorid). As I'm more familiar with bug reporting in Tribler, I'll take the issue and try to fix it myself.

**Comment by drew2a** [comment]
After some investigations, it is clear that Error Reporting in general works correctly.

The case described in this issue is the consequence of the following:
1. An error has been raised in the core
2. The core's error has been reported to Sentry: https://sentry.tribler.org/organizations/tribler/issues/878
3. GUI loses connection to the core
4. GUI raises an error 
5. GUI's error has been reported to Sentry: https://sentry.tribler.org/organizations/tribler/issues/879

For the end-user, it looks like just one (the last) error has been reported. And the last reported error (from GUI) does not contain the core issue, which led to the feeling that Error Reporting doesn't work.
