### ISSUE TITLE
Error on deletion of a 40k-files torrent

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6454]
Latest `main`: during deletion of a download with **many** files, such as[ this one](https://academictorrents.com/details/5a447ff50062194bd58dd11c0fedead59e6d873c) (40k entries!)

Steps to reproduce:
1. start downloading a 40k files torrent
2. wait until some files finish
3. in the downloads table, right-clik on the torrent and choose "remove", then "remove with files".
4. with some (bad) luck see the following message appear
```
An error occurred during the request:

Traceback (most recent call last):
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/restapi/rest_manager.py", line 60, in error_middleware
    response = await handler(request)
  File "/home/vader/.pyenv/versions/tribler382/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/components/libtorrent/restapi/downloads_endpoint.py", line 330, in get_downloads
    download_json["files"] = self.get_files_info_json(download)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/components/libtorrent/restapi/downloads_endpoint.py", line 150, in get_files_info_json
    files_completion = {name: progress for name, progress in download.get_state().get_files_completion()}
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/src/tribler-core/tribler_core/components/libtorrent/download_manager/download_state.py", line 170, in get_files_completion
    progress = self.download.handle.file_progress(flags=1)
RuntimeError: invalid torrent handle used
```

**Comment by qstokkink** [comment]
The reported error happens on the following lines, note the `self.download.handle.is_valid()` check before accessing the handle:

https://github.com/Tribler/tribler/blob/504eb18640a0f39eb76bb614aae24080f35603aa/src/tribler/core/components/libtorrent/download_manager/download_state.py#L162-L164

For the `RuntimeError` to occur either (1) the handle becomes invalid between calls or (2) the `is_valid()` return value is incorrect. In both cases, I don't see a more elegant solution than simply catching the `RuntimeError`.
