### ISSUE TITLE
[Jenkins] Tunnel experiments broken

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6471]
None of the experiments in `experiment/tunnel_community` [on Jenkins](https://jenkins-ci.tribler.org/job/tunnel_experiments/) work with the latest `main` branch.

These are the outputs:

```python
speed_test_e2e.py
Traceback (most recent call last):
  File "/home/jenkins/ci/workspace/tunnel_experiments/speed_test_e2e/tribler/experiment/tunnel_community/speed_test_e2e.py", line 9, in <module>
    from experiment.tunnel_community.speed_test_exit import EXPERIMENT_NUM_CIRCUITS, EXPERIMENT_NUM_HOPS, \
  File "/home/jenkins/ci/workspace/tunnel_experiments/speed_test_e2e/tribler/experiment/tunnel_community/speed_test_exit.py", line 8, in <module>
    from tribler_core.components.ipv8.ipv8_component import Ipv8Component
  File "/home/jenkins/ci/workspace/tunnel_experiments/speed_test_e2e/tribler/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py", line 116
    if bootstrap_override := self.session.config.ipv8.bootstrap_override:
                           ^
SyntaxError: invalid syntax
```

```python
speed_test_exit.py
Traceback (most recent call last):
  File "/home/jenkins/ci/workspace/tunnel_experiments/speed_test_exit/tribler/experiment/tunnel_community/speed_test_exit.py", line 8, in <module>
    from tribler_core.components.ipv8.ipv8_component import Ipv8Component
  File "/home/jenkins/ci/workspace/tunnel_experiments/speed_test_exit/tribler/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py", line 116
    if bootstrap_override := self.session.config.ipv8.bootstrap_override:
                           ^
SyntaxError: invalid syntax
```

```python
hidden_peer_discovery.py
Traceback (most recent call last):
  File "/home/jenkins/ci/workspace/tunnel_experiments/hidden_peer_discovery/tribler/experiment/tunnel_community/hidden_peer_discovery.py", line 8, in <module>
    from tribler_core.components.ipv8.ipv8_component import Ipv8Component
  File "/home/jenkins/ci/workspace/tunnel_experiments/hidden_peer_discovery/tribler/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py", line 116
    if bootstrap_override := self.session.config.ipv8.bootstrap_override:
                           ^
SyntaxError: invalid syntax
```

The only reason these jobs were passing before, is because they were running a branch that was +- 500 commits behind `main`.

---

Edit: the same is true for the [`Initial_filling_velocity`](https://jenkins-ci.tribler.org/job/popularity_experiments/job/Initial_filling_velocity/) experiment:

```python
initial_filling.py -i 30 -t 1800 -f result.csv
Traceback (most recent call last):
  File "/home/jenkins/ci/workspace/popularity_experiments/Initial_filling_velocity/tribler/experiment/popularity_community/initial_filling.py", line 15, in <module>
    from tribler_core.components.ipv8.ipv8_component import Ipv8Component
  File "/home/jenkins/ci/workspace/popularity_experiments/Initial_filling_velocity/tribler/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py", line 116
    if bootstrap_override := self.session.config.ipv8.bootstrap_override:
                           ^
SyntaxError: invalid syntax
```

**Comment by kozlovsky** [comment]
I'm upgrading Jenkins to Python 3.8, it should work soon
