### ISSUE TITLE
tribler is not usable on fedora 35 / aborts with error parser not found

### ISSUE THREAD

**Issue by damnms** [Tribler/tribler#6538]
#### Please, fill all relevant items: ####

- [ x] I have read CONTRIBUTING.rst

- [ x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
stable, the .tar.xz

##### Operating system and version: #####
fedora 35

##### Steps to reproduce the behavior: #####
follow the https://tribler.readthedocs.io/en/latest/development/development_on_linux.html guide for fedora and it will fail at ./tribler.sh 

##### Expected behavior: #####
to have a UI/GUI that starts

##### Actual behavior: #####
an error that a package parser is missing, but no idea what parser 

##### Relevant log file output: #####
no parser is mentioned in requirements.txt

```
[oli@DESKTOP-E83VF5L src]$ ./tribler.sh 
INFO:__main__:Sentry has been initialised in normal mode
INFO:__main__:Root state dir: /home/oli/.Tribler
INFO:__main__:Running in "normal" mode
INFO:tribler_gui:Load logger config: /home/oli/.Tribler
[PID:46655] 2021-11-09 17:30:46,161 - INFO - tribler_core.dependencies(78) - Check for missing dependencies. Scope: both
[PID:46655] 2021-11-09 17:30:46,301 - INFO - tribler_core.check_os(226) - Check and enable code tracing. Process name: "gui". Log dir: "/home/oli/.Tribler"
[PID:46655] 2021-11-09 17:30:46,301 - INFO - tribler_core.check_os(208) - Enable fault handler: "/home/oli/.Tribler"
[PID:46655] 2021-11-09 17:30:46,301 - INFO - tribler_core.check_os(49) - Check environment
[PID:46655] 2021-11-09 17:30:46,301 - INFO - tribler_core.check_os(80) - Should kill other Tribler instances
[PID:46655] 2021-11-09 17:30:46,301 - INFO - tribler_core.check_os(88) - Old PID: -1. Current PID: 46655
[PID:46655] 2021-11-09 17:30:46,301 - INFO - tribler_core.check_os(54) - Check free space
[PID:46655] 2021-11-09 17:30:46,332 - ERROR <run_tribler:216> __main__.<module>(): No module named 'parser'
Traceback (most recent call last):
  File "/home/oli/Downloads/tribler/src/run_tribler.py", line 187, in <module>
    from tribler_gui.tribler_window import TriblerWindow
  File "/home/oli/Downloads/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 82, in <module>
    from tribler_gui.widgets.tablecontentmodel import DiscoveredChannelsModel, PopularTorrentsModel
  File "/home/oli/Downloads/tribler/src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py", line 11, in <module>
    from tribler_core.modules.metadata_store.orm_bindings.channel_node import NEW
  File "/home/oli/Downloads/tribler/src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_node.py", line 7, in <module>
    from pony import orm
  File "/home/oli/.local/lib/python3.10/site-packages/pony/orm/__init__.py", line 3, in <module>
    from pony.orm.core import *
  File "/home/oli/.local/lib/python3.10/site-packages/pony/orm/core.py", line 17, in <module>
    from pony.thirdparty.compiler import ast, parse
  File "/home/oli/.local/lib/python3.10/site-packages/pony/thirdparty/compiler/__init__.py", line 24, in <module>
    from .transformer import parse, parseFile
  File "/home/oli/.local/lib/python3.10/site-packages/pony/thirdparty/compiler/transformer.py", line 32, in <module>
    import parser
ModuleNotFoundError: No module named 'parser'
********************************************************************************
Import Error
********************************************************************************
Import error: No module named 'parser'
********************************************************************************
Error while showing a message box: [Errno 2] No such file or directory: 'xmessage'
```

**Comment by xoriole** [comment]
@damnms Thank you for the report. We have Flatpak build now available which should work on Fedora as well. If you'd like to try, it is available here: https://flathub.org/apps/details/org.tribler.Tribler

@kozlovsky The module error seems to be related to pony orm looking at the stack trace. Would you like to check this one?

**Comment by damnms** [comment]
awesome, thanks, i'll go with the flatpak package

**Comment by kozlovsky** [comment]
Right now, PonyORM does not support Python 3.10. I expect the support will be added in a month. Until that, you need to use Python 3.8 or 3.9.
