### ISSUE TITLE
[Main] Pressing the keyboard "Home" button on empty tags list crash

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6549]
Steps to reproduce:
1. Click "Be the first to suggest tags" on a torrent
2. Press "Home" button on the keyboard

```python
Traceback (most recent call last):
  File "/home/<user>/tribler/src/tribler-gui/tribler_gui/widgets/tagslineedit.py", line 413, in keyPressEvent
    self.edit_tag(0)
  File "/home/<user>/tribler/src/tribler-gui/tribler_gui/widgets/tagslineedit.py", line 311, in edit_tag
    self.move_cursor(len(self.tags[self.editing_index].text), False)
IndexError: list index out of range
```

**Comment by devos50** [comment]
Seems that I missed this bug. I will fix it tomorrow.
