### ISSUE TITLE
[Main] Brackets in search query crashes Tribler

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6576]
## How to reproduce:
1. Run Tribler
2. Put "[]" to the search field

![image](https://user-images.githubusercontent.com/13798583/143043195-728fce1f-b332-4b25-91a7-fc84584cab01.png)

### Exception

```python
TypeError
setStringList(self, Iterable[str]): argument 1 has unexpected type 'str'
```

### Stacktrace

```python
tribler_gui.utilities.CreationTraceback: , 
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/run_tribler.py", line 128, in <module>, 
    sys.exit(app.exec_()), 
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 670, in on_search_text_change, 
    TriblerNetworkRequest(, 
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 178, in __init__, 
    connect(self.received_json, self.reply_callback), 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 373, in trackback_wrapper, 
    raise exc from CreationTraceback(traceback_str), 
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 370, in trackback_wrapper, 
    callback(*args, **kwargs), 
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 678, in on_received_search_completions, 
    self.search_completion_model.setStringList(completions["completions"]), 
TypeError: setStringList(self, Iterable[str]): argument 1 has unexpected type 'str'
```

### Sentry Event
https://sentry.tribler.org/organizations/tribler/issues/965/?project=3&query=is%3Aunresolved

**Comment by drew2a** [comment]
The error happened because in the case of `query == ""` the `on_received_search_completions` calls with the following arguments:

```python
completions = {'completions': ''}
```

These completions will pass to the `self.search_completion_model.setStringList(completions["completions"])` as a string, but `self.search_completion_model.setStringList` waits a list.


It is happening here: https://github.com/Tribler/tribler/blob/726dd338a2c790c530efac0908e055a097ed42aa/src/tribler-gui/tribler_gui/tribler_window.py#L695-L699
