### ISSUE TITLE
TypeError: setRawHeader argument 2 has unexpected type 'str'

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6607]
Suddenly, out of the blue, `run_tribler.py` stopped working on my machine. An attempt to run it leads to the following error:

```python
Traceback (most recent call last):
  File "C:\dev\tribler\src\run_tribler.py", line 158, in <module>
    window = TriblerWindow(settings,
  File "C:\dev\tribler\src\tribler-gui\tribler_gui\tribler_window.py", line 166, in __init__
    self.core_manager = CoreManager(self.root_state_dir, api_port, api_key, self.error_handler)
  File "C:\dev\tribler\src\tribler-gui\tribler_gui\core_manager.py", line 31, in __init__
    self.events_manager = EventRequestManager(self.api_port, self.api_key, error_handler)
  File "C:\dev\tribler\src\tribler-gui\tribler_gui\event_request_manager.py", line 40, in __init__
    self.request.setRawHeader(b'X-Api-Key', api_key)
TypeError: setRawHeader(self, Union[QByteArray, bytes, bytearray], Union[QByteArray, bytes, bytearray]): argument 2 has unexpected type 'str'
```

Interestingly, the error persists even if I roll back to a previous version of Tribler, for example, to release 7.10. The fact that the error persists even on the version of code that successfully worked before probably means that some config changes cause it. But I did not change anything in the config. The value of `api_key` is stored in `triblerd.conf`, but removing it did not fix the problem.

As it turns out, the encoding/decoding of api_key when passing it from GUI to Core was wrong. I fixed it in PR #6608.

But I'm still cannot understand how the broken encoding/decoding of `api_key` worked successfully up to this day and why it suddenly stopped working on my machine at that exact moment.

Anyway, the following PR #6608 fixes it.

**Comment by xoriole** [comment]
@kozlovsky With the latest PR merged, Tribler fails on my setup with the following stacktrace
```python
/home/jupiter/tudelft/tribler/venv/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/jupiter/tudelft/release/tribler/src/run_tribler.py", line 158, in <module>
    window = TriblerWindow(settings,
  File "/home/jupiter/tudelft/release/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 166, in __init__
    self.core_manager = CoreManager(self.root_state_dir, api_port, api_key, self.error_handler)
  File "/home/jupiter/tudelft/release/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 31, in __init__
    self.events_manager = EventRequestManager(self.api_port, self.api_key, error_handler)
  File "/home/jupiter/tudelft/release/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 40, in __init__
    self.request.setRawHeader(b'X-Api-Key', api_key.encode('ascii'))
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by kozlovsky** [comment]
@xoriole hmm, that is strange. On the GUI side, we always work with api_key as string, except when passing it as a request header. At what time it becomes bytes? I'll add a defensive code for that.
