### ISSUE TITLE
CancelledError on Tribler shutdown shortly after start

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6648]
If a user stops Tribler shortly after the launch, sometimes the following exception arises:

```python
Traceback (most recent call last):
  File "C:\dev\tribler\src\pyipv8\ipv8\bootstrapping\dispersy\bootstrapper.py", line 52, in get_addresses
    async def get_addresses(self, overlay: Community, timeout: float) -> Iterable[Address]:
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\dev\tribler\src\pyipv8\ipv8\community.py", line 186, in received_bootstrapped_addresses
    if addresses and addresses.result():
asyncio.exceptions.CancelledError
```

It seems, [`received_bootstrapped_addresses`](https://github.com/Tribler/py-ipv8/blob/b46f9e0f62c5fd2a8fa9f0f957168c56a9fee6df/ipv8/community.py#L185) method should catch the possible `CancelledError` exception when requesting the future's value `addresses.result()`:

```python
def bootstrap(self):
    ...
    for bootstrapper in self.bootstrappers:
        task = self.register_anonymous_task(...)
        task.add_done_callback(self.received_bootstrapped_addresses)

def received_bootstrapped_addresses(self, addresses):
    if addresses and addresses.result():
        for address in list(addresses.result())[:self.max_peers]:
            self.walk_to(address)
```

**Comment by qstokkink** [comment]
This will be fixed by the next IPv8 pointer update.
