### ISSUE TITLE
Documentation build failing - missing module faker

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#6655]
The documentation build is failing with missing dependency. The stacktrace is below:
```
Running Sphinx v4.3.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.8/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/conf.py", line 48, in <module>
    from extract_swagger import extract_swagger  # noqa: I100
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/extract_swagger.py", line 10, in <module>
    from tribler_core.components.restapi.rest.rest_manager import ApiKeyMiddleware, RESTManager, error_middleware
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/components/restapi/rest/rest_manager.py", line 12, in <module>
    from tribler_core.components.reporter.exception_handler import default_core_exception_handler
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/components/reporter/exception_handler.py", line 11, in <module>
    from tribler_common.sentry_reporter.sentry_reporter import SentryReporter
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py", line 9, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 216, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.8/site-packages/sphinx/config.py", line 173, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.8/site-packages/sphinx/config.py", line 342, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.8/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/conf.py", line 48, in <module>
    from extract_swagger import extract_swagger  # noqa: I100
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/extract_swagger.py", line 10, in <module>
    from tribler_core.components.restapi.rest.rest_manager import ApiKeyMiddleware, RESTManager, error_middleware
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/components/restapi/rest/rest_manager.py", line 12, in <module>
    from tribler_core.components.reporter.exception_handler import default_core_exception_handler
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/components/reporter/exception_handler.py", line 11, in <module>
    from tribler_common.sentry_reporter.sentry_reporter import SentryReporter
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py", line 9, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/envs/latest/lib/python3.8/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/conf.py", line 48, in <module>
    from extract_swagger import extract_swagger  # noqa: I100
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/doc/extract_swagger.py", line 10, in <module>
    from tribler_core.components.restapi.rest.rest_manager import ApiKeyMiddleware, RESTManager, error_middleware
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/components/restapi/rest/rest_manager.py", line 12, in <module>
    from tribler_core.components.reporter.exception_handler import default_core_exception_handler
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-core/tribler_core/components/reporter/exception_handler.py", line 11, in <module>
    from tribler_common.sentry_reporter.sentry_reporter import SentryReporter
  File "/home/docs/checkouts/readthedocs.org/user_builds/tribler/checkouts/latest/src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py", line 9, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
```

Reference: https://readthedocs.org/projects/tribler/builds/15536296/

**Comment by xoriole** [comment]
Build still failing, reopening the issue
https://readthedocs.org/projects/tribler/builds/15581583/

**Comment by xoriole** [comment]
Here is a successful build after the fix:
https://readthedocs.org/projects/tribler/builds/15691755/
