### ISSUE TITLE
TypeError: No Python class registered for C++ class libtorrent

### ISSUE THREAD

**Issue by Anth0rx** [Tribler/tribler#6717]
**Describe the bug**
I currently receive a libtorrent related error when I try to download a torrent from a torrent file.

**To Reproduce**
1. Go to "Add torrent"
2. Click on "Import torrent from file"
3. Wait a moment

**Expected behavior**
I would expect the download to start properly.

**Logs**
```
[PID:49542] 2022-01-11 16:35:06,868 - ERROR <error_handler:67> ErrorHandler.core_error(): No Python class registered for C++ class libtorrent::flags::bitfield_flag<unsigned char, libtorrent::connection_type_tag, void>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/var/home/Anth0rx/Downloads/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/var/home/Anth0rx/Downloads/tribler/src/pyipv8/ipv8/taskmanager.py", line 18, in interval_runner
    await task(*args)
  File "/var/home/Anth0rx/Downloads/tribler/src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py", line 776, in _invoke_states_cb
    await result
  File "/var/home/Anth0rx/Downloads/tribler/src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py", line 798, in sesscb_states_callback
    for peer in download.get_peerlist():
  File "/var/home/Anth0rx/Downloads/tribler/src/tribler-core/tribler_core/components/libtorrent/download_manager/download.py", line 529, in get_peerlist
    'connection_type': peer_info.connection_type,
TypeError: No Python class registered for C++ class libtorrent::flags::bitfield_flag<unsigned char, libtorrent::connection_type_tag, void>
```

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue 35
 - Tribler's version 7.11

**Comment by brausepulver** [comment]
Downgrading to libtorrent-rasterbar 1.2.15 from 2.0.5 fixed this issue for me.

**Comment by devos50** [comment]
@Anth0rx I suppose you are running Tribler from source?

Tribler indeed is not compatible (yet) with libtorrent 2.0 so downgrading to 1.2.x (or 1.1.x) is the best option for now 👍

**Comment by drew2a** [comment]
So, I close the issue because there are seemingly no bugs from our side.
