### ISSUE TITLE
Startup issue on Ubuntu (frozen environment)

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#6733]
Running Tribler (from the pyinstaller build) on Ubuntu fails to start with the following stacktrace:
```
INFO:__main__:Sentry has been initialised in normal mode
INFO:__main__:Root state dir: /home/sysadmin/.Tribler
INFO:__main__:
INFO:tribler_common.logger:Load logger config: app_mode=tribler-gui, config_path=/usr/share/tribler/tribler_source/tribler_common/logger.yaml, dir=/home/sysadmin/.Tribler
Error in loading logger config. Using default configs. Error: Unable to configure handler 'stderr_handler'
INFO:tribler_core.check_os:Check and enable code tracing. Process name: "gui". Log dir: "/home/sysadmin/.Tribler"
INFO:tribler_core.check_os:Enable fault handler: "/home/sysadmin/.Tribler"
INFO:tribler_core.check_os:Check environment
INFO:tribler_core.check_os:Check free space
INFO:TriblerApplication:Start Tribler application. Win id: "triblerapp". Sys argv: "['/usr/share/tribler/tribler']"
INFO:TriblerApplication:No running instances (socket error: 2)
INFO:tribler_gui.utilities:Available Tribler translations {'Portuguese': 'pt_BR', 'Chinese': 'zh_CN', 'Russian': 'ru_RU', 'English': 'en_US'}
INFO:tribler_gui.utilities:System language: ['en-US'], Tribler language: ['en', 'en-US', 'en-Latn-US']
INFO:__main__:Start Tribler Window
INFO:NetworkUtils:Looking for first free port in range [52194..65535]
INFO:NetworkUtils:52194 is free
INFO:Tribler Config:Load: /home/sysadmin/.Tribler/7.10/triblerd.conf. State dir: /home/sysadmin/.Tribler/7.10. Reset config on error: True
INFO:Tribler Config:Init. State dir: None. File: None
INFO:__main__:Sentry has been initialised in normal mode
usage: tribler [-h] [--core] [--gui-test-mode]
tribler: error: unrecognized arguments: /usr/share/tribler/tribler
WARNING:CoreManager:The Tribler core has unexpectedly finished with exit code 2 and status: 0!
Last core output: 
 usage: tribler [-h] [--core] [--gui-test-mode]
tribler: error: unrecognized arguments: /usr/share/tribler/tribler
ERROR:ErrorHandler:tribler_gui.utilities.CreationTraceback: 
  File "run_tribler.py", line 165, in <module>
  File "tribler_gui/utilities.py", line 400, in trackback_wrapper
  File "tribler_gui/core_manager.py", line 103, in start_tribler_core


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tribler_gui/utilities.py", line 403, in trackback_wrapper
  File "tribler_gui/utilities.py", line 400, in trackback_wrapper
  File "tribler_gui/core_manager.py", line 169, in on_core_finished
tribler_gui.exceptions.CoreCrashedError: The Tribler core has unexpectedly finished with exit code 2 and status: 0!
Last core output: 
 usage: tribler [-h] [--core] [--gui-test-mode]
tribler: error: unrecognized arguments: /usr/share/tribler/tribler

INFO:CoreManager:Stopping Core manager
INFO:CoreManager:Sending shutdown request to Tribler Core
INFO:SentryReporter:Event from exception: The Tribler core has unexpectedly finished with exit code 2 and status: 0!
Last core output: 
 usage: tribler [-h] [--core] [--gui-test-mode]
tribler: error: unrecognized arguments: /usr/share/tribler/tribler
INFO:__main__:Shutting down Tribler
```

The issue is because of the difference how arguments are parsed on the frozen version

**Comment by drew2a** [comment]
@xoriole is this issue still actual?
