### ISSUE TITLE
[7.10] Tribler core crashes with ValueError "Failed to decrypt message".

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6749]
The following exception caused [core crash](https://sentry.tribler.org/organizations/tribler/issues/1103/?project=7) in Tribler 7.10:

```python
RuntimeError: The Tribler core has unexpectedly finished with exit code 11 and status: 1!, 
Traceback (most recent call last):, 
  File "ipv8/messaging/anonymization/community.py", line 647, in on_packet_from_circuit, 
  File "ipv8/messaging/anonymization/community.py", line 42, in wrapper, 
  File "ipv8/messaging/anonymization/community.py", line 791, in on_extended, 
  File "tribler_core/modules/tunnel/community/triblertunnel_community.py", line 440, in _ours_on_created_extended, 
  File "ipv8/messaging/anonymization/community.py", line 512, in _ours_on_created_extended, 
  File "ipv8/messaging/anonymization/tunnelcrypto.py", line 79, in decrypt_str, 
  File "libnacl/aead.py", line 59, in decrypt, 
  File "libnacl/__init__.py", line 829, in crypto_aead_chacha20poly1305_ietf_decrypt, 
ValueError: Failed to decrypt message,
```

I don't know the exact reason for the error, but I think it should not cause core crashes. So we probably should add try/except block in  `TriblerTunnelCommunity._ours_on_created_extended` to handle this situation.

**Comment by qstokkink** [comment]
`on_packet_from_circuit` already [has a general exception handler wrapping it](https://github.com/Tribler/py-ipv8/blob/7a94e31c1036b7d13491dc63a8e8d55ed34f0c7d/ipv8/messaging/anonymization/community.py#L645-L652). This is just a log message and not the core error.

In the Sentry issue you can see the log statement comes after the original crash:

```python
tribler_gui.utilities.CreationTraceback: ,
   File "run_tribler.py", line 213, in <module>,
   File "tribler_gui/utilities.py", line 395, in trackback_wrapper,
   File "tribler_gui/core_manager.py", line 97, in on_request_error,
   File "tribler_gui/core_manager.py", line 177, in start_tribler_core,
 The above exception was the direct cause of the following exception:,
 Traceback (most recent call last):,
   File "tribler_gui/utilities.py", line 398, in trackback_wrapper,
   File "tribler_gui/utilities.py", line 395, in trackback_wrapper,
   File "tribler_gui/core_manager.py", line 87, in on_core_finished,
 RuntimeError: The Tribler core has unexpectedly finished with exit code 11 and status: 1!,
 [PID:2487982] 2022-01-29 19:27:53,657 - ERROR <community:651> TriblerTunnelCommunity.on_packet_from_circuit(): Exception occurred while handling packet!, 
```

**Comment by kozlovsky** [comment]
@qstokkink, thanks for the explanation!

The order of log lines may be an artifact of the ordering of signal handlers, as the `on_core_finished` handler just was called before the `on_core_read_ready` handler. The core cannot write new messages to the log after it crashes. So, the logged error should happen right before the core crash and be logged just a moment later. But you are correct that the error is probably not the reason for the crash, just coincidence.
