### ISSUE TITLE
Weird bug 

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#6767]
Never had this issue until yesterday night. This bug is automatically closing Tribler & not letting it start. I have not changed any settings.
Windows 10 up-to-date. Tribler 7.11.0

______________________________________________________________________________________
tribler_gui.utilities.CreationTraceback: 
  File "run_tribler.py", line 128, in <module>
  File "tribler_gui\utilities.py", line 372, in trackback_wrapper
  File "tribler_gui\event_request_manager.py", line 140, in connect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tribler_gui\utilities.py", line 375, in trackback_wrapper
  File "tribler_gui\utilities.py", line 372, in trackback_wrapper
  File "tribler_gui\event_request_manager.py", line 140, in <lambda>
  File "tribler_gui\event_request_manager.py", line 84, in on_error
tribler_gui.exceptions.CoreConnectTimeoutError: Could not connect with the Tribler Core within 60 seconds
ERROR:CoreExceptionHandler:Unhandled exception occurred! [Errno 10048] error while attempting to bind on address ('::1', 61441, 0, 0): only one usage of each socket address (protocol/network address/port) is normally permitted
Traceback (most recent call last):
  File "tribler_core\components\base.py", line 174, in start
  File "tribler_core\components\restapi\restapi_component.py", line 93, in run
  File "tribler_core\components\restapi\rest\rest_manager.py", line 138, in start
  File "aiohttp\web_runner.py", line 121, in start
  File "asyncio\base_events.py", line 1463, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('::1', 61441, 0, 0): only one usage of each socket address (protocol/network address/port) is normally permitted

--LONG TEXT--

--CONTEXT--

**Comment by drew2a** [comment]
@absolutep it seems that the core process is stuck somewhy. 
Could you please attach logs (then we could analyze what happened)?

**Comment by absolutep** [comment]
I think it was related to port number. I have another torrent client and I set the port number of both torrent client as same.
However, once I changed the port number issue vanished. 

This is just my anecdotal answer as the issue was resolved after I did aforementioned.

Therefore, closing it for now. 

Tribler team can continue to discuss it though as & when they feel right.
