### ISSUE TITLE
PyIpv8 submodule is missing in main

### ISSUE THREAD

**Issue by 2ico** [Tribler/tribler#6793]
PyIpv8 submodule is missing in main. The same command works in v7.11.

```
src (main)> ./tribler.sh
INFO:__main__:Sentry has been initialised in normal mode
INFO:__main__:Run Tribler: Namespace(torrent='', core=False, gui_test_mode=False)
INFO:__main__:Root state dir: /home/george/.Tribler
Traceback (most recent call last):
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/run_tribler.py", line 83, in <module>
    from tribler_gui.start_gui import run_gui
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/tribler-gui/tribler_gui/start_gui.py", line 21, in <module>
    from tribler_gui.tribler_window import TriblerWindow
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/tribler-gui/tribler_gui/tribler_window.py", line 55, in <module>
    from tribler_gui.core_manager import CoreManager
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/tribler-gui/tribler_gui/core_manager.py", line 8, in <module>
    from tribler_gui.event_request_manager import EventRequestManager
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/tribler-gui/tribler_gui/event_request_manager.py", line 8, in <module>
    from tribler_core import notifications
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/tribler-core/tribler_core/notifications.py", line 3, in <module>
    from ipv8.messaging.anonymization.tunnel import Circuit
ModuleNotFoundError: No module named 'ipv8'
```

OS: Manjaro (Arch Linux)

**Comment by drew2a** [comment]
Hi, @2ico, thank you for reporting this behavior. 
Now you have to install `ipv8` as a pip dependency.

To do so, you have to run the following commands (could be different in your OS)

```bash
cd src
python3 -m pip install -r requirements.txt
```

We have switched ipv8 from submodule to external dependency in https://github.com/Tribler/tribler/pull/6757

**Comment by 2ico** [comment]
Ok I don't know why it didn't work, I can see it in https://github.com/Tribler/tribler/blob/9ec9fd8aae2b6e10aa472757e8c5b819f5f3d439/src/tribler-core/tribler_core/requirements.txt
