### ISSUE TITLE
[7.11] Unhandled exception in HiddenTunnelCommunity.create_created_e2e()

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6810]
Tribler core crashes with an error:
```python
Traceback (most recent call last):, 
  File "ipv8\taskmanager.py", line 131, in done_cb, 
  File "ipv8\messaging\anonymization\hidden_services.py", line 366, in on_create_e2e, 
  File "ipv8\messaging\anonymization\hidden_services.py", line 378, in create_created_e2e, 
KeyError: 1030643827
```

[Here](https://github.com/Tribler/py-ipv8/blob/2d4034e51bf6a2067c5d461848d44e950364fbf0/ipv8/messaging/anonymization/hidden_services.py#L378):
```python
    def create_created_e2e(self, rp, source_address, payload, circuit_id):
        ...
        circuit = self.circuits[circuit_id]  # <-- KeyError
        self.tunnel_data(circuit, source_address, CreatedE2EPayload(payload.identifier, Y, AUTH, rp_info_enc))
```

It seems the IPv8 code should handle the case of missing `curcuit_id`.

**Comment by qstokkink** [comment]
Seeing as this is the fourth time (apparently) that log output is posted as a bug, may I suggest prefixing log lines with some special character? Something like this would do:

```python
import logging

logging.basicConfig(format="[PID:%(process)d] %(asctime)s - %(levelname)s <%(module)s:%(lineno)d> %(name)s.%(funcName)s(): %(message)s")
old_factory = logging.getLogRecordFactory()


def print_error():
    logging.error("""Something went wrong!
Traceback (most recent call last):, 
  File "ipv8\taskmanager.py", line 131, in done_cb, 
  File "ipv8\messaging\anonymization\hidden_services.py", line 366, in on_create_e2e, 
  File "ipv8\messaging\anonymization\hidden_services.py", line 378, in create_created_e2e, 
KeyError: 1030643827""")


def record_factory(*args, **kwargs):
    new_args = args[:4] + (args[4].replace("\n", "\n> "),) + args[5:]
    record_class = old_factory(*new_args, **kwargs)
    return record_class


logging.error("Without identation sybols, looks like uncaught exception:")
print_error()

logging.error("With identation sybols:")
logging.setLogRecordFactory(record_factory)
print_error()
```

Example output:

```
[PID:17428] 2022-03-23 14:49:14,288 - ERROR <loggingstuff:22> root.<module>(): Without identation sybols, looks like uncaught exception:
[PID:17428] 2022-03-23 14:49:14,288 - ERROR <loggingstuff:8> root.print_error(): Something went wrong!
Traceback (most recent call last):,
  File "ipv8    askmanager.py", line 131, in done_cb,
  File "ipv8\messagingnonymization\hidden_services.py", line 366, in on_create_e2e,
  File "ipv8\messagingnonymization\hidden_services.py", line 378, in create_created_e2e,
KeyError: 1030643827
[PID:17428] 2022-03-23 14:49:14,288 - ERROR <loggingstuff:25> root.<module>(): With identation sybols:
[PID:17428] 2022-03-23 14:49:14,288 - ERROR <loggingstuff:8> root.print_error(): Something went wrong!
> Traceback (most recent call last):,
>   File "ipv8  askmanager.py", line 131, in done_cb,
>   File "ipv8\messagingnonymization\hidden_services.py", line 366, in on_create_e2e,
>   File "ipv8\messagingnonymization\hidden_services.py", line 378, in create_created_e2e,
> KeyError: 1030643827
```
