### ISSUE TITLE
Issue with progressbar paint on downloads page

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#6908]
When selecting multiple downloads at the same time while the progressbar is being loaded, Tribler on Linux (release/7.12) shows an error popup with the following stack trace.

```python
[PID:181488] 2022-05-18 12:35:29,554 - ERROR <error_handler:32> ErrorHandler.gui_error(): Traceback (most recent call last):
  File "/home/sysadmin/tudelft/dev/tribler/src/tribler/gui/widgets/downloadprogressbar.py", line 85, in paintEvent
    painter.fillRect(QRect(0, 0, self.width() * self.fraction, self.height()), QColor(230, 115, 0))
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 3 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'int'
  QRect(QPoint, QSize): argument 1 has unexpected type 'int'
  QRect(QRect): argument 1 has unexpected type 'int'

QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
[PID:181488] 2022-05-18 12:35:29,558 - ERROR <error_handler:32> ErrorHandler.gui_error(): Traceback (most recent call last):
  File "/home/sysadmin/tudelft/dev/tribler/src/tribler/gui/widgets/downloadprogressbar.py", line 85, in paintEvent
    painter.fillRect(QRect(0, 0, self.width() * self.fraction, self.height()), QColor(230, 115, 0))
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 3 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'int'
  QRect(QPoint, QSize): argument 1 has unexpected type 'int'
  QRect(QRect): argument 1 has unexpected type 'int'

QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
```

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/6910
