### ISSUE TITLE
Error when removing entries from the FeedbackDialog

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6961]
In case of exception, in the FeedbackDialog, there is a list of key/value pairs that describe the user environment. It is possible to right-click on the line and select the "Remove Item" command from the drop-down menu. But, instead of deleting the line, Tribler shows another error:

```python
[PID:9728] 2022-07-04 16:22:35,198 - INFO - SentryReporter(283) - Event from exception: Tribler GUI Test Exception
[PID:9728] 2022-07-04 16:22:38,731 - INFO - SentryReporter(283) - Event from exception: on_remove_entry() takes 1 positional argument but 2 were given
[PID:9728] 2022-07-04 16:22:38,731 - ERROR <error_handler:32> ErrorHandler.gui_error(): tribler.gui.utilities.CreationTraceback: 
  File "C:\dev\tribler\src\run_tribler.py", line 97, in <module>
    run_gui(api_port, api_key, root_state_dir, parsed_args)
  File "C:\dev\tribler\src\tribler\gui\start_gui.py", line 77, in run_gui
    sys.exit(app.exec_())
  File "C:\dev\tribler\src\tribler\gui\utilities.py", line 410, in trackback_wrapper
    callback(*args, **kwargs)
  File "C:\dev\tribler\src\tribler\gui\dialogs\feedbackdialog.py", line 138, in on_right_click_item
    connect(remove_action.triggered, self.on_remove_entry)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\dev\tribler\src\tribler\gui\utilities.py", line 413, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "C:\dev\tribler\src\tribler\gui\utilities.py", line 410, in trackback_wrapper
    callback(*args, **kwargs)
TypeError: on_remove_entry() takes 1 positional argument but 2 were given
```

**Comment by kozlovsky** [comment]
Fixed in #6962
