### ISSUE TITLE
[7.11] TypeError: setPixelSize(self, int): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6967]
The bug was already fixed in #6620; I'm adding the issue to be able to refer to it from Sentry.

```python
Traceback (most recent call last):, 
  File "/nix/store/gg1rf9p161zjjiy791r7fqzbgfkjxr1g-tribler-7.11.0/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py", line 248, in paint, 
    if not self.paint_exact(painter, option, index):, 
  File "/nix/store/gg1rf9p161zjjiy791r7fqzbgfkjxr1g-tribler-7.11.0/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py", line 256, in paint_exact, 
    return drawing_action(painter, option, index, data_item), 
  File "/nix/store/gg1rf9p161zjjiy791r7fqzbgfkjxr1g-tribler-7.11.0/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py", line 338, in draw_subscribed_control, 
    self.subscribe_control.paint(, 
  File "/nix/store/gg1rf9p161zjjiy791r7fqzbgfkjxr1g-tribler-7.11.0/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py", line 675, in paint, 
    font.setPixelSize(1.5 * self._thumb_radius), 
TypeError: setPixelSize(self, int): argument 1 has unexpected type 'float'
```

The code: `tribler_gui/widgets/tablecontentdelegate.py` in `paint` at line 675:
```python
            2 * self._thumb_radius,
        )
        p.setPen(text_color)
        p.setOpacity(text_opacity)
        font = p.font()
        font.setPixelSize(1.5 * self._thumb_radius)  # <-- here
        p.setFont(font)
        p.drawText(
            QRectF(
                x + offset - self._thumb_radius,
                y + self._base_offset - self._thumb_radius,
```

**Comment by kozlovsky** [comment]
Fixed in #6620
