### ISSUE TITLE
Tribler crashes when pressing Ctrl+O shortcut

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6979]
When pressing a `Ctrl+O` shortcut that should open a file dialog to add a torrent, Tribler crashes with the following error:

```python
tribler_gui.utilities.CreationTraceback: , 
  File "/Users/<user>/dev/tribler/src/run_tribler.py", line 124, in <module>, 
    window = TriblerWindow(settings), 
  File "/Users/<user>/dev/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 202, in __init__, 
    connect(self.import_torrent_shortcut.activated, self.on_add_torrent_browse_file), 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "/Users/<user>/dev/tribler/src/tribler-gui/tribler_gui/utilities.py", line 375, in trackback_wrapper, 
    raise exc from CreationTraceback(traceback_str), 
  File "/Users/<user>/dev/tribler/src/tribler-gui/tribler_gui/utilities.py", line 372, in trackback_wrapper, 
    callback(*args, **kwargs), 
TypeError: on_add_torrent_browse_file() missing 1 required positional argument: 'index'
```

**Comment by kozlovsky** [comment]
Fixed in #6980
