### ISSUE TITLE
[7.12.1] RuntimeError: thread_info(THREAD_BASIC_INFO) syscall failed

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7068]
```python
tribler.gui.utilities.CreationTraceback: , 
  File "run_tribler.py", line 100, in <module>, 
  File "tribler/gui/start_gui.py", line 77, in run_gui, 
  File "tribler/gui/upgrade_manager.py", line 137, in on_worker_finished, 
  File "tribler/gui/utilities.py", line 411, in trackback_wrapper, 
  File "tribler/gui/core_manager.py", line 117, in start_tribler_core, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "tribler/gui/utilities.py", line 414, in trackback_wrapper, 
  File "tribler/gui/utilities.py", line 411, in trackback_wrapper, 
  File "tribler/gui/core_manager.py", line 241, in on_core_finished, 
tribler.gui.exceptions.CoreCrashedError: The Tribler core has unexpectedly finished with exit code 255 and status: 0., 
Error message: Unknown error: 255, 
Last Core output:, 
> Traceback (most recent call last):, 
>   File "run_tribler.py", line 94, in <module>, 
>   File "tribler/core/start_core.py", line 182, in run_core, 
>   File "contextlib.py", line 113, in __enter__, 
>   File "tribler/core/utilities/process_checker.py", line 22, in single_tribler_instance, 
>   File "tribler/core/utilities/process_checker.py", line 52, in check_and_restart_if_necessary, 
>   File "tribler/core/utilities/process_checker.py", line 103, in _is_old_tribler_process_running, 
>   File "psutil/__init__.py", line 525, in as_dict, 
>   File "psutil/__init__.py", line 870, in threads, 
>   File "psutil/_psosx.py", line 344, in wrapper, 
>   File "psutil/_psosx.py", line 572, in threads, 
> RuntimeError: thread_info(THREAD_BASIC_INFO) syscall failed, 
> [66039] Failed to execute script run_triblerSentry is attempting to send 1 pending error messages, 
> Waiting up to 2 seconds, 
> Press Ctrl-C to quit
```

**Comment by drew2a** [comment]
Could be fixed in https://github.com/Tribler/tribler/pull/7212.
Close for now.
