### ISSUE TITLE
Error in gen_key (current devel)

### ISSUE THREAD

**Issue by vvs-** [Tribler/tribler#719]
```
ERROR   1406670163.41   sqlitecachedb:371   No existing database found. Attempting to create a new database u'/home/vvs/.Tribler/sqlite/tribler.sdb'
ERROR   1406670165.06           utils:130   libvlc_get_version couldn't be called, no playback possible
ERROR   1406670167.03           utils:130   libvlc_get_version couldn't be called, no playback possible
GUI started
Exception ValueError: 'Received a NULL pointer.' in <bound method EC.__del__ of <M2Crypto.EC.EC instance at 0xb3183cc>> ignored
ERROR   1406670167.20            util:270   Exception raised on the reactor's thread.
 Traceback from this thread:
  File "/usr/lib/python2.7/threading.py", line 784, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/home/vvs/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 753, in run
    self.init()
  File "/home/vvs/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 174, in init
    success = self.dispersy.start()
  File "/home/vvs/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/vvs/tribler/Tribler/dispersy/util.py", line 267, in blockingCallFromThread
    this_thread_tb = traceback.extract_stack()

 Traceback from the reactor's thread:
   File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 134, in maybeDeferred
    result = f(*args, **kw)
  File "/home/vvs/tribler/Tribler/dispersy/dispersy.py", line 2134, in start
    self._discovery_community = self.define_auto_load(DiscoveryCommunity, self.get_new_member(), load=True)[0]
  File "/home/vvs/tribler/Tribler/dispersy/dispersy.py", line 529, in get_new_member
    key = self.crypto.generate_key(securitylevel)
  File "/home/vvs/tribler/Tribler/dispersy/util.py", line 184, in wrapper
    return_value = func(*args, **kargs)
  File "/home/vvs/tribler/Tribler/dispersy/crypto.py", line 123, in generate_key
    ec.gen_key()
  File "/home/vvs/.local/lib/python2.7/site-packages/M2Crypto/EC.py", line 126, in gen_key
    m2.ec_key_gen_key(self.ec)

Exception in thread NetworkThread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/home/vvs/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 753, in run
    self.init()
  File "/home/vvs/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 174, in init
    success = self.dispersy.start()
  File "/home/vvs/tribler/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/vvs/tribler/Tribler/dispersy/util.py", line 271, in blockingCallFromThread
    result.raiseException()
  File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 370, in raiseException
    raise self.type, self.value, self.tb
ValueError: Received a NULL pointer.

GUI ready
ERROR   1406670172.20           utils:130   libvlc_get_version couldn't be called, no playback possible
```

Tribler just stays dormant, no network connections, no dispersy packets. This happens on devel branch. Tribler 6.2.0 works just fine.

**Comment by Lcstyle** [comment]
also receiving the same issue:

./tribler.sh 
Traceback (most recent call last):
  File "/home/lcstyle/Download/tribler-6.4.1/tribler/Tribler/Main/tribler_main.py", line 1114, in run
    abc = ABCApp(params, installdir, is_unit_testing)
  File "/home/lcstyle/Download/tribler-6.4.1/tribler/Tribler/Main/tribler_main.py", line 175, in __init__
    session = self.InitStage1(installdir)
  File "/home/lcstyle/Download/tribler-6.4.1/tribler/Tribler/Main/tribler_main.py", line 418, in InitStage1
    session = Session(self.sconfig)
  File "/home/lcstyle/Download/tribler-6.4.1/tribler/Tribler/Core/Session.py", line 122, in __init__
    self.keypair = permidmod.generate_keypair()
  File "/home/lcstyle/Download/tribler-6.4.1/tribler/Tribler/Core/permid.py", line 21, in generate_keypair
    ec_keypair = EC.gen_params(KEYPAIR_ECC_CURVE)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 269, in gen_params
    return EC(m2.ec_key_new_by_curve_name(curve), 1)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 106, in __init__
    assert m2.ec_key_type_check(ec), "'ec' type error"
ValueError: Received a NULL pointer.

**Comment by whirm** [comment]
@Lcstyle is that with current ```devel```?
