### ISSUE TITLE
Tribler having problems with QT on Wayland

### ISSUE THREAD

**Issue by nadimahmedwales** [Tribler/tribler#7206]
For some reason, tribler suddenly stopped working. When I was pressing the icon, it wouldn't start up. So I downloaded the source code and went into tribler's src directory

```
./tribler.sh 

INFO:__main__:Run Tribler: Namespace(torrent='', core=False, gui_test_mode=False, allow_code_injection=False, trace_exception=False, trace_debug=False, testnet=False, chant_testnet=False, trustchain_testnet=False, tunnel_testnet=False)
INFO:__main__:Root state dir: /home/myuser/.Tribler
INFO:__main__:Sentry has been initialised in normal mode
INFO:tribler.gui.start_gui:
INFO:tribler.gui.start_gui:Enabling a workaround for Ubuntu 21.04+ wayland environment
INFO:tribler.core.logger.logger:Load logger config: app_mode=tribler-gui, config_path=/home/myuser/software/tribler/src/tribler/core/logger/logger.yaml, dir=/home/myuser/.Tribler
[PID:10614] 2022-11-29 10:52:08,260 - INFO - tribler.core.logger.logger(63) - Config loaded for app_mode=tribler-gui
[PID:10614] 2022-11-29 10:52:08,260 - INFO - tribler.core.check_os(109) - Check and enable code tracing. Process name: "gui". Log dir: "/home/myuser/.Tribler"
[PID:10614] 2022-11-29 10:52:08,260 - INFO - tribler.core.check_os(91) - Enable fault handler: "/home/myuser/.Tribler"
[PID:10614] 2022-11-29 10:52:08,261 - INFO - tribler.core.check_os(44) - Check environment
[PID:10614] 2022-11-29 10:52:08,261 - INFO - tribler.core.check_os(49) - Check free space
[PID:10614] 2022-11-29 10:52:08,261 - INFO - TriblerApplication(25) - Start Tribler application. Win id: "triblerapp". Sys argv: "['/home/myuser/software/tribler/src/run_tribler.py']"
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
[PID:10614] 2022-11-29 10:52:08,342 - INFO - TriblerApplication(52) - No running instances (socket error: 2)
[PID:10614] 2022-11-29 10:52:08,395 - INFO - tribler.gui.utilities(472) - Available Tribler translations {'Russian': 'ru_RU', 'Chinese': 'zh_CN', 'Portuguese': 'pt_BR', 'English': 'en_US'}
[PID:10614] 2022-11-29 10:52:08,395 - INFO - tribler.gui.utilities(473) - System language: ['en-GB', 'en'], Tribler language: ['en-GB', 'en-Latn-GB']
[PID:10614] 2022-11-29 10:52:08,396 - INFO - tribler.gui.start_gui(72) - Start Tribler Window
[PID:10614] 2022-11-29 10:52:08,397 - INFO - NetworkUtils(46) - Looking for first free port in range [20100..65535]
[PID:10614] 2022-11-29 10:52:08,398 - INFO - NetworkUtils(50) - 20100 is free
[PID:10614] 2022-11-29 10:52:08,401 - INFO - Tribler Config(86) - Init. State dir: /home/myuser/.Tribler. File: /home/myuser/.Tribler/triblerd.conf
[PID:10614] 2022-11-29 10:52:08,402 - INFO - VersionHistory(288) - Files to copy: ['ec_multichain.pem', 'ecpub_multichain.pem', 'secondary_key.pem', 'ec_trustchain_testnet.pem', 'triblerd.conf', 'lt.state']
[PID:10614] 2022-11-29 10:52:08,402 - INFO - VersionHistory(232) - No previous version found, current Tribler version is 7.12.1-GIT
[PID:10614] 2022-11-29 10:52:08,907 - INFO - ErrorHandler(31) - Processing GUI error: <class 'ValueError'>
[PID:10614] 2022-11-29 10:52:08,907 - ERROR <error_handler:34> ErrorHandler.gui_error(): Traceback (most recent call last):
  File "/home/myuser/software/tribler/src/run_tribler.py", line 100, in <module>
    run_gui(api_port, api_key, root_state_dir, parsed_args)
  File "/home/myuser/software/tribler/src/tribler/gui/start_gui.py", line 73, in run_gui
    window = TriblerWindow(app_manager, settings, root_state_dir, api_port=api_port, api_key=api_key)
  File "/home/myuser/software/tribler/src/tribler/gui/tribler_window.py", line 285, in __init__
    self.trust_graph_page.initialize_trust_graph()
  File "/home/myuser/software/tribler/src/tribler/gui/widgets/trustgraphpage.py", line 105, in initialize_trust_graph
    graph_layout = pg.GraphicsLayoutWidget()
  File "/home/myuser/.local/lib/python3.10/site-packages/pyqtgraph/widgets/GraphicsLayoutWidget.py", line 51, in __init__
    GraphicsView.__init__(self, parent)
  File "/home/myuser/.local/lib/python3.10/site-packages/pyqtgraph/widgets/GraphicsView.py", line 80, in __init__
    self.setBackground(background)
  File "/home/myuser/.local/lib/python3.10/site-packages/pyqtgraph/widgets/GraphicsView.py", line 132, in setBackground
    brush = fn.mkBrush(background)
  File "/home/myuser/.local/lib/python3.10/site-packages/pyqtgraph/functions.py", line 343, in mkBrush
    return QtGui.QBrush(mkColor(color))
  File "/home/myuser/.local/lib/python3.10/site-packages/pyqtgraph/functions.py", line 272, in mkColor
    raise ValueError(f"Unable to convert {c} to QColor")
ValueError: Unable to convert 222222 to QColor
```

==========================================================================

I then decided to try a flatpak version and got the following
```
flatpak run org.tribler.Tribler

INFO:__main__:Run Tribler: Namespace(allow_code_injection=False, chant_testnet=False, core=False, gui_test_mode=False, testnet=False, torrent='', trace_debug=False, trace_exception=False, trustchain_testnet=False, tunnel_testnet=False)
INFO:__main__:Root state dir: /home/myuser/.Tribler
INFO:__main__:Sentry has been initialised in normal mode
INFO:tribler.gui.start_gui:
INFO:tribler.gui.start_gui:Enabling a workaround for Ubuntu 21.04+ wayland environment
INFO:tribler.core.logger.logger:Load logger config: app_mode=tribler-gui, config_path=/app/share/tribler/tribler_source/tribler/core/logger/logger.yaml, dir=/home/myuser/.Tribler
[PID:2] 2022-11-29 10:58:04,695 - INFO - tribler.core.logger.logger(64) - Config loaded for app_mode=tribler-gui
[PID:2] 2022-11-29 10:58:04,695 - INFO - tribler.core.check_os(109) - Check and enable code tracing. Process name: "gui". Log dir: "/home/myuser/.Tribler"
[PID:2] 2022-11-29 10:58:04,695 - INFO - tribler.core.check_os(91) - Enable fault handler: "/home/myuser/.Tribler"
[PID:2] 2022-11-29 10:58:04,696 - INFO - tribler.core.check_os(44) - Check environment
[PID:2] 2022-11-29 10:58:04,696 - INFO - tribler.core.check_os(49) - Check free space
[PID:2] 2022-11-29 10:58:04,696 - INFO - TriblerApplication(25) - Start Tribler application. Win id: "triblerapp". Sys argv: "['/app/share/tribler/tribler']"

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

```
Any ideas on what's going on? I have a feeling that something updated QT, but tribler doesn't like it and is unable to downgrade it.  I have the following set:

```
set | grep QT
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
QT_QPA_PLATFORM=wayland
XDG_SESSION_TYPE=wayland
```

**Comment by drew2a** [comment]
@nadimahmedwales thank you for informing us!

As far as I understand you tried to run Tribler from the source code of the latest main. 
Have you installed all the requirements from https://tribler.readthedocs.io/en/latest/development/development_on_linux.html?

**Comment by nadimahmedwales** [comment]
Thanks,
I have managed to get the source code working. I couldn't get the prebuilt versions working. At least I have a version working.
