### ISSUE TITLE
ValueError: "Unable to convert 222222 to QColor" in pyqtgraph/functions.py when starting Tribler

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7271]
After upgrading requirements I start getting this error when starting run_tribler.py:
```
Traceback (most recent call last):
  File "C:\dev\tribler\src\tribler\gui\start_gui.py", line 80, in run_gui
    window = TriblerWindow(process_manager, app_manager, settings, root_state_dir,
  File "C:\dev\tribler\src\tribler\gui\tribler_window.py", line 290, in __init__
    self.trust_graph_page.initialize_trust_graph()
  File "C:\dev\tribler\src\tribler\gui\widgets\trustgraphpage.py", line 105, in initialize_trust_graph
    graph_layout = pg.GraphicsLayoutWidget()
  File "C:\dev\tribler\venv\lib\site-packages\pyqtgraph\widgets\GraphicsLayoutWidget.py", line 51, in __init__
    GraphicsView.__init__(self, parent)
  File "C:\dev\tribler\venv\lib\site-packages\pyqtgraph\widgets\GraphicsView.py", line 80, in __init__
    self.setBackground(background)
  File "C:\dev\tribler\venv\lib\site-packages\pyqtgraph\widgets\GraphicsView.py", line 132, in setBackground
    brush = fn.mkBrush(background)
  File "C:\dev\tribler\venv\lib\site-packages\pyqtgraph\functions.py", line 343, in mkBrush
    return QtGui.QBrush(mkColor(color))
  File "C:\dev\tribler\venv\lib\site-packages\pyqtgraph\functions.py", line 272, in mkColor
    raise ValueError(f"Unable to convert {c} to QColor")
ValueError: Unable to convert 222222 to QColor
```

**Comment by drew2a** [comment]
@kozlovsky could you please downgrade `pyqtgraph` to `pyqtgraph==0.12.3` and check?
