### ISSUE TITLE
KeyError in register_request callback in SearchResultsWidget.search

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7333]
```
[
tribler.gui.utilities.CreationTraceback: , 
  File "run_tribler.py", line 103, in <module>, 
  File "tribler/gui/start_gui.py", line 84, in run_gui, 
  File "tribler/gui/utilities.py", line 413, in trackback_wrapper, 
  File "tribler/gui/tribler_window.py", line 1083, in on_top_search_bar_return_pressed, 
  File "tribler/gui/widgets/searchresultswidget.py", line 120, in search, 
  File "tribler/gui/network/request_manager.py", line 80, in put, 
  File "tribler/gui/network/request.py", line 64, in __init__, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "tribler/gui/utilities.py", line 416, in trackback_wrapper, 
  File "tribler/gui/utilities.py", line 413, in trackback_wrapper, 
  File "tribler/gui/widgets/searchresultswidget.py", line 114, in register_request, 
KeyError: 'peers'
]
```
[Here](https://github.com/Tribler/tribler/blob/f5d6aeb2e4befc55c1385ce6596393b95aa4d7c1/src/tribler/gui/widgets/searchresultswidget.py#L114):
```python
# searchresultswidget.py
class SearchResultsWidget(AddBreadcrumbOnShowMixin, widget_form, widget_class):
    ...
    def search(self, query: Query) -> bool:
        ...
        def register_request(response):
            peers = set(response["peers"])  # <-- here
            self.search_request = SearchRequest(response["request_uuid"], query, peers)
            self.search_progress_bar.set_remote_total(len(peers))

        params = {'txt_filter': fts_query, 'hide_xxx': self.hide_xxx, 'tags': list(query.tags),
                  'metadata_type': REGULAR_TORRENT, 'exclude_deleted': True}
        request_manager.put('remote_query', register_request, url_params=params)

        return True
```

The reason for the error is we got an empty dict in the callback. The empty dict is created [here](https://github.com/Tribler/tribler/blob/93927779051ddfe2412731067b5e3d4c14ad162d/src/tribler/gui/network/request.py#L107):

```python
class Request(QObject):
    ...
    def on_finished(self):
        ...
        try:
            ...
            data = bytes(self.reply.readAll())
            ...

            if not data:
                self.on_finished_signal.emit({})  # <-- here
                return
```

The code for returning an empty dict is added in #7298 to fix #7297. Apparently, when no data is returned in the reply, it is better not to call the callback at all, as the callback usually expects some keys in the resulting dict.

Also, it looks like the `on_finish` callback is better to rename to `on_success`, as these callback functions are expected to be called only on successful responses with correct results.

The actual reason why it is possible to receive an empty response from the reply is still unknown, I'll describe it in a separate issue #7335, so it will be possible to discuss it later.

**Comment by kozlovsky** [comment]
Fixed in #7334
