### ISSUE TITLE
[7.13] UpgradeError: No space left on device

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7368]
User comment: "updating the database at first launch of 7.13-RC1. Might have run out of disk space while processing."
```
Traceback (most recent call last):, 
  File "tribler/gui/upgrade_manager.py", line 45, in run, 
  File "tribler/gui/upgrade_manager.py", line 62, in upgrade_state_dir, 
  File "tribler/core/upgrade/version_manager.py", line 345, in fork_state_directory_if_necessary, 
  File "tribler/core/upgrade/version_manager.py", line 170, in copy_state_from, 
  File "shutil.py", line 554, in copytree, 
  File "shutil.py", line 510, in _copytree, 
shutil.Error: [Errno 28] No space left on device: 
```

Ideally, Tribler should estimate the necessary space before upgrading and not start the upgrade if the space is insufficient

**Comment by drew2a** [comment]
@xoriole does the #7496 fix the current issue?

**Comment by xoriole** [comment]
https://github.com/Tribler/tribler/pull/7496 addresses this, closing this issue.
