### ISSUE TITLE
[7.12.1] PackError ipv8.messaging.serialization in pack_serializable

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7430]
https://sentry.tribler.org/organizations/tribler/issues/2134/

```
Could not pack item: ('I', -2), 
error: argument out of range
```

```python
Traceback (most recent call last):, 
  File "ipv8\messaging\serialization.py", line 365, in pack_serializable, 
  File "ipv8\messaging\serialization.py", line 252, in pack, 
struct.error: argument out of range, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "asyncio\events.py", line 81, in _run, 
  File "ipv8\taskmanager.py", line 131, in done_cb, 
  File "ipv8\taskmanager.py", line 18, in interval_runner, 
  File "ipv8\util.py", line 35, in call_async, 
  File "tribler\core\components\popularity\community\popularity_community.py", line 116, in gossip_random_torrents_health, 
  File "tribler\core\components\popularity\community\popularity_community.py", line 110, in _gossip_torrents_health, 
  File "ipv8\lazy_community.py", line 199, in ez_send, 
  File "ipv8\lazy_community.py", line 215, in _ez_senda, 
  File "ipv8\lazy_community.py", line 231, in ezr_pack, 
  File "ipv8\lazy_community.py", line 234, in _ez_pack, 
  File "ipv8\messaging\serialization.py", line 379, in pack_serializable_list, 
  File "ipv8\messaging\serialization.py", line 379, in <genexpr>, 
  File "ipv8\messaging\serialization.py", line 363, in pack_serializable, 
  File ", 
def to_pack_list(self):, 
    return [("I", self.random_torrents_length), ("I", self.torrents_checked_length), ("varlenI", self.fix_pack_random_torrents(self.random_torrents)), ("raw", self.fix_pack_torrents_checked(self.torrents_checked))], 
        ", line 3, in to_pack_list, 
  File "tribler\core\components\popularity\community\payload.py", line 28, in fix_pack_random_torrents, 
  File "tribler\core\components\popularity\community\payload.py", line 28, in <genexpr>, 
  File "ipv8\messaging\serialization.py", line 367, in pack_serializable, 
ipv8.messaging.serialization.PackError: Could not pack item: ('I', -2), 
error: argument out of range
```

**Comment by qstokkink** [comment]
Looking at the Sentry event, this entry seems to have introduced the `-2`:

```
"event_23":[
   {
      "topic":"channel_entity_updated",
      "args":[
         {
            "infohash":"<hash>",
            "num_seeders":4,
            "num_leechers":-2,
            "last_tracker_check":1684539510,
            "health":"updated"
         }
      ],
      "kwargs":{
         
      }
   }" (time":1684539510.4257843)
]
```
