### ISSUE TITLE
OSError: [WinError 740] The requested operation requires elevation

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#7574]
Deployment tests on 64 bit windows failed with the following traceback
```python
Traceback (most recent call last):
  File "deployment_scripts\deploy_windows.py", line 47, in <module>
    completed_process = subprocess.run([INSTALLER_FILE, "/S"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\tribler-user\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\tribler-user\AppData\Roaming\Python\Python38\site-packages\sentry_sdk\integrations\stdlib.py", line 190, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)  # type: ignore
  File "C:\Users\tribler-user\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\tribler-user\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 740] The requested operation requires elevation
```

**Comment by kozlovsky** [comment]
The reason for this is Jenkins Agent, by default, starts without administrative privileges. When it tries to run the Tribler installation, it gets this error. Manual restarting the agent with admin privileges helps; it would be nice to start it this way automatically.
