### ISSUE TITLE
[7.13.0] ERROR:tribler.core.utilities.process_manager.manager:OperationalError: unable to open database file

### ISSUE THREAD

**Issue by grigio** [Tribler/tribler#7587]
**Describe the bug**
tribler do not start if state dir is missing

**To Reproduce**

```
git clone https://github.com/Tribler/tribler
git checkout v7.13.0
docker-compose build
docker-compose up
Creating triblercore ... done
Attaching to triblercore
triblercore     | INFO:__main__:Run Tribler: Namespace(allow_code_injection=False, chant_testnet=False, core=True, gui_test_mode=False, testnet=False, torrent='', trace_debug=False, trace_exception=False, trustchain_testnet=False, tunnel_testnet=False)
triblercore     | INFO:__main__:Root state dir: /home/user/.Tribler
triblercore     | INFO:__main__:Sentry has been initialised in normal mode
triblercore     | INFO:tribler.core.utilities.slow_coro_detection:Start tracing of coroutine stack to show stack for slow coroutines (makes code execution slower)
triblercore     | INFO:tribler.core.start_core:Running Core in normal mode
triblercore     | ERROR:tribler.core.utilities.process_manager.manager:OperationalError: unable to open database file
triblercore     | Traceback (most recent call last):
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/manager.py", line 62, in connect
triblercore     |     self.connection = connection = sqlite3.connect(str(self.db_filepath))
triblercore     | sqlite3.OperationalError: unable to open database file
triblercore     | WARNING:tribler.core.utilities.process_manager.manager:Retrying after the error: OperationalError: unable to open database file
triblercore     | ERROR:tribler.core.utilities.process_manager.manager:OperationalError: unable to open database file
triblercore     | Traceback (most recent call last):
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/utils.py", line 29, in new_method
triblercore     |     return method(self, *args, **kwargs)
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/process.py", line 150, in become_primary
triblercore     |     with self.manager.connect():
triblercore     |   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
triblercore     |     return next(self.gen)
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/manager.py", line 62, in connect
triblercore     |     self.connection = connection = sqlite3.connect(str(self.db_filepath))
triblercore     | sqlite3.OperationalError: unable to open database file
triblercore     | 
triblercore     | During handling of the above exception, another exception occurred:
triblercore     | 
triblercore     | Traceback (most recent call last):
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/manager.py", line 62, in connect
triblercore     |     self.connection = connection = sqlite3.connect(str(self.db_filepath))
triblercore     | sqlite3.OperationalError: unable to open database file
triblercore     | Traceback (most recent call last):
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/utils.py", line 29, in new_method
triblercore     |     return method(self, *args, **kwargs)
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/process.py", line 150, in become_primary
triblercore     |     with self.manager.connect():
triblercore     |   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
triblercore     |     return next(self.gen)
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/manager.py", line 62, in connect
triblercore     |     self.connection = connection = sqlite3.connect(str(self.db_filepath))
triblercore     | sqlite3.OperationalError: unable to open database file
triblercore     | 
triblercore     | During handling of the above exception, another exception occurred:
triblercore     | 
triblercore     | Traceback (most recent call last):
triblercore     |   File "/home/user/tribler/src/run_tribler.py", line 109, in <module>
triblercore     |     run_core(api_port, api_key, root_state_dir, parsed_args)
triblercore     |   File "/home/user/tribler/src/tribler/core/start_core.py", line 193, in run_core
triblercore     |     current_process_is_primary = process_manager.current_process.become_primary()
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/utils.py", line 32, in new_method
triblercore     |     return method(self, *args, **kwargs)
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/process.py", line 150, in become_primary
triblercore     |     with self.manager.connect():
triblercore     |   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
triblercore     |     return next(self.gen)
triblercore     |   File "/home/user/tribler/src/tribler/core/utilities/process_manager/manager.py", line 62, in connect
triblercore     |     self.connection = connection = sqlite3.connect(str(self.db_filepath))
triblercore     | sqlite3.OperationalError: unable to open database file
triblercore exited with code 1

```

**Comment by synctext** [comment]
@grigio thank you for this bug report!
This seems to be a Docket only issue. Very helpful to know the exact Traceback you are experiencing.
Related file {possibly/likely}: https://github.com/Tribler/docker-tribler-prod

**Comment by bortek** [comment]
Any updates on this or is there a workaround? I get this when starting docker compose container.

**Comment by drew2a** [comment]
@kozlovsky is it fixed now?

**Comment by kozlovsky** [comment]
@drew2a #7611 should now clarify the reason for the error, whether it is a permission error or something else.

Regarding the problem specified in the issue, I tried to run the docker image with docker-compose, and it works; when the `.Tribler` directory specified in the `docker-compose` volume mapping does not exist on the host machine, Docker creates it automatically.

The possible reason for the problem is that the `.Tribler` directory was manually created with insufficient permissions, so the user inside the container does not have enough rights to access it. To solve the problem, set correct permissions to the manually created `.Tribler` directory. If you do not care much about security, you can apply `chmod 777`.

So, it looks like the problem is in the incorrect configuration of the host machine and not in Tribler itself.
