### ISSUE TITLE
[7.13.0] TypeError: 'NoneType' object is not subscriptable in StartDownloadDialog.__init__()

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7641]
```python
tribler.gui.utilities.CreationTraceback:
  File "run_tribler.py", line 115, in <module>
  File "tribler\gui\start_gui.py", line 58, in run_gui
  File "tribler\gui\tribler_app.py", line 32, in __init__
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "tribler\gui\utilities.py", line 438, in trackback_wrapper
  File "tribler\gui\utilities.py", line 435, in trackback_wrapper
  File "tribler\gui\tribler_app.py", line 36, in on_app_message
  File "tribler\gui\tribler_app.py", line 40, in handle_uri
  File "tribler\gui\tribler_window.py", line 1256, in handle_uri
  File "tribler\gui\tribler_window.py", line 639, in process_uri_request
  File "tribler\gui\tribler_window.py", line 866, in start_download_from_uri
  File "tribler\gui\dialogs\startdownloaddialog.py", line 100, in __init__
TypeError: 'NoneType' object is not subscriptable
```

[Here](https://github.com/Tribler/tribler/blob/cf0669e40a672ef9e45734c9baa7a17b1ed7393c/src/tribler/gui/dialogs/startdownloaddialog.py#L100):
```python
        self.dialog_widget.anon_download_checkbox.setChecked(
            self.window().tribler_settings['download_defaults']['anonymity_enabled']
```

It looks like sometimes an option can be missed from the config.

**Comment by drew2a** [comment]
I can not reproduce the bug but I have a hypnotise of how it could happened.

Consider the following sequence:
1. Tribler starts the second instance of GUI and receives a URL from the first instance via the local socket (you can see it in logs)
2. GUI handles the URL:
https://github.com/Tribler/tribler/blob/5662d712dae1a6ec7c7f793336336bdea39ddc80/src/tribler/gui/tribler_window.py#L1253-L1256

But there is a chance that at this moment `self.tribler_settings` is still None as they have not been received yet. Therefore we see the `TypeError: 'NoneType' object is not subscriptable` as `self.tribler_settings` equals None.
