### ISSUE TITLE
Stuck on "SENDING..." when submitting a crash report

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#7697]
To reproduce: send a SIGKILL to the core process and click send on the error report.

```python
[tribler-gui PID:12144] 2023-11-17 11:57:04,752 - ERROR <error_handler:40> ErrorHandler.gui_error(): tribler.gui.utilities.CreationTraceback: 
  File "/tribler/src/run_tribler.py", line 115, in <module>
    run_gui(api_port, api_key, root_state_dir, parsed_args)
  File "/tribler/src/tribler/gui/start_gui.py", line 79, in run_gui
    exit_code = app.exec_()
  File "/tribler/src/tribler/gui/utilities.py", line 448, in trackback_wrapper
    callback(*args, **kwargs)
  File "/tribler/src/tribler/gui/core_manager.py", line 170, in check_core_api_port
    self.events_manager.connect_to_core(reschedule_on_err=True)
  File "/tribler/src/tribler/gui/event_request_manager.py", line 198, in connect_to_core
    self._connect_to_core(reschedule_on_err)
  File "/tribler/src/tribler/gui/event_request_manager.py", line 217, in _connect_to_core
    connect(self.reply.error, lambda error: self.on_error(error, reschedule_on_err=reschedule_on_err))


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tribler/src/tribler/gui/utilities.py", line 451, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/tribler/src/tribler/gui/utilities.py", line 448, in trackback_wrapper
    callback(*args, **kwargs)
  File "/tribler/src/tribler/gui/event_request_manager.py", line 217, in <lambda>
    connect(self.reply.error, lambda error: self.on_error(error, reschedule_on_err=reschedule_on_err))
  File "/tribler/src/tribler/gui/event_request_manager.py", line 137, in on_error
    raise CoreConnectionError('The connection to the Tribler Core was lost')
tribler.gui.exceptions.CoreConnectionError: The connection to the Tribler Core was lost

[tribler-gui PID:12144] 2023-11-17 11:57:19,852 - ERROR <error_handler:40> ErrorHandler.gui_error(): tribler.gui.utilities.CreationTraceback: 
  File "/tribler/src/run_tribler.py", line 115, in <module>
    run_gui(api_port, api_key, root_state_dir, parsed_args)
  File "/tribler/src/tribler/gui/start_gui.py", line 79, in run_gui
    exit_code = app.exec_()
  File "/tribler/src/tribler/gui/error_handler.py", line 80, in gui_error
    FeedbackDialog(
  File "/tribler/src/tribler/gui/dialogs/feedbackdialog.py", line 150, in __init__
    connect(self.send_report_button.clicked, self.on_send_clicked)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tribler/src/tribler/gui/utilities.py", line 451, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/tribler/src/tribler/gui/utilities.py", line 448, in trackback_wrapper
    callback(*args, **kwargs)
  File "/tribler/src/tribler/gui/dialogs/feedbackdialog.py", line 174, in on_send_clicked
    self.sentry_reporter.send_event(
  File "/tribler/src/tribler/core/sentry_reporter/sentry_reporter.py", line 197, in send_event
    if CONTEXTS not in event:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by qstokkink** [comment]
@drew2a I'm running Ubuntu 22.04.3.

**Comment by qstokkink** [comment]
Since I can reliably reproduce this, I printed all of the arguments being forwarded to Sentry here:

https://github.com/Tribler/tribler/blob/cd1af307902109a17425c281a6aa8ab871b5fcba/src/tribler/gui/dialogs/feedbackdialog.py#L174-L180

The result is (I stripped out part of `info` for brevity):

```
event= None
tags= {'source': 'gui', 'tribler_stopped': True, 'version': '7.13.0-GIT', 'machine': 'x86_64', 'os': 'Linux-5.15.0-88-generic-x86_64-with-glibc2.29', 'platform': 'linux'}
info= {'_error_text': 'tribler.gui.utilities.CreationTraceback: \n .. [[[BIG DICT OMITTED]]] .. '}
last_core_output= /home/quinten/.local/lib/python3.8/site-packages/apispec/core.py:625: UserWarning: Non-integer code not allowed in OpenAPI < 3
  warnings.warn("Non-integer code not allowed in OpenAPI < 3")
tribler_version= 7.13.0-GIT
```

The problem seems to be that `event` is `None`.
