### ISSUE TITLE
[main branch] AttributeError: 'TorrentDefNoMetainfo' object has no attribute 'torrent_info_loaded' (in get_files_info_json_paged)

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7732]
I got this bug on my machine:

```python
An error occurred during the request "GET http://localhost:59116/downloads/8bfbb8a87948e26bd83be120c4b7eac0a126b661/files?view_start_path=.&view_size=20":

Traceback (most recent call last):
  File "C:\dev\tribler\src\tribler\core\components\restapi\rest\rest_manager.py", line 53, in error_middleware
    response = await handler(request)
  File "C:\dev\tribler\venv39\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\dev\tribler\src\tribler\core\components\libtorrent\restapi\downloads_endpoint.py", line 658, in get_files
    "files": self.get_files_info_json_paged(download, Path(view_start_path), view_size)
  File "C:\dev\tribler\src\tribler\core\components\libtorrent\restapi\downloads_endpoint.py", line 173, in get_files_info_json_paged
    if not download.tdef.torrent_info_loaded():
AttributeError: 'TorrentDefNoMetainfo' object has no attribute 'torrent_info_loaded'
```

[Here](https://github.com/Tribler/tribler/blob/596e36cdede452bcf875148a9ab535c86397ce90/src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py#L173):
```python
    @staticmethod
    def get_files_info_json_paged(download: Download, view_start: Path, view_size: int):
        """
        ...
        """
        if not download.tdef.torrent_info_loaded():  # <-- here
            download.tdef.load_torrent_info()
            return [{
                "index": IllegalFileIndex.unloaded.value,
                "name": "loading...",
                "size": 0,
                "included": 0,
                "progress": 0.0
            }]
        ...
```

As I understand it, there are three ways to fix the problem:

1) **The most complete solution:** It looks like the `TorrentDefNoMetainfo` instance represents a temporary state of the `TorrentDef` object, so probably, at some moment, we can get rid of the `TorrentDefNoMetainfo` class completely and directly use `TorrentDef` class instance instead after we extend the logic of the `TorrentDef` class so it can handle the state when no meta info data is loaded yet. 

    This approach can simplify the logic in eight places where we currently have checks like:
    
    ```python
        if not isinstance(self.tdef, TorrentDefNoMetainfo):
            ...
    ```

    These checks will be unnecessary if the base torrent def object can handle all appropriate cases.

2) **The simplest solution:** We can just add yet another check `if isinstance(self.tdef, TorrentDefNoMetainfo)` to the `get_files_info_json_paged` endpoint

3) **The balanced solution:** We can add a simple method implementation to the `TorrentDefNoMetainfo` class:

    ```python
        def torrent_info_loaded(self):
            return False
    ```

**Comment by qstokkink** [comment]
Since `TorrentDef` can already handle `metainfo=None`, I consider `TorrentDefNoMetainfo` to be obsolete and I think now would be a good time to purge the latter (fix 1).

**Comment by kozlovsky** [comment]
Currently, `TorrentDefNoMetainfo` has `infohash`, `name`, and `url` fields, but `TorrentDef` does not have `name` and `url` fields. It looks like `TorrentDef` is able to keep `name` in `self.torrent_parameters[b'name']`, but should we add an additional field for `url`?

**Comment by qstokkink** [comment]
There is also a url list:

https://github.com/Tribler/tribler/blob/da5911d680fd538821cf01168f5125e10f8d8df3/src/tribler/core/components/libtorrent/torrentdef.py#L98
