### ISSUE TITLE
AttributeError: 'PreformattedTorrentFileTreeWidget' object has no attribute 'topLevelItemCount'

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7750]
I was integrating Application Tester to the PR checks (#7748) and discovered [the following error](https://github.com/Tribler/tribler/actions/runs/7086961518/job/19286225444?pr=7749#step:9:848) in the test PR (#7749).

```
tree_view = window.download_files_list
if tree_view.topLevelItemCount() == 0:
    exit_script()
item = tree_view.topLevelItem(randint(0, tree_view.topLevelItemCount() - 1))
check_state = Qt.Checked if item.checkState(CHECKBOX_COL) == Qt.Unchecked else Qt.Unchecked
item.setCheckState(CHECKBOX_COL, check_state)
QMetaObject.invokeMethod(tree_view, "itemClicked", Q_ARG(QTreeWidgetItem, item), Q_ARG(int, CHECKBOX_COL))
exit_script()

(end of code)
ERROR - Executor(353): Tribler that run by AppTester crashed after uptime of 65.0387670993805 sec! Stack trace:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<string>", line 29, in <module>
AttributeError: 'PreformattedTorrentFileTreeWidget' object has no attribute 'topLevelItemCount'
```

**Comment by qstokkink** [comment]
The file list is no longer a `QTreeWidget` but a `QTableWidget` under the hood. These calls should be replaced with their equivalent for a table.

**Comment by drew2a** [comment]
I've commented out "ChangeDownloadFilesAction" to make the ApplicationTester workable again.
