### ISSUE TITLE
pip3 error: externally-managed-environment

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#7811]
**Describe the bug**
pip3 error: externally-managed-environment

**To Reproduce**

1. Put Debian 12 in a VM
2. Try https://tribler.readthedocs.io/en/latest/development/development_on_linux.html#debian-ubuntu-mint
3. Report documentation bug

**Expected behavior**
Documentation should use one of the options listed in the pip3 error, or Not list Debian as an option.

**Desktop (please complete the following information):**

- OS: Debian 12
- Tribler's version: master

**Additional context**
```
pip3 install --upgrade -r tribler/requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by Dmole** [comment]
Maybe
```
apt install python3-full
mkdir tribler_env
python3 -m venv tribler_env 
./tribler_env/bin/pip3 install --upgrade -r tribler/requirements.txt
```

Only that errors with

```
ERROR: Could not find a version that satisfies the requirement libtorrent==1.2.19 (from versions: none)
ERROR: No matching distribution found for libtorrent==1.2.19
```

and so does the recommended 
https://pypi.org/project/libtorrent/
This works though:
https://pypi.org/project/lbry-libtorrent/
```
lbry-libtorrent==1.2.4
```
But then
```
Building wheels for collected packages: PyQt5-sip
  Building wheel for PyQt5-sip (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for PyQt5-sip (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'PyQt5.sip' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/tim/Downloads/tribler_env/include -I/usr/include/python3.11 -c apiversions.c -o build/temp.linux-x86_64-cpython-311/apiversions.o
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/tim/Downloads/tribler_env/include -I/usr/include/python3.11 -c array.c -o build/temp.linux-x86_64-cpython-311/array.o
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/tim/Downloads/tribler_env/include -I/usr/include/python3.11 -c descriptors.c -o build/temp.linux-x86_64-cpython-311/descriptors.o
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/tim/Downloads/tribler_env/include -I/usr/include/python3.11 -c int_convertors.c -o build/temp.linux-x86_64-cpython-311/int_convertors.o
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/tim/Downloads/tribler_env/include -I/usr/include/python3.11 -c objmap.c -o build/temp.linux-x86_64-cpython-311/objmap.o
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/tim/Downloads/tribler_env/include -I/usr/include/python3.11 -c qtlib.c -o build/temp.linux-x86_64-cpython-311/qtlib.o
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/tim/Downloads/tribler_env/include -I/usr/include/python3.11 -c siplib.c -o build/temp.linux-x86_64-cpython-311/siplib.o
      siplib.c: In function ‘sip_api_get_frame’:
      siplib.c:12751:22: error: invalid use of undefined type ‘struct _frame’
      12751 |         frame = frame->f_back;
            |                      ^~
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyQt5-sip
Failed to build PyQt5-sip
ERROR: Could not build wheels for PyQt5-sip, which is required to install pyproject.toml-based projects
```
Any I don't even want the GUI part so I'll leave the QT fix for others.

**Comment by Dmole** [comment]
Predictably the libtorrent swap needs more work:

```
bash tribler/src/tribler_headless.sh
Traceback (most recent call last):
  File "/home/me/Downloads/tribler/src/run_tribler_headless.py", line 18, in <module>
    from tribler.core.components.session import Session
  File "/home/me/Downloads/tribler/src/tribler/core/components/session.py", line 14, in <module>
    from tribler.core.config.tribler_config import TriblerConfig
  File "/home/me/Downloads/tribler/src/tribler/core/config/tribler_config.py", line 19, in <module>
    from tribler.core.components.libtorrent.settings import DownloadDefaultsSettings, LibtorrentSettings
  File "/home/me/Downloads/tribler/src/tribler/core/components/libtorrent/settings.py", line 10, in <module>
    from tribler.core.utilities.utilities import INT32_MAX
  File "/home/me/Downloads/tribler/src/tribler/core/utilities/utilities.py", line 22, in <module>
    from tribler.core.components.libtorrent.utils.libtorrent_helper import libtorrent as lt
  File "/home/me/Downloads/tribler/src/tribler/core/components/libtorrent/utils/libtorrent_helper.py", line 21, in <module>
    import libtorrent
SystemError: initialization of libtorrent raised unreported exception
```
maybe getting it from github would work... 
https://github.com/arvidn/libtorrent/releases/download/v2.0.9/libtorrent-rasterbar-2.0.9.tar.gz

**Comment by Dmole** [comment]
After adding async_timeout to requirements-core.txt that worked.

**Comment by Dmole** [comment]
https://github.com/Tribler/tribler/pull/7813

**Comment by qstokkink** [comment]
This should be resolved by the most-recent Tribler GUI rework.
