### ISSUE TITLE
Application Tester: 'NoneType' object has no attribute 'checkState'

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7822]
https://github.com/Tribler/tribler/actions/runs/7528230542/job/20490007957?pr=7816#step:9:1091

```python
ERROR - Executor(327): Tribler that run by AppTester crashed after uptime of 101.4193651676178 sec! Stack trace:
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<string>", line 41, in <module>
AttributeError: 'NoneType' object has no attribute 'checkState'
```

- Occurred in #7816

cc: @xoriole

**Comment by drew2a** [comment]
Occurred again: https://github.com/Tribler/tribler/actions/runs/7557114456/job/20575624862?pr=7833#step:10:898
In:
- #7833
