### ISSUE TITLE
channeltorrent_id type is None

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#786]
```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/data/feina/code/delft/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/community.py", line 2036, in _process_message_batch
    return self._on_batch_cache(meta, batch)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/community.py", line 2079, in _on_batch_cache
    self.on_messages(messages)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/community.py", line 2191, in on_messages
    if self._dispersy.store_update_forward(possibly_messages, True, True, False):
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/dispersy.py", line 1694, in store_update_forward
    if self._update(possibly_messages) == False:
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/util.py", line 183, in wrapper
    return_value = func(*args, **kargs)
  File "/var/data/feina/code/delft/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/var/data/feina/code/delft/tribler/Tribler/community/channel/community.py", line 687, in _disp_on_modification
    latest = self._get_latest_modification_from_torrent_id(channeltorrent_id, modification_type_id)
  File "/var/data/feina/code/delft/tribler/Tribler/community/channel/community.py", line 1040, in _get_latest_modification_from_torrent_id
    assert isinstance(channeltorrent_id, (int, long)), "channeltorrent_id type is '%s'" % type(channeltorrent_id)
exceptions.AssertionError: channeltorrent_id type is '<type 'NoneType'>'
```

**Comment by whirm** [comment]
I don't know how to reproduce this and haven't seen this in two months. Closing.
