### ISSUE TITLE
Illegal IP address string in TunnelCommunity

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#787]
Got the following error when dest_address[0] is a hostname instead of an IP:

```
ERROR   1408700660.57             log:443   Unhandled Error
Traceback (most recent call last):
  File "C:\Python272\Lib\site-packages\twisted-13.2.0-py2.7-win32.egg\twisted\python\log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python272\Lib\site-packages\twisted-13.2.0-py2.7-win32.egg\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python272\Lib\site-packages\twisted-13.2.0-py2.7-win32.egg\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "C:\Python272\Lib\site-packages\twisted-13.2.0-py2.7-win32.egg\twisted\internet\selectreactor.py", line 151, in _doReadOrWrite
    why = getattr(selectable, method)()
--- <exception caught here> ---
  File "C:\Python272\Lib\site-packages\twisted-13.2.0-py2.7-win32.egg\twisted\internet\udp.py", line 234, in doRead
    self.protocol.datagramReceived(data, addr)
  File "C:\Users\Egbert\git\tribler\Tribler\community\tunnel\Socks5\server.py", line 61, in datagramReceived
    circuit.tunnel_data(request.destination, request.payload)
  File "C:\Users\Egbert\git\tribler\Tribler\community\tunnel\routing.py", line 86, in tunnel_data
    return self.proxy.tunnel_data_to_end(destination, payload, self)
  File "C:\Users\Egbert\git\tribler\Tribler\community\tunnel\community.py", line 802, in tunnel_data_to_end
    packet = TunnelConversion.encode_data(circuit.circuit_id, ultimate_destination, ('0.0.0.0', 0), data)
  File "C:\Users\Egbert\git\tribler\Tribler\community\tunnel\conversion.py", line 201, in encode_data
    return pack("!I4sH4sH", circuit_id, inet_aton(dest_address[0]), dest_address[1],
socket.error: illegal IP address string passed to inet_aton
```

In libtorrent we have set proxy_hostnames to True, which ensures that libtorrent will not attempt to resolve hostnames locally, but through the proxy. We need to adapt the tunneling protocol to support this.

**Comment by whirm** [comment]
I'm still getting those:
```
ERROR   1420566231.68       community:202   >>>>>>>> ('tracker.openbittorrent.com', 80)
ERROR   1420566231.68       community:1118  Dropping data packets while EXITing
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/community/tunnel/community.py", line 1116, in exit_data
    self.exit_sockets[circuit_id].sendto(data, destination)
  File "/var/data/feina/code/delft/tribler/Tribler/community/tunnel/community.py", line 200, in sendto
    self.transport.write(data, destination)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 284, in write
    "write() only accepts IP addresses, not hostnames")
InvalidAddressError
```

**Comment by egbertbouman** [comment]
@whirm The exit node still needs to resolve the hostname

**Comment by LipuFei** [comment]
@whirm I guess this should go to V6.5

**Comment by whirm** [comment]
Should this be taken care of by @rjruigrok too?

**Comment by whirm** [comment]
@rjruigrok is that fixed already?

**Comment by rjruigrok** [comment]
Nope, apparently not. Will have a look at it.

**Comment by whirm** [comment]
Great, thx!
