### ISSUE TITLE
ValueError in `query_http_uri`: Can redirect only to http or https

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7946]
```
Traceback (most recent call last):, 
  File "<relief>/core/components/restapi/rest/rest_manager.py", line 53, in error_middleware, 
  File "aiohttp/web_middlewares.py", line 117, in impl, 
  File "<relief>/core/components/libtorrent/restapi/torrentinfo_endpoint.py", line 102, in get_torrent_info, 
  File "<relief>/core/components/libtorrent/restapi/torrentinfo_endpoint.py", line 39, in query_http_uri, 
  File "aiohttp/client.py", line 624, in _request, 
ValueError: Can redirect only to http or https
```

[Here](https://github.com/Tribler/tribler/blob/0866177d73d121c7484c585754ee32f3980ae615/src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py#L102):
```python
    async def get_torrent_info(self, request):
        ...
            try:
                response = await query_http_uri(uri)
            except (ServerConnectionError, ClientResponseError, SSLError, ClientConnectorError, AsyncTimeoutError) as e:
                ...
```

`ValueError` should be added to the list of possible errors for `query_http_uri`

**Comment by kozlovsky** [comment]
Fixed in #7947
