### ISSUE TITLE
[7.13.3] CoreCrashedError on Linux with error code 4: Interrupted system call (Unterbrechung während des Betriebssystemaufrufs)

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7948]
```
tribler.gui.utilities.CreationTraceback: , 
  File "run_tribler.py", line 119, in <module>, 
  File "tribler/gui/start_gui.py", line 82, in run_gui, 
  File "tribler/gui/upgrade_manager.py", line 252, in on_worker_finished, 
  File "tribler/gui/utilities.py", line 439, in trackback_wrapper, 
  File "tribler/gui/core_manager.py", line 135, in start_tribler_core, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "tribler/gui/utilities.py", line 442, in trackback_wrapper, 
  File "tribler/gui/utilities.py", line 439, in trackback_wrapper, 
  File "tribler/gui/core_manager.py", line 315, in on_core_finished, 
tribler.gui.exceptions.CoreCrashedError: The Tribler core has unexpectedly finished with exit code 4 and status: 1., 
Error message: Unterbrechung während des Betriebssystemaufrufs
```

The Core process duration before the crash was 0:14:47, so the error wasn't during the Core startup.

What is the best way to handle this type of error?
Probably, GUI should just restart Core in case of such an error?

**Comment by qstokkink** [comment]
With the switch to a web-based GUI this issue should now be resolved.
