### ISSUE TITLE
Crash after restarting Tribler

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#8090]
Starting the second time after starting Tribler with a fresh `configuration.json`, Tribler keeps crashing.

```python
INFO:__main__:Run Tribler: {'torrent': '', 'log_level': 'INFO'}
INFO:__main__:Root state dir: /home/quinten/.Tribler
INFO:tribler.tribler_config:Load: /home/quinten/.Tribler/git/configuration.json.
INFO:__main__:Creating session. API port: 0. API key: 82a6982ee20521dcef29adbbea3adc65.
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1073, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection
    sock = await _connect_sock(
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 166, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 38165)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 137, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 102, in main
    server_url = await session.find_api_server()
  File "/home/quinten/Documents/tribler/src/tribler/core/session.py", line 182, in find_api_server
    if await _is_url_available(http_url):
  File "/home/quinten/Documents/tribler/src/tribler/core/session.py", line 83, in _is_url_available
    async with session.get(url, timeout=timeout):
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/quinten/Documents/tribler/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1088, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:38165 ssl:default [Connect call failed ('127.0.0.1', 38165)]

```

**Comment by qstokkink** [comment]
I found a workaround that doesn't require me to delete my configuration every time: setting `http_port_running` to `0` after shutting down Tribler.

**Comment by hbiyik** [comment]
@qstokkink 

i still get the same error from the git main branch.
i am running arch btw :)

```python
Traceback (most recent call last):
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 1073, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 122, in start_connection
    raise OSError(first_errno, msg)
ConnectionRefusedError: [Errno 111] Multiple exceptions: [Errno 111] Connect call failed ('::1', 5173, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5173)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/boogie/src/tribler/src/tribler/core/restapi/rest_manager.py", line 106, in error_middleware
    response = await handler(request)
  File "/home/boogie/src/tribler/src/tribler/core/restapi/rest_manager.py", line 161, in required_components_middleware
    return await handler(request)
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/home/boogie/src/tribler/src/tribler/core/restapi/webui_endpoint.py", line 36, in return_files
    async with self.session.get(f'http://localhost:5173/{path}') as response:
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/boogie/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 1088, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5173 ssl:default [Multiple exceptions: [Errno 111] Connect call failed ('::1', 5173, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5173)]
```

**Comment by qstokkink** [comment]
@hbiyik Thanks for testing! I want to revive Arch support in the next minor `8.1.x` releases (#6740, #6739), and also proper multiplatform releases in general (#8171, #5345, #5327) using GitHub Actions: I've been going through your `buildsys` repository again 🙂 Anyway, for now, disclaimer: Arch may be a bit of a rocky experience.

It looks like you didn't perform the `npm run build` step, step 3 of the [docs](https://tribler.readthedocs.io/en/latest/basics/running.html). Is that correct?

**Comment by hbiyik** [comment]
i hadnt done the npm build, but after building the ts still get the same error. May be i should just put some debugger in it.

PS: that buildsys should be quite irrelevant now but the ideas might in it might live on.

**Comment by qstokkink** [comment]
If you want to debug this, the following line looks for the `dist` folder and puts you in "developer" mode if it cannot be found:

https://github.com/Tribler/tribler/blob/417ce08d2df839a5eab560a234b745f4e556ec14/src/tribler/core/restapi/webui_endpoint.py#L28-L29

The `webui_root` is defined here:

https://github.com/Tribler/tribler/blob/6b1b6401fdc7431398ed839b528415dbcd833e84/src/tribler/__init__.py#L14

Normally, this should be looking for `src/tribler/ui/dist`. You could try using my `dist` (built for commit ca82531f22b73fcff0b5907ac1d3e08ca752878e) and putting it in that directory:

[dist.zip](https://github.com/user-attachments/files/17261583/dist.zip)
