### ISSUE TITLE
Error while opening version settings

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#8139]
I got this while opening the version settings. Apparently `task_manager` isn't actually a `TaskManager`:
```
Traceback (most recent call last):
  File "C:\Users\Egbert\Desktop\Git\tribler\src\tribler\core\restapi\rest_manager.py", line 106, in error_middleware
    response = await handler(request)
  File "C:\Users\Egbert\Desktop\Git\tribler\src\tribler\core\restapi\rest_manager.py", line 161, in required_components_middleware
    return await handler(request)
  File "C:\Python39\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Egbert\Desktop\Git\tribler\src\tribler\core\versioning\restapi\versioning_endpoint.py", line 137, in is_upgrading
    return RESTResponse({"running": request.context[0].task_manager.get_task("Upgrade") is not None})
AttributeError: 'VersioningComponent' object has no attribute 'get_task'
```

**Comment by qstokkink** [comment]
Is your IPv8 submodule up to date?

**Comment by qstokkink** [comment]
And/or are you importing `ipv8` from your site packages?

The latest release of IPv8 does not have `TaskManager.get_task()`.

**Comment by egbertbouman** [comment]
You're right, my bad. The submodule was updated and I didn't have IPv8 in `site-packages`, but somehow I still ended up using an old version :face_with_head_bandage:
