### ISSUE TITLE
Sanitize GigaChannel serialization errors

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#8160]
When connected to peers with an old GigaChannelCommunity, they will send messages like metadata type `CHANNEL_TORRENT (400)`. Tribler's response is to raise an exception:

https://github.com/Tribler/tribler/blob/898f54d1260263491264211eb903df65e83f83de/src/tribler/core/database/serialization.py#L71-L72

And then it handles it as follows:

https://github.com/Tribler/tribler/blob/0c76f48f2298c2f0de8cc66fe5d78d975ca04b50/src/tribler/core/database/store.py#L319-L321

In turn, Tribler prints a big stack trace.

```python
ERROR:MetadataStore:DB transaction error when tried to process compressed mdblob: UnknownBlobTypeException: 400
Traceback (most recent call last):
  File "src/tribler/core/database/store.py", line 317, in process_compressed_mdblob_threaded
    return await self.run_threaded(self.process_compressed_mdblob, compressed_data, **kwargs)
  File "src/tribler/core/database/store.py", line 310, in run_threaded
    return await get_running_loop().run_in_executor(None, wrapper)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "src/tribler/core/database/store.py", line 304, in wrapper
    return func(*args, **kwargs)
  File "src/tribler/core/database/store.py", line 344, in process_compressed_mdblob
    return self.process_squashed_mdblob(decompressed_data, health_info=health_info,
  File "src/tribler/core/database/store.py", line 390, in process_squashed_mdblob
    payload, offset = read_payload_with_offset(chunk_data, offset)
  File "src/tribler/core/database/serialization.py", line 72, in read_payload_with_offset
    raise UnknownBlobTypeException(metadata_type)
tribler.core.database.serialization.UnknownBlobTypeException: 400
```

This seems somewhat excessive for such a mundane log statement.

**Comment by qstokkink** [comment]
Hold on, this may be throwing out more than we would like:

https://github.com/Tribler/tribler/blob/0c76f48f2298c2f0de8cc66fe5d78d975ca04b50/src/tribler/core/database/store.py#L388-L392

If an exception happens in `read_payload_with_offset`, all other payloads in the list will also be discarded. This seems exceptionally wasteful.

**Comment by qstokkink** [comment]
We should probably revert to before https://github.com/Tribler/tribler/commit/e14bf2fd2f8e6b58c34f5ad45c310289b312ed8a#diff-53e24bbf8a59d2202c0c1393fa771407b3eacc514d5128f661be0133b483282e
