### ISSUE TITLE
Mac build fails to run after signing

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#8175]
Currently, our Mac build instantly exits when executing it:

```python
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libsodium.dylib, 0x0006): tried: '/usr/local/lib/libsodium.dylib' (code signature in <E66AE69B-7207-3EAA-B3E3-E8FAE32DE49E> '/usr/local/Cellar/libsodium/1.0.19/lib/libsodium.26.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/libsodium/1.0.19/lib/libsodium.26.dylib' (code signature in <E66AE69B-7207-3EAA-B3E3-E8FAE32DE49E> '/usr/local/Cellar/libsodium/1.0.19/lib/libsodium.26.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_tribler.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "tribler/core/session.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "ipv8/loader.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "ipv8/keyvault/crypto.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "ipv8/keyvault/private/libnaclkey.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "libnacl/__init__.py", line 87, in <module>
  File "libnacl/__init__.py", line 21, in _get_nacl
  File "ctypes/__init__.py", line 452, in LoadLibrary
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll '/usr/local/lib/libsodium.dylib'. Most likely this dynlib/dll was not found when the application was frozen.
[92093] Failed to execute script 'run_tribler' due to unhandled exception!
logout
```

**Comment by qstokkink** [comment]
We could try adding an entitlement to [disable library validation](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation):

```
<key>com.apple.security.cs.disable-library-validation</key>
<true/>
```

Of course, it would be better to actually have a signed version of the library.

**Comment by qstokkink** [comment]
Alright, I made [a branch](https://github.com/qstokkink/tribler/tree/add_mac_unsignedlib_entitlement) and it [successfully built](https://jenkins.tribler.org/job/Tribler/job/Build/job/Build-macOS/228/). Tomorrow, I'll check if it actually runs.

**Comment by qstokkink** [comment]
😲 it actually works.
