### ISSUE TITLE
Ubuntu 24.04: 8.0.1 : Namespace AppIndicator3 not available

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#8218]
When trying to start Tribler 8.0.1 on Ubuntu 24.04 it crashes with a segfault.
The offending lines are:
```
ValueError: Namespace AppIndicator3 not available
ValueError: Namespace AyatanaAppIndicator3 not available
```

 Here is the log:
```
╰─❯ cat /tmp/user-tribler-ZN1A2ReG.log
INFO:__main__:Run Tribler: {'torrent': '', 'log_level': 'INFO', 'server': False}
INFO:__main__:Root state dir: /home/user/.Tribler
INFO:tribler.tribler_config:Load: /home/user/.Tribler/8.0/configuration.json.
INFO:__main__:Creating session. API port: 0. API key: f64ea91348717d287cfda4999686ba6f.
INFO:RESTManager:Starting RESTManager...
INFO:RESTManager:Set security scheme and apply to all endpoints
INFO:RESTManager:Remove head
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/apispec/ext/marshmallow/openapi.py:135: UserWarning: Multiple schemas resolved to the name AddTrackerRequest. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/apispec/ext/marshmallow/openapi.py:135: UserWarning: Multiple schemas resolved to the name AddTrackerResponse. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/apispec/ext/marshmallow/openapi.py:135: UserWarning: Multiple schemas resolved to the name File. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/apispec/ext/marshmallow/openapi.py:135: UserWarning: Multiple schemas resolved to the name GetMetainfoResponse. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
INFO:RESTManager:Http enabled
INFO:RESTManager:Starting HTTP REST API server on port 0...
INFO:RESTManager:HTTP REST API server started on port 39441
INFO:RESTManager:Swagger docs: http://127.0.0.1:39441/docs
INFO:RESTManager:Swagger JSON: http://127.0.0.1:39441/docs/swagger.json
INFO:Socks5Server:Started SOCKS5 server on port 43493
INFO:Socks5Server:Started SOCKS5 server on port 46227
INFO:Socks5Server:Started SOCKS5 server on port 45105
INFO:Socks5Server:Started SOCKS5 server on port 35373
INFO:Socks5Server:Started SOCKS5 server on port 37501
INFO:tribler.core.libtorrent.download_manager.download_manager:Creating a session
INFO:tribler.core.libtorrent.download_manager.download_manager:Hops: 0.
INFO:tribler.core.libtorrent.download_manager.download_manager:Libtorrent port: 0
INFO:tribler.core.libtorrent.download_manager.download_manager:could not load libtorrent state, got exception: FileNotFoundError(2, 'Нет такого файла или каталога'). starting from scratch
INFO:tribler.core.libtorrent.download_manager.download_manager:Started libtorrent session for 0 hops on port 32867
INFO:IPv8CommunityLoader:Loading overlay <class 'abc.DatabaseComponent'>
INFO:IPv8CommunityLoader:Loading overlay <class 'ipv8.dht.discovery.DHTDiscoveryCommunity'>
INFO:DHTDiscoveryCommunity:DHT community initialized (peer mid b'eab4d13d45d6cb93b5d1bb265d7615ad629c7ea3')
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.knowledge.community.KnowledgeCommunity'>
INFO:KnowledgeCommunity:Knowledge community initialized
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.recommender.community.RecommenderCommunity'>
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.rendezvous.community.RendezvousCommunity'>
INFO:TrackerManager:No tracker blacklist file found at /home/user/.Tribler/8.0/tracker_blacklist.txt.
INFO:IPv8CommunityLoader:Loading overlay <class 'abc.TorrentCheckerComponent'>
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.tunnel.community.TriblerTunnelCommunity'>
INFO:TriblerTunnelCommunity:Exit settings: BT=False, IPv8=False
INFO:TriblerTunnelCommunity:Using DispatcherEndpoint with flags {8, 1}
INFO:IPv8CommunityLoader:Loading overlay <class 'abc.VersioningComponent'>
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.content_discovery.community.ContentDiscoveryCommunity'>
INFO:ContentDiscoveryCommunity:Content Discovery Community initialized (peer mid b'eab4d13d45d6cb93b5d1bb265d7615ad629c7ea3')
INFO:IPv8CommunityLoader:Finished loading communities!
INFO:DownloadManager:Load checkpoints...
INFO:DownloadManager:Checkpoints are loaded
ERROR:tribler.core.session:Uncaught exception: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/_appindicator.py", line 24, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/gi/__init__.py", line 122, in require_version
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
  File "src/tribler/run.py", line 209, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/runners.py", line 44, in run
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
  File "src/tribler/run.py", line 188, in main
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/__init__.py", line 64, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/__init__.py", line 56, in backend
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/__init__.py", line 28, in appindicator
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/_appindicator.py", line 27, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/gi/__init__.py", line 122, in require_version
ValueError: Namespace AyatanaAppIndicator3 not available
NoneType: None
FATAL: exception not rethrown
```

**Comment by qstokkink** [comment]
If my assumption at https://github.com/Tribler/tribler/issues/8217#issuecomment-2416522990 is correct, #8217 is the root cause of this issue.

**Comment by qstokkink** [comment]
Sorry about that. I forgot that was fixed in #8194 and is not part of 8.0.1 yet. In the next release this is fixed.
