### ISSUE TITLE
gtk-4.0 required for Tribler 8.0 on Ubuntu LTS 20.04.06

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#8242]
Install the rock-stable old Ubuntu LTS 20.04.06
Try to install Tribler V8.0.3

```Apollo Guidance Computer
sudo apt-get install ~/Downloads/tribler_8.0.3_aarch64.deb 
[sudo] password for tribleruser: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'tribler' instead of '/home/tribleruser/Downloads/tribler_8.0.3_aarch64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tribler : Depends: gir1.2-gtk-4.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by qstokkink** [comment]
First, I assume you need the `x64.deb` and not `aarch64.deb`. Second, could you try the following?

```
sudo dpkg -i ~/Downloads/tribler_8.0.3_x64.deb
sudo apt install gir1.2-gtk-3.0
tribler
```

**Comment by synctext** [comment]
GTK3 is not acceptable for Tribler8 :bug: 
```
sudo dpkg -i ~/Downloads/tribler_8.0.3_x64.deb 
[sudo] password for tribleruser: 
(Reading database ... 484243 files and directories currently installed.)
Preparing to unpack .../tribler_8.0.3_x64.deb ...
Unpacking tribler (8.0.3) over (7.14.0) ...
dpkg: dependency problems prevent configuration of tribler:
 tribler depends on gir1.2-gtk-4.0; however:
  Package gir1.2-gtk-4.0 is not installed.

dpkg: error processing package tribler (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 tribler
XPS13:~>sudo apt install gir1.2-gtk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-gtk-3.0 is already the newest version (3.24.20-0ubuntu1.2).
gir1.2-gtk-3.0 set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 tribler : Depends: gir1.2-gtk-4.0 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by qstokkink** [comment]
@synctext just to confirm: did you attempt to run Tribler (the third command)?

Explanation: what should happen in the first command is that `tribler` **is installed** but "unconfigured". However, in this state, you should be able to run `tribler` anyway. The `dpkg: error processing package tribler (--install): dependency problems - leaving unconfigured` is actually more of a warning than an error.

**Comment by synctext** [comment]
Nope, here is the log file:
```
********************************************************************************
A ImportError occurred
********************************************************************************
Traceback (most recent call last):
  File "src/tribler/run.py", line 61, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/PIL/Image.py", line 97, in <module>
ImportError: liblzma-c9407571.so.5.6.3: cannot open shared object file: No such file or directory

********************************************************************************
```

**Comment by qstokkink** [comment]
Good news! The patient died but the operation succeeded. This should be a one line fix.

**Comment by qstokkink** [comment]
@egbertbouman Do you have any ideas about what to do with the most recent traceback?

**Comment by egbertbouman** [comment]
It looks like `pystray` can't find any of the possible backends. I'm guessing that the last one it tries is the `xorg` backend, which fails the Xlib error. If that's the case, this error isn't really helpful.

**Comment by qstokkink** [comment]
That seems like a wild goose chase that I don't really have time for right now. I'll unassign myself.

**Comment by egbertbouman** [comment]
I wasn't having much luck solving the error while staying on `ubuntu-latest`, so I ended up building the .deb on `ubuntu-20.04` instead. This seems to have worked. I've tested the build on Ubuntu 20.04 & 24.04.

The build can be downloaded [here](https://github.com/egbertbouman/tribler/actions/runs/11728315439/artifacts/2159156329)

**Comment by synctext** [comment]
Tribler works again om my ancient laptop!
![Screenshot from 2024-11-11 16-43-07](https://github.com/user-attachments/assets/b25bd44f-aa08-4e5d-97f2-8c919e75ba76)
