### ISSUE TITLE
importing 7.14

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#8275]
Hi! I was using Tribler and THIS happened! :cry:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\events.py", line 80, in _run
  File "D:\a\tribler\tribler\pyipv8\ipv8\taskmanager.py", line 153, in done_cb
  File "D:\a\tribler\tribler\pyipv8\ipv8\taskmanager.py", line 28, in interval_runner
  File "D:\a\tribler\tribler\src\tribler\core\torrent_checker\torrent_checker.py", line 280, in check_local_torrents
  File "D:\a\tribler\tribler\src\tribler\core\torrent_checker\torrent_checker.py", line 280, in <listcomp>
  File "D:\a\tribler\tribler\src\tribler\core\torrent_checker\torrent_checker.py", line 343, in check_torrent_health
  File "D:\a\tribler\tribler\src\tribler\core\torrent_checker\torrent_checker.py", line 371, in create_session_for_request
TypeError: '>' not supported between instances of 'str' and 'int'

rE@http://127.0.0.1:55239/ui/assets/index.9ee516a5.js:80:336

```

**Comment by qstokkink** [comment]
This will be fixed* in the upcoming 8.0.5 version*. In the next version, you can remove the `.upgraded` and `configuration.json` files from your `.Tribler/8.0` directory and importing your old settings should work correctly.

The fix for this was part of #8273 and is not included in any release yet.
