### ISSUE TITLE
issue report

### ISSUE THREAD

**Issue by EMC2Gazua** [Tribler/tribler#8283]
Hi! I was using Tribler and THIS happened! :cry:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\events.py", line 80, in _run
  File "D:\a\tribler\tribler\pyipv8\ipv8\taskmanager.py", line 153, in done_cb
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\concurrent\futures\thread.py", line 58, in run
  File "D:\a\tribler\tribler\src\tribler\upgrade_script.py", line 370, in upgrade
  File "D:\a\tribler\tribler\src\tribler\upgrade_script.py", line 337, in _inject_7_14_tables
  File "D:\a\tribler\tribler\src\tribler\upgrade_script.py", line 298, in _inject_TorrentState_TrackerState
IndexError: list index out of range

Error: Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\events.py", line 80, in _run
  File "D:\a\tribler\tribler\pyipv8\ipv8\taskmanager.py", line 153, in done_cb
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\concurrent\futures\thread.py", line 58, in run
  File "D:\a\tribler\tribler\src\tribler\upgrade_script.py", line 370, in upgrade
  File "D:\a\tribler\tribler\src\tribler\upgrade_script.py", line 337, in _inject_7_14_tables
  File "D:\a\tribler\tribler\src\tribler\upgrade_script.py", line 298, in _inject_TorrentState_TrackerState
IndexError: list index out of range

    at EventSource.rE (http://127.0.0.1:10231/ui/assets/index.9ee516a5.js:80:336)
```

**Comment by qstokkink** [comment]
Thanks for reporting!

If I understand your issue correctly, the _temporary_ workaround for your issue would be to:
1. Search for anything (in the example screenshot below I searched for "ubuntu".
2. Click any of the orbs next to the seeders/leechers counts (I clicked a green orb pointed to by the red arrow) and wait for the check to complete.

After this, I believe the version import should work. Please let me know if that is not the case.

![](https://github.com/user-attachments/assets/b6e8ddbe-8515-4ed9-876e-0556d1efe313)

We'll make sure that the next Tribler version won't have this issue.
