### ISSUE TITLE
Tribler 8.0.5 on Debian x64 error while importing old settings: list index out of range

### ISSUE THREAD

**Issue by johannesvig** [Tribler/tribler#8285]
Hi! I was using Tribler and THIS happened! :cry:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/events.py", line 80, in _run
  File "/home/runner/work/tribler/tribler/pyipv8/ipv8/taskmanager.py", line 153, in done_cb
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 370, in upgrade
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 337, in _inject_7_14_tables
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 298, in _inject_TorrentState_TrackerState
IndexError: list index out of range

rE@http://127.0.0.1:45873/ui/assets/index.70dc79d9.js:80:336

```

**Comment by qstokkink** [comment]
Thanks for reporting! This issue was already reported in #8283. I posted a temporary workaround there, I hope it works for you: https://github.com/Tribler/tribler/issues/8283#issuecomment-2507759382.

We'll try to get a fix out ASAP. However, in order not to discuss the same issue in multiple issues, I'll close this one.
