### ISSUE TITLE
Tribler WebUI not loading

### ISSUE THREAD

**Issue by davidgordiienko** [Tribler/tribler#8289]
I'm on Tribler 8.0.5 on Ubuntu using Firefox. Whenever I click on the Tribler app icon, it opens in the web browser. Previously, it was loading, but now for some reason it comes up blank and never finishes loading. I also get a popup from some program called xmessage saying that the database is locked.

**Comment by davidgordiienko** [comment]
I also have another issue where sometimes it loads but says failed to connect to Tribler

**Comment by qstokkink** [comment]
I tried to reproduce this by running multiple processes and by changing the permissions on my database file, but I can't reproduce this.

After running Tribler, could you run the following command and provide us with the output?

```
cat /tmp/*-tribler-*.log
```

There should be a `Traceback` in there that provides us more information on how Tribler crashed. For example, when using a read-only database:

```python
Traceback (most recent call last):
  File "/home/runner/work/tribler/tribler/pyipv8/ipv8/taskmanager.py", line 153, in done_cb
  File "/home/runner/work/tribler/tribler/src/tribler/core/content_discovery/community.py", line 181, in on_torrents_health
  File "<string>", line 2, in process_torrents_health
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 538, in new_func
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/utils/utils.py", line 88, in reraise
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 519, in new_func
  File "/home/runner/work/tribler/tribler/src/tribler/core/content_discovery/community.py", line 196, in process_torrents_health
  File "/home/runner/work/tribler/tribler/src/tribler/core/database/store.py", line 358, in process_torrent_health
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 4017, in get_for_update
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 4114, in _find_one_
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 4173, in _find_in_db_
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 938, in _exec_sql
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 1805, in prepare_connection_for_query_execution
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 1891, in flush
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 5424, in _save_
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 5281, in _save_created_
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/utils/utils.py", line 99, in throw
pony.orm.core.UnexpectedError: Object TorrentState[new:602] cannot be stored in the database. OperationalError: attempt to write a readonly database
```

**Comment by qstokkink** [comment]
Thanks for the info. I think I ran into exactly your issue then while stress testing my fix for #8283.

**Comment by qstokkink** [comment]
@mbennette68 the browser will be our primary user interface, at least for a while. If you also have the issue of a blank screen, please let me know.

**Comment by mbennette68** [comment]
> @mbennette68 the browser will be our primary user interface, at least for a while. If you also have the issue of a blank screen, please let me know.

Hello,

Thank you for the feedback.  I don't have a black screen issue though I've reverted back to v7.14.0 as I don't trust the browser interacting with a torrent client, at least not on this PC. 

That being said, may I ask if using the browser as main interface will be temporary until all bugs are fixed? 

Thank you,':)

**Comment by qstokkink** [comment]
> That being said, may I ask if using the browser as main interface will be temporary until all bugs are fixed?

Yes and no. Once we've weeded out most of the bugs, we can start looking at packaging standalone GUIs again. So, technically, I could say it's "temporary" BUT this can take quite a while, perhaps more than a year and maybe even longer.
