### ISSUE TITLE
ValueError when importing data from a previous version

### ISSUE THREAD

**Issue by im-vmn** [Tribler/tribler#8308]
**Traceback and/or steps to reproduce:**

1. Update Tribler to the latest version (8.05) with .deb package from https://www.tribler.org/
2. Run new version
3. Try to import data from 7.14

```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/events.py", line 80, in _run
  File "/home/runner/work/tribler/tribler/pyipv8/ipv8/taskmanager.py", line 153, in done_cb
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 353, in upgrade
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 82, in _import_7_14_settings
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 49, in _copy_if_exists
ValueError: invalid literal for int() with base 10: '36600.0'
```

**Comment by qstokkink** [comment]
Thanks for reporting!  We'll get that fixed in the next version.

_[dev stuff]_ This should be a conversion to `float` not to `int`:

https://github.com/Tribler/tribler/blob/b3837b2ca40b94687b3b45a5b4f45a397db59d93/src/tribler/tribler_config.py#L85
