### ISSUE TITLE
Unable to import old torrent files from tribler v7.1.4 to v8.0.6

### ISSUE THREAD

**Issue by lpastyle** [Tribler/tribler#8320]
Hi! I was using Tribler and THIS happened! :cry:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/dbapiprovider.py", line 55, in wrap_dbapi_exceptions
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/dbproviders/sqlite.py", line 392, in set_transaction_mode
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/events.py", line 80, in _run
  File "/home/runner/work/tribler/tribler/pyipv8/ipv8/taskmanager.py", line 153, in done_cb
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 402, in upgrade
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 367, in _inject_7_14_tables
  File "/home/runner/work/tribler/tribler/src/tribler/upgrade_script.py", line 230, in _inject_ChannelNode
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 870, in execute
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 882, in _exec_raw_sql
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 938, in _exec_sql
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 1800, in prepare_connection_for_query_execution
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/core.py", line 1768, in connect
  File "<string>", line 2, in set_transaction_mode
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pony/orm/dbapiprovider.py", line 72, in wrap_dbapi_exceptions
pony.orm.dbapiprovider.OperationalError: database is locked

n_@http://127.0.0.1:37803/ui/assets/index.9844966d.js:76:336

```

**Comment by lpastyle** [comment]
Issue occured on
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"

**Comment by qstokkink** [comment]
Thanks for reporting! We'll try to get this fixed.

_[dev stuff]_ It appears the `rollback()` of the database after a `database is locked` error, is itself causing a `database is locked` error. Instead of manually rolling back, we could also just set `@db_session(retry=...)`, surround the entire thing with an exception handler and only log on error. Perhaps we should also look at `optimistic=False` and `serializable=True`?
