### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by zticky** [Tribler/tribler#8330]
Hi! I was using Tribler and THIS happened! :cry:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\events.py", line 80, in _run
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\tasks.py", line 674, in cancel
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\tasks.py", line 674, in cancel
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\tasks.py", line 674, in cancel
  [Previous line repeated 491 more times]
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\tasks.py", line 670, in cancel
RecursionError: maximum recursion depth exceeded while calling a Python object

rE@http://127.0.0.1:57786/ui/assets/index.9ee516a5.js:80:336

```

**Comment by qstokkink** [comment]
Thanks for reporting! I see we already have an issue open for this, in #8322. I'll close this issue to keep the discussion in one place. We'll try to get this resolved as soon as possible.
