### ISSUE TITLE
ConnectionResetError when connected to unstable Wi-Fi

### ISSUE THREAD

**Issue by teddyrogers** [Tribler/tribler#8355]
Tribler 8.0.7, I have noticed when there is a connection issue a red error appears at the top of the WebGUI 

![image](https://github.com/user-attachments/assets/bcf8be38-ac2f-4cc0-8cf1-0b41630566e8)

```
Tribler encountered an error! What do you want to do?

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\events.py", line 80, in _run
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\asyncio\selector_events.py", line 115, in _read_from_self
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

n_@http://127.0.0.1:61260/ui/assets/index.8a64a9d4.js:76:336
```

It seems to be consistent, is there a better way for Tribler to detect and handle dropped connections?

**Comment by qstokkink** [comment]
Thanks for the report! This should not be happening. Could you tell us how you consistently trigger this? Does this happen when shutting down Tribler?

**Comment by teddyrogers** [comment]
@qstokkink if you need more info or for me to complete some tests please let me know.
