### ISSUE TITLE
Test got a PydeadObject exception but didn't fail

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#845]
Known objects that have this `PyDeadObject` Problem:
- [x] SaveAs (fixed by #970)
- [ ] AddTorrent
- [ ] MainFrame
- [ ] ListBody
- [ ] TorrentDetails
- [ ] ActivitiesList

```
11:57:55 [-] [wrap_in_vnc.sh run_n...] ERR: test_save_dialog (Tribler.Test.test_gui_dialogs.TestGuiDialogs) ... tgs: waiting for session instance
11:57:56 [-] [wrap_in_vnc.sh run_n...] ERR: test_as_server: condition satisfied after 1 seconds, calling callback '<lambda>'
11:57:56 [-] [wrap_in_vnc.sh run_n...] ERR: tgs: found instance, staring to wait for lm to be initcomplete
11:57:56 [-] [wrap_in_vnc.sh run_n...] ERR: test_as_server: condition satisfied after 0 seconds, calling callback 'wait_for_guiutility'
11:57:56 [-] [wrap_in_vnc.sh run_n...] ERR: tgs: waiting for guiutility instance
11:57:56 [-] [wrap_in_vnc.sh run_n...] ERR: test_as_server: condition satisfied after 0 seconds, calling callback 'wait_for_init'
11:57:56 [-] [wrap_in_vnc.sh run_n...] ERR: tgs: lm initcomplete, staring to wait for GUIUtility to be ready
11:57:56 [-] [wrap_in_vnc.sh run_n...] ERR: GUI started
11:57:57 [-] [wrap_in_vnc.sh run_n...] ERR: GUI ready
11:57:57 [-] [wrap_in_vnc.sh run_n...] ERR: test_as_server: condition satisfied after 0 seconds, calling callback 'wait_for_frame'
11:57:57 [-] [wrap_in_vnc.sh run_n...] ERR: tgs: GUIUtility ready, staring to wait for frame to be ready
11:57:57 [-] [wrap_in_vnc.sh run_n...] ERR: test_as_server: condition satisfied after 0 seconds, calling callback 'call_callback'
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR: Traceback (most recent call last):
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py", line 1358, in Notify
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR:     self.notify()
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14767, in Notify
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR:     self.result = self.callable(*self.args, **self.kwargs)
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Test/test_gui_dialogs.py", line 88, in <lambda>
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR:     self.Call(2, lambda: add_dialog.EndModal(wx.ID_CANCEL))
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14615, in __getattr__
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR:     raise PyDeadObjectError(self.attrStr % self._name)
11:58:04 [-] [wrap_in_vnc.sh run_n...] ERR: wx._core.PyDeadObjectError: The C++ part of the AddTorrent object has been deleted, attribute access no longer allowed.
11:58:05 [-] [wrap_in_vnc.sh run_n...] ERR: GUI closing
11:58:05 [-] [wrap_in_vnc.sh run_n...] ERR: GUI closed
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR: Unhandled error in Deferred:
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR: Unhandled Error
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR: Traceback (most recent call last):
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     self.mainLoop()
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     self.runUntilCurrent()
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     call.func(*call.args, **call.kw)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 218, in __call__
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     d = defer.maybeDeferred(self.f, *self.a, **self.kw)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR: --- <exception caught here> ---
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     result = f(*args, **kw)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/community.py", line 1191, in take_step
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     self.create_introduction_request(candidate, self.dispersy_enable_bloom_filter_sync)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/community/search/community.py", line 225, in create_introduction_request
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     myPreferences = sorted(self._mypref_db.getMyPrefListInfohash(limit=500))
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 1747, in getMyPrefListInfohash
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     res = self._db.fetchall(sql)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/util.py", line 43, in helper
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     return func(*args, **kargs)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2296, in fetchall
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     return SQLiteCacheDBV5.fetchall(self, sql, args)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 574, in fetchall
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     res = self.execute_read(sql, args)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 485, in execute_read
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     return self._execute(sql, args)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/dispersy/util.py", line 43, in helper
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     return func(*args, **kargs)
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 2300, in _execute
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     cur = self.getCursor()
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Core/CacheDB/sqlitecachedb.py", line 197, in getCursor
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR:     assert self.cursor_table != None
11:58:08 [-] [wrap_in_vnc.sh run_n...] ERR: exceptions.AssertionError:
11:58:09 [-] [wrap_in_vnc.sh run_n...] ERR: ONEXIT deleting instances
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Number of threads still running 8
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Thread still running MainThread daemon False instance: <_MainThread(MainThread, started 140367452333824)>
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Thread still running Thread-1 daemon True instance: <Thread(Thread-1, started daemon 140367128377088)>
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Thread still running PoolThread-twisted.internet.reactor-5 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-5, started daemon 140365520672512)>
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Thread still running PoolThread-twisted.internet.reactor-4 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-4, started daemon 140365529065216)>
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Thread still running PoolThread-twisted.internet.reactor-3 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-3, started daemon 140365159982848)>
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Thread still running PoolThread-twisted.internet.reactor-1 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-1, started daemon 140365571028736)>
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Thread still running PoolThread-twisted.internet.reactor-6 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-6, started daemon 140365168375552)>
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: Thread still running PoolThread-twisted.internet.reactor-2 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-2, started daemon 140365537457920)>
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: content of pymdht.log
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: 2014-09-10 11:57:56,634 CRITICAL minitwisted.py:100 - run2()
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: run
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: teardown: finished printing content of pymdht.log
11:58:15 [-] [wrap_in_vnc.sh run_n...] ERR: ok
```

Full log:
http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/2752/consoleFull

**Comment by lfdversluis** [comment]
@whirm I think this can be closed, but `MainFrame` and `Listbody` were fixed right?

**Comment by whirm** [comment]
Do we still have any pydeadobject error at all left?

**Comment by whirm** [comment]
@devos50 ^

**Comment by devos50** [comment]
Haven't seen any PyDeadObjectErrors recently. iirc we had indeed fixed them a while ago.

**Comment by lfdversluis** [comment]
@devos50 Yes I have fixed the Dialog race condition segfault thingy months ago and the listbody and artworkpanel a few weeks ago.

**Comment by whirm** [comment]
I though so :) :tada:
