### ISSUE TITLE
socket.sendto() Invalid parameter in TunnelCommunity

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#952]
Got the backtrace from http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/3006

```
Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/community/tunnel/community.py", line 1109, in exit_data
    self.exit_sockets[circuit_id].sendto(data, destination)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/community/tunnel/community.py", line 198, in sendto
    self.transport.write(data, destination)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 271, in write
    return self.socket.sendto(datagram, addr)
error: [Errno 22] Invalid argument
```

**Comment by synctext** [comment]
Got this again when running V6.4.0 for almost 3 weeks on my Ubuntu box. Fixed in V6.4.1 ?

```
ERROR   1418979352.59       community:617   Could not remove relay 3290279600 no activity
ERROR   1418979353.76       community:853   Don't know how to decrypt incoming message for circuit_id 1377147404
ERROR   1418979355.85       community:1112  Dropping data packets while EXITing
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 1110, in exit_data
    self.exit_sockets[circuit_id].sendto(data, destination)
  File "/usr/share/tribler/Tribler/community/tunnel/community.py", line 198, in sendto
    self.transport.write(data, destination)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 271, in write
    return self.socket.sendto(datagram, addr)
error: [Errno 22] Invalid argument
ERROR   1418979362.59       community:617   Could not remove relay 670744770 no activity
ERROR   1418979367.59       community:617   Could not remove relay 4118921637 no activity
ERROR   1418979372.58       community:617   Could not remove relay 3430112127 no activity
```

**Comment by whirm** [comment]
@synctext It should. Could you see if it works for you too?

**Comment by synctext** [comment]
Still happening on current Next branch
commit: 385dfb1ddbace2bf964d5bfe5fe7fc7a005a2cc7
```
ERROR   1420644596.38       community:618   Could not remove relay 2453034024 no activity
ERROR   1420644611.38       community:618   Could not remove relay 1405835282 no activity
ERROR   1420644626.38       community:618   Could not remove relay 2851575279 no activity
ERROR   1420644661.38       community:618   Could not remove relay 3400979831 no activity
ERROR   1420644664.55       community:1113  Dropping data packets while EXITing
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 1111, in exit_data
    self.exit_sockets[circuit_id].sendto(data, destination)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/tunnel/community.py", line 199, in sendto
    self.transport.write(data, destination)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 271, in write
    return self.socket.sendto(datagram, addr)
error: [Errno 22] Invalid argument
ERROR   1420644671.39       community:618   Could not remove relay 276085091 no activity
ERROR   1420644719.14       community:854   Don't know how to decrypt incoming message for circuit_id 1334814537
ERROR   1420644727.99       community:854   Don't know how to decrypt incoming message for circuit_id 3890524595
ERROR   1420644781.38       community:618   Could not remove relay 1221675467 no activity
ERROR   1420644796.38       community:618   Could not remove relay 766621800 no activity
```

**Comment by synctext** [comment]
Elric suspects it's a datagram-too-short problem.
We'll do a more meaningful error, instead of this TraceBack.

**Comment by whirm** [comment]
Turns out it's not a payload length issue. We will be showing more info when this happens the next time.

**Comment by whirm** [comment]
This will be fixed when we get to refactor the Session class. See: https://github.com/Tribler/tribler/issues/1070

**Comment by whirm** [comment]
@rjruigrok did you check the issues you got assigned? I think several could be closed now.
