### ISSUE TITLE
Dispersy: exceptions.IndexError: string index out of range

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#958]
```
ERROR   1418227895.19       community:610   TunnelCommunity: removing relay 4198770084 no activity
ERROR   1418227895.19       community:610   TunnelCommunity: removing relay 3641179580 no activity
ERROR   1418227895.19       community:617   TunnelCommunity: could not remove relay 3641179580 no activity
ERROR   1418227896.17             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/endpoint.py", line 184, in dispersythread_data_came_in
    timestamp)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1452, in on_incoming_packets
    for community_id, iterator in groupby(sorted(packets, key=sort_key), key=groupby_key):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1450, in <lambda>
    sort_key = lambda tup: (tup[1][2:22], tup[1][1], 0 if tup[1][22] == chr(248) else tup[1][22])  # community ID, community version, message meta type
exceptions.IndexError: string index out of range

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/endpoint.py", line 184, in dispersythread_data_came_in
    timestamp)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1452, in on_incoming_packets
    for community_id, iterator in groupby(sorted(packets, key=sort_key), key=groupby_key):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1450, in <lambda>
    sort_key = lambda tup: (tup[1][2:22], tup[1][1], 0 if tup[1][22] == chr(248) else tup[1][22])  # community ID, community version, message meta type
exceptions.IndexError: string index out of range
```

**Comment by synctext** [comment]
Nope not seen recently.
