### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'download_file'

### ISSUE THREAD

**Issue by rjruigrok** [Tribler/tribler#987]
This error appeared (once) on closing Tribler

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rob/git/tribler/Tribler/Core/Utilities/twisted_thread.py", line 21, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/rob/git/tribler/Tribler/Core/RemoteTorrentHandler.py", line 570, in _do_request
    self._session.lm.tftp_handler.download_file(file_name, ip, port, extra_info=extra_info,
exceptions.AttributeError: 'NoneType' object has no attribute 'download_file'

**Comment by LipuFei** [comment]
Fixed with #1128
