### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'on_success'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#991]
Another RC1 error:
```
ERROR   1418622875.43       community:853   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622875.44       community:996   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622875.51       community:996   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622875.53       community:996   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622875.54       community:996   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622876.06       community:996   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622877.02       community:996   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622877.06        dispersy:1724  exception during handle_callback for pong
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/usr/share/tribler/Tribler/dispersy/discovery/community.py", line 691, in on_pong
    if request.on_success(message.candidate):
AttributeError: 'NoneType' object has no attribute 'on_success'
ERROR   1418622877.73       community:996   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622878.30       community:996   Don't know how to decrypt incoming message for circuit_id 2643081376
ERROR   1418622878.47         handler:394   TFTP[22160 C 131.180.224.100:7759][d92f19147dcc681306d3dae9216eb1e0a0150b44.torrent] got ERROR message: code = 1, msg = File not found
ERROR   1418622884.10       community:610   TunnelCommunity: removing relay 1834757198 no activity
ERROR   1418622884.10       community:610   TunnelCommunity: removing relay 3764965223 no activity
ERROR   1418622884.10       community:617   TunnelCommunity: could not remove relay 3764965223 no activity
```

**Comment by whirm** [comment]
This totally looks like a different stacktrace for the same issue as https://github.com/Tribler/tribler/issues/985

**Comment by whirm** [comment]
@synctext do you remember if you where running in optimized mode or not?

**Comment by whirm** [comment]
@synctext Nevermind we found the cause.

**Comment by whirm** [comment]
This will fix the issue: https://github.com/Tribler/dispersy/pull/394

**Comment by synctext** [comment]
Running the default ```./tribler.sh``` (seems -O is NOT used)

Seeing this error again.
Niels had issues with the previous fix it seems: https://github.com/Tribler/dispersy/pull/394#commitcomment-10214280

```
ERROR   1436256347.52       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436256347.52       community:2577  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436258831.41        dispersy:1724  exception during handle_callback for pong
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/discovery/community.py", line 742, in on_pong
    if request.on_success(message.candidate):
AttributeError: 'NoneType' object has no attribute 'on_success'
ERROR   1436259577.41       community:2866  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436259577.41       community:2866  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
ERROR   1436259577.41       community:2866  already seen this indentifier in this batch, previous candidate {192.168.0.27:7759 24.69.63.0:7759} this one {192.168.0.27:7759 24.69.63.0:7759}
```

**Comment by whirm** [comment]
@synctext  that already got reverted. 
I'll add a check on the discovery community.
